import { KNOWLEDGE_SCHEMA_V03 } from '../../knowledge/schema/executable-schema.ts'
import type { KnowledgeClaimV03, KnowledgeEntityV03, KnowledgeRelationV03, KnowledgeSourceV03 } from '../../knowledge/schema/domain.ts'
import type { KnowledgeChangeSetV03, KnowledgeOperationV03, KnowledgeSourceOperationV03 } from '../../knowledge/schema/mutation.ts'
import { hashKnowledgeObject } from '../../knowledge/storage/canonical-hash.ts'
import { KnowledgeIndexV03 } from '../../knowledge/query/index.ts'
import { allocateClaimId, allocateEntityId, allocateRelationId, allocateSourceId } from './id-helpers.ts'
import type { ClaimCandidate, EntityCandidate, RelationCandidate, ReportMap, ResolvedCandidateGroup } from '../../skills/knowledge-curation/contracts.ts'
import type { KnowledgeAssetCollectionV03 } from '../../knowledge/storage/v03-types.ts'
import type { AcceptedExtractionPlan, ReviewItem } from './contracts.ts'
import { type EntityBinding, type ResolutionIntent, resolveResolutionIntentBarrier } from './knowledge-resolution.ts'
import { categoryForRationale, plannerReviewKey } from './review-telemetry.ts'

type Dict = Record<string, unknown>
export interface EntityResolution { readonly candidateId: string; readonly status: 'existing' | 'created' | 'review' | 'rejected'; readonly canonicalId?: string; readonly plannedRef?: string; readonly rationale: string }
export interface ChangeSetPlanningInput {
  readonly knowledgeBaseId: string; readonly baseRevision: number; readonly workflowRunId: string; readonly rawRef: string
  readonly rawManifest: { readonly originalFilename: string | null; readonly suppliedMetadata: { readonly title: string | null; readonly institution: string | null; readonly author: string | null; readonly publishedAt: string | null; readonly sourceUrl: string | null } }
  readonly documentId: string; readonly document: { readonly metadata: { readonly originalFilename: string | null; readonly title?: string | null } }
  readonly reportMap: ReportMap; readonly plan: AcceptedExtractionPlan; readonly groups: readonly ResolvedCandidateGroup[]
  readonly intents: readonly ResolutionIntent[]; readonly bindings: ReadonlyMap<string, EntityBinding>; readonly assets: KnowledgeAssetCollectionV03
  readonly resolutionReviews?: readonly ReviewItem[]; readonly consolidationReviews?: readonly { readonly candidateId: string; readonly reason: string; readonly conflictingFields: readonly string[] }[]
}
export interface ChangeSetPlanningResult { readonly changeSet?: KnowledgeChangeSetV03; readonly reviewItems: readonly ReviewItem[]; readonly safeOperationCount: number; readonly summary: Readonly<Record<string, number>>; readonly entityResolutions: readonly EntityResolution[]; readonly blocked?: boolean; readonly errors?: readonly string[] }

function record(value: unknown): value is Dict { return typeof value === 'object' && value !== null && !Array.isArray(value) }
function unique(values: readonly string[]): string[] { return [...new Set(values)].sort() }
function sourceType(value: string | undefined): KnowledgeSourceV03['sourceType'] { return KNOWLEDGE_SCHEMA_V03.source.types.includes(value as never) ? value as KnowledgeSourceV03['sourceType'] : 'unknown' }
function reliability(value: string | undefined): KnowledgeSourceV03['sourceReliability'] { return KNOWLEDGE_SCHEMA_V03.source.reliabilities.includes(value as never) ? value as KnowledgeSourceV03['sourceReliability'] : 'unknown' }
function norm(value: unknown): string { return typeof value === 'string' ? value.trim().toLocaleLowerCase().replace(/\s+/g, ' ') : '' }
function blockLocator(plan: AcceptedExtractionPlan, refs: readonly string[]): string | null { const primary = new Set(plan.units.flatMap((unit) => unit.primaryBlockIds)); return [...refs].sort().find((ref) => primary.has(ref)) ?? [...refs].sort()[0] ?? null }
function operationId(prefix: string, sequence: number): string { return `${prefix}-${String(sequence).padStart(3, '0')}` }
function allowedAttributes(type: string): Dict | undefined { return (KNOWLEDGE_SCHEMA_V03.relation.definitions[type as keyof typeof KNOWLEDGE_SCHEMA_V03.relation.definitions] as { attributes?: Dict } | undefined)?.attributes }
function validFinancialContribution(value: unknown): boolean { if (value === null) return true; if (!record(value)) return false; const fields = new Set(['period', 'revenueAmount', 'revenueShare', 'profitAmount', 'profitShare', 'currency', 'separatelyReported']); for (const [key, item] of Object.entries(value)) { if (!fields.has(key)) return false; if (['revenueShare', 'profitShare'].includes(key) && item !== null && (typeof item !== 'number' || !Number.isFinite(item) || item < 0 || item > 1)) return false; if (['revenueAmount', 'profitAmount'].includes(key) && item !== null && (typeof item !== 'number' || !Number.isFinite(item))) return false; if (key === 'period' && item !== null && typeof item !== 'string') return false; if (key === 'currency' && item !== null && typeof item !== 'string') return false; if (key === 'separatelyReported' && item !== null && typeof item !== 'boolean') return false } return true }
function validAttributes(type: string, attributes: unknown): boolean { if (attributes === undefined) return true; if (!record(attributes)) return false; const rules = allowedAttributes(type); for (const [key, value] of Object.entries(attributes)) { const rule = rules?.[key]; if (rule === undefined) return false; if (type === 'business_exposure' && key === 'financialContribution' && !validFinancialContribution(value)) return false; if (Array.isArray(rule) && !rule.includes(value as never)) return false; if (rule === 'number_0_to_1_or_null' && value !== null && (typeof value !== 'number' || !Number.isFinite(value) || value < 0 || value > 1)) return false } return true }
function makeEntity(candidate: EntityCandidate, id: string): KnowledgeEntityV03 { const value: Dict = { id, type: candidate.entityType, name: candidate.name, aliases: unique(candidate.aliases ?? []), description: candidate.description ?? null, lifecycle: { status: 'active' } }; const fields = candidate.semanticFields ?? {}; if (candidate.entityType === 'company') for (const key of ['ticker', 'exchange', 'legalName']) if (fields[key] !== undefined) value[key] = fields[key]; if (candidate.confidence !== undefined) value.metadata = { extractionConfidence: candidate.confidence }; return value as unknown as KnowledgeEntityV03 }
function patchEntity(existing: KnowledgeEntityV03, candidate: EntityCandidate): KnowledgeEntityV03 { const value = structuredClone(existing) as unknown as Dict; value.aliases = unique([...(Array.isArray(value.aliases) ? value.aliases.filter((item): item is string => typeof item === 'string') : []), ...(candidate.aliases ?? []), ...(norm(candidate.name) !== norm(existing.name) ? [candidate.name] : [])]); if (candidate.description !== undefined && candidate.description !== null && (existing.description === undefined || existing.description === null)) value.description = candidate.description; if (candidate.entityType === 'company') for (const key of ['ticker', 'exchange', 'legalName']) if (candidate.semanticFields?.[key] !== undefined && (existing as unknown as Dict)[key] === undefined || candidate.semanticFields?.[key] !== undefined && (existing as unknown as Dict)[key] === null) value[key] = candidate.semanticFields[key]; return value as unknown as KnowledgeEntityV03 }
function makeRelation(candidate: RelationCandidate, id: string, sourceRef: string, targetRef: string, sourceId: string): KnowledgeRelationV03 { const value: Dict = { id, type: candidate.relationType, sourceRef, targetRef, sourceRefs: [sourceId], lifecycle: { status: 'active' } }; if (candidate.attributes !== undefined && Object.keys(candidate.attributes).length > 0) value.attributes = structuredClone(candidate.attributes); if (candidate.confidence !== undefined) value.confidence = candidate.confidence; return value as unknown as KnowledgeRelationV03 }
function patchRelation(existing: KnowledgeRelationV03, candidate: RelationCandidate, sourceId: string, replaceState = false): KnowledgeRelationV03 { const value = structuredClone(existing) as unknown as Dict; const current = record(value.attributes) ? value.attributes : {}; value.attributes = replaceState ? structuredClone(candidate.attributes ?? {}) : { ...current, ...(candidate.attributes ?? {}) }; value.sourceRefs = unique([...(Array.isArray(value.sourceRefs) ? value.sourceRefs.filter((item): item is string => typeof item === 'string') : []), sourceId]); return value as unknown as KnowledgeRelationV03 }
function makeClaim(input: ChangeSetPlanningInput, candidate: ClaimCandidate, id: string, subjects: readonly string[], sourceId: string, supersedes?: string): KnowledgeClaimV03 { const value: Dict = { id, claimType: candidate.claimType, statement: candidate.statement, subjectRefs: unique(subjects), primarySubjectRef: subjects[0], sourceRefs: [sourceId], provenance: candidate.evidenceBlockRefs.map((ref) => ({ sourceRef: sourceId, rawRef: input.rawRef, locator: blockLocator(input.plan, [ref]), chunkRef: null })), lifecycle: { status: 'active' } }; if (supersedes !== undefined) value.supersedes = [supersedes]; if (candidate.temporal !== undefined && candidate.temporal !== null) value.temporal = structuredClone(candidate.temporal); if (candidate.structuredValue !== undefined && candidate.structuredValue !== null) value.structuredValue = structuredClone(candidate.structuredValue); if (candidate.confidence !== undefined) value.confidence = candidate.confidence; return value as unknown as KnowledgeClaimV03 }
function patchClaim(input: ChangeSetPlanningInput, existing: KnowledgeClaimV03, candidate: ClaimCandidate, sourceId: string): KnowledgeClaimV03 { const value = structuredClone(existing) as unknown as Dict; value.sourceRefs = unique([...(Array.isArray(value.sourceRefs) ? value.sourceRefs.filter((item): item is string => typeof item === 'string') : []), sourceId]); const provenance = Array.isArray(value.provenance) ? value.provenance.filter(record) : []; const seen = new Set(provenance.map((item) => hashKnowledgeObject(item))); for (const ref of candidate.evidenceBlockRefs) { const anchor = { sourceRef: sourceId, rawRef: input.rawRef, locator: blockLocator(input.plan, [ref]), chunkRef: null }; const key = hashKnowledgeObject(anchor); if (!seen.has(key)) { provenance.push(anchor); seen.add(key) } } value.provenance = provenance; return value as unknown as KnowledgeClaimV03 }
function addReview(reviews: Map<string, ReviewItem>, group: ResolvedCandidateGroup, rationale: string, dependency = false, refs: readonly string[] = [], stage = 'knowledge_resolution'): void { const category = categoryForRationale(rationale); const reviewKey = plannerReviewKey(group.candidateId, stage, category, rationale, dependency); if (!reviews.has(reviewKey)) reviews.set(reviewKey, { candidateId: group.candidateId, kind: group.kind, rationale, dependentCandidateIds: unique(refs), stage, category, origin: dependency ? 'dependency_isolation' : 'knowledge_resolution', dependency, reviewKey }) }

export function planKnowledgeChangeSet(input: ChangeSetPlanningInput): ChangeSetPlanningResult {
  const index = KnowledgeIndexV03.fromAssets(input.assets); const groups = new Map(input.groups.map((group) => [group.candidateId, group])); const intents = new Map(input.intents.map((item) => [item.candidateRef, item])); const barrier = resolveResolutionIntentBarrier(input.groups, input.intents, input.bindings)
  const reviews = new Map<string, ReviewItem>((input.resolutionReviews ?? []).map((item) => [item.reviewKey ?? `${item.candidateId}|${item.rationale}`, item])); for (const constraint of input.consolidationReviews ?? []) { const group = groups.get(constraint.candidateId); if (group) addReview(reviews, group, constraint.reason, false, [], 'consolidation') }
  if (!barrier.valid) return { reviewItems: [...reviews.values()], safeOperationCount: 0, summary: { sourceOperations: 0, knowledgeCreates: 0, reviewItems: reviews.size, blockedDependencies: 0, noChanges: 1 }, entityResolutions: [], blocked: true, errors: barrier.errors }
  const plannedEntityIds = new Map<string, string>(); const entityResolutions: EntityResolution[] = []; const knowledgeOperations: KnowledgeOperationV03[] = []; let sequence = 1
  const sourceId = allocateSourceId({ sourceUrl: input.rawManifest.suppliedMetadata.sourceUrl, publishedAt: input.rawManifest.suppliedMetadata.publishedAt, title: input.rawManifest.suppliedMetadata.title ?? input.document.metadata.title ?? input.rawManifest.originalFilename, rawRef: input.rawRef })
  const resolveEntityRef = (candidateId: string): string | undefined => { const binding = input.bindings.get(candidateId); if (!binding) return undefined; return binding.ref ?? (binding.plannedRef === undefined ? undefined : plannedEntityIds.get(binding.plannedRef) ?? binding.plannedRef) }
  for (const group of input.groups.filter((item) => item.kind === 'entity').sort((a, b) => a.candidateId.localeCompare(b.candidateId))) {
    const item = intents.get(group.candidateId)!; const candidate = group.candidate as EntityCandidate; const binding = input.bindings.get(group.candidateId)
    if (item.disposition === 'review') { entityResolutions.push({ candidateId: group.candidateId, status: 'review', rationale: item.semanticBasis.rationale }); continue }
    if (item.disposition === 'reject') { entityResolutions.push({ candidateId: group.candidateId, status: 'rejected', rationale: item.semanticBasis.rationale }); continue }
    if (binding?.state === 'PlannedNew' && item.disposition === 'create') { const id = allocateEntityId(candidate.entityType, candidate.name); if (index.entities.has(id) || plannedEntityIds.has(binding.plannedRef ?? '') || knowledgeOperations.some((operation) => operation.type === 'create' && operation.object.id === id)) { addReview(reviews, group, 'Planned Entity durable ID collides with existing or planned state'); entityResolutions.push({ candidateId: group.candidateId, status: 'review', rationale: 'Planned Entity durable ID collision' }) } else { plannedEntityIds.set(binding.plannedRef!, id); knowledgeOperations.push({ operationId: operationId('entity-create', sequence++), type: 'create', object: makeEntity(candidate, id) }); entityResolutions.push({ candidateId: group.candidateId, status: 'created', canonicalId: id, plannedRef: binding.plannedRef, rationale: item.semanticBasis.rationale }) } continue }
    const target = item.targetRef ?? binding?.ref; const existing = target === undefined ? undefined : index.entities.get(target)
    if (!existing) { addReview(reviews, group, 'BoundExisting Entity target is not infrastructure-owned or no longer exists'); entityResolutions.push({ candidateId: group.candidateId, status: 'review', rationale: 'Missing canonical Entity target' }); continue }
    if (item.disposition === 'enrich_existing') knowledgeOperations.push({ operationId: operationId('entity-update', sequence++), type: 'update', knowledgeId: existing.id, expectedBeforeHash: hashKnowledgeObject(existing), object: patchEntity(existing, candidate) }); entityResolutions.push({ candidateId: group.candidateId, status: 'existing', canonicalId: existing.id, rationale: item.semanticBasis.rationale })
  }
  for (const group of input.groups.filter((item) => item.kind === 'relation').sort((a, b) => a.candidateId.localeCompare(b.candidateId))) {
    const item = intents.get(group.candidateId)!; const candidate = group.candidate as RelationCandidate; if (item.disposition === 'review' || item.disposition === 'reject' || item.disposition === 'no_op') continue
    const sourceRef = resolveEntityRef(candidate.source.candidateRef); const targetRef = resolveEntityRef(candidate.target.candidateRef); if (!sourceRef || !targetRef || sourceRef.startsWith('planned-entity-') || targetRef.startsWith('planned-entity-')) { addReview(reviews, group, 'Relation endpoint planned reference was not resolved before ChangeSet planning'); continue }
    if (!validAttributes(candidate.relationType, candidate.attributes)) { addReview(reviews, group, 'Relation attributes are not Schema 0.3 valid'); continue }
    const symmetric = candidate.relationType === 'competes_with' || candidate.relationType === 'substitutes_for'; const left = symmetric ? [sourceRef, targetRef].sort() : [sourceRef, targetRef]; const matches = [...index.relations.values()].filter((relation) => { const endpoints = symmetric ? [relation.sourceRef, relation.targetRef].sort() : [relation.sourceRef, relation.targetRef]; return relation.type === candidate.relationType && endpoints[0] === left[0] && endpoints[1] === left[1] && (relation.lifecycle.status === undefined || relation.lifecycle.status === 'active') })
    if (matches.length > 1) { addReview(reviews, group, 'Multiple canonical Relations share the resolved identity'); continue }
    if (item.disposition === 'create') { const id = allocateRelationId(candidate.relationType, sourceRef, targetRef, candidate.attributes ?? {}); if (index.relations.has(id) || knowledgeOperations.some((operation) => operation.type === 'create' && operation.object.id === id)) addReview(reviews, group, 'Deterministic Relation ID already exists'); else knowledgeOperations.push({ operationId: operationId('relation-create', sequence++), type: 'create', object: makeRelation(candidate, id, sourceRef, targetRef, sourceId) }); continue }
    const existing = matches[0]; if (!existing) { addReview(reviews, group, 'ResolutionIntent requires an existing Relation target'); continue }
    if (item.disposition === 'merge_evidence') { if (!Array.isArray(existing.sourceRefs)) addReview(reviews, group, 'Relation target does not support sourceRefs'); else knowledgeOperations.push({ operationId: operationId('relation-source-merge', sequence++), type: 'merge_source', knowledgeId: existing.id, expectedBeforeHash: hashKnowledgeObject(existing), addSourceRefs: [sourceId] }) }
    else if (item.disposition === 'enrich_existing' || item.disposition === 'replace_state') knowledgeOperations.push({ operationId: operationId('relation-update', sequence++), type: 'update', knowledgeId: existing.id, expectedBeforeHash: hashKnowledgeObject(existing), object: patchRelation(existing, candidate, sourceId, item.disposition === 'replace_state') })
  }
  for (const group of input.groups.filter((item) => item.kind === 'claim').sort((a, b) => a.candidateId.localeCompare(b.candidateId))) {
    const item = intents.get(group.candidateId)!; const candidate = group.candidate as ClaimCandidate; if (item.disposition === 'review' || item.disposition === 'reject' || item.disposition === 'no_op') continue
    const subjects = candidate.subjectRefs.map((subject) => resolveEntityRef(subject.candidateRef)); if (subjects.some((value) => value === undefined || value.startsWith('planned-entity-'))) { addReview(reviews, group, 'Claim subject planned reference was not resolved before ChangeSet planning'); continue }
    const subjectRefs = subjects as string[]; const existing = item.targetRef === undefined ? undefined : index.claims.get(item.targetRef)
    if (item.disposition === 'create') { const id = allocateClaimId({ claimType: candidate.claimType, statement: norm(candidate.statement), subjectRefs: unique(subjectRefs), temporal: candidate.temporal ?? null, structuredValue: candidate.structuredValue ?? null, discriminator: item.semanticBasis.outcome === 'coexists' || item.semanticBasis.outcome === 'contradicts' ? { workflowRunId: input.workflowRunId, candidateId: group.candidateId } : undefined }); if (index.claims.has(id) || knowledgeOperations.some((operation) => operation.type === 'create' && operation.object.id === id)) addReview(reviews, group, 'Deterministic Claim ID already exists'); else knowledgeOperations.push({ operationId: operationId('claim-create', sequence++), type: 'create', object: makeClaim(input, candidate, id, subjectRefs, sourceId) }); continue }
    if (!existing) { addReview(reviews, group, 'ResolutionIntent requires an existing Claim target'); continue }
    if (item.disposition === 'merge_evidence' || item.disposition === 'enrich_existing') knowledgeOperations.push({ operationId: operationId('claim-update', sequence++), type: 'update', knowledgeId: existing.id, expectedBeforeHash: hashKnowledgeObject(existing), object: patchClaim(input, existing, candidate, sourceId) })
    else if (item.disposition === 'supersede') { const id = allocateClaimId({ claimType: candidate.claimType, statement: candidate.statement, subjectRefs: unique(subjectRefs), temporal: candidate.temporal ?? null, structuredValue: candidate.structuredValue ?? null, discriminator: { supersedes: existing.id } }); knowledgeOperations.push({ operationId: operationId('claim-supersede', sequence++), type: 'supersede', knowledgeId: existing.id, expectedBeforeHash: hashKnowledgeObject(existing), replacement: makeClaim(input, candidate, id, subjectRefs, sourceId, existing.id) }) }
  }
  const reviewItems = [...reviews.values()].sort((a, b) => (a.reviewKey ?? '').localeCompare(b.reviewKey ?? ''))
  if (knowledgeOperations.length === 0) return { reviewItems, safeOperationCount: 0, summary: { sourceOperations: 0, knowledgeCreates: 0, reviewItems: reviewItems.length, blockedDependencies: reviewItems.filter((item) => item.dependency).length, noChanges: 1 }, entityResolutions }
  const source: KnowledgeSourceV03 = { id: sourceId as KnowledgeSourceV03['id'], title: input.rawManifest.suppliedMetadata.title ?? input.document.metadata.title ?? input.rawManifest.originalFilename ?? input.documentId, sourceType: sourceType(input.reportMap.sourceAssessment.sourceType), institution: input.rawManifest.suppliedMetadata.institution, author: input.rawManifest.suppliedMetadata.author, publishedAt: input.rawManifest.suppliedMetadata.publishedAt, url: input.rawManifest.suppliedMetadata.sourceUrl, sourceReliability: reliability(input.reportMap.sourceAssessment.reliability), rawRefs: [input.rawRef as KnowledgeSourceV03['rawRefs'] extends (infer T)[] ? T : never], metadata: { workflowRunId: input.workflowRunId, documentId: input.documentId }, lifecycle: { status: 'active' } }
  const existingSource = index.sources.get(sourceId); const sourceOperations: KnowledgeSourceOperationV03[] = existingSource ? [{ operationId: 'source-merge-001', type: 'source_merge', sourceId, expectedBeforeHash: hashKnowledgeObject(existingSource), addRawRefs: [input.rawRef] }] : [{ operationId: 'source-create-001', type: 'source_create', source }]
  const changeSetId = `changeset-${hashKnowledgeObject({ workflowRunId: input.workflowRunId, knowledgeBaseId: input.knowledgeBaseId, rawRef: input.rawRef, documentId: input.documentId, groups: input.groups, intents: input.intents }).slice(7, 23)}`
  const changeSet: KnowledgeChangeSetV03 = { changeSetId, workflowRunId: input.workflowRunId, knowledgeBaseId: input.knowledgeBaseId, schemaVersion: '0.3', storageFormatVersion: '1', expectedBaseRevision: input.baseRevision, requiresRawProvenance: true, sourceOperations, knowledgeOperations, ingestionContext: { documentId: input.documentId, rawRef: input.rawRef, extractionUnitCount: input.plan.units.length } }
  return { changeSet, reviewItems, safeOperationCount: sourceOperations.length + knowledgeOperations.length, summary: { sourceOperations: sourceOperations.length, knowledgeCreates: knowledgeOperations.filter((operation) => operation.type === 'create').length, reviewItems: reviewItems.length, blockedDependencies: reviewItems.filter((item) => item.dependency).length }, entityResolutions }
}
