import assert from 'node:assert/strict'
import test from 'node:test'
import { mkdtemp, readFile, rm } from 'node:fs/promises'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { readResearchReport, writeResearchReport, type ResearchReport } from '../../../app/services/research-report.ts'

test('ResearchReport writes Markdown plus validated metadata', async () => { const root = await mkdtemp(join(tmpdir(), 'researchhub-report-')); try { const report: ResearchReport = { reportId: 'report-test', reportType: 'company_research', subjectRefs: ['entity:company-test'], generatedAt: '2026-09-08T00:00:00.000Z', asOf: '2026-09-08T00:00:00.000Z', workflowRunId: 'run-test', knowledgeBaseRevision: 1, sourceRefs: ['source:test'], claimRefs: ['claim:test'], methodology: 'fixture', sections: [{ id: 'overview', title: 'Company Overview', markdown: 'Evidence-backed overview.', sourceRefs: ['source:test'], claimRefs: ['claim:test'] }], outputPath: 'report-test.md' }; const output = await writeResearchReport(report, root); assert.match(await readFile(output, 'utf8'), /Company Overview/); assert.equal((await readResearchReport(`${output}.json`)).reportId, 'report-test') } finally { await rm(root, { recursive: true, force: true }) } })

test('ResearchReport accepts event_research and renders the product title', async () => { const root = await mkdtemp(join(tmpdir(), 'researchhub-event-report-')); try { const report: ResearchReport = { reportId: 'event-report-test', reportType: 'event_research', subjectRefs: ['entity:company-test'], generatedAt: '2026-09-08T00:00:00.000Z', asOf: '2026-09-08T00:00:00.000Z', workflowRunId: 'event-run-test', knowledgeBaseRevision: 1, sourceRefs: [], claimRefs: [], methodology: 'bounded event fixture', sections: [{ id: 'event-summary', title: 'Event Summary', markdown: 'Event-backed summary.' }], outputPath: 'event-report-test.md' }; const output = await writeResearchReport(report, root); assert.match(await readFile(output, 'utf8'), /^# Event Research/m); assert.equal((await readResearchReport(`${output}.json`)).reportType, 'event_research') } finally { await rm(root, { recursive: true, force: true }) } })

test('ResearchReport accepts industry_research, renders title, and preserves relation provenance', async () => { const root = await mkdtemp(join(tmpdir(), 'researchhub-industry-report-')); try { const report: ResearchReport = { reportId: 'industry-report-test', reportType: 'industry_research', subjectRefs: ['entity:industry-test'], generatedAt: '2026-09-08T00:00:00.000Z', asOf: '2026-09-08T00:00:00.000Z', workflowRunId: 'industry-run-test', knowledgeBaseRevision: 2, sourceRefs: ['source:s'], claimRefs: ['claim:c'], methodology: 'fixture', sections: [{ id: 's1', title: 'Industry Scope & Definition', markdown: 'Industry-backed.', sourceRefs: ['source:s'], claimRefs: ['claim:c'], relationRefs: ['relation:r'] }], outputPath: 'industry-report-test.md' }; const output = await writeResearchReport(report, root); assert.match(await readFile(output, 'utf8'), /^# Industry Research/m); const loaded = await readResearchReport(`${output}.json`); assert.deepEqual(loaded.sections[0]?.relationRefs, ['relation:r']); assert.equal(loaded.sections.length, 1) } finally { await rm(root, { recursive: true, force: true }) } })
