import assert from 'node:assert/strict'
import test from 'node:test'
import { mkdtemp, rm } from 'node:fs/promises'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { createFreshKnowledgeBaseV04 } from '../../../knowledge/storage/create-v04.ts'
import { ResearchService } from '../../../app/services/research-service.ts'
import { WorkflowService } from '../../../app/services/workflow-service.ts'
import type { ResearchAcquisitionPlugin } from '../../../plugins/research-acquisition/contracts.ts'

test('Application Service exposes research_company through one Workflow path', async () => { const root = await mkdtemp(join(tmpdir(), 'researchhub-service-kb-')); const reports = await mkdtemp(join(tmpdir(), 'researchhub-service-reports-')); try { await createFreshKnowledgeBaseV04(root, { knowledgeBaseId: 'kb-service' }); const plugin: ResearchAcquisitionPlugin = { name: 'fixture-official', discover: async () => [], fetch: async (candidate) => ({ candidate, retrievedAt: new Date().toISOString(), content: '' }), normalize: async (source) => ({ candidate: source.candidate, retrievedAt: source.retrievedAt, title: source.candidate.title, content: source.content, contentHash: 'a'.repeat(64), publisher: source.candidate.provider, rights: { accessScope: 'public', retentionAllowed: true, aiProcessingAllowed: true, derivativeKnowledgeAllowed: true, redistributionAllowed: false } }) }; const workflowService = new WorkflowService(); const service = new ResearchService({ mountedKnowledgeBaseRoot: root, reportRoot: reports, acquisitionPlugins: [plugin], workflowService }); const started = service.startResearchCompany({ workflowRunId: 'service-run', symbol: '600519' }); const result = await started.completion; assert.equal(result.status, 'completed'); assert.equal(workflowService.getWorkflowStatus('service-run')?.status, 'completed'); assert.match(result.reportId ?? '', /600519/); assert.equal((await service.getResearchReport(result.reportId!)).reportId, result.reportId) } finally { await rm(root, { recursive: true, force: true }); await rm(reports, { recursive: true, force: true }) } })

test('Application Service exposes event_research with telemetry and provider outcome mapping', async () => { const root = await mkdtemp(join(tmpdir(), 'researchhub-event-service-kb-')); const reports = await mkdtemp(join(tmpdir(), 'researchhub-event-service-reports-')); try { await createFreshKnowledgeBaseV04(root, { knowledgeBaseId: 'kb-event-service' }); const workflowService = new WorkflowService(); const service = new ResearchService({ mountedKnowledgeBaseRoot: root, reportRoot: reports, acquisitionPlugins: [], workflowService }); const started = service.startEventResearch({ workflowRunId: 'event-service-run', symbol: '600519', anchor: { kind: 'user_event', title: 'Fixture event', description: 'A bounded fixture event.' } }); assert.equal(workflowService.getWorkflowStatus(started.runId)?.workflowType, 'event_research'); const result = await started.completion; assert.equal(result.status, 'blocked'); assert.equal(result.telemetry !== undefined, true); assert.deepEqual(result.providerOutcome, []); assert.equal(result.reportId, undefined); assert.equal(result.reportPath, undefined) } finally { await rm(root, { recursive: true, force: true }); await rm(reports, { recursive: true, force: true }) } })

test('Industry Service rejects a missing ReasoningExecutor before Workflow registration', async () => { const root = await mkdtemp(join(tmpdir(), 'researchhub-industry-missing-executor-')); const reports = await mkdtemp(join(tmpdir(), 'researchhub-industry-missing-reports-')); try { await createFreshKnowledgeBaseV04(root, { knowledgeBaseId: 'kb-industry-missing-executor' }); const workflowService = new WorkflowService(); const service = new ResearchService({ mountedKnowledgeBaseRoot: root, reportRoot: reports, acquisitionPlugins: [], workflowService }); assert.throws(() => service.startIndustryResearch({ workflowRunId: 'industry-missing-executor', name: 'PCB' }), /ReasoningExecutor/); assert.equal(workflowService.getWorkflowStatus('industry-missing-executor'), undefined) } finally { await rm(root, { recursive: true, force: true }); await rm(reports, { recursive: true, force: true }) } })

test('Company Research never invokes an Industry-only provider', async () => { const root = await mkdtemp(join(tmpdir(), 'researchhub-company-industry-seam-')); const reports = await mkdtemp(join(tmpdir(), 'researchhub-company-industry-seam-reports-')); let calls = 0; try { await createFreshKnowledgeBaseV04(root, { knowledgeBaseId: 'kb-company-industry-seam' }); const industryOnly: ResearchAcquisitionPlugin = { name: 'industry-only-fixture', discover: async () => { calls++; return [] }, fetch: async (candidate) => ({ candidate, retrievedAt: '2026-09-13T00:00:00.000Z', content: '' }), normalize: async (source) => ({ candidate: source.candidate, retrievedAt: source.retrievedAt, title: source.candidate.title, content: source.content, contentHash: 'a'.repeat(64), publisher: 'fixture', rights: { accessScope: 'public', retentionAllowed: true, aiProcessingAllowed: true, derivativeKnowledgeAllowed: true, redistributionAllowed: false } }) }; const service = new ResearchService({ mountedKnowledgeBaseRoot: root, reportRoot: reports, acquisitionPlugins: [], industryAcquisitionPlugins: [industryOnly], workflowService: new WorkflowService() }); await service.startResearchCompany({ workflowRunId: 'company-industry-seam', symbol: '600519' }).completion; assert.equal(calls, 0) } finally { await rm(root, { recursive: true, force: true }); await rm(reports, { recursive: true, force: true }) } })
