import { sha256 } from '../research-acquisition/hash.ts'
import { DocumentInputResolver } from '../document/input-resolver.ts'
import type { ResearchAcquisitionPlugin, ResearchAcquisitionRequest, ResearchFetchedSource, ResearchSourceCandidate, NormalizedResearchSource } from '../research-acquisition/contracts.ts'

export interface WebResearchAcquisitionOptions { readonly provider: string; readonly urls: readonly string[]; readonly tier?: 1 | 2 | 3 | 4 | 5; readonly kind?: 'news' | 'rss' | 'web_article'; readonly fetchImpl?: typeof fetch; readonly now?: () => string; readonly accountRef?: string; readonly discoveryUrl?: string; readonly scope?: 'company' | 'broad' }
/** Bounded public acquisition. A homepage is identity/reference only and never becomes a signal. */
export class WebResearchAcquisition implements ResearchAcquisitionPlugin {
  readonly name: string; readonly dailyScope: 'company' | 'broad'; private readonly fetchImpl: typeof fetch; private readonly now: () => string; private readonly resolver = new DocumentInputResolver()
  constructor(private readonly options: WebResearchAcquisitionOptions) { this.name = `web-research-${options.provider}`; this.dailyScope = options.scope ?? 'company'; this.fetchImpl = options.fetchImpl ?? fetch; this.now = options.now ?? (() => new Date().toISOString()) }
  async discover(request: ResearchAcquisitionRequest): Promise<readonly ResearchSourceCandidate[]> {
    const result: ResearchSourceCandidate[] = []
    for (const configured of this.options.urls.slice(0, 10)) { const response = await this.fetchImpl(this.options.discoveryUrl ?? configured, { headers: { accept: 'text/html, application/rss+xml, application/atom+xml, text/plain' } }); if (!response.ok) throw new Error(`${this.options.provider} discovery failed with HTTP ${response.status}`); const bytes = new Uint8Array(await response.arrayBuffer()); const raw = new TextDecoder().decode(bytes); const items = extractItems(raw, configured, response.headers.get('content-type') ?? '')
      for (const item of items.slice(0, request.limitPerKind ?? 5)) {
        const companySymbol = request.company?.symbol
        const metadata = { ...(this.options.accountRef ? { sourceAccountRef: this.options.accountRef } : {}), ...(this.dailyScope === 'company' && companySymbol !== undefined ? { companySymbol } : {}), providerObjectId: item.objectId ?? sha256(`${item.title}|${item.url ?? ''}`), acquisitionMode: 'public_item_discovery' }
        result.push({ candidateId: `${this.options.provider}-${sha256(item.url ?? item.title).slice(0, 16)}`, kind: this.options.kind ?? 'web_article', tier: this.options.tier ?? 3, title: item.title, ...(item.url ? { url: item.url } : {}), provider: this.options.provider, ...(item.publishedAt ? { publishedAt: item.publishedAt } : {}), metadata })
      }
    }
    return result
  }
  async fetch(candidate: ResearchSourceCandidate): Promise<ResearchFetchedSource> { if (!candidate.url) throw new Error('public source candidate has no URL'); const response = await this.fetchImpl(candidate.url, { headers: { accept: 'text/html, application/pdf, text/plain' } }); if (!response.ok) throw new Error(`${this.options.provider} item fetch failed with HTTP ${response.status}`); const rawBytes = new Uint8Array(await response.arrayBuffer()); const content = new TextDecoder().decode(rawBytes); return { candidate, retrievedAt: this.now(), content, rawBytes, mediaType: response.headers.get('content-type')?.split(';')[0] ?? 'text/html', contentType: response.headers.get('content-type') ?? undefined, contentHash: sha256(content) } }
  async normalize(source: ResearchFetchedSource): Promise<NormalizedResearchSource> { const bytes = source.rawBytes ?? new TextEncoder().encode(source.content); const document = await this.resolver.parse({ bytes, filename: source.mediaType === 'application/pdf' ? 'source.pdf' : 'source.html', mediaType: source.mediaType ?? source.contentType ?? 'text/html' }); return { candidate: source.candidate, retrievedAt: source.retrievedAt, title: source.candidate.title, content: document.normalizedText, canonicalUrl: source.candidate.url, contentHash: source.contentHash ?? sha256(source.content), rawBytes: Uint8Array.from(bytes), publisher: this.options.provider, rights: { accessScope: 'public', retentionAllowed: true, aiProcessingAllowed: true, derivativeKnowledgeAllowed: true, redistributionAllowed: false } } }
}
export class PublicInstitutionalViewAcquisition extends WebResearchAcquisition { constructor(options: Omit<WebResearchAcquisitionOptions, 'kind'>) { super({ ...options, kind: 'web_article', scope: options.scope ?? 'broad' }) } }
export class CommunitySignalAcquisition extends WebResearchAcquisition { constructor(options: Omit<WebResearchAcquisitionOptions, 'kind'>) { super({ ...options, kind: 'web_article', scope: options.scope ?? 'company' }); if (/xueqiu/i.test(options.provider) && !options.discoveryUrl) throw new Error('authentication_required: Xueqiu public feed requires an authenticated public endpoint') } }
interface DiscoveredItem { title: string; url?: string; publishedAt?: string; objectId?: string }
function extractItems(raw: string, base: string, contentType: string): DiscoveredItem[] { const items: DiscoveredItem[] = []; for (const match of raw.matchAll(/<(?:item|entry)\b[^>]*>([\s\S]*?)<\/(?:item|entry)>/gi)) { const body = match[1] ?? ''; const title = tag(body, 'title'); const url = tag(body, 'link') || /<link\b[^>]*href=["']([^"']+)/i.exec(body)?.[1]; const date = tag(body, 'pubDate') || tag(body, 'published') || tag(body, 'updated'); if (title && url) items.push({ title, url: absolute(url, base), publishedAt: isoDate(date) }) } for (const match of raw.matchAll(/<article\b[^>]*[\s\S]*?<\/article>/gi)) { const body = match[0]; const url = /<a\b[^>]*href=["']([^"']+)/i.exec(body)?.[1]; const title = tag(body, 'h1') || tag(body, 'h2') || tag(body, 'h3') || meta(body, 'og:title'); const date = meta(body, 'article:published_time') || /<(?:time|span)\b[^>]*(?:datetime|data-date)=["']([^"']+)/i.exec(body)?.[1]; if (title && url) items.push({ title, url: absolute(url, base), publishedAt: isoDate(date), objectId: /data-(?:id|post-id|thread-id)=["']([^"']+)/i.exec(body)?.[1] }) } if (!items.length && /json|javascript/i.test(contentType)) for (const match of raw.matchAll(/"(?:url|link)"\s*:\s*"(https?:\\?\/\\?\/[^"\\]+)"[\s\S]{0,800}?"(?:title|name)"\s*:\s*"([^"]+)"/gi)) items.push({ url: match[1]!.replace(/\\\//g, '/'), title: match[2]!.replace(/\\"/g, '"') }); return items.filter((item, index) => item.url && item.title && items.findIndex((candidate) => candidate.url === item.url) === index) }
function tag(value: string, name: string): string | undefined { const m = new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`, 'i').exec(value); return m?.[1]?.replace(/<!\[CDATA\[|\]\]>/g, '').replace(/<[^>]+>/g, ' ').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/\s+/g, ' ').trim() || undefined }
function meta(value: string, property: string): string | undefined { return new RegExp(`<meta[^>]+(?:property|name)=["']${property}["'][^>]+content=["']([^"']+)`, 'i').exec(value)?.[1] }
function absolute(value: string, base: string): string { try { return new URL(value, base).toString() } catch { return value } }
function isoDate(value: string | undefined): string | undefined { if (!value) return undefined; const date = new Date(value); return Number.isNaN(date.getTime()) ? undefined : date.toISOString() }
