import { sha256 } from '../research-acquisition/hash.ts'
import type { AkshareDataClient } from '../research-acquisition/akshare.ts'
import type { ResearchAcquisitionPlugin, ResearchAcquisitionRequest, ResearchFetchedSource, ResearchSourceCandidate, NormalizedResearchSource } from '../research-acquisition/contracts.ts'

export class AkshareDailyMarketAcquisition implements ResearchAcquisitionPlugin {
  readonly name = 'akshare-daily-market-acquisition'; readonly dailyScope = 'broad' as const
  constructor(private readonly client: AkshareDataClient, private readonly now: () => string = () => new Date().toISOString()) {}
  async discover(request: ResearchAcquisitionRequest): Promise<readonly ResearchSourceCandidate[]> { const endpoints = request.company.symbol === 'BROAD_SCOPE' ? ['000001', '399001', '399006', '000688', 'sector'] : [request.company.symbol]; return endpoints.map((symbol) => ({ candidateId: `akshare-${sha256(`${symbol}|${request.asOf ?? ''}`).slice(0, 16)}`, kind: 'structured_data', tier: 2, title: `AKShare market ${symbol}`, provider: 'akshare', metadata: { endpoint: symbol, dataKind: symbol === 'sector' ? 'sector-performance' : 'index-daily' } })) }
  async fetch(candidate: ResearchSourceCandidate): Promise<ResearchFetchedSource> { const symbol = String(candidate.metadata?.endpoint ?? '000001'); const value = symbol === 'sector' ? await this.client.sectorPerformance?.({ symbol }) : await this.client.indexDaily?.({ symbol }); if (value === undefined) throw new Error('AKShare market endpoint unavailable'); const content = JSON.stringify(value); return { candidate, retrievedAt: this.now(), content, rawBytes: new TextEncoder().encode(content), mediaType: 'application/json', contentType: 'application/json', contentHash: sha256(content) } }
  async normalize(source: ResearchFetchedSource): Promise<NormalizedResearchSource> { return { candidate: source.candidate, retrievedAt: source.retrievedAt, title: source.candidate.title, content: source.content, canonicalUrl: undefined, contentHash: source.contentHash ?? sha256(source.content), rawBytes: source.rawBytes, publisher: 'akshare', rights: { accessScope: 'public', retentionAllowed: true, aiProcessingAllowed: true, derivativeKnowledgeAllowed: true, redistributionAllowed: false } } }
}
