import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import type { DailyBriefType } from './contracts.ts'
import { TradingCalendarService } from './calendar.ts'
export interface DailySchedulerState { readonly lastSuccessfulRun?: Readonly<Partial<Record<DailyBriefType, string>>>; readonly lastCheckedAt?: string }
export interface DailyBriefSchedulerOptions { readonly statePath: string; readonly calendar: TradingCalendarService; readonly now?: () => string; readonly morningDue?: string; readonly eveningDue?: string; readonly run: (type: DailyBriefType, tradeDate: string, forceRefresh?: boolean) => Promise<{ readonly status: string }> }
/** China-local due scheduler. Date-only tick is retained as a deterministic compatibility/test hook. */
export class DailyBriefScheduler {
  constructor(private readonly options: DailyBriefSchedulerOptions) {}
  async tick(value: string | Date): Promise<readonly { readonly briefType: DailyBriefType; readonly status: string }[]> { const explicitDate = typeof value === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(value); const current = explicitDate ? `${value}T23:59:59+08:00` : value instanceof Date ? value.toISOString() : value; const tradeDate = explicitDate ? value as string : chinaDate(current); const localMinutes = explicitDate ? 24 * 60 : chinaMinutes(current); const state = await this.read(); const checked = { ...state, lastCheckedAt: new Date().toISOString() }; const day = await this.options.calendar.isTradingDay(tradeDate); if (!day.isTradingDay) { await this.write(checked); return [] } const due: DailyBriefType[] = explicitDate ? ['morning', 'evening'] : [ ...(localMinutes >= toMinutes(this.options.morningDue ?? '08:00') ? ['morning' as const] : []), ...(localMinutes >= toMinutes(this.options.eveningDue ?? '20:30') ? ['evening' as const] : []) ]; const output: Array<{ briefType: DailyBriefType; status: string }> = []; let next = checked; for (const type of due) { if (next.lastSuccessfulRun?.[type] === tradeDate) continue; const result = await this.options.run(type, tradeDate); output.push({ briefType: type, status: result.status }); if (result.status === 'completed' || result.status === 'already_completed') { next = { ...next, lastSuccessfulRun: { ...(next.lastSuccessfulRun ?? {}), [type]: tradeDate } }; await this.write(next) } } if (output.length === 0) await this.write(next); return output }
  private async read(): Promise<DailySchedulerState> { try { return JSON.parse(await readFile(resolve(this.options.statePath), 'utf8')) as DailySchedulerState } catch (error) { if ((error as NodeJS.ErrnoException).code === 'ENOENT') return {}; throw error } }
  private async write(state: DailySchedulerState): Promise<void> { const path = resolve(this.options.statePath); await mkdir(dirname(path), { recursive: true }); const temp = `${path}.${process.pid}.tmp`; await writeFile(temp, `${JSON.stringify(state, null, 2)}\n`, 'utf8'); const { rename } = await import('node:fs/promises'); await rename(temp, path) }
}
function chinaDate(value: string): string { return new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Shanghai', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date(value)) }
function chinaMinutes(value: string): number { const parts = new Intl.DateTimeFormat('en-GB', { timeZone: 'Asia/Shanghai', hour: '2-digit', minute: '2-digit', hour12: false }).formatToParts(new Date(value)); return Number(parts.find((item) => item.type === 'hour')?.value ?? 0) * 60 + Number(parts.find((item) => item.type === 'minute')?.value ?? 0) }
function toMinutes(value: string): number { const [hour, minute] = value.split(':').map(Number); return hour * 60 + minute }
