import { sha256 } from './hash.ts'
import { DocumentInputResolver } from '../document/input-resolver.ts'
import type { NormalizedResearchSource, ResearchAcquisitionPlugin, ResearchAcquisitionRequest, ResearchFetchedSource, ResearchSourceCandidate } from './contracts.ts'

export interface MiitIndustryResearchPluginOptions { readonly fetchImpl?: typeof fetch; readonly now?: () => string; readonly timeoutMs?: number; readonly maxListPayloadBytes?: number; readonly maxDocumentPayloadBytes?: number; readonly documentResolver?: Pick<DocumentInputResolver, 'parse'>; readonly routes?: readonly string[] }
const PROVIDER = 'miit'; const NAME = 'miit-industry-research-acquisition'; const PUBLISHER = 'Ministry of Industry and Information Technology'
export const MIIT_INDUSTRY_ROUTES = ['https://www.miit.gov.cn/jgsj/dzs/wjfb/', 'https://www.miit.gov.cn/zwgk/zcwj/wjfb/gg/', 'https://www.miit.gov.cn/jgsj/yxj/xxfb/'] as const
export const MIIT_PCB_DEFINITION_ANCHORS = [
  { title: '\u5370\u5236\u7535\u8def\u677f\u884c\u4e1a\u89c4\u8303\u6761\u4ef6', url: 'https://wap.miit.gov.cn/cms_files/filemanager/oldfile/miit/n1146295/n1652858/n1652930/n4509607/c6577041/part/6577143.pdf', publishedAt: '2013-09-17T00:00:00.000Z' },
  { title: '\u5370\u5236\u7535\u8def\u677f\u884c\u4e1a\u89c4\u8303\u516c\u544a\u7ba1\u7406\u6682\u884c\u529e\u6cd5', url: 'https://www.miit.gov.cn/cms_files/filemanager/oldfile/miit/n1146285/n1146352/n3054355/n3057643/n3057649/c6576614/part/6576630.pdf', publishedAt: '2013-09-17T00:00:00.000Z' },
  { title: '\u4e2d\u534e\u4eba\u6c11\u5171\u548c\u56fd\u5de5\u4e1a\u548c\u4fe1\u606f\u5316\u90e8\u516c\u544a2024\u5e74\u7b2c46\u53f7', url: 'https://www.miit.gov.cn/zwgk/zcwj/wjfb/gg/art/2024/art_aae4295d7b924abeabe37d8bcf47be53.html', publishedAt: '2024-12-30T00:00:00.000Z' }
] as const
const GENERIC = new Set(['industry','manufacturing','\u884c\u4e1a','\u4ea7\u4e1a','\u5236\u9020\u4e1a']); const TRACKING = new Set(['spm','from','source','share','share_token','utm_source','utm_medium','utm_campaign','utm_term','utm_content'])
const clean = (v: string, max = 1000) => v.normalize('NFKC').replace(/\s+/g, ' ').trim().slice(0, max)
const isPcbTarget = (r: Extract<ResearchAcquisitionRequest, { industry: unknown }>) => [r.industry.name, ...(r.industry.aliases ?? []), ...r.industry.searchTerms].map((x) => clean(x, 120).toLowerCase()).some((x) => x === 'pcb' || x === 'printed circuit board' || x === 'printed circuit boards' || x === '\u5370\u5236\u7535\u8def\u677f' || /\bpcb\b/.test(x) || x.includes('printed circuit board') || x.includes('\u5370\u5236\u7535\u8def\u677f'))
const validMiitUrl = (v: unknown): v is string => { try { const u = new URL(String(v)); return u.protocol === 'https:' && (u.hostname === 'miit.gov.cn' || u.hostname.endsWith('.miit.gov.cn')) } catch { return false } }
export { validMiitUrl }
const canonical = (v: string) => { const u = new URL(v); u.hash = ''; for (const k of [...u.searchParams.keys()]) if (TRACKING.has(k.toLowerCase())) u.searchParams.delete(k); return u.toString() }
const terms = (r: Extract<ResearchAcquisitionRequest, { industry: unknown }>) => [...new Set([r.industry.name, ...(r.industry.aliases ?? []), ...r.industry.searchTerms].map((x) => clean(x, 120)).filter(Boolean))].filter((x) => !GENERIC.has(x.toLowerCase()))
const score = (title: string, _snippet: string | undefined, ts: readonly string[]) => ts.filter((t) => title.toLowerCase().includes(t.toLowerCase())).length
const pubDate = (v: string) => { const m = v.match(/20\d{2}[\u5e74\/-]\d{1,2}[\u6708\/-]\d{1,2}[\u65e5]?/); if (!m) return undefined; const d = new Date(m[0].replace(/[\u5e74\u6708\u65e5\/]/g, '-').replace(/-+$/, '')); return Number.isNaN(d.getTime()) ? undefined : d.toISOString() }
type Row = { title: string; url: string; snippet?: string; publishedAt?: string }
function parseList(html: string, baseUrl: string): { rows: Row[]; next: string[] } { const rows: Row[] = []; const next: string[] = []; const re = /<a\b[^>]*href\s*=\s*["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi; let m: RegExpExecArray | null; while ((m = re.exec(html))) { const title = clean(m[2]!.replace(/<[^>]+>/g, '')); let url: string; try { url = canonical(new URL(m[1]!.trim(), baseUrl).toString()) } catch { continue } if (!title || !validMiitUrl(url)) continue; const context = clean(html.slice(Math.max(0, m.index - 220), Math.min(html.length, re.lastIndex + 220))); if (/page|next|\u4e0b\u4e00\u9875|\u4e0b\u9875/i.test(`${title} ${m[1]}`)) next.push(url); else rows.push({ title, url, snippet: context, publishedAt: pubDate(context) }) } return { rows, next } }
async function bounded(r: Response, max: number) { if (!r.body) { const b = new TextEncoder().encode(await r.text()); if (b.byteLength > max) throw new Error('MIIT payload exceeds bound'); return b } const rd = r.body.getReader(); const cs: Uint8Array[] = []; let n = 0; for (;;) { const p = await rd.read(); if (p.done) break; n += p.value.byteLength; if (n > max) { await rd.cancel(); throw new Error('MIIT payload exceeds bound') } cs.push(p.value) } const out = new Uint8Array(n); let o = 0; for (const c of cs) { out.set(c, o); o += c.byteLength } return out }
export class MiitIndustryResearchPlugin implements ResearchAcquisitionPlugin {
  readonly name = NAME; private readonly fetchImpl: typeof fetch; private readonly now: () => string; private readonly timeoutMs: number; private readonly listMax: number; private readonly docMax: number; private readonly resolver: Pick<DocumentInputResolver, 'parse'>; private readonly routes: readonly string[]
  constructor(o: MiitIndustryResearchPluginOptions = {}) { this.fetchImpl = o.fetchImpl ?? fetch; this.now = o.now ?? (() => new Date().toISOString()); this.timeoutMs = Math.min(20_000, Math.max(1, o.timeoutMs ?? 15_000)); this.listMax = Math.min(2 * 1024 * 1024, o.maxListPayloadBytes ?? 2 * 1024 * 1024); this.docMax = Math.min(8 * 1024 * 1024, o.maxDocumentPayloadBytes ?? 8 * 1024 * 1024); this.resolver = o.documentResolver ?? new DocumentInputResolver(); this.routes = (o.routes ?? MIIT_INDUSTRY_ROUTES).slice(0, 3).filter(validMiitUrl) }
  private async request(url: string, max: number) { if (!validMiitUrl(url)) throw new Error('MIIT URL is outside the allowed domain'); const c = new AbortController(); const timer = setTimeout(() => c.abort(), this.timeoutMs); try { const response = await this.fetchImpl(url, { signal: c.signal, headers: { accept: 'text/html,application/xhtml+xml,application/pdf' } }); const finalUrl = canonical(response.url || url); if (!validMiitUrl(finalUrl)) throw new Error('MIIT redirect crossed domain boundary'); if (!response.ok) throw new Error(`MIIT request failed with HTTP ${response.status}`); return { response, finalUrl, bytes: await bounded(response, max) } } finally { clearTimeout(timer) } }
  async discover(r: ResearchAcquisitionRequest): Promise<readonly ResearchSourceCandidate[]> { if ('company' in r) return []; const ts = terms(r); if (!ts.length) return []; const limit = Math.min(8, Math.max(0, r.limitPerKind ?? 6)); const found = new Map<string, ResearchSourceCandidate>(); if (isPcbTarget(r)) for (const anchor of MIIT_PCB_DEFINITION_ANCHORS) { if (anchor.publishedAt && r.asOf && anchor.publishedAt > new Date(r.asOf).toISOString()) continue; const url = canonical(anchor.url); found.set(url, { candidateId: `${PROVIDER}-${sha256(url)}`, kind: 'official_disclosure', tier: 1, title: anchor.title, url, provider: PROVIDER, publishedAt: anchor.publishedAt, snippet: 'Bounded authoritative MIIT PCB definition and scope anchor.', metadata: { officialHost: new URL(url).hostname, discoveryRoute: 'pcb-definition-anchor', relevanceTerms: ['PCB', 'Industry Definition'], anchor: true } }) } for (const route of this.routes) { let page = route; const routeHost = new URL(route).hostname; const visited = new Set<string>(); for (let i = 0; i < 2 && page; i++) { if (visited.has(page)) break; visited.add(page); const { finalUrl, bytes } = await this.request(page, this.listMax); const p = parseList(new TextDecoder().decode(bytes), finalUrl); for (const x of p.rows) { if (!score(x.title, x.snippet, ts) || (x.publishedAt && r.asOf && x.publishedAt > new Date(r.asOf).toISOString())) continue; found.set(x.url, { candidateId: `${PROVIDER}-${sha256(x.url)}`, kind: 'web_article', tier: 1, title: x.title, url: x.url, provider: PROVIDER, ...(x.publishedAt ? { publishedAt: x.publishedAt } : {}), snippet: x.snippet, metadata: { officialHost: new URL(x.url).hostname, discoveryRoute: new URL(route).pathname, relevanceTerms: ts.filter((t) => `${x.title} ${x.snippet ?? ''}`.toLowerCase().includes(t.toLowerCase())) } }) } page = p.next.find((x) => validMiitUrl(x) && new URL(x).hostname === routeHost) ?? '' } } const anchors = [...found.values()].filter((x) => Boolean((x.metadata as Record<string, unknown> | undefined)?.anchor)); const normal = [...found.values()].filter((x) => !(x.metadata as Record<string, unknown> | undefined)?.anchor).sort((a,b) => score(b.title,b.snippet,ts)-score(a.title,a.snippet,ts) || (b.publishedAt ?? '').localeCompare(a.publishedAt ?? '') || (a.url ?? '').localeCompare(b.url ?? '')); return [...anchors, ...normal].slice(0, limit) }
  async fetch(cand: ResearchSourceCandidate): Promise<ResearchFetchedSource> { if (cand.provider !== PROVIDER || !cand.url || !validMiitUrl(cand.url) || cand.candidateId !== `${PROVIDER}-${sha256(canonical(cand.url))}`) throw new Error('candidate does not belong to MIIT'); const requested = canonical(cand.url); const { response, bytes } = await this.request(requested, this.docMax); const finalUrl = canonical(response.url || requested); const ct = (response.headers.get('content-type') ?? '').split(';')[0].toLowerCase(); const pdf = ct === 'application/pdf' || finalUrl.toLowerCase().includes('.pdf'); if (!pdf && !['text/html','application/xhtml+xml','text/plain',''].includes(ct)) throw new Error(`MIIT unsupported content type: ${ct}`); return { candidate: { ...cand, url: finalUrl }, retrievedAt: this.now(), content: new TextDecoder().decode(bytes), contentType: ct, mediaType: pdf ? 'application/pdf' : ct || 'text/html', rawBytes: bytes, contentHash: sha256(bytes) } }
  async normalize(s: ResearchFetchedSource): Promise<NormalizedResearchSource> { if (s.candidate.provider !== PROVIDER || !s.rawBytes?.byteLength || !s.candidate.url || !validMiitUrl(s.candidate.url)) throw new Error('source does not belong to MIIT'); const mediaType = s.mediaType ?? s.contentType ?? 'text/html'; const doc = await this.resolver.parse({ bytes: s.rawBytes, filename: mediaType === 'application/pdf' ? 'miit-document.pdf' : 'miit-document.html', mediaType }); if (!doc.normalizedText.trim()) throw new Error('MIIT normalized document is empty'); return { candidate: s.candidate, retrievedAt: s.retrievedAt, title: s.candidate.title, content: doc.normalizedText, canonicalUrl: canonical(s.candidate.url), contentHash: s.contentHash ?? sha256(s.rawBytes), rawBytes: Uint8Array.from(s.rawBytes), publisher: PUBLISHER, rights: { accessScope: 'public', retentionAllowed: true, aiProcessingAllowed: true, derivativeKnowledgeAllowed: true, redistributionAllowed: false, policyBasis: 'personal_noncommercial_research' } } }
}
