import test from 'node:test'
import assert from 'node:assert/strict'
import { resolveKnowledge, resolveResolutionIntentBarrier } from '../../workflows/raw-document-knowledge-ingestion/knowledge-resolution.ts'
import { planKnowledgeChangeSet } from '../../workflows/raw-document-knowledge-ingestion/changeset-planner.ts'
import { KnowledgeCurationSkill } from '../../skills/knowledge-curation/skill.ts'
import { MockReasoningExecutor } from '../../plugins/reasoning/mock/executor.ts'
import { emptyReviewSummary, normalizeReviewSummary, writeNoOpExecutionRecord } from '../../workflows/raw-document-knowledge-ingestion/review-telemetry.ts'
import { boundedExtract } from '../../workflows/raw-document-knowledge-ingestion/workflow.ts'
import { KnowledgeCurationError } from '../../skills/knowledge-curation/errors.ts'
import { createKnowledgeBase, removeKnowledgeBase } from '../knowledge/helpers.ts'
import type { KnowledgeAssetCollectionV03 } from '../../knowledge/storage/v03-types.ts'
import type { ClaimCandidate, EntityCandidate, RelationCandidate, ResolvedCandidateGroup, ValidatedExtractKnowledgeResult } from '../../skills/knowledge-curation/contracts.ts'
import type { AcceptedExtractionPlan } from '../../workflows/raw-document-knowledge-ingestion/contracts.ts'
import type { EffectiveConfig } from '../../workflows/raw-document-knowledge-ingestion/workflow.ts'
import { allocateSourceId } from '../../workflows/raw-document-knowledge-ingestion/id-helpers.ts'

const rawRef = 'raw-sha256-' + '0'.repeat(64)
const reportMap = { sourceAssessment: { summary: 'test', sourceType: 'unknown' as const, reliability: 'unknown' as const }, researchScope: 'test', majorTopics: [], majorEntityMentions: [], majorConclusions: [], sectionSemantics: [], semanticDependencies: [], themeHypotheses: [], uncertainty: [] }
const plan: AcceptedExtractionPlan = { units: [], excludedBlockIds: [], estimatedContextTokens: {} }
const emptyAssets = (): KnowledgeAssetCollectionV03 => ({ rootDir: '', themeGroups: [], entities: [], relations: [], claims: [], modules: [], sources: [], registry: [] })
function loaded(kind: 'entity' | 'relation' | 'claim', value: Record<string, unknown>): { kind: typeof kind; value: Record<string, unknown>; filePath: string; storageRef: string } { return { kind, value, filePath: '', storageRef: '' } }
function entity(id: string, name: string, entityType: EntityCandidate['entityType'] = 'company', extra: Record<string, unknown> = {}): EntityCandidate { return { candidateId: id, entityType, name, evidenceBlockRefs: [], reason: 'test', ...extra } }
function relation(id: string, relationType: RelationCandidate['relationType'], source: string, target: string, attributes?: Record<string, unknown>): RelationCandidate { return { candidateId: id, relationType, source: { candidateRef: source, mention: source }, target: { candidateRef: target, mention: target }, ...(attributes === undefined ? {} : { attributes }), evidenceBlockRefs: [], reason: 'test' } }
function claim(id: string, statement: string, subject: string, extra: Record<string, unknown> = {}): ClaimCandidate { return { candidateId: id, claimType: 'fact', statement, subjectRefs: [{ candidateRef: subject, mention: subject }], evidenceBlockRefs: [], reason: 'test', ...extra } }
function group(candidate: EntityCandidate | RelationCandidate | ClaimCandidate): ResolvedCandidateGroup { return { candidateId: candidate.candidateId, kind: 'entityType' in candidate ? 'entity' : 'relationType' in candidate ? 'relation' : 'claim', candidate } }
function assets(entities: Record<string, unknown>[] = [], relations: Record<string, unknown>[] = [], claims: Record<string, unknown>[] = []): KnowledgeAssetCollectionV03 { return { ...emptyAssets(), entities: entities.map((value) => loaded('entity', value) as never), relations: relations.map((value) => loaded('relation', value) as never), claims: claims.map((value) => loaded('claim', value) as never) } }
function executor(response?: unknown): MockReasoningExecutor { const fallback = (request: { input: unknown }) => { const kind = ((request.input as { resolutionCase?: { caseKind?: string } }).resolutionCase?.caseKind); if (kind === 'EntityBindingCase') { if (response && typeof response === 'object' && ['equivalent_to', 'distinct_from_all', 'uncertain'].includes(String((response as { outcome?: unknown }).outcome))) return response; return { outcome: 'equivalent_to', targetAlias: 'existing-001', rationale: 'Bounded fixture equivalence.' } } return response ?? { outcome: 'equivalent', targetAlias: 'existing-001', rationale: 'Bounded fixture equivalence.' } }; return new MockReasoningExecutor({ capabilities: { maxContextTokens: 10_000, maxOutputTokens: 10_000, structuredOutputSupport: true, maxConcurrency: 4 }, responses: { resolveSemanticCase: fallback } }) }
async function resolve(groups: readonly ResolvedCandidateGroup[], existing: KnowledgeAssetCollectionV03 = emptyAssets(), response?: unknown, options: Record<string, unknown> = {}) { const mock = executor(response); const skill = new KnowledgeCurationSkill({ executor: mock }); const result = await resolveKnowledge({ assets: existing, groups, reportMap, plan, rawRef, skill, ...options } as never); return { result, mock } }
function plannerInput(groups: readonly ResolvedCandidateGroup[], resolution: Awaited<ReturnType<typeof resolveKnowledge>>, existing: KnowledgeAssetCollectionV03 = emptyAssets()): Parameters<typeof planKnowledgeChangeSet>[0] { return { knowledgeBaseId: 'kb-test', baseRevision: 0, workflowRunId: 'run-test', rawRef, rawManifest: { originalFilename: 'test.txt', suppliedMetadata: { title: 'Test', institution: null, author: null, publishedAt: null, sourceUrl: null } }, documentId: 'doc-test', document: { metadata: { originalFilename: 'test.txt', title: 'Test' } }, reportMap, plan, groups, intents: resolution.intents, bindings: resolution.bindings, assets: existing, resolutionReviews: resolution.reviewItems } }

test('empty KB Entity becomes PlannedNew without reasoning', async () => { const { result, mock } = await resolve([group(entity('e', 'Acme'))]); assert.equal(result.bindings.get('e')?.state, 'PlannedNew'); assert.equal(result.intents[0]?.disposition, 'create'); assert.equal(mock.calls.length, 0) })
test('Company exact exchange and ticker binds deterministically', async () => { const { result, mock } = await resolve([group(entity('e', 'Acme', 'company', { semanticFields: { exchange: 'NYSE', ticker: 'ACM' } }))], assets([{ id: 'entity:acme', type: 'company', name: 'Acme Corp', exchange: 'nyse', ticker: 'acm', lifecycle: { status: 'active' } }])); assert.equal(result.bindings.get('e')?.state, 'BoundExisting'); assert.equal(result.bindings.get('e')?.ref, 'entity:acme'); assert.equal(mock.calls.length, 0) })
test('duplicate hard-key canonical Companies deterministically block', async () => { const { result } = await resolve([group(entity('e', 'Acme', 'company', { semanticFields: { exchange: 'NYSE', ticker: 'ACM' } }))], assets([{ id: 'entity:a', type: 'company', name: 'A', exchange: 'NYSE', ticker: 'ACM', lifecycle: { status: 'active' } }, { id: 'entity:b', type: 'company', name: 'B', exchange: 'NYSE', ticker: 'ACM', lifecycle: { status: 'active' } }])); assert.equal(result.blocked, true); assert.match(result.errors[0] ?? '', /integrity defect/) })
test('exact name is plausible EntityBindingCase, not automatic binding', async () => { const { result, mock } = await resolve([group(entity('e', 'Acme'))], assets([{ id: 'entity:acme', type: 'company', name: 'Acme', lifecycle: { status: 'active' } }]), { outcome: 'uncertain', rationale: 'Insufficient evidence.' }); assert.equal(result.intents[0]?.disposition, 'review'); assert.equal(mock.calls.length, 1); const input = mock.calls[0]?.input as { resolutionCase: { existingProjections: readonly unknown[] } }; assert.equal(JSON.stringify(input), JSON.stringify(input).replace('entity:acme', 'case-local')) })
test('alias-only match is bounded and case-local', async () => { const { result, mock } = await resolve([group(entity('e', '海力士'))], assets([{ id: 'entity:hynix', type: 'company', name: 'SK Hynix', aliases: ['海力士'], lifecycle: { status: 'active' } }]), { outcome: 'equivalent_to', targetAlias: 'existing-001', rationale: 'Alias and evidence agree.' }); assert.equal(result.bindings.get('e')?.ref, 'entity:hynix'); assert.equal(mock.calls.length, 1); assert.doesNotMatch(JSON.stringify(mock.calls[0]?.input), /entity:hynix/) })
test('semantic equivalent_to maps only the infrastructure target', async () => { const { result } = await resolve([group(entity('e', 'Alias'))], assets([{ id: 'entity:x', type: 'company', name: 'Canonical', aliases: ['Alias'], lifecycle: { status: 'active' } }]), { outcome: 'equivalent_to', targetAlias: 'existing-001', rationale: 'Same entity.' }); assert.equal(result.intents[0]?.targetRef, 'entity:x') })
test('distinct_from_all creates a PlannedNew binding', async () => { const { result } = await resolve([group(entity('e', 'Alias'))], assets([{ id: 'entity:x', type: 'company', name: 'Canonical', aliases: ['Alias'], lifecycle: { status: 'active' } }]), { outcome: 'distinct_from_all', rationale: 'Evidence distinguishes them.' }); assert.equal(result.bindings.get('e')?.state, 'PlannedNew'); assert.match(result.bindings.get('e')?.plannedRef ?? '', /^planned-entity-/) })
test('uncertain Entity binding becomes root Review', async () => { const { result } = await resolve([group(entity('e', 'Alias'))], assets([{ id: 'entity:x', type: 'company', name: 'Canonical', aliases: ['Alias'], lifecycle: { status: 'active' } }]), { outcome: 'uncertain', rationale: 'Need review.' }); assert.equal(result.intents[0]?.disposition, 'review'); assert.equal(result.reviewItems[0]?.dependency, false) })
test('Entity with no new fields produces no_op', async () => { const { result } = await resolve([group(entity('e', 'Acme'))], assets([{ id: 'entity:acme', type: 'company', name: 'Acme', lifecycle: { status: 'active' } }])); assert.equal(result.intents[0]?.disposition, 'no_op') })
test('Entity missing alias produces enrich_existing', async () => { const { result } = await resolve([group(entity('e', 'Acme', 'company', { aliases: ['ACM'] }))], assets([{ id: 'entity:acme', type: 'company', name: 'Acme', lifecycle: { status: 'active' } }])); assert.equal(result.intents[0]?.disposition, 'enrich_existing') })
test('Entity conflicting populated state becomes Review', async () => { const { result } = await resolve([group(entity('e', 'Acme', 'company', { semanticFields: { exchange: 'NASDAQ', ticker: 'ACM' } }))], assets([{ id: 'entity:acme', type: 'company', name: 'Acme', exchange: 'NYSE', ticker: 'ACM', lifecycle: { status: 'active' } }])); assert.equal(result.intents[0]?.disposition, 'review') })
test('Relation with PlannedNew endpoint is create intent', async () => { const { result } = await resolve([group(entity('a', 'A')), group(entity('b', 'B', 'product')), group(relation('r', 'offers_product', 'a', 'b'))]); assert.equal(result.intents.find((item) => item.candidateRef === 'r')?.disposition, 'create') })
test('Relation with existing endpoints and no match is create', async () => { const groups = [group(entity('a', 'A')), group(entity('b', 'B', 'product')), group(relation('r', 'offers_product', 'a', 'b'))]; const { result } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }, { id: 'entity:b', type: 'product', name: 'B', lifecycle: { status: 'active' } }])); assert.equal(result.intents.find((item) => item.candidateRef === 'r')?.disposition, 'create') })
test('exact Relation uses merge_evidence with no Relation conflict case', async () => { const groups = [group(entity('a', 'A')), group(entity('b', 'B', 'product')), group(relation('r', 'offers_product', 'a', 'b'))]; const old = { id: 'relation:r', type: 'offers_product', sourceRef: 'entity:a', targetRef: 'entity:b', sourceRefs: ['source:old'], lifecycle: { status: 'active' } }; const { result, mock } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }, { id: 'entity:b', type: 'product', name: 'B', lifecycle: { status: 'active' } }], [old])); assert.equal(result.intents.find((item) => item.candidateRef === 'r')?.disposition, 'merge_evidence'); assert.equal(mock.calls.filter((call) => ((call.input as { resolutionCase?: { caseKind?: string } }).resolutionCase?.caseKind) === 'RelationConflictCase').length, 0) })
test('Relation additive attributes use enrich_existing', async () => { const groups = [group(entity('a', 'A')), group(entity('b', 'B', 'product')), group(relation('r', 'offers_product', 'a', 'b', { } as Record<string, unknown>))]; const old = { id: 'relation:r', type: 'offers_product', sourceRef: 'entity:a', targetRef: 'entity:b', sourceRefs: ['source:old'], lifecycle: { status: 'active' } }; const { result } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }, { id: 'entity:b', type: 'product', name: 'B', lifecycle: { status: 'active' } }], [old])); assert.equal(result.intents.find((item) => item.candidateRef === 'r')?.disposition, 'merge_evidence') })
test('Relation conflicting attributes invokes RelationConflictCase', async () => { const groups = [group(entity('a', 'A')), group(entity('b', 'B', 'product')), group(relation('r', 'offers_product', 'a', 'b', { importance: 'high' }))]; const old = { id: 'relation:r', type: 'offers_product', sourceRef: 'entity:a', targetRef: 'entity:b', attributes: { importance: 'low' }, sourceRefs: ['source:old'], lifecycle: { status: 'active' } }; const { result } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }, { id: 'entity:b', type: 'product', name: 'B', lifecycle: { status: 'active' } }], [old]), { outcome: 'uncertain', rationale: 'Conflict needs review.' }); assert.equal(result.intents.find((item) => item.candidateRef === 'r')?.disposition, 'review') })
test('RelationConflict equivalent maps to merge_evidence', async () => { const groups = [group(entity('a', 'A')), group(entity('b', 'B', 'product')), group(relation('r', 'offers_product', 'a', 'b', { importance: 'high' }))]; const old = { id: 'relation:r', type: 'offers_product', sourceRef: 'entity:a', targetRef: 'entity:b', attributes: { importance: 'low' }, sourceRefs: ['source:old'], lifecycle: { status: 'active' } }; const { result } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }, { id: 'entity:b', type: 'product', name: 'B', lifecycle: { status: 'active' } }], [old]), { outcome: 'equivalent', targetAlias: 'existing-001', rationale: 'Same relation.' }); assert.equal(result.intents.find((item) => item.candidateRef === 'r')?.disposition, 'merge_evidence') })
test('RelationConflict state_changed maps to replace_state', async () => { const groups = [group(entity('a', 'A')), group(entity('b', 'B', 'product')), group(relation('r', 'offers_product', 'a', 'b', { importance: 'high' }))]; const old = { id: 'relation:r', type: 'offers_product', sourceRef: 'entity:a', targetRef: 'entity:b', attributes: { importance: 'low' }, sourceRefs: ['source:old'], lifecycle: { status: 'active' } }; const { result } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }, { id: 'entity:b', type: 'product', name: 'B', lifecycle: { status: 'active' } }], [old]), { outcome: 'state_changed', targetAlias: 'existing-001', rationale: 'State changed.' }); assert.equal(result.intents.find((item) => item.candidateRef === 'r')?.disposition, 'replace_state') })
test('RelationConflict coexists and contradicts remain Review', async () => { for (const outcome of ['coexists', 'contradicts'] as const) { const groups = [group(entity('a', 'A')), group(entity('b', 'B', 'product')), group(relation('r', 'offers_product', 'a', 'b', { importance: 'high' }))]; const old = { id: 'relation:r', type: 'offers_product', sourceRef: 'entity:a', targetRef: 'entity:b', attributes: { importance: 'low' }, sourceRefs: ['source:old'], lifecycle: { status: 'active' } }; const { result } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }, { id: 'entity:b', type: 'product', name: 'B', lifecycle: { status: 'active' } }], [old]), { outcome, rationale: outcome }); assert.equal(result.intents.find((item) => item.candidateRef === 'r')?.disposition, 'review') } })
test('RelationConflict invalid maps to reject', async () => { const groups = [group(entity('a', 'A')), group(entity('b', 'B', 'product')), group(relation('r', 'offers_product', 'a', 'b', { importance: 'high' }))]; const old = { id: 'relation:r', type: 'offers_product', sourceRef: 'entity:a', targetRef: 'entity:b', attributes: { importance: 'low' }, sourceRefs: ['source:old'], lifecycle: { status: 'active' } }; const { result } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }, { id: 'entity:b', type: 'product', name: 'B', lifecycle: { status: 'active' } }], [old]), { outcome: 'invalid', rationale: 'Invalid.' }); assert.equal(result.intents.find((item) => item.candidateRef === 'r')?.disposition, 'reject') })
test('Claim exact identity uses merge_evidence', async () => { const groups = [group(entity('a', 'A')), group(claim('c', 'A grows', 'a'))]; const old = { id: 'claim:old', claimType: 'fact', statement: 'A grows', subjectRefs: ['entity:a'], sourceRefs: ['source:old'], lifecycle: { status: 'active' } }; const { result } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }], [], [old])); assert.equal(result.intents.find((item) => item.candidateRef === 'c')?.disposition, 'merge_evidence') })
test('Claim exact evidence merge preserves source and provenance in planner', () => { const groups = [group(entity('a', 'A')), group(claim('c', 'A grows', 'a', { evidenceBlockRefs: ['block-1'] }))]; const old = { id: 'claim:old', claimType: 'fact', statement: 'A grows', subjectRefs: ['entity:a'], sourceRefs: ['source:old'], provenance: [{ sourceRef: 'source:old', rawRef, locator: 'old', chunkRef: null }], lifecycle: { status: 'active' } }; return resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }], [], [old])).then((resolution) => { const result = planKnowledgeChangeSet(plannerInput(groups, resolution.result, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }], [], [old]))); const op = result.changeSet?.knowledgeOperations.find((item) => item.type === 'update'); assert.equal(op?.type, 'update'); if (op?.type === 'update' && 'sourceRefs' in op.object) { assert.deepEqual(op.object.sourceRefs, ['source:old', allocateSourceId({ sourceUrl: null, publishedAt: null, title: 'Test', rawRef })].sort()); assert.equal((op.object as unknown as { provenance?: unknown[] }).provenance?.length, 2) } }) })
test('Claim with no plausible conflict is create', async () => { const groups = [group(entity('a', 'A')), group(claim('c', 'A grows', 'a'))]; const { result } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }])); assert.equal(result.intents.find((item) => item.candidateRef === 'c')?.disposition, 'create') })
test('Claim same subject and type conflict invokes bounded case', async () => { const groups = [group(entity('a', 'A')), group(claim('c', 'A grows rapidly', 'a'))]; const old = { id: 'claim:old', claimType: 'fact', statement: 'A grows slowly', subjectRefs: ['entity:a'], temporal: null, sourceRefs: ['source:old'], lifecycle: { status: 'active' } }; const { result, mock } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }], [], [old]), { outcome: 'uncertain', rationale: 'Conflict uncertain.' }); assert.equal(result.intents.find((item) => item.candidateRef === 'c')?.disposition, 'review'); assert.equal(mock.calls.length, 1) })
test('Claim supersedes maps to supersede', async () => { const groups = [group(entity('a', 'A')), group(claim('c', 'A grows rapidly', 'a'))]; const old = { id: 'claim:old', claimType: 'fact', statement: 'A grows slowly', subjectRefs: ['entity:a'], sourceRefs: ['source:old'], lifecycle: { status: 'active' } }; const { result } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }], [], [old]), { outcome: 'supersedes', targetAlias: 'existing-001', rationale: 'Newer fact.' }); assert.equal(result.intents.find((item) => item.candidateRef === 'c')?.disposition, 'supersede') })
test('Claim coexists maps to a distinct create', async () => { const groups = [group(entity('a', 'A')), group(claim('c', 'A has a different view', 'a'))]; const old = { id: 'claim:old', claimType: 'viewpoint', statement: 'A has an older view', subjectRefs: ['entity:a'], sourceRefs: ['source:old'], lifecycle: { status: 'active' } }; const candidate = { ...groups[1]!.candidate as ClaimCandidate, claimType: 'viewpoint' as const }; const { result } = await resolve([groups[0]!, group(candidate)], assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }], [], [old]), { outcome: 'coexists', rationale: 'Distinct supported view.' }); assert.equal(result.intents.find((item) => item.candidateRef === 'c')?.disposition, 'create') })
test('contradictory forecast may coexist while fact is Review', async () => { for (const claimType of ['forecast', 'fact'] as const) { const groups = [group(entity('a', 'A')), group({ ...claim('c', 'A outcome', 'a'), claimType })]; const old = { id: 'claim:old', claimType, statement: 'A prior outcome', subjectRefs: ['entity:a'], sourceRefs: ['source:old'], lifecycle: { status: 'active' } }; const { result } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }], [], [old]), { outcome: 'contradicts', rationale: 'Contradiction.' }); assert.equal(result.intents.find((item) => item.candidateRef === 'c')?.disposition, claimType === 'forecast' ? 'create' : 'review') } })
test('Claim retrieval overflow becomes explicit Review', async () => { const e = { id: 'entity:a', type: 'company', name: 'A', exchange: 'NYSE', ticker: 'A', lifecycle: { status: 'active' } }; const old = Array.from({ length: 9 }, (_, index) => ({ id: `claim:${index}`, claimType: 'fact', statement: `Prior statement ${index}`, subjectRefs: ['entity:a'], sourceRefs: ['source:old'], lifecycle: { status: 'active' } })); const { result, mock } = await resolve([group(entity('a', 'A', 'company', { semanticFields: { exchange: 'NYSE', ticker: 'A' } })), group(claim('c', 'new statement', 'a'))], assets([e], [], old)); assert.equal(result.intents.find((item) => item.candidateRef === 'c')?.disposition, 'review'); assert.equal(mock.calls.length, 0); assert.match(result.reviewItems.find((item) => item.candidateId === 'c')?.rationale ?? '', /overflow/) })
test('dependent Relation and Claim isolate when Entity is Review', async () => { const groups = [group(entity('a', 'Alias')), group(entity('b', 'B', 'product')), group(relation('r', 'offers_product', 'a', 'b')), group(claim('c', 'Alias matters', 'a'))]; const { result } = await resolve(groups, assets([{ id: 'entity:x', type: 'company', name: 'Alias' }, { id: 'entity:b', type: 'product', name: 'B' }]), { outcome: 'uncertain', rationale: 'Entity uncertain.' }); assert.equal(result.intents.find((item) => item.candidateRef === 'r')?.disposition, 'review'); assert.equal(result.intents.find((item) => item.candidateRef === 'c')?.disposition, 'review'); assert.equal(result.reviewItems.filter((item) => item.dependency).length, 2) })
test('Resolution barrier rejects duplicate intents', () => { const g = group(entity('e', 'E')); const bindings = new Map([['e', { candidateId: 'e', state: 'PlannedNew' as const, plannedRef: 'planned-entity-x', plausibleMatches: [] }]]); const one = { candidateRef: 'e', candidateKind: 'entity' as const, disposition: 'create' as const, targetRef: 'planned-entity-x', semanticBasis: { rationale: 'x' }, evidenceRefs: [] }; assert.equal(resolveResolutionIntentBarrier([g], [one, one], bindings).valid, false) })
test('Resolution barrier rejects missing intents', () => { const g = group(entity('e', 'E')); assert.equal(resolveResolutionIntentBarrier([g], [], new Map()).valid, false) })
test('Resolution barrier rejects unresolved safe local refs', () => { const g = group(entity('e', 'E')); const binding = { candidateId: 'e', state: 'PlannedNew' as const, plannedRef: 'planned-entity-x', plausibleMatches: [] }; const intent = { candidateRef: 'e', candidateKind: 'entity' as const, disposition: 'create' as const, targetRef: 'local-e', semanticBasis: { rationale: 'x' }, evidenceRefs: [] }; assert.equal(resolveResolutionIntentBarrier([g], [intent], new Map([['e', binding]])).valid, false) })
test('fresh synthetic graph scales without semantic resolution calls', async () => { const groups = Array.from({ length: 120 }, (_, index) => group(entity(`e-${index}`, `Fresh ${index}`))); const { result, mock } = await resolve(groups); assert.equal(result.semanticCaseCalls, 0); assert.equal(mock.calls.length, 0); assert.equal(result.intents.length, 120); assert.equal(result.intents.every((item) => item.disposition === 'create'), true) })
test('mature KB reasoning scales with ambiguity rather than candidate count', async () => { const groups = Array.from({ length: 20 }, (_, index) => group(entity(`e-${index}`, index === 0 ? 'Ambiguous' : `Fresh ${index}`))); const { result, mock } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'Ambiguous' }]), { outcome: 'uncertain', rationale: 'Ambiguous.' }); assert.equal(mock.calls.length, 1); assert.equal(result.semanticCaseCalls, 1); assert.equal(result.intents.length, 20) })
test('planner allocates durable IDs only after ResolutionIntent', async () => { const groups = [group(entity('e', 'New'))]; const resolution = await resolve(groups); const planned = resolution.result.bindings.get('e')?.plannedRef; assert.match(planned ?? '', /^planned-entity-/); const result = planKnowledgeChangeSet(plannerInput(groups, resolution.result)); assert.equal(result.entityResolutions[0]?.status, 'created'); assert.match(result.entityResolutions[0]?.canonicalId ?? '', /^entity:/) })
test('review-only resolution creates no unreferenced Source', async () => { const groups = [group(entity('e', 'Alias'))]; const resolution = await resolve(groups, assets([{ id: 'entity:x', type: 'company', name: 'Alias' }]), { outcome: 'uncertain', rationale: 'Review.' }); const result = planKnowledgeChangeSet(plannerInput(groups, resolution.result, assets([{ id: 'entity:x', type: 'company', name: 'Alias' }]))); assert.equal(result.changeSet, undefined); assert.equal(result.safeOperationCount, 0) })
test('symmetric Relation identity resolves reverse orientation', async () => { const groups = [group(entity('a', 'A')), group(entity('b', 'B')), group(relation('r', 'competes_with', 'a', 'b'))]; const old = { id: 'relation:old', type: 'competes_with', sourceRef: 'entity:b', targetRef: 'entity:a', sourceRefs: ['source:old'], lifecycle: { status: 'active' } }; const { result } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A' }, { id: 'entity:b', type: 'company', name: 'B' }], [old])); assert.equal(result.intents.find((item) => item.candidateRef === 'r')?.disposition, 'merge_evidence') })
test('bounded extraction still retries only failed units', async () => { const calls: string[] = []; const config = { maxExtractionUnits: 64, maxPlanAttempts: 2, maxExtractionAttempts: 3, maxConcurrency: 1 } as EffectiveConfig; const empty = (): ValidatedExtractKnowledgeResult => ({ entities: [], relations: [], claims: [], rejected: [], summary: { inputCounts: { entity: 0, relation: 0, claim: 0 }, acceptedCounts: { entity: 0, relation: 0, claim: 0 }, rejectedCounts: { entity: 0, relation: 0, claim: 0 }, rejectionCodes: [] } }); const input = { skill: { extractKnowledge: async ({ unit }: { unit: { unitId: string } }) => { calls.push(unit.unitId); if (unit.unitId === 'two' && calls.filter((id) => id === 'two').length === 1) throw new KnowledgeCurationError('invalid_model_output', 'bad'); return empty() } } } as never; const units = ['one', 'two'].map((unitId) => ({ unitId, proposedUnitId: unitId, topic: 't', semanticPurpose: 't', primaryRefs: [], contextRefs: [], primaryBlockIds: [], contextBlockIds: [] })); const result = await boundedExtract(input, {} as never, {} as never, units, 1, config); assert.deepEqual(calls, ['one', 'two', 'two']); assert.equal(result.summaries[1]?.attempts, 2) })
test('review summary keeps knowledge-resolution stage visible', () => { const summary = normalizeReviewSummary({ resolutionReviews: [{ candidateId: 'e', kind: 'entity', rationale: 'Ambiguous binding', dependentCandidateIds: [], stage: 'semantic_case', category: 'reconciliation_review', origin: 'semantic_case', dependency: false, reviewKey: 'case-e' }], candidateGroups: [group(entity('e', 'E'))] }); assert.equal(summary.total, 1); assert.equal(summary.byCategory.reconciliation_review, 1) })
test('ReviewSummary frozen shape remains stable', () => { const summary = emptyReviewSummary(); assert.equal(summary.total, 0); assert.deepEqual(Object.keys(summary.byCandidateKind).sort(), ['claim', 'entity', 'relation', 'workflow_level']) })
test('no-op execution records replay without revision change', async () => { const root = await createKnowledgeBase({ knowledgeBaseId: 'kb-noop-resolution' }); try { const record = { workflowRunId: 'run-noop', knowledgeBaseId: 'kb-noop-resolution', rawRef, documentId: 'doc', workflowInputFingerprint: 'fp', status: 'completed' as const, writeStatus: 'no_changes' as const, baseRevision: 0, committedRevision: 0, reviewSummary: emptyReviewSummary(), completedAt: 'now', errors: [] }; assert.equal((await writeNoOpExecutionRecord(root, record)).kind, 'written'); assert.equal((await writeNoOpExecutionRecord(root, record)).kind, 'replay') } finally { await removeKnowledgeBase(root) } })
