import test from 'node:test'
import assert from 'node:assert/strict'
import { resolveKnowledge, resolveResolutionIntentBarrier } from '../../workflows/raw-document-knowledge-ingestion/knowledge-resolution.ts'
import { planKnowledgeChangeSet } from '../../workflows/raw-document-knowledge-ingestion/changeset-planner.ts'
import { KnowledgeCurationSkill } from '../../skills/knowledge-curation/skill.ts'
import { MockReasoningExecutor } from '../../plugins/reasoning/mock/executor.ts'
import { emptyReviewSummary, normalizeReviewSummary, writeNoOpExecutionRecord } from '../../workflows/raw-document-knowledge-ingestion/review-telemetry.ts'
import { boundedExtract } from '../../workflows/raw-document-knowledge-ingestion/workflow.ts'
import { KnowledgeCurationError } from '../../skills/knowledge-curation/errors.ts'
import { createKnowledgeBase, removeKnowledgeBase } from '../knowledge/helpers.ts'
import { KnowledgeBaseRegistry } from '../../knowledge/registry/registry.ts'
import { validateKnowledgeChangeSetV03 } from '../../knowledge/validation/v03-change-set-validator.ts'
import type { KnowledgeAssetCollectionV03 } from '../../knowledge/storage/v03-types.ts'
import type { ClaimCandidate, EntityCandidate, RelationCandidate, ResolvedCandidateGroup, ValidatedExtractKnowledgeResult } from '../../skills/knowledge-curation/contracts.ts'
import type { AcceptedExtractionPlan } from '../../workflows/raw-document-knowledge-ingestion/contracts.ts'
import type { EffectiveConfig } from '../../workflows/raw-document-knowledge-ingestion/workflow.ts'
import { allocateSourceId } from '../../workflows/raw-document-knowledge-ingestion/id-helpers.ts'
import { buildCurationSchemaContext } from '../../skills/knowledge-curation/schema-context.ts'
import { validateExtractKnowledge } from '../../skills/knowledge-curation/validation.ts'
import { semanticOutcomeVocabulary, validateSemanticResolutionResult } from '../../skills/knowledge-curation/validation.ts'
import { consolidateExtractions } from '../../workflows/raw-document-knowledge-ingestion/consolidation.ts'
import { assessPotentialNewInvestmentTheme } from '../../workflows/raw-document-knowledge-ingestion/investment-theme-policy.ts'

const rawRef = 'raw-sha256-' + '0'.repeat(64)
const reportMap = { sourceAssessment: { summary: 'test', sourceType: 'unknown' as const, reliability: 'unknown' as const }, researchScope: 'test', majorTopics: [], majorEntityMentions: [], majorConclusions: [], sectionSemantics: [], semanticDependencies: [], themeHypotheses: [], uncertainty: [] }
const plan: AcceptedExtractionPlan = { units: [], excludedBlockIds: [], estimatedContextTokens: {} }
const document = { documentId: 'doc-test', parser: { id: 'test' }, metadata: { originalFilename: 'test.txt', mediaType: 'text/plain' }, normalizedText: 'SK海力士预计2026年HBM收入增长...', sections: [], blocks: [{ blockId: 'block-1', type: 'paragraph' as const, text: 'SK海力士预计2026年HBM收入增长...', sectionRef: null, page: 1, locator: { page: 1 }, order: 1 }], stats: { pageCount: 1, sectionCount: 0, blockCount: 1, normalizedCharacters: 25, tableCount: 0, headingCount: 0, listCount: 0, captionCount: 0 }, warnings: [] }
const emptyAssets = (): KnowledgeAssetCollectionV03 => ({ rootDir: '', themeGroups: [], entities: [], relations: [], claims: [], modules: [], sources: [], registry: [] })
function loaded(kind: 'entity' | 'relation' | 'claim' | 'source', value: Record<string, unknown>): { kind: typeof kind; value: Record<string, unknown>; filePath: string; storageRef: string } { return { kind, value, filePath: '', storageRef: '' } }
function entity(id: string, name: string, entityType: EntityCandidate['entityType'] = 'company', extra: Record<string, unknown> = {}): EntityCandidate { return { candidateId: id, entityType, name, evidenceBlockRefs: [], reason: 'test', ...extra } }
function relation(id: string, relationType: RelationCandidate['relationType'], source: string, target: string, attributes?: Record<string, unknown>): RelationCandidate { return { candidateId: id, relationType, source: { candidateRef: source, mention: source }, target: { candidateRef: target, mention: target }, ...(attributes === undefined ? {} : { attributes }), evidenceBlockRefs: [], reason: 'test' } }
function claim(id: string, statement: string, subject: string, extra: Record<string, unknown> = {}): ClaimCandidate { return { candidateId: id, claimType: 'fact', statement, subjectRefs: [{ candidateRef: subject, mention: subject }], evidenceBlockRefs: [], reason: 'test', ...extra } }
function group(candidate: EntityCandidate | RelationCandidate | ClaimCandidate): ResolvedCandidateGroup { return { candidateId: candidate.candidateId, kind: 'entityType' in candidate ? 'entity' : 'relationType' in candidate ? 'relation' : 'claim', candidate } }
function assets(entities: Record<string, unknown>[] = [], relations: Record<string, unknown>[] = [], claims: Record<string, unknown>[] = [], sources: Record<string, unknown>[] = []): KnowledgeAssetCollectionV03 { return { ...emptyAssets(), entities: entities.map((value) => loaded('entity', value) as never), relations: relations.map((value) => loaded('relation', value) as never), claims: claims.map((value) => loaded('claim', value) as never), sources: sources.map((value) => loaded('source', value) as never) } }
function executor(response?: unknown): MockReasoningExecutor { const fallback = (request: { input: unknown }) => { const kind = ((request.input as { resolutionCase?: { caseKind?: string } }).resolutionCase?.caseKind); if (kind === 'EntityBindingCase') { if (response && typeof response === 'object' && ['equivalent_to', 'distinct_from_all', 'uncertain'].includes(String((response as { outcome?: unknown }).outcome))) return response; return { outcome: 'equivalent_to', targetAlias: 'existing-001', rationale: 'Bounded fixture equivalence.' } } return response ?? { outcome: 'equivalent', targetAlias: 'existing-001', rationale: 'Bounded fixture equivalence.' } }; const semanticResponse = typeof response === 'function' ? response : fallback; return new MockReasoningExecutor({ capabilities: { maxContextTokens: 10_000, maxOutputTokens: 10_000, structuredOutputSupport: true, maxConcurrency: 4 }, responses: { resolveSemanticCase: semanticResponse as never } }) }
async function resolve(groups: readonly ResolvedCandidateGroup[], existing: KnowledgeAssetCollectionV03 = emptyAssets(), response?: unknown, options: Record<string, unknown> = {}) { const mock = executor(response); const skill = new KnowledgeCurationSkill({ executor: mock }); const result = await resolveKnowledge({ assets: existing, document, groups, reportMap, plan, rawRef, skill, ...options } as never); return { result, mock } }
function plannerInput(groups: readonly ResolvedCandidateGroup[], resolution: Awaited<ReturnType<typeof resolveKnowledge>>, existing: KnowledgeAssetCollectionV03 = emptyAssets()): Parameters<typeof planKnowledgeChangeSet>[0] { return { knowledgeBaseId: 'kb-test', baseRevision: 0, workflowRunId: 'run-test', rawRef, rawManifest: { originalFilename: 'test.txt', suppliedMetadata: { title: 'Test', institution: null, author: null, publishedAt: null, sourceUrl: null } }, documentId: 'doc-test', document: { metadata: { originalFilename: 'test.txt', title: 'Test' } }, reportMap, plan, groups, intents: resolution.intents, bindings: resolution.bindings, assets: existing, resolutionReviews: resolution.reviewItems } }
function extractionFixture(unitId: string, entities: EntityCandidate[], relations: RelationCandidate[] = [], claims: ClaimCandidate[] = [], blockId = 'block-1'): { unit: AcceptedExtractionPlan['units'][number]; result: ValidatedExtractKnowledgeResult } { return { unit: { unitId, proposedUnitId: unitId, topic: 'test', semanticPurpose: 'test', primaryRefs: [], contextRefs: [], primaryBlockIds: [blockId], contextBlockIds: [] }, result: { entities, relations, claims, rejected: [], summary: { inputCounts: { entity: entities.length, relation: relations.length, claim: claims.length }, acceptedCounts: { entity: entities.length, relation: relations.length, claim: claims.length }, rejectedCounts: { entity: 0, relation: 0, claim: 0 }, rejectionCodes: [] } } } }

test('empty KB Entity becomes PlannedNew without reasoning', async () => { const { result, mock } = await resolve([group(entity('e', 'Acme'))]); assert.equal(result.bindings.get('e')?.state, 'PlannedNew'); assert.equal(result.intents[0]?.disposition, 'create'); assert.equal(mock.calls.length, 0) })
test('Company exact exchange and ticker binds deterministically', async () => { const { result, mock } = await resolve([group(entity('e', 'Acme', 'company', { semanticFields: { exchange: 'NYSE', ticker: 'ACM' } }))], assets([{ id: 'entity:acme', type: 'company', name: 'Acme Corp', exchange: 'nyse', ticker: 'acm', lifecycle: { status: 'active' } }])); assert.equal(result.bindings.get('e')?.state, 'BoundExisting'); assert.equal(result.bindings.get('e')?.ref, 'entity:acme'); assert.equal(mock.calls.length, 0) })
test('duplicate hard-key canonical Companies deterministically block', async () => { const { result } = await resolve([group(entity('e', 'Acme', 'company', { semanticFields: { exchange: 'NYSE', ticker: 'ACM' } }))], assets([{ id: 'entity:a', type: 'company', name: 'A', exchange: 'NYSE', ticker: 'ACM', lifecycle: { status: 'active' } }, { id: 'entity:b', type: 'company', name: 'B', exchange: 'NYSE', ticker: 'ACM', lifecycle: { status: 'active' } }])); assert.equal(result.blocked, true); assert.match(result.errors[0] ?? '', /integrity defect/) })
test('exact name is plausible EntityBindingCase, not automatic binding', async () => { const { result, mock } = await resolve([group(entity('e', 'Acme'))], assets([{ id: 'entity:acme', type: 'company', name: 'Acme', lifecycle: { status: 'active' } }]), { outcome: 'uncertain', rationale: 'Insufficient evidence.' }); assert.equal(result.intents[0]?.disposition, 'review'); assert.equal(mock.calls.length, 1); const input = mock.calls[0]?.input as { resolutionCase: { existingProjections: readonly unknown[] } }; assert.equal(JSON.stringify(input), JSON.stringify(input).replace('entity:acme', 'case-local')) })
test('alias-only match is bounded and case-local', async () => { const { result, mock } = await resolve([group(entity('e', '海力士'))], assets([{ id: 'entity:hynix', type: 'company', name: 'SK Hynix', aliases: ['海力士'], lifecycle: { status: 'active' } }]), { outcome: 'equivalent_to', targetAlias: 'existing-001', rationale: 'Alias and evidence agree.' }); assert.equal(result.bindings.get('e')?.ref, 'entity:hynix'); assert.equal(mock.calls.length, 1); assert.doesNotMatch(JSON.stringify(mock.calls[0]?.input), /entity:hynix/) })
test('semantic equivalent_to maps only the infrastructure target', async () => { const { result } = await resolve([group(entity('e', 'Alias'))], assets([{ id: 'entity:x', type: 'company', name: 'Canonical', aliases: ['Alias'], lifecycle: { status: 'active' } }]), { outcome: 'equivalent_to', targetAlias: 'existing-001', rationale: 'Same entity.' }); assert.equal(result.intents[0]?.targetRef, 'entity:x') })
test('distinct_from_all creates a PlannedNew binding', async () => { const { result } = await resolve([group(entity('e', 'Alias'))], assets([{ id: 'entity:x', type: 'company', name: 'Canonical', aliases: ['Alias'], lifecycle: { status: 'active' } }]), { outcome: 'distinct_from_all', rationale: 'Evidence distinguishes them.' }); assert.equal(result.bindings.get('e')?.state, 'PlannedNew'); assert.match(result.bindings.get('e')?.plannedRef ?? '', /^planned-entity-/) })
test('uncertain Entity binding becomes root Review', async () => { const { result } = await resolve([group(entity('e', 'Alias'))], assets([{ id: 'entity:x', type: 'company', name: 'Canonical', aliases: ['Alias'], lifecycle: { status: 'active' } }]), { outcome: 'uncertain', rationale: 'Need review.' }); assert.equal(result.intents[0]?.disposition, 'review'); assert.equal(result.reviewItems[0]?.dependency, false) })
test('Entity with no new fields produces no_op', async () => { const { result } = await resolve([group(entity('e', 'Acme'))], assets([{ id: 'entity:acme', type: 'company', name: 'Acme', lifecycle: { status: 'active' } }])); assert.equal(result.intents[0]?.disposition, 'no_op') })
test('Entity missing alias produces enrich_existing', async () => { const { result } = await resolve([group(entity('e', 'Acme', 'company', { aliases: ['ACM'] }))], assets([{ id: 'entity:acme', type: 'company', name: 'Acme', lifecycle: { status: 'active' } }])); assert.equal(result.intents[0]?.disposition, 'enrich_existing') })
test('Entity conflicting populated state becomes Review', async () => { const { result } = await resolve([group(entity('e', 'Acme', 'company', { semanticFields: { exchange: 'NASDAQ', ticker: 'ACM' } }))], assets([{ id: 'entity:acme', type: 'company', name: 'Acme', exchange: 'NYSE', ticker: 'ACM', lifecycle: { status: 'active' } }])); assert.equal(result.intents[0]?.disposition, 'review') })
test('description formatting variants retain one description without Review', () => { const consolidated = consolidateExtractions([extractionFixture('unit-a', [entity('a', 'Acme', 'company', { description: 'Acme  Corporation' })]), extractionFixture('unit-b', [entity('b', ' ＡＣＭＥ ', 'company', { description: ' Acme Corporation ' })])]); assert.equal(consolidated.groups.length, 1); assert.ok((consolidated.groups[0]?.candidate as EntityCandidate).description); assert.equal(consolidated.reviewConstraints.length, 0) })
test('description-only conflict is non-blocking and sticky', async () => { const consolidated = consolidateExtractions([extractionFixture('unit-a', [entity('a', 'Acme', 'company', { description: 'Description A' })]), extractionFixture('unit-b', [entity('b', 'Acme', 'company', { description: 'Description B' })]), extractionFixture('unit-c', [entity('c', 'Acme', 'company', { description: 'Description A' })])]); const merged = consolidated.groups.find((item) => item.kind === 'entity')?.candidate as EntityCandidate; assert.equal(merged.description, undefined); assert.equal(consolidated.reviewConstraints.length, 1); assert.equal(consolidated.reviewConstraints[0]?.blocking, false); assert.deepEqual(consolidated.reviewConstraints[0]?.conflictingFields, ['description']); const { result, mock } = await resolve(consolidated.groups, emptyAssets(), undefined, { consolidationReviews: consolidated.reviewConstraints }); assert.equal(result.bindings.get(merged.candidateId)?.state, 'PlannedNew'); assert.equal(result.intents.find((item) => item.candidateRef === merged.candidateId)?.disposition, 'create'); assert.equal(result.reviewItems.length, 0); assert.equal(mock.calls.length, 0) })
test('description-only conflict does not isolate dependent Relation or Claim', async () => { const source = entity('a', 'Acme', 'company', { description: 'Description A' }); const target = entity('b', 'Product', 'product'); const rel = relation('r', 'offers_product', 'a', 'b'); const cl = claim('c', 'Acme offers Product', 'a'); const consolidated = consolidateExtractions([extractionFixture('unit-a', [source, target], [rel], [cl]), extractionFixture('unit-b', [entity('a2', 'Acme', 'company', { description: 'Description B' })], [], [], 'block-2')]); const { result } = await resolve(consolidated.groups, emptyAssets(), undefined, { consolidationReviews: consolidated.reviewConstraints }); assert.equal(consolidated.reviewConstraints.filter((item) => item.blocking).length, 0); const relationIntent = result.intents.find((item) => item.candidateKind === 'relation'); const claimIntent = result.intents.find((item) => item.candidateKind === 'claim'); assert.equal(relationIntent?.disposition, 'create'); assert.equal(claimIntent?.disposition, 'create'); assert.equal(result.reviewItems.filter((item) => item.dependency).length, 0) })
test('different complete Company hard identities remain separate', async () => { const first = entity('a', 'Acme', 'company', { semanticFields: { ticker: '600000', exchange: 'SSE' } }); const second = entity('b', 'Acme', 'company', { semanticFields: { ticker: '300000', exchange: 'SZSE' } }); const target = entity('p', 'Product', 'product'); const consolidated = consolidateExtractions([extractionFixture('unit-a', [first, target], [relation('r', 'offers_product', 'a', 'p')], [claim('c', 'Acme offers Product', 'a')]), extractionFixture('unit-b', [second], [], [], 'block-2')]); const companies = consolidated.groups.filter((item) => item.kind === 'entity' && (item.candidate as EntityCandidate).entityType === 'company'); assert.equal(companies.length, 2); assert.equal(consolidated.reviewConstraints.length, 0); const { result } = await resolve(consolidated.groups, emptyAssets(), undefined, { consolidationReviews: consolidated.reviewConstraints }); const relationGroup = consolidated.groups.find((item) => item.kind === 'relation'); const claimGroup = consolidated.groups.find((item) => item.kind === 'claim'); assert.equal(result.reviewItems.length, 0); assert.equal(result.intents.find((item) => item.candidateRef === relationGroup?.candidateId)?.disposition, 'create'); assert.equal(result.intents.find((item) => item.candidateRef === claimGroup?.candidateId)?.disposition, 'create') })
test('Company missing hard fields are safely enriched during consolidation', () => { const consolidated = consolidateExtractions([extractionFixture('unit-a', [entity('a', 'Acme', 'company', { semanticFields: {} })]), extractionFixture('unit-b', [entity('b', 'Acme', 'company', { semanticFields: { ticker: '600000', exchange: 'SSE' } })])]); const merged = consolidated.groups[0]?.candidate as EntityCandidate; assert.deepEqual(merged.semanticFields, { exchange: 'SH', ticker: '600000' }); assert.equal(consolidated.reviewConstraints.length, 0) })
test('Company legalName conflict is field-level and non-blocking', async () => { const consolidated = consolidateExtractions([extractionFixture('unit-a', [entity('a', 'Acme', 'company', { semanticFields: { ticker: '600000', exchange: 'SSE', legalName: 'Acme A' } })]), extractionFixture('unit-b', [entity('b', 'Acme', 'company', { semanticFields: { ticker: '600000', exchange: 'SSE', legalName: 'Acme B' } })])]); const merged = consolidated.groups[0]?.candidate as EntityCandidate; assert.equal(merged.semanticFields?.legalName, undefined); assert.equal(consolidated.reviewConstraints.length, 1); assert.equal(consolidated.reviewConstraints[0]?.blocking, false); const { result } = await resolve(consolidated.groups, emptyAssets(), undefined, { consolidationReviews: consolidated.reviewConstraints }); assert.equal(result.intents[0]?.disposition, 'create') })
test('Relation with PlannedNew endpoint is create intent', async () => { const { result } = await resolve([group(entity('a', 'A')), group(entity('b', 'B', 'product')), group(relation('r', 'offers_product', 'a', 'b'))]); assert.equal(result.intents.find((item) => item.candidateRef === 'r')?.disposition, 'create') })
test('Relation with existing endpoints and no match is create', async () => { const groups = [group(entity('a', 'A')), group(entity('b', 'B', 'product')), group(relation('r', 'offers_product', 'a', 'b'))]; const { result } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }, { id: 'entity:b', type: 'product', name: 'B', lifecycle: { status: 'active' } }])); assert.equal(result.intents.find((item) => item.candidateRef === 'r')?.disposition, 'create') })
test('exact Relation uses merge_evidence with no Relation conflict case', async () => { const groups = [group(entity('a', 'A')), group(entity('b', 'B', 'product')), group(relation('r', 'offers_product', 'a', 'b'))]; const old = { id: 'relation:r', type: 'offers_product', sourceRef: 'entity:a', targetRef: 'entity:b', sourceRefs: ['source:old'], lifecycle: { status: 'active' } }; const { result, mock } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }, { id: 'entity:b', type: 'product', name: 'B', lifecycle: { status: 'active' } }], [old])); assert.equal(result.intents.find((item) => item.candidateRef === 'r')?.disposition, 'merge_evidence'); assert.equal(mock.calls.filter((call) => ((call.input as { resolutionCase?: { caseKind?: string } }).resolutionCase?.caseKind) === 'RelationConflictCase').length, 0) })
test('Relation additive attributes use enrich_existing', async () => { const groups = [group(entity('a', 'A')), group(entity('b', 'B', 'product')), group(relation('r', 'offers_product', 'a', 'b', { } as Record<string, unknown>))]; const old = { id: 'relation:r', type: 'offers_product', sourceRef: 'entity:a', targetRef: 'entity:b', sourceRefs: ['source:old'], lifecycle: { status: 'active' } }; const { result } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }, { id: 'entity:b', type: 'product', name: 'B', lifecycle: { status: 'active' } }], [old])); assert.equal(result.intents.find((item) => item.candidateRef === 'r')?.disposition, 'merge_evidence') })
test('Relation conflicting attributes invokes RelationConflictCase', async () => { const groups = [group(entity('a', 'A')), group(entity('b', 'B', 'product')), group(relation('r', 'offers_product', 'a', 'b', { importance: 'high' }))]; const old = { id: 'relation:r', type: 'offers_product', sourceRef: 'entity:a', targetRef: 'entity:b', attributes: { importance: 'low' }, sourceRefs: ['source:old'], lifecycle: { status: 'active' } }; const { result } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }, { id: 'entity:b', type: 'product', name: 'B', lifecycle: { status: 'active' } }], [old]), { outcome: 'uncertain', rationale: 'Conflict needs review.' }); assert.equal(result.intents.find((item) => item.candidateRef === 'r')?.disposition, 'review') })
test('RelationConflict equivalent maps to merge_evidence', async () => { const groups = [group(entity('a', 'A')), group(entity('b', 'B', 'product')), group(relation('r', 'offers_product', 'a', 'b', { importance: 'high' }))]; const old = { id: 'relation:r', type: 'offers_product', sourceRef: 'entity:a', targetRef: 'entity:b', attributes: { importance: 'low' }, sourceRefs: ['source:old'], lifecycle: { status: 'active' } }; const { result } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }, { id: 'entity:b', type: 'product', name: 'B', lifecycle: { status: 'active' } }], [old]), { outcome: 'equivalent', targetAlias: 'existing-001', rationale: 'Same relation.' }); assert.equal(result.intents.find((item) => item.candidateRef === 'r')?.disposition, 'merge_evidence') })
test('RelationConflict state_changed maps to replace_state', async () => { const groups = [group(entity('a', 'A')), group(entity('b', 'B', 'product')), group(relation('r', 'offers_product', 'a', 'b', { importance: 'high' }))]; const old = { id: 'relation:r', type: 'offers_product', sourceRef: 'entity:a', targetRef: 'entity:b', attributes: { importance: 'low' }, sourceRefs: ['source:old'], lifecycle: { status: 'active' } }; const { result } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }, { id: 'entity:b', type: 'product', name: 'B', lifecycle: { status: 'active' } }], [old]), { outcome: 'state_changed', targetAlias: 'existing-001', rationale: 'State changed.' }); assert.equal(result.intents.find((item) => item.candidateRef === 'r')?.disposition, 'replace_state') })
test('RelationConflict coexists and contradicts remain Review', async () => { for (const outcome of ['coexists', 'contradicts'] as const) { const groups = [group(entity('a', 'A')), group(entity('b', 'B', 'product')), group(relation('r', 'offers_product', 'a', 'b', { importance: 'high' }))]; const old = { id: 'relation:r', type: 'offers_product', sourceRef: 'entity:a', targetRef: 'entity:b', attributes: { importance: 'low' }, sourceRefs: ['source:old'], lifecycle: { status: 'active' } }; const { result } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }, { id: 'entity:b', type: 'product', name: 'B', lifecycle: { status: 'active' } }], [old]), { outcome, rationale: outcome }); assert.equal(result.intents.find((item) => item.candidateRef === 'r')?.disposition, 'review') } })
test('RelationConflict invalid maps to reject', async () => { const groups = [group(entity('a', 'A')), group(entity('b', 'B', 'product')), group(relation('r', 'offers_product', 'a', 'b', { importance: 'high' }))]; const old = { id: 'relation:r', type: 'offers_product', sourceRef: 'entity:a', targetRef: 'entity:b', attributes: { importance: 'low' }, sourceRefs: ['source:old'], lifecycle: { status: 'active' } }; const { result } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }, { id: 'entity:b', type: 'product', name: 'B', lifecycle: { status: 'active' } }], [old]), { outcome: 'invalid', rationale: 'Invalid.' }); assert.equal(result.intents.find((item) => item.candidateRef === 'r')?.disposition, 'reject') })
test('Claim exact identity uses merge_evidence', async () => { const groups = [group(entity('a', 'A')), group(claim('c', 'A grows', 'a'))]; const old = { id: 'claim:old', claimType: 'fact', statement: 'A grows', subjectRefs: ['entity:a'], sourceRefs: ['source:old'], lifecycle: { status: 'active' } }; const { result } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }], [], [old])); assert.equal(result.intents.find((item) => item.candidateRef === 'c')?.disposition, 'merge_evidence') })
test('Claim exact evidence merge preserves source and provenance in planner', () => { const groups = [group(entity('a', 'A')), group(claim('c', 'A grows', 'a', { evidenceBlockRefs: ['block-1'] }))]; const old = { id: 'claim:old', claimType: 'fact', statement: 'A grows', subjectRefs: ['entity:a'], sourceRefs: ['source:old'], provenance: [{ sourceRef: 'source:old', rawRef, locator: 'old', chunkRef: null }], lifecycle: { status: 'active' } }; return resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }], [], [old])).then((resolution) => { const result = planKnowledgeChangeSet(plannerInput(groups, resolution.result, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }], [], [old]))); const op = result.changeSet?.knowledgeOperations.find((item) => item.type === 'update'); assert.equal(op?.type, 'update'); if (op?.type === 'update' && 'sourceRefs' in op.object) { assert.deepEqual(op.object.sourceRefs, ['source:old', allocateSourceId({ sourceUrl: null, publishedAt: null, title: 'Test', rawRef })].sort()); assert.equal((op.object as unknown as { provenance?: unknown[] }).provenance?.length, 2) } }) })
test('Claim with no plausible conflict is create', async () => { const groups = [group(entity('a', 'A')), group(claim('c', 'A grows', 'a'))]; const { result } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }])); assert.equal(result.intents.find((item) => item.candidateRef === 'c')?.disposition, 'create') })
test('Claim same subject and type conflict invokes bounded case', async () => { const groups = [group(entity('a', 'A')), group(claim('c', 'A grows rapidly', 'a'))]; const old = { id: 'claim:old', claimType: 'fact', statement: 'A grows slowly', subjectRefs: ['entity:a'], temporal: null, sourceRefs: ['source:old'], lifecycle: { status: 'active' } }; const { result, mock } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }], [], [old]), { outcome: 'uncertain', rationale: 'Conflict uncertain.' }); assert.equal(result.intents.find((item) => item.candidateRef === 'c')?.disposition, 'review'); assert.equal(mock.calls.length, 1) })
test('Claim supersedes maps to supersede', async () => { const groups = [group(entity('a', 'A')), group(claim('c', 'A grows rapidly', 'a'))]; const old = { id: 'claim:old', claimType: 'fact', statement: 'A grows slowly', subjectRefs: ['entity:a'], sourceRefs: ['source:old'], lifecycle: { status: 'active' } }; const { result } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }], [], [old]), { outcome: 'supersedes', targetAlias: 'existing-001', rationale: 'Newer fact.' }); assert.equal(result.intents.find((item) => item.candidateRef === 'c')?.disposition, 'supersede') })
test('Claim coexists maps to a distinct create', async () => { const groups = [group(entity('a', 'A')), group(claim('c', 'A has a different view', 'a'))]; const old = { id: 'claim:old', claimType: 'viewpoint', statement: 'A has an older view', subjectRefs: ['entity:a'], sourceRefs: ['source:old'], lifecycle: { status: 'active' } }; const candidate = { ...groups[1]!.candidate as ClaimCandidate, claimType: 'viewpoint' as const }; const { result } = await resolve([groups[0]!, group(candidate)], assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }], [], [old]), { outcome: 'coexists', rationale: 'Distinct supported view.' }); assert.equal(result.intents.find((item) => item.candidateRef === 'c')?.disposition, 'create') })
test('contradictory forecast may coexist while fact is Review', async () => { for (const claimType of ['forecast', 'fact'] as const) { const groups = [group(entity('a', 'A')), group({ ...claim('c', 'A outcome', 'a'), claimType })]; const old = { id: 'claim:old', claimType, statement: 'A prior outcome', subjectRefs: ['entity:a'], sourceRefs: ['source:old'], lifecycle: { status: 'active' } }; const { result } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A', lifecycle: { status: 'active' } }], [], [old]), { outcome: 'contradicts', rationale: 'Contradiction.' }); assert.equal(result.intents.find((item) => item.candidateRef === 'c')?.disposition, claimType === 'forecast' ? 'create' : 'review') } })
test('Claim retrieval overflow becomes explicit Review', async () => { const e = { id: 'entity:a', type: 'company', name: 'A', exchange: 'NYSE', ticker: 'A', lifecycle: { status: 'active' } }; const old = Array.from({ length: 9 }, (_, index) => ({ id: `claim:${index}`, claimType: 'fact', statement: `Prior statement ${index}`, subjectRefs: ['entity:a'], sourceRefs: ['source:old'], lifecycle: { status: 'active' } })); const { result, mock } = await resolve([group(entity('a', 'A', 'company', { semanticFields: { exchange: 'NYSE', ticker: 'A' } })), group(claim('c', 'new statement', 'a'))], assets([e], [], old)); assert.equal(result.intents.find((item) => item.candidateRef === 'c')?.disposition, 'review'); assert.equal(mock.calls.length, 0); assert.match(result.reviewItems.find((item) => item.candidateId === 'c')?.rationale ?? '', /overflow/) })
test('dependent Relation and Claim isolate when Entity is Review', async () => { const groups = [group(entity('a', 'Alias')), group(entity('b', 'B', 'product')), group(relation('r', 'offers_product', 'a', 'b')), group(claim('c', 'Alias matters', 'a'))]; const { result } = await resolve(groups, assets([{ id: 'entity:x', type: 'company', name: 'Alias' }, { id: 'entity:b', type: 'product', name: 'B' }]), { outcome: 'uncertain', rationale: 'Entity uncertain.' }); assert.equal(result.intents.find((item) => item.candidateRef === 'r')?.disposition, 'review'); assert.equal(result.intents.find((item) => item.candidateRef === 'c')?.disposition, 'review'); assert.equal(result.reviewItems.filter((item) => item.dependency).length, 2) })
test('Resolution barrier rejects duplicate intents', () => { const g = group(entity('e', 'E')); const bindings = new Map([['e', { candidateId: 'e', state: 'PlannedNew' as const, plannedRef: 'planned-entity-x', plausibleMatches: [] }]]); const one = { candidateRef: 'e', candidateKind: 'entity' as const, disposition: 'create' as const, targetRef: 'planned-entity-x', semanticBasis: { rationale: 'x' }, evidenceRefs: [] }; assert.equal(resolveResolutionIntentBarrier([g], [one, one], bindings).valid, false) })
test('Resolution barrier rejects missing intents', () => { const g = group(entity('e', 'E')); assert.equal(resolveResolutionIntentBarrier([g], [], new Map()).valid, false) })
test('Resolution barrier rejects unresolved safe local refs', () => { const g = group(entity('e', 'E')); const binding = { candidateId: 'e', state: 'PlannedNew' as const, plannedRef: 'planned-entity-x', plausibleMatches: [] }; const intent = { candidateRef: 'e', candidateKind: 'entity' as const, disposition: 'create' as const, targetRef: 'local-e', semanticBasis: { rationale: 'x' }, evidenceRefs: [] }; assert.equal(resolveResolutionIntentBarrier([g], [intent], new Map([['e', binding]])).valid, false) })
test('fresh synthetic graph scales without semantic resolution calls', async () => { const groups = Array.from({ length: 120 }, (_, index) => group(entity(`e-${index}`, `Fresh ${index}`))); const { result, mock } = await resolve(groups); assert.equal(result.semanticCaseCalls, 0); assert.equal(mock.calls.length, 0); assert.equal(result.intents.length, 120); assert.equal(result.intents.every((item) => item.disposition === 'create'), true) })
test('mature KB reasoning scales with ambiguity rather than candidate count', async () => { const groups = Array.from({ length: 20 }, (_, index) => group(entity(`e-${index}`, index === 0 ? 'Ambiguous' : `Fresh ${index}`))); const { result, mock } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'Ambiguous' }]), { outcome: 'uncertain', rationale: 'Ambiguous.' }); assert.equal(mock.calls.length, 1); assert.equal(result.semanticCaseCalls, 1); assert.equal(result.intents.length, 20) })
test('planner allocates durable IDs only after ResolutionIntent', async () => { const groups = [group(entity('e', 'New'))]; const resolution = await resolve(groups); const planned = resolution.result.bindings.get('e')?.plannedRef; assert.match(planned ?? '', /^planned-entity-/); const result = planKnowledgeChangeSet(plannerInput(groups, resolution.result)); assert.equal(result.entityResolutions[0]?.status, 'created'); assert.match(result.entityResolutions[0]?.canonicalId ?? '', /^entity:/) })
test('valid Claim temporal survives planning and publication metadata stays separate', async () => { const temporal = { asOf: '2026-08-05', scope: { type: 'period' as const, start: '2026-01-01', end: '2026-12-31', label: '2026E' } }; const groups = [group(entity('e', 'Alpha')), group(claim('c', 'Alpha has the stated outlook', 'e', { temporal }))]; const resolution = await resolve(groups); const input = plannerInput(groups, resolution.result); const planned = planKnowledgeChangeSet({ ...input, rawManifest: { ...input.rawManifest, suppliedMetadata: { ...input.rawManifest.suppliedMetadata, publishedAt: '2026-08-05' } } }); const operation = planned.changeSet?.knowledgeOperations.find((item) => item.type === 'create' && item.object.id.startsWith('claim:')); assert.equal(operation?.type, 'create'); if (operation?.type === 'create') assert.deepEqual((operation.object as { temporal?: unknown }).temporal, temporal); const source = planned.changeSet?.sourceOperations[0]; assert.equal(source?.type, 'source_create'); if (source?.type === 'source_create') assert.equal(source.source.publishedAt, '2026-08-05'); const noTemporalGroups = [group(entity('e', 'Beta')), group(claim('c', 'Beta has the stated outlook', 'e'))]; const noTemporalResolution = await resolve(noTemporalGroups); const noTemporalPlan = planKnowledgeChangeSet({ ...plannerInput(noTemporalGroups, noTemporalResolution.result), rawManifest: { ...input.rawManifest, suppliedMetadata: { ...input.rawManifest.suppliedMetadata, publishedAt: '2026-08-05' } } }); const noTemporalClaim = noTemporalPlan.changeSet?.knowledgeOperations.find((item) => item.type === 'create' && item.object.id.startsWith('claim:')); assert.equal(noTemporalClaim?.type, 'create'); if (noTemporalClaim?.type === 'create') assert.equal('temporal' in noTemporalClaim.object, false) })
test('accepted Candidate temporal variants remain accepted by canonical ChangeSet validation', async () => { const variants = [undefined, null, { asOf: '2026-08-05', scope: { type: 'period', start: '2026-01-01', end: '2026-12-31', label: '2026E' } }] as const; const extractionUnit = { proposedUnitId: 'unit-1', topic: 'test', semanticPurpose: 'test', primaryRefs: [{ kind: 'block' as const, blockId: 'block-1' }], contextRefs: [] }; for (const temporal of variants) { const rawClaim = { candidateId: 'claim-1', claimType: 'fact', statement: 'Alpha has the stated outlook.', subjectRefs: [{ candidateRef: 'alpha', mention: 'Alpha' }], evidenceBlockRefs: ['block-1'], reason: 'direct statement', ...(temporal === undefined ? {} : { temporal }) }; const extracted = validateExtractKnowledge({ entities: [{ candidateId: 'alpha', entityType: 'company', name: 'Alpha', evidenceBlockRefs: ['block-1'], reason: 'named' }], relations: [], claims: [rawClaim] }, { document, reportMap, unit: extractionUnit, schemaContext: buildCurationSchemaContext('knowledge_extraction') }); assert.equal(extracted.claims.length, 1); assert.equal(extracted.rejected.length, 0); const groups = [group(extracted.entities[0]!), group(extracted.claims[0]!)]; const resolution = await resolve(groups); const planned = planKnowledgeChangeSet(plannerInput(groups, resolution.result)); assert.equal(planned.changeSet !== undefined, true); const root = await createKnowledgeBase(); try { const handle = await new KnowledgeBaseRegistry().mount(root); const validation = await validateKnowledgeChangeSetV03(handle, planned.changeSet!, { mode: 'dry_run', virtualRawRefs: [rawRef] }); assert.equal(validation.report.status, 'passed', JSON.stringify(validation.report.errors)); } finally { await removeKnowledgeBase(root) } } })
test('Planner isolates a bypassed malformed Claim temporal and preserves safe ChangeSet operations', async () => { const malformed = claim('bad', 'Alpha has a malformed temporal', 'e', { temporal: { asOf: '2026E', scope: { type: 'period', start: null, end: null, label: null } } }); const safe = claim('safe', 'Alpha has a safe temporal', 'e', { temporal: { asOf: null, scope: { type: 'period', start: null, end: null, label: '2026E' }, }, evidenceBlockRefs: ['block-1'] }); const groups = [group(entity('e', 'Alpha')), group(safe), group(malformed as unknown as ClaimCandidate)]; const resolution = await resolve(groups); const planned = planKnowledgeChangeSet(plannerInput(groups, resolution.result)); const operations = planned.changeSet?.knowledgeOperations ?? []; assert.equal(operations.filter((item) => item.type === 'create' && item.object.id.startsWith('claim:')).length, 1); assert.equal(operations.some((item) => item.type === 'create' && item.object.id.includes('bad')), false); const review = planned.reviewItems.find((item) => item.candidateId === 'bad'); assert.equal(review?.origin, 'planner'); assert.match(review?.rationale ?? '', /Claim temporal is not Schema 0\.3 admissible/); assert.equal(planned.changeSet !== undefined, true); const root = await createKnowledgeBase(); try { const handle = await new KnowledgeBaseRegistry().mount(root); const validation = await validateKnowledgeChangeSetV03(handle, planned.changeSet!, { mode: 'dry_run', virtualRawRefs: [rawRef] }); assert.equal(validation.report.status, 'passed', JSON.stringify(validation.report.errors)); } finally { await removeKnowledgeBase(root) } })
test('review-only resolution creates no unreferenced Source', async () => { const groups = [group(entity('e', 'Alias'))]; const resolution = await resolve(groups, assets([{ id: 'entity:x', type: 'company', name: 'Alias' }]), { outcome: 'uncertain', rationale: 'Review.' }); const result = planKnowledgeChangeSet(plannerInput(groups, resolution.result, assets([{ id: 'entity:x', type: 'company', name: 'Alias' }]))); assert.equal(result.changeSet, undefined); assert.equal(result.safeOperationCount, 0) })
test('symmetric Relation identity resolves reverse orientation', async () => { const groups = [group(entity('a', 'A')), group(entity('b', 'B')), group(relation('r', 'competes_with', 'a', 'b'))]; const old = { id: 'relation:old', type: 'competes_with', sourceRef: 'entity:b', targetRef: 'entity:a', sourceRefs: ['source:old'], lifecycle: { status: 'active' } }; const { result } = await resolve(groups, assets([{ id: 'entity:a', type: 'company', name: 'A' }, { id: 'entity:b', type: 'company', name: 'B' }], [old])); assert.equal(result.intents.find((item) => item.candidateRef === 'r')?.disposition, 'merge_evidence') })
test('bounded extraction still retries only failed units', async () => { const calls: string[] = []; const config = { maxExtractionUnits: 64, maxPlanAttempts: 2, maxExtractionAttempts: 3, maxConcurrency: 1 } as EffectiveConfig; const empty = (): ValidatedExtractKnowledgeResult => ({ entities: [], relations: [], claims: [], rejected: [], summary: { inputCounts: { entity: 0, relation: 0, claim: 0 }, acceptedCounts: { entity: 0, relation: 0, claim: 0 }, rejectedCounts: { entity: 0, relation: 0, claim: 0 }, rejectionCodes: [] } }); const input = { skill: { extractKnowledge: async ({ unit }: { unit: { unitId: string } }) => { calls.push(unit.unitId); if (unit.unitId === 'two' && calls.filter((id) => id === 'two').length === 1) throw new KnowledgeCurationError('invalid_model_output', 'bad'); return empty() } } } as never; const units = ['one', 'two'].map((unitId) => ({ unitId, proposedUnitId: unitId, topic: 't', semanticPurpose: 't', primaryRefs: [], contextRefs: [], primaryBlockIds: [], contextBlockIds: [] })); const result = await boundedExtract(input, {} as never, {} as never, units, 1, config); assert.deepEqual(calls, ['one', 'two', 'two']); assert.equal(result.summaries[1]?.attempts, 2) })
test('review summary keeps knowledge-resolution stage visible', () => { const summary = normalizeReviewSummary({ resolutionReviews: [{ candidateId: 'e', kind: 'entity', rationale: 'Ambiguous binding', dependentCandidateIds: [], stage: 'semantic_case', category: 'reconciliation_review', origin: 'semantic_case', dependency: false, reviewKey: 'case-e' }], candidateGroups: [group(entity('e', 'E'))] }); assert.equal(summary.total, 1); assert.equal(summary.byCategory.reconciliation_review, 1) })
test('ReviewSummary frozen shape remains stable', () => { const summary = emptyReviewSummary(); assert.equal(summary.total, 0); assert.deepEqual(Object.keys(summary.byCandidateKind).sort(), ['claim', 'entity', 'relation', 'workflow_level']) })
test('no-op execution records replay without revision change', async () => { const root = await createKnowledgeBase({ knowledgeBaseId: 'kb-noop-resolution' }); try { const record = { workflowRunId: 'run-noop', knowledgeBaseId: 'kb-noop-resolution', rawRef, documentId: 'doc', workflowInputFingerprint: 'fp', status: 'completed' as const, writeStatus: 'no_changes' as const, baseRevision: 0, committedRevision: 0, reviewSummary: emptyReviewSummary(), completedAt: 'now', errors: [] }; assert.equal((await writeNoOpExecutionRecord(root, record)).kind, 'written'); assert.equal((await writeNoOpExecutionRecord(root, record)).kind, 'replay') } finally { await removeKnowledgeBase(root) } })
test('semantic cases project bounded real document evidence only', async () => { const caseDocument = { ...document, normalizedText: 'FULL NORMALIZED TEXT MUST NOT LEAK', blocks: [{ ...document.blocks[0]!, text: 'SK海力士预计2026年HBM收入增长...', page: 3 }, { blockId: 'unrelated', type: 'paragraph' as const, text: 'UNRELATED BLOCK MUST NOT LEAK', sectionRef: null, page: 4, locator: { page: 4 }, order: 2 }] }; const casePlan = { units: [{ unitId: 'unit-1', proposedUnitId: 'unit-1', topic: 'test', semanticPurpose: 'test', primaryRefs: [], contextRefs: [], primaryBlockIds: ['block-1'], contextBlockIds: ['unrelated'] }], excludedBlockIds: [], estimatedContextTokens: {} }; const { mock } = await resolve([group(entity('e', 'Alpha', 'company', { evidenceBlockRefs: ['block-1'] }))], assets([{ id: 'entity:alpha', type: 'company', name: 'Alpha', lifecycle: { status: 'active' } }]), { outcome: 'equivalent_to', targetAlias: 'existing-001', rationale: 'Same bounded evidence.' }, { document: caseDocument, plan: casePlan }); const request = mock.calls.find((item) => item.operation === 'resolveSemanticCase'); const input = request?.input as { resolutionCase: { evidence: readonly { blockId: string; blockType: string; sectionRef: string | null; page: number | null; role: string; textExcerpt: string }[] } }; assert.deepEqual(input.resolutionCase.evidence, [{ blockId: 'block-1', blockType: 'paragraph', sectionRef: null, page: 3, role: 'primary', textExcerpt: 'SK海力士预计2026年HBM收入增长...' }]); const serialized = JSON.stringify(request?.input); assert.equal(serialized.includes('UNRELATED BLOCK MUST NOT LEAK'), false); assert.equal(serialized.includes('FULL NORMALIZED TEXT MUST NOT LEAK'), false); assert.equal(serialized.includes('reportMap'), false); assert.equal(serialized.includes('entity:alpha'), false) })
test('missing semantic evidence block becomes explicit Review without omission', async () => { const { result, mock } = await resolve([group(entity('e', 'Alpha', 'company', { evidenceBlockRefs: ['missing-block'] }))], assets([{ id: 'entity:alpha', type: 'company', name: 'Alpha', lifecycle: { status: 'active' } }]), { outcome: 'equivalent_to', targetAlias: 'existing-001', rationale: 'Should not execute.' }); assert.equal(mock.calls.length, 0); assert.match(result.reviewItems[0]?.rationale ?? '', /semantic_case_missing_evidence_block/) })
test('semantic case capacity uses the final evidence-bearing case payload', async () => { const { result, mock } = await resolve([group(entity('e', 'Alpha', 'company', { evidenceBlockRefs: ['block-1'] }))], assets([{ id: 'entity:alpha', type: 'company', name: 'Alpha', lifecycle: { status: 'active' } }]), undefined, { maxContextTokens: 1 }); assert.equal(mock.calls.length, 0); assert.match(result.reviewItems[0]?.rationale ?? '', /semantic_case_capacity_exceeded/) })
test('Claim Conflict cases carry incoming and existing source context without durable refs', async () => { const existing = assets([{ id: 'entity:alpha', type: 'company', name: 'Alpha', exchange: 'NYSE', ticker: 'ALPHA', lifecycle: { status: 'active' } }], [], [{ id: 'claim:old', claimType: 'fact', statement: 'Alpha grows slowly', subjectRefs: ['entity:alpha'], sourceRefs: ['source:old'], lifecycle: { status: 'active' } }], [{ id: 'source:old', title: 'Existing filing', institution: 'B', author: 'Author B', publishedAt: '2026-05-01', sourceType: 'official_disclosure', sourceReliability: 'high', rawRefs: [rawRef], lifecycle: { status: 'active' } }]); const groups = [group(entity('a', 'Alpha', 'company', { semanticFields: { exchange: 'NYSE', ticker: 'ALPHA' } })), group(claim('c', 'Alpha grows rapidly', 'a', { evidenceBlockRefs: ['block-1'] }))]; const { result, mock } = await resolve(groups, existing, (request: { input: unknown }) => ((request.input as { resolutionCase: { caseKind: string } }).resolutionCase.caseKind === 'EntityBindingCase' ? { outcome: 'equivalent_to', targetAlias: 'existing-001', rationale: 'Same company.' } : { outcome: 'uncertain', rationale: 'Source chronology is context only.' }), { incomingSourceContext: { title: 'Incoming filing', institution: 'A', author: 'Author A', publishedAt: '2026-08-01', sourceType: 'official_disclosure', reliability: 'high' } }); const request = mock.calls.find((item) => item.operation === 'resolveSemanticCase' && ((item.input as { resolutionCase?: { caseKind?: string } }).resolutionCase?.caseKind === 'ClaimConflictCase')); const input = request?.input as { resolutionCase: { sourceContext: Record<string, unknown>; existingProjections: readonly { projection: { sources: readonly Record<string, unknown>[] } }[]; candidateProjection: { temporal?: unknown } } }; assert.equal(input.resolutionCase.sourceContext.institution, 'A'); assert.equal(input.resolutionCase.sourceContext.publishedAt, '2026-08-01'); assert.equal(input.resolutionCase.existingProjections[0]?.projection.sources[0]?.institution, 'B'); assert.equal(input.resolutionCase.existingProjections[0]?.projection.sources[0]?.publishedAt, '2026-05-01'); const serialized = JSON.stringify(input); assert.equal(serialized.includes('source:old'), false); assert.equal(serialized.includes(rawRef), false); assert.equal(result.intents.find((item) => item.candidateRef === 'c')?.disposition, 'review') })
test('publication chronology alone does not force Claim supersession or alter Claim temporal scope', async () => { const temporal = { asOf: '2026-08-01', scope: { type: 'point_in_time', start: null, end: null, label: 'August' } }; const existing = assets([{ id: 'entity:alpha', type: 'company', name: 'Alpha', exchange: 'NYSE', ticker: 'ALPHA', lifecycle: { status: 'active' } }], [], [{ id: 'claim:old', claimType: 'fact', statement: 'Alpha grows slowly', subjectRefs: ['entity:alpha'], temporal, sourceRefs: ['source:old'], lifecycle: { status: 'active' } }], [{ id: 'source:old', title: 'Old', institution: 'B', publishedAt: '2026-05-01', sourceType: 'official_disclosure', lifecycle: { status: 'active' } }]); const candidate = claim('c', 'Alpha grows rapidly', 'a', { temporal }); const { result, mock } = await resolve([group(entity('a', 'Alpha', 'company', { semanticFields: { exchange: 'NYSE', ticker: 'ALPHA' } })), group(candidate)], existing, { outcome: 'uncertain', rationale: 'Source chronology is context only.' }, { incomingSourceContext: { publishedAt: '2026-08-01', institution: 'A' } }); const request = mock.calls.find((item) => item.operation === 'resolveSemanticCase'); const input = request?.input as { resolutionCase: { candidateProjection: { temporal: unknown } } }; assert.deepEqual(input.resolutionCase.candidateProjection.temporal, candidate.temporal); assert.equal(result.intents.find((item) => item.candidateRef === 'c')?.disposition, 'review') })
test('Entity plausible retrieval overflows without truncation or semantic calls', async () => { const existing = Array.from({ length: 9 }, (_, index) => ({ id: `entity:weak-${index}`, type: 'company', name: `Weak ${index}`, exchange: 'NYSE', lifecycle: { status: 'active' } })); const { result, mock } = await resolve([group(entity('e', 'Exact Target', 'company', { semanticFields: { exchange: 'NYSE' } }))], assets(existing), undefined, { maxEntityBindingCandidates: 8 }); const binding = result.bindings.get('e'); assert.equal(mock.calls.length, 0); assert.equal(binding?.state, 'Unresolved'); assert.equal(binding?.plausibleMatches.length, 9); assert.match(result.reviewItems[0]?.rationale ?? '', /entity_plausible_match_overflow/) })
test('Entity plausible membership is independent of maxResolutionCases', async () => { const existing = Array.from({ length: 8 }, (_, index) => ({ id: `entity:weak-${index}`, type: 'company', name: `Weak ${index}`, exchange: 'NYSE', lifecycle: { status: 'active' } })).concat([{ id: 'entity:exact', type: 'company', name: 'Exact Target', exchange: 'NYSE', lifecycle: { status: 'active' } }]); const groups = [group(entity('e', 'Exact Target', 'company', { semanticFields: { exchange: 'NYSE' } }))]; const low = await resolve(groups, assets(existing), undefined, { maxResolutionCases: 1, maxEntityBindingCandidates: 32 }); const high = await resolve(groups, assets(existing), undefined, { maxResolutionCases: 32, maxEntityBindingCandidates: 32 }); assert.deepEqual(low.result.bindings.get('e')?.plausibleMatches, high.result.bindings.get('e')?.plausibleMatches); assert.ok(low.result.bindings.get('e')?.plausibleMatches.includes('entity:exact')) })
test('semantic case count is separate from retry call count', async () => { let alphaAttempts = 0; const response = (request: { input: unknown }) => { const name = ((request.input as { resolutionCase: { candidateProjection: { name?: string } } }).resolutionCase.candidateProjection.name); if (name === 'Alpha') { alphaAttempts += 1; if (alphaAttempts === 1) return { outcome: 'unsupported', rationale: 'Retry this case.' } } return { outcome: 'equivalent_to', targetAlias: 'existing-001', rationale: 'Bounded retry success.' } }; const groups = [group(entity('a', 'Alpha')), group(entity('b', 'Beta'))]; const { result } = await resolve(groups, assets([{ id: 'entity:alpha', type: 'company', name: 'Alpha', lifecycle: { status: 'active' } }, { id: 'entity:beta', type: 'company', name: 'Beta', lifecycle: { status: 'active' } }]), response, { maxResolutionCases: 2, maxResolutionAttempts: 2 }); assert.equal(result.semanticCaseCount, 2); assert.equal(result.semanticCaseCalls, 3); assert.equal(result.summary.semanticCases, 2); assert.equal(result.summary.semanticCaseCalls, 3) })
test('mixed fresh Knowledge Resolution graph plans all canonical references', async () => { const entityGroups = Array.from({ length: 60 }, (_, index) => group(entity(`e-${index}`, `Fresh ${index}`, index < 15 ? 'company' : index < 30 ? 'product' : index < 45 ? 'industry' : 'technology'))); const relationGroups = Array.from({ length: 15 }, (_, index) => group(relation(`offers-${index}`, 'offers_product', `e-${index}`, `e-${15 + index}`))).concat(Array.from({ length: 15 }, (_, index) => group(relation(`develops-${index}`, 'develops_technology', `e-${index}`, `e-${45 + index}`)))); const claimGroups = Array.from({ length: 30 }, (_, index) => group(claim(`claim-${index}`, `Fresh ${index} is documented`, `e-${index}`, { evidenceBlockRefs: ['block-1'] }))); const groups = [...entityGroups, ...relationGroups, ...claimGroups]; const mixedPlan = { ...plan, units: [{ unitId: 'unit-1', proposedUnitId: 'unit-1', topic: 'mixed', semanticPurpose: 'mixed', primaryRefs: [], contextRefs: [], primaryBlockIds: ['block-1'], contextBlockIds: [] }] }; const resolution = await resolve(groups, emptyAssets(), undefined, { plan: mixedPlan }); const planned = planKnowledgeChangeSet({ ...plannerInput(groups, resolution.result), plan: mixedPlan }); const operations = planned.changeSet?.knowledgeOperations ?? []; assert.equal(resolution.result.semanticCaseCount, 0); assert.equal(resolution.result.semanticCaseCalls, 0); assert.equal(planned.reviewItems.length, 0); assert.equal(operations.filter((item) => item.type === 'create' && 'object' in item && item.object.id.startsWith('entity:')).length, 60); assert.equal(operations.filter((item) => item.type === 'create' && 'object' in item && item.object.id.startsWith('relation:')).length, 30); assert.equal(operations.filter((item) => item.type === 'create' && 'object' in item && item.object.id.startsWith('claim:')).length, 30); assert.equal(planned.changeSet?.sourceOperations.length, 1); assert.equal(JSON.stringify(planned.changeSet).includes('planned-entity-'), false); assert.equal(planned.changeSet !== undefined, true) })
test('Schema-valid Relation state change becomes replace_state and invalid nested state is isolated', async () => { const baseEntities = [{ id: 'entity:company', type: 'company', name: 'Company', exchange: 'NYSE', ticker: 'COMP', lifecycle: { status: 'active' } }, { id: 'entity:industry', type: 'industry', name: 'Industry', lifecycle: { status: 'active' } }]; const old = { id: 'relation:old', type: 'business_exposure', sourceRef: 'entity:company', targetRef: 'entity:industry', attributes: { exposureBasis: 'unknown', realizationStage: 'unknown', materiality: 'minor' }, sourceRefs: ['source:old'], lifecycle: { status: 'active' } }; const response = (request: { input: unknown }) => ((request.input as { resolutionCase: { caseKind: string } }).resolutionCase.caseKind === 'EntityBindingCase' ? { outcome: 'equivalent_to', targetAlias: 'existing-001', rationale: 'Same endpoint.' } : { outcome: 'state_changed', targetAlias: 'existing-001', rationale: 'The exposure state changed.' }); const validGroups = [group(entity('c', 'Company', 'company', { semanticFields: { exchange: 'NYSE', ticker: 'COMP' } })), group(entity('i', 'Industry', 'industry')), group(relation('r', 'business_exposure', 'c', 'i', { exposureBasis: 'direct_operation', realizationStage: 'commercialized', materiality: 'core' }))]; const valid = await resolve(validGroups, assets(baseEntities, [old]), response); const validPlan = planKnowledgeChangeSet(plannerInput(validGroups, valid.result, assets(baseEntities, [old]))); const update = validPlan.changeSet?.knowledgeOperations.find((item) => item.type === 'update'); assert.equal(valid.result.intents.find((item) => item.candidateRef === 'r')?.disposition, 'replace_state'); assert.equal(update?.type, 'update'); if (update?.type === 'update') assert.equal((update.object as { attributes?: { materiality?: string } }).attributes?.materiality, 'core'); const invalidGroups = [group(entity('c', 'Company', 'company', { semanticFields: { exchange: 'NYSE', ticker: 'COMP' } })), group(entity('i', 'Industry', 'industry')), group(relation('r', 'business_exposure', 'c', 'i', { financialContribution: { revenueShare: 2 } }))]; const invalid = await resolve(invalidGroups, assets(baseEntities, [old]), response); const invalidPlan = planKnowledgeChangeSet(plannerInput(invalidGroups, invalid.result, assets(baseEntities, [old]))); assert.equal(invalidPlan.changeSet?.knowledgeOperations.some((item) => item.type === 'update' && item.knowledgeId === 'relation:old') ?? false, false); assert.ok(invalidPlan.reviewItems.some((item) => item.candidateId === 'r')) })

const themeDocument = { ...document, sections: [{ sectionId: 'section-1', title: 'Theme', level: 1, parentSectionId: null, blockRefs: ['block-1', 'block-2', 'block-3', 'block-4', 'block-5', 'block-6', 'block-7', 'block-8'] }], blocks: Array.from({ length: 8 }, (_, index) => ({ blockId: `block-${index + 1}`, type: 'paragraph' as const, text: `Material theme evidence ${index + 1}`, sectionRef: 'section-1', page: 1, locator: { page: 1 }, order: index + 1 })) }
const themePlan: AcceptedExtractionPlan = { units: [{ unitId: 'unit-1', proposedUnitId: 'unit-1', topic: 'theme', semanticPurpose: 'theme', primaryRefs: [], contextRefs: [], primaryBlockIds: ['block-1'], contextBlockIds: [] }], excludedBlockIds: [], estimatedContextTokens: {} }
function investmentTheme(id: string, name: string, extra: Record<string, unknown> = {}): EntityCandidate { return entity(id, name, 'investment_theme', { evidenceBlockRefs: ['block-1'], ...extra }) }
function themeAsset(id: string, name: string, extra: Record<string, unknown> = {}): Record<string, unknown> { return { id, type: 'investment_theme', name, themeGroupRef: 'theme-group:default', lifecycle: { status: 'active' }, ...extra } }
function themeExistingAssets(values: Record<string, unknown>[]): KnowledgeAssetCollectionV03 { return assets(values) }
async function resolveTheme(candidate: EntityCandidate, existing: KnowledgeAssetCollectionV03 = emptyAssets(), response?: unknown, options: Record<string, unknown> = {}) { const mock = executor(response); const skill = new KnowledgeCurationSkill({ executor: mock }); const result = await resolveKnowledge({ assets: existing, document: themeDocument as never, groups: [group(candidate)], reportMap, plan: themePlan, rawRef, skill, ...options } as never); return { result, mock } }

test('InvestmentTheme same name uses bounded coverage case and no durable ID is exposed', async () => { const { result, mock } = await resolveTheme(investmentTheme('theme', 'AI Compute'), themeExistingAssets([themeAsset('entity:ai-compute', 'AI Compute', { definition: 'AI infrastructure cycle', inclusionCriteria: ['compute demand'], exclusionCriteria: ['unrelated software'] })]), { outcome: 'matches_existing', targetAlias: 'existing-theme-001', rationale: 'The existing theme covers the candidate.' }); assert.equal(result.bindings.get('theme')?.state, 'BoundExisting'); assert.equal(result.bindings.get('theme')?.ref, 'entity:ai-compute'); const request = mock.calls.find((item) => ((item.input as { resolutionCase?: { caseKind?: string } }).resolutionCase?.caseKind) === 'InvestmentThemeCoverageCase'); assert.ok(request); const serialized = JSON.stringify(request?.input); assert.doesNotMatch(serialized, /entity:ai-compute|theme-group:default/); assert.match(serialized, /AI infrastructure cycle/); assert.match(request?.instruction ?? '', /only when no supplied existing InvestmentTheme reasonably covers the Candidate may you return potential_new/i); assert.equal(result.potentialNewInvestmentThemes.length, 0) })

test('InvestmentTheme ambiguous coverage becomes theme_ambiguity Review', async () => { const { result, mock } = await resolveTheme(investmentTheme('theme', 'Liquid Cooling'), themeExistingAssets([themeAsset('entity:ai', 'AI Compute'), themeAsset('entity:datacenter', 'Data Center Infrastructure')]), { outcome: 'ambiguous_existing', rationale: 'Both existing themes may cover the candidate.' }); assert.equal(mock.calls.length, 1); assert.equal(result.bindings.get('theme')?.state, 'Unresolved'); assert.equal(result.intents[0]?.disposition, 'review'); assert.equal(result.reviewItems[0]?.category, 'theme_ambiguity'); assert.equal(result.potentialNewInvestmentThemes.length, 0) })

test('InvestmentTheme potential_new is Review and weak support is not recommended', async () => { const { result, mock } = await resolveTheme(investmentTheme('theme', 'Quantum Cooling'), themeExistingAssets([themeAsset('entity:ai', 'AI Compute')]), { outcome: 'potential_new', rationale: 'No supplied existing theme reasonably covers it.' }); assert.equal(mock.calls.length, 1); assert.equal(result.bindings.get('theme')?.state, 'Unresolved'); assert.equal(result.intents[0]?.disposition, 'review'); assert.equal(result.reviewItems[0]?.category, 'theme_creation'); assert.equal(result.potentialNewInvestmentThemes.length, 1); assert.equal(result.potentialNewInvestmentThemes[0]?.recommendation, 'do_not_recommend'); assert.equal(result.recommendedNewInvestmentThemes.length, 0) })

test('Fresh KB allows potential_new but material consolidated support recommends without creating', async () => { const candidate = investmentTheme('theme', 'Quantum Cooling'); const support = new Map([['theme', { supportingCandidateCount: 2, supportingUnitIds: ['unit-1', 'unit-2'], evidenceBlockRefs: ['block-1', 'block-2'] }]]); const { result } = await resolveTheme(candidate, emptyAssets(), undefined, { candidateSupport: support }); assert.equal(result.bindings.get('theme')?.state, 'Unresolved'); assert.equal(result.potentialNewInvestmentThemes.length, 1); assert.equal(result.potentialNewInvestmentThemes[0]?.support.supportingCandidateCount, 2); assert.equal(result.potentialNewInvestmentThemes[0]?.support.supportingUnitCount, 2); assert.equal(result.potentialNewInvestmentThemes[0]?.recommendation, 'recommend'); assert.equal(result.recommendedNewInvestmentThemes.length, 1); assert.equal(result.intents[0]?.targetRef, undefined); })

test('Incomplete existing Theme context cannot produce potential_new', async () => { const { result, mock } = await resolveTheme(investmentTheme('theme', 'Quantum Cooling'), themeExistingAssets([themeAsset('entity:ai', 'AI Compute')]), { outcome: 'potential_new', rationale: 'Should not execute.' }, { maxContextTokens: 1 }); assert.equal(mock.calls.length, 0); assert.equal(result.bindings.get('theme')?.state, 'Unresolved'); assert.equal(result.reviewItems[0]?.category, 'theme_ambiguity'); assert.equal(result.potentialNewInvestmentThemes.length, 0) })

test('InvestmentTheme dependent Relation and Claim are isolated while unrelated Entity remains safe', async () => { const theme = investmentTheme('theme', 'Quantum Cooling'); const industry = entity('industry', 'Cooling Industry', 'industry', { evidenceBlockRefs: ['block-1'] }); const relationCandidate = relation('exposure', 'theme_exposure', 'theme', 'industry'); const claimCandidate = claim('claim-theme', 'Quantum Cooling matters', 'theme', { evidenceBlockRefs: ['block-1'] }); const groups = [group(theme), group(industry), group(relationCandidate), group(claimCandidate)]; const mock = executor((request: { input: unknown }) => ((request.input as { resolutionCase?: { caseKind?: string } }).resolutionCase?.caseKind === 'InvestmentThemeCoverageCase' ? { outcome: 'potential_new', rationale: 'No existing Theme covers it.' } : { outcome: 'equivalent_to', targetAlias: 'existing-001', rationale: 'not expected' })); const skill = new KnowledgeCurationSkill({ executor: mock }); const result = await resolveKnowledge({ assets: emptyAssets(), document: themeDocument as never, groups, reportMap, plan: themePlan, rawRef, skill } as never); assert.equal(result.bindings.get('theme')?.state, 'Unresolved'); assert.equal(result.intents.find((item) => item.candidateRef === 'exposure')?.disposition, 'review'); assert.equal(result.intents.find((item) => item.candidateRef === 'claim-theme')?.disposition, 'review'); assert.ok(result.intents.find((item) => item.candidateRef === 'industry')?.disposition === 'create'); assert.ok(result.reviewItems.filter((item) => item.dependency).length >= 2) })

test('Consolidated duplicate Theme candidates produce one materiality assessment', async () => { const candidate = investmentTheme('raw-theme', 'Quantum Cooling'); const extraction = (unitId: string, blockId: string): { unit: AcceptedExtractionPlan['units'][number]; result: ValidatedExtractKnowledgeResult } => ({ unit: { unitId, proposedUnitId: unitId, topic: 'theme', semanticPurpose: 'theme', primaryRefs: [], contextRefs: [], primaryBlockIds: [blockId], contextBlockIds: [] }, result: { entities: [candidate], relations: [], claims: [], rejected: [], summary: { inputCounts: { entity: 1, relation: 0, claim: 0 }, acceptedCounts: { entity: 1, relation: 0, claim: 0 }, rejectedCounts: { entity: 0, relation: 0, claim: 0 }, rejectionCodes: [] } } }); const consolidated = consolidateExtractions([extraction('unit-1', 'block-1'), extraction('unit-2', 'block-2')]); assert.equal(consolidated.groups.length, 1); const merged = consolidated.groups[0]!; const { result } = await resolveTheme(merged.candidate as EntityCandidate, emptyAssets(), undefined, { candidateSupport: consolidated.candidateSupport, plan: { units: [extraction('unit-1', 'block-1').unit, extraction('unit-2', 'block-2').unit], excludedBlockIds: [], estimatedContextTokens: {} } }); assert.equal(result.potentialNewInvestmentThemes.length, 1); assert.equal(result.recommendedNewInvestmentThemes.length, 1); assert.equal(result.potentialNewInvestmentThemes[0]?.support.supportingCandidateCount, 2) })
test('InvestmentTheme description conflict does not preempt Theme policy', async () => { const consolidated = consolidateExtractions([extractionFixture('unit-1', [investmentTheme('a', 'Quantum Cooling', { description: 'Theme A' })]), extractionFixture('unit-2', [investmentTheme('b', 'Quantum Cooling', { description: 'Theme B' })], [], [], 'block-2')]); const merged = consolidated.groups[0]?.candidate as EntityCandidate; assert.equal(merged.description, undefined); assert.equal(consolidated.reviewConstraints[0]?.blocking, false); const { result, mock } = await resolveTheme(merged, emptyAssets(), undefined, { consolidationReviews: consolidated.reviewConstraints, candidateSupport: consolidated.candidateSupport }); assert.equal(mock.calls.length, 0); assert.equal(result.reviewItems[0]?.category, 'theme_creation'); assert.equal(result.bindings.get(merged.candidateId)?.state, 'Unresolved'); assert.equal(result.potentialNewInvestmentThemes.length, 1) })

test('one consolidation issue remains one normalized Review across lifecycle mirrors', () => { const constraint = { candidateId: 'e', reason: 'Entity description variants across extraction units; canonical description omitted', conflictingFields: ['description'], blocking: false, category: 'other' as const, reviewKey: 'consolidation|e|entity description variants across extraction units; canonical description omitted|description' }; const mirror = { candidateId: 'e', kind: 'entity', rationale: constraint.reason, dependentCandidateIds: [], stage: 'consolidation', category: 'other' as const, origin: 'consolidation' as const, dependency: false, reviewKey: constraint.reviewKey }; const summary = normalizeReviewSummary({ consolidationReviews: [constraint], resolutionReviews: [mirror], plannerReviewItems: [mirror], candidateGroups: [group(entity('e', 'E'))] }); assert.equal(summary.total, 1); assert.equal(summary.rootCount, 1); assert.equal(summary.dependencyCount, 0); assert.equal(summary.byCategory.other, 1); assert.equal(summary.byCandidateKind.entity, 1) })
test('ReviewSummary counts all events while bounding category samples', () => { const items = Array.from({ length: 8 }, (_, index) => ({ candidateId: `e-${index}`, kind: 'entity', rationale: `Independent review ${index}`, dependentCandidateIds: [], stage: 'planner', category: 'other' as const, origin: 'planner' as const, dependency: false, reviewKey: `planner|e-${index}` })); const summary = normalizeReviewSummary({ plannerReviewItems: items, candidateGroups: items.map((item) => group(entity(item.candidateId, item.candidateId))) }); const samplesBoundedToFive = Object.values(summary.samplesByCategory).every((samples) => samples.length <= 5); const allHold = summary.total === summary.rootCount + summary.dependencyCount && Object.values(summary.byCategory).reduce((total, count) => total + count, 0) === summary.total && Object.values(summary.byCandidateKind).reduce((total, count) => total + count, 0) === summary.total && samplesBoundedToFive; assert.equal(summary.byCategory.other, 8); assert.equal(summary.samplesByCategory.other.length, 5); assert.equal(samplesBoundedToFive, true); assert.equal(allHold, true) })

test('Planner revalidates bypassed Relation attributes and preserves unrelated safe operations', async () => {
  const groups = [
    group(entity('company', 'Company', 'company')),
    group(entity('industry', 'Industry', 'industry')),
    group(entity('safe', 'Safe Company', 'company')),
    group(relation('bad-relation', 'business_exposure', 'company', 'industry', { financialContribution: { revenueShare: 2 } })),
  ]
  const resolution = await resolve(groups)
  const planned = planKnowledgeChangeSet(plannerInput(groups, resolution.result))
  const operations = planned.changeSet?.knowledgeOperations ?? []
  assert.equal(operations.some((item) => item.type === 'create' && item.object.id.startsWith('relation:')), false)
  assert.equal(operations.filter((item) => item.type === 'create' && item.object.id.startsWith('entity:')).length, 3)
  const review = planned.reviewItems.find((item) => item.candidateId === 'bad-relation')
  assert.equal(review?.origin, 'planner')
  assert.match(review?.rationale ?? '', /Relation attributes are not Schema 0\.3 valid/)
})

test('Planner blocks bypassed PlannedNew InvestmentTheme and preserves safe unrelated create', async () => { const theme = investmentTheme('theme', 'Quantum Cooling'); const safe = entity('safe', 'Independent Company', 'company'); const groups = [group(theme), group(safe)]; const intents = [{ candidateRef: 'theme', candidateKind: 'entity' as const, disposition: 'create' as const, targetRef: 'planned-entity-theme', semanticBasis: { rationale: 'bypassed' }, evidenceRefs: [] }, { candidateRef: 'safe', candidateKind: 'entity' as const, disposition: 'create' as const, targetRef: 'planned-entity-safe', semanticBasis: { rationale: 'safe' }, evidenceRefs: [] }]; const bindings = new Map([['theme', { candidateId: 'theme', state: 'PlannedNew' as const, plannedRef: 'planned-entity-theme', plausibleMatches: [] }], ['safe', { candidateId: 'safe', state: 'PlannedNew' as const, plannedRef: 'planned-entity-safe', plausibleMatches: [] }]]); const planned = planKnowledgeChangeSet({ ...plannerInput(groups, { intents, bindings, reviewItems: [], blocked: false } as never), intents, bindings }); assert.equal(planned.entityResolutions.find((item) => item.candidateId === 'theme')?.status, 'review'); assert.equal(planned.reviewItems.find((item) => item.candidateId === 'theme')?.category, 'theme_creation'); assert.equal(planned.changeSet?.knowledgeOperations.some((item) => item.type === 'create' && item.object.id.includes('investment_theme')), false); assert.equal(planned.changeSet?.knowledgeOperations.some((item) => item.type === 'create' && item.object.id.startsWith('entity:company-')), true) })

test('Existing InvestmentTheme enrichment preserves themeGroupRef', async () => { const existing = themeExistingAssets([themeAsset('entity:ai', 'AI Compute', { aliases: [] })]); const candidate = investmentTheme('theme', 'AI Compute', { aliases: ['AI Infrastructure'] }); const { result } = await resolveTheme(candidate, existing, { outcome: 'matches_existing', targetAlias: 'existing-theme-001', rationale: 'Existing theme covers it.' }); const planned = planKnowledgeChangeSet(plannerInput([group(candidate)], result, existing)); const update = planned.changeSet?.knowledgeOperations.find((item) => item.type === 'update'); assert.equal(update?.type, 'update'); if (update?.type === 'update') assert.equal((update.object as { themeGroupRef?: string }).themeGroupRef, 'theme-group:default') })

test('Theme Review does not block safe unrelated ChangeSet operations', async () => { const theme = investmentTheme('theme', 'Quantum Cooling'); const safe = entity('safe', 'Independent Company', 'company'); const groups = [group(theme), group(safe)]; const mock = executor((request: { input: unknown }) => ((request.input as { resolutionCase?: { caseKind?: string } }).resolutionCase?.caseKind === 'InvestmentThemeCoverageCase' ? { outcome: 'potential_new', rationale: 'No existing Theme covers it.' } : { outcome: 'equivalent_to', targetAlias: 'existing-001', rationale: 'not expected' })); const skill = new KnowledgeCurationSkill({ executor: mock }); const resolution = await resolveKnowledge({ assets: emptyAssets(), document: themeDocument as never, groups, reportMap, plan: themePlan, rawRef, skill } as never); const planned = planKnowledgeChangeSet(plannerInput(groups, resolution, emptyAssets())); assert.ok(planned.changeSet); const operations = planned.changeSet?.knowledgeOperations ?? []; assert.equal(operations.some((item) => item.type === 'create' && item.object.id.includes('investment_theme')), false); assert.equal(operations.some((item) => item.type === 'create' && item.object.id.startsWith('entity:company-')), true); assert.equal(operations.filter((item) => item.type === 'create' && item.object.id.startsWith('theme-group:')).length, 0); const root = await createKnowledgeBase(); try { const handle = await new KnowledgeBaseRegistry().mount(root); const validation = await validateKnowledgeChangeSetV03(handle, planned.changeSet!, { mode: 'dry_run', virtualRawRefs: [rawRef] }); assert.equal(validation.report.status, 'passed', JSON.stringify(validation.report.errors)); } finally { await removeKnowledgeBase(root) } })

test('Theme materiality counts only primary blocks owned by supporting Units', () => {
  const blocks = Array.from({ length: 9 }, (_, index) => ({ blockId: `support-${index + 1}`, type: 'paragraph' as const, text: `Support ${index + 1}`, sectionRef: 'section-1', page: 1, locator: { page: 1 }, order: index + 1 }))
  const supportDocument = { ...themeDocument, blocks, sections: [] }
  const crossUnitPlan: AcceptedExtractionPlan = { units: [{ unitId: 'unit-a', proposedUnitId: 'unit-a', topic: 'theme', semanticPurpose: 'theme', primaryRefs: [], contextRefs: [], primaryBlockIds: ['support-1'], contextBlockIds: blocks.slice(1).map((block) => block.blockId) }, ...blocks.slice(1).map((block) => ({ unitId: `unit-${block.blockId}`, proposedUnitId: `unit-${block.blockId}`, topic: 'context owner', semanticPurpose: 'context owner', primaryRefs: [], contextRefs: [], primaryBlockIds: [block.blockId], contextBlockIds: [] }))], excludedBlockIds: [], estimatedContextTokens: {} }
  const assessment = assessPotentialNewInvestmentTheme(investmentTheme('cross', 'Cross Unit Theme', { evidenceBlockRefs: blocks.map((block) => block.blockId) }), { supportingCandidateCount: 1, supportingUnitIds: ['unit-a'], evidenceBlockRefs: blocks.map((block) => block.blockId) }, crossUnitPlan, supportDocument as never)
  assert.equal(assessment.support.supportingUnitCount, 1)
  assert.equal(assessment.support.supportingPrimaryBlockCount, 1)
  assert.equal(assessment.recommendation, 'do_not_recommend')
})

test('Theme materiality preserves strong single-Unit primary support', () => {
  const blocks = Array.from({ length: 8 }, (_, index) => ({ blockId: `strong-${index + 1}`, type: 'paragraph' as const, text: `Strong ${index + 1}`, sectionRef: 'section-1', page: 1, locator: { page: 1 }, order: index + 1 }))
  const strongPlan: AcceptedExtractionPlan = { units: [{ unitId: 'unit-a', proposedUnitId: 'unit-a', topic: 'theme', semanticPurpose: 'theme', primaryRefs: [], contextRefs: [], primaryBlockIds: blocks.map((block) => block.blockId), contextBlockIds: [] }], excludedBlockIds: [], estimatedContextTokens: {} }
  const assessment = assessPotentialNewInvestmentTheme(investmentTheme('strong', 'Strong Theme', { evidenceBlockRefs: blocks.map((block) => block.blockId) }), { supportingCandidateCount: 1, supportingUnitIds: ['unit-a'], evidenceBlockRefs: blocks.map((block) => block.blockId) }, strongPlan, { ...themeDocument, blocks } as never)
  assert.equal(assessment.support.supportingUnitCount, 1)
  assert.equal(assessment.support.supportingPrimaryBlockCount, 8)
  assert.equal(assessment.recommendation, 'recommend')
})

test('Theme materiality preserves two-Unit recommendation with low block support', () => {
  const blocks = Array.from({ length: 2 }, (_, index) => ({ blockId: `multi-${index + 1}`, type: 'paragraph' as const, text: `Multi ${index + 1}`, sectionRef: 'section-1', page: 1, locator: { page: 1 }, order: index + 1 }))
  const multiPlan: AcceptedExtractionPlan = { units: [{ unitId: 'unit-a', proposedUnitId: 'unit-a', topic: 'theme', semanticPurpose: 'theme', primaryRefs: [], contextRefs: [], primaryBlockIds: ['multi-1'], contextBlockIds: [] }, { unitId: 'unit-b', proposedUnitId: 'unit-b', topic: 'theme', semanticPurpose: 'theme', primaryRefs: [], contextRefs: [], primaryBlockIds: ['multi-2'], contextBlockIds: [] }], excludedBlockIds: [], estimatedContextTokens: {} }
  const assessment = assessPotentialNewInvestmentTheme(investmentTheme('multi', 'Multi Unit Theme', { evidenceBlockRefs: blocks.map((block) => block.blockId) }), { supportingCandidateCount: 2, supportingUnitIds: ['unit-a', 'unit-b'], evidenceBlockRefs: blocks.map((block) => block.blockId) }, multiPlan, { ...themeDocument, blocks } as never)
  assert.equal(assessment.support.supportingUnitCount, 2)
  assert.equal(assessment.recommendation, 'recommend')
})

test('InvestmentTheme coverage prompt maps uncertainty to ambiguous_existing', async () => { const { mock } = await resolveTheme(investmentTheme('theme', 'Prompt Theme'), themeExistingAssets([themeAsset('entity:theme', 'Existing Theme')]), { outcome: 'ambiguous_existing', rationale: 'Coverage is uncertain.' }); const request = mock.calls.find((item) => ((item.input as { resolutionCase?: { caseKind?: string } }).resolutionCase?.caseKind) === 'InvestmentThemeCoverageCase'); const instruction = request?.instruction ?? ''; const themeBranch = instruction.split('For other case kinds')[0] ?? ''; assert.match(themeBranch, /coverage is uncertain[\s\S]*ambiguous_existing/i); assert.doesNotMatch(themeBranch, /return uncertain/i); assert.match(instruction, /other case kinds[\s\S]*uncertain/i) })

test('InvestmentTheme coverage vocabulary rejects uncertain while other cases retain it', () => { assert.deepEqual([...semanticOutcomeVocabulary('InvestmentThemeCoverageCase')], ['matches_existing', 'ambiguous_existing', 'potential_new']); assert.ok(!semanticOutcomeVocabulary('InvestmentThemeCoverageCase').includes('uncertain')); assert.ok(semanticOutcomeVocabulary('EntityBindingCase').includes('uncertain')); assert.ok(semanticOutcomeVocabulary('RelationConflictCase').includes('uncertain')); assert.ok(semanticOutcomeVocabulary('ClaimConflictCase').includes('uncertain')); assert.throws(() => validateSemanticResolutionResult({ caseId: 'case', caseKind: 'InvestmentThemeCoverageCase', outcome: 'uncertain', rationale: 'Not legal for Theme coverage.' }, { resolutionCase: { caseId: 'case', caseKind: 'InvestmentThemeCoverageCase', candidateProjection: {}, existingProjections: [], evidence: [], sourceContext: {}, schemaContextSlice: {}, allowedOutcomes: semanticOutcomeVocabulary('InvestmentThemeCoverageCase') }, schemaContext: buildCurationSchemaContext('knowledge_resolution') }), KnowledgeCurationError) })

test('same Company hard identity consolidates names and preserves alternatives as aliases', () => { const consolidated = consolidateExtractions([extractionFixture('unit-a', [entity('a', '中巨芯', 'company', { semanticFields: { ticker: '688549', exchange: 'sh' } })]), extractionFixture('unit-b', [entity('b', '中巨芯科技', 'company', { semanticFields: { ticker: '688549', exchange: 'SH' } })])]); const companies = consolidated.groups.filter((item) => item.kind === 'entity').map((item) => item.candidate as EntityCandidate); assert.equal(companies.length, 1); assert.equal(companies[0]?.name, '中巨芯'); assert.deepEqual(companies[0]?.aliases, ['中巨芯科技']); assert.deepEqual(companies[0]?.semanticFields, { exchange: 'SH', ticker: '688549' }); assert.equal(consolidated.reviewConstraints.length, 0) })

test('unkeyed Company attaches to exactly one matching hard-identity group', () => { const consolidated = consolidateExtractions([extractionFixture('unit-a', [entity('hard', '中巨芯', 'company', { aliases: ['China JG'], semanticFields: { ticker: '688549', exchange: 'SH' } })]), extractionFixture('unit-b', [entity('unkeyed', 'China JG')])]); const companies = consolidated.groups.filter((item) => item.kind === 'entity').map((item) => item.candidate as EntityCandidate); assert.equal(companies.length, 1); assert.deepEqual(companies[0]?.aliases, ['China JG']); assert.equal(consolidated.reviewConstraints.length, 0) })

test('unkeyed Company matching multiple hard identities becomes blocking Review', async () => { const consolidated = consolidateExtractions([extractionFixture('unit-a', [entity('a', 'ABC', 'company', { semanticFields: { ticker: '600001', exchange: 'SH' } })]), extractionFixture('unit-b', [entity('b', 'ABC', 'company', { semanticFields: { ticker: '300001', exchange: 'SZ' } })]), extractionFixture('unit-c', [entity('c', 'ABC')])]); const companies = consolidated.groups.filter((item) => item.kind === 'entity').map((item) => item.candidate as EntityCandidate); assert.equal(companies.length, 3); const review = consolidated.reviewConstraints.find((item) => item.reason.includes('ambiguously matches multiple hard-identity groups')); assert.equal(review?.blocking, true); const { result } = await resolve(consolidated.groups, emptyAssets(), undefined, { consolidationReviews: consolidated.reviewConstraints }); assert.equal(result.intents.find((item) => item.candidateRef === review?.candidateId)?.disposition, 'review') })

test('Company display variants converge Relation and Claim local references', () => { const companyA = entity('company-a', '中巨芯'); const companyB = entity('company-b', '中巨芯（688549.SH）'); const p1 = entity('product-a', 'Product A', 'product'); const p2 = entity('product-b', 'Product B', 'product'); const r1 = relation('relation-a', 'offers_product', 'company-a', 'product-a'); const r2 = relation('relation-b', 'offers_product', 'company-b', 'product-b'); const c1 = claim('claim-a', '中巨芯 supports Product A', 'company-a'); const c2 = claim('claim-b', '中巨芯 supports Product B', 'company-b'); const consolidated = consolidateExtractions([extractionFixture('unit-a', [companyA, p1], [r1], [c1]), extractionFixture('unit-b', [companyB, p2], [r2], [c2], 'block-2')]); const company = consolidated.groups.find((item) => item.kind === 'entity' && (item.candidate as EntityCandidate).entityType === 'company')?.candidate as EntityCandidate; const relations = consolidated.groups.filter((item) => item.kind === 'relation').map((item) => item.candidate as RelationCandidate); const claims = consolidated.groups.filter((item) => item.kind === 'claim').map((item) => item.candidate as ClaimCandidate); assert.equal(company.name, '中巨芯'); assert.equal(new Set(relations.map((item) => item.source.candidateRef)).size, 1); assert.equal(new Set(claims.map((item) => item.subjectRefs[0]?.candidateRef)).size, 1); assert.equal(relations.every((item) => item.source.candidateRef === company.candidateId), true); assert.equal(claims.every((item) => item.subjectRefs[0]?.candidateRef === company.candidateId), true) })

test('representative Company identity variants consolidate into three document-local groups', () => { const sh = entity('sh', '上海新阳'); const shDisplay = entity('sh-display', '上海新阳（300236.SZ）'); const jg = entity('jg', '中巨芯'); const jgDisplay = entity('jg-display', '中巨芯(688549.SH)'); const honeywell = entity('honeywell', '霍尼韦尔'); const honeywellDisplay = entity('honeywell-display', '霍尼韦尔（Honeywell）'); const consolidated = consolidateExtractions([extractionFixture('unit-1', [sh, jg, honeywell]), extractionFixture('unit-2', [shDisplay, jgDisplay, honeywellDisplay], [], [], 'block-2')]); const companies = consolidated.groups.filter((item) => item.kind === 'entity').map((item) => item.candidate as EntityCandidate); assert.equal(companies.length, 3); const shMerged = companies.find((item) => item.name === '上海新阳'); const jgMerged = companies.find((item) => item.name === '中巨芯'); const honeywellMerged = companies.find((item) => item.name === '霍尼韦尔'); assert.deepEqual(shMerged?.semanticFields, { exchange: 'SZ', ticker: '300236' }); assert.deepEqual(jgMerged?.semanticFields, { exchange: 'SH', ticker: '688549' }); assert.deepEqual(honeywellMerged?.aliases, ['Honeywell']) })
