import type { SemanticProductionProposal } from '../../knowledge/production/contracts.ts'
import type { KnowledgeBaseHandle } from '../../knowledge/storage/handle.ts'
import type { ResearchAcquisitionPlugin, ResearchCompanyIdentity, ResearchProviderOutcome } from '../../plugins/research-acquisition/contracts.ts'
import type { EventResearchSignalStore } from '../../plugins/daily-intelligence/contracts.ts'
import type { ReasoningExecutor } from '../../plugins/reasoning/contracts.ts'

export const THESIS_ATTACK_VECTOR_TYPES = ['assumption_failure','causal_break','demand_downside','supply_cost','competitive_response','execution','regulation','accounting_quality','capital_allocation','valuation_dependency','alternative_explanation','evidence_gap'] as const
export type ThesisAttackVectorType = typeof THESIS_ATTACK_VECTOR_TYPES[number]
export const RED_TEAM_PRIORITIES = ['high','medium','low'] as const
export type RedTeamPriority = typeof RED_TEAM_PRIORITIES[number]
export const RED_TEAM_CHALLENGE_TYPES = ['assumption_failure','thesis_contradiction','causal_break','alternative_explanation','failure_case','risk_escalation','invalidation_condition','evidence_gap','resilience'] as const
export type RedTeamChallengeType = typeof RED_TEAM_CHALLENGE_TYPES[number]
export const RED_TEAM_BASES = ['verified_evidence','inference','hypothesis'] as const
export type RedTeamChallengeBasis = typeof RED_TEAM_BASES[number]
export const RED_TEAM_CHALLENGE_STATUSES = ['supported','partially_supported','not_supported','condition_met','unresolved'] as const
export type RedTeamChallengeStatus = typeof RED_TEAM_CHALLENGE_STATUSES[number]
export const RED_TEAM_VERDICTS = ['survives','weakened','materially_challenged','invalidation_condition_met','inconclusive'] as const
export type RedTeamVerdict = typeof RED_TEAM_VERDICTS[number]
export const RED_TEAM_RELATIONS = ['disconfirms','supports','context','irrelevant'] as const
export type RedTeamEvidenceRelation = typeof RED_TEAM_RELATIONS[number]
export const RED_TEAM_STRENGTHS = ['low','medium','high'] as const
export type RedTeamEvidenceStrength = typeof RED_TEAM_STRENGTHS[number]

export interface ThesisRedTeamInput { readonly workflowRunId: string; readonly symbol: string; readonly name?: string; readonly exchange?: string; readonly thesisRef: string; readonly lookbackDays?: number }
export interface ThesisRedTeamCompany { readonly symbol: string; readonly name?: string; readonly exchange?: string }
export interface ThesisProjectionClaim { readonly canonicalRef: string; readonly claimType?: string; readonly statement?: string; readonly subjectRefs?: readonly string[]; readonly lifecycle?: unknown; readonly confidence?: number; readonly probability?: number; readonly supportsClaimRefs?: readonly string[]; readonly dependsOnClaimRefs?: readonly string[]; readonly contradictsClaimRefs?: readonly string[]; readonly supersedes?: readonly string[]; readonly supersededBy?: readonly string[]; readonly structuredValue?: Readonly<Record<string, unknown>> | null; readonly sourceRefs?: readonly string[] }
export interface ThesisDependencyProjection { readonly targetThesisRef: string; readonly companyRef: string; readonly claims: readonly ThesisProjectionClaim[]; readonly directDependencyRefs: readonly string[]; readonly incomingDependencyRefs: readonly string[]; readonly criticalAssumptions: readonly ThesisProjectionClaim[]; readonly risks: readonly ThesisProjectionClaim[]; readonly catalysts: readonly ThesisProjectionClaim[]; readonly supportingClaims: readonly ThesisProjectionClaim[]; readonly contradictingClaims: readonly ThesisProjectionClaim[]; readonly truncated: boolean }
export interface ThesisSignalContext { readonly signalId: string; readonly title: string; readonly excerpt?: string; readonly narrative?: string; readonly publishedAt?: string; readonly category: string; readonly provider: string }
export interface ThesisAttackVector { readonly vectorId: string; readonly vectorType: ThesisAttackVectorType; readonly priority: RedTeamPriority; readonly targetExistingClaimRefs: readonly string[]; readonly falsificationQuestion: string; readonly failureMechanism: string; readonly evidenceNeeded: string; readonly searchTerms: readonly string[] }
export interface ImplicitThesisAssumption { readonly assumptionId: string; readonly statement: string; readonly rationale: string }
export interface ThesisInvalidationCondition { readonly conditionId: string; readonly statement: string; readonly severity: 'high'|'critical'; readonly targetExistingClaimRefs: readonly string[] }
export interface ThesisAttackDesign { readonly attackVectors: readonly ThesisAttackVector[]; readonly implicitAssumptions: readonly ImplicitThesisAssumption[]; readonly invalidationConditions: readonly ThesisInvalidationCondition[] }
export interface RedTeamEvidenceSource { readonly candidateId: string; readonly title: string; readonly provider: string; readonly kind?: string; readonly url?: string; readonly publishedAt?: string; readonly excerpt: string; readonly official?: boolean }
export interface RedTeamEvidenceAssessment { readonly sourceCandidateId: string; readonly attackVectorRefs: readonly string[]; readonly relation: RedTeamEvidenceRelation; readonly strength: RedTeamEvidenceStrength; readonly rationale: string }
export interface RedTeamChallengeAssessment { readonly challengeId: string; readonly challengeType: RedTeamChallengeType; readonly basis: RedTeamChallengeBasis; readonly status: RedTeamChallengeStatus; readonly severity: 'low'|'medium'|'high'|'critical'; readonly timeHorizon: 'immediate'|'near_term'|'medium_term'|'long_term'; readonly targetExistingClaimRefs: readonly string[]; readonly attackVectorRefs: readonly string[]; readonly sourceCandidateIds: readonly string[]; readonly conditionRef?: string; readonly causalChain: string; readonly rationale: string }
export interface RedTeamInterpretation { readonly interpretationId: string; readonly sectionId: string; readonly markdown: string; readonly sourceCandidateIds: readonly string[]; readonly existingKnowledgeRefs: readonly string[]; readonly challengeRefs: readonly string[] }
export interface RedTeamProposalCandidate extends SemanticProductionProposal { readonly challengeRefs?: readonly string[]; readonly sourceCandidateIds?: readonly string[]; readonly existingKnowledgeRefs?: readonly string[] }
export interface ThesisRedTeamSynthesisOutput { readonly evidenceAssessments: readonly RedTeamEvidenceAssessment[]; readonly challengeAssessments: readonly RedTeamChallengeAssessment[]; readonly thesisVerdict: RedTeamVerdict; readonly interpretations: readonly RedTeamInterpretation[]; readonly proposals: readonly RedTeamProposalCandidate[] }
export interface ThesisRedTeamReasoningShape { readonly topLevelKeys: readonly string[]; readonly attackVectorCount?: number; readonly evidenceAssessmentCount?: number; readonly challengeCount?: number; readonly proposalCount?: number }
export interface ThesisRedTeamReasoningTelemetry { readonly called: boolean; readonly operation: 'thesis_attack_design'|'thesis_red_team_synthesis'; readonly model?: string; readonly validated: boolean; readonly applied: boolean; readonly fallbackUsed: boolean; readonly repairAttempts: number; readonly diagnostics: readonly string[]; readonly firstAttemptShape?: ThesisRedTeamReasoningShape; readonly repairAttemptShape?: ThesisRedTeamReasoningShape }
export interface ThesisAttackDesignSkillResult { readonly output: ThesisAttackDesign; readonly reasoning: ThesisRedTeamReasoningTelemetry }
export interface ThesisRedTeamSynthesisSkillResult { readonly output: ThesisRedTeamSynthesisOutput; readonly reasoning: ThesisRedTeamReasoningTelemetry }
export interface ThesisRedTeamSkillContext { readonly company: ThesisRedTeamCompany; readonly thesis: ThesisProjectionClaim; readonly projection: ThesisDependencyProjection; readonly signals: readonly ThesisSignalContext[]; readonly sources: readonly RedTeamEvidenceSource[]; readonly attackDesign: ThesisAttackDesign }
export interface ThesisRedTeamProposalGateResult { readonly accepted: readonly RedTeamProposalCandidate[]; readonly diagnostics: readonly string[] }
export interface ThesisRedTeamProviderOutcome extends ResearchProviderOutcome { readonly transportSucceeded?: boolean; readonly fetchSucceeded?: boolean }
export interface ThesisRedTeamReportSection { readonly id: string; readonly title: string; readonly markdown: string; readonly sourceRefs?: readonly string[]; readonly claimRefs?: readonly string[]; readonly signalRefs?: readonly string[] }
export interface ThesisRedTeamReport { readonly reportId: string; readonly reportType: 'thesis_red_team'; readonly subjectRefs: readonly string[]; readonly generatedAt: string; readonly asOf: string; readonly workflowRunId: string; readonly knowledgeBaseRevision: number; readonly sourceRefs: readonly string[]; readonly claimRefs: readonly string[]; readonly methodology: string; readonly sections: readonly ThesisRedTeamReportSection[]; readonly outputPath: string }
export interface ThesisRedTeamTelemetry { readonly companyResolved: boolean; readonly thesisResolved: boolean; readonly thesisFingerprint: string; readonly dependencyClaimCount: number; readonly criticalAssumptionCount: number; readonly recentSignalCount: number; readonly attackVectorCount: number; readonly implicitAssumptionCount: number; readonly invalidationConditionCount: number; readonly acquisition: { readonly discoveredCount: number; readonly normalizedCount: number; readonly deduplicatedCount: number; readonly outsideWindowCount: number; readonly futureCount: number; readonly unknownDateCount: number; readonly providerOutcomes: readonly ThesisRedTeamProviderOutcome[] }; readonly stageA: ThesisRedTeamReasoningTelemetry; readonly stageB: ThesisRedTeamReasoningTelemetry; readonly thesisVerdict?: RedTeamVerdict; readonly challengeCount: number; readonly disconfirmingEvidenceCount: number; readonly supportingEvidenceCount: number; readonly alternativeExplanationCount: number; readonly failureCaseCount: number; readonly assumptionChallengeCount: number; readonly riskEscalationCount: number; readonly invalidationConditionMetCount: number; readonly affectedExistingClaimCount: number; readonly modelDerivedInterpretationCount: number; readonly proposalCandidateCount: number; readonly acceptedModelCandidateCount: number; readonly proposalRejectionDiagnostics: readonly string[]; readonly deterministicVerdictProposalIncluded: boolean; readonly riskProposalIncluded: boolean; readonly alternativeViewpointProposalIncluded: boolean; readonly assumptionUpdateProposalIncluded: boolean; readonly acceptedProposalCount: number; readonly targetThesisChanged: boolean; readonly targetThesisHashBefore: string; readonly targetThesisHashAfter: string; readonly targetThesisLifecycleBefore: string; readonly targetThesisLifecycleAfter: string; readonly thesisProposalCount: number; readonly signalCanonicalized: boolean; readonly irrelevantSourceCanonicalized: boolean; readonly reportPersistence: 'persisted'; readonly diagnostics: readonly string[] }
export interface ThesisRedTeamWorkflowInput { readonly workflowRunId: string; readonly handle: KnowledgeBaseHandle; readonly company: ResearchCompanyIdentity; readonly thesisRef: string; readonly acquisitionPlugins: readonly ResearchAcquisitionPlugin[]; readonly dailySignalStore?: EventResearchSignalStore; readonly reportRoot: string; readonly reasoningExecutor?: ReasoningExecutor; readonly signal?: AbortSignal; readonly now?: () => string; readonly lookbackDays?: number }
export interface ThesisRedTeamWorkflowResult { readonly workflowRunId: string; readonly status: 'completed'|'blocked'|'cancelled'|'failed'; readonly knowledgeBaseId: string; readonly knowledgeBaseRevision: number; readonly report?: ThesisRedTeamReport; readonly proposalIds: readonly string[]; readonly committedIds: readonly string[]; readonly sourceIds: readonly string[]; readonly claimIds: readonly string[]; readonly errors: readonly string[]; readonly diagnostics: readonly string[]; readonly providerOutcomes: readonly ThesisRedTeamProviderOutcome[]; readonly existingKnowledge: readonly ThesisProjectionClaim[]; readonly dependencyProjection?: ThesisDependencyProjection; readonly attackDesign?: ThesisAttackDesign; readonly synthesis?: ThesisRedTeamSynthesisOutput; readonly telemetry: ThesisRedTeamTelemetry }
