import type { ReasoningExecutor } from '../../plugins/reasoning/contracts.ts'
import { ReasoningExecutorError } from '../../plugins/reasoning/errors.ts'
import {
  RED_TEAM_BASES, RED_TEAM_CHALLENGE_STATUSES, RED_TEAM_CHALLENGE_TYPES, RED_TEAM_PRIORITIES,
  RED_TEAM_RELATIONS, RED_TEAM_STRENGTHS, RED_TEAM_VERDICTS, THESIS_ATTACK_VECTOR_TYPES,
  type ImplicitThesisAssumption, type RedTeamChallengeAssessment, type RedTeamEvidenceAssessment,
  type RedTeamInterpretation, type RedTeamProposalCandidate,
  type ThesisAttackDesign, type ThesisAttackVector, type ThesisDependencyProjection,
  type ThesisInvalidationCondition, type ThesisRedTeamReasoningShape, type ThesisRedTeamReasoningTelemetry,
  type ThesisRedTeamSkillContext, type ThesisRedTeamSynthesisOutput, type ThesisRedTeamSynthesisSkillResult,
  type ThesisAttackDesignSkillResult, type RedTeamVerdict, type ThesisProjectionClaim,
  type RedTeamEvidenceSource, type QualifiedRedTeamEvidence,
} from './contracts.ts'

const LOCAL_ID = /^[A-Za-z0-9][A-Za-z0-9._-]{0,95}$/
const MAX_TEXT = 4_000
const MAX_REFS = 40
const MAX_SOURCES = 12
const WRAPPERS = ['result', 'output', 'data', 'structuredOutput', 'response'] as const

export class ThesisRedTeamSemanticError extends Error {
  readonly retryable: boolean
  readonly diagnostics: readonly string[]
  constructor(message: string, diagnostics: readonly string[] = [], retryable = true) { super(message); this.name = 'ThesisRedTeamSemanticError'; this.retryable = retryable; this.diagnostics = diagnostics }
}
const record = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === 'object' && !Array.isArray(value)
const text = (value: unknown, max = MAX_TEXT): value is string => typeof value === 'string' && value.trim() !== '' && value.length <= max
const enumValue = <T extends string>(value: unknown, values: readonly T[]): value is T => typeof value === 'string' && values.includes(value as T)
const refs = (value: unknown, allowed: ReadonlySet<string>, max = MAX_REFS, required = false): value is readonly string[] => Array.isArray(value) && value.length <= max && (!required || value.length > 0) && value.every((item) => typeof item === 'string' && allowed.has(item)) && new Set(value).size === value.length
const unique = (value: readonly string[]): readonly string[] => [...new Set(value)].sort()

export function parseThesisRedTeamReasoningObject(value: unknown, depth = 0): Record<string, unknown> {
  if (typeof value === 'string') { try { const cleaned = value.trim().replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, ''); return parseThesisRedTeamReasoningObject(JSON.parse(cleaned), depth) } catch { throw new ThesisRedTeamSemanticError('Thesis Red Team reasoning returned invalid JSON', ['output_json_invalid']) } }
  if (!record(value)) throw new ThesisRedTeamSemanticError('Thesis Red Team reasoning must return an object', ['output_object_missing'])
  const wrapper = WRAPPERS.find((key) => value[key] !== undefined)
  if (!wrapper) return value
  if (depth >= 2) throw new ThesisRedTeamSemanticError('Thesis Red Team wrapper depth exceeded', ['output_wrapper_depth_exceeded'])
  return parseThesisRedTeamReasoningObject(value[wrapper], depth + 1)
}
export function thesisRedTeamReasoningShape(value: unknown): ThesisRedTeamReasoningShape { const object = record(value) ? value : {}; const count = (key: string) => Array.isArray(object[key]) ? object[key].length : 0; return { topLevelKeys: Object.keys(object).sort().slice(0, 16), attackVectorCount: count('attackVectors'), evidenceAssessmentCount: count('evidenceAssessments'), challengeCount: count('challengeAssessments'), proposalCount: count('proposals') } }
function safeDiagnostics(error: unknown): readonly string[] { if (error instanceof ThesisRedTeamSemanticError && error.diagnostics.length) return error.diagnostics.filter((item) => /^[A-Za-z0-9_.:-]+$/.test(item)).slice(0, 32); if (error instanceof ReasoningExecutorError) return [`executor_${error.code}`]; return ['thesis_red_team_reasoning_failed'] }
function modelName(executor: ReasoningExecutor | undefined): string | undefined { const metadata = executor as unknown as { runtimeMetadata?: () => { requestedModel?: string } } | undefined; return typeof metadata?.runtimeMetadata === 'function' ? metadata.runtimeMetadata().requestedModel : undefined }
function telemetry(executor: ReasoningExecutor | undefined, operation: ThesisRedTeamReasoningTelemetry['operation'], values: Omit<ThesisRedTeamReasoningTelemetry, 'called'|'operation'|'model'>): ThesisRedTeamReasoningTelemetry { const model = modelName(executor); return { called: executor !== undefined, operation, ...(model ? { model } : {}), ...values } }
function allowedContract(kind: 'attack'|'synthesis'): unknown { return kind === 'attack' ? { type: 'object', required: ['attackVectors','implicitAssumptions','invalidationConditions'], properties: { attackVectors: { type: 'array', minItems: 1, maxItems: 8 }, implicitAssumptions: { type: 'array', maxItems: 6 }, invalidationConditions: { type: 'array', minItems: 1, maxItems: 6 } } } : { type: 'object', required: ['evidenceAssessments','challengeAssessments','thesisVerdict','interpretations','proposals'], properties: { evidenceAssessments: { type: 'array', maxItems: 12 }, challengeAssessments: { type: 'array', maxItems: 16 }, thesisVerdict: { enum: RED_TEAM_VERDICTS }, interpretations: { type: 'array', maxItems: 16 }, proposals: { type: 'array', maxItems: 6 } } } }

function validateAttackVector(value: unknown, index: number, claimRefs: ReadonlySet<string>): ThesisAttackVector { if (!record(value) || !LOCAL_ID.test(String(value.vectorId ?? '')) || !enumValue(value.vectorType, THESIS_ATTACK_VECTOR_TYPES) || !enumValue(value.priority, RED_TEAM_PRIORITIES) || !refs(value.targetExistingClaimRefs, claimRefs) || !text(value.falsificationQuestion) || !text(value.failureMechanism) || !text(value.evidenceNeeded) || !Array.isArray(value.searchTerms) || value.searchTerms.length > 4 || value.searchTerms.some((item) => !text(item, 80))) throw new ThesisRedTeamSemanticError('Invalid attack vector', [`attack_vector_${index}_invalid`]); return value as unknown as ThesisAttackVector }
function validateAttackDesign(value: unknown, claimRefs: ReadonlySet<string>): ThesisAttackDesign { if (!record(value) || !Array.isArray(value.attackVectors) || value.attackVectors.length < 1 || value.attackVectors.length > 8 || !Array.isArray(value.implicitAssumptions) || value.implicitAssumptions.length > 6 || !Array.isArray(value.invalidationConditions) || value.invalidationConditions.length < 1 || value.invalidationConditions.length > 6) throw new ThesisRedTeamSemanticError('Invalid attack design', ['attack_design_shape_invalid']); const vectors = value.attackVectors.map((item, index) => validateAttackVector(item, index, claimRefs)); if (new Set(vectors.map((item) => item.vectorId)).size !== vectors.length) throw new ThesisRedTeamSemanticError('Duplicate attack vector IDs', ['attack_vector_duplicate']); const assumptions: ImplicitThesisAssumption[] = value.implicitAssumptions.map((item, index) => { if (!record(item) || !LOCAL_ID.test(String(item.assumptionId ?? '')) || !text(item.statement) || !text(item.rationale)) throw new ThesisRedTeamSemanticError('Invalid implicit assumption', [`implicit_assumption_${index}_invalid`]); return item as unknown as ImplicitThesisAssumption }); const conditions: ThesisInvalidationCondition[] = value.invalidationConditions.map((item, index) => { if (!record(item) || !LOCAL_ID.test(String(item.conditionId ?? '')) || !text(item.statement) || !enumValue(item.severity, ['high','critical'] as const) || !refs(item.targetExistingClaimRefs, claimRefs)) throw new ThesisRedTeamSemanticError('Invalid invalidation condition', [`invalidation_condition_${index}_invalid`]); return item as unknown as ThesisInvalidationCondition }); if (new Set(conditions.map((item) => item.conditionId)).size !== conditions.length) throw new ThesisRedTeamSemanticError('Duplicate invalidation condition IDs', ['invalidation_condition_duplicate']); return { attackVectors: vectors, implicitAssumptions: assumptions, invalidationConditions: conditions } }
function inputForAttack(context: ThesisRedTeamSkillContext): unknown { return { company: context.company, thesis: context.thesis, dependencyProjection: context.projection, existingAssumptions: context.projection.criticalAssumptions, existingRisks: context.projection.risks, existingCatalysts: context.projection.catalysts, supportingClaims: context.projection.supportingClaims, contradictingClaims: context.projection.contradictingClaims } }
function attackInstruction(): string { return 'Design falsifiable attack surfaces for the exact active Thesis before seeing newly acquired evidence. Return JSON only with attackVectors, implicitAssumptions, and invalidationConditions. Do not state facts, verdicts, or durable proposals. Use only supplied Claim refs.' }
export async function designThesisAttacks(context: ThesisRedTeamSkillContext, executor?: ReasoningExecutor): Promise<ThesisAttackDesignSkillResult> {
  const claimRefs = new Set(context.projection.claims.map((item) => item.canonicalRef));
  if (!executor) return { output: { attackVectors: [], implicitAssumptions: [], invalidationConditions: [] }, reasoning: telemetry(undefined, 'thesis_attack_design', { validated: false, applied: false, fallbackUsed: true, repairAttempts: 0, diagnostics: ['reasoning_executor_missing'] }) }
  let first: ThesisRedTeamReasoningShape | undefined; let repair: ThesisRedTeamReasoningShape | undefined; let diagnostics: readonly string[] = []
  try { const result = await executor.execute({ operation: 'thesis_attack_design', instruction: attackInstruction(), input: inputForAttack(context), outputContract: allowedContract('attack') }); first = thesisRedTeamReasoningShape(result.output); const output = validateAttackDesign(parseThesisRedTeamReasoningObject(result.output), claimRefs); return { output, reasoning: telemetry(executor, 'thesis_attack_design', { validated: true, applied: true, fallbackUsed: false, repairAttempts: 0, diagnostics: [], firstAttemptShape: first }) } }
  catch (error) { diagnostics = safeDiagnostics(error); if (!(error instanceof ThesisRedTeamSemanticError) || !error.retryable) return { output: { attackVectors: [], implicitAssumptions: [], invalidationConditions: [] }, reasoning: telemetry(executor, 'thesis_attack_design', { validated: false, applied: false, fallbackUsed: true, repairAttempts: 0, diagnostics, firstAttemptShape: first }) } }
  try { const result = await executor.execute({ operation: 'thesis_attack_design', instruction: `${attackInstruction()} Repair the previous invalid output. Return only a bounded valid object.`, input: { context: inputForAttack(context), previousOutput: 'bounded-invalid-output', diagnostics: diagnostics.slice(0, 16) }, outputContract: allowedContract('attack') }); repair = thesisRedTeamReasoningShape(result.output); const output = validateAttackDesign(parseThesisRedTeamReasoningObject(result.output), claimRefs); return { output, reasoning: telemetry(executor, 'thesis_attack_design', { validated: true, applied: true, fallbackUsed: false, repairAttempts: 1, diagnostics: [], firstAttemptShape: first, repairAttemptShape: repair }) } } catch (error) { const finalDiagnostics = safeDiagnostics(error); return { output: { attackVectors: [], implicitAssumptions: [], invalidationConditions: [] }, reasoning: telemetry(executor, 'thesis_attack_design', { validated: false, applied: false, fallbackUsed: true, repairAttempts: 1, diagnostics: finalDiagnostics, firstAttemptShape: first, repairAttemptShape: repair }) } }
}

function validateEvidence(value: unknown, index: number, sourceRefs: ReadonlySet<string>, vectorRefs: ReadonlySet<string>): RedTeamEvidenceAssessment { if (!record(value) || !sourceRefs.has(String(value.sourceCandidateId ?? '')) || !refs(value.attackVectorRefs, vectorRefs) || !enumValue(value.relation, RED_TEAM_RELATIONS) || !enumValue(value.strength, RED_TEAM_STRENGTHS) || !text(value.rationale)) throw new ThesisRedTeamSemanticError('Invalid evidence assessment', [`evidence_assessment_${index}_invalid`]); return value as unknown as RedTeamEvidenceAssessment }
function validateChallenge(value: unknown, index: number, claimRefs: ReadonlySet<string>, vectorRefs: ReadonlySet<string>, sourceRefs: ReadonlySet<string>, conditionRefs: ReadonlySet<string>): RedTeamChallengeAssessment { if (!record(value) || !LOCAL_ID.test(String(value.challengeId ?? '')) || !enumValue(value.challengeType, RED_TEAM_CHALLENGE_TYPES) || !enumValue(value.basis, RED_TEAM_BASES) || !enumValue(value.status, RED_TEAM_CHALLENGE_STATUSES) || !enumValue(value.severity, ['low','medium','high','critical'] as const) || !enumValue(value.timeHorizon, ['immediate','near_term','medium_term','long_term'] as const) || !refs(value.targetExistingClaimRefs, claimRefs) || !refs(value.attackVectorRefs, vectorRefs) || !refs(value.sourceCandidateIds, sourceRefs) || (value.conditionRef !== undefined && !conditionRefs.has(String(value.conditionRef))) || (value.challengeType === 'invalidation_condition' && !conditionRefs.has(String(value.conditionRef ?? ''))) || !text(value.causalChain) || !text(value.rationale)) throw new ThesisRedTeamSemanticError('Invalid challenge assessment', [`challenge_${index}_invalid`]); if (value.basis === 'hypothesis' && value.sourceCandidateIds.length > 0) throw new ThesisRedTeamSemanticError('Hypothesis challenge cannot use durable evidence', [`challenge_${index}_hypothesis_evidence`]); return value as unknown as RedTeamChallengeAssessment }
function validateInterpretation(value: unknown, index: number, claimRefs: ReadonlySet<string>, sourceRefs: ReadonlySet<string>, challengeRefs: ReadonlySet<string>): RedTeamInterpretation { if (!record(value) || !LOCAL_ID.test(String(value.interpretationId ?? '')) || !text(value.sectionId, 120) || !text(value.markdown, 8_000) || !refs(value.sourceCandidateIds, sourceRefs) || !refs(value.existingKnowledgeRefs, claimRefs) || !refs(value.challengeRefs, challengeRefs)) throw new ThesisRedTeamSemanticError('Invalid interpretation', [`interpretation_${index}_invalid`]); return value as unknown as RedTeamInterpretation }
function validateProposal(value: unknown, index: number, context: ThesisRedTeamSkillContext, challengeRefs: ReadonlySet<string>): RedTeamProposalCandidate { if (!record(value) || !LOCAL_ID.test(String(value.proposalId ?? '')) || value.kind !== 'claim' || value.claimType === 'thesis' || value.subjectKey !== 'company' || !text(value.statement) || !refs(value.sourceCandidateIds, new Set(context.sources.map((item) => item.candidateId)), MAX_SOURCES, true) || !refs(value.challengeRefs ?? [], challengeRefs)) throw new ThesisRedTeamSemanticError('Invalid proposal candidate', [`proposal_${index}_invalid`]); if (value.claimType !== 'risk' && value.claimType !== 'viewpoint' && value.claimType !== 'assumption') throw new ThesisRedTeamSemanticError('Unsupported proposal candidate type', [`proposal_${index}_claim_type_invalid`]); return value as unknown as RedTeamProposalCandidate }
export function validateThesisRedTeamSemanticCore(value: unknown, context: ThesisRedTeamSkillContext): Omit<ThesisRedTeamSynthesisOutput, 'proposals'> { const object = parseThesisRedTeamReasoningObject(value); const sourceRefs = new Set(context.sources.map((item) => item.candidateId)); const claimRefs = new Set(context.projection.claims.map((item) => item.canonicalRef)); const vectorRefs = new Set(context.attackDesign.attackVectors.map((item) => item.vectorId)); const conditionRefs = new Set(context.attackDesign.invalidationConditions.map((item) => item.conditionId)); if (!Array.isArray(object.evidenceAssessments) || object.evidenceAssessments.length > MAX_SOURCES || !Array.isArray(object.challengeAssessments) || object.challengeAssessments.length > 16 || !enumValue(object.thesisVerdict, RED_TEAM_VERDICTS) || !Array.isArray(object.interpretations) || object.interpretations.length > 16) throw new ThesisRedTeamSemanticError('Invalid synthesis semantic core', ['synthesis_semantic_core_shape_invalid']); const evidence = object.evidenceAssessments.map((item, index) => validateEvidence(item, index, sourceRefs, vectorRefs)); const challenges = object.challengeAssessments.map((item, index) => validateChallenge(item, index, claimRefs, vectorRefs, sourceRefs, conditionRefs)); if (new Set(challenges.map((item) => item.challengeId)).size !== challenges.length) throw new ThesisRedTeamSemanticError('Duplicate challenge IDs', ['challenge_duplicate']); const challengeRefs = new Set(challenges.map((item) => item.challengeId)); const interpretations = object.interpretations.map((item, index) => validateInterpretation(item, index, claimRefs, sourceRefs, challengeRefs)); return { evidenceAssessments: evidence, challengeAssessments: challenges, thesisVerdict: object.thesisVerdict as RedTeamVerdict, interpretations } }
export function validateThesisRedTeamProposalCandidates(value: unknown, context: ThesisRedTeamSkillContext, challengeRefs: ReadonlySet<string>): { readonly proposals: readonly RedTeamProposalCandidate[]; readonly diagnostics: readonly string[] } { const object = parseThesisRedTeamReasoningObject(value); if (!Array.isArray(object.proposals) || object.proposals.length > 6) throw new ThesisRedTeamSemanticError('Invalid proposal candidate shape', ['proposal_candidate_shape_invalid']); const proposals: RedTeamProposalCandidate[] = []; const diagnostics: string[] = []; for (const [index, item] of object.proposals.entries()) { try { proposals.push(validateProposal(item, index, context, challengeRefs)) } catch (error) { diagnostics.push(...safeDiagnostics(error)) } } return { proposals, diagnostics: unique(diagnostics) } }
function validateSynthesis(value: unknown, context: ThesisRedTeamSkillContext): ThesisRedTeamSynthesisOutput { const core = validateThesisRedTeamSemanticCore(value, context); const candidates = validateThesisRedTeamProposalCandidates(value, context, new Set(core.challengeAssessments.map((item) => item.challengeId))); return { ...core, proposals: candidates.proposals } }
function validateSynthesisWithDiagnostics(value: unknown, context: ThesisRedTeamSkillContext): { readonly output: ThesisRedTeamSynthesisOutput; readonly diagnostics: readonly string[] } { const core = validateThesisRedTeamSemanticCore(value, context); const candidates = validateThesisRedTeamProposalCandidates(value, context, new Set(core.challengeAssessments.map((item) => item.challengeId))); return { output: { ...core, proposals: candidates.proposals }, diagnostics: candidates.diagnostics } }
function synthesisInstruction(context: ThesisRedTeamSkillContext): string { return `Assess evidence against the exact Thesis and attack design. Return JSON only with evidenceAssessments, challengeAssessments, thesisVerdict, interpretations, and proposals. Use exact allowlists. Hypotheses are report-only; do not create a Thesis proposal. Do not treat Signals as evidence. Thesis: ${context.thesis.statement ?? ''}` }
export async function synthesizeThesisRedTeam(context: ThesisRedTeamSkillContext, executor?: ReasoningExecutor): Promise<ThesisRedTeamSynthesisSkillResult> {
  const fallback: ThesisRedTeamSynthesisOutput = { evidenceAssessments: [], challengeAssessments: [], thesisVerdict: 'inconclusive', interpretations: [], proposals: [] }
  if (!executor) return { output: fallback, reasoning: telemetry(undefined, 'thesis_red_team_synthesis', { validated: false, applied: false, fallbackUsed: true, repairAttempts: 0, diagnostics: ['reasoning_executor_missing'] }) }
  let first: ThesisRedTeamReasoningShape | undefined; let repair: ThesisRedTeamReasoningShape | undefined; let diagnostics: readonly string[] = []
  const input = { company: context.company, thesis: context.thesis, dependencyProjection: context.projection, attackDesign: context.attackDesign, sources: context.sources, signals: context.signals, allowedClaimRefs: context.projection.claims.map((item) => item.canonicalRef), allowedSourceCandidateIds: context.sources.map((item) => item.candidateId) }
  try { const result = await executor.execute({ operation: 'thesis_red_team_synthesis', instruction: synthesisInstruction(context), input, outputContract: allowedContract('synthesis') }); first = thesisRedTeamReasoningShape(result.output); const parsed = validateSynthesisWithDiagnostics(result.output, context); return { output: parsed.output, reasoning: telemetry(executor, 'thesis_red_team_synthesis', { validated: true, applied: true, fallbackUsed: false, repairAttempts: 0, diagnostics: parsed.diagnostics, firstAttemptShape: first }) } } catch (error) { diagnostics = safeDiagnostics(error); if (!(error instanceof ThesisRedTeamSemanticError) || !error.retryable) return { output: fallback, reasoning: telemetry(executor, 'thesis_red_team_synthesis', { validated: false, applied: false, fallbackUsed: true, repairAttempts: 0, diagnostics, firstAttemptShape: first }) } }
  try { const result = await executor.execute({ operation: 'thesis_red_team_synthesis', instruction: `${synthesisInstruction(context)} Repair the prior bounded output using these diagnostics.`, input: { ...input, previousOutput: 'bounded-invalid-output', diagnostics: diagnostics.slice(0, 16) }, outputContract: allowedContract('synthesis') }); repair = thesisRedTeamReasoningShape(result.output); const parsed = validateSynthesisWithDiagnostics(result.output, context); return { output: parsed.output, reasoning: telemetry(executor, 'thesis_red_team_synthesis', { validated: true, applied: true, fallbackUsed: false, repairAttempts: 1, diagnostics: parsed.diagnostics, firstAttemptShape: first, repairAttemptShape: repair }) } } catch (error) { const finalDiagnostics = safeDiagnostics(error); return { output: fallback, reasoning: telemetry(executor, 'thesis_red_team_synthesis', { validated: false, applied: false, fallbackUsed: true, repairAttempts: 1, diagnostics: finalDiagnostics, firstAttemptShape: first, repairAttemptShape: repair }) } }
}

export function validateThesisRedTeamSynthesis(value: unknown, context: ThesisRedTeamSkillContext): ThesisRedTeamSynthesisOutput { if (record(value) && value.sections !== undefined) throw new ThesisRedTeamSemanticError('Model-owned report sections are not allowed', ['legacy_sections_rejected']); return validateSynthesis(value, context) }
export function qualifyRedTeamEvidence(assessment: RedTeamEvidenceAssessment, sources: readonly RedTeamEvidenceSource[]): import('./contracts.ts').QualifiedRedTeamEvidence { const source = sources.find((item) => item.candidateId === assessment.sourceCandidateId); if (!source) return { sourceCandidateId: assessment.sourceCandidateId, relation: assessment.relation, strength: 'low', qualified: false, durableEligible: false, reason: 'source_not_found' }; if (!source.publishedAt || Number.isNaN(Date.parse(source.publishedAt))) return { sourceCandidateId: source.candidateId, relation: assessment.relation, strength: 'low', qualified: false, durableEligible: false, reason: 'unknown_date' }; if (assessment.relation === 'irrelevant' || assessment.relation === 'context') return { sourceCandidateId: source.candidateId, relation: assessment.relation, strength: 'low', qualified: false, durableEligible: false, reason: 'non_evidence_relation' }; const providerKeys = new Set(sources.filter((item) => item.publishedAt && !Number.isNaN(Date.parse(item.publishedAt))).map((item) => { try { return new URL(item.url ?? '').hostname || item.provider } catch { return item.provider } })); const independent = providerKeys.size >= 2; const official = source.official === true || source.kind === 'official_disclosure' || /cninfo/i.test(source.provider); const strength = official || independent ? 'high' : 'medium'; return { sourceCandidateId: source.candidateId, relation: assessment.relation, strength, qualified: true, durableEligible: true, reason: official ? 'current_official_disclosure' : independent ? 'independent_provider_or_domain_corroboration' : 'single_source_only' } }
export function validateRedTeamVerdictConsistency(verdict: RedTeamVerdict, challenges: readonly RedTeamChallengeAssessment[], evidence: readonly QualifiedRedTeamEvidence[], conditionRefs: ReadonlySet<string>): { readonly valid: boolean; readonly effectiveVerdict: RedTeamVerdict; readonly diagnostics: readonly string[] } { const supported = challenges.some((item) => item.status === 'supported' && ['high', 'critical'].includes(item.severity)); const strongDisconfirming = evidence.some((item) => item.qualified && item.durableEligible && item.relation === 'disconfirms' && item.strength === 'high'); const conditionMet = challenges.some((item) => item.challengeType === 'invalidation_condition' && item.status === 'condition_met' && item.conditionRef !== undefined && conditionRefs.has(item.conditionRef)); if (verdict === 'inconclusive' && (supported || strongDisconfirming)) return { valid: false, effectiveVerdict: 'inconclusive', diagnostics: ['inconclusive_material_conclusion'] }; if (verdict === 'weakened' && !challenges.some((item) => item.status === 'supported' || item.status === 'partially_supported')) return { valid: false, effectiveVerdict: 'inconclusive', diagnostics: ['weakened_without_material_challenge'] }; if (verdict === 'materially_challenged' && !supported) return { valid: false, effectiveVerdict: 'inconclusive', diagnostics: ['materially_challenged_without_supported_high_critical_challenge'] }; if (verdict === 'invalidation_condition_met' && !(conditionMet && strongDisconfirming)) return { valid: false, effectiveVerdict: 'inconclusive', diagnostics: ['invalidation_verdict_without_matching_condition_and_evidence'] }; return { valid: true, effectiveVerdict: verdict, diagnostics: [] } }
export function filterThesisRedTeamProposals(context: ThesisRedTeamSkillContext, output: ThesisRedTeamSynthesisOutput): { readonly accepted: readonly RedTeamProposalCandidate[]; readonly diagnostics: readonly string[] } { const accepted: RedTeamProposalCandidate[] = []; const diagnostics: string[] = []; for (const [index, proposal] of output.proposals.entries()) { try { const proposalSources = proposal.sourceCandidateIds ?? []; if (proposalSources.some((id) => { const source = context.sources.find((item) => item.candidateId === id); return !source?.publishedAt || Number.isNaN(Date.parse(source.publishedAt)) })) throw new ThesisRedTeamSemanticError('Proposal references unknown-date evidence', [`proposal_${index}_unknown_date_evidence`]); if (proposal.claimType === 'risk' && !proposalSources.some((id) => context.sources.find((source) => source.candidateId === id)?.official === true || context.sources.find((source) => source.candidateId === id)?.kind === 'official_disclosure')) throw new ThesisRedTeamSemanticError('Risk candidate lacks verified evidence', [`proposal_${index}_risk_evidence_required`]); if ((proposal.claimType === 'viewpoint' || proposal.claimType === 'risk') && proposal.statement?.match(/\b\d+(?:\.\d+)?%?\b/)) throw new ThesisRedTeamSemanticError('Unsupported numeric proposal', [`proposal_${index}_numeric_unsupported`]); accepted.push(proposal) } catch (error) { diagnostics.push(...safeDiagnostics(error)) } } return { accepted, diagnostics: unique(diagnostics) } }
export function projectionClaimsForThesis(objects: readonly ThesisProjectionClaim[], companyRef: string, thesisRef: string): ThesisDependencyProjection { const byRef = new Map(objects.map((item) => [item.canonicalRef, item])); const linked = (item: ThesisProjectionClaim, field: keyof ThesisProjectionClaim) => Array.isArray(item[field]) ? (item[field] as readonly string[]) : []; const thesis = byRef.get(thesisRef) ?? { canonicalRef: thesisRef }; const direct = unique([...linked(thesis, 'dependsOnClaimRefs'), ...linked(thesis, 'supportsClaimRefs'), ...linked(thesis, 'contradictsClaimRefs')]); const incoming = objects.filter((item) => linked(item, 'supportsClaimRefs').includes(thesisRef) || linked(item, 'dependsOnClaimRefs').includes(thesisRef) || linked(item, 'contradictsClaimRefs').includes(thesisRef)).map((item) => item.canonicalRef); const required = new Set([thesisRef, ...direct, ...incoming]); const hopOne = new Set<string>(); for (const ref of [...required]) { const item = byRef.get(ref); if (item) for (const next of [...linked(item, 'dependsOnClaimRefs'), ...linked(item, 'supportsClaimRefs'), ...linked(item, 'contradictsClaimRefs')]) hopOne.add(next) } const ordered = objects.filter((item) => required.has(item.canonicalRef) && item.subjectRefs?.includes(companyRef)); const category = (item: ThesisProjectionClaim) => item.canonicalRef === thesisRef ? 0 : direct.includes(item.canonicalRef) ? 1 : ['risk','catalyst'].includes(item.claimType ?? '') ? 2 : ['fact','viewpoint','forecast','trend'].includes(item.claimType ?? '') ? 3 : hopOne.has(item.canonicalRef) ? 4 : 5; const claims = [...ordered].sort((a, b) => category(a) - category(b) || a.canonicalRef.localeCompare(b.canonicalRef)).slice(0, 40); const claimRefs = new Set(claims.map((item) => item.canonicalRef)); for (const ref of [thesisRef, ...direct]) if (!claimRefs.has(ref) && byRef.has(ref)) claims.push(byRef.get(ref)!); return { targetThesisRef: thesisRef, companyRef, claims: claims.slice(0, 40), directDependencyRefs: direct, incomingDependencyRefs: incoming, criticalAssumptions: claims.filter((item) => item.claimType === 'assumption' && direct.includes(item.canonicalRef)), risks: claims.filter((item) => item.claimType === 'risk'), catalysts: claims.filter((item) => item.claimType === 'catalyst'), supportingClaims: claims.filter((item) => item.canonicalRef !== thesisRef && linked(thesis, 'supportsClaimRefs').includes(item.canonicalRef)), contradictingClaims: claims.filter((item) => linked(thesis, 'contradictsClaimRefs').includes(item.canonicalRef)), truncated: required.size + hopOne.size > 40 } }
