import assert from 'node:assert/strict'
import test from 'node:test'
import { IndustryResearchSkill, INDUSTRY_MODULES, validateIndustryModuleResult, validateIndustryResearchDesign } from '../../../skills/industry-research/index.ts'
import type { ReasoningExecutor } from '../../../plugins/reasoning/contracts.ts'
const design = { definitionHypothesis: 'A bounded manufacturing industry.', targetKind: 'industry', scope: { included: ['manufacturing'], excluded: ['broad theme'] }, moduleQuestions: Object.fromEntries(INDUSTRY_MODULES.map((m) => [m, `Question for ${m}`])), keyMetrics: ['capacity'], evidenceRequirements: ['official'], searchTerms: ['fixture industry'], knownGaps: [], verificationCandidates: [] }
const source = { candidate: { candidateId: 's1', kind: 'official_disclosure' as const, tier: 1 as const, title: 'Official', provider: 'fixture', publishedAt: '2026-09-01' }, retrievedAt: '2026-09-01', title: 'Official', content: 'The industry supplies products.', contentHash: 'a'.repeat(64), publisher: 'Fixture', rights: { accessScope: 'public' as const, retentionAllowed: true, aiProcessingAllowed: true, derivativeKnowledgeAllowed: true, redistributionAllowed: false } }
function executor(output: unknown): ReasoningExecutor { return { capabilities: () => ({ maxContextTokens: 1000, maxOutputTokens: 1000, structuredOutputSupport: true, maxConcurrency: 2 }), execute: async (r) => ({ operation: r.operation, output }) } }
function moduleOutput(module: typeof INDUSTRY_MODULES[number]) { return { module, status: 'supported', analysis: 'Bounded analysis.', evidenceIds: ['e1'], proposals: [], gaps: [], reportMaterial: { markdown: 'Evidence-backed.', evidenceIds: ['e1'], proposalIds: [] } } }
test('Industry Skill exposes exact operations and all eight modules', async () => { const skill = new IndustryResearchSkill(executor(design)); assert.equal((await skill.design({ target: { name: 'Fixture' }, existingKnowledge: [] })).targetKind, 'industry'); for (const module of INDUSTRY_MODULES) assert.equal((await new IndustryResearchSkill(executor(moduleOutput(module))).analyze(module, { target: { name: 'Fixture' }, evidence: [{ evidenceId: 'e1', source }], existingKnowledge: [], localReferences: [] })).module, module) })
test('Industry Skill rejects canonical IDs, unknown evidence, and bounded evidence escape', () => { assert.throws(() => validateIndustryModuleResult({ ...moduleOutput('market_size_growth'), evidenceIds: ['unknown'] }, 'market_size_growth', ['e1']), /evidence/); assert.throws(() => validateIndustryModuleResult({ ...moduleOutput('market_size_growth'), proposals: [{ proposalId: 'p', kind: 'claim', subjectKey: 'entity:bad', claimType: 'fact', statement: 'bad', sourceCandidateIds: ['e1'] }] }, 'market_size_growth', ['e1']), /canonical/) })
test('Industry Skill performs at most one repair attempt and marks repeated invalid output unavailable', async () => { let calls = 0; const bad: ReasoningExecutor = { capabilities: () => ({ maxContextTokens: 1, maxOutputTokens: 1, structuredOutputSupport: true, maxConcurrency: 1 }), execute: async (r) => { calls++; return { operation: r.operation, output: { invalid: true } } } }; const result = await new IndustryResearchSkill(bad).analyze('risk_analysis', { target: { name: 'Fixture' }, evidence: [], existingKnowledge: [], localReferences: [] }); assert.equal(calls, 2); assert.equal(result.status, 'unavailable') })
test('Industry Skill validates design gaps, candidates, string arrays and quantitative values', () => {
  assert.throws(() => validateIndustryResearchDesign({ ...design, knownGaps: [{ gapId: 'entity:bad', module: 'market_size_growth', question: 'q', reason: 'r', actionable: true }] }), /known gap/)
  assert.throws(() => validateIndustryResearchDesign({ ...design, verificationCandidates: [{ name: 'x', kind: 'person', reason: 'r' }] }), /candidate/)
  assert.throws(() => validateIndustryModuleResult({ ...moduleOutput('market_size_growth'), proposals: [{ proposalId: 'p', kind: 'claim', subjectKey: 'local', claimType: 'fact', statement: 'q', sourceCandidateIds: ['e1'], structuredValue: { metric: 'm', value: NaN, unit: 'u', comparator: 'eq', period: '2026' } }] }, 'market_size_growth', ['e1']), /quantitative/)
  assert.throws(() => validateIndustryModuleResult({ ...moduleOutput('market_size_growth'), proposals: [{ proposalId: 'p', kind: 'claim', subjectKey: 'local', claimType: 'unknown', statement: 'q', sourceCandidateIds: ['e1'] }] }, 'market_size_growth', ['e1']), /Claim/)
})
