import test from 'node:test'
import assert from 'node:assert/strict'
import { createHash } from 'node:crypto'
import { decide, inferPrimitiveSchemaTypes, makeAllObjectPropertiesRequired, TYPED_ALL_REQUIRED_CONTROL, TYPED_OPTIONAL_PROPERTY_CONTROL } from './codex-cli-strict-required-schema-isolation.ts'
import { INDUSTRY_RESEARCH_DESIGN_CONTRACT } from '../../skills/industry-research/contracts.ts'
import { normalizeCodexOutputSchema } from '../../plugins/reasoning/codex-cli/executor.ts'

test('recursively requires every declared object property in schema positions', () => { const result = makeAllObjectPropertiesRequired({ type: 'object', properties: { a: { type: 'object', properties: { b: { type: 'string' } } }, list: { type: 'array', items: { type: 'object', properties: { c: { type: 'boolean' } } } }, branch: { oneOf: [{ type: 'object', properties: { d: { type: 'number' } } }] }, map: { type: 'object', additionalProperties: { type: 'object', properties: { e: { type: 'null' } } } } } }); assert.deepEqual(result.changes.map((x) => x.path), ['$', '$.properties.a', '$.properties.list.items', '$.properties.branch.oneOf[0]', '$.properties.map.additionalProperties']); assert.deepEqual((result.copy as any).properties.a.required, ['b']) })
test('requiredness and primitive helpers do not mutate authoritative source', () => { const before = JSON.stringify(INDUSTRY_RESEARCH_DESIGN_CONTRACT); const beforeFingerprint = createHash('sha256').update(before).digest('hex').slice(0, 16); makeAllObjectPropertiesRequired(INDUSTRY_RESEARCH_DESIGN_CONTRACT); inferPrimitiveSchemaTypes(INDUSTRY_RESEARCH_DESIGN_CONTRACT); assert.equal(JSON.stringify(INDUSTRY_RESEARCH_DESIGN_CONTRACT), before); assert.equal(createHash('sha256').update(JSON.stringify(INDUSTRY_RESEARCH_DESIGN_CONTRACT)).digest('hex').slice(0, 16), beforeFingerprint); assert.equal(beforeFingerprint, '9854f93073c44d96') })
test('reuses DIAG-005 primitive inference semantics', () => { const result = inferPrimitiveSchemaTypes({ properties: { s: { const: 'x' }, i: { const: 2 }, n: { const: 2.5 }, mixed: { enum: ['x', 1] } } }); assert.deepEqual(result.additions, [{ path: '$.properties.s', type: 'string' }, { path: '$.properties.i', type: 'integer' }, { path: '$.properties.n', type: 'number' }]) })
test('control schemas differ only in requiredness and normalize independently', () => { assert.deepEqual({ ...TYPED_OPTIONAL_PROPERTY_CONTROL, required: undefined }, { ...TYPED_ALL_REQUIRED_CONTROL, required: undefined }); assert.deepEqual(normalizeCodexOutputSchema(TYPED_OPTIONAL_PROPERTY_CONTROL).schema.properties, normalizeCodexOutputSchema(TYPED_ALL_REQUIRED_CONTROL).schema.properties); assert.notDeepEqual(TYPED_OPTIONAL_PROPERTY_CONTROL.required, TYPED_ALL_REQUIRED_CONTROL.required) })
const state = (extra: Record<string, unknown> = {}) => ({ attempted: true, semanticResultAvailable: false, ...extra })
test('decision state machine covers early stopping and bounded call graph', () => { assert.equal(decide({ probeA: state({ semanticResultAvailable: true }), designFingerprintUnchanged: true }).classification, 'OPTIONAL_PROPERTIES_ACCEPTED_STRICT_REQUIRED_HYPOTHESIS_REJECTED'); assert.equal(decide({ probeA: state(), probeB: state(), designFingerprintUnchanged: true }).classification, 'STRICT_REQUIRED_CONTROL_DIFFERENTIAL_NOT_PROVEN'); assert.equal(decide({ probeA: state(), probeB: state({ semanticResultAvailable: true }), probeC: state({ semanticResultAvailable: true, validatorStatus: 'passed' }), designFingerprintUnchanged: true }).classification, 'ALL_PROPERTIES_REQUIRED_TRANSFORMATION_PROVEN'); assert.equal(decide({ probeA: state(), probeB: state({ semanticResultAvailable: true }), probeC: state({ safeFailureClass: 'unknown_nonzero_exit' }), probeD: state({ semanticResultAvailable: true, validatorStatus: 'passed' }), designFingerprintUnchanged: true }).classification, 'ALL_REQUIRED_PLUS_PRIMITIVE_TYPE_INFERENCE_PROVEN'); assert.equal(decide({ probeA: state(), probeB: state({ semanticResultAvailable: true }), probeC: state({ semanticResultAvailable: true, validatorStatus: 'failed' }), designFingerprintUnchanged: true }).classification, 'ALL_REQUIRED_TRANSPORT_WORKS_SEMANTICS_INVALID'); assert.equal(decide({ probeA: state({ safeFailureClass: 'authentication_or_account' }), designFingerprintUnchanged: true }).classification, 'BACKEND_AUTH_OR_ACCOUNT_BLOCKED'); assert.equal(decide({ probeA: state(), probeB: state({ semanticResultAvailable: true }), probeC: state({ safeFailureClass: 'unknown_nonzero_exit' }), probeD: state({ safeFailureClass: 'unknown_nonzero_exit' }), designFingerprintUnchanged: true }).classification, 'STRICT_REQUIRED_AND_TYPE_INFERENCE_INSUFFICIENT') })
