import { createHash } from 'node:crypto'
import { execFile as execFileCallback } from 'node:child_process'
import { mkdir, writeFile } from 'node:fs/promises'
import { promisify } from 'node:util'
import { resolve } from 'node:path'
import { createIndustryModuleResultContract } from '../../skills/industry-research/contracts.ts'
import { parseIndustryReasoningObject, validateIndustryModuleResult } from '../../skills/industry-research/skill.ts'
import { createIndustryProductionReasoningExecutor } from '../../app/pi/model-selection.ts'
import { normalizeCodexOutputSchema } from '../../plugins/reasoning/codex-cli/executor.ts'
import { ReasoningExecutorError } from '../../plugins/reasoning/errors.ts'
import type { ReasoningRequest, ReasoningResult } from '../../plugins/reasoning/contracts.ts'

export const TASK_ID = 'RHL-M3B-3B-DIAG-013-CODEX-MODULE-SCHEMA-COMPATIBILITY'
export const BASE_COMMIT = 'cae69cc518cc38300d3a2cf7e55505c0dc045c27'
export const MAX_REAL_MODEL_CALLS = 8
export const MODULE = 'industry_definition' as const
export const CAPABILITIES = { maxContextTokens: 128_000, maxOutputTokens: 16_384, structuredOutputSupport: true, maxConcurrency: 1 } as const
export const PROBE_NAMES = ['FULL_MODULE_BASELINE', 'UNTYPED_CONST_MINIMAL', 'TYPED_CONST_MINIMAL', 'FULL_MODULE_CONST_TYPED', 'NESTED_ONEOF_MINIMAL', 'NESTED_ANYOF_MINIMAL', 'FULL_MODULE_GUARDED_VARIANT_NORMALIZATION', 'FULL_MODULE_STRUCTURED_VALUE_LEAF_NORMALIZATION'] as const
export type ProbeName = typeof PROBE_NAMES[number]
export type Classification = 'PRODUCTION_MODULE_TRANSPORT_FAILURE_NOT_REPRODUCED' | 'BASELINE_MODULE_TRANSPORT_WORKS_SEMANTICS_INVALID' | 'MODULE_CONST_TYPE_INFERENCE_PROVEN' | 'CONST_TYPED_MODULE_TRANSPORT_WORKS_SEMANTICS_INVALID' | 'MODULE_GUARDED_ONEOF_NORMALIZATION_PROVEN' | 'MODULE_CONST_AND_GUARDED_ONEOF_NORMALIZATION_PROVEN' | 'VARIANT_NORMALIZED_MODULE_TRANSPORT_WORKS_SEMANTICS_INVALID' | 'MODULE_COMBINED_SCHEMA_NORMALIZATION_PROVEN' | 'KNOWN_MODULE_SCHEMA_DELTAS_INSUFFICIENT' | 'BACKEND_AUTH_OR_ACCOUNT_BLOCKED' | 'BACKEND_MODEL_UNAVAILABLE' | 'BACKEND_RATE_OR_QUOTA_BLOCKED' | 'BACKEND_SAFETY_OR_POLICY_BLOCKED' | 'BACKEND_TIMEOUT_OR_CANCELLED' | 'BACKEND_TRANSPORT_OR_SERVICE_FAILURE' | 'BACKEND_FAILURE_DIAGNOSTIC_INCONCLUSIVE' | 'RUNTIME_CONFIGURATION_MISMATCH'
export type NextAction = 'RERUN_MODULE_DIAGNOSTIC_NO_PRODUCTION_CHANGE' | 'REVIEW_MODULE_SEMANTICS_NOT_TRANSPORT' | 'IMPLEMENT_NARROW_CODEX_PRIMITIVE_CONST_TYPE_INFERENCE' | 'REVIEW_MODULE_SEMANTICS_WITH_TRANSPORT_PROVEN' | 'IMPLEMENT_NARROW_CODEX_GUARDED_ONEOF_NORMALIZATION' | 'IMPLEMENT_NARROW_CODEX_CONST_AND_GUARDED_ONEOF_NORMALIZATION' | 'IMPLEMENT_GUARDED_CODEX_MODULE_SCHEMA_NORMALIZATION' | 'REVIEW_NEXT_CODEX_MODULE_SCHEMA_DELTA' | 'REVIEW_BACKEND_RUNTIME_FAILURE' | 'REVIEW_RUNTIME_CONFIGURATION'
export interface ProbeOutcome { name: ProbeName; actualCallOrdinal: number; contractFingerprint: string; contractBytes: number; normalizedFingerprint: string; normalizedBytes: number; processStarted: boolean; exitState: string; semanticResultAvailable: boolean; safeFailureClass: string | null; safeReasoningCode: string | null; safeErrorCode: string | null; parserStatus: string; validatorStatus: string; returnedSemanticStatus: string | null; structuralCounts: StructuralCounts; }
export interface StructuralCounts { untypedPrimitiveConst: number; enumWithoutType: number; oneOf: number; anyOf: number; emptySchemaLeaves: number; objectWithProperties: number; normalizedStrengthenedObjectCount: number; }
type Obj = Record<string, any>
const json = (v: unknown) => JSON.stringify(v)
const fingerprint = (v: unknown) => createHash('sha256').update(json(v)).digest('hex').slice(0, 16)
const size = (v: unknown) => Buffer.byteLength(json(v), 'utf8')
const clone = <T>(v: T): T => JSON.parse(json(v)) as T

export function inferPrimitiveConstTypes<T>(schema: T): T {
  const walk = (v: any): any => {
    if (Array.isArray(v)) return v.map(walk)
    if (!v || typeof v !== 'object') return v
    const out: Obj = Object.fromEntries(Object.entries(v).map(([k, x]) => [k, walk(x)]))
    if (!('type' in out) && Object.prototype.hasOwnProperty.call(out, 'const')) {
      if (typeof out.const === 'string') out.type = 'string'
      else if (typeof out.const === 'boolean') out.type = 'boolean'
      else if (typeof out.const === 'number' && Number.isFinite(out.const)) out.type = Number.isInteger(out.const) ? 'integer' : 'number'
      else if (out.const === null) out.type = 'null'
    }
    return out
  }
  return walk(clone(schema))
}

function isStrictDisjointVariant(v: any): boolean { return !!v && v.type === 'object' && v.additionalProperties === false && Array.isArray(v.required) && v.required.includes('kind') && !!v.properties?.kind && Object.prototype.hasOwnProperty.call(v.properties.kind, 'const') && ['string', 'boolean', 'number'].includes(typeof v.properties.kind.const) }
export function convertDisjointConstOneOfToAnyOf<T>(schema: T): T {
  const walk = (v: any): any => {
    if (Array.isArray(v)) return v.map(walk)
    if (!v || typeof v !== 'object') return v
    const out: Obj = Object.fromEntries(Object.entries(v).map(([k, x]) => [k, walk(x)]))
    if (Array.isArray(out.oneOf) && out.oneOf.length > 0 && out.oneOf.every(isStrictDisjointVariant)) {
      const values = out.oneOf.map((x: any) => x.properties.kind.const)
      if (new Set(values).size === values.length && values.every((x: any) => ['entity', 'relation', 'claim'].includes(x) || ['a', 'b'].includes(x))) { out.anyOf = out.oneOf; delete out.oneOf }
    }
    return out
  }
  return walk(clone(schema))
}

export function normalizeStructuredValueLeaf<T>(schema: T): T {
  const out: any = clone(schema)
  const proposalChoice = out?.properties?.proposals?.items?.oneOf ?? out?.properties?.proposals?.items?.anyOf
  if (!Array.isArray(proposalChoice)) return out
  const claim = proposalChoice.find((x: any) => x?.properties?.kind?.const === 'claim')
  const leaf = claim?.properties?.structuredValue?.properties?.value
  if (leaf && typeof leaf === 'object' && !Array.isArray(leaf) && Object.keys(leaf).length === 0) claim.properties.structuredValue.properties.value = { anyOf: [{ type: 'number' }, { type: 'string' }, { type: 'boolean' }] }
  return out
}

export function structuralCounts(schema: unknown): StructuralCounts {
  const c = { untypedPrimitiveConst: 0, enumWithoutType: 0, oneOf: 0, anyOf: 0, emptySchemaLeaves: 0, objectWithProperties: 0, normalizedStrengthenedObjectCount: 0 }
  const walk = (v: any) => { if (Array.isArray(v)) return v.forEach(walk); if (!v || typeof v !== 'object') return; if (Object.keys(v).length === 0) c.emptySchemaLeaves++; if (v.const !== undefined && v.type === undefined && (v.const === null || ['string', 'boolean', 'number'].includes(typeof v.const))) c.untypedPrimitiveConst++; if (v.enum !== undefined && v.type === undefined) c.enumWithoutType++; if (v.oneOf) c.oneOf++; if (v.anyOf) c.anyOf++; if (v.type === 'object' && v.properties) c.objectWithProperties++; Object.values(v).forEach(walk) }
  walk(schema); return c
}

export function buildMinimalConstSchema(typed: boolean): Obj { return { type: 'object', additionalProperties: false, required: ['status'], properties: { status: typed ? { type: 'string', const: 'ok' } : { const: 'ok' } } } }
export function buildNestedChoiceSchema(choice: 'oneOf' | 'anyOf'): Obj { return { type: 'object', additionalProperties: false, required: ['proposal'], properties: { proposal: { [choice]: [{ type: 'object', additionalProperties: false, required: ['kind', 'name'], properties: { kind: { type: 'string', const: 'a' }, name: { type: 'string' } } }, { type: 'object', additionalProperties: false, required: ['kind', 'value'], properties: { kind: { type: 'string', const: 'b' }, value: { type: 'string' } } }] } } } }

function classifyFailure(e: unknown): Classification { if (!(e instanceof ReasoningExecutorError)) return 'BACKEND_FAILURE_DIAGNOSTIC_INCONCLUSIVE'; switch (e.failureClass) { case 'authentication_or_account': return 'BACKEND_AUTH_OR_ACCOUNT_BLOCKED'; case 'model_unavailable': return 'BACKEND_MODEL_UNAVAILABLE'; case 'rate_limit_or_quota': return 'BACKEND_RATE_OR_QUOTA_BLOCKED'; case 'safety_or_policy': return 'BACKEND_SAFETY_OR_POLICY_BLOCKED'; case 'timeout_or_cancel': return 'BACKEND_TIMEOUT_OR_CANCELLED'; case 'transport_or_service': return 'BACKEND_TRANSPORT_OR_SERVICE_FAILURE'; default: return 'BACKEND_FAILURE_DIAGNOSTIC_INCONCLUSIVE' } }
const preSemantic = (o?: ProbeOutcome) => !!o && !o.semanticResultAvailable
export function decideProbePath(outcomes: readonly ProbeOutcome[]): { classification: Classification; nextActionCategory: NextAction; stopReason: string } {
  const a = outcomes.find(x => x.name === 'FULL_MODULE_BASELINE'); const b = outcomes.find(x => x.name === 'UNTYPED_CONST_MINIMAL'); const c = outcomes.find(x => x.name === 'TYPED_CONST_MINIMAL'); const d = outcomes.find(x => x.name === 'FULL_MODULE_CONST_TYPED'); const e = outcomes.find(x => x.name === 'NESTED_ONEOF_MINIMAL'); const f = outcomes.find(x => x.name === 'NESTED_ANYOF_MINIMAL'); const g = outcomes.find(x => x.name === 'FULL_MODULE_GUARDED_VARIANT_NORMALIZATION'); const h = outcomes.find(x => x.name === 'FULL_MODULE_STRUCTURED_VALUE_LEAF_NORMALIZATION')
  if (a?.semanticResultAvailable && a.validatorStatus === 'passed') return { classification: 'PRODUCTION_MODULE_TRANSPORT_FAILURE_NOT_REPRODUCED', nextActionCategory: 'RERUN_MODULE_DIAGNOSTIC_NO_PRODUCTION_CHANGE', stopReason: 'Baseline module parsed and validated' }
  if (a?.semanticResultAvailable) return { classification: 'BASELINE_MODULE_TRANSPORT_WORKS_SEMANTICS_INVALID', nextActionCategory: 'REVIEW_MODULE_SEMANTICS_NOT_TRANSPORT', stopReason: 'Baseline reached semantic output but validation failed' }
  if (a && a.safeFailureClass && a.safeFailureClass !== 'structured_output_configuration' && a.safeFailureClass !== 'unknown_nonzero_exit') return { classification: classifyFailure({ failureClass: a.safeFailureClass } as any), nextActionCategory: 'REVIEW_BACKEND_RUNTIME_FAILURE', stopReason: 'Baseline failed in an environmental backend category' }
  if (!b || !c) return { classification: 'BACKEND_FAILURE_DIAGNOSTIC_INCONCLUSIVE', nextActionCategory: 'REVIEW_BACKEND_RUNTIME_FAILURE', stopReason: 'Const differential incomplete' }
  if (b.safeFailureClass && b.safeFailureClass !== 'structured_output_configuration' && b.safeFailureClass !== 'unknown_nonzero_exit' && !b.semanticResultAvailable) return { classification: classifyFailure({ failureClass: b.safeFailureClass } as any), nextActionCategory: 'REVIEW_BACKEND_RUNTIME_FAILURE', stopReason: 'Untyped const control failed environmentally' }
  if (c.safeFailureClass && c.safeFailureClass !== 'structured_output_configuration' && c.safeFailureClass !== 'unknown_nonzero_exit' && !c.semanticResultAvailable) return { classification: classifyFailure({ failureClass: c.safeFailureClass } as any), nextActionCategory: 'REVIEW_BACKEND_RUNTIME_FAILURE', stopReason: 'Typed const control failed environmentally' }
  const constRequired = preSemantic(b) && c.semanticResultAvailable
  if (constRequired && d?.semanticResultAvailable && d.validatorStatus === 'passed') return { classification: 'MODULE_CONST_TYPE_INFERENCE_PROVEN', nextActionCategory: 'IMPLEMENT_NARROW_CODEX_PRIMITIVE_CONST_TYPE_INFERENCE', stopReason: 'Typed const differential and full Module validation passed' }
  if (constRequired && d?.semanticResultAvailable) return { classification: 'CONST_TYPED_MODULE_TRANSPORT_WORKS_SEMANTICS_INVALID', nextActionCategory: 'REVIEW_MODULE_SEMANTICS_WITH_TRANSPORT_PROVEN', stopReason: 'Const-typed Module reached semantic output but validation failed' }
  if (!e || !f) return { classification: 'BACKEND_FAILURE_DIAGNOSTIC_INCONCLUSIVE', nextActionCategory: 'REVIEW_BACKEND_RUNTIME_FAILURE', stopReason: 'oneOf differential incomplete' }
  if (e.semanticResultAvailable && f.semanticResultAvailable) return { classification: 'KNOWN_MODULE_SCHEMA_DELTAS_INSUFFICIENT', nextActionCategory: 'REVIEW_NEXT_CODEX_MODULE_SCHEMA_DELTA', stopReason: 'oneOf and anyOf both accepted' }
  if (preSemantic(e) && f.semanticResultAvailable) { if (g?.semanticResultAvailable && g.validatorStatus === 'passed') return { classification: constRequired ? 'MODULE_CONST_AND_GUARDED_ONEOF_NORMALIZATION_PROVEN' : 'MODULE_GUARDED_ONEOF_NORMALIZATION_PROVEN', nextActionCategory: constRequired ? 'IMPLEMENT_NARROW_CODEX_CONST_AND_GUARDED_ONEOF_NORMALIZATION' : 'IMPLEMENT_NARROW_CODEX_GUARDED_ONEOF_NORMALIZATION', stopReason: 'Guarded variant normalization passed full Module validation' }; if (g?.semanticResultAvailable) return { classification: 'VARIANT_NORMALIZED_MODULE_TRANSPORT_WORKS_SEMANTICS_INVALID', nextActionCategory: 'REVIEW_MODULE_SEMANTICS_WITH_TRANSPORT_PROVEN', stopReason: 'Variant-normalized Module reached semantic output but validation failed' }; if (h?.semanticResultAvailable && h.validatorStatus === 'passed') return { classification: 'MODULE_COMBINED_SCHEMA_NORMALIZATION_PROVEN', nextActionCategory: 'IMPLEMENT_GUARDED_CODEX_MODULE_SCHEMA_NORMALIZATION', stopReason: 'Structured-value leaf normalization passed full Module validation' }; if (h) return { classification: 'KNOWN_MODULE_SCHEMA_DELTAS_INSUFFICIENT', nextActionCategory: 'REVIEW_NEXT_CODEX_MODULE_SCHEMA_DELTA', stopReason: 'Known schema deltas remained insufficient' } }
  return { classification: 'BACKEND_FAILURE_DIAGNOSTIC_INCONCLUSIVE', nextActionCategory: 'REVIEW_BACKEND_RUNTIME_FAILURE', stopReason: 'No permitted differential established compatibility' }
}

const neutralInput = { module: MODULE, target: { name: 'generic fictional industry' }, evidence: [], existingKnowledge: [], localReferences: [] }
const instruction = 'Return one bounded module result for a generic fictional industry with zero evidence. Use status unavailable, empty evidenceIds and proposals, one bounded actionable gap, and valid reportMaterial.'
function safeError(e: unknown): Partial<ProbeOutcome> { const x = e instanceof ReasoningExecutorError ? e : undefined; return { processStarted: x?.processStarted ?? false, exitState: x?.exitState ?? 'not_started', semanticResultAvailable: false, safeFailureClass: x?.failureClass ?? 'unknown_nonzero_exit', safeReasoningCode: x?.code ?? 'reasoning_execution_failed', safeErrorCode: x?.safeErrorCode ?? null, parserStatus: 'not_run', validatorStatus: 'not_run', returnedSemanticStatus: null } }
async function cliVersion(): Promise<string | null> { try { const r = await promisify(execFileCallback)('codex', ['--version'], { windowsHide: true, maxBuffer: 8_000 }); return r.stdout.trim().slice(0, 128) || null } catch { return null } }
async function runProbe(executor: any, name: ProbeName, contract: unknown, ordinal: number, counts: StructuralCounts): Promise<ProbeOutcome> { const normalized = normalizeCodexOutputSchema(contract); const base: ProbeOutcome = { name, actualCallOrdinal: ordinal, contractFingerprint: fingerprint(contract), contractBytes: size(contract), normalizedFingerprint: normalized.fingerprint, normalizedBytes: normalized.bytes, processStarted: false, exitState: 'not_started', semanticResultAvailable: false, safeFailureClass: null, safeReasoningCode: null, safeErrorCode: null, parserStatus: 'not_run', validatorStatus: 'not_run', returnedSemanticStatus: null, structuralCounts: counts }; const request: ReasoningRequest = { operation: name.includes('MINIMAL') ? 'industry_module_analysis' : 'industry_module_analysis', instruction, input: name.includes('MINIMAL') ? { request: name.includes('CONST') ? { status: 'ok' } : { proposal: { kind: 'a', name: 'neutral' } } } : neutralInput, outputContract: contract, metadata: { executionId: `diag-013-${ordinal}` } }; try { const result: ReasoningResult = await executor.execute(request); const parsed = parseIndustryReasoningObject(result.output); let validStatus = 'failed'; let semanticStatus: string | null = null; try { const validated = name.includes('MINIMAL') ? parsed : validateIndustryModuleResult(parsed, MODULE, []); validStatus = 'passed'; semanticStatus = name.includes('MINIMAL') ? null : String((validated as any).status) } catch { /* recorded below */ } return { ...base, processStarted: true, exitState: 'normal_exit', semanticResultAvailable: true, parserStatus: 'passed', validatorStatus: validStatus, returnedSemanticStatus: semanticStatus } } catch (e) { return { ...base, ...safeError(e) } } }

export async function main(): Promise<void> { const source = createIndustryModuleResultContract(MODULE, []); const sourceBefore = fingerprint(source); const normalized = normalizeCodexOutputSchema(source); const baselineCounts = structuralCounts(source); baselineCounts.normalizedStrengthenedObjectCount = normalized.strengthenedObjectCount; const outcomes: ProbeOutcome[] = []; let executor: any; try { executor = await createIndustryProductionReasoningExecutor({ capabilities: CAPABILITIES, timeoutMs: 900_000, maxOutputChars: 400_000 }) } catch (e) { outcomes.push({ name: 'FULL_MODULE_BASELINE', actualCallOrdinal: 0, contractFingerprint: sourceBefore, contractBytes: size(source), normalizedFingerprint: normalized.fingerprint, normalizedBytes: normalized.bytes, structuralCounts: baselineCounts, ...safeError(e) } as ProbeOutcome) }
  const call = async (name: ProbeName, contract: unknown) => outcomes.push(await runProbe(executor, name, contract, outcomes.length + 1, structuralCounts(contract)))
  if (executor) { const meta = executor.runtimeMetadata?.(); if (meta?.backend !== 'codex-cli' || meta?.requestedModel !== 'gpt-5.6-luna' || meta?.requestedReasoningEffort !== 'medium' || meta?.structuredOutputEnabled !== true) { const evidence = makeEvidence(source, sourceBefore, normalized, baselineCounts, outcomes, { classification: 'RUNTIME_CONFIGURATION_MISMATCH', nextActionCategory: 'REVIEW_RUNTIME_CONFIGURATION', stopReason: 'Production executor metadata mismatch' }, await cliVersion()); await writeEvidence(evidence); return }
    await call('FULL_MODULE_BASELINE', source); const a = outcomes[0]; if (a.semanticResultAvailable) { await writeEvidence(makeEvidence(source, sourceBefore, normalized, baselineCounts, outcomes, decideProbePath(outcomes), await cliVersion())); return }
    await call('UNTYPED_CONST_MINIMAL', buildMinimalConstSchema(false)); await call('TYPED_CONST_MINIMAL', buildMinimalConstSchema(true)); const b = outcomes[1], c = outcomes[2]; const differentialFailure = (x: ProbeOutcome) => !x.semanticResultAvailable && x.safeFailureClass !== 'structured_output_configuration' && x.safeFailureClass !== 'unknown_nonzero_exit'; if (b.semanticResultAvailable && c.semanticResultAvailable) {} else if (differentialFailure(b) || differentialFailure(c)) { await writeEvidence(makeEvidence(source, sourceBefore, normalized, baselineCounts, outcomes, decideProbePath(outcomes), await cliVersion())); return } else if (!b.semanticResultAvailable && c.semanticResultAvailable) await call('FULL_MODULE_CONST_TYPED', inferPrimitiveConstTypes(source));
    const d = outcomes.find(x => x.name === 'FULL_MODULE_CONST_TYPED'); if (d?.semanticResultAvailable) { await writeEvidence(makeEvidence(source, sourceBefore, normalized, baselineCounts, outcomes, decideProbePath(outcomes), await cliVersion())); return }
    await call('NESTED_ONEOF_MINIMAL', buildNestedChoiceSchema('oneOf')); await call('NESTED_ANYOF_MINIMAL', buildNestedChoiceSchema('anyOf')); const e = outcomes.find(x => x.name === 'NESTED_ONEOF_MINIMAL'), f = outcomes.find(x => x.name === 'NESTED_ANYOF_MINIMAL'); if (e?.semanticResultAvailable && f?.semanticResultAvailable || !e?.semanticResultAvailable && !f?.semanticResultAvailable) { await writeEvidence(makeEvidence(source, sourceBefore, normalized, baselineCounts, outcomes, decideProbePath(outcomes), await cliVersion())); return } if (!e?.semanticResultAvailable && f?.semanticResultAvailable) { let transformed: any = source; if (b && !b.semanticResultAvailable && c?.semanticResultAvailable) transformed = inferPrimitiveConstTypes(transformed); transformed = convertDisjointConstOneOfToAnyOf(transformed); await call('FULL_MODULE_GUARDED_VARIANT_NORMALIZATION', transformed); const g = outcomes.find(x => x.name === 'FULL_MODULE_GUARDED_VARIANT_NORMALIZATION'); if (!g?.semanticResultAvailable) await call('FULL_MODULE_STRUCTURED_VALUE_LEAF_NORMALIZATION', normalizeStructuredValueLeaf(transformed)) }
  }
  await writeEvidence(makeEvidence(source, sourceBefore, normalized, baselineCounts, outcomes, decideProbePath(outcomes), await cliVersion())) }
function makeEvidence(source: any, sourceBefore: string, normalized: any, counts: StructuralCounts, probes: ProbeOutcome[], decision: any, cliVersionValue: string | null) { const sourceAfter = fingerprint(source); return { taskId: TASK_ID, baseCommit: BASE_COMMIT, generatedAt: new Date().toISOString(), diag012Acceptance: { acceptedTestEvidenceOnly: true, classification: 'MODULE_TRANSPORT_BLOCKER_PROVEN', designCalls: 1, moduleCalls: 16, boundedRepairPerModule: true, synthesisRequested: false, terminalKnowledgeRevision: 0, acquisitionLimitation: { cninfoEmpty: true, gdeltEastmoneyAkshareFailed: true, evidenceRelevanceEstablished: false } }, backend: 'codex-cli', model: 'gpt-5.6-luna', effort: 'medium', cliVersion: cliVersionValue, authoritativeModuleSource: { fingerprint: sourceAfter, bytes: size(source), byteEqualBeforeAfter: sourceBefore === sourceAfter }, baselineNormalized: { fingerprint: normalized.fingerprint, bytes: normalized.bytes }, structuralFeatureCounts: counts, helperTransformations: { primitiveConstTypeInference: 'TEST-only, primitive consts only', guardedOneOfConversion: 'TEST-only, strict unique kind const entity|relation|claim only', structuredValueLeaf: 'TEST-only, exact structuredValue.value empty leaf to finite scalar anyOf' }, probes, actualCallCount: probes.length, modelCallCount: probes.length, provenDifferentials: { primitiveConstTypeRequirementDifferential: probes.some(x => x.name === 'UNTYPED_CONST_MINIMAL' && !x.semanticResultAvailable) && probes.some(x => x.name === 'TYPED_CONST_MINIMAL' && x.semanticResultAvailable) ? 'proven' : 'not_proven', nestedOneOfDifferential: probes.some(x => x.name === 'NESTED_ONEOF_MINIMAL' && !x.semanticResultAvailable) && probes.some(x => x.name === 'NESTED_ANYOF_MINIMAL' && x.semanticResultAvailable) ? 'proven' : 'not_proven' }, ...decision, mutation: { knowledgeMutation: false, gatewaySubmitCount: 0, writerCommitCount: 0, productionCodeMutation: false, sourceContractMutated: false, acquisitionCalls: 0 }, privacy: { rawPrompt: false, fullInput: false, fullSchema: false, modelOutput: false, stdout: false, stderr: false, jsonl: false, credentials: false, authData: false, privatePaths: false, reasoningTraces: false }, maxRealModelCalls: MAX_REAL_MODEL_CALLS } }
async function writeEvidence(evidence: unknown) { const path = resolve(import.meta.dirname, 'evidence/RHL_M3B_CODEX_MODULE_SCHEMA_COMPATIBILITY.json'); await mkdir(resolve(import.meta.dirname, 'evidence'), { recursive: true }); await writeFile(path, `${JSON.stringify(evidence, null, 2)}\n`, 'utf8'); console.log(JSON.stringify(evidence, null, 2)) }
if (process.argv[1]?.endsWith('codex-module-schema-compatibility.ts')) await main()
