import test from 'node:test'
import assert from 'node:assert/strict'
import { createProbePlans, buildStrictRequiredCopy, decideMatrix, EXPECTED_DESIGN_FINGERPRINT, EXPECTED_DESIGN_TRANSPORT, PROBE_NAMES } from './codex-cli-structured-schema-compatibility-matrix.ts'
import { INDUSTRY_RESEARCH_DESIGN_CONTRACT } from '../../skills/industry-research/contracts.ts'

const outcome = (name: typeof PROBE_NAMES[number], extra: Record<string, unknown> = {}) => ({ name, attempted: true, processStarted: true, exitState: 'normal_exit', semanticResultAvailable: true, safeReasoningCode: null, safeFailureClass: null, structuredEventType: null, safeErrorCode: null, durationMs: 1, schemaFingerprint: 'x', schemaBytes: 1, outputHash: 'x', outputBytes: 1, ...extra }) as any

test('plans are deterministic and match the accepted Design fingerprints', () => { const info = createProbePlans(); assert.equal(info.sourceFingerprint, EXPECTED_DESIGN_FINGERPRINT); assert.equal(info.normalizedDesignFingerprint, EXPECTED_DESIGN_TRANSPORT.fingerprint); assert.equal(info.normalizedDesignBytes, EXPECTED_DESIGN_TRANSPORT.bytes); assert.deepEqual(info.plans.map((p) => p.name), PROBE_NAMES.slice(0, 3)) })
test('Probe 1 failure stops later probes', () => { const decision = decideMatrix([outcome('MINIMAL_STRICT_CONTROL', { semanticResultAvailable: false, safeFailureClass: 'unknown_nonzero_exit' })]); assert.equal(decision.classification, 'BACKEND_FAILURE_DIAGNOSTIC_INCONCLUSIVE'); assert.equal(decision.calls, 1) })
test('Probe 1 success, optional configuration failure, Design configuration failure permits Probe 4', () => { const decision = decideMatrix([outcome('MINIMAL_STRICT_CONTROL'), outcome('OPTIONAL_PROPERTY_PROBE', { semanticResultAvailable: false, safeFailureClass: 'structured_output_configuration' }), outcome('CURRENT_DESIGN_SCHEMA_NEUTRAL', { semanticResultAvailable: false, safeFailureClass: 'structured_output_configuration' }), outcome('STRICT_REQUIRED_DESIGN_PROBE', { validatorStatus: 'passed' })]); assert.equal(decision.classification, 'STRICT_REQUIRED_DESIGN_TRANSFORMATION_PROVEN'); assert.equal(decision.calls, 4) })
test('successful current Design stops before Probe 4', () => { const decision = decideMatrix([outcome('MINIMAL_STRICT_CONTROL'), outcome('OPTIONAL_PROPERTY_PROBE'), outcome('CURRENT_DESIGN_SCHEMA_NEUTRAL', { validatorStatus: 'passed' })]); assert.equal(decision.classification, 'CURRENT_DESIGN_SCHEMA_EXECUTES'); assert.equal(decision.calls, 3) })
test('unrelated Design backend failure blocks Probe 4', () => { const decision = decideMatrix([outcome('MINIMAL_STRICT_CONTROL'), outcome('OPTIONAL_PROPERTY_PROBE', { semanticResultAvailable: false, safeFailureClass: 'structured_output_configuration' }), outcome('CURRENT_DESIGN_SCHEMA_NEUTRAL', { semanticResultAvailable: false, safeFailureClass: 'transport_or_service' })]); assert.equal(decision.classification, 'OPTIONAL_PROPERTY_STRICTNESS_INCOMPATIBILITY_UNCONFIRMED'); assert.equal(decision.calls, 3) })
test('Probe 4 failure yields other Design incompatibility', () => { const decision = decideMatrix([outcome('MINIMAL_STRICT_CONTROL'), outcome('OPTIONAL_PROPERTY_PROBE', { semanticResultAvailable: false, safeFailureClass: 'structured_output_configuration' }), outcome('CURRENT_DESIGN_SCHEMA_NEUTRAL', { semanticResultAvailable: false, safeFailureClass: 'structured_output_configuration' }), outcome('STRICT_REQUIRED_DESIGN_PROBE', { semanticResultAvailable: false, safeFailureClass: 'structured_output_configuration' })]); assert.equal(decision.classification, 'DESIGN_SCHEMA_OTHER_INCOMPATIBILITY') })
test('strict-required copy is recursive and does not mutate source', () => { const before = JSON.stringify(INDUSTRY_RESEARCH_DESIGN_CONTRACT); const copy = buildStrictRequiredCopy(INDUSTRY_RESEARCH_DESIGN_CONTRACT) as any; assert.equal(JSON.stringify(INDUSTRY_RESEARCH_DESIGN_CONTRACT), before); assert.deepEqual(copy.required, Object.keys(copy.properties)); assert.deepEqual(copy.properties.scope.required, Object.keys(copy.properties.scope.properties)); assert.deepEqual(copy.properties.moduleQuestions.required, Object.keys(copy.properties.moduleQuestions.properties)); assert.notEqual(copy, INDUSTRY_RESEARCH_DESIGN_CONTRACT) })
