import test from 'node:test'
import assert from 'node:assert/strict'
import { decide, MAX_REAL_MODEL_CALLS, parseFinalAssistantEvent, satisfiesMinimalSchema, PROBES } from './codex-cli-native-structured-output-isolation.ts'

const record = (name: typeof PROBES[number], extra: Record<string, unknown> = {}) => ({ name, attempted: true, processStarted: true, exitCode: 0, exitState: 'normal_exit', durationMs: 1, flags: {}, schemaEnabled: name !== PROBES[0], jsonEventsEnabled: name !== PROBES[2], outputFileEnabled: name !== PROBES[3], model: 'gpt-5.6-luna', reasoningEffort: 'medium', stdoutSha256: 'x', stdoutBytes: 0, stderrSha256: 'x', stderrBytes: 0, finalOutputSha256: 'x', finalOutputBytes: 1, validJson: true, schemaSatisfied: false, safeFailureClass: null, safeProviderCliCode: null, externalSetupRequired: false, ...extra }) as any

test('Probe A failure stops', () => { const r = decide([record(PROBES[0], { processStarted: true, exitCode: 1, exitState: 'nonzero_exit', validJson: false, safeFailureClass: 'unknown_nonzero_exit' })]); assert.equal(r.classification, 'NATIVE_STRUCTURED_OUTPUT_FAILURE_UNCLASSIFIED') })
test('Probe B success stops as native working', () => { const r = decide([record(PROBES[0]), record(PROBES[1], { schemaSatisfied: true })]); assert.equal(r.classification, 'NATIVE_STRUCTURED_OUTPUT_WORKS') })
test('B failure and C success is JSON event conflict', () => { const r = decide([record(PROBES[0]), record(PROBES[1], { exitCode: 1, validJson: false, safeFailureClass: 'structured_output_unsupported_for_model' }), record(PROBES[2], { schemaSatisfied: true })]); assert.equal(r.classification, 'JSON_EVENT_MODE_CONFLICT') })
test('B/C failure and D success is output file conflict', () => { const fail = { exitCode: 1, validJson: false, safeFailureClass: 'structured_output_unsupported_for_model' }; const r = decide([record(PROBES[0]), record(PROBES[1], fail), record(PROBES[2], fail), record(PROBES[3], { schemaSatisfied: true })]); assert.equal(r.classification, 'OUTPUT_LAST_MESSAGE_CONFLICT') })
test('consistent structured rejection is Luna unsupported', () => { const fail = { exitCode: 1, validJson: false, safeFailureClass: 'structured_output_unsupported_for_model' }; const r = decide([record(PROBES[0]), record(PROBES[1], fail), record(PROBES[2], fail), record(PROBES[3], fail)]); assert.equal(r.classification, 'LUNA_STRUCTURED_OUTPUT_UNSUPPORTED_OR_SERVER_REJECTED') })
test('unknown structured failures are unclassified', () => { const fail = { exitCode: 1, validJson: false, safeFailureClass: 'unknown_nonzero_exit' }; const r = decide([record(PROBES[0]), record(PROBES[1], fail), record(PROBES[2], fail), record(PROBES[3], fail)]); assert.equal(r.classification, 'NATIVE_STRUCTURED_OUTPUT_FAILURE_UNCLASSIFIED') })
test('external setup stops immediately and calls remain four maximum', () => { const r = decide([record(PROBES[0], { processStarted: false, exitState: 'not_started', externalSetupRequired: true, validJson: false })]); assert.equal(r.classification, 'BLOCKED_EXTERNAL_SETUP'); assert.equal(PROBES.length, MAX_REAL_MODEL_CALLS); assert.ok([PROBES[0]].length <= MAX_REAL_MODEL_CALLS) })
test('final event parser and minimal assertion are deterministic', () => { const output = parseFinalAssistantEvent('{"type":"item.completed","item":{"type":"agent_message","text":"{\\"status\\":\\"ok\\"}"}}'); assert.equal(output, '{"status":"ok"}'); assert.equal(satisfiesMinimalSchema(JSON.parse(output!)), true); assert.equal(satisfiesMinimalSchema({ status: 'ok', extra: 1 }), false) })
