import { mkdir, writeFile } from 'node:fs/promises'
import { dirname } from 'node:path'
import { CpcaAcquisitionError, CpcaIndustryResearchPlugin, cpcaTargetTerms, CPCA_INDUSTRY_ROUTES, validCpcaUrl } from '../../plugins/research-acquisition/cpca-industry.ts'
import type { ResearchSourceCandidate } from '../../plugins/research-acquisition/contracts.ts'
import { sha256 } from '../../plugins/research-acquisition/hash.ts'

export const CPCA_LIVE_CLASSIFICATIONS = ['CPCA_SPECIALIST_SOURCE_PROVEN', 'CPCA_SPECIALIST_SOURCE_PARTIAL', 'CPCA_DISCOVERY_EMPTY', 'CPCA_RESTRICTED_ONLY', 'CPCA_ROUTE_OR_PARSER_GAP', 'LIVE_SOURCE_INCONCLUSIVE'] as const
export type CpcaLiveClassification = typeof CPCA_LIVE_CLASSIFICATIONS[number]
export const CPCA_OUTCOME_CLASSES = ['NORMALIZED_PUBLIC', 'RESTRICTED_ACCESS_GATE', 'FETCH_OR_TRANSPORT_FAILURE', 'UNSUPPORTED_MEDIA', 'PARSER_OR_NORMALIZATION_FAILURE', 'OTHER_SAFE_FAILURE'] as const
export type CpcaOutcomeClass = typeof CPCA_OUTCOME_CLASSES[number]
export type CpcaProbeOutcome = { readonly outcome: CpcaOutcomeClass; readonly relevant?: boolean; readonly publishedAt?: string }

export function classifyCpcaOutcomes(input: { readonly discoveryStable: boolean; readonly targetRelevantCandidates: number; readonly outcomes: readonly CpcaProbeOutcome[]; readonly has2026PcbAnalysis?: boolean; readonly has2026MarketAnalysis?: boolean }): CpcaLiveClassification {
  const normalized = input.outcomes.filter((x) => x.outcome === 'NORMALIZED_PUBLIC').length
  const ambiguous = input.outcomes.some((x) => ['FETCH_OR_TRANSPORT_FAILURE', 'UNSUPPORTED_MEDIA', 'PARSER_OR_NORMALIZATION_FAILURE', 'OTHER_SAFE_FAILURE'].includes(x.outcome))
  if (normalized >= 2 && input.has2026PcbAnalysis && input.has2026MarketAnalysis) return 'CPCA_SPECIALIST_SOURCE_PROVEN'
  if (normalized > 0) return 'CPCA_SPECIALIST_SOURCE_PARTIAL'
  if (ambiguous) return input.outcomes.some((x) => x.outcome === 'FETCH_OR_TRANSPORT_FAILURE') ? 'LIVE_SOURCE_INCONCLUSIVE' : 'CPCA_ROUTE_OR_PARSER_GAP'
  if (input.targetRelevantCandidates > 0 && input.outcomes.length > 0 && input.outcomes.every((x) => x.outcome === 'RESTRICTED_ACCESS_GATE')) return 'CPCA_RESTRICTED_ONLY'
  return input.discoveryStable && input.targetRelevantCandidates === 0 ? 'CPCA_DISCOVERY_EMPTY' : 'LIVE_SOURCE_INCONCLUSIVE'
}

const output = 'tests/validation/evidence/RHL_M3B_CPCA_INDUSTRY_PRODUCTION_ACQUISITION.json'
const target = { name: 'PCB Manufacturing', aliases: ['Printed Circuit Board', '印制电路板'], searchTerms: ['PCB 印制电路板', 'AI服务器 PCB HDI', 'PCB 产业链', 'PCB 行业 产能', 'PCB 市场分析', 'PCB 行业周报', '覆铜板 CCL', '电子信息制造业'], asOf: '2026-09-14T00:00:00.000Z' }
const hash = (value: string | Uint8Array) => sha256(value).slice(0, 16)
const sizeBucket = (size: number) => size < 16 * 1024 ? '0-16KiB' : size < 256 * 1024 ? '16-256KiB' : size < 1024 * 1024 ? '256KiB-1MiB' : '1-8MiB'
const errorOutcome = (error: unknown): CpcaOutcomeClass => error instanceof CpcaAcquisitionError ? error.code : 'OTHER_SAFE_FAILURE'

const main = async () => {
  let phase: 'discovery' | 'candidate' = 'discovery'; let listPages = 0; let candidateFetches = 0; let stableRoutes = 0; let targetMatches = 0; let candidates: readonly ResearchSourceCandidate[] = []; let failure: string | null = null
  const routeEvidence: unknown[] = []; const sources: Record<string, unknown>[] = []; const outcomes: CpcaProbeOutcome[] = []
  const vocabulary = cpcaTargetTerms({ industry: target }); const evidence: Record<string, unknown> = { taskId: 'RHL-M3B-3B-FIX-025-CPCA-RESTRICTION-AND-LIVE-CLASSIFICATION', baseCommit: '28681734d9c16ae54f4ac1acce118d0885b0773a', generatedAt: new Date().toISOString(), target: { nameHash: hash(target.name), aliasHashes: target.aliases.map(hash), searchTermHashes: target.searchTerms.map(hash), targetTermHashes: vocabulary.map(hash), targetTermCount: vocabulary.length, asOf: target.asOf }, authorizedRoutes: CPCA_INDUSTRY_ROUTES.map((route) => new URL(route).pathname), requestCounts: { listPages: 0, candidateFetches: 0, retries: 0, modelCalls: 0, gatewaySubmissions: 0, writerCommits: 0, knowledgeMutations: 0 }, routeEvidence, candidates: 0, normalizedSources: 0, publicOutcomes: 0, restrictedOutcomes: 0, publicationDateAvailability: 0, canonicalHosts: [], sources, mutation: { modelCalls: 0, gatewaySubmissions: 0, writerCommits: 0, knowledgeMutations: 0 }, privacy: { rawBodiesIncluded: false, fullDocumentsIncluded: false, cookiesIncluded: false, credentialsIncluded: false, authorizationHeadersIncluded: false, privateAbsolutePathsIncluded: false, reasoningTracesIncluded: false } }
  try {
    const searchTerms = cpcaTargetTerms({ industry: target })
    const plugin = new CpcaIndustryResearchPlugin({ fetchImpl: async (input, init) => { const requested = new URL(String(input)); if (phase === 'discovery') listPages++; else candidateFetches++; const response = await fetch(input, init); const final = response.url || String(input); const item: Record<string, unknown> = { requested: { host: requested.hostname, path: requested.pathname }, final: { host: new URL(final).hostname, path: new URL(final).pathname }, http: response.status, finalAuthorized: validCpcaUrl(final) }; if (phase === 'discovery') { try { const bytes = new Uint8Array(await response.clone().arrayBuffer()); const html = new TextDecoder().decode(bytes).slice(0, 2 * 1024 * 1024); const anchors = [...html.matchAll(/<a\b[^>]*href\s*=\s*["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)]; const matches = anchors.filter((anchor) => searchTerms.some((term) => html.slice(Math.max(0, (anchor.index ?? 0) - 180), Math.min(html.length, (anchor.index ?? 0) + anchor[0].length + 180)).toLocaleLowerCase().includes(term.toLocaleLowerCase()))); targetMatches += matches.length; routeEvidence.push({ ...item, sizeBucket: sizeBucket(bytes.byteLength), anchorCount: anchors.length, targetMatchCount: matches.length, responseHash: hash(bytes) }); stableRoutes++ } catch { routeEvidence.push({ ...item, sizeBucket: 'unavailable', anchorCount: 0, targetMatchCount: 0, responseHash: null }) } } return response } })
    candidates = await plugin.discover({ industry: target, asOf: target.asOf, limitPerKind: 8 }); evidence.candidates = candidates.length; phase = 'candidate'
    for (const candidate of candidates.slice(0, 4)) { try { const normalized = await plugin.normalize(await plugin.fetch(candidate)); const url = new URL(normalized.canonicalUrl!); sources.push({ titleHash: hash(normalized.title), safeTitle: normalized.title.slice(0, 160), canonicalHost: url.hostname, path: url.pathname, publishedAt: candidate.publishedAt ?? null, dateAvailable: Boolean(candidate.publishedAt), discoveryRoute: candidate.metadata?.discoveryRoute ?? null, contentHash: normalized.contentHash, kind: normalized.candidate.kind, tier: normalized.candidate.tier, outcome: 'NORMALIZED_PUBLIC' }); outcomes.push({ outcome: 'NORMALIZED_PUBLIC', relevant: true, publishedAt: candidate.publishedAt }) } catch (error) { const outcome = errorOutcome(error); outcomes.push({ outcome, relevant: true, publishedAt: candidate.publishedAt }); const url = candidate.url ? new URL(candidate.url) : null; sources.push({ titleHash: hash(candidate.title), safeTitle: candidate.title.slice(0, 160), requestedHost: url?.hostname ?? null, requestedPath: url?.pathname ?? null, publishedAt: candidate.publishedAt ?? null, dateAvailable: Boolean(candidate.publishedAt), discoveryRoute: candidate.metadata?.discoveryRoute ?? null, outcome }) } }
  } catch (error) { failure = error instanceof Error ? error.name.slice(0, 40) : 'live failure' }
  const counts = evidence.requestCounts as Record<string, number>; counts.listPages = listPages; counts.candidateFetches = candidateFetches; const has2026PcbAnalysis = sources.some((x) => /pcb|printed circuit|印制电路板/i.test(String(x.safeTitle)) && String(x.publishedAt).startsWith('2026-')); const has2026MarketAnalysis = sources.some((x) => /market|市场|周报|weekly|monitor/i.test(String(x.safeTitle)) && String(x.publishedAt).startsWith('2026-')); const classification = classifyCpcaOutcomes({ discoveryStable: !failure && stableRoutes === CPCA_INDUSTRY_ROUTES.length, targetRelevantCandidates: candidates.length || targetMatches, outcomes, has2026PcbAnalysis, has2026MarketAnalysis }); evidence.normalizedSources = sources.filter((x) => x.outcome === 'NORMALIZED_PUBLIC').length; evidence.publicOutcomes = evidence.normalizedSources; evidence.restrictedOutcomes = sources.filter((x) => x.outcome === 'RESTRICTED_ACCESS_GATE').length; evidence.publicationDateAvailability = sources.filter((x) => x.dateAvailable).length; evidence.canonicalHosts = [...new Set(sources.map((x) => x.canonicalHost).filter(Boolean))]; evidence.classification = CPCA_LIVE_CLASSIFICATIONS.includes(classification) ? classification : 'LIVE_SOURCE_INCONCLUSIVE'; if (failure) evidence.failure = failure; await mkdir(dirname(output), { recursive: true }); await writeFile(output, JSON.stringify(evidence, null, 2) + '\n', 'utf8'); console.log(JSON.stringify({ classification: evidence.classification, listPages, candidateFetches, candidates: candidates.length, normalizedSources: evidence.normalizedSources }))
}
if (process.argv[1]?.endsWith('cpca-industry-production-acquisition.ts')) await main()
