import { mkdir, writeFile } from 'node:fs/promises'
import { dirname } from 'node:path'
import { CpcaIndustryResearchPlugin, CPCA_INDUSTRY_ROUTES, validCpcaUrl } from '../../plugins/research-acquisition/cpca-industry.ts'
import { sha256 } from '../../plugins/research-acquisition/hash.ts'

const output = 'tests/validation/evidence/RHL_M3B_CPCA_INDUSTRY_PRODUCTION_ACQUISITION.json'
const target = { name: 'PCB Manufacturing', aliases: ['Printed Circuit Board', '印制电路板'], searchTerms: ['PCB 印制电路板', 'AI服务器 PCB HDI', 'PCB 产业链', 'PCB 行业 产能', 'PCB 市场分析', 'PCB 行业周报', '覆铜板 CCL', '电子信息制造业'], asOf: '2026-09-14T00:00:00.000Z' }
const hash = (value: string | Uint8Array) => sha256(value).slice(0, 16)
const sizeBucket = (size: number) => size < 16 * 1024 ? '0-16KiB' : size < 256 * 1024 ? '16-256KiB' : size < 1024 * 1024 ? '256KiB-1MiB' : '1-8MiB'
const classifications = ['CPCA_SPECIALIST_SOURCE_PROVEN', 'CPCA_SPECIALIST_SOURCE_PARTIAL', 'CPCA_DISCOVERY_EMPTY', 'CPCA_RESTRICTED_ONLY', 'CPCA_ROUTE_OR_PARSER_GAP', 'LIVE_SOURCE_INCONCLUSIVE'] as const

const main = async () => {
  let listPages = 0; let candidateFetches = 0; let stableRoutes = 0; let targetMatches = 0; let restricted = 0; const routeEvidence: unknown[] = []; const sources: unknown[] = []; let candidates: readonly any[] = []; let classification: typeof classifications[number] = 'LIVE_SOURCE_INCONCLUSIVE'; let failure: string | null = null
  const evidence: Record<string, unknown> = { taskId: 'RHL-M3B-3B-IMPL-024-CPCA-SPECIALIST-INDUSTRY-ACQUISITION', baseCommit: '23760a0220dc8af030c43be7a746cab05e9f6a34', generatedAt: new Date().toISOString(), target: { nameHash: hash(target.name), aliasHashes: target.aliases.map(hash), searchTermHashes: target.searchTerms.map(hash), searchTermCount: target.searchTerms.length, asOf: target.asOf }, authorizedRoutes: CPCA_INDUSTRY_ROUTES.map((route) => new URL(route).pathname), requestCounts: { listPages: 0, candidateFetches: 0, retries: 0, modelCalls: 0, gatewaySubmissions: 0, writerCommits: 0, knowledgeMutations: 0 }, routeEvidence, candidates: 0, normalizedSources: 0, publicOutcomes: 0, restrictedOutcomes: 0, publicationDateAvailability: 0, canonicalHosts: [], sources, mutation: { modelCalls: 0, gatewaySubmissions: 0, writerCommits: 0, knowledgeMutations: 0 }, privacy: { rawBodiesIncluded: false, fullDocumentsIncluded: false, cookiesIncluded: false, credentialsIncluded: false, authorizationHeadersIncluded: false, privateAbsolutePathsIncluded: false, reasoningTracesIncluded: false } }
  try {
    const plugin = new CpcaIndustryResearchPlugin({ fetchImpl: async (input, init) => { const requested = new URL(String(input)); const isList = CPCA_INDUSTRY_ROUTES.some((route) => new URL(route).pathname === requested.pathname && !requested.pathname.includes('/current/')); if (isList) listPages++; else candidateFetches++; const response = await fetch(input, init); const final = response.url || String(input); const item: Record<string, unknown> = { requested: { host: requested.hostname, path: requested.pathname }, final: { host: new URL(final).hostname, path: new URL(final).pathname }, http: response.status, finalAuthorized: validCpcaUrl(final) }; if (isList) { try { const bytes = new Uint8Array(await response.clone().arrayBuffer()); const html = new TextDecoder().decode(bytes).slice(0, 2 * 1024 * 1024); const anchors = [...html.matchAll(/<a\b[^>]*href\s*=\s*["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)]; const matches = anchors.filter((anchor) => target.searchTerms.some((term) => html.slice(Math.max(0, (anchor.index ?? 0) - 180), Math.min(html.length, (anchor.index ?? 0) + anchor[0].length + 180)).toLocaleLowerCase().includes(term.toLocaleLowerCase()))); targetMatches += matches.length; routeEvidence.push({ ...item, sizeBucket: sizeBucket(bytes.byteLength), anchorCount: anchors.length, targetMatchCount: matches.length, responseHash: hash(bytes) }); stableRoutes++ } catch { routeEvidence.push({ ...item, sizeBucket: 'unavailable', anchorCount: 0, targetMatchCount: 0, responseHash: null }) } } return response } })
    candidates = await plugin.discover({ industry: target, asOf: target.asOf, limitPerKind: 8 }); evidence.candidates = candidates.length
    for (const candidate of candidates.slice(0, 4)) { try { const normalized = await plugin.normalize(await plugin.fetch(candidate)); const host = new URL(normalized.canonicalUrl!).hostname; const list = sources as unknown[]; list.push({ titleHash: hash(normalized.title), safeTitle: normalized.title.slice(0, 160), canonicalHost: host, publishedAt: candidate.publishedAt ?? null, dateAvailable: Boolean(candidate.publishedAt), contentHash: normalized.contentHash, kind: normalized.candidate.kind, tier: normalized.candidate.tier, restricted: false }); } catch { restricted++; } }
    evidence.publicOutcomes = sources.length; evidence.restrictedOutcomes = restricted; evidence.normalizedSources = sources.length; evidence.publicationDateAvailability = (sources as Array<Record<string, unknown>>).filter((x) => x.dateAvailable).length; evidence.canonicalHosts = [...new Set((sources as Array<Record<string, string>>).map((x) => x.canonicalHost))]
    const analysis = (sources as Array<Record<string, unknown>>).filter((source) => /pcb|printed circuit|印制电路板/i.test(String(source.safeTitle))); const market = (sources as Array<Record<string, unknown>>).filter((source) => /market|市场|周报|weekly|monitor/i.test(String(source.safeTitle))); const has2026 = (items: Array<Record<string, unknown>>) => items.some((x) => String(x.publishedAt ?? '').startsWith('2026-'))
    classification = analysis.length > 0 && market.length > 0 && has2026(analysis) && has2026(market) && sources.length >= 2 ? 'CPCA_SPECIALIST_SOURCE_PROVEN' : sources.length > 0 ? 'CPCA_SPECIALIST_SOURCE_PARTIAL' : restricted > 0 ? 'CPCA_RESTRICTED_ONLY' : stableRoutes === 3 && targetMatches === 0 ? 'CPCA_DISCOVERY_EMPTY' : targetMatches > 0 ? 'CPCA_ROUTE_OR_PARSER_GAP' : 'LIVE_SOURCE_INCONCLUSIVE'
  } catch (error) { failure = error instanceof Error ? error.name.slice(0, 40) : 'live failure'; classification = 'LIVE_SOURCE_INCONCLUSIVE' }
  const counts = evidence.requestCounts as Record<string, number>; counts.listPages = listPages; counts.candidateFetches = candidateFetches; evidence.classification = classifications.includes(classification) ? classification : 'LIVE_SOURCE_INCONCLUSIVE'; if (failure) evidence.failure = failure; await mkdir(dirname(output), { recursive: true }); await writeFile(output, JSON.stringify(evidence, null, 2) + '\n', 'utf8'); console.log(JSON.stringify({ classification: evidence.classification, listPages, candidateFetches, candidates: candidates.length, normalizedSources: sources.length }))
}
if (process.argv[1]?.endsWith('cpca-industry-production-acquisition.ts')) await main()
