import { mkdir, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { ModelRuntime, getAgentDir } from '@earendil-works/pi-coding-agent'
import type { Api, Model } from '@earendil-works/pi-ai'
import { PiReasoningExecutor } from '../../plugins/reasoning/pi/executor.ts'
import { selectProductionReasoningModel } from '../../app/pi/model-selection.ts'
import { FileDailySignalStore } from '../../plugins/daily-intelligence/signal-store.ts'
import { runDailyIntelligence } from '../../workflows/daily-intelligence/workflow.ts'
import type { ResearchAcquisitionPlugin } from '../../plugins/research-acquisition/contracts.ts'
import { sha256 } from '../../plugins/research-acquisition/hash.ts'

const root = resolve('tests/validation/evidence'); await mkdir(root, { recursive: true }); const fixture: ResearchAcquisitionPlugin = { name: 'fixture-public-retained', async discover() { return [{ candidateId: 'daily-pi-fixture', kind: 'official_disclosure', tier: 1, title: 'Public retained disclosure fixture', provider: 'cninfo', publishedAt: '2026-09-08T00:00:00.000Z', metadata: { companySymbol: '600519' } }] }, async fetch(candidate) { const content = 'Public retained fixture: channel quality and premium spirits demand observation.'; return { candidate, retrievedAt: '2026-09-08T01:00:00.000Z', content, contentHash: sha256(content) } }, async normalize(source) { return { candidate: source.candidate, retrievedAt: source.retrievedAt, title: source.candidate.title, content: source.content, contentHash: source.contentHash!, publisher: 'CNINFO fixture', rights: { accessScope: 'public', retentionAllowed: true, aiProcessingAllowed: true, derivativeKnowledgeAllowed: true, redistributionAllowed: false } } } }; let runtime: ModelRuntime | undefined
try { runtime = await ModelRuntime.create({ authPath: join(getAgentDir(), 'auth.json'), modelsPath: join(getAgentDir(), 'models.json'), allowModelNetwork: true, refreshOnCreate: false }); const model = selectProductionReasoningModel(runtime) as Model<Api>; const executor = new PiReasoningExecutor({ modelRuntime: runtime, model, timeoutMs: 900_000, maxOutputChars: 200_000 }); const base = { watchlist: { companies: [{ symbol: '600519', name: '贵州茅台', exchange: 'SSE' }], themes: ['AI'], industries: ['consumer'] }, providers: [fixture], signalStore: new FileDailySignalStore(join(root, 'daily-pi-signals.jsonl')), briefRoot: join(root, 'daily-pi-briefs'), reportRoot: join(root, 'daily-pi-reports'), reasoningExecutor: executor, now: () => '2026-09-08T02:00:00.000Z' }; const runs = []; for (const briefType of ['morning', 'evening'] as const) runs.push(await runDailyIntelligence({ ...base, briefType, workflowRunId: `daily-pi-${briefType}`, tradeDate: '2026-09-08' })); const evidence = { generatedAt: new Date().toISOString(), taskId: 'RHL-PERSONAL-RESEARCH-V1-DAILY-INTELLIGENCE-001', classification: runs.every((run) => run.status === 'completed') ? 'EXECUTED' : 'PRODUCT_OR_ENVIRONMENT_BLOCKED', realPiReasoningExecutor: true, runs: runs.map((run) => ({ status: run.status, briefType: run.brief?.briefType ?? null, sectionCount: run.brief?.sections.length ?? 0, signalCount: run.signals.length, claimCount: run.brief?.quality.claimCount ?? null, reasoningCalls: 1, errors: run.errors })), secretsIncluded: false, rawBodiesIncluded: false }; await writeFile(join(root, 'RHL_DAILY_INTELLIGENCE_V1_PI_E2E.json'), `${JSON.stringify(evidence, null, 2)}\n`, 'utf8'); console.log(JSON.stringify(evidence, null, 2)) } catch (error) { const evidence = { generatedAt: new Date().toISOString(), taskId: 'RHL-PERSONAL-RESEARCH-V1-DAILY-INTELLIGENCE-001', classification: 'ENVIRONMENT_BLOCKED', realPiReasoningExecutor: true, error: error instanceof Error ? error.message : String(error), secretsIncluded: false, rawBodiesIncluded: false }; await writeFile(join(root, 'RHL_DAILY_INTELLIGENCE_V1_PI_E2E.json'), `${JSON.stringify(evidence, null, 2)}\n`, 'utf8'); console.error(JSON.stringify(evidence, null, 2)); process.exitCode = 1 } finally { await Promise.resolve((runtime as unknown as { dispose?: () => void | Promise<void> } | undefined)?.dispose?.()).catch(() => undefined) }
