import { mkdir, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { CninfoOfficialDisclosureClient, OfficialDisclosureResearchPlugin } from '../../plugins/research-acquisition/official.ts'
import { GdeltResearchPlugin } from '../../plugins/research-acquisition/gdelt.ts'
import { RssResearchPlugin } from '../../plugins/research-acquisition/rss.ts'
import { AkshareDataAdapter } from '../../plugins/research-acquisition/akshare.ts'
import { CommunitySignalAcquisition, PublicInstitutionalViewAcquisition } from '../../plugins/daily-intelligence/acquisition.ts'
import { loadSourceCatalog } from '../../plugins/daily-intelligence/config.ts'

const root = resolve('tests/validation/evidence'); await mkdir(root, { recursive: true }); const company = { symbol: '600519', name: '贵州茅台', exchange: 'SSE' }; const catalog = await loadSourceCatalog(); const results: Array<Record<string, unknown>> = []
async function attempt(provider: string, operation: () => Promise<unknown>): Promise<void> { try { const value = await operation(); const usable = Array.isArray(value) ? value.length > 0 : value !== undefined && value !== null && (typeof value !== 'object' || Object.keys(value as object).length > 0); results.push({ provider, attempted: true, status: usable ? 'succeeded' : 'empty', usable }) } catch (error) { const message = error instanceof Error ? error.message : String(error); results.push({ provider, attempted: true, status: /401|403|captcha|login/i.test(message) ? 'blocked' : 'failed', usable: false, diagnostics: message.slice(0, 200) }) } }
const source = (provider: string, urls: readonly string[], tier: 1 | 2 | 3 | 4 | 5) => new (provider.includes('community') ? CommunitySignalAcquisition : PublicInstitutionalViewAcquisition)({ provider, urls, tier })
await attempt('cninfo', () => new OfficialDisclosureResearchPlugin(new CninfoOfficialDisclosureClient()).discover({ company, asOf: '2026-09-08T23:59:59.000Z', limitPerKind: 3 })); await attempt('gdelt', () => new GdeltResearchPlugin().discover({ company, asOf: '2026-09-08T23:59:59.000Z', limitPerKind: 3 })); await attempt('rss', () => new RssResearchPlugin({ feedUrls: ['https://www.gov.cn/rss/zhengce.xml'] }).discover({ company, limitPerKind: 3 })); const akshare = new AkshareDataAdapter(); await attempt('akshare', () => akshare.companyBasic({ symbol: company.symbol })); await attempt('public-institutional', () => source('public-institutional', catalog.filter((item) => item.category === 'institution').slice(0, 2).map((item) => item.evidenceUrl), 2).discover({ company, limitPerKind: 2 })); await attempt('xueqiu-eastmoney-guba-community', () => source('community-public', catalog.filter((item) => item.category === 'community').slice(0, 2).map((item) => item.evidenceUrl), 4).discover({ company, limitPerKind: 2 }))
const evidence = { generatedAt: new Date().toISOString(), taskId: 'RHL-PERSONAL-RESEARCH-V1-DAILY-INTELLIGENCE-001', classification: results.some((item) => item.status === 'failed' || item.status === 'blocked') ? 'EXECUTED_WITH_PROVIDER_LIMITATIONS' : 'EXECUTED', providers: results, sourceCatalogCount: catalog.length, secretsIncluded: false, rawBodiesIncluded: false, caveat: 'Provider probes are live public checks; a successful discovery does not assert legal redistribution or consensus availability.' }; const path = join(root, 'RHL_DAILY_INTELLIGENCE_V1.json'); await writeFile(path, `${JSON.stringify(evidence, null, 2)}\n`, 'utf8'); console.log(JSON.stringify({ ...evidence, evidencePath: path }, null, 2))
