import { mkdir, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { CninfoOfficialDisclosureClient, OfficialDisclosureResearchPlugin } from '../../plugins/research-acquisition/official.ts'
import { GdeltResearchPlugin } from '../../plugins/research-acquisition/gdelt.ts'
import { RssResearchPlugin } from '../../plugins/research-acquisition/rss.ts'
import { AkshareDataAdapter } from '../../plugins/research-acquisition/akshare.ts'
import { CommunitySignalAcquisition, PublicInstitutionalViewAcquisition } from '../../plugins/daily-intelligence/acquisition.ts'
import { AkshareDailyMarketAcquisition } from '../../plugins/daily-intelligence/market.ts'
import { loadSourceCatalog } from '../../plugins/daily-intelligence/config.ts'
import type { ResearchAcquisitionPlugin, ResearchCompanyIdentity } from '../../plugins/research-acquisition/contracts.ts'

const root = resolve('tests/validation/evidence'); await mkdir(root, { recursive: true }); const company: ResearchCompanyIdentity = { symbol: '600519', name: '贵州茅台', exchange: 'SSE' }; const catalog = await loadSourceCatalog();
async function probe(name: string, plugin: ResearchAcquisitionPlugin): Promise<Record<string, unknown>> { const stages = { discover: 'not_attempted', fetch: 'not_attempted', normalize: 'not_attempted' }; let usable = 0; let diagnostics: string[] = []; try { const candidates = await plugin.discover({ company, asOf: '2026-09-08T23:59:59.000Z', limitPerKind: 3 }); stages.discover = candidates.length ? 'succeeded' : 'empty'; for (const candidate of candidates.slice(0, 3)) { try { const fetched = await plugin.fetch(candidate); stages.fetch = fetched.content.trim() ? 'succeeded' : 'empty'; const normalized = await plugin.normalize(fetched); stages.normalize = normalized.content.trim() ? 'succeeded' : 'empty'; if (normalized.content.trim()) usable++ } catch (error) { diagnostics.push(error instanceof Error ? error.message.slice(0, 160) : String(error).slice(0, 160)); stages.fetch = 'failed' } } return { provider: name, stages, usable, status: usable ? 'succeeded' : stages.discover === 'empty' ? 'empty' : 'failed', diagnostics } } catch (error) { const message = error instanceof Error ? error.message.slice(0, 160) : String(error).slice(0, 160); return { provider: name, stages, usable: 0, status: /401|403|429|captcha|login|authentication|blocked/i.test(message) ? 'blocked' : 'failed', diagnostics: [message] } } }
const akshare = new AkshareDataAdapter(); const institution = catalog.find((item) => item.category === 'institution'); const guba = catalog.find((item) => item.platform === 'eastmoney-guba'); const xueqiu = catalog.find((item) => item.platform === 'xueqiu'); const providers: Array<Promise<Record<string, unknown>>> = [probe('cninfo', new OfficialDisclosureResearchPlugin(new CninfoOfficialDisclosureClient())), probe('gdelt', new GdeltResearchPlugin()), probe('rss', new RssResearchPlugin({ feedUrls: ['https://www.gov.cn/rss/zhengce.xml'] })), probe('akshare-market', new AkshareDailyMarketAcquisition(akshare)), ...(institution ? [probe(`institution:${institution.platform}`, new PublicInstitutionalViewAcquisition({ provider: institution.platform, accountRef: `${institution.platform}:${institution.accountId}`, urls: institution.discoveryUrl ? [institution.discoveryUrl] : [institution.evidenceUrl], tier: institution.reliabilityTier, scope: 'broad' }))] : []), ...(guba ? [probe('eastmoney-guba', new CommunitySignalAcquisition({ provider: guba.platform, accountRef: `${guba.platform}:${guba.accountId}`, urls: guba.discoveryUrl ? [guba.discoveryUrl] : [guba.evidenceUrl], tier: guba.reliabilityTier }))] : [])]; let xueqiuResult: Record<string, unknown>; try { if (!xueqiu) throw new Error('metadata_only: xueqiu not in catalog'); new CommunitySignalAcquisition({ provider: 'xueqiu', urls: [xueqiu.evidenceUrl], tier: xueqiu.reliabilityTier }) ; xueqiuResult = { provider: 'xueqiu', status: 'unexpectedly_constructed' } } catch (error) { xueqiuResult = { provider: 'xueqiu', status: 'authentication_required', diagnostics: error instanceof Error ? error.message : String(error) } }
const results = [...await Promise.all(providers), xueqiuResult]; const evidence = { generatedAt: new Date().toISOString(), taskId: 'RHL-PERSONAL-RESEARCH-V1-DAILY-INTELLIGENCE-001-FIX-001', classification: 'EXECUTED_WITH_PROVIDER_LIMITATIONS', sourceCatalogCount: catalog.length, activeSourceCount: catalog.filter((item) => item.operationalStatus === 'active').length, providers: results, secretsIncluded: false, rawBodiesIncluded: false }; await writeFile(join(root, 'RHL_DAILY_INTELLIGENCE_V1_FIX_001.json'), `${JSON.stringify(evidence, null, 2)}\n`, 'utf8'); await writeFile(join(root, 'RHL_DAILY_INTELLIGENCE_V1_FIX_001_SUMMARY.md'), `# Daily Intelligence FIX-001 Evidence\n\n- Catalog entries: ${catalog.length}\n- Active operational entries: ${catalog.filter((item) => item.operationalStatus === 'active').length}\n- Every provider records discover, fetch, normalize, and usable status.\n- Xueqiu is recorded as authentication_required when no public endpoint is configured.\n- No secrets or raw provider bodies are included.\n`, 'utf8'); console.log(JSON.stringify(evidence, null, 2))
