import assert from 'node:assert/strict'
import test from 'node:test'
import { approvedCandidate, classifyInterrupted, classifyReadySmoke, classifySetup, privacySafe, runControlled, sanitizeTelemetry } from './document-parser-controlled-setup-miit-pdf-smoke-after-pip-hardening.ts'

const ready = { status: 'READY', pythonReady: true, dependencyReady: true, artifactsReady: true, bridgeReady: true }
const notReady = { status: 'MANAGED_PYTHON_MISSING', pythonReady: false, dependencyReady: false, artifactsReady: false, bridgeReady: false }
const deps = (pre: any, post: any, setupResult: any = { status: 'INCONCLUSIVE', reason: 'PIP_INSTALL_FAILED' }, fetch = async () => { throw new Error('fetch must not run') }, normalize = async () => ({ content: '印制电路板 企业 专用设备', contentHash: 'a'.repeat(64), publisher: 'Ministry of Industry and Information Technology', rights: { accessScope: 'public' } })) => { let preflights = 0; let setupInvocations = 0; let fetches = 0; return { get counts() { return { preflights, setupInvocations, fetches } }, runner: () => runControlled({ root: 'fixture', preflight: async () => preflights++ === 0 ? pre : post, setup: async () => { setupInvocations++; return setupResult }, readTelemetry: async () => null, state: async () => ({}), fetch: async (c) => { fetches++; return fetch(c) }, normalize }) } }

test('timeout and failure reasons classify deterministically', () => { for (const reason of ['PIP_INSTALL_TIMEOUT', 'MODEL_DOWNLOAD_TIMEOUT', 'BRIDGE_SMOKE_TIMEOUT', 'FINAL_VERIFICATION_TIMEOUT']) assert.equal(classifySetup('INCONCLUSIVE', reason), 'DOCUMENT_PARSER_SETUP_TIMED_OUT'); for (const reason of ['PIP_INSTALL_FAILED', 'MODEL_DOWNLOAD_FAILED', 'BRIDGE_SMOKE_FAILED', 'PROMOTION_FAILED']) assert.equal(classifySetup('INCONCLUSIVE', reason), 'DOCUMENT_PARSER_SETUP_FAILED') })
test('all accepted timeout stages are timeout classifications', () => { for (const reason of ['BASE_PYTHON_PROBE_TIMEOUT', 'VENV_CREATION_TIMEOUT', 'DEPENDENCY_VERIFY_TIMEOUT']) assert.equal(classifySetup('INCONCLUSIVE', reason), 'DOCUMENT_PARSER_SETUP_TIMED_OUT') })
test('READY preflight skips setup and performs exactly one approved MIIT fetch', async () => { const c = approvedCandidate(); assert.equal(c.provider, 'miit'); assert.equal(c.tier, 1); assert.equal(c.kind, 'official_disclosure'); assert.equal(new URL(c.url).hostname, 'wap.miit.gov.cn'); const d = deps(ready, ready, { status: 'READY' }, async () => ({ rawBytes: new Uint8Array([1]), mediaType: 'application/pdf', contentHash: 'b'.repeat(64) })); const e = await d.runner(); assert.equal(d.counts.setupInvocations, 0); assert.equal(d.counts.fetches, 1); assert.equal(e.finalClassification, 'DOCUMENT_PARSER_MIIT_PDF_READY') })
test('non-READY preflight invokes setup no more than once', async () => { const d = deps(notReady, notReady); const e = await d.runner(); assert.equal(d.counts.setupInvocations, 1); assert.equal(e.setupInvocationCount, 1); assert.equal(e.finalClassification, 'DOCUMENT_PARSER_SETUP_FAILED') })
test('non-READY post-setup state prevents MIIT fetch', async () => { const d = deps(notReady, notReady); const e = await d.runner(); assert.equal(d.counts.fetches, 0); assert.equal(e.fetch.attempted, false) })
test('READY result contradicted by postflight is a setup defect', async () => { const d = deps(notReady, notReady, { status: 'READY' }); const e = await d.runner(); assert.equal(e.finalClassification, 'DOCUMENT_PARSER_SETUP_DEFECT') })
test('external interruption reports real active telemetry stage', () => { assert.deepEqual(classifyInterrupted({ status: 'RUNNING', stage: 'PIP_INSTALL' }), { classification: 'DOCUMENT_PARSER_SMOKE_INCONCLUSIVE', activeStage: 'PIP_INSTALL' }) })
test('empty or non-relevant normalization is a defect, fetch failure is external failure', () => { assert.equal(classifyReadySmoke({ postReady: true, fetchSucceeded: true, pdfMedia: true, normalizedCharacterCount: 0, pcbIdentity: false, scopeBoundary: false }), 'MIIT_PDF_NORMALIZATION_DEFECT'); assert.equal(classifyReadySmoke({ postReady: true, fetchSucceeded: true, pdfMedia: true, normalizedCharacterCount: 100, pcbIdentity: true, scopeBoundary: false }), 'MIIT_PDF_NORMALIZATION_DEFECT'); assert.equal(classifyReadySmoke({ postReady: true, fetchSucceeded: false, pdfMedia: true, normalizedCharacterCount: 0, pcbIdentity: false, scopeBoundary: false, fetchExternalFailure: true }), 'MIIT_PDF_FETCH_EXTERNAL_FAILURE') })
test('telemetry and privacy fields are bounded', () => { assert.deepEqual(sanitizeTelemetry({ schemaVersion: 1, stage: 'PIP_INSTALL', status: 'RUNNING', lastCompletedStage: 'VENV_CREATE', reason: 'PIP_INSTALL_TIMEOUT', elapsedBucket: 'GTE_120S', rawOutput: 'secret' }), { schemaVersion: 1, stage: 'PIP_INSTALL', status: 'RUNNING', lastCompletedStage: 'VENV_CREATE', reason: 'PIP_INSTALL_TIMEOUT', elapsedBucket: 'GTE_120S' }); assert.equal(privacySafe({ path: 'C:\\Users\\x\\venv' }), false); assert.equal(privacySafe({ output: 'pip install docling' }), false); assert.equal(privacySafe({ normalizedText: 'full text' }), false); assert.equal(privacySafe({ byteCount: 12, contentHash: 'a'.repeat(64) }), true) })
