import { mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { tmpdir } from 'node:os'
import { ModelRuntime, getAgentDir } from '@earendil-works/pi-coding-agent'
import type { Api, Model } from '@earendil-works/pi-ai'
import { PiReasoningExecutor } from '../../plugins/reasoning/pi/executor.ts'
import { selectProductionReasoningModel } from '../../app/pi/model-selection.ts'
import { createFreshKnowledgeBaseV04, readCanonicalV04Assets } from '../../knowledge/storage/index.ts'
import { KnowledgeBaseRegistry } from '../../knowledge/registry/registry.ts'
import { KnowledgeProductionGateway } from '../../knowledge/production/gateway.ts'
import { runEarningsReview } from '../../workflows/earnings-review/workflow.ts'
import type { NormalizedResearchSource, ResearchAcquisitionPlugin, ResearchSourceCandidate } from '../../plugins/research-acquisition/contracts.ts'
import type { AkshareDataClient } from '../../plugins/research-acquisition/akshare.ts'
import { sha256 } from '../../plugins/research-acquisition/hash.ts'

const repoRoot = resolve(import.meta.dirname, '../..')
const evidencePath = resolve(repoRoot, 'tests/validation/evidence/RHL_M3A_EARNINGS_REVIEW_V1_PI_E2E.json')
const now = () => '2026-09-08T23:59:59.000Z'
const rights = { accessScope: 'public' as const, retentionAllowed: true, aiProcessingAllowed: true, derivativeKnowledgeAllowed: true, redistributionAllowed: false }
const candidate: ResearchSourceCandidate = { candidateId: 'pi-earnings-official', kind: 'official_disclosure', tier: 1, title: '2026年半年度报告', provider: 'cninfo', publishedAt: '2026-08-30T00:00:00.000Z', metadata: { companySymbol: '600519' } }
const officialPlugin: ResearchAcquisitionPlugin = { name: 'fixture-official-disclosure', discover: async () => [candidate], fetch: async (value) => { const content = '2026年半年度报告：营业收入同比增长，经营活动现金流保持为正，管理层继续关注渠道质量。'; return { candidate: value, retrievedAt: now(), content, contentHash: sha256(content), rawBytes: new TextEncoder().encode(`PDF:${content}`), mediaType: 'application/pdf' } }, normalize: async (value) => ({ candidate: value.candidate, retrievedAt: value.retrievedAt, title: value.candidate.title, content: value.content, contentHash: value.contentHash!, rawBytes: value.rawBytes, publisher: 'CNINFO fixture', rights }) }
const akshare: AkshareDataClient = { companyBasic: async () => { throw new Error('not used') }, historicalMarketData: async () => { throw new Error('not used') }, financialData: async () => [{ 报告期: '2025-06-30', 营业收入: 90, 净利润: 9, 销售毛利率: 40, 经营活动产生的现金流量净额: 8, 基本每股收益: 0.8 }, { 报告期: '2026-06-30', 营业收入: 120, 净利润: 15, 销售毛利率: 45, 经营活动产生的现金流量净额: 20, 基本每股收益: 1.2 }] }

let modelRuntime: ModelRuntime | undefined
try {
  const root = await mkdtemp(join(tmpdir(), 'rhl-m3a-earnings-pi-')); const kbRoot = join(root, 'kb'); const reportRoot = join(root, 'reports'); await mkdir(reportRoot, { recursive: true }); await createFreshKnowledgeBaseV04(kbRoot, { knowledgeBaseId: 'kb-m3a-earnings-pi', now: now() })
  const registry = new KnowledgeBaseRegistry(); let handle = await registry.mount(kbRoot); const seedContent = 'Seeded company coverage with existing thesis and assumption.'; const seed: NormalizedResearchSource = { candidate: { candidateId: 'pi-seed-source', kind: 'official_disclosure', tier: 1, title: 'Seed coverage', provider: 'cninfo', publishedAt: '2026-01-01T00:00:00.000Z', metadata: { companySymbol: '600519' } }, retrievedAt: now(), title: 'Seed coverage', content: seedContent, contentHash: sha256(seedContent), publisher: 'CNINFO fixture', rights }
  const seeded = await new KnowledgeProductionGateway(registry).submit({ handle, producerType: 'fixture_seed', producerRunId: 'pi-earnings-seed', schemaProfile: { schemaVersion: '0.4', storageFormatVersion: '1', requiresRawProvenance: true }, entity: { localKey: 'company', entityType: 'company', name: '贵州茅台', aliases: ['600519'], semanticFields: { ticker: '600519', exchange: 'SH' } }, proposals: [{ proposalId: 'seed-assumption', kind: 'claim', claimType: 'assumption', subjectKey: 'company', statement: 'Premium spirits demand remains resilient.', sourceCandidateIds: ['pi-seed-source'] }, { proposalId: 'seed-thesis', kind: 'claim', claimType: 'thesis', subjectKey: 'company', statement: 'The company retains long-term pricing power.', sourceCandidateIds: ['pi-seed-source'] }], evidenceBindings: [{ localSourceId: 'pi-seed-source', source: seed }], asOf: now(), now })
  if (seeded.status !== 'committed') throw new Error(`Unable to seed fixture Knowledge Base: ${seeded.errors.join('; ')}`)
  handle = await registry.mount(kbRoot); modelRuntime = await ModelRuntime.create({ authPath: join(getAgentDir(), 'auth.json'), modelsPath: join(getAgentDir(), 'models.json'), allowModelNetwork: true, refreshOnCreate: false }); const model = selectProductionReasoningModel(modelRuntime) as Model<Api>; const executor = new PiReasoningExecutor({ modelRuntime, model, timeoutMs: 900_000, maxOutputChars: 400_000 }); const result = await runEarningsReview({ workflowRunId: 'pi-earnings-review-001', handle, company: { symbol: '600519', name: '贵州茅台', exchange: 'SSE' }, fiscalYear: 2026, period: 'H1', asOf: now(), reportRoot, acquisitionPlugins: [officialPlugin], akshare, reasoningExecutor: executor, now })
  const assets = await readCanonicalV04Assets(kbRoot); const report = result.report ? JSON.parse(await readFile(join(reportRoot, `${result.report.reportId}.md.json`), 'utf8')) as { reportType?: string; sections?: unknown[]; sourceRefs?: unknown[]; claimRefs?: unknown[] } : undefined; const gate = { earnings_review_synthesisCalled: result.telemetry.reasoning.called, structuredOutputValidated: result.telemetry.reasoning.validated, reasoningApplied: result.telemetry.reasoning.applied, fallbackUsed: result.telemetry.reasoning.fallbackUsed, modelDerivedSectionCount: result.sections?.filter((section) => section.markdown.length > 0 && section.sourceCandidateIds.length > 0).length ?? 0, validAssessmentCount: result.telemetry.validAssessmentCount, durableAssessmentCount: result.telemetry.durableAssessmentCount, acceptedProposalCount: result.telemetry.acceptedProposalCount, reportType: report?.reportType ?? null, workflowTerminalStatus: result.status }
  const evidence = { classification: Object.values(gate).every((value) => value !== false) && gate.modelDerivedSectionCount >= 1 && gate.validAssessmentCount >= 1 && gate.durableAssessmentCount >= 1 && gate.acceptedProposalCount >= 1 && gate.reportType === 'earnings_review' && gate.workflowTerminalStatus === 'completed' ? 'EXECUTED' : 'REAL_MODEL_CONTRACT_BLOCKED', host: executor.runtimeMetadata(), operation: 'earnings_review_synthesis', realPiReasoningExecutor: true, gate, run: { status: result.status, reportId: result.report?.reportId ?? null, sectionCount: report?.sections?.length ?? 0, sourceRefs: report?.sourceRefs?.length ?? 0, claimRefs: report?.claimRefs?.length ?? 0, errors: result.errors }, canonicalCounts: { entities: assets.objects.filter((item) => item.kind === 'entity').length, sources: assets.objects.filter((item) => item.kind === 'source').length, claims: assets.objects.filter((item) => item.kind === 'claim').length }, secretsIncluded: false, rawBodiesIncluded: false }
  await writeFile(evidencePath, `${JSON.stringify(evidence, null, 2)}\n`, 'utf8'); console.log(JSON.stringify(evidence, null, 2)); if (evidence.classification !== 'EXECUTED') process.exitCode = 1
} catch (error) { const evidence = { classification: 'REAL_MODEL_CONTRACT_BLOCKED', operation: 'earnings_review_synthesis', realPiReasoningExecutor: true, error: error instanceof Error ? error.message : String(error), secretsIncluded: false, rawBodiesIncluded: false }; await writeFile(evidencePath, `${JSON.stringify(evidence, null, 2)}\n`, 'utf8'); console.error(JSON.stringify(evidence, null, 2)); process.exitCode = 1
} finally { await Promise.resolve((modelRuntime as unknown as { dispose?: () => void | Promise<void> } | undefined)?.dispose?.()).catch(() => undefined) }
