import { mkdir, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { AkshareDataAdapter } from '../../plugins/research-acquisition/akshare.ts'
import { CninfoOfficialDisclosureClient, OfficialDisclosureResearchPlugin } from '../../plugins/research-acquisition/official.ts'
import { earningsPeriodSpec, hasUsableExactPeriod, normalizeAkshareFinancialData } from '../../skills/earnings-review/financials.ts'
import { selectOfficialEarningsFilings } from '../../workflows/earnings-review/workflow.ts'
import type { ResearchSourceCandidate } from '../../plugins/research-acquisition/contracts.ts'

const evidencePath = resolve('tests/validation/evidence/RHL_M3A_EARNINGS_REVIEW_V1_PROVIDER_SMOKE.json')
const asOf = '2026-09-08T23:59:59.000Z'; const requested = earningsPeriodSpec(2025, 'FY'); const company = { symbol: '600519', name: '贵州茅台', exchange: 'SSE' }
const official = new OfficialDisclosureResearchPlugin(new CninfoOfficialDisclosureClient({ pageSize: 100 })); const akshare = new AkshareDataAdapter()
const result: { readonly provider: string; providerAttempted: boolean; providerSucceeded: boolean; providerEmpty: boolean; providerFailed: boolean; periodEvidenceFound: boolean; usableForEarningsReview: boolean; error?: string }[] = []
try {
  let candidates: ResearchSourceCandidate[] = []; try { candidates = [...await official.discover({ company, asOf, limitPerKind: 100 })] } catch (error) { result.push({ provider: 'CNINFO', providerAttempted: true, providerSucceeded: false, providerEmpty: false, providerFailed: true, periodEvidenceFound: false, usableForEarningsReview: false, error: error instanceof Error ? error.message : String(error) }) }
  if (result.every((item) => item.provider !== 'CNINFO')) { const selection = selectOfficialEarningsFilings(candidates, requested, asOf); let usable = false; for (const candidate of selection.candidates) { try { const fetched = await official.fetch(candidate); usable = fetched.content.trim().length > 0; if (usable) break } catch { /* record at provider level */ } } result.push({ provider: 'CNINFO', providerAttempted: true, providerSucceeded: true, providerEmpty: candidates.length === 0, providerFailed: false, periodEvidenceFound: selection.candidates.length > 0, usableForEarningsReview: usable }) }
} catch (error) { result.push({ provider: 'CNINFO', providerAttempted: true, providerSucceeded: false, providerEmpty: false, providerFailed: true, periodEvidenceFound: false, usableForEarningsReview: false, error: error instanceof Error ? error.message : String(error) }) }
try { const raw = await akshare.financialData({ symbol: company.symbol }); const normalized = normalizeAkshareFinancialData(raw, requested, `smoke-${requested.key}`); result.push({ provider: 'AKShare', providerAttempted: true, providerSucceeded: true, providerEmpty: !Array.isArray(raw) || raw.length === 0, providerFailed: false, periodEvidenceFound: normalized.current !== undefined, usableForEarningsReview: hasUsableExactPeriod(normalized), ...(normalized.diagnostics.length ? { error: normalized.diagnostics.join('; ') } : {}) }) } catch (error) { result.push({ provider: 'AKShare', providerAttempted: true, providerSucceeded: false, providerEmpty: false, providerFailed: true, periodEvidenceFound: false, usableForEarningsReview: false, error: error instanceof Error ? error.message : String(error) }) }
const evidence = { generatedAt: new Date().toISOString(), taskId: 'RHL-PERSONAL-RESEARCH-V1-M3A-EARNINGS-REVIEW-001', company, requestedPeriod: requested, asOf, providers: result, secretsIncluded: false, rawBodiesIncluded: false }; await mkdir(resolve('tests/validation/evidence'), { recursive: true }); await writeFile(evidencePath, `${JSON.stringify(evidence, null, 2)}\n`, 'utf8'); console.log(JSON.stringify(evidence, null, 2))
