import assert from 'node:assert/strict'
import test from 'node:test'
import { evaluateIndustryPiGate, type IndustryPiGateInput } from './industry-research-pi-e2e-gate.ts'

const modules = ['industry_definition', 'market_size_growth', 'supply_demand_analysis', 'industry_chain_analysis', 'competitive_landscape', 'technology_evolution', 'company_mapping', 'risk_analysis'].map((module) => ({ module, status: 'supported' }))
function gate(overrides: Partial<IndustryPiGateInput> = {}): IndustryPiGateInput {
  return { executed: true, realPiReasoningExecutor: true, runtimeProvider: 'pi-coding-agent', operations: ['industry_research_design', 'industry_module_analysis', 'industry_cross_module_synthesis'], operationCounts: { industry_research_design: 1, industry_module_analysis: 8, industry_cross_module_synthesis: 1 }, status: 'completed', targetKind: 'industry', modules, industryDefinitionAvailable: true, gatewaySubmitCount: 1, firstRunRevisionDelta: 1, durableClaimCount: 2, chainRelation: true, companyExposure: true, industryRoot: true, productOrTechnology: true, company: true, sourceRawProvenance: true, unsupportedNumericObservationCount: 0, semanticTypingIntact: true, report: { persisted: true, reportType: 'industry_research', sectionCount: 16, hasResearchGaps: true }, graph: { profile: 'industry_context', canonicalRefs: true, root: true, productOrTechnology: true, company: true, requiredEdge: true }, replay: { outcome: 'no_changes', rootIdStable: true, duplicateEntities: false, duplicateRelations: false, duplicateClaims: false, duplicateSources: false, duplicateRaw: false, revisionDelta: 0, graphStable: true }, privacy: { serializedEvidenceSafe: true, sentinelAbsent: true, pathsRedacted: true, secretsAbsent: true }, ...overrides }
}

test('M3B-3B gate accepts the complete bounded real-Pi contract', () => assert.equal(evaluateIndustryPiGate(gate()).classification, 'EXECUTED / PASS GATE'))
test('M3B-3B gate classifies not-executed setup as blocked', () => assert.equal(evaluateIndustryPiGate(gate({ executed: false })).classification, 'NOT_EXECUTED / BLOCKED'))
for (const [name, change] of [
  ['fake/non-Pi executor', { realPiReasoningExecutor: false }], ['wrong target kind', { targetKind: 'theme' }], ['missing module', { modules: modules.slice(1) }], ['Industry Definition unavailable', { industryDefinitionAvailable: false }], ['unsupported numeric', { unsupportedNumericObservationCount: 1 }], ['missing chain Relation', { chainRelation: false }], ['missing Company exposure', { companyExposure: false }], ['missing durable Claim', { durableClaimCount: 0 }], ['gateway count not one', { gatewaySubmitCount: 2 }], ['revision delta not one', { firstRunRevisionDelta: 2 }], ['missing Source/Raw', { sourceRawProvenance: false }], ['wrong report', { report: { persisted: true, reportType: 'theme', sectionCount: 15, hasResearchGaps: false } }], ['graph failure', { graph: { profile: null, canonicalRefs: false, root: false, productOrTechnology: false, company: false, requiredEdge: false } }], ['replay duplication/revision advance', { replay: { outcome: 'committed', rootIdStable: false, duplicateEntities: true, duplicateRelations: false, duplicateClaims: false, duplicateSources: false, duplicateRaw: false, revisionDelta: 1, graphStable: false } }], ['privacy leakage', { privacy: { serializedEvidenceSafe: false, sentinelAbsent: false, pathsRedacted: false, secretsAbsent: false } }],
] as const) test(`M3B-3B gate rejects ${name}`, () => assert.equal(evaluateIndustryPiGate(gate(change)).pass, false))
