import test from 'node:test'
import assert from 'node:assert/strict'
import { classifyRepairBoundViolation, classifyTerminalBoundary, createIndustryReasoningInstrumentation, TEST_036_SECTIONS } from './industry-runtime-terminal-boundary-diagnosis.ts'

test('authoritative errors take precedence over generic failed status', () => assert.equal(classifyTerminalBoundary({ preflightOk: true, workflowStatus: 'failed', errors: ['proposal_invalid: bounded candidate rejected'], diagnostics: ['reasoning-runtime-error'] }), 'RUNTIME_PROJECT_DEFECT'))
test('eight different first-pass modules are not repairs', async () => { const calls: any[] = []; const real = { capabilities: () => ({}), execute: async (r: any) => ({ operation: r.operation, output: {} }) }; const x = createIndustryReasoningInstrumentation(real); for (const module of ['industry_definition','market_size_growth','supply_demand_analysis','industry_chain_analysis','competitive_landscape','technology_evolution','company_mapping','risk_analysis']) await x.execute({ operation: 'industry_module_analysis', input: { module } }); calls.push(...x.calls); assert.equal(calls.filter((c) => c.boundedRepairInference).length, 0); assert.deepEqual(calls.map((c) => c.perIdentityOrdinal), [1,1,1,1,1,1,1,1]) })
test('second call for one module is that module repair only', async () => { const x = createIndustryReasoningInstrumentation({ capabilities: () => ({}), execute: async (r: any) => ({ operation: r.operation, output: {} }) }); await x.execute({ operation: 'industry_module_analysis', input: { module: 'company_mapping' } }); await x.execute({ operation: 'industry_module_analysis', input: { module: 'company_mapping' } }); await x.execute({ operation: 'industry_module_analysis', input: { module: 'risk_analysis' } }); assert.deepEqual(x.calls.map((c) => [c.module, c.perIdentityOrdinal, c.boundedRepairInference]), [['company_mapping',1,false],['company_mapping',2,true],['risk_analysis',1,false]]) })
test('second synthesis call is exactly one bounded synthesis repair', async () => { const x = createIndustryReasoningInstrumentation({ capabilities: () => ({}), execute: async (r: any) => ({ operation: r.operation, output: {} }) }); await x.execute({ operation: 'industry_cross_module_synthesis', input: {} }); await x.execute({ operation: 'industry_cross_module_synthesis', input: {} }); assert.deepEqual(x.calls.map((c) => c.boundedRepairInference), [false, true]) })
test('repair counts above two are project-controlled violations', () => { assert.equal(classifyRepairBoundViolation({ modules: { company_mapping: 3 } }), true); assert.equal(classifyRepairBoundViolation({ synthesis: 3 }), true); assert.equal(classifyRepairBoundViolation({ design: 3 }), true); assert.equal(classifyRepairBoundViolation({ modules: { company_mapping: 2 }, synthesis: 2, design: 2 }), false) })
test('repository contradiction is defect but second model-invalid candidate is external', () => { assert.equal(classifyTerminalBoundary({ preflightOk: true, workflowStatus: 'failed', errors: ['second model candidate remained semantically invalid after bounded repair'] }), 'RUNTIME_EXTERNAL_INCONCLUSIVE'); assert.equal(classifyTerminalBoundary({ preflightOk: true, workflowStatus: 'failed', errors: ['V04_STRUCTURED_VALUE accepted upstream but rejected during canonical conversion'] }), 'RUNTIME_PROJECT_DEFECT') })
test('healthy lifecycle requires Gateway and all frozen report sections', () => assert.equal(classifyTerminalBoundary({ preflightOk: true, workflowStatus: 'completed', errors: [], gatewaySubmitCount: 1, revisionDelta: 1, reportType: 'industry_research', sectionCount: 16, sectionTitles: TEST_036_SECTIONS }), 'RUNTIME_PATH_HEALTHY'))
