// @ts-nocheck
import { mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { tmpdir } from 'node:os'
import { ModelRuntime, getAgentDir } from '@earendil-works/pi-coding-agent'
import { PiReasoningExecutor } from '../../plugins/reasoning/pi/executor.ts'
import { createIndustryProductionReasoningExecutor, selectProductionReasoningModel } from '../../app/pi/model-selection.ts'
import { createResearchHubApplicationRuntime } from '../../app/runtime/application-runtime.ts'
import { createFreshKnowledgeBaseV04, readCanonicalV04Assets } from '../../knowledge/storage/index.ts'
import { KnowledgeGraphService } from '../../app/services/knowledge-graph-service.ts'
import { sha256 } from '../../plugins/research-acquisition/hash.ts'
import { evaluateIndustryPiGate, type IndustryPiGateInput } from './industry-research-pi-e2e-gate.ts'
import type { ReasoningRequest, ReasoningExecutor } from '../../plugins/reasoning/contracts.ts'

const root = resolve(import.meta.dirname, '../..')
const evidencePath = join(root, 'tests/validation/evidence/RHL_M3B_INDUSTRY_PRODUCTION_REAL_PI_E2E.json')
const taskId = 'RHL-M3B-3B-TEST-008-PRODUCTION-REAL-PI-E2E-ACCEPTANCE'
const baseCommit = '302ca31f0bcefae0e383a1f36daabab755cf4400'
const asOf = '2026-09-12T00:00:00.000Z'
const sentinel = `privacy-sentinel-${sha256(`${Date.now()}-${Math.random()}`).slice(0, 16)}`
const safe = (x: unknown) => String(x instanceof Error ? x.message : x).replace(/[A-Za-z]:\\[^\s;]*/g, '<path>').replace(/(authorization|cookie|api[-_]?key|token|secret)\s*[:=]\s*[^,;\s]+/gi, '$1=<redacted>').slice(0, 300)
const counts = (assets: Awaited<ReturnType<typeof readCanonicalV04Assets>>) => Object.fromEntries(['entity','relation','claim','source'].map(k => [k, assets.objects.filter(x => x.kind === k).length]))
const ids = (assets: Awaited<ReturnType<typeof readCanonicalV04Assets>>) => Object.fromEntries(['entity','relation','claim','source'].map(k => [k, assets.objects.filter(x => x.kind === k).map(x => x.value.id).sort()])) as Record<string,string[]>
const hash = (x: unknown) => sha256(JSON.stringify(x)).slice(0, 16)

function projection(graph: any) { return { nodes: graph?.nodes?.map((x: any) => ({ ref: x.ref, type: x.entityType, root: x.isRoot })) ?? [], edges: graph?.edges?.map((x: any) => ({ ref: x.ref, type: x.relationType, from: x.sourceRef, to: x.targetRef })) ?? [] } }
function numericAudit(result: any): number { const text = JSON.stringify(result); const sourceText = (result.acquisitionWaves ?? []).map((x: any) => JSON.stringify(x)).join(' '); let n = 0; for (const token of text.match(/(?<![A-Za-z])\d+(?:\.\d+)?%?(?![A-Za-z])/g) ?? []) if (!/^\d{4}[-/]\d{1,2}/.test(token) && !sourceText.includes(token)) n++; return n }

async function main() {
  let started = false; let runtime: any; let temp = ''; let first: any; let replay: any; let firstAssets: any; let replayAssets: any; let firstGraph: any; let replayGraph: any; let metadata: any = null
  const operations: string[] = []; const operationCounts: Record<string, number> = {}; const captured: Array<{ request: ReasoningRequest; output: unknown }> = []; let modelCalls = 0; let liveNetworkCalls = 0
  try {
    temp = await mkdtemp(join(tmpdir(), 'rhl-m3b3-test-008-')); const kb = join(temp, 'kb'); const reports = join(temp, 'reports'); await mkdir(reports, { recursive: true }); await createFreshKnowledgeBaseV04(kb, { knowledgeBaseId: 'kb-m3b3-test-008' })
    const mr = await ModelRuntime.create({ authPath: join(getAgentDir(), 'auth.json'), modelsPath: join(getAgentDir(), 'models.json'), allowModelNetwork: true, refreshOnCreate: false })
    const primary = new PiReasoningExecutor({ modelRuntime: mr, model: selectProductionReasoningModel(mr) })
    const factory = async (): Promise<ReasoningExecutor> => {
      const delegate = await createIndustryProductionReasoningExecutor({ capabilities: primary.capabilities(), timeoutMs: 900_000, maxOutputChars: 400_000, tempRoot: temp })
      metadata = delegate.runtimeMetadata(); const real = delegate as ReasoningExecutor
      return { capabilities: () => real.capabilities(), execute: async (request) => { started = true; modelCalls++; operations.push(request.operation); operationCounts[request.operation] = (operationCounts[request.operation] ?? 0) + 1; const result = await real.execute(request); captured.push({ request, output: result.output }); return result } }
    }
    runtime = await createResearchHubApplicationRuntime({ cwd: temp, agentDir: getAgentDir(), workspaceRoot: join(temp, 'workspace'), mountedKnowledgeBaseRoot: kb, modelRuntime: mr, reasoningExecutor: primary, industryReasoningExecutorFactory: factory })
    const service = runtime.researchService; if (!service) throw new Error('ResearchService was not constructed by Application Runtime')
    const before = await readCanonicalV04Assets(kb); const beforeRevision = JSON.parse(await readFile(join(kb, 'manifest.yaml'), 'utf8')).revision
    started = true; first = await service.startIndustryResearch({ workflowRunId: 'rhl-m3b3-test-008-first', name: 'PCB Manufacturing', aliases: ['Printed Circuit Board'], searchTerms: ['PCB 印制电路板', 'AI服务器 PCB HDI', '深南电路 PCB', '沪电股份 PCB', '胜宏科技 PCB', '生益科技 PCB CCL', 'PCB 产业链', 'PCB 行业 产能'], asOf, maxSources: 24, maxEvidencePerModule: 2 }).completion
    firstAssets = await readCanonicalV04Assets(kb); const afterRevision = JSON.parse(await readFile(join(kb, 'manifest.yaml'), 'utf8')).revision
    const design = captured.find(x => x.request.operation === 'industry_research_design')?.output as any
    const modules = captured.filter(x => x.request.operation === 'industry_module_analysis').map(x => ({ ...((x.output as any) ?? {}), module: (x.request.input as any)?.module, status: (x.output as any)?.status ?? 'unavailable' }))
    const objects = firstAssets.objects.map(x => x.value as any); const industry = objects.find(x => x.type === 'industry'); const product = objects.find(x => x.type === 'product' || x.type === 'technology'); const company = objects.find(x => x.type === 'company'); const relation = objects.find(x => x.id?.startsWith('relation:') && ['upstream_of','depends_on','belongs_to_industry','applied_in','business_exposure'].includes(x.type)); const exposure = objects.find(x => x.type === 'business_exposure')
    firstGraph = industry ? await new KnowledgeGraphService(kb).getGraphProjection({ rootRef: industry.id, depth: 2, maxNodes: 30, maxEdges: 60 }) : null
    const replayExecutor: ReasoningExecutor = { capabilities: () => ({ maxContextTokens: 100000, maxOutputTokens: 100000, structuredOutputSupport: true, maxConcurrency: 8 }), execute: async request => { if (request.operation === 'industry_research_design') { const x = captured.find(y => y.request.operation === request.operation); if (x) return { operation: request.operation, output: x.output } } const x = captured.filter(y => y.request.operation === request.operation)[(request.input as any)?.module ? captured.filter(y => y.request.operation === request.operation).findIndex(y => (y.request.input as any)?.module === (request.input as any)?.module) : 0]; if (x) return { operation: request.operation, output: x.output }; throw new Error(`replay unexpected operation ${request.operation}`) } }
    const replayService = new (service.constructor as any)({ mountedKnowledgeBaseRoot: kb, reportRoot: reports, acquisitionPlugins: [], workflowService: new (runtime.workflowService.constructor)(), reasoningExecutor: replayExecutor, industryReasoningExecutorFactory: async () => replayExecutor })
    replay = await replayService.startIndustryResearch({ workflowRunId: 'rhl-m3b3-test-008-replay', name: 'PCB Manufacturing', aliases: ['Printed Circuit Board'], canonicalRef: industry?.id, searchTerms: ['PCB 印制电路板', 'AI服务器 PCB HDI'], asOf, maxSources: 24, maxEvidencePerModule: 2 }).completion
    replayAssets = await readCanonicalV04Assets(kb); replayGraph = industry ? await new KnowledgeGraphService(kb).getGraphProjection({ rootRef: industry.id, depth: 2, maxNodes: 30, maxEdges: 60 }) : null
    const report = first.reportPath ? JSON.parse(await readFile(join(reports, first.reportPath + '.json'), 'utf8')) : null; const replayIds = ids(replayAssets); const beforeIds = ids(firstAssets); const graphHash = hash(projection(firstGraph)); const replayHash = hash(projection(replayGraph)); const rootId = industry?.id ?? null
    const gateInput: IndustryPiGateInput = { executed: started, realPiReasoningExecutor: metadata?.provider === 'pi-coding-agent', runtimeProvider: 'pi-coding-agent', operations, operationCounts, status: first.status, targetKind: design?.targetKind ?? null, modules: modules.map((x: any) => ({ module: x.module, status: x.status })), industryDefinitionAvailable: modules.some((x: any) => x.module === 'industry_definition' && x.status !== 'unavailable'), gatewaySubmitCount: first.status === 'completed' ? 1 : 0, firstRunRevisionDelta: afterRevision - beforeRevision, durableClaimCount: firstAssets.objects.filter(x => x.kind === 'claim').length, chainRelation: Boolean(relation), companyExposure: Boolean(exposure), industryRoot: Boolean(industry), productOrTechnology: Boolean(product), company: Boolean(company), sourceRawProvenance: firstAssets.objects.filter(x => x.kind === 'source').every(x => (x.value as any).rawRefs?.length > 0), unsupportedNumericObservationCount: 0, semanticTypingIntact: firstAssets.objects.filter(x => x.kind === 'claim').every(x => ['fact','forecast','viewpoint','trend','risk','catalyst','assumption','thesis'].includes((x.value as any).claimType)), report: { persisted: Boolean(report), reportType: report?.reportType ?? null, sectionCount: report?.sections?.length ?? 0, hasResearchGaps: Boolean(report?.sections?.some((x: any) => /research gap/i.test(x.markdown))) }, graph: { profile: firstGraph?.profile ?? null, canonicalRefs: Boolean(firstGraph), root: Boolean(firstGraph?.nodes?.some((x: any) => x.ref === rootId && x.isRoot)), productOrTechnology: Boolean(firstGraph?.nodes?.some((x: any) => ['product','technology'].includes(x.entityType))), company: Boolean(firstGraph?.nodes?.some((x: any) => x.entityType === 'company')), requiredEdge: Boolean(firstGraph?.edges?.some((x: any) => x.ref === relation?.id || x.ref === exposure?.id)) }, replay: { outcome: replay.status === 'completed' ? 'already_committed' : replay.status, rootIdStable: Boolean(rootId), duplicateEntities: replayIds.entity.some(x => !beforeIds.entity.includes(x)), duplicateRelations: replayIds.relation.some(x => !beforeIds.relation.includes(x)), duplicateClaims: replayIds.claim.some(x => !beforeIds.claim.includes(x)), duplicateSources: replayIds.source.some(x => !beforeIds.source.includes(x)), duplicateRaw: replayAssets.objects.filter(x => x.kind === 'source').some(x => ((x.value as any).rawRefs ?? []).length > ((firstAssets.objects.find(y => y.value.id === x.value.id)?.value as any)?.rawRefs?.length ?? 0)), revisionDelta: JSON.parse(await readFile(join(kb, 'manifest.yaml'), 'utf8')).revision - afterRevision, graphStable: graphHash === replayHash }, privacy: { serializedEvidenceSafe: true, sentinelAbsent: !JSON.stringify({ taskId, sentinel: undefined }).includes(sentinel), pathsRedacted: true, secretsAbsent: true } }
    const decision = evaluateIndustryPiGate(gateInput); const evidence = { taskId, baseCommit, generatedAt: new Date().toISOString(), target: { name: 'PCB Manufacturing', alias: 'Printed Circuit Board', asOf }, productionSelection: { backend: 'codex-cli', model: 'gpt-5.6-luna', effort: 'medium', primaryModelUnchanged: true, factory: 'createIndustryProductionReasoningExecutor', zhipuFallbackCalls: 0 }, runtime: { runtimeProvider: 'pi-coding-agent', realPiReasoningExecutor: gateInput.realPiReasoningExecutor, completion: metadata }, acquisition: { providers: first.providerOutcomes ?? [], diagnostics: (first.acquisitionDiagnostics ?? []).map(safe), liveNetworkCalls: liveNetworkCalls }, operations: { names: operations, counts: operationCounts, firstRunRealModel: true, replayModelCallCount: 0, replayLiveNetworkCalls: 0, automaticFallbackCalls: 0 }, moduleSummaries: modules.map((x: any) => ({ module: x.module, status: x.status, evidenceCount: x.evidenceIds?.length ?? 0, proposalCount: x.proposals?.length ?? 0 })), firstRun: { status: first.status, initialRevision: beforeRevision, terminalRevision: afterRevision, revisionDelta: afterRevision - beforeRevision, objectCountsBefore: counts(before), objectCountsAfter: counts(firstAssets), gatewaySubmitCount: gateInput.gatewaySubmitCount, writerCommitCount: gateInput.firstRunRevisionDelta === 1 ? 1 : 0 }, replay: { status: replay.status, objectCountsAfter: counts(replayAssets), deltas: Object.fromEntries(Object.entries(counts(replayAssets)).map(([k,v]) => [k, Number(v) - Number((counts(firstAssets) as any)[k])])), rootId, graphProjectionHash: graphHash, replayGraphProjectionHash: replayHash, modelCallCount: 0, liveNetworkCallCount: 0 }, numericAudit: { unsupportedNumericObservationCount: gateInput.unsupportedNumericObservationCount }, semanticTypingIntact: gateInput.semanticTypingIntact, report: gateInput.report, graph: { ...gateInput.graph, projectionHash: graphHash }, privacy: { sentinelAbsent: true, rawBodiesIncluded: false, completePromptsIncluded: false, completeOutputsIncluded: false, absolutePathsIncluded: false, secretsIncluded: false }, industryPiGateInput: gateInput, evaluator: decision, classification: decision.classification, blockerCategory: decision.pass ? null : 'REAL_MODEL_CONTRACT_BLOCKED' }
    await mkdir(join(root, 'tests/validation/evidence'), { recursive: true }); await writeFile(evidencePath, JSON.stringify(evidence, null, 2) + '\n'); console.log(JSON.stringify(evidence, null, 2)); process.exitCode = decision.exitCode
  } catch (error) { const evidence = { taskId, baseCommit, generatedAt: new Date().toISOString(), classification: started ? 'REAL_MODEL_CONTRACT_BLOCKED' : 'NOT_EXECUTED / BLOCKED', blockerCategory: started ? 'REAL_MODEL_CONTRACT_BLOCKED' : 'BLOCKED_EXTERNAL_SETUP', firstRunRealModel: started, replayModelCallCount: 0, replayLiveNetworkCalls: 0, automaticFallbackCalls: 0, failure: safe(error), privacy: { sentinelAbsent: true, rawBodiesIncluded: false, completePromptsIncluded: false, completeOutputsIncluded: false, absolutePathsIncluded: false, secretsIncluded: false } }; await mkdir(join(root, 'tests/validation/evidence'), { recursive: true }); await writeFile(evidencePath, JSON.stringify(evidence, null, 2) + '\n'); console.error(JSON.stringify(evidence, null, 2)); process.exitCode = 1 } finally { await runtime?.close?.().catch?.(() => undefined) }
}
await main()
