import test from 'node:test'
import assert from 'node:assert/strict'
import { auditStructuredValues, classifyDiagnosticFailure, classifyModelRuntime, TEST_035_SECTIONS } from './industry-model-runtime-rerun-after-v04-convergence.ts'

test('completed Gateway/canonical/report lifecycle is healthy', () => assert.equal(classifyModelRuntime({ preflightOk: true, workflowStatus: 'completed', gatewaySubmissionCount: 1, revisionDelta: 1, reportType: 'industry_research', sectionCount: 16, sectionTitles: TEST_035_SECTIONS }), 'MODEL_RUNTIME_PATH_HEALTHY'))
test('external process or model availability is inconclusive', () => { assert.equal(classifyDiagnosticFailure({ preflightOk: false, error: 'process-launch' }), 'MODEL_RUNTIME_EXTERNAL_INCONCLUSIVE'); assert.equal(classifyDiagnosticFailure({ preflightOk: true, error: 'timeout' }), 'MODEL_RUNTIME_EXTERNAL_INCONCLUSIVE') })
test('corrected-validator-approved canonical drift is a project defect', () => assert.equal(classifyDiagnosticFailure({ preflightOk: true, error: 'V04_STRUCTURED_VALUE', boundary: 'corrected-validator-approved-to-canonical-conversion' }), 'MODEL_RUNTIME_PROJECT_DEFECT'))
test('one incompatible candidate plus one compatible repair is healthy', () => assert.equal(classifyModelRuntime({ preflightOk: true, workflowStatus: 'completed', gatewaySubmissionCount: 1, revisionDelta: 1, reportType: 'industry_research', sectionCount: 16, sectionTitles: [...TEST_035_SECTIONS], terminalErrorCategory: null }), 'MODEL_RUNTIME_PATH_HEALTHY'))
test('structuredValue audit enforces the Schema 0.4 field and comparator allowlists', () => { const objects = [{ id: 'claim:one', structuredValue: { metric: 'revenue', value: 1, unit: 'CNY', comparator: 'eq', period: '2026' } }, { id: 'claim:two', structuredValue: { metric: 'bad', value: 1, unit: 'CNY', comparator: 'observed', geography: 'CN' } }]; const result = auditStructuredValues(objects); assert.equal(result.quantitativeClaimCandidatesObserved, 2); assert.equal(result.schema04CompatibleStructuredValueCandidates, 1); assert.equal(result.locallyRejectedIncompatibleCandidates, 1); assert.equal(result.allValidatedKeysAllowed, false); assert.equal(result.allComparatorsCanonical, false) })
