// @ts-nocheck
import { readFile, writeFile, mkdir, mkdtemp } from 'node:fs/promises'
import { join, resolve, isAbsolute } from 'node:path'
import { tmpdir } from 'node:os'
import { fileURLToPath } from 'node:url'
import { ModelRuntime, getAgentDir } from '@earendil-works/pi-coding-agent'
import { PiReasoningExecutor } from '../../plugins/reasoning/pi/executor.ts'
import { createIndustryProductionReasoningExecutor, selectProductionReasoningModel } from '../../app/pi/model-selection.ts'
import { runIndustryDeepResearch } from '../../workflows/industry-deep-research/workflow.ts'
import { IndustryAcquisitionComposition } from '../../plugins/research-acquisition/industry-composition.ts'
import { OfficialDisclosureResearchPlugin, CninfoOfficialDisclosureClient } from '../../plugins/research-acquisition/official.ts'
import { GdeltResearchPlugin } from '../../plugins/research-acquisition/gdelt.ts'
import { MiitIndustryResearchPlugin, MIIT_PCB_DEFINITION_ANCHORS } from '../../plugins/research-acquisition/miit-industry.ts'
import { GovCnIndustryResearchPlugin } from '../../plugins/research-acquisition/govcn-industry.ts'
import { EastmoneyIndustryResearchPlugin } from '../../plugins/research-acquisition/eastmoney-industry.ts'
import { CpcaIndustryResearchPlugin } from '../../plugins/research-acquisition/cpca-industry.ts'
import { AkshareDataAdapter } from '../../plugins/research-acquisition/akshare.ts'
import { AkshareIndustryResearchPlugin } from '../../plugins/research-acquisition/industry.ts'
import { sha256 } from '../../plugins/research-acquisition/hash.ts'
import { createFreshKnowledgeBaseV04, readCanonicalV04Assets } from '../../knowledge/storage/index.ts'
import { KnowledgeBaseRegistry } from '../../knowledge/registry/registry.ts'
import { validateKnowledgeV04Objects } from '../../knowledge/validation/v04-validator.ts'
import { preflight } from '../../scripts/document-parser-runtime.mjs'
import { acceptedEvidenceCounts, assembleTest054Evidence, TEST054_MODULES, TEST054_PROVIDERS, TEST054_SECTIONS, classifyTest054, metricProviderName, summarizeMiitManagedParser } from './industry-seven-provider-product-quality-after-docling-ready-assembly.ts'

export const TARGET = { name: 'PCB Manufacturing', aliases: ['Printed Circuit Board', '印制电路板'], asOf: '2026-09-14T00:00:00.000Z', searchTerms: ['PCB 印制电路板', 'AI server PCB HDI', 'PCB industry chain', 'PCB industry capacity'] } as const
const root = resolve(fileURLToPath(new URL('../..', import.meta.url)))
const evidencePath = join(root, 'tests/validation/evidence/RHL_M3B_INDUSTRY_SEVEN_PROVIDER_PRODUCT_QUALITY_AFTER_DOCLING_READY.json')
const safe = (v: unknown) => String(v instanceof Error ? v.message : v).replace(/[A-Za-z]:[\\/][^\s;)]+/g, '<private-path>').replace(/(authorization|cookie|api[-_]?key|token|secret|password)\s*[:=]\s*[^,;\s]+/gi, '$1=<redacted>').slice(0, 500)
const privacy = { rawBodiesIncluded: false, fullNormalizedTextIncluded: false, reportBodyIncluded: false, credentialsIncluded: false, tokensIncluded: false, absolutePathsIncluded: false, environmentDumpIncluded: false, proxyValuesIncluded: false, cookiesIncluded: false, requestHeadersIncluded: false, modelPromptsIncluded: false, modelResponsesIncluded: false }
const countKinds = (assets: any) => Object.fromEntries(['entity','relation','claim','source'].map(k => [k, assets.objects.filter((x: any) => x.kind === k).length]))

function instrument(plugin: any, log: any[]) { return { name: plugin.name, async discover(request: any) { const row: any = { provider: plugin.name, phase: 'discover', wave: request.wave, attempted: true }; log.push(row); try { const out = await plugin.discover(request); row.searchResultCount = out.length; row.succeeded = true; return out } catch (e) { row.failed = true; row.failureCategory = safe(e); throw e } }, async fetch(c: any) { const row: any = { provider: plugin.name, phase: 'fetch', attempted: true, candidateId: c.candidateId }; log.push(row); try { const out = await plugin.fetch(c); row.succeeded = true; row.fetchedCount = 1; row.mediaType = out.mediaType; row.byteCount = out.rawBytes?.byteLength ?? 0; return out } catch (e) { row.failed = true; row.failureCategory = safe(e); throw e } }, async normalize(s: any) { const row: any = { provider: plugin.name, phase: 'normalize', attempted: true, candidateId: s.candidate?.candidateId }; log.push(row); try { const out = await plugin.normalize(s); row.succeeded = true; row.normalizedCount = 1; row.qualifiedCandidate = Boolean(out.content?.trim()); row.contentHash = out.contentHash; row.publisher = out.publisher; row.contentLength = typeof out.content === 'string' ? out.content.length : 0; return out } catch (e) { row.failed = true; row.failureCategory = safe(e); throw e } } } }
function providerMetrics(log: any[], outcomes: any[], acceptedByProvider = new Map<string, number>()) { return TEST054_PROVIDERS.map(provider => { const rows = log.filter(x => x.provider === provider); const o = outcomes.filter(x => x.provider === provider); return { provider, attempted: rows.length > 0 || o.length > 0, searchResultCount: rows.filter(x => x.phase === 'discover').reduce((n, x) => n + (x.searchResultCount ?? 0), 0), fetchedCount: rows.filter(x => x.phase === 'fetch' && x.succeeded).length, normalizedCount: rows.filter(x => x.phase === 'normalize' && x.succeeded).length, usableSourceCount: o.reduce((n, x) => n + (x.usableSourceCount ?? 0), 0), qualifiedEvidenceCount: acceptedByProvider.get(provider) ?? 0, boundedFailureCategory: [...new Set(rows.filter(x => x.failed).map(x => x.failureCategory))][0] ?? null, contributedModules: [] as string[] } }) }
function sanitizeEvidence(e: any) { const c = e.source?.candidate ?? {}; return { evidenceId: e.evidenceId, provider: c.provider, tier: c.tier, title: c.title, url: c.url, publishedAt: c.publishedAt ?? null, canonicalUrl: e.source?.canonicalUrl, contentHash: e.source?.contentHash, publisher: e.source?.publisher, rights: e.source?.rights?.accessScope ?? null, contentLength: typeof e.source?.content === 'string' ? e.source.content.length : null } }
function sanitizeModule(m: any) { return { module: m.module, status: m.status, qualifiedEvidenceCount: (m.evidenceIds ?? []).length, sourceTierCounts: {}, gapCount: (m.gaps ?? []).length, gapIds: (m.gaps ?? []).map((g: any) => g.gapId), evidenceIds: m.evidenceIds ?? [] } }

export async function main() {
  const taskId = 'RHL-M3B-3B-TEST-054-INDUSTRY-SEVEN-PROVIDER-PRODUCT-QUALITY-AFTER-DOCLING-READY'
  const parser = await preflight({ root });
  const base: any = { taskId, baseCommit: '7d939d97159c4c5734113369f77f24037bb62c1c', test052Acceptance: { accepted: true, authoritativeBaseline: '1218b5fd043d6bac58198f9b362e329d3d665b69', completedHead: '7d939d97159c4c5734113369f77f24037bb62c1c', ancestry: 'exactly_one_commit_ahead', historicalInternalBaseCorrection: 'Historical TEST-052 artifacts retain 49e7dd9ae576505ed4addfe29476a3fd86bd1fd0; GitHub ancestry and execution baseline are authoritative.' }, parserPreflight: { status: parser?.status ?? 'INCONCLUSIVE', pythonReady: parser?.pythonReady === true, dependencyReady: parser?.dependencyReady === true, artifactsReady: parser?.artifactsReady === true, bridgeReady: parser?.bridgeReady === true }, target: { nameHash: sha256(TARGET.name), aliasHashes: TARGET.aliases.map(sha256), asOf: TARGET.asOf }, providerPortfolio: TEST054_PROVIDERS, privacy }
  await mkdir(join(root, 'tests/validation/evidence'), { recursive: true })
  if (parser?.status !== 'READY') { const out = { ...base, workflowInvoked: false, finalClassification: 'INDUSTRY_PRODUCT_QUALITY_BLOCKED_BY_EXTERNAL_PROVIDER' }; await writeFile(evidencePath, JSON.stringify(out, null, 2) + '\n'); return out }
  const temp = await mkdtemp(join(tmpdir(), 'rhl-m3b3-test-054-')), kb = join(temp, 'kb'), reports = join(temp, 'reports'); await mkdir(reports, { recursive: true }); await createFreshKnowledgeBaseV04(kb, { knowledgeBaseId: 'kb-m3b3-test-054', now: TARGET.asOf }); const before = await readCanonicalV04Assets(kb); const log: any[] = [], outcomes: any[] = [], calls: any[] = []; let runtime: any
  try {
    const registry = new KnowledgeBaseRegistry(), handle = await registry.mount(kb); runtime = await ModelRuntime.create({ authPath: join(getAgentDir(), 'auth.json'), modelsPath: join(getAgentDir(), 'models.json'), allowModelNetwork: true, refreshOnCreate: false }); const primary = new PiReasoningExecutor({ modelRuntime: runtime, model: selectProductionReasoningModel(runtime) }); const real = await createIndustryProductionReasoningExecutor({ capabilities: primary.capabilities(), timeoutMs: 900000, maxOutputChars: 400000, tempRoot: temp }); const reasoning = { capabilities: () => real.capabilities(), execute: async (r: any) => { calls.push({ operation: r.operation, module: r.input?.module ?? null }); return real.execute(r) } }
    const plugins = [new OfficialDisclosureResearchPlugin(new CninfoOfficialDisclosureClient()), new GdeltResearchPlugin(), new MiitIndustryResearchPlugin({ now: () => TARGET.asOf }), new GovCnIndustryResearchPlugin(), new EastmoneyIndustryResearchPlugin(), new CpcaIndustryResearchPlugin(), new AkshareIndustryResearchPlugin(new AkshareDataAdapter())].map(p => instrument(p, log)); const composition = new IndustryAcquisitionComposition(plugins)
    const result: any = await runIndustryDeepResearch({ workflowRunId: 'rhl-m3b3-test-054-live', handle, target: TARGET, reportRoot: reports, reasoningExecutor: reasoning, asOf: TARGET.asOf, maxSources: 24, maxEvidencePerModule: 2, acquisitionWave: async req => { const searchTerms = req.wave === 1 ? TARGET.searchTerms : [...new Set([...req.searchTerms, ...TARGET.searchTerms])].slice(0, 8); const got = await composition.acquire({ ...req, searchTerms }); outcomes.push(...got.outcomes); return got.sources } }); const after = await readCanonicalV04Assets(kb); const validation = validateKnowledgeV04Objects(after.objects.map((x: any) => x.value)); const report = result.report ? await readFile(isAbsolute(result.report.outputPath) ? `${result.report.outputPath}.json` : join(reports, `${result.report.outputPath}.json`), 'utf8').then(JSON.parse).catch(() => null) : null; const metrics = providerMetrics(log, outcomes, acceptedEvidenceCounts(result.evidence ?? [])); const modules = (result.modules ?? []).map(sanitizeModule)
    for (const m of result.modules ?? []) for (const id of m.evidenceIds ?? []) { const ev = (result.evidence ?? []).find((e: any) => e.evidenceId === id); const row = metrics.find(x => x.provider === metricProviderName(ev?.source?.candidate?.provider)); if (row && !row.contributedModules.includes(m.module)) row.contributedModules.push(m.module) }
    const miitAnchorCandidateIds = new Set(MIIT_PCB_DEFINITION_ANCHORS.map(x => `miit-${sha256(x.url)}`)); const miitPdfAnchorCandidateIds = new Set(MIIT_PCB_DEFINITION_ANCHORS.filter(x => /\.pdf(?:$|[?#])/i.test(x.url)).map(x => `miit-${sha256(x.url)}`)); const miitManagedParser = summarizeMiitManagedParser(log, miitAnchorCandidateIds, miitPdfAnchorCandidateIds); const reportMetrics = { generated: Boolean(report), sectionCount: report?.sections?.length ?? 0, sectionTitles: report?.sections?.map((x: any) => x.title) ?? [], expectedSectionCount: TEST054_SECTIONS.length, moduleCoverage: TEST054_SECTIONS.every(x => report?.sections?.some((s: any) => s.title === x)), unresolvedGapCount: (result.modules ?? []).flatMap((m: any) => m.gaps ?? []).length, validationStatus: report ? 'validated' : 'not_generated' }
    const sourceRaw = after.objects.filter((x: any) => x.kind === 'source').every((x: any) => (x.value.rawRefs ?? []).length > 0); const proposals = [...(result.modules ?? []).flatMap((m: any) => m.proposals ?? []), ...(result.synthesis?.proposals ?? [])]; const durableProposals = proposals.filter((p: any) => p.kind === 'claim' || p.kind === 'relation'); const provenance = { durableProposalCount: durableProposals.length, proposalsWithSourceRawProvenance: durableProposals.filter((p: any) => (p.sourceCandidateIds ?? []).length > 0).length, allDurableProposalsHaveSourceRaw: durableProposals.every((p: any) => (p.sourceCandidateIds ?? []).length > 0) && sourceRaw }
    const changeSetCount = result.status === 'completed' ? 1 : 0; const writerInvocationCount = changeSetCount; const out = { ...base, workflowInvoked: true, workflow: { status: result.status, errors: (result.errors ?? []).map(safe), diagnostics: (result.diagnostics ?? []).map(safe), acquisitionWaveCount: result.acquisitionWaves, wave2Reason: result.acquisitionWaves > 1 ? 'actionable_gap_fill' : null, moduleCallCounts: result.moduleCallCounts, gatewayCallCount: result.gatewaySubmitCount, proposalBundleCount: result.proposalIds?.length ? 1 : 0, changeSetCount, writerInvocationCount }, providers: metrics, miitManagedParser, modules, gapIdValidation: { valid: (result.modules ?? []).flatMap((m: any) => m.gaps ?? []).every((g: any) => typeof g.gapId === 'string' && g.gapId.length > 0), gapIds: (result.modules ?? []).flatMap((m: any) => (m.gaps ?? []).map((g: any) => g.gapId)) }, evidenceSummary: { totalQualified: result.evidence?.length ?? 0, byModule: Object.fromEntries(TEST054_MODULES.map(m => [m, (result.modules ?? []).find((x: any) => x.module === m)?.evidenceIds?.length ?? 0])), byTier: Object.fromEntries([...new Set((result.evidence ?? []).map((e: any) => e.source?.candidate?.tier))].map(t => [t, (result.evidence ?? []).filter((e: any) => e.source?.candidate?.tier === t).length])) }, proposalProvenance: provenance, canonical: { countsBefore: countKinds(before), countsAfter: countKinds(after), validationStatus: validation.status, diagnosticCodes: validation.errors.map((x: any) => x.code), sourceRawProvenance: sourceRaw }, report: reportMetrics, priorErrorObserved: false, calls, finalClassification: classifyTest054({ parserReady: true, workflowStatus: result.status, providers: metrics, definitionEvidence: (result.modules ?? []).find((m: any) => m.module === 'industry_definition')?.evidenceIds?.length > 0, modules: result.modules, waveCount: result.acquisitionWaves, gapIdsValid: (result.modules ?? []).flatMap((m: any) => m.gaps ?? []).every((g: any) => typeof g.gapId === 'string' && g.gapId.length > 0), provenance, proposalBundleCount: result.proposalIds?.length ? 1 : 0, gatewayCallCount: result.gatewaySubmitCount, changeSetCount, writerInvocationCount, report: reportMetrics, canonicalValidation: validation.status }) }; await writeFile(evidencePath, JSON.stringify(out, null, 2) + '\n'); return out
  } catch (e) { const out = { ...base, workflowInvoked: true, errors: [safe(e)], finalClassification: 'INDUSTRY_PRODUCT_QUALITY_WORKFLOW_DEFECT' }; await writeFile(evidencePath, JSON.stringify(out, null, 2) + '\n'); return out } finally { await runtime?.dispose?.().catch?.(() => undefined) }
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main().then(x => console.log(JSON.stringify(x, null, 2)))
