import test from 'node:test'
import assert from 'node:assert/strict'
import { classifyTest054, TEST054_PROVIDERS } from './industry-seven-provider-product-quality-after-docling-ready-assembly.ts'
const ready = () => ({ parserReady: true, workflowStatus: 'completed', providers: TEST054_PROVIDERS.map(provider => ({ provider, attempted: true })), definitionEvidence: true, modules: Array.from({ length: 8 }, () => ({ status: 'supported' })), waveCount: 1, gapIdsValid: true, provenance: { allDurableProposalsHaveSourceRaw: true }, proposalBundleCount: 1, gatewayCallCount: 1, changeSetCount: 1, writerInvocationCount: 1, canonicalValidation: 'valid', report: { generated: true, moduleCoverage: true } })
test('READY requires managed parser and authoritative Industry Definition evidence', () => { assert.equal(classifyTest054(ready()), 'INDUSTRY_PRODUCT_QUALITY_READY'); assert.equal(classifyTest054({ ...ready(), parserReady: false }), 'INDUSTRY_PRODUCT_QUALITY_WORKFLOW_DEFECT'); assert.equal(classifyTest054({ ...ready(), definitionEvidence: false, workflowStatus: 'blocked' }), 'INDUSTRY_PRODUCT_QUALITY_BLOCKED_BY_EVIDENCE') })
test('non-READY parser prevents Workflow invocation and provider accounting is exact', () => { assert.equal(classifyTest054({ ...ready(), parserReady: false, providers: [] }), 'INDUSTRY_PRODUCT_QUALITY_WORKFLOW_DEFECT'); assert.deepEqual(TEST054_PROVIDERS, [...new Set(TEST054_PROVIDERS)]); assert.equal(TEST054_PROVIDERS.length, 7) })
test('bounded provider failure is tolerated when mandatory evidence and invariants hold', () => { const x: any = ready(); x.providers[0].boundedFailureCategory = 'external_unavailable'; assert.equal(classifyTest054(x), 'INDUSTRY_PRODUCT_QUALITY_READY') })
test('Wave2 greater than one, invalid gap, or missing provenance is a workflow defect', () => { assert.equal(classifyTest054({ ...ready(), waveCount: 3 }), 'INDUSTRY_PRODUCT_QUALITY_WORKFLOW_DEFECT'); assert.equal(classifyTest054({ ...ready(), gapIdsValid: false }), 'INDUSTRY_PRODUCT_QUALITY_WORKFLOW_DEFECT'); assert.equal(classifyTest054({ ...ready(), provenance: { allDurableProposalsHaveSourceRaw: false } }), 'INDUSTRY_PRODUCT_QUALITY_WORKFLOW_DEFECT') })
test('proposal, Gateway, ChangeSet, and Writer cardinality violations are defects', () => { for (const key of ['proposalBundleCount','gatewayCallCount','changeSetCount','writerInvocationCount']) assert.equal(classifyTest054({ ...ready(), [key]: 2 }), 'INDUSTRY_PRODUCT_QUALITY_WORKFLOW_DEFECT') })
test('privacy evidence is bounded and model runtime is classified separately', () => { assert.equal(classifyTest054({ ...ready(), modelRuntimeUnavailable: true }), 'INDUSTRY_PRODUCT_QUALITY_BLOCKED_BY_MODEL_RUNTIME') })
