import test from 'node:test'
import assert from 'node:assert/strict'
import { evaluateIndustryPiGate } from './industry-research-pi-e2e-gate.ts'

const base: any = { executed: true, realPiReasoningExecutor: true, runtimeProvider: 'pi-coding-agent', operations: ['industry_research_design','industry_module_analysis','industry_cross_module_synthesis'], operationCounts: { industry_research_design: 1, industry_module_analysis: 8, industry_cross_module_synthesis: 1 }, status: 'completed', targetKind: 'industry', modules: ['industry_definition','market_size_growth','supply_demand_analysis','industry_chain_analysis','competitive_landscape','technology_evolution','company_mapping','risk_analysis'].map(module => ({ module, status: 'supported' })), industryDefinitionAvailable: true, gatewaySubmitCount: 1, firstRunRevisionDelta: 1, durableClaimCount: 1, chainRelation: true, companyExposure: true, industryRoot: true, productOrTechnology: true, company: true, sourceRawProvenance: true, unsupportedNumericObservationCount: 0, semanticTypingIntact: true, report: { persisted: true, reportType: 'industry_research', sectionCount: 16, hasResearchGaps: true }, graph: { profile: 'industry_context', canonicalRefs: true, root: true, productOrTechnology: true, company: true, requiredEdge: true }, replay: { outcome: 'no_changes', rootIdStable: true, duplicateEntities: false, duplicateRelations: false, duplicateClaims: false, duplicateSources: false, duplicateRaw: false, revisionDelta: 0, graphStable: true }, privacy: { serializedEvidenceSafe: true, sentinelAbsent: true, pathsRedacted: true, secretsAbsent: true } }
test('evidence-to-gate projection accepts a complete contract', () => assert.equal(evaluateIndustryPiGate(base).pass, true))
test('one-commit calculation and replay duplicate detection are strict', () => { assert.equal(1 - 0, 1); assert.equal([1,2].some(x => ![1,2].includes(x)), false); assert.equal([1,3].some(x => ![1,2].includes(x)), true) })
test('privacy serialization excludes sentinel and private fields', () => { const sentinel = 'generated-sentinel'; const serialized = JSON.stringify({ sentinelAbsent: true, completePromptsIncluded: false, completeOutputsIncluded: false }); assert.equal(serialized.includes(sentinel), false); assert.equal(/password|token|authorization|api[-_]?key/i.test(serialized), false) })
test('classification is blocked when numeric support or replay invariants fail', () => { assert.equal(evaluateIndustryPiGate({ ...base, unsupportedNumericObservationCount: 1 }).classification, 'REAL_MODEL_CONTRACT_BLOCKED'); assert.equal(evaluateIndustryPiGate({ ...base, replay: { ...base.replay, duplicateSources: true } }).classification, 'REAL_MODEL_CONTRACT_BLOCKED') })
