// TEST-033: one live production Industry reasoning-path diagnosis; no commit/push.
// @ts-nocheck
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { tmpdir } from 'node:os'
import { ModelRuntime, getAgentDir } from '@earendil-works/pi-coding-agent'
import { PiReasoningExecutor } from '../../plugins/reasoning/pi/executor.ts'
import { buildCodexCliProcessInvocation, resolveCodexCliExecutable } from '../../plugins/reasoning/codex-cli/executor.ts'
import { createIndustryProductionReasoningExecutor, selectProductionReasoningModel } from '../../app/pi/model-selection.ts'
import { ResearchService } from '../../app/services/research-service.ts'
import { WorkflowService } from '../../app/services/workflow-service.ts'
import { createFreshKnowledgeBaseV04, readCanonicalV04Assets } from '../../knowledge/storage/index.ts'
import { sha256 } from '../../plugins/research-acquisition/hash.ts'
import type { NormalizedResearchSource, ResearchAcquisitionRequest } from '../../plugins/research-acquisition/contracts.ts'

export const TEST_033_TASK_ID = 'RHL-M3B-3B-TEST-033-INDUSTRY-MODEL-RUNTIME-LIVE-DIAGNOSIS'
export const TEST_033_BASELINE = 'd7259b05b6725d6b860128d031b9906136cbeaf2'
export const TEST_033_TARGET = { name: 'PCB Manufacturing', aliases: ['Printed Circuit Board', '印制电路板'], asOf: '2026-09-14T00:00:00.000Z' } as const
export const TEST_033_MODULES = ['industry_definition','market_size_growth','supply_demand_analysis','industry_chain_analysis','competitive_landscape','technology_evolution','company_mapping','risk_analysis'] as const
export const TEST_033_SECTIONS = ['Executive Industry View','Industry Scope & Definition','Market Size & Growth','Demand Structure & Drivers','Supply, Capacity & Utilization','Supply-Demand Balance & Pricing','Industry Chain Map','Value Capture & Industry Economics','Competitive Landscape','Technology & Product Roadmap','Company Mapping & Exposure','Catalysts','Risks & Invalidation Conditions','Key Metrics & Monitoring','Research Gaps & Alternative Views','Methodology & Provenance'] as const
export type FinalClassification = 'MODEL_RUNTIME_PATH_HEALTHY' | 'MODEL_RUNTIME_EXTERNAL_INCONCLUSIVE' | 'MODEL_RUNTIME_PROJECT_DEFECT'
const root = resolve(import.meta.dirname, '../..')
const evidencePath = join(root, 'tests/validation/evidence/RHL_M3B_INDUSTRY_MODEL_RUNTIME_LIVE_DIAGNOSIS.json')
const safe = (x: unknown) => String(x instanceof Error ? x.message : x).replace(/[A-Za-z]:\\[^\s;]*/g, '<path>').replace(/(authorization|cookie|api[-_]?key|token|secret|password)\s*[:=]\s*[^,;\s]+/gi, '$1=<redacted>').replace(/\s+/g, ' ').slice(0, 300)
const digest = (x: unknown) => sha256(JSON.stringify(x))
const elapsedBucket = (ms: number) => ms < 1000 ? '<1s' : ms < 10_000 ? '1-10s' : ms < 60_000 ? '10-60s' : '>=60s'

export function classifyModelRuntime(input: { workflowStatus?: string; gatewaySubmissionCount?: number; revisionDelta?: number; reportType?: string | null; sectionCount?: number; sectionTitles?: readonly string[]; preflightOk?: boolean; terminalErrorCategory?: string | null; smallestFailingBoundary?: string | null; }) : FinalClassification {
  if (!input.preflightOk) return 'MODEL_RUNTIME_EXTERNAL_INCONCLUSIVE'
  const healthy = input.workflowStatus === 'completed' && input.gatewaySubmissionCount === 1 && input.revisionDelta === 1 && input.reportType === 'industry_research' && input.sectionCount === 16 && TEST_033_SECTIONS.every((title) => input.sectionTitles?.includes(title))
  if (healthy) return 'MODEL_RUNTIME_PATH_HEALTHY'
  if (input.smallestFailingBoundary === 'project-controlled-contract-or-adapter') return 'MODEL_RUNTIME_PROJECT_DEFECT'
  if (input.terminalErrorCategory && /transport|quota|service|auth|timeout|launch|runtime|process|external/i.test(input.terminalErrorCategory)) return 'MODEL_RUNTIME_EXTERNAL_INCONCLUSIVE'
  return 'MODEL_RUNTIME_EXTERNAL_INCONCLUSIVE'
}

export function sanitizeOperationError(error: unknown) { const text = safe(error).toLowerCase(); if (/timeout/.test(text)) return 'timeout'; if (/auth|login|credential|401|403/.test(text)) return 'authentication-session'; if (/quota|rate.?limit|429/.test(text)) return 'quota'; if (/spawn|launch|enoent|process/.test(text)) return 'process-launch'; if (/network|fetch|socket|connect|transport|service unavailable|unavailable/.test(text)) return 'transport-service'; if (/json|schema|contract|parse|invalid output/.test(text)) return 'local-structured-output-validation'; return 'reasoning-runtime-error' }

export function classifyDiagnosticFailure(input: { preflightOk: boolean; error?: string; boundary?: string }) { return classifyModelRuntime({ preflightOk: input.preflightOk, terminalErrorCategory: input.error, smallestFailingBoundary: input.boundary }) }

async function codexPreflight() { const out:any = { discovered: false, resolutionSource: 'none', executableKind: 'none', versionAvailable: false, version: null, helpAvailable: false }; try { const found = resolveCodexCliExecutable(); out.discovered = true; out.resolutionSource = found.source; out.executableKind = found.kind; const run = promisify(execFile); const version = buildCodexCliProcessInvocation(found.executable, ['--version']); const help = buildCodexCliProcessInvocation(found.executable, ['exec', '--help']); const v = await run(version.executable, version.args, { windowsHide: true, timeout: 15_000, maxBuffer: 16_000 }); out.version = safe(v.stdout.trim().split(/\r?\n/)[0] ?? ''); out.versionAvailable = true; await run(help.executable, help.args, { windowsHide: true, timeout: 15_000, maxBuffer: 32_000 }); out.helpAvailable = true } catch { /* sanitized field shape is intentionally fixed */ } return out }

function fixtureSource(): NormalizedResearchSource { const candidate = { candidateId: 'test033-pcb-fixture-001', kind: 'web_article' as const, tier: 2 as const, title: 'Deterministic PCB manufacturing industry fixture', url: 'https://fixture.invalid/rhl-m3b-test-033', provider: 'test-local-deterministic-fixture', publishedAt: '2026-09-01T00:00:00.000Z', snippet: 'Bounded PCB manufacturing evidence fixture', metadata: { modules: [...TEST_033_MODULES], testFixture: true } }; const content = 'TEST-033 DETERMINISTIC FIXTURE ONLY. PCB manufacturing covers printed circuit boards and 印制电路板. The bounded evidence describes substrate and copper-clad laminate inputs, drilling, imaging, plating, testing, assembly demand, capacity, utilization, pricing, technology, competitive positioning, company mapping, risks, and monitoring questions. It is synthetic test material, not real market evidence, and must not be interpreted as a market fact.'; return { candidate, retrievedAt: '2026-09-14T00:00:00.000Z', title: candidate.title, content, canonicalUrl: candidate.url, contentHash: sha256(content), publisher: 'Deterministic Test Fixture', rights: { accessScope: 'public', retentionAllowed: true, aiProcessingAllowed: true, derivativeKnowledgeAllowed: true, redistributionAllowed: false, policyBasis: 'personal_noncommercial_research' } } }

function fixturePlugin(source: NormalizedResearchSource) { return { name: 'test-local-deterministic-fixture', async discover(_request: ResearchAcquisitionRequest) { return [source.candidate] }, async fetch(candidate:any) { return { candidate, retrievedAt: source.retrievedAt, content: source.content, contentHash: source.contentHash } }, async normalize(_fetched:any) { return source } } }
function counts(assets:any) { return Object.fromEntries(['entity','relation','claim','source'].map((kind) => [kind, assets.objects.filter((x:any) => x.kind === kind).length])) }
function privacy() { return { rawBodiesIncluded: false, completePromptsIncluded: false, completeOutputsIncluded: false, credentialsIncluded: false, privatePathsIncluded: false, reasoningTracesIncluded: false, publicProviderCalls: false } }
async function writeEvidence(value:any) { await mkdir(join(root, 'tests/validation/evidence'), { recursive: true }); await writeFile(evidencePath, JSON.stringify(value, null, 2) + '\n') }

export async function main() {
  const preflight = await codexPreflight(); const preflightOk = preflight.discovered && preflight.versionAvailable && preflight.helpAvailable
  if (!preflightOk) { const output = { taskId: TEST_033_TASK_ID, baseline: TEST_033_BASELINE, codexPreflight: preflight, selectedModel: { backend: 'codex-cli', model: 'gpt-5.6-luna', reasoningEffort: 'medium' }, fixture: { candidateId: 'test033-pcb-fixture-001', contentHash: sha256(fixtureSource().content), publisher: 'Deterministic Test Fixture', publishedAt: fixtureSource().candidate.publishedAt }, reasoning: { operationCounts: {}, operations: [] }, workflow: { terminalStatus: 'not_started' }, acquisitionWaveCount: 0, gatewaySubmissionCount: 0, revisionDelta: 0, canonicalObjectCounts: { before: null, after: null }, report: { present: false, type: null, sectionCount: 0, sectionTitles: [], frozenTitlesPresent: false }, privacyFlags: privacy(), finalClassification: 'MODEL_RUNTIME_EXTERNAL_INCONCLUSIVE' as const }; await writeEvidence(output); console.log(JSON.stringify(output, null, 2)); return output }
  let modelRuntime:any, appRuntime:any; const temp = await mkdtemp(join(tmpdir(), 'rhl-m3b3-test-033-')); const kb = join(temp, 'kb'); const reports = join(temp, 'reports'); const source = fixtureSource(); const operations:any[] = []; let callNumber = 0; let result:any; let before:any; let after:any; let initialRevision = 0; let terminalErrorCategory:string|null = null; let smallestFailingBoundary:string|null = null
  try {
    await mkdir(reports, { recursive: true }); await createFreshKnowledgeBaseV04(kb, { knowledgeBaseId: 'kb-m3b3-test-033' }); before = await readCanonicalV04Assets(kb); initialRevision = JSON.parse(await readFile(join(kb, 'manifest.yaml'), 'utf8')).revision
    modelRuntime = await ModelRuntime.create({ authPath: join(getAgentDir(), 'auth.json'), modelsPath: join(getAgentDir(), 'models.json'), allowModelNetwork: true, refreshOnCreate: false }); const primary = new PiReasoningExecutor({ modelRuntime, model: selectProductionReasoningModel(modelRuntime) }); const real = await createIndustryProductionReasoningExecutor({ capabilities: primary.capabilities(), timeoutMs: 900_000, maxOutputChars: 400_000, tempRoot: temp }); const executor:any = { capabilities: () => real.capabilities(), runtimeMetadata: () => real.runtimeMetadata?.(), execute: async (request:any) => { const started = new Date().toISOString(); const startedMs = Date.now(); callNumber++; const ordinal = callNumber; const prior = operations.filter((x) => x.operation === request.operation).length; const entry:any = { operation: request.operation, ordinal, started, returned: false, locallyValidated: undefined, repairCall: prior > 0 }; operations.push(entry); try { const response = await real.execute(request); entry.returned = true; entry.locallyValidated = true; entry.elapsed = elapsedBucket(Date.now() - startedMs); return response } catch (error) { entry.returned = false; entry.elapsed = elapsedBucket(Date.now() - startedMs); entry.terminalErrorCategory = sanitizeOperationError(error); terminalErrorCategory = entry.terminalErrorCategory; smallestFailingBoundary = 'reasoning-runtime'; throw error } } }
    const service = new ResearchService({ mountedKnowledgeBaseRoot: kb, reportRoot: reports, cwd: temp, acquisitionPlugins: [], industryAcquisitionPlugins: [fixturePlugin(source)], workflowService: new WorkflowService(), reasoningExecutor: primary, industryReasoningExecutorFactory: async () => executor }); appRuntime = await (await import('../../app/runtime/application-runtime.ts')).createResearchHubApplicationRuntime({ cwd: temp, agentDir: getAgentDir(), workspaceRoot: join(temp, 'workspace'), mountedKnowledgeBaseRoot: kb, modelRuntime, reasoningExecutor: primary, researchService: service })
    result = await service.startIndustryResearch({ workflowRunId: 'rhl-m3b3-test-033-live', name: TEST_033_TARGET.name, aliases: [...TEST_033_TARGET.aliases], asOf: TEST_033_TARGET.asOf, maxSources: 24, maxEvidencePerModule: 2, searchTerms: ['PCB manufacturing', 'printed circuit board', '印制电路板'] }).completion
    after = await readCanonicalV04Assets(kb); const finalRevision = JSON.parse(await readFile(join(kb, 'manifest.yaml'), 'utf8')).revision; const report = result.reportPath ? JSON.parse(await readFile(join(reports, result.reportPath + '.json'), 'utf8')) : null; const titles = report?.sections?.map((x:any) => x.title) ?? []; const terminal = { status: result.status, errors: (result.errorSummary ?? result.workflow?.errors?.join('; ') ?? '').split(';').map((x:string) => safe(x)).filter(Boolean).slice(0, 8) }; const output = { taskId: TEST_033_TASK_ID, baseline: TEST_033_BASELINE, codexPreflight: preflight, selectedModel: { backend: 'codex-cli', model: 'gpt-5.6-luna', reasoningEffort: 'medium' }, fixture: { candidateId: source.candidate.candidateId, contentHash: source.contentHash, contentHashAlgorithm: 'sha256', publisher: source.publisher, publishedAt: source.candidate.publishedAt, bodyPersisted: false }, reasoning: { operationCounts: Object.fromEntries(TEST_033_MODULES.length ? ['industry_research_design','industry_module_analysis','industry_cross_module_synthesis'].map((x) => [x, operations.filter((o) => o.operation === x).length]) : []), operations }, workflow: { terminalStatus: result.status, errors: terminal.errors, moduleSummary: (result.workflow?.modules ?? []).map((m:any) => ({ module: m.module, status: m.status })) }, acquisitionWaveCount: result.workflow?.acquisitionWaves ?? 0, gatewaySubmissionCount: result.workflow?.gatewaySubmitCount ?? 0, revisionDelta: finalRevision - initialRevision, canonicalObjectCounts: { before: counts(before), after: counts(after) }, report: { present: Boolean(report), type: report?.reportType ?? null, sectionCount: titles.length, sectionTitles: titles, frozenTitlesPresent: TEST_033_SECTIONS.every((x) => titles.includes(x)) }, failure: { category: terminalErrorCategory, smallestFailingBoundary }, privacyFlags: privacy(), finalClassification: classifyModelRuntime({ preflightOk, workflowStatus: result.status, gatewaySubmissionCount: result.workflow?.gatewaySubmitCount, revisionDelta: finalRevision - initialRevision, reportType: report?.reportType, sectionCount: titles.length, sectionTitles: titles, terminalErrorCategory, smallestFailingBoundary }) }; await writeEvidence(output); console.log(JSON.stringify(output, null, 2)); return output
  } catch (error) { terminalErrorCategory ??= sanitizeOperationError(error); smallestFailingBoundary ??= /V04_CANONICAL_INVALID|structuredValue|invalid output/i.test(safe(error)) ? 'model-output-contract-validation' : 'reasoning-runtime'; after ??= before; const output = { taskId: TEST_033_TASK_ID, baseline: TEST_033_BASELINE, codexPreflight: preflight, selectedModel: { backend: 'codex-cli', model: 'gpt-5.6-luna', reasoningEffort: 'medium' }, fixture: { candidateId: source.candidate.candidateId, contentHash: source.contentHash, contentHashAlgorithm: 'sha256', publisher: source.publisher, publishedAt: source.candidate.publishedAt, bodyPersisted: false }, reasoning: { operationCounts: Object.fromEntries(['industry_research_design','industry_module_analysis','industry_cross_module_synthesis'].map((x) => [x, operations.filter((o) => o.operation === x).length])), operations }, workflow: { terminalStatus: result?.status ?? 'failed', errors: [safe(error)], moduleSummary: (result?.workflow?.modules ?? []).map((m:any) => ({ module: m.module, status: m.status })) }, acquisitionWaveCount: operations.length > 0 ? 1 : 0, gatewaySubmissionCount: result?.workflow?.gatewaySubmitCount ?? 0, revisionDelta: 0, canonicalObjectCounts: { before: before ? counts(before) : null, after: after ? counts(after) : null }, report: { present: false, type: null, sectionCount: 0, sectionTitles: [], frozenTitlesPresent: false }, failure: { category: terminalErrorCategory, smallestFailingBoundary }, privacyFlags: privacy(), finalClassification: classifyModelRuntime({ preflightOk, terminalErrorCategory, smallestFailingBoundary }) }; await writeEvidence(output); console.error(JSON.stringify(output, null, 2)); return output }
  finally { await appRuntime?.close?.().catch?.(() => undefined); await modelRuntime?.dispose?.().catch?.(() => undefined) }
}
if (process.argv[1]?.endsWith('industry-model-runtime-live-diagnosis.ts')) await main()
