// TEST-041 is the sole live entrypoint for this rerun.
// @ts-nocheck
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { tmpdir } from "node:os";
import { ModelRuntime, getAgentDir } from "@earendil-works/pi-coding-agent";
import { PiReasoningExecutor } from "../../plugins/reasoning/pi/executor.ts";
import { resolveCodexCliExecutable, buildCodexCliProcessInvocation } from "../../plugins/reasoning/codex-cli/executor.ts";
import { createIndustryProductionReasoningExecutor, selectProductionReasoningModel } from "../../app/pi/model-selection.ts";
import { runIndustryDeepResearch } from "../../workflows/industry-deep-research/workflow.ts";
import { IndustryAcquisitionComposition } from "../../plugins/research-acquisition/industry-composition.ts";
import { createFreshKnowledgeBaseV04, readCanonicalV04Assets } from "../../knowledge/storage/index.ts";
import { KnowledgeBaseRegistry } from "../../knowledge/registry/registry.ts";
import { validateKnowledgeV04Objects } from "../../knowledge/validation/v04-validator.ts";
import { OfficialDisclosureResearchPlugin, CninfoOfficialDisclosureClient } from "../../plugins/research-acquisition/official.ts";
import { GdeltResearchPlugin } from "../../plugins/research-acquisition/gdelt.ts";
import { MiitIndustryResearchPlugin } from "../../plugins/research-acquisition/miit-industry.ts";
import { GovCnIndustryResearchPlugin } from "../../plugins/research-acquisition/govcn-industry.ts";
import { EastmoneyIndustryResearchPlugin } from "../../plugins/research-acquisition/eastmoney-industry.ts";
import { CpcaIndustryResearchPlugin } from "../../plugins/research-acquisition/cpca-industry.ts";
import { AkshareDataAdapter } from "../../plugins/research-acquisition/akshare.ts";
import { AkshareIndustryResearchPlugin } from "../../plugins/research-acquisition/industry.ts";
import { sha256 } from "../../plugins/research-acquisition/hash.ts";
import { TEST041_MODULES, TEST041_SECTIONS, assembleTest041ProductQualityEvidence, auditTest041Numbers } from "./industry-product-quality-rerun-after-audit-harness-fix-assembly.ts";

export const TARGET = {
  name: "PCB Manufacturing",
  aliases: ["Printed Circuit Board", "印制电路板"],
  asOf: "2026-09-14T00:00:00.000Z",
  searchTerms: ["PCB 印制电路板", "AI server PCB HDI", "Shennan Circuit PCB", "WUS PCB", "Pengding Technology PCB CCL", "Shengyi Technology PCB CCL", "PCB industry chain", "PCB industry capacity"],
} as const;
const root = resolve(import.meta.dirname, "../..");
const evidencePath = join(root, "tests/validation/evidence/RHL_M3B_INDUSTRY_PRODUCT_QUALITY_RERUN_AFTER_AUDIT_HARNESS_FIX.json");
const reportPath = join(root, "tests/validation/evidence/RHL_M3B_INDUSTRY_REPORT_RERUN_AFTER_AUDIT_HARNESS_FIX.json");
const safe = (x: unknown) => String(x instanceof Error ? x.message : x).replace(/[A-Za-z]:[\\/][^\s;)]+/g, "<private-path>").replace(/(authorization|cookie|api[-_]?key|token|secret|password)\s*[:=]\s*[^,;\s]+/gi, "$1=<redacted>").slice(0, 500);
const counts = (a: any) => Object.fromEntries(["entity", "relation", "claim", "source"].map((k) => [k, a.objects.filter((x: any) => x.kind === k).length]));

async function preflight() {
  const out: any = { discovered: false, versionAvailable: false, helpAvailable: false, resolutionSource: "none", executableKind: "none", version: null };
  let authoritativeWorkflow;
  try {
    const found = resolveCodexCliExecutable(); out.discovered = true; out.resolutionSource = found.source; out.executableKind = found.kind;
    const run = promisify(execFile); const version = buildCodexCliProcessInvocation(found.executable, ["--version"]); const help = buildCodexCliProcessInvocation(found.executable, ["exec", "--help"]);
    const vr = await run(version.executable, version.args, { windowsHide: true, timeout: 15000, maxBuffer: 16000 }); out.version = safe(vr.stdout.trim().split(/\r?\n/)[0] ?? ""); out.versionAvailable = true;
    await run(help.executable, help.args, { windowsHide: true, timeout: 15000, maxBuffer: 32000 }); out.helpAvailable = true;
  } catch (e) { out.failure = safe(e); }
  return out;
}
function wrap(plugin: any, log: any[]) {
  return { name: plugin.name,
    async discover(req: any) { const row = { provider: plugin.name, wave: req.wave, phase: "discover", attempted: true }; log.push(row); try { const value = await plugin.discover(req); row.succeeded = true; row.candidateCount = value.length; return value; } catch (e) { row.failed = true; row.failureCategory = safe(e); throw e; } },
    async fetch(candidate: any) { const row = { provider: plugin.name, phase: "fetch", attempted: true, candidateId: candidate.candidateId }; log.push(row); try { const value = await plugin.fetch(candidate); row.succeeded = true; return value; } catch (e) { row.failed = true; row.failureCategory = safe(e); throw e; } },
    async normalize(fetched: any) { const row: any = { provider: plugin.name, phase: "normalize", attempted: true, candidateId: fetched.candidate?.candidateId }; log.push(row); try { const value = await plugin.normalize(fetched); row.succeeded = true; row.usable = Boolean(value.content?.trim()); row.contentHash = value.contentHash; row.canonicalHost = value.canonicalUrl ? new URL(value.canonicalUrl).hostname : null; row.tier = value.candidate?.tier ?? null; row.publishedAtAvailable = Boolean(value.candidate?.publishedAt); return value; } catch (e) { row.failed = true; row.failureCategory = safe(e); throw e; } },
  };
}
function providerRows(log: any[], outcomes: any[]) { return [...new Set(log.map((x) => x.provider))].map((provider) => { const rows = log.filter((x) => x.provider === provider); const out = outcomes.filter((x) => x.provider === provider); return { provider, attempted: true, succeeded: out.some((x) => x.providerSucceeded), empty: out.some((x) => x.providerEmpty), failed: out.some((x) => x.providerFailed), usableNormalizedSourceCount: out.reduce((n, x) => n + (x.usableSourceCount ?? 0), 0), distinctContentCount: new Set(rows.map((x) => x.contentHash).filter(Boolean)).size, canonicalHostSet: [...new Set(rows.map((x) => x.canonicalHost).filter(Boolean))], tierDistribution: Object.fromEntries([...new Set(rows.map((x) => x.tier).filter(Boolean))].map((t) => [t, rows.filter((x) => x.tier === t).length])), publicationDateAvailable: rows.some((x) => x.publishedAtAvailable), failureCategories: [...new Set(rows.map((x) => x.failureCategory).filter(Boolean))], wavesAttempted: [...new Set(rows.map((x) => x.wave).filter(Boolean))] }; }); }
function sections(report: any, canonical: Set<string>) { return (report?.sections ?? []).map((s: any) => ({ title: s.title, markdown: String(s.markdown).slice(0, 8000), sourceRefs: s.sourceRefs ?? [], claimRefs: s.claimRefs ?? [], relationRefs: s.relationRefs ?? [], canonicalReferencesResolve: [...(s.sourceRefs ?? []), ...(s.claimRefs ?? []), ...(s.relationRefs ?? [])].every((x) => canonical.has(x)) })); }
function moduleMatrix(result: any, evidence: any[]) { return TEST041_MODULES.map((module) => { const m = (result.modules ?? []).find((x) => x.module === module); const ids = new Set(m?.evidenceIds ?? []); const used = evidence.filter((x) => ids.has(x.evidenceId)); return { module, status: m?.status ?? "unavailable", reasoningCallCount: result.moduleCallCounts?.[module] ?? 0, evidenceIds: [...ids], evidenceCount: ids.size, distinctProductionProviders: [...new Set(used.map((x) => x.source?.candidate?.provider).filter(Boolean))], proposalCounts: Object.fromEntries(["entity", "relation", "claim"].map((kind) => [kind, (m?.proposals ?? []).filter((p) => p.kind === kind).length])), actionableGapCount: (m?.gaps ?? []).filter((g) => g.actionable).length, reportMaterial: Boolean(m?.reportMaterial?.markdown), primaryGapCause: ids.size ? "NONE" : "NO_QUALIFIED_EVIDENCE_FOR_MODULE" }; }); }
function dimensions(sectionList: any[], matrix: any[]) { const evidence = (names: string[]) => names.reduce((n, name) => n + (matrix.find((x) => x.module === name)?.evidenceCount ?? 0), 0); const make = (dimension: string, titles: string[], modules: string[]) => { const xs = sectionList.filter((x) => titles.includes(x.title)); const n = evidence(modules); const gap = xs.some((x) => /research gap|unavailable|insufficient/i.test(x.markdown)); return { dimension, status: n === 0 ? "UNAVAILABLE" : gap ? "THIN" : "USABLE", rationale: `${n} routed evidence item(s); ${gap ? "material includes observed research gaps" : "material is traceable to acquired evidence"}.` }; }; return [make("scope clarity", ["Industry Scope & Definition"], ["industry_definition"]), make("factual evidence density", ["Executive Industry View", "Methodology & Provenance"], [...TEST041_MODULES]), make("quantitative and KPI usefulness", ["Market Size & Growth", "Key Metrics & Monitoring"], ["market_size_growth", "supply_demand_analysis"]), make("industry-chain and value-capture usefulness", ["Industry Chain Map", "Value Capture & Industry Economics"], ["industry_chain_analysis"]), make("company-mapping usefulness", ["Company Mapping & Exposure"], ["company_mapping"]), make("catalysts, risks, monitoring, and invalidation usefulness", ["Catalysts", "Risks & Invalidation Conditions", "Key Metrics & Monitoring"], ["risk_analysis", "supply_demand_analysis"])]; }

export async function main() {
  const taskId = "RHL-M3B-3B-TEST-041-INDUSTRY-PRODUCT-QUALITY-RERUN-AFTER-AUDIT-HARNESS-FIX"; const startedAt = new Date().toISOString(); const codexPreflight = await preflight();
  const base: any = { taskId, baseCommit: "30ae2bd3806e0c9879c05f1a288f8ecd5012cf9c", generatedAt: startedAt, codexPreflight, target: { nameHash: sha256(TARGET.name), aliasHashes: TARGET.aliases.map(sha256), searchTermHashes: TARGET.searchTerms.map(sha256), asOf: TARGET.asOf }, fix039Accepted: true, privacy: { rawBodiesIncluded: false, hiddenReasoningIncluded: false, credentialsIncluded: false, privatePathsIncluded: false } };
  await mkdir(join(root, "tests/validation/evidence"), { recursive: true });
  if (!codexPreflight.discovered || !codexPreflight.versionAvailable || !codexPreflight.helpAvailable) { const out = { ...base, providerCoverage: [], reasoningAudit: [], finalClassification: "PRODUCT_QUALITY_LIVE_INCONCLUSIVE" }; await writeFile(evidencePath, JSON.stringify(out, null, 2) + "\n"); await writeFile(reportPath, JSON.stringify({ taskId, status: "NOT_PRODUCED", reason: "Codex preflight failed" }, null, 2) + "\n"); return out; }
  const temp = await mkdtemp(join(tmpdir(), "rhl-m3b3-test-041-")); const kb = join(temp, "kb"); const reports = join(temp, "reports"); let model; const log: any[] = []; const reasoningAudit: any[] = [];
  try {
    await mkdir(reports, { recursive: true }); await createFreshKnowledgeBaseV04(kb, { knowledgeBaseId: "kb-m3b3-test-041", now: TARGET.asOf }); const before = await readCanonicalV04Assets(kb); const registry = new KnowledgeBaseRegistry(); const handle = await registry.mount(kb); model = await ModelRuntime.create({ authPath: join(getAgentDir(), "auth.json"), modelsPath: join(getAgentDir(), "models.json"), allowModelNetwork: true, refreshOnCreate: false }); const primary = new PiReasoningExecutor({ modelRuntime: model, model: selectProductionReasoningModel(model) }); const real = await createIndustryProductionReasoningExecutor({ capabilities: primary.capabilities(), timeoutMs: 900000, maxOutputChars: 400000, tempRoot: temp }); const ordinals = new Map(); const exec = { capabilities: () => real.capabilities(), execute: async (req: any) => { const identity = `${req.operation}:${req.input?.module ?? ""}`; const callCount = (ordinals.get(identity) ?? 0) + 1; try { const value = await real.execute(req); const text = JSON.stringify(value); reasoningAudit.push({ identity, callCount, boundedRepair: callCount === 2, returned: true, localValidationCategory: /Invalid Research Gap|module_shape_invalid/i.test(text) ? "module_shape_invalid" : null }); return value; } catch (e) { reasoningAudit.push({ identity, callCount, boundedRepair: callCount === 2, threw: true, failureCategory: safe(e) }); throw e; } finally { ordinals.set(identity, callCount); } } };
    const plugins = [new OfficialDisclosureResearchPlugin(new CninfoOfficialDisclosureClient()), new GdeltResearchPlugin(), new MiitIndustryResearchPlugin(), new GovCnIndustryResearchPlugin(), new EastmoneyIndustryResearchPlugin(), new CpcaIndustryResearchPlugin(), new AkshareIndustryResearchPlugin(new AkshareDataAdapter())].map((plugin) => wrap(plugin, log)); const composition = new IndustryAcquisitionComposition(plugins); const result = await runIndustryDeepResearch({ workflowRunId: "rhl-m3b3-test-041-live", handle, target: TARGET, reportRoot: reports, reasoningExecutor: exec, asOf: TARGET.asOf, maxSources: 24, maxEvidencePerModule: 2, acquisitionWave: async (request) => composition.acquire(request).then((out) => out.sources) });
    authoritativeWorkflow = structuredClone(result); const after = await readCanonicalV04Assets(kb); const validation = validateKnowledgeV04Objects(after.objects); const report = result.report ? await readFile(join(reports, result.report.outputPath + ".json"), "utf8").then(JSON.parse).catch(() => null) : null; const canonical = new Set(after.objects.map((x) => x.value.id)); const sectionList = sections(report, canonical); const matrix = moduleMatrix(authoritativeWorkflow, authoritativeWorkflow.evidence ?? []); const numericAssertions = sectionList.flatMap((x) => auditTest041Numbers(x.markdown, x.sourceRefs.length, x.claimRefs.length).assertions); const numericalAudit = { assertions: numericAssertions, unsupportedNumericCount: numericAssertions.filter((x) => x.classification === "unsupported").length }; const assembled = assembleTest041ProductQualityEvidence({ workflow: { status: authoritativeWorkflow.status, errors: (authoritativeWorkflow.errors ?? []).map(safe), diagnostics: (authoritativeWorkflow.diagnostics ?? []).map(safe), moduleCallCounts: authoritativeWorkflow.moduleCallCounts, modules: authoritativeWorkflow.modules, acquisitionWaves: authoritativeWorkflow.acquisitionWaves, gatewaySubmitCount: authoritativeWorkflow.gatewaySubmitCount, knowledgeBaseRevisionDelta: (authoritativeWorkflow.knowledgeBaseRevision ?? 0) - (before.revision ?? 0), proposalIds: authoritativeWorkflow.proposalIds, committedIds: authoritativeWorkflow.committedIds, sourceIds: authoritativeWorkflow.sourceIds, relationIds: authoritativeWorkflow.relationIds, claimIds: authoritativeWorkflow.claimIds }, provider: providerRows(log, authoritativeWorkflow.providerOutcomes ?? []), canonical: { validationStatus: validation.status, diagnosticCodes: validation.errors.map((x) => x.code), countsBefore: counts(before), countsAfter: counts(after), sourceToRawProvenanceComplete: after.objects.filter((x) => x.kind === "source").every((x) => (x.value.rawRefs ?? []).length > 0) }, report: report ? { sections: sectionList } : null, modules: matrix, reasoning: reasoningAudit, numericalAudit, dimensions: dimensions(sectionList, matrix), reportSnapshot: report ? { taskId, status: "PRODUCED", reportId: result.report?.reportId, reportType: report.reportType, sectionCount: sectionList.length, sections: sectionList } : { taskId, status: "NOT_PRODUCED", reason: "Workflow did not persist a trustworthy report" } });
    const out = { ...base, workflow: assembled.workflow, providerCoverage: assembled.providerCoverage, reasoningAudit, researchGapConvergence: authoritativeWorkflow.modules, canonical: assembled.canonical, reportSnapshot: assembled.reportSnapshot, moduleMatrix: matrix, dimensions: assembled.dimensions, numericalAudit, finalClassification: assembled.finalClassification }; await writeFile(evidencePath, JSON.stringify(out, null, 2) + "\n"); await writeFile(reportPath, JSON.stringify(assembled.reportSnapshot, null, 2) + "\n"); return out;
  } catch (error) { const out = authoritativeWorkflow ? { ...base, workflow: authoritativeWorkflow, providerCoverage: providerRows(log, authoritativeWorkflow.providerOutcomes ?? []), reasoningAudit, testHarnessError: safe(error), finalClassification: "PRODUCT_QUALITY_TEST_HARNESS_DEFECT" } : { ...base, workflow: { status: "failed", errors: [safe(error)] }, providerCoverage: providerRows(log, []), reasoningAudit, finalClassification: "PRODUCT_QUALITY_LIVE_INCONCLUSIVE" }; await writeFile(evidencePath, JSON.stringify(out, null, 2) + "\n"); await writeFile(reportPath, JSON.stringify({ taskId, status: "NOT_PRODUCED", reason: authoritativeWorkflow ? "TEST-only assembly failed after authoritative Workflow capture" : "Workflow failed before trustworthy report" }, null, 2) + "\n"); return out; } finally { await model?.dispose?.().catch?.(() => undefined); }
}
if (process.argv[1]?.endsWith("industry-product-quality-rerun-after-audit-harness-fix.ts")) main().then((out) => console.log(JSON.stringify(out, null, 2))).catch((error) => { console.error(safe(error)); process.exitCode = 1; });
