import test from 'node:test'
import assert from 'node:assert/strict'
import { classifyPortfolioAcceptance, semanticDuplicateAudit, TEST_029_SECTIONS, TEST_029_TARGET, TEST_029_PROVIDERS } from './industry-production-portfolio-real-pi-e2e-rerun-after-cli-unblock.ts'

const base:any={workflowStatus:'completed',realPi:true,moduleCount:8,sectionCount:16,gatewaySubmissions:1,revisionDelta:1,writerCommits:1,sourceRawProvenance:true,unsupportedNumericCount:0,replay:{liveModelCalls:0,liveProviderCalls:0,revisionDelta:0,duplicates:{entity:false,relation:false,claim:false,source:false}},privacy:true,usableSourceCount:2,providerCount:2,durableSemanticCount:1}
test('frozen target, providers and report contract are code-owned',()=>{assert.equal(TEST_029_TARGET.name,'PCB Manufacturing');assert.equal(TEST_029_TARGET.aliases[1],'印制电路板');assert.equal(TEST_029_TARGET.searchTerms.length,8);assert.deepEqual(TEST_029_PROVIDERS.slice(2,6),['miit-industry-research-acquisition','govcn-industry-research-acquisition','eastmoney-industry-research-acquisition','cpca-industry-research-acquisition']);assert.equal(TEST_029_SECTIONS.length,16)})
test('complete real portfolio is accepted',()=>assert.equal(classifyPortfolioAcceptance(base),'PORTFOLIO_E2E_ACCEPTED'))
test('one-source invariant-safe result is partial evidence accepted',()=>assert.equal(classifyPortfolioAcceptance({...base,usableSourceCount:1,providerCount:1}),'PORTFOLIO_E2E_PARTIAL_EVIDENCE_ACCEPTED'))
test('invariant failure is a production defect, external failure is inconclusive',()=>{assert.equal(classifyPortfolioAcceptance({...base,sectionCount:15}),'PORTFOLIO_E2E_PRODUCTION_DEFECT');assert.equal(classifyPortfolioAcceptance({...base,workflowStatus:'failed',externalFailure:true}),'PORTFOLIO_E2E_LIVE_INCONCLUSIVE')})
test('duplicate audit detects semantic additions and ignores identical replay',()=>{const a={objects:[{kind:'entity',value:{id:'entity:a',name:'PCB'}}]};assert.deepEqual(semanticDuplicateAudit(a,a),{entity:false,relation:false,claim:false,source:false});assert.equal(semanticDuplicateAudit(a,{objects:[...a.objects,{kind:'entity',value:{id:'entity:b',name:'Company'}}]}).entity,true)})
