import test from 'node:test'
import assert from 'node:assert/strict'
import { acceptedEvidenceCounts, classifyTest054, metricProviderName, summarizeMiitManagedParser, TEST054_PROVIDERS } from './industry-seven-provider-product-quality-after-docling-ready-assembly.ts'
const ready = () => ({ parserReady: true, workflowStatus: 'completed', providers: TEST054_PROVIDERS.map(provider => ({ provider, attempted: true })), definitionEvidence: true, modules: Array.from({ length: 8 }, () => ({ status: 'supported' })), waveCount: 1, gapIdsValid: true, provenance: { allDurableProposalsHaveSourceRaw: true }, proposalBundleCount: 1, gatewayCallCount: 1, changeSetCount: 1, writerInvocationCount: 1, canonicalValidation: 'valid', report: { generated: true, moduleCoverage: true } })
test('READY requires managed parser and authoritative Industry Definition evidence', () => { assert.equal(classifyTest054(ready()), 'INDUSTRY_PRODUCT_QUALITY_READY'); assert.equal(classifyTest054({ ...ready(), parserReady: false }), 'INDUSTRY_PRODUCT_QUALITY_WORKFLOW_DEFECT'); assert.equal(classifyTest054({ ...ready(), definitionEvidence: false, workflowStatus: 'blocked' }), 'INDUSTRY_PRODUCT_QUALITY_BLOCKED_BY_EVIDENCE') })
test('non-READY parser prevents Workflow invocation and provider accounting is exact', () => { assert.equal(classifyTest054({ ...ready(), parserReady: false, providers: [] }), 'INDUSTRY_PRODUCT_QUALITY_WORKFLOW_DEFECT'); assert.deepEqual(TEST054_PROVIDERS, [...new Set(TEST054_PROVIDERS)]); assert.equal(TEST054_PROVIDERS.length, 7) })
test('bounded provider failure is tolerated when mandatory evidence and invariants hold', () => { const x: any = ready(); x.providers[0].boundedFailureCategory = 'external_unavailable'; assert.equal(classifyTest054(x), 'INDUSTRY_PRODUCT_QUALITY_READY') })
test('Wave2 greater than one, invalid gap, or missing provenance is a workflow defect', () => { assert.equal(classifyTest054({ ...ready(), waveCount: 3 }), 'INDUSTRY_PRODUCT_QUALITY_WORKFLOW_DEFECT'); assert.equal(classifyTest054({ ...ready(), gapIdsValid: false }), 'INDUSTRY_PRODUCT_QUALITY_WORKFLOW_DEFECT'); assert.equal(classifyTest054({ ...ready(), provenance: { allDurableProposalsHaveSourceRaw: false } }), 'INDUSTRY_PRODUCT_QUALITY_WORKFLOW_DEFECT') })
test('proposal, Gateway, ChangeSet, and Writer cardinality violations are defects', () => { for (const key of ['proposalBundleCount','gatewayCallCount','changeSetCount','writerInvocationCount']) assert.equal(classifyTest054({ ...ready(), [key]: 2 }), 'INDUSTRY_PRODUCT_QUALITY_WORKFLOW_DEFECT') })
test('privacy evidence is bounded and model runtime is classified separately', () => { assert.equal(classifyTest054({ ...ready(), modelRuntimeUnavailable: true }), 'INDUSTRY_PRODUCT_QUALITY_BLOCKED_BY_MODEL_RUNTIME') })
test('MIIT parser telemetry isolates authoritative PCB anchors from ordinary MIIT pages', () => { const result = summarizeMiitManagedParser([{ provider: 'miit-industry-research-acquisition', phase: 'fetch', succeeded: true, candidateId: 'anchor-pdf', mediaType: 'application/pdf', byteCount: 120 }, { provider: 'miit-industry-research-acquisition', phase: 'fetch', succeeded: true, candidateId: 'anchor-html', mediaType: 'text/html', byteCount: 500 }, { provider: 'miit-industry-research-acquisition', phase: 'fetch', succeeded: true, candidateId: 'ordinary-1', mediaType: 'text/html', byteCount: 999 }, { provider: 'miit-industry-research-acquisition', phase: 'normalize', succeeded: true, candidateId: 'anchor-pdf', contentHash: 'hash-1', publisher: 'MIIT', contentLength: 42 }, { provider: 'miit-industry-research-acquisition', phase: 'normalize', succeeded: true, candidateId: 'anchor-html', contentHash: 'hash-2', publisher: 'MIIT', contentLength: 60 }, { provider: 'miit-industry-research-acquisition', phase: 'normalize', succeeded: true, candidateId: 'ordinary-1', contentHash: 'hash-3', publisher: 'MIIT', contentLength: 900 }], new Set(['anchor-pdf', 'anchor-html']), new Set(['anchor-pdf'])); assert.equal(result.pdfMediaType, true); assert.equal(result.byteCount, 620); assert.equal(result.normalizedCount, 2); assert.equal(result.normalizedCharacterCount, 102); assert.deepEqual(result.documents.map((x: any) => x.candidateId), ['anchor-pdf', 'anchor-html']); assert.equal(result.pcbIdentity, true) })
test('candidate provider IDs map to stable seven-provider metric names', () => { assert.equal(metricProviderName('miit'), 'miit-industry-research-acquisition'); assert.equal(metricProviderName('cpca'), 'cpca-industry-research-acquisition'); assert.equal(metricProviderName('cninfo'), 'official-disclosure-research-acquisition'); assert.equal(metricProviderName('unknown'), 'unknown') })
test('qualified evidence metrics count only Workflow-accepted evidence', () => { const counts = acceptedEvidenceCounts([{ source: { candidate: { provider: 'miit' } } }, { source: { candidate: { provider: 'miit' } } }, { source: { candidate: { provider: 'cpca' } } }, { source: { candidate: { provider: 'unknown' } } }]); assert.equal(counts.get('miit-industry-research-acquisition'), 2); assert.equal(counts.get('cpca-industry-research-acquisition'), 1); assert.equal(counts.has('unknown'), true) })
