import test from 'node:test'
import assert from 'node:assert/strict'
import { classifyAggregate, classifyEastmoneyTarget, finalModuleState, operationTopology, safeValidatorSummary } from './industry-live-pcb-module-stage-after-transport-fix.ts'
test('topology records immediate repair, Wave-2 rerun, mixed sequence, sentinel, and cap violation', () => { assert.deepEqual(operationTopology([{ module: 'industry_definition', repair: false, wave: 1 }, { module: 'industry_definition', repair: true, wave: 1 }], ['industry_module_analysis']).repairPairs, ['industry_definition']); assert.deepEqual(operationTopology([{ module: 'industry_definition', repair: false, wave: 1 }, { module: 'industry_definition', repair: false, wave: 2 }], ['industry_module_analysis']).reruns, ['industry_definition']); assert.equal(operationTopology([], ['industry_cross_module_synthesis']).classification, 'MODULE_STAGE_PASSED_AFTER_TRANSPORT_FIX'); assert.equal(operationTopology([], Array.from({ length: 25 }, () => 'industry_module_analysis')).classification, 'UNEXPECTED_MODULE_CALL_TOPOLOGY')
})
test('aggregate precedence is fail closed and distinguishes request evidence from acquisition', () => { const topology = operationTopology([], ['industry_module_analysis']); assert.equal(classifyAggregate({ transportRegression: true, topology }).classification, 'MODULE_TRANSPORT_REGRESSION'); assert.equal(classifyAggregate({ topology: { violations: ['x'] } }).classification, 'UNEXPECTED_MODULE_CALL_TOPOLOGY'); assert.equal(classifyAggregate({ topology: { synthesisRequested: true }, allModulesValid: true, industryDefinitionStatus: 'supported' }).classification, 'MODULE_STAGE_PASSED_AFTER_TRANSPORT_FIX'); assert.equal(classifyAggregate({ strongTargetNormalizedSourceCount: 2, industryDefinitionEvidenceEveryNonRepairAttempt: 0, topology }).classification, 'EVIDENCE_RELEVANCE_FILTER_BLOCKER_PROVEN'); assert.equal(classifyAggregate({ semanticContractFailure: true, topology }).classification, 'MODULE_SEMANTIC_CONTRACT_BLOCKER'); assert.equal(classifyAggregate({ industryDefinitionValidUnavailable: true, topology }).classification, 'INDUSTRY_DEFINITION_EVIDENCE_BREADTH_INSUFFICIENT'); assert.equal(classifyAggregate({ noUsableSources: true, topology }).classification, 'LIVE_ACQUISITION_UNAVAILABLE'); assert.equal(classifyAggregate({ topology }).classification, 'MIXED_POST_TRANSPORT_MODULE_BLOCKERS')
})
test('valid_unavailable is semantic, and positive pass requires all modules, definition, and synthesis request', () => { assert.equal(finalModuleState([{ validator: { parsed: true, authoritativeValidatorPassed: true, returnedStatus: 'unavailable' } }]), 'valid_unavailable'); assert.equal(classifyAggregate({ topology: { synthesisRequested: true }, allModulesValid: false, industryDefinitionStatus: 'supported' }).classification, 'MIXED_POST_TRANSPORT_MODULE_BLOCKERS'); assert.equal(classifyAggregate({ topology: { synthesisRequested: true }, allModulesValid: true, industryDefinitionStatus: 'partial' }).classification, 'MODULE_STAGE_PASSED_AFTER_TRANSPORT_FIX')
})
test('strong-target acquisition alone cannot prove a relevance blocker', () => { assert.equal(classifyAggregate({ strongTargetNormalizedSourceCount: 1, industryDefinitionEvidenceEveryNonRepairAttempt: 1, topology: operationTopology([], []) }).classification, 'MIXED_POST_TRANSPORT_MODULE_BLOCKERS'); assert.equal(classifyEastmoneyTarget('PCB'), 'strong_target_match'); assert.equal(classifyEastmoneyTarget('新能源设备'), 'non_target_context_match')
})
test('validator telemetry excludes semantic prose', () => { const s = safeValidatorSummary({ status: 'supported', analysis: 'PRIVATE_ANALYSIS', evidenceIds: [], proposals: [], gaps: [], reportMaterial: { markdown: 'PRIVATE_MARKDOWN', evidenceIds: [], proposalIds: [] } }, 'industry_definition', []); assert.equal(s.parsed, true); assert.equal(s.authoritativeValidatorPassed, false); assert.ok(!JSON.stringify(s).includes('PRIVATE_'))
})
