import test from 'node:test'
import assert from 'node:assert/strict'
import { acceptedEvidenceCounts, classifyTest054, metricProviderName, summarizeMiitManagedParser, TEST054_PROVIDERS } from './industry-seven-provider-product-quality-after-docling-ready-assembly.ts'
const ready = () => ({ parserReady: true, workflowStatus: 'completed', providers: TEST054_PROVIDERS.map(provider => ({ provider, attempted: true })), definitionEvidence: true, modules: Array.from({ length: 8 }, () => ({ status: 'supported' })), waveCount: 1, gapIdsValid: true, provenance: { allDurableProposalsHaveSourceRaw: true }, proposalBundleCount: 1, gatewayCallCount: 1, changeSetCount: 1, writerInvocationCount: 1, canonicalValidation: 'valid', report: { generated: true, moduleCoverage: true } })
test('READY requires managed parser and authoritative Industry Definition evidence', () => { assert.equal(classifyTest054(ready()), 'INDUSTRY_PRODUCT_QUALITY_READY'); assert.equal(classifyTest054({ ...ready(), parserReady: false }), 'INDUSTRY_PRODUCT_QUALITY_WORKFLOW_DEFECT'); assert.equal(classifyTest054({ ...ready(), definitionEvidence: false, workflowStatus: 'blocked' }), 'INDUSTRY_PRODUCT_QUALITY_BLOCKED_BY_EVIDENCE') })
test('non-READY parser prevents Workflow invocation and provider accounting is exact', () => { assert.equal(classifyTest054({ ...ready(), parserReady: false, providers: [] }), 'INDUSTRY_PRODUCT_QUALITY_WORKFLOW_DEFECT'); assert.deepEqual(TEST054_PROVIDERS, [...new Set(TEST054_PROVIDERS)]); assert.equal(TEST054_PROVIDERS.length, 7) })
test('bounded provider failure is tolerated when mandatory evidence and invariants hold', () => { const x: any = ready(); x.providers[0].boundedFailureCategory = 'external_unavailable'; assert.equal(classifyTest054(x), 'INDUSTRY_PRODUCT_QUALITY_READY') })
test('Wave2 greater than one, invalid gap, or missing provenance is a workflow defect', () => { assert.equal(classifyTest054({ ...ready(), waveCount: 3 }), 'INDUSTRY_PRODUCT_QUALITY_WORKFLOW_DEFECT'); assert.equal(classifyTest054({ ...ready(), gapIdsValid: false }), 'INDUSTRY_PRODUCT_QUALITY_WORKFLOW_DEFECT'); assert.equal(classifyTest054({ ...ready(), provenance: { allDurableProposalsHaveSourceRaw: false } }), 'INDUSTRY_PRODUCT_QUALITY_WORKFLOW_DEFECT') })
test('proposal, Gateway, ChangeSet, and Writer cardinality violations are defects', () => { for (const key of ['proposalBundleCount','gatewayCallCount','changeSetCount','writerInvocationCount']) assert.equal(classifyTest054({ ...ready(), [key]: 2 }), 'INDUSTRY_PRODUCT_QUALITY_WORKFLOW_DEFECT') })
test('privacy evidence is bounded and model runtime is classified separately', () => { assert.equal(classifyTest054({ ...ready(), modelRuntimeUnavailable: true }), 'INDUSTRY_PRODUCT_QUALITY_BLOCKED_BY_MODEL_RUNTIME') })
test('accepted evidence counts resolve candidate provider identity without overstating usable sources', () => { assert.equal(metricProviderName('miit'), 'miit-industry-research-acquisition'); assert.equal(metricProviderName('unknown-provider'), 'unknown-provider'); assert.deepEqual([...acceptedEvidenceCounts([{ source: { candidate: { provider: 'miit' } } }, { source: { candidate: { provider: 'miit' } } }, { source: { candidate: { provider: 'cpca' } } } ])], [['miit-industry-research-acquisition', 2], ['cpca-industry-research-acquisition', 1]]) })
test('MIIT managed parser telemetry counts only expected anchors and preserves PDF identity', () => { const ids = new Set(['miit-pdf', 'miit-html']); const pdf = new Set(['miit-pdf']); const log = [{ provider: 'miit-industry-research-acquisition', phase: 'fetch', candidateId: 'miit-pdf', succeeded: true, mediaType: 'application/pdf', byteCount: 10 }, { provider: 'miit-industry-research-acquisition', phase: 'fetch', candidateId: 'miit-html', succeeded: true, mediaType: 'text/html', byteCount: 5 }, { provider: 'miit-industry-research-acquisition', phase: 'normalize', candidateId: 'miit-pdf', succeeded: true, contentLength: 100, contentHash: 'pdf', publisher: 'MIIT' }, { provider: 'miit-industry-research-acquisition', phase: 'normalize', candidateId: 'miit-html', succeeded: true, contentLength: 50, contentHash: 'html', publisher: 'MIIT' }, { provider: 'miit-industry-research-acquisition', phase: 'fetch', candidateId: 'ordinary', succeeded: true, mediaType: 'text/html', byteCount: 99 }]; const out = summarizeMiitManagedParser(log, ids, pdf); assert.equal(out.fetchAttempted, true); assert.equal(out.fetchSucceeded, true); assert.equal(out.normalizedCount, 2); assert.equal(out.pdfMediaType, true); assert.equal(out.byteCount, 15); assert.equal(out.normalizedCharacterCount, 150); assert.equal(out.documents.length, 2) })
