import test from 'node:test'
import assert from 'node:assert/strict'
import { evaluateIndustryPiGate } from './industry-research-pi-e2e-gate.ts'
import { classifyEastmoneyTarget, graphProjectionHash, numericSupportAudit, relevantDurableRelation, semanticDuplicates, writerCommitCount, privacyCheck } from './industry-production-real-pi-e2e-rerun.ts'

test('Eastmoney target classification separates PCB from context boards', () => { assert.equal(classifyEastmoneyTarget('印制电路板'), 'strong_target_match'); assert.equal(classifyEastmoneyTarget('AI应用'), 'non_target_context_match') })
test('durable relation relevance requires evidence and allowed target relation', () => { const s = new Set(['source:pcb']); assert.equal(relevantDurableRelation({ type: 'upstream_of', sourceRef: 'entity:industry', targetRef: 'entity:x', sourceRefs: ['source:pcb'] }, 'entity:industry', s), true); assert.equal(relevantDurableRelation({ type: 'upstream_of', sourceRef: 'entity:industry', targetRef: 'entity:x', sourceRefs: ['source:ai'] }, 'entity:industry', s), false) })
test('empty source provenance is false and writer count is derived', () => { const empty = { objects: [] }; assert.equal(empty.objects.length > 0 && true, false); assert.equal(writerCommitCount(0, 0), 0); assert.equal(writerCommitCount(0, 1), 1) })
test('numeric structured claims require supported value and schema context', () => { const assets = { objects: [{ kind: 'claim', value: { structuredValue: { value: 48, unit: 'count', comparator: 'equals', period: '2026-09-12' }, provenance: [{ rawRef: 'raw:1' }] } }] }; assert.equal(numericSupportAudit(assets, new Map([['raw:1', 'constituents 48'] ])), 0); assert.equal(numericSupportAudit(assets, new Map()), 1) })
test('semantic duplicate detection sees changed IDs with same stable value', () => { const before = { objects: [{ kind: 'entity', value: { id: 'entity:a', type: 'industry', name: 'PCB' } }] }; const after = { objects: [{ kind: 'entity', value: { id: 'entity:b', type: 'industry', name: 'PCB' } }] }; assert.equal(semanticDuplicates(before, after).entity, true) })
test('graph projection hash is order independent', () => { const a = { nodes: [{ ref: 'b', entityType: 'company' }, { ref: 'a', entityType: 'industry', isRoot: true }], edges: [] }; const b = { nodes: [...a.nodes].reverse(), edges: [] }; assert.equal(graphProjectionHash(a), graphProjectionHash(b)) })
test('exact replay operation queue rejects unexpected or missing operations', async () => { const base: any = { executed: true, realPiReasoningExecutor: true, runtimeProvider: 'pi-coding-agent', operations: ['industry_research_design','industry_module_analysis','industry_cross_module_synthesis'], operationCounts: { industry_research_design: 1, industry_module_analysis: 8, industry_cross_module_synthesis: 1 }, status: 'completed', targetKind: 'industry', modules: ['industry_definition','market_size_growth','supply_demand_analysis','industry_chain_analysis','competitive_landscape','technology_evolution','company_mapping','risk_analysis'].map(module => ({ module, status: 'supported' })), industryDefinitionAvailable: true, gatewaySubmitCount: 1, firstRunRevisionDelta: 1, durableClaimCount: 1, chainRelation: true, companyExposure: true, industryRoot: true, productOrTechnology: true, company: true, sourceRawProvenance: true, unsupportedNumericObservationCount: 0, semanticTypingIntact: true, report: { persisted: true, reportType: 'industry_research', sectionCount: 16, hasResearchGaps: true }, graph: { profile: 'industry_context', canonicalRefs: true, root: true, productOrTechnology: true, company: true, requiredEdge: true }, replay: { outcome: 'no_changes', rootIdStable: true, duplicateEntities: false, duplicateRelations: false, duplicateClaims: false, duplicateSources: false, duplicateRaw: false, revisionDelta: 0, graphStable: true }, privacy: { serializedEvidenceSafe: true, sentinelAbsent: true, pathsRedacted: true, secretsAbsent: true } }; assert.equal(evaluateIndustryPiGate(base).pass, true); assert.equal(evaluateIndustryPiGate({ ...base, operationCounts: { ...base.operationCounts, industry_module_analysis: 33 } }).pass, false) })
test('privacy serialization and evaluator additional-failure downgrade remain strict', () => { const p = privacyCheck('{"ok":true}', 'sentinel', ['C:\\private']); assert.equal(p.serializedEvidenceSafe, true); const base: any = { executed: true, realPiReasoningExecutor: true, runtimeProvider: 'pi-coding-agent', operations: ['industry_research_design','industry_module_analysis','industry_cross_module_synthesis'], operationCounts: { industry_research_design: 1, industry_module_analysis: 8, industry_cross_module_synthesis: 1 }, status: 'completed', targetKind: 'industry', modules: ['industry_definition','market_size_growth','supply_demand_analysis','industry_chain_analysis','competitive_landscape','technology_evolution','company_mapping','risk_analysis'].map(module => ({ module, status: 'supported' })), industryDefinitionAvailable: true, gatewaySubmitCount: 1, firstRunRevisionDelta: 1, durableClaimCount: 1, chainRelation: true, companyExposure: true, industryRoot: true, productOrTechnology: true, company: true, sourceRawProvenance: true, unsupportedNumericObservationCount: 0, semanticTypingIntact: true, report: { persisted: true, reportType: 'industry_research', sectionCount: 16, hasResearchGaps: true }, graph: { profile: 'industry_context', canonicalRefs: true, root: true, productOrTechnology: true, company: true, requiredEdge: true }, replay: { outcome: 'no_changes', rootIdStable: true, duplicateEntities: false, duplicateRelations: false, duplicateClaims: false, duplicateSources: false, duplicateRaw: false, revisionDelta: 0, graphStable: true }, privacy: { serializedEvidenceSafe: true, sentinelAbsent: true, pathsRedacted: true, secretsAbsent: true } }; assert.equal(evaluateIndustryPiGate(base).classification, 'EXECUTED / PASS GATE'); assert.equal(evaluateIndustryPiGate({ ...base, chainRelation: false }).classification, 'REAL_MODEL_CONTRACT_BLOCKED') })
