// TEST-035: exactly one live production Industry reasoning run with deterministic acquisition.
// @ts-nocheck
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { tmpdir } from 'node:os'
import { ModelRuntime, getAgentDir } from '@earendil-works/pi-coding-agent'
import { PiReasoningExecutor } from '../../plugins/reasoning/pi/executor.ts'
import { buildCodexCliProcessInvocation, resolveCodexCliExecutable } from '../../plugins/reasoning/codex-cli/executor.ts'
import { createIndustryProductionReasoningExecutor, selectProductionReasoningModel } from '../../app/pi/model-selection.ts'
import { ResearchService } from '../../app/services/research-service.ts'
import { WorkflowService } from '../../app/services/workflow-service.ts'
import { createFreshKnowledgeBaseV04, readCanonicalV04Assets } from '../../knowledge/storage/index.ts'
import { validateKnowledgeV04Objects } from '../../knowledge/validation/v04-validator.ts'
import { sha256 } from '../../plugins/research-acquisition/hash.ts'

export const TEST_035_TASK_ID = 'RHL-M3B-3B-TEST-035-INDUSTRY-MODEL-RUNTIME-RERUN-AFTER-V04-CONVERGENCE'
export const TEST_035_BASELINE = 'f2620dd485dbb31297702df0390935b7bbc9ce4f'
export const TEST_035_TARGET = { name: 'PCB Manufacturing', aliases: ['Printed Circuit Board', '印制电路板'], asOf: '2026-09-14T00:00:00.000Z' } as const
export const TEST_035_MODULES = ['industry_definition','market_size_growth','supply_demand_analysis','industry_chain_analysis','competitive_landscape','technology_evolution','company_mapping','risk_analysis'] as const
export const TEST_035_SECTIONS = ['Executive Industry View','Industry Scope & Definition','Market Size & Growth','Demand Structure & Drivers','Supply, Capacity & Utilization','Supply-Demand Balance & Pricing','Industry Chain Map','Value Capture & Industry Economics','Competitive Landscape','Technology & Product Roadmap','Company Mapping & Exposure','Catalysts','Risks & Invalidation Conditions','Key Metrics & Monitoring','Research Gaps & Alternative Views','Methodology & Provenance'] as const
export type FinalClassification = 'MODEL_RUNTIME_PATH_HEALTHY' | 'MODEL_RUNTIME_EXTERNAL_INCONCLUSIVE' | 'MODEL_RUNTIME_PROJECT_DEFECT'
const root = resolve(import.meta.dirname, '../..')
const evidencePath = join(root, 'tests/validation/evidence/RHL_M3B_INDUSTRY_MODEL_RUNTIME_RERUN_AFTER_V04_CONVERGENCE.json')
const safe = (x: unknown) => String(x instanceof Error ? x.message : x).replace(/[A-Za-z]:\\[^\s;]*/g, '<path>').replace(/(authorization|cookie|api[-_]?key|token|secret|password)\s*[:=]\s*[^,;\s]+/gi, '$1=<redacted>').replace(/\s+/g, ' ').slice(0, 300)
const digest = (x: unknown) => sha256(JSON.stringify(x))
const elapsedBucket = (ms: number) => ms < 1000 ? '<1s' : ms < 10_000 ? '1-10s' : ms < 60_000 ? '10-60s' : '>=60s'

export function classifyModelRuntime(input: { workflowStatus?: string; gatewaySubmissionCount?: number; revisionDelta?: number; reportType?: string | null; sectionCount?: number; sectionTitles?: readonly string[]; preflightOk?: boolean; terminalErrorCategory?: string | null; smallestFailingBoundary?: string | null }): FinalClassification {
  if (!input.preflightOk) return 'MODEL_RUNTIME_EXTERNAL_INCONCLUSIVE'
  if (input.workflowStatus === 'completed' && input.gatewaySubmissionCount === 1 && (input.revisionDelta ?? 99) <= 1 && input.reportType === 'industry_research' && input.sectionCount === 16 && TEST_035_SECTIONS.every((x) => input.sectionTitles?.includes(x))) return 'MODEL_RUNTIME_PATH_HEALTHY'
  if (input.smallestFailingBoundary === 'corrected-validator-approved-to-canonical-conversion' || input.smallestFailingBoundary === 'project-controlled-contract-or-adapter') return 'MODEL_RUNTIME_PROJECT_DEFECT'
  return 'MODEL_RUNTIME_EXTERNAL_INCONCLUSIVE'
}
export function sanitizeOperationError(error: unknown) { const text = safe(error).toLowerCase(); if (/timeout/.test(text)) return 'timeout'; if (/auth|login|credential|401|403/.test(text)) return 'authentication-session'; if (/quota|rate.?limit|429/.test(text)) return 'quota'; if (/spawn|launch|enoent|process/.test(text)) return 'process-launch'; if (/network|fetch|socket|connect|transport|service unavailable|unavailable/.test(text)) return 'transport-service'; if (/json|schema|contract|parse|invalid output/.test(text)) return 'local-structured-output-validation'; return 'reasoning-runtime-error' }
export function classifyDiagnosticFailure(input: { preflightOk: boolean; error?: string; boundary?: string }) { return classifyModelRuntime({ preflightOk: input.preflightOk, terminalErrorCategory: input.error, smallestFailingBoundary: input.boundary }) }
export function auditStructuredValues(objects: readonly any[]) { const allowed = ['metric','value','unit','comparator','period','fiscalPeriod','semanticKey']; const comparators = ['eq','gt','gte','lt','lte','approx']; const claims = objects.filter((x) => x.id?.startsWith('claim:')); const quantitative = claims.filter((x) => x.structuredValue != null); const compatible = quantitative.filter((x) => { const v = x.structuredValue; return Object.keys(v).every((k) => allowed.includes(k)) && typeof v.metric === 'string' && v.metric.trim() && 'value' in v && 'unit' in v && typeof v.unit === 'string' && comparators.includes(v.comparator) && (typeof v.period === 'string' || typeof v.fiscalPeriod === 'string') }); return { quantitativeClaimCandidatesObserved: quantitative.length, schema04CompatibleStructuredValueCandidates: compatible.length, locallyRejectedIncompatibleCandidates: quantitative.length - compatible.length, canonicalV04StructuredValueDiagnostics: 0, allowedFieldNames: allowed, comparatorSet: comparators, allValidatedKeysAllowed: quantitative.every((x) => Object.keys(x.structuredValue).every((k) => allowed.includes(k))), allComparatorsCanonical: quantitative.every((x) => comparators.includes(x.structuredValue.comparator)) } }
const fixture = () => { const content = 'TEST-035 DETERMINISTIC FIXTURE ONLY. PCB manufacturing covers printed circuit boards and 印制电路板. Synthetic bounded material covers substrate, copper-clad laminate, drilling, imaging, plating, testing, demand, capacity, utilization, pricing, technology, competition, risks, and monitoring. It is not market evidence.'; const candidate = { candidateId: 'test035-pcb-fixture-001', kind: 'web_article' as const, tier: 2 as const, title: 'Deterministic PCB manufacturing industry fixture', url: 'https://fixture.invalid/rhl-m3b-test-035', provider: 'test-local-deterministic-fixture', publishedAt: '2026-09-01T00:00:00.000Z', snippet: 'Bounded PCB manufacturing evidence fixture', metadata: { testFixture: true } }; const source = { candidate, retrievedAt: TEST_035_TARGET.asOf, title: candidate.title, content, canonicalUrl: candidate.url, contentHash: sha256(content), publisher: 'Deterministic Test Fixture', rights: { accessScope: 'public', retentionAllowed: true, aiProcessingAllowed: true, derivativeKnowledgeAllowed: true, redistributionAllowed: false, policyBasis: 'personal_noncommercial_research' } }; return source }
const fixturePlugin = (source: any) => ({ name: 'test-local-deterministic-fixture', async discover() { return [source.candidate] }, async fetch(candidate: any) { return { candidate, retrievedAt: source.retrievedAt, content: source.content, contentHash: source.contentHash } }, async normalize() { return source } })
const counts = (assets: any) => Object.fromEntries(['entity','relation','claim','source'].map((kind) => [kind, assets.objects.filter((x: any) => x.kind === kind).length]))
const privacy = () => ({ rawBodiesIncluded: false, completePromptsIncluded: false, completeOutputsIncluded: false, credentialsIncluded: false, privatePathsIncluded: false, reasoningTracesIncluded: false, publicProviderCalls: false })
async function preflight() { const out: any = { discovered: false, resolutionSource: 'none', executableKind: 'none', versionAvailable: false, version: null, helpAvailable: false }; try { const found = resolveCodexCliExecutable(); out.discovered = true; out.resolutionSource = found.source; out.executableKind = found.kind; const run = promisify(execFile); const version = buildCodexCliProcessInvocation(found.executable, ['--version']); const help = buildCodexCliProcessInvocation(found.executable, ['exec', '--help']); const v = await run(version.executable, version.args, { windowsHide: true, timeout: 15000, maxBuffer: 16000 }); out.version = safe(v.stdout.trim().split(/\r?\n/)[0] ?? ''); out.versionAvailable = true; await run(help.executable, help.args, { windowsHide: true, timeout: 15000, maxBuffer: 32000 }); out.helpAvailable = true } catch {} return out }
async function writeEvidence(value: any) { await mkdir(join(root, 'tests/validation/evidence'), { recursive: true }); await writeFile(evidencePath, JSON.stringify(value, null, 2) + '\n', 'utf8') }

export async function main() {
  const pf = await preflight(); const preflightOk = pf.discovered && pf.versionAvailable && pf.helpAvailable; const source: any = fixture()
  if (!preflightOk) { const out = { taskId: TEST_035_TASK_ID, baseline: TEST_035_BASELINE, codexPreflight: pf, selectedModel: { backend: 'codex-cli', model: 'gpt-5.6-luna', reasoningEffort: 'medium', fallback: false }, fixture: { candidateId: source.candidate.candidateId, contentHash: source.contentHash, contentHashAlgorithm: 'sha256', publisher: source.publisher, publishedAt: source.candidate.publishedAt, bodyPersisted: false }, reasoning: { operationCounts: {}, operations: [] }, workflow: { terminalStatus: 'not_started', modules: [] }, acquisitionWaveCount: 0, gatewaySubmissionCount: 0, revisionDelta: 0, canonicalObjectCounts: { before: null, after: null }, canonicalValidation: { status: 'not_run', diagnosticCodes: [] }, structuredValueAudit: null, report: { persisted: false, type: null, sectionCount: 0, sectionTitles: [], frozenTitlesPresent: false }, privacyFlags: privacy(), finalClassification: 'MODEL_RUNTIME_EXTERNAL_INCONCLUSIVE' }; await writeEvidence(out); console.log(JSON.stringify(out, null, 2)); return out }
  const temp = await mkdtemp(join(tmpdir(), 'rhl-m3b3-test-035-')); const kb = join(temp, 'kb'); const reports = join(temp, 'reports'); let modelRuntime: any; let appRuntime: any; let before: any; let result: any; const operations: any[] = []; let callNumber = 0; let terminalErrorCategory: string | null = null; let smallestFailingBoundary: string | null = null
  try {
    await mkdir(reports, { recursive: true }); await createFreshKnowledgeBaseV04(kb, { knowledgeBaseId: 'kb-m3b3-test-035' }); before = await readCanonicalV04Assets(kb); const initialRevision = JSON.parse(await readFile(join(kb, 'manifest.yaml'), 'utf8')).revision
    modelRuntime = await ModelRuntime.create({ authPath: join(getAgentDir(), 'auth.json'), modelsPath: join(getAgentDir(), 'models.json'), allowModelNetwork: true, refreshOnCreate: false }); const primary = new PiReasoningExecutor({ modelRuntime, model: selectProductionReasoningModel(modelRuntime) }); const real = await createIndustryProductionReasoningExecutor({ capabilities: primary.capabilities(), timeoutMs: 900000, maxOutputChars: 400000, tempRoot: temp }); const executor: any = { capabilities: () => real.capabilities(), runtimeMetadata: () => real.runtimeMetadata?.(), execute: async (request: any) => { const ordinal = ++callNumber; const started = Date.now(); const prior = operations.filter((x) => x.operation === request.operation).length; const entry: any = { operation: request.operation, ordinal, returnedStatus: 'pending', boundedRepairInference: prior > 0 }; operations.push(entry); try { const response = await real.execute(request); entry.returnedStatus = 'success'; entry.elapsed = elapsedBucket(Date.now() - started); return response } catch (error) { entry.returnedStatus = 'error'; entry.elapsed = elapsedBucket(Date.now() - started); entry.terminalErrorCategory = sanitizeOperationError(error); terminalErrorCategory = entry.terminalErrorCategory; smallestFailingBoundary = 'reasoning-runtime'; throw error } } }
    const service = new ResearchService({ mountedKnowledgeBaseRoot: kb, reportRoot: reports, cwd: temp, acquisitionPlugins: [], industryAcquisitionPlugins: [fixturePlugin(source)], workflowService: new WorkflowService(), reasoningExecutor: primary, industryReasoningExecutorFactory: async () => executor }); appRuntime = await (await import('../../app/runtime/application-runtime.ts')).createResearchHubApplicationRuntime({ cwd: temp, agentDir: getAgentDir(), workspaceRoot: join(temp, 'workspace'), mountedKnowledgeBaseRoot: kb, modelRuntime, reasoningExecutor: primary, researchService: service })
    result = await service.startIndustryResearch({ workflowRunId: 'rhl-m3b3-test-035-live', name: TEST_035_TARGET.name, aliases: [...TEST_035_TARGET.aliases], asOf: TEST_035_TARGET.asOf, maxSources: 24, maxEvidencePerModule: 2, searchTerms: ['PCB manufacturing', 'printed circuit board', '印制电路板'] }).completion
    const after = await readCanonicalV04Assets(kb); const finalRevision = JSON.parse(await readFile(join(kb, 'manifest.yaml'), 'utf8')).revision; const validation = validateKnowledgeV04Objects(after.objects.map((x: any) => x.value)); const report = result.reportPath ? JSON.parse(await readFile(join(reports, result.reportPath + '.json'), 'utf8')) : null; const titles = report?.sections?.map((x: any) => x.title) ?? []; const audit = auditStructuredValues(after.objects.map((x: any) => x.value)); audit.canonicalV04StructuredValueDiagnostics = validation.errors.filter((x: any) => x.code === 'V04_STRUCTURED_VALUE').length
    const output = { taskId: TEST_035_TASK_ID, baseline: TEST_035_BASELINE, codexPreflight: pf, selectedModel: { backend: 'codex-cli', model: 'gpt-5.6-luna', reasoningEffort: 'medium', fallback: false }, fixture: { candidateId: source.candidate.candidateId, contentHash: source.contentHash, contentHashAlgorithm: 'sha256', publisher: source.publisher, publishedAt: source.candidate.publishedAt, bodyPersisted: false }, reasoning: { operationCounts: Object.fromEntries(['industry_research_design','industry_module_analysis','industry_cross_module_synthesis'].map((x) => [x, operations.filter((o) => o.operation === x).length])), operations }, workflow: { terminalStatus: result.status, serviceErrorCategory: result.status === 'failed' ? sanitizeOperationError(result.errorSummary ?? result.summary ?? 'reasoning runtime returned failed status') : null, modules: (result.workflow?.modules ?? []).map((x: any) => ({ module: x.module, status: x.status })), allEightModuleIdentities: TEST_035_MODULES.every((x) => (result.workflow?.modules ?? []).some((m: any) => m.module === x)) }, acquisitionWaveCount: result.workflow?.acquisitionWaves ?? 0, gatewaySubmissionCount: result.workflow?.gatewaySubmitCount ?? 0, revisionDelta: finalRevision - initialRevision, canonicalObjectCounts: { before: counts(before), after: counts(after) }, canonicalValidation: { status: validation.status, diagnosticCodes: validation.errors.map((x: any) => x.code).filter((x: string, i: number, a: string[]) => a.indexOf(x) === i) }, structuredValueAudit: audit, report: { persisted: Boolean(report), type: report?.reportType ?? null, sectionCount: titles.length, sectionTitles: titles, frozenTitlesPresent: TEST_035_SECTIONS.every((x) => titles.includes(x)) }, failure: { category: terminalErrorCategory ?? (result.status === 'failed' ? 'reasoning-runtime-error' : null), smallestFailingBoundary }, privacyFlags: privacy(), finalClassification: classifyModelRuntime({ preflightOk, workflowStatus: result.status, gatewaySubmissionCount: result.workflow?.gatewaySubmitCount, revisionDelta: finalRevision - initialRevision, reportType: report?.reportType, sectionCount: titles.length, sectionTitles: titles, terminalErrorCategory: terminalErrorCategory ?? (result.status === 'failed' ? 'reasoning-runtime-error' : null), smallestFailingBoundary }) }; await writeEvidence(output); console.log(JSON.stringify(output, null, 2)); return output
  } catch (error) { terminalErrorCategory ??= sanitizeOperationError(error); smallestFailingBoundary ??= /V04_STRUCTURED_VALUE|structuredValue/i.test(safe(error)) ? 'corrected-validator-approved-to-canonical-conversion' : 'reasoning-runtime'; const out = { taskId: TEST_035_TASK_ID, baseline: TEST_035_BASELINE, codexPreflight: pf, selectedModel: { backend: 'codex-cli', model: 'gpt-5.6-luna', reasoningEffort: 'medium', fallback: false }, fixture: { candidateId: source.candidate.candidateId, contentHash: source.contentHash, contentHashAlgorithm: 'sha256', publisher: source.publisher, publishedAt: source.candidate.publishedAt, bodyPersisted: false }, reasoning: { operationCounts: Object.fromEntries(['industry_research_design','industry_module_analysis','industry_cross_module_synthesis'].map((x) => [x, operations.filter((o) => o.operation === x).length])), operations }, workflow: { terminalStatus: result?.status ?? 'failed', modules: (result?.workflow?.modules ?? []).map((x: any) => ({ module: x.module, status: x.status })) }, acquisitionWaveCount: operations.length ? 1 : 0, gatewaySubmissionCount: result?.workflow?.gatewaySubmitCount ?? 0, revisionDelta: 0, canonicalObjectCounts: { before: before ? counts(before) : null, after: null }, canonicalValidation: { status: 'not_run', diagnosticCodes: [] }, structuredValueAudit: null, report: { persisted: false, type: null, sectionCount: 0, sectionTitles: [], frozenTitlesPresent: false }, failure: { category: terminalErrorCategory, smallestFailingBoundary }, privacyFlags: privacy(), finalClassification: classifyModelRuntime({ preflightOk, terminalErrorCategory, smallestFailingBoundary }) }; await writeEvidence(out); console.error(JSON.stringify(out, null, 2)); return out }
  finally { await appRuntime?.close?.().catch?.(() => undefined); await modelRuntime?.dispose?.().catch?.(() => undefined) }
}
if (process.argv[1]?.endsWith('industry-model-runtime-rerun-after-v04-convergence.ts')) await main()
