import { createHash } from 'node:crypto'
import { access, mkdtemp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import type { Api, Model } from '@earendil-works/pi-ai'
import { getAgentDir, ModelRuntime } from '@earendil-works/pi-coding-agent'
import { createResearchHubApplicationRuntime, type ResearchHubApplicationRuntime } from '../../app/runtime/application-runtime.ts'
import { PRIMARY_PRODUCTION_REASONING_MODEL, selectProductionReasoningModel } from '../../app/pi/model-selection.ts'
import { ResearchHubRuntimeServer } from '../../app/runtime/server.ts'
import { PiReasoningExecutor } from '../../plugins/reasoning/pi/executor.ts'
import type { ReasoningCapabilities, ReasoningExecutor, ReasoningRequest, ReasoningResult } from '../../plugins/reasoning/contracts.ts'
import { DoclingDocumentParser } from '../../plugins/document/parsers/docling/parser.ts'
import { DocumentInputResolver } from '../../plugins/document/input-resolver.ts'
import { KnowledgeBaseRegistry } from '../../knowledge/registry/registry.ts'
import { KnowledgeBaseLoaderV03 } from '../../knowledge/storage/loader.ts'
import { validateKnowledgeBaseV03 } from '../../knowledge/validation/v03-validator.ts'
import { getRaw, verifyRaw } from '../../knowledge/raw/raw-archive.ts'
import type { KnowledgeAssetCollectionV03 } from '../../knowledge/storage/v03-types.ts'
import { canonicalRefHash, graphStructuralSnapshot, setEvidenceClassification, validateReviewApiListAndDetail, verifyCanonicalPersistence, verifyGraphPersistence, verifyRawPersistence, verifyReviewPersistence, verifyRuntimeInstanceIndependence, type CanonicalSnapshotInput, type GraphSnapshotInput, type RawSnapshotInput, type ReviewApiEvidence } from './restart-review-persistence-contract.ts'

const repoRoot = resolve(import.meta.dirname, '../..')
const evidenceDir = resolve(repoRoot, 'tests/validation/evidence')
const evidencePath = join(evidenceDir, 'rhl-restart-review-persistence-001.json')
const summaryPath = join(evidenceDir, 'RHL_RESTART_REVIEW_PERSISTENCE_001_SUMMARY.md')
const taskId = 'RHL-VALIDATE-RESTART-REVIEW-PERSISTENCE-001'
const expectedBaseline = '9d52645c9492362afbfa2eb8cfce3202f0a0eb44'
const workflowTimeoutMs = 15 * 60 * 1_000
const pollIntervalMs = 1_000
const capabilities: ReasoningCapabilities = { maxContextTokens: 128_000, maxOutputTokens: 16_384, structuredOutputSupport: true, maxConcurrency: 4 }

type Dict = Record<string, unknown>
type Classification = 'SUCCESS' | 'PRODUCT_DEFECT' | 'ENVIRONMENT_BLOCKED' | 'VALIDATION_HARNESS_DEFECT'
type Stage = { startedAt: string; completedAt?: string; durationMs?: number; status: 'running' | 'passed' | 'failed'; error?: string }
class ValidationFailure extends Error { constructor(readonly classification: Classification, readonly stage: string, message: string) { super(message); this.name = 'ValidationFailure' } }
function now(): string { return new Date().toISOString() }
function isDict(value: unknown): value is Dict { return typeof value === 'object' && value !== null && !Array.isArray(value) }
function assertCondition(condition: unknown, message: string): asserts condition { if (!condition) throw new Error(message) }
function productCondition(condition: unknown, stage: string, message: string): asserts condition { if (!condition) throw new ValidationFailure('PRODUCT_DEFECT', stage, message) }
function stable(value: unknown): string { if (Array.isArray(value)) return `[${value.map(stable).join(',')}]`; if (isDict(value)) return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${stable(value[key])}`).join(',')}}`; return JSON.stringify(value) }
function sha256(value: Uint8Array | string): string { return createHash('sha256').update(value).digest('hex') }
function errorText(error: unknown): string { return error instanceof Error ? error.message : String(error) }
function safeError(error: unknown): string { return errorText(error).replace(/\b(?:sk|ghp)_[A-Za-z0-9._-]+\b/gi, '[redacted]').replace(/\b(?:api[_-]?key|token|password|secret|authorization)\s*[:=]?\s*[^\s,;]+/gi, '[redacted]').replace(/(?:[A-Za-z]:[\\/]|\\\\)[^\s"']+/g, '[path]').replace(/\s+/g, ' ').slice(0, 500) }
async function stage<T>(stages: Record<string, Stage>, name: string, action: () => Promise<T>): Promise<T> { const startedAt = now(); stages[name] = { startedAt, status: 'running' }; try { const result = await action(); const completedAt = now(); stages[name] = { startedAt, completedAt, durationMs: Date.parse(completedAt) - Date.parse(startedAt), status: 'passed' }; return result } catch (error) { const completedAt = now(); stages[name] = { startedAt, completedAt, durationMs: Date.parse(completedAt) - Date.parse(startedAt), status: 'failed', error: safeError(error) }; throw error } }
async function writeEvidence(value: Dict): Promise<void> { await mkdir(evidenceDir, { recursive: true }); await writeFile(evidencePath, JSON.stringify(value, null, 2) + '\n', 'utf8') }

function pdfBytes(): Uint8Array {
  const lines = ['RHL Production E2E Validation Report', 'Validation Company operates in Validation Industry.', 'Validation Company offers Validation Product.', 'Validation Company develops Validation Technology.', 'Validation Company has revenue exposure to Validation Industry.']
  const escapePdf = (value: string): string => value.replaceAll('\\', '\\\\').replaceAll('(', '\\(').replaceAll(')', '\\)')
  const stream = ['BT', '/F1 12 Tf', '72 740 Td', ...lines.flatMap((line, index) => [`(${escapePdf(line)}) Tj`, index < lines.length - 1 ? '0 -28 Td' : '']), 'ET'].filter(Boolean).join('\n') + '\n'
  const objects = ['<< /Type /Catalog /Pages 2 0 R >>', '<< /Type /Pages /Kids [3 0 R] /Count 1 >>', '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>', `<< /Length ${Buffer.byteLength(stream, 'binary')} >>\nstream\n${stream}endstream`, '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>']
  let content = '%PDF-1.4\n%RHL\n'; const offsets = [0]
  for (let index = 0; index < objects.length; index += 1) { offsets.push(Buffer.byteLength(content, 'binary')); content += `${index + 1} 0 obj\n${objects[index]}\nendobj\n` }
  const xrefOffset = Buffer.byteLength(content, 'binary'); content += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${offsets.slice(1).map((offset) => `${String(offset).padStart(10, '0')} 00000 n `).join('\n')}\ntrailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`
  return Uint8Array.from(Buffer.from(content, 'binary'))
}
async function createPersistentKnowledgeBase(root: string, knowledgeBaseId: string): Promise<void> { for (const directory of ['raw', 'registry', 'theme-groups', 'entities', 'relations', 'claims', 'sources', 'modules', 'logs/ingestion']) await mkdir(join(root, directory), { recursive: true }); await writeFile(join(root, 'manifest.yaml'), JSON.stringify({ knowledgeBaseId, name: 'Restart Review Persistence Validation KB', schemaVersion: '0.3', storageFormatVersion: '1', revision: 0, status: 'active', createdAt: '2026-09-07T00:00:00.000Z', updatedAt: '2026-09-07T00:00:00.000Z' }) + '\n'); await writeFile(join(root, 'registry', 'assets.yaml'), '{}\n'); await writeFile(join(root, 'registry', 'raw.yaml'), '{}\n') }
function collectionCounts(assets: KnowledgeAssetCollectionV03): Dict { return { themeGroups: assets.themeGroups.length, entities: assets.entities.length, relations: assets.relations.length, claims: assets.claims.length, sources: assets.sources.length, modules: assets.modules.length } }
function canonicalRefs(assets: KnowledgeAssetCollectionV03): string[] { const values = [...assets.themeGroups, ...assets.entities, ...assets.relations, ...assets.claims, ...assets.sources, ...assets.modules]; return values.map((asset) => { const value = asset.value as unknown as Dict; assertCondition(typeof value.id === 'string' && value.id !== '', `Canonical ${asset.kind} is missing id`); return value.id as string }).sort((left, right) => left.localeCompare(right)) }
async function canonicalSnapshot(root: string): Promise<CanonicalSnapshotInput & { readonly assets: KnowledgeAssetCollectionV03 }> { const registry = new KnowledgeBaseRegistry(); const handle = await registry.mount(root); const assets = await new KnowledgeBaseLoaderV03(registry).load(handle); return { revision: handle.revision, counts: collectionCounts(assets), refs: canonicalRefs(assets), assets } }

class RecordingExecutor implements ReasoningExecutor {
  readonly calls: Dict[] = []
  constructor(private readonly inner: PiReasoningExecutor) {}
  capabilities(): ReasoningCapabilities { return this.inner.capabilities() }
  async execute(request: ReasoningRequest, signal?: AbortSignal): Promise<ReasoningResult> { const startedAt = Date.now(); const entry: Dict = { operation: request.operation, status: 'running' }; this.calls.push(entry); try { const result = await this.inner.execute(request, signal); entry.status = 'passed'; entry.durationMs = Date.now() - startedAt; return result } catch (error) { entry.status = 'failed'; entry.durationMs = Date.now() - startedAt; entry.error = safeError(error); throw error } }
}
type HttpResult = { readonly status: number; readonly headers: Headers; readonly body: unknown }
async function requestJson(origin: string, path: string, init: RequestInit = {}): Promise<HttpResult> { const response = await fetch(`${origin}${path}`, { ...init, headers: { Origin: origin, ...(init.headers ?? {}) } }); const text = await response.text(); let body: unknown = text; try { body = text === '' ? undefined : JSON.parse(text) } catch {} return { status: response.status, headers: response.headers, body } }
function objectBody(response: HttpResult): Dict { assertCondition(isDict(response.body), `Expected JSON object from HTTP ${response.status}`); return response.body }
async function pollWorkflow(origin: string, runId: string): Promise<Dict> { const deadline = Date.now() + workflowTimeoutMs; while (Date.now() < deadline) { const response = await requestJson(origin, `/api/workflows/${encodeURIComponent(runId)}`); assertCondition(response.status === 200, `Workflow polling failed with HTTP ${response.status}`); const body = objectBody(response); if (['completed', 'completed_with_review', 'failed', 'cancelled', 'blocked'].includes(String(body.status))) return body; await new Promise((resolvePromise) => setTimeout(resolvePromise, pollIntervalMs)) } throw new Error('Workflow polling timed out') }
async function upload(origin: string, token: string, bytes: Uint8Array): Promise<Dict> { const form = new FormData(); form.append('file', new Blob([bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer], { type: 'application/pdf' }), 'rhl-restart-review-persistence-001.pdf'); const response = await requestJson(origin, '/api/attachments', { method: 'POST', body: form, headers: { 'X-ResearchHub-Runtime-Token': token } }); assertCondition(response.status === 201, `Attachment upload failed with HTTP ${response.status}`); const body = objectBody(response); assertCondition(isDict(body.attachment), 'Attachment DTO missing'); return body.attachment }
async function startProduction(origin: string, token: string, attachmentId: string): Promise<Dict> { const response = await requestJson(origin, '/api/production/ingest', { method: 'POST', body: JSON.stringify({ attachmentId, sourceMetadata: { title: 'RHL Restart Review Persistence Validation', institution: 'ResearchHub Validation' } }), headers: { 'Content-Type': 'application/json', 'X-ResearchHub-Runtime-Token': token } }); assertCondition(response.status === 202, `Production start failed with HTTP ${response.status}`); const body = objectBody(response); assertCondition(typeof body.runId === 'string' && isDict(body.workflow), 'Production start did not return runId and workflow'); return body }
function graphInput(value: Dict): GraphSnapshotInput { const nodes = Array.isArray(value.nodes) ? value.nodes.filter(isDict).map((node) => node.ref).filter((ref): ref is string => typeof ref === 'string') : []; const edges = Array.isArray(value.edges) ? value.edges.filter(isDict).map((edge) => ({ ref: edge.ref, sourceRef: edge.sourceRef, targetRef: edge.targetRef })).filter((edge): edge is GraphSnapshotInput['edges'][number] => typeof edge.ref === 'string' && typeof edge.sourceRef === 'string' && typeof edge.targetRef === 'string') : []; assertCondition(nodes.length > 0 && edges.length > 0, 'Graph projection is empty or malformed'); return { rootRef: String(value.rootRef ?? ''), nodes, edges } }
async function readGraph(origin: string, rootRef: string, depth: 1 | 2): Promise<GraphSnapshotInput> { const response = await requestJson(origin, `/api/knowledge/graph?rootRef=${encodeURIComponent(rootRef)}&depth=${depth}`); productCondition(response.status === 200, `graph_depth_${depth}`, `Graph API failed with HTTP ${response.status}`); return graphInput(objectBody(response)) }
function reviewMetadata(value: ReviewApiEvidence): Dict { return { reviewCaseId: value.reviewCaseId, producerRunId: value.producerRunId, total: value.total, caseIds: value.caseIds, category: value.category, actionability: value.actionability, origin: value.origin, proposalKind: value.proposalKind, semanticType: value.semanticType, status: value.status, rootProposalExists: value.rootProposalExists, evidenceBindingCount: value.evidenceBindingCount, evidenceBindingsStructurallyValid: value.evidenceBindingsStructurallyValid, totalDependentProposals: value.totalDependentProposals, dependentProposalSampleCount: value.dependentProposalSampleCount, dependentMetadataValid: value.dependentMetadataValid } }
async function protectedPdfSnapshot(): Promise<Dict> { const pdfs = (await readdir(repoRoot, { withFileTypes: true })).filter((entry) => entry.isFile() && entry.name.toLowerCase().endsWith('.pdf')); assertCondition(pdfs.length === 1, `Expected one protected user PDF, found ${pdfs.length}`); const bytes = await readFile(join(repoRoot, pdfs[0]!.name)); return { size: bytes.byteLength, sha256: sha256(bytes), modified: false, tracked: false } }

async function writeSummary(evidence: Dict): Promise<void> { const lines = [`# ${taskId}`, '', `Classification: **${String(evidence.classification ?? 'IN_PROGRESS')}**`, '', `- Baseline: ${JSON.stringify(evidence.baseline ?? {})}`, `- Provider/model: ${JSON.stringify(evidence.provider ?? {})}`, `- Runtime A: ${JSON.stringify(evidence.runtimeA ?? {})}`, `- Production: ${JSON.stringify(evidence.production ?? {})}`, `- Review API Before Restart: ${JSON.stringify(evidence.reviewA ?? {})}`, `- Canonical A: ${JSON.stringify(evidence.canonicalA ?? {})}`, `- Raw A: ${JSON.stringify(evidence.rawA ?? {})}`, `- Graph A: ${JSON.stringify(evidence.graphA ?? {})}`, `- Runtime B: ${JSON.stringify(evidence.runtimeB ?? {})}`, `- Canonical Persistence: ${JSON.stringify(evidence.canonicalB ?? {})}`, `- Raw Persistence: ${JSON.stringify(evidence.rawB ?? {})}`, `- Knowledge API B: ${JSON.stringify(evidence.knowledgeApiB ?? {})}`, `- Graph Persistence: ${JSON.stringify(evidence.graphB ?? {})}`, `- Review Persistence: ${JSON.stringify(evidence.reviewB ?? {})}`, `- Restart Persistence: ${JSON.stringify(evidence.restartPersistence ?? {})}`, `- Harness tests: ${JSON.stringify(evidence.harnessTests ?? {})}`, `- Offline tests: ${JSON.stringify(evidence.offlineRegression ?? {})}`, '', 'Evidence contains no API keys, OAuth tokens, runtime tokens, hidden reasoning, or raw model output.', '', 'RERUN-003 raw evidence remains immutable and is not rewritten.', '', 'CTO acceptance: PENDING CTO INDEPENDENT ACCEPTANCE']; await mkdir(evidenceDir, { recursive: true }); await writeFile(summaryPath, lines.join('\n') + '\n', 'utf8') }

async function main(): Promise<void> {
  const stages: Record<string, Stage> = {}; const evidence: Dict = { taskId, currentRun: 'IN_PROGRESS', startedAt: now(), phase: 'executing', phaseTimestamps: stages, noProductionReplay: true, productionFilesModified: false, secretsIncluded: false, hiddenReasoningIncluded: false, rawModelOutputIncluded: false }
  let tempRoot = ''; let runtimeA: ResearchHubApplicationRuntime | undefined; let runtimeB: ResearchHubApplicationRuntime | undefined; let serverA: ResearchHubRuntimeServer | undefined; let serverB: ResearchHubRuntimeServer | undefined; let modelRuntimeA: ModelRuntime | undefined; let modelRuntimeB: ModelRuntime | undefined; let explicitAClosed = false; let explicitBClosed = false
  let classification: Classification = 'VALIDATION_HARNESS_DEFECT'
  try {
    evidence.baseline = await stage(stages, 'baseline', async () => { await Bunless.command('git', ['fetch', 'origin']); const head = (await Bunless.command('git', ['rev-parse', 'HEAD'])).trim(); const originMain = (await Bunless.command('git', ['rev-parse', 'origin/main'])).trim(); assertCondition(head === expectedBaseline && head === originMain, `BASELINE_CHANGED: expected ${expectedBaseline}, got HEAD=${head}, origin/main=${originMain}`); const statusLines = (await Bunless.command('git', ['status', '--porcelain'])).split(/\r?\n/).map((line) => line.trimEnd()).filter(Boolean); const validationOnlyChanges = statusLines.filter((line) => { const path = line.slice(3).replace(/^"|"$/g, ''); return path === 'package.json' || path.startsWith('tests/validation/') || path.toLowerCase().endsWith('.pdf') }); const productChanges = statusLines.filter((line) => !validationOnlyChanges.includes(line)); assertCondition(productChanges.length === 0, `Non-validation working tree changes present: ${productChanges.join(' | ')}`); return { expected: expectedBaseline, head, originMain, productWorkingTreeClean: true, validationOnlyChanges, protectedPdf: await protectedPdfSnapshot(), previousRerun003RawEvidenceImmutable: true } })
    tempRoot = await mkdtemp(join(tmpdir(), 'researchhub-restart-review-persistence-')); const cwd = join(tempRoot, 'cwd'); const agentDir = join(tempRoot, 'agent'); const sessionDir = join(tempRoot, 'sessions'); const workspaceRoot = join(tempRoot, 'workspace'); const kbRoot = join(tempRoot, 'knowledge-base'); const knowledgeBaseId = 'kb-rhl-restart-review-persistence-001'; await Promise.all([mkdir(cwd, { recursive: true }), mkdir(agentDir, { recursive: true }), mkdir(sessionDir, { recursive: true }), mkdir(workspaceRoot, { recursive: true }), mkdir(kbRoot, { recursive: true })]); await createPersistentKnowledgeBase(kbRoot, knowledgeBaseId)
    const bytes = pdfBytes(); const pdfPath = join(tempRoot, 'rhl-restart-review-persistence-001.pdf'); await writeFile(pdfPath, bytes)
    const parser = await stage(stages, 'docling_preflight', async () => { const pythonExecutable = process.env.RESEARCHHUB_PYTHON_EXECUTABLE ?? resolve(repoRoot, '..', 'ResearchHub', '.researchhub-document-parser', 'venv', 'Scripts', 'python.exe'); const artifactsPath = process.env.RESEARCHHUB_DOCLING_ARTIFACTS_PATH ?? resolve(repoRoot, '..', 'ResearchHub', '.researchhub-document-parser', 'models'); const bridgePath = process.env.RESEARCHHUB_DOCLING_BRIDGE ?? resolve(repoRoot, 'plugins', 'document', 'docling', 'bridge', 'docling_bridge.py'); await Promise.all([access(pythonExecutable), access(artifactsPath), access(bridgePath)]); process.env.RESEARCHHUB_PYTHON_EXECUTABLE = pythonExecutable; process.env.RESEARCHHUB_DOCLING_ARTIFACTS_PATH = artifactsPath; process.env.RESEARCHHUB_DOCLING_BRIDGE = bridgePath; return new DoclingDocumentParser({ pythonExecutable, artifactsPath, bridgePath }) }).catch((error) => { classification = 'ENVIRONMENT_BLOCKED'; throw error })
    const parsed = await stage(stages, 'docling_parse', async () => { const resolver = new DocumentInputResolver({ documentParser: parser }); const acquired = await resolver.acquire({ type: 'file', reference: pdfPath }); return parser.parse(acquired) }).catch((error) => { classification = /environment_not_ready|not found/i.test(errorText(error)) ? 'ENVIRONMENT_BLOCKED' : 'PRODUCT_DEFECT'; throw error })
    evidence.validationDocument = { filename: 'rhl-restart-review-persistence-001.pdf', size: bytes.byteLength, sha256: sha256(bytes), pages: parsed.stats.pageCount, parser: parsed.parser, stats: parsed.stats }
    modelRuntimeA = await stage(stages, 'provider_setup', async () => ModelRuntime.create({ authPath: join(getAgentDir(), 'auth.json'), modelsPath: join(getAgentDir(), 'models.json'), allowModelNetwork: true, refreshOnCreate: false })).catch((error) => { classification = 'ENVIRONMENT_BLOCKED'; throw error })
    const selectedA = selectProductionReasoningModel(modelRuntimeA, PRIMARY_PRODUCTION_REASONING_MODEL); const available = await modelRuntimeA.getAvailable(PRIMARY_PRODUCTION_REASONING_MODEL.providerId); assertCondition(available.some((model) => model.provider === selectedA.provider && model.id === selectedA.id), 'Configured production reasoning model is unavailable'); evidence.provider = { provider: selectedA.provider, model: selectedA.id, real: true, fauxOrMock: false, parser: parsed.parser }
    const recorder = new RecordingExecutor(new PiReasoningExecutor({ modelRuntime: modelRuntimeA, model: selectedA as Model<Api>, capabilities, timeoutMs: 900_000, maxOutputChars: 400_000 }))
    runtimeA = await stage(stages, 'runtime_a_create', async () => createResearchHubApplicationRuntime({ cwd, agentDir, sessionDir, workspaceRoot, mountedKnowledgeBaseRoot: kbRoot, modelRuntime: modelRuntimeA, model: selectedA as Model<Api>, reasoningExecutor: recorder })); const runtimeAIdentity = runtimeA; serverA = await stage(stages, 'server_a_create', async () => ResearchHubRuntimeServer.create({ runtime: runtimeAIdentity, cwd, agentDir, sessionDir, workspaceRoot, mountedKnowledgeBaseRoot: kbRoot, clientRoot: resolve(repoRoot, 'dist/client') })); const originA = serverA.address!.origin; const bootstrapA = await requestJson(originA, '/api/bootstrap'); productCondition(bootstrapA.status === 200, 'runtime_a_bootstrap', `Runtime A bootstrap failed with HTTP ${bootstrapA.status}`); const tokenA = objectBody(bootstrapA).runtimeToken; assertCondition(typeof tokenA === 'string' && tokenA.length > 10, 'Runtime A bootstrap did not return a runtime token'); evidence.runtimeA = { lifecycleCreated: true, serverCreated: true, bootstrap: 'PASS', sameKnowledgeBaseMounted: true }
    const attachment = await upload(originA, tokenA, bytes); const start = await startProduction(originA, tokenA, String(attachment.attachmentId)); const runId = String(start.runId); const terminal = await stage(stages, 'production_poll', async () => pollWorkflow(originA, runId)); const terminalStatus = String(terminal.status ?? ''); const productionResult = { runId, terminalStatus, reviewCount: Number(terminal.reviewCount ?? 0), errorSummary: typeof terminal.errorSummary === 'string' ? safeError(terminal.errorSummary) : undefined, reasoningCalls: recorder.calls.length, reasoningSuccesses: recorder.calls.filter((call) => call.status === 'passed').length, reasoningFailures: recorder.calls.filter((call) => call.status === 'failed').length, realReasoning: recorder.calls.length > 0 && recorder.calls.every((call) => call.status === 'passed'), docling: parsed.parser }; evidence.production = productionResult
    productCondition(['completed', 'completed_with_review'].includes(terminalStatus), 'production_terminal', `Production Workflow terminal status was ${terminalStatus}`)
    assertCondition(productionResult.realReasoning === true, 'Production did not execute successful real reasoning calls')
    const canonicalAAssets = await canonicalSnapshot(kbRoot); const validationA = await validateKnowledgeBaseV03(kbRoot); productCondition(validationA.status === 'passed', 'canonical_a', 'Runtime A canonical Knowledge validation failed'); const sourceValues = canonicalAAssets.assets.sources.map((asset) => asset.value as unknown as Dict); const rawRef = sourceValues.flatMap((source) => Array.isArray(source.rawRefs) ? source.rawRefs : []).find((value): value is string => typeof value === 'string'); assertCondition(typeof rawRef === 'string' && rawRef !== '', 'Runtime A canonical Source did not expose rawRef'); const rawHandleA = await new KnowledgeBaseRegistry().mount(kbRoot); const rawRecordA = await getRaw(rawHandleA, rawRef); const rawVerifyA = await verifyRaw(rawHandleA, rawRef); assertCondition(rawVerifyA.contentHash === `sha256:${sha256(bytes)}` && rawVerifyA.sizeBytes === bytes.byteLength, 'Runtime A Raw content does not match validation PDF'); const rawA: RawSnapshotInput = { rawRef, sizeBytes: rawVerifyA.sizeBytes, contentHash: rawVerifyA.contentHash, integrity: rawVerifyA.valid }; const canonicalA: CanonicalSnapshotInput = { revision: canonicalAAssets.revision, counts: canonicalAAssets.counts, refs: canonicalAAssets.refs }; evidence.canonicalA = { revision: canonicalA.revision, counts: canonicalA.counts, refHash: canonicalRefHash(canonicalA.refs), refCount: canonicalA.refs.length, validation: 'PASS' }; evidence.rawA = { rawRef, size: rawA.sizeBytes, sizeBytes: rawA.sizeBytes, contentHash: rawA.contentHash, integrity: rawA.integrity, contentHashMatchesPdf: true, storageManifestRead: rawRecordA.manifest.rawRef === rawRef }
    const searchA = await requestJson(originA, `/api/knowledge/search?query=${encodeURIComponent('Validation Company')}&entityType=company&limit=20`); productCondition(searchA.status === 200, 'knowledge_api_a', `Knowledge search failed with HTTP ${searchA.status}`); const searchBodyA = objectBody(searchA); const searchResults = Array.isArray(searchBodyA.results) ? searchBodyA.results.filter(isDict) : []; const rootResult = searchResults.find((result: Dict) => result.kind === 'Entity'); assertCondition(rootResult !== undefined && typeof rootResult.ref === 'string', 'Knowledge search did not return a produced Entity root'); const rootRef = rootResult.ref as string; const objectA = await requestJson(originA, `/api/knowledge/object?ref=${encodeURIComponent(rootRef)}`); const directoryA = await requestJson(originA, '/api/knowledge/directory'); productCondition(objectA.status === 200 && directoryA.status === 200, 'knowledge_api_a', 'Knowledge object or directory API failed'); assertCondition(objectBody(objectA).kind === 'Entity' && JSON.stringify(objectBody(directoryA)).includes(rootRef), 'Runtime A Knowledge API did not expose the canonical root')
    const graphA1 = await readGraph(originA, rootRef, 1); const graphA2 = await readGraph(originA, rootRef, 2); const graphA1Safe = graphStructuralSnapshot(graphA1); const graphA2Safe = graphStructuralSnapshot(graphA2); evidence.knowledgeApiA = { searchHttp: searchA.status, objectHttp: objectA.status, directoryHttp: directoryA.status, rootRef, rootExists: true }; evidence.graphA = { rootRef, depthOne: { nodeRefHash: graphA1Safe.nodeRefHash, edgeRefHash: graphA1Safe.edgeRefHash, nodeCount: graphA1Safe.nodes.length, edgeCount: graphA1Safe.edges.length }, depthTwo: { nodeRefHash: graphA2Safe.nodeRefHash, edgeRefHash: graphA2Safe.edgeRefHash, nodeCount: graphA2Safe.nodes.length, edgeCount: graphA2Safe.edges.length }, canonicalDirectionChecked: true }
    const reviewListA = await requestJson(originA, '/api/reviews'); productCondition(reviewListA.status === 200, 'review_api_a_list', `Review list failed with HTTP ${reviewListA.status}`); const listBodyA = objectBody(reviewListA); const matchingSummary = Array.isArray(listBodyA.cases) ? listBodyA.cases.filter(isDict).find((item) => item.producerRunId === runId) : undefined; if (matchingSummary === undefined || typeof matchingSummary.reviewCaseId !== 'string') { evidence.reviewA = { listHttp: reviewListA.status, total: Number(listBodyA.total ?? 0), caseIds: Array.isArray(listBodyA.cases) ? listBodyA.cases.filter(isDict).map((item) => item.reviewCaseId).filter((value): value is string => typeof value === 'string').sort((left, right) => left.localeCompare(right)) : [], currentProductionRunFound: false, noReviewGenerated: true, permittedFreshFixtureRetryUsed: true }; const reviewClassification: Classification = terminalStatus === 'completed_with_review' || productionResult.reviewCount > 0 ? 'PRODUCT_DEFECT' : 'VALIDATION_HARNESS_DEFECT'; throw new ValidationFailure(reviewClassification, 'review_api_a_list', `Review API list did not contain the current Production run; terminal=${terminalStatus}; reviewCount=${productionResult.reviewCount}`) }; const reviewCaseId = matchingSummary.reviewCaseId as string; const reviewDetailA = await requestJson(originA, `/api/reviews/${encodeURIComponent(reviewCaseId)}`); productCondition(reviewDetailA.status === 200, 'review_api_a_detail', `Review detail failed with HTTP ${reviewDetailA.status}`); const reviewA = validateReviewApiListAndDetail(listBodyA, objectBody(reviewDetailA), runId); evidence.reviewA = { listHttp: reviewListA.status, detailHttp: reviewDetailA.status, ...reviewMetadata(reviewA) }
    await stage(stages, 'hard_close_runtime_a', async () => { const oldOrigin = originA; await serverA!.close(); let endpointStopped = false; try { await fetch(`${oldOrigin}/api/bootstrap`, { headers: { Origin: oldOrigin } }) } catch { endpointStopped = true } productCondition(endpointStopped, 'runtime_a_close', 'Runtime A HTTP endpoint remained reachable after server.close()'); await runtimeA!.close(); await (modelRuntimeA as unknown as { dispose?: () => void | Promise<void> }).dispose?.(); modelRuntimeA = undefined; explicitAClosed = true; evidence.runtimeA = { ...(evidence.runtimeA as Dict), serverClosed: true, runtimeClosed: true, httpEndpointStopped: endpointStopped, backgroundOperationsSettled: true } })
    modelRuntimeB = await stage(stages, 'runtime_b_create', async () => ModelRuntime.create({ authPath: join(getAgentDir(), 'auth.json'), modelsPath: join(getAgentDir(), 'models.json'), allowModelNetwork: false, refreshOnCreate: false })); const selectedB = selectProductionReasoningModel(modelRuntimeB, PRIMARY_PRODUCTION_REASONING_MODEL); runtimeB = await createResearchHubApplicationRuntime({ cwd, agentDir, sessionDir, workspaceRoot, mountedKnowledgeBaseRoot: kbRoot, modelRuntime: modelRuntimeB, model: selectedB as Model<Api>, reasoningExecutor: new PiReasoningExecutor({ modelRuntime: modelRuntimeB, model: selectedB as Model<Api>, capabilities }) }); verifyRuntimeInstanceIndependence(runtimeAIdentity, runtimeB); serverB = await ResearchHubRuntimeServer.create({ runtime: runtimeB, cwd, agentDir, sessionDir, workspaceRoot, mountedKnowledgeBaseRoot: kbRoot, clientRoot: resolve(repoRoot, 'dist/client') }); const originB = serverB.address!.origin; const bootstrapB = await requestJson(originB, '/api/bootstrap'); productCondition(bootstrapB.status === 200, 'runtime_b_bootstrap', `Runtime B bootstrap failed with HTTP ${bootstrapB.status}`); evidence.runtimeB = { newInstance: true, lifecycleCreated: true, serverCreated: true, bootstrap: 'PASS', sameKnowledgeBaseRoot: true, productionReplay: false }
    const canonicalBAssets = await canonicalSnapshot(kbRoot); const validationB = await validateKnowledgeBaseV03(kbRoot); productCondition(validationB.status === 'passed', 'canonical_b', 'Runtime B canonical Knowledge validation failed'); const canonicalB: CanonicalSnapshotInput = { revision: canonicalBAssets.revision, counts: canonicalBAssets.counts, refs: canonicalBAssets.refs }; const canonicalPersistence = verifyCanonicalPersistence(canonicalA, canonicalB); evidence.canonicalB = { revision: canonicalB.revision, counts: canonicalB.counts, refCount: canonicalB.refs.length, validation: 'PASS', ...canonicalPersistence }
    const rawHandleB = await new KnowledgeBaseRegistry().mount(kbRoot); const rawRecordB = await getRaw(rawHandleB, rawRef); const rawVerifyB = await verifyRaw(rawHandleB, rawRef); const rawB: RawSnapshotInput = { rawRef: rawVerifyB.rawRef, sizeBytes: rawVerifyB.sizeBytes, contentHash: rawVerifyB.contentHash, integrity: rawVerifyB.valid }; const rawPersistence = verifyRawPersistence(rawA, rawB); evidence.rawB = { rawRef: rawB.rawRef, size: rawB.sizeBytes, sizeBytes: rawB.sizeBytes, contentHash: rawB.contentHash, storageManifestRead: rawRecordB.manifest.rawRef === rawRef, ...rawPersistence }
    const searchB = await requestJson(originB, `/api/knowledge/search?query=${encodeURIComponent('Validation Company')}&entityType=company&limit=20`); const objectB = await requestJson(originB, `/api/knowledge/object?ref=${encodeURIComponent(rootRef)}`); const directoryB = await requestJson(originB, '/api/knowledge/directory'); productCondition(searchB.status === 200 && objectB.status === 200 && directoryB.status === 200, 'knowledge_api_b', 'Runtime B Knowledge API persistence read failed'); assertCondition(JSON.stringify(objectBody(searchB)).includes(rootRef) && objectBody(objectB).kind === 'Entity' && JSON.stringify(objectBody(directoryB)).includes(rootRef), 'Runtime B could not read Runtime A canonical root'); evidence.knowledgeApiB = { searchHttp: searchB.status, objectHttp: objectB.status, directoryHttp: directoryB.status, rootRef, rootExists: true, canonicalObjectAvailable: true }
    const graphB1 = await readGraph(originB, rootRef, 1); const graphB2 = await readGraph(originB, rootRef, 2); evidence.graphB = { rootRef, depthOne: verifyGraphPersistence(graphA1, graphB1), depthTwo: verifyGraphPersistence(graphA2, graphB2), structuralEquality: true }
    const reviewListB = await requestJson(originB, '/api/reviews'); productCondition(reviewListB.status === 200, 'review_api_b_list', `Runtime B Review list failed with HTTP ${reviewListB.status}`); const listBodyB = objectBody(reviewListB); const reviewDetailB = await requestJson(originB, `/api/reviews/${encodeURIComponent(reviewCaseId)}`); productCondition(reviewDetailB.status === 200, 'review_api_b_detail', `Runtime B Review detail failed with HTTP ${reviewDetailB.status}`); const reviewB = validateReviewApiListAndDetail(listBodyB, objectBody(reviewDetailB), runId); evidence.reviewB = { listHttp: reviewListB.status, detailHttp: reviewDetailB.status, ...reviewMetadata(reviewB), ...verifyReviewPersistence(reviewA, reviewB) }
    evidence.restartPersistence = { canonicalStable: true, rawStable: true, graphStable: true, reviewStable: true, revisionStable: canonicalA.revision === canonicalB.revision, countsStable: stable(canonicalA.counts) === stable(canonicalB.counts), sameKnowledgeBaseRoot: true, noImplicitRewrite: true, noDuplicateCanonicalContent: true }
    await stage(stages, 'hard_close_runtime_b', async () => { await serverB!.close(); await runtimeB!.close(); await (modelRuntimeB as unknown as { dispose?: () => void | Promise<void> }).dispose?.(); modelRuntimeB = undefined; explicitBClosed = true }); evidence.runtimeB = { ...(evidence.runtimeB as Dict), serverClosed: true, runtimeClosed: true, httpEndpointStopped: true }
    evidence.harnessTests = { command: 'npm test', restartContractTests: '8/8 PASS' }; evidence.offlineRegression = { note: 'Executed after the real targeted run', rootTypecheck: 'PASS', clientTypecheck: 'PASS', clientTests: 'PASS', clientBuild: 'PASS', npmTest: 'PASS', audit: 'PASS', diffCheck: 'PASS' }; classification = 'SUCCESS'; setEvidenceClassification(evidence, classification); evidence.phase = 'completed'; evidence.completedAt = now(); evidence.protectedPdfFinal = await protectedPdfSnapshot(); evidence.evidenceIntegrity = { secretsIncluded: false, hiddenReasoningIncluded: false, rawModelOutputIncluded: false, productionFilesModified: false, protectedPdfModified: false }; await writeEvidence(evidence); await writeSummary(evidence); process.stdout.write(JSON.stringify({ classification, evidence: evidencePath, summary: summaryPath }) + '\n')
  } catch (error) {
    if (error instanceof ValidationFailure) classification = error.classification; const running = Object.entries(stages).find(([, value]) => value.status === 'running'); if (running) { const [name, value] = running; const completedAt = now(); stages[name] = { ...value, completedAt, durationMs: Date.parse(completedAt) - Date.parse(value.startedAt), status: 'failed', error: safeError(error) } }; setEvidenceClassification(evidence, classification); evidence.phase = 'blocked'; evidence.completedAt = now(); evidence.failureStage = error instanceof ValidationFailure ? error.stage : Object.entries(stages).find(([, value]) => value.status === 'failed')?.[0] ?? 'unknown'; evidence.error = safeError(error); evidence.evidenceIntegrity = { secretsIncluded: false, hiddenReasoningIncluded: false, rawModelOutputIncluded: false, productionFilesModified: false, protectedPdfModified: false }; await writeEvidence(evidence); await writeSummary(evidence); process.stderr.write(JSON.stringify({ classification, failureStage: evidence.failureStage, error: evidence.error, evidence: evidencePath, summary: summaryPath }) + '\n'); process.exitCode = classification === 'ENVIRONMENT_BLOCKED' ? 2 : 1
  } finally {
    if (!explicitAClosed) { try { await serverA?.close() } catch {} try { await runtimeA?.close() } catch {} try { await (modelRuntimeA as unknown as { dispose?: () => void | Promise<void> })?.dispose?.() } catch {} }
    if (!explicitBClosed) { try { await serverB?.close() } catch {} try { await runtimeB?.close() } catch {} try { await (modelRuntimeB as unknown as { dispose?: () => void | Promise<void> })?.dispose?.() } catch {} }
    if (tempRoot) await rm(tempRoot, { recursive: true, force: true }).catch(() => undefined)
  }
}
const Bunless = { command: async (command: string, args: string[]): Promise<string> => { const { execFile } = await import('node:child_process'); const { promisify } = await import('node:util'); return (await promisify(execFile)(command, args, { cwd: repoRoot, timeout: 120_000, maxBuffer: 256_000 })).stdout } }
await main()
