import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { access, mkdir, mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { createHash } from 'node:crypto'
import type { Api, Model } from '@earendil-works/pi-ai'
import { getAgentDir, ModelRuntime } from '@earendil-works/pi-coding-agent'
import { createResearchHubApplicationRuntime, type ResearchHubApplicationRuntime } from '../../app/runtime/application-runtime.ts'
import { ResearchHubRuntimeServer } from '../../app/runtime/server.ts'
import { PRIMARY_PRODUCTION_REASONING_MODEL, selectProductionReasoningModel } from '../../app/pi/model-selection.ts'
import { PiReasoningExecutor } from '../../plugins/reasoning/pi/executor.ts'
import type { ReasoningCapabilities, ReasoningExecutor, ReasoningRequest, ReasoningResult } from '../../plugins/reasoning/contracts.ts'
import { DoclingDocumentParser } from '../../plugins/document/docling/parser.ts'
import { DocumentInputResolver } from '../../plugins/document/input-resolver.ts'
import { KnowledgeBaseRegistry } from '../../knowledge/registry/registry.ts'
import { KnowledgeBaseLoaderV03 } from '../../knowledge/storage/loader.ts'
import { parseYaml } from '../../knowledge/storage/yaml.ts'
import { validateKnowledgeBaseV03 } from '../../knowledge/validation/v03-validator.ts'
import { setEvidenceClassification } from './restart-review-persistence-contract.ts'

const repoRoot = resolve(import.meta.dirname, '../..')
const evidenceDir = resolve(repoRoot, 'tests/validation/evidence')
const evidencePath = join(evidenceDir, 'rhl-review-terminal-case-invariant-001.json')
const summaryPath = join(evidenceDir, 'RHL_REVIEW_TERMINAL_CASE_INVARIANT_001_SUMMARY.md')
const taskId = 'RHL-FIX-REVIEW-TERMINAL-CASE-INVARIANT-001'
const expectedParentBaseline = '80f3aece47309dab3aace57e9379969dfcb32830'
const capabilities: ReasoningCapabilities = { maxContextTokens: 128_000, maxOutputTokens: 16_384, structuredOutputSupport: true, maxConcurrency: 4 }
const workflowTimeoutMs = 15 * 60 * 1_000
type Dict = Record<string, unknown>
type Classification = 'SUCCESS' | 'PRODUCT_DEFECT' | 'ENVIRONMENT_BLOCKED' | 'VALIDATION_HARNESS_DEFECT'
type Stage = { startedAt: string; completedAt?: string; durationMs?: number; status: 'running' | 'passed' | 'failed'; error?: string }
class ValidationFailure extends Error { constructor(readonly classification: Classification, readonly stage: string, message: string) { super(message); this.name = 'ValidationFailure' } }
function now(): string { return new Date().toISOString() }
function isDict(value: unknown): value is Dict { return typeof value === 'object' && value !== null && !Array.isArray(value) }
function errorText(error: unknown): string { return error instanceof Error ? error.message : String(error) }
function safeError(error: unknown): string { return errorText(error).replace(/\b(?:sk|ghp)_[A-Za-z0-9._-]+\b/gi, '[redacted]').replace(/\b(?:api[_-]?key|token|password|secret|authorization)\s*[:=]?\s*[^\s,;]+/gi, '[redacted]').replace(/(?:[A-Za-z]:[\\/]|\\\\)[^\s"']+/g, '[path]').replace(/\s+/g, ' ').slice(0, 500) }
function assertCondition(condition: unknown, message: string): asserts condition { if (!condition) throw new Error(message) }
function productCondition(condition: unknown, stage: string, message: string): asserts condition { if (!condition) throw new ValidationFailure('PRODUCT_DEFECT', stage, message) }
async function stage<T>(stages: Record<string, Stage>, name: string, action: () => Promise<T>): Promise<T> { const startedAt = now(); stages[name] = { startedAt, status: 'running' }; try { const value = await action(); const completedAt = now(); stages[name] = { startedAt, completedAt, durationMs: Date.parse(completedAt) - Date.parse(startedAt), status: 'passed' }; return value } catch (error) { const completedAt = now(); stages[name] = { startedAt, completedAt, durationMs: Date.parse(completedAt) - Date.parse(startedAt), status: 'failed', error: safeError(error) }; throw error } }
async function git(...args: string[]): Promise<string> { return (await promisify(execFile)('git', args, { cwd: repoRoot, timeout: 120_000, maxBuffer: 256_000 })).stdout.trim() }
async function writeEvidence(value: Dict): Promise<void> { await mkdir(evidenceDir, { recursive: true }); await writeFile(evidencePath, JSON.stringify(value, null, 2) + '\n', 'utf8') }
async function protectedPdfSnapshot(): Promise<Dict> { const pdfs = (await readdir(repoRoot, { withFileTypes: true })).filter((entry) => entry.isFile() && entry.name.toLowerCase().endsWith('.pdf')); assertCondition(pdfs.length === 1, `Expected one protected user PDF, found ${pdfs.length}`); const bytes = await readFile(join(repoRoot, pdfs[0]!.name)); return { size: bytes.byteLength, sha256: createHash('sha256').update(bytes).digest('hex'), modified: false, tracked: false } }
function pdfBytes(): Uint8Array { const lines = ['RHL Review terminal invariant validation', 'Validation Company operates in Validation Industry.', 'Validation Company offers Validation Product.', 'Validation Company develops Validation Technology.', 'Validation Company has revenue exposure to Validation Industry.']; const escapePdf = (value: string): string => value.replaceAll('\\', '\\\\').replaceAll('(', '\\(').replaceAll(')', '\\)'); const stream = ['BT', '/F1 12 Tf', '72 740 Td', ...lines.flatMap((line, index) => [`(${escapePdf(line)}) Tj`, index < lines.length - 1 ? '0 -28 Td' : '']), 'ET'].filter(Boolean).join('\n') + '\n'; const objects = ['<< /Type /Catalog /Pages 2 0 R >>', '<< /Type /Pages /Kids [3 0 R] /Count 1 >>', '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>', `<< /Length ${Buffer.byteLength(stream, 'binary')} >>\nstream\n${stream}endstream`, '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>']; let content = '%PDF-1.4\n%RHL\n'; const offsets = [0]; for (let index = 0; index < objects.length; index += 1) { offsets.push(Buffer.byteLength(content, 'binary')); content += `${index + 1} 0 obj\n${objects[index]}\nendobj\n` } const xrefOffset = Buffer.byteLength(content, 'binary'); content += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${offsets.slice(1).map((offset) => `${String(offset).padStart(10, '0')} 00000 n `).join('\n')}\ntrailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`; return Uint8Array.from(Buffer.from(content, 'binary')) }
async function createKnowledgeBase(root: string, knowledgeBaseId: string): Promise<void> { for (const directory of ['raw', 'registry', 'theme-groups', 'entities', 'relations', 'claims', 'sources', 'modules', 'logs/ingestion']) await mkdir(join(root, directory), { recursive: true }); await writeFile(join(root, 'manifest.yaml'), JSON.stringify({ knowledgeBaseId, name: 'Review terminal invariant validation KB', schemaVersion: '0.3', storageFormatVersion: '1', revision: 0, status: 'active', createdAt: '2026-09-07T00:00:00.000Z', updatedAt: '2026-09-07T00:00:00.000Z' }) + '\n'); await writeFile(join(root, 'registry', 'assets.yaml'), '{}\n'); await writeFile(join(root, 'registry', 'raw.yaml'), '{}\n') }
class RecordingExecutor implements ReasoningExecutor { readonly calls: Dict[] = []; constructor(private readonly inner: PiReasoningExecutor) {} capabilities(): ReasoningCapabilities { return this.inner.capabilities() } async execute(request: ReasoningRequest, signal?: AbortSignal): Promise<ReasoningResult> { const entry: Dict = { operation: request.operation, status: 'running' }; this.calls.push(entry); try { const result = await this.inner.execute(request, signal); entry.status = 'passed'; return result } catch (error) { entry.status = 'failed'; entry.error = safeError(error); throw error } } }
type HttpResult = { readonly status: number; readonly body: unknown }
async function requestJson(origin: string, path: string, init: RequestInit = {}): Promise<HttpResult> { const response = await fetch(`${origin}${path}`, { ...init, headers: { Origin: origin, ...(init.headers ?? {}) } }); const text = await response.text(); let body: unknown = text; try { body = text === '' ? undefined : JSON.parse(text) } catch {} return { status: response.status, body } }
function objectBody(response: HttpResult): Dict { assertCondition(isDict(response.body), `Expected JSON object from HTTP ${response.status}`); return response.body }
async function pollWorkflow(origin: string, runId: string): Promise<Dict> { const deadline = Date.now() + workflowTimeoutMs; while (Date.now() < deadline) { const response = await requestJson(origin, `/api/workflows/${encodeURIComponent(runId)}`); assertCondition(response.status === 200, `Workflow polling failed with HTTP ${response.status}`); const body = objectBody(response); if (['completed', 'completed_with_review', 'failed', 'cancelled', 'blocked'].includes(String(body.status))) return body; await new Promise((resolvePromise) => setTimeout(resolvePromise, 1_000)) } throw new Error('Workflow polling timed out') }
async function upload(origin: string, token: string, bytes: Uint8Array): Promise<string> { const form = new FormData(); form.append('file', new Blob([bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer], { type: 'application/pdf' }), 'rhl-review-terminal-case-invariant-001.pdf'); const response = await requestJson(origin, '/api/attachments', { method: 'POST', body: form, headers: { 'X-ResearchHub-Runtime-Token': token } }); assertCondition(response.status === 201, `Attachment upload failed with HTTP ${response.status}`); const attachment = objectBody(response).attachment; assertCondition(isDict(attachment) && typeof attachment.attachmentId === 'string', 'Attachment DTO missing attachmentId'); return attachment.attachmentId }
async function startProduction(origin: string, token: string, attachmentId: string): Promise<string> { const response = await requestJson(origin, '/api/production/ingest', { method: 'POST', body: JSON.stringify({ attachmentId, sourceMetadata: { title: 'RHL Review terminal invariant validation', institution: 'ResearchHub Validation' } }), headers: { 'Content-Type': 'application/json', 'X-ResearchHub-Runtime-Token': token } }); assertCondition(response.status === 202, `Production start failed with HTTP ${response.status}`); const body = objectBody(response); assertCondition(typeof body.runId === 'string', 'Production start did not return runId'); return body.runId }
function collectionCounts(rootAssets: Awaited<ReturnType<KnowledgeBaseLoaderV03['load']>>): Dict { return { themeGroups: rootAssets.themeGroups.length, entities: rootAssets.entities.length, relations: rootAssets.relations.length, claims: rootAssets.claims.length, sources: rootAssets.sources.length, modules: rootAssets.modules.length } }

async function writeSummary(evidence: Dict): Promise<void> { const lines = [`# ${taskId}`, '', `Classification: **${String(evidence.classification ?? 'IN_PROGRESS')}**`, '', `- Baseline: ${JSON.stringify(evidence.baseline ?? {})}`, `- Provider/model: ${JSON.stringify(evidence.provider ?? {})}`, `- Production terminal: ${JSON.stringify(evidence.production ?? {})}`, `- Review API: ${JSON.stringify(evidence.reviewApi ?? {})}`, `- Review telemetry: ${JSON.stringify(evidence.reviewTelemetry ?? {})}`, `- Canonical: ${JSON.stringify(evidence.canonical ?? {})}`, `- Validation: ${JSON.stringify(evidence.validation ?? {})}`, '', 'Targeted real Production only; no browser smoke, Runtime B restart, or full E2E replay was executed.', '', 'Evidence contains no API keys, OAuth tokens, runtime tokens, hidden reasoning, prompts, or raw model output.', '', 'Historical RERUN-003 and restart-persistence raw evidence remain immutable.', '', 'CTO acceptance: PENDING CTO INDEPENDENT ACCEPTANCE']; await mkdir(evidenceDir, { recursive: true }); await writeFile(summaryPath, lines.join('\n') + '\n', 'utf8') }

async function main(): Promise<void> {
  const stages: Record<string, Stage> = {}; const evidence: Dict = { taskId, currentRun: 'IN_PROGRESS', startedAt: now(), phase: 'executing', phaseTimestamps: stages, targetedRealProductionOnly: true, noBrowser: true, noRuntimeBRestart: true, secretsIncluded: false, hiddenReasoningIncluded: false, rawModelOutputIncluded: false }
  let classification: Classification = 'VALIDATION_HARNESS_DEFECT'; let tempRoot = ''; let runtime: ResearchHubApplicationRuntime | undefined; let server: ResearchHubRuntimeServer | undefined; let modelRuntime: ModelRuntime | undefined; let explicitlyClosed = false
  try {
    await stage(stages, 'baseline_fetch', async () => { await git('fetch', 'origin'); const head = await git('rev-parse', 'HEAD'); const originMain = await git('rev-parse', 'origin/main'); const changed = (await git('diff', '--name-only', expectedParentBaseline, 'HEAD')).split(/\r?\n/).map((item) => item.trim()).filter(Boolean); const approved = new Set(['workflows/raw-document-knowledge-ingestion/workflow.ts', 'app/services/production-service.ts', 'tests/workflow/raw-document-knowledge-ingestion.test.ts', 'tests/workflow/raw-document-knowledge-ingestion-fix.test.ts', 'tests/app/application-services.test.ts', 'tests/validation/restart-review-persistence.ts', 'tests/validation/restart-review-persistence-contract.ts', 'tests/validation/restart-review-persistence-contract.test.ts', 'tests/validation/review-terminal-case-invariant.ts', 'docs/superpowers/specs/2026-09-07-review-terminal-case-invariant-design.md']); assertCondition(changed.every((item) => approved.has(item) || item.toLowerCase().endsWith('.md') || item.startsWith('tests/validation/evidence/')), `Unexpected changed paths: ${changed.join(', ')}`); evidence.baseline = { expectedParentBaseline, head, originMain, approvedDiffOnly: true, changedPaths: changed, protectedPdf: await protectedPdfSnapshot() } })
    tempRoot = await mkdtemp(join(tmpdir(), 'researchhub-review-terminal-invariant-')); const cwd = join(tempRoot, 'cwd'); const agentDir = join(tempRoot, 'agent'); const sessionDir = join(tempRoot, 'sessions'); const workspaceRoot = join(tempRoot, 'workspace'); const kbRoot = join(tempRoot, 'knowledge-base'); await Promise.all([mkdir(cwd, { recursive: true }), mkdir(agentDir, { recursive: true }), mkdir(sessionDir, { recursive: true }), mkdir(workspaceRoot, { recursive: true }), mkdir(kbRoot, { recursive: true })]); await createKnowledgeBase(kbRoot, 'kb-rhl-review-terminal-case-invariant-001')
    const bytes = pdfBytes(); const pdfPath = join(tempRoot, 'rhl-review-terminal-case-invariant-001.pdf'); await writeFile(pdfPath, bytes)
    const parser = await stage(stages, 'docling_preflight', async () => { const pythonExecutable = process.env.RESEARCHHUB_PYTHON_EXECUTABLE ?? resolve(repoRoot, '..', 'ResearchHub', '.researchhub-document-parser', 'venv', 'Scripts', 'python.exe'); const artifactsPath = process.env.RESEARCHHUB_DOCLING_ARTIFACTS_PATH ?? resolve(repoRoot, '..', 'ResearchHub', '.researchhub-document-parser', 'models'); const bridgePath = process.env.RESEARCHHUB_DOCLING_BRIDGE ?? resolve(repoRoot, 'plugins', 'document', 'docling', 'bridge', 'docling_bridge.py'); await Promise.all([access(pythonExecutable), access(artifactsPath), access(bridgePath)]); process.env.RESEARCHHUB_PYTHON_EXECUTABLE = pythonExecutable; process.env.RESEARCHHUB_DOCLING_ARTIFACTS_PATH = artifactsPath; process.env.RESEARCHHUB_DOCLING_BRIDGE = bridgePath; return new DoclingDocumentParser({ pythonExecutable, artifactsPath, bridgePath }) }).catch((error) => { classification = 'ENVIRONMENT_BLOCKED'; throw error })
    const parsed = await stage(stages, 'docling_parse', async () => new DocumentInputResolver({ documentParser: parser }).parse(await new DocumentInputResolver({ documentParser: parser }).acquire({ type: 'file', reference: pdfPath }))).catch((error) => { classification = /environment_not_ready|not found/i.test(errorText(error)) ? 'ENVIRONMENT_BLOCKED' : 'PRODUCT_DEFECT'; throw error }); evidence.validationDocument = { filename: 'rhl-review-terminal-case-invariant-001.pdf', size: bytes.byteLength, sha256: createHash('sha256').update(bytes).digest('hex'), parser: parsed.parser, stats: parsed.stats }
    modelRuntime = await stage(stages, 'provider_setup', async () => ModelRuntime.create({ authPath: join(getAgentDir(), 'auth.json'), modelsPath: join(getAgentDir(), 'models.json'), allowModelNetwork: true, refreshOnCreate: false })).catch((error) => { classification = 'ENVIRONMENT_BLOCKED'; throw error }); const selected = selectProductionReasoningModel(modelRuntime, PRIMARY_PRODUCTION_REASONING_MODEL); const available = await modelRuntime.getAvailable(PRIMARY_PRODUCTION_REASONING_MODEL.providerId); assertCondition(available.some((model) => model.provider === selected.provider && model.id === selected.id), 'Configured production reasoning model is unavailable'); evidence.provider = { provider: selected.provider, model: selected.id, real: true, fauxOrMock: false, parser: parsed.parser }
    const recorder = new RecordingExecutor(new PiReasoningExecutor({ modelRuntime, model: selected as Model<Api>, capabilities, timeoutMs: 900_000, maxOutputChars: 400_000 })); runtime = await stage(stages, 'runtime_create', async () => createResearchHubApplicationRuntime({ cwd, agentDir, sessionDir, workspaceRoot, mountedKnowledgeBaseRoot: kbRoot, modelRuntime, model: selected as Model<Api>, reasoningExecutor: recorder })); server = await stage(stages, 'server_create', async () => ResearchHubRuntimeServer.create({ runtime: runtime!, cwd, agentDir, sessionDir, workspaceRoot, mountedKnowledgeBaseRoot: kbRoot, clientRoot: resolve(repoRoot, 'dist/client') })); const origin = server.address!.origin; const bootstrap = await requestJson(origin, '/api/bootstrap'); productCondition(bootstrap.status === 200, 'runtime_bootstrap', `Runtime bootstrap failed with HTTP ${bootstrap.status}`); const token = objectBody(bootstrap).runtimeToken; assertCondition(typeof token === 'string' && token.length > 10, 'Runtime bootstrap did not return a runtime token')
    const attachmentId = await upload(origin, token, bytes); const runId = await startProduction(origin, token, attachmentId); const terminal = await stage(stages, 'production_poll', async () => pollWorkflow(origin, runId)); const terminalStatus = String(terminal.status ?? ''); const reviewCount = Number(terminal.reviewCount ?? 0); const realReasoning = recorder.calls.length > 0 && recorder.calls.every((call) => call.status === 'passed'); evidence.production = { runId, status: terminalStatus, reviewCount, errorSummary: typeof terminal.errorSummary === 'string' ? safeError(terminal.errorSummary) : undefined, parser: parsed.parser, reasoningCalls: recorder.calls.length, reasoningSuccesses: recorder.calls.filter((call) => call.status === 'passed').length, reasoningFailures: recorder.calls.filter((call) => call.status === 'failed').length, realReasoning }; productCondition(terminalStatus === 'completed' ? reviewCount === 0 : terminalStatus === 'completed_with_review' ? reviewCount > 0 : false, 'terminal_case_invariant', `Terminal status ${terminalStatus} is inconsistent with reviewCount ${reviewCount}`); assertCondition(realReasoning === true, 'Production did not execute successful real reasoning calls')
    const reviewList = await requestJson(origin, '/api/reviews'); productCondition(reviewList.status === 200, 'review_api_list', `Review list failed with HTTP ${reviewList.status}`); const listBody = objectBody(reviewList); const cases = Array.isArray(listBody.cases) ? listBody.cases.filter(isDict) : []; const matching = cases.find((item) => item.producerRunId === runId); if (terminalStatus === 'completed') { productCondition(matching === undefined, 'review_api_completed_case', 'Completed Production run has a durable ReviewCase in the Review API'); evidence.reviewApi = { listHttp: reviewList.status, total: Number(listBody.total ?? 0), currentProducerRunFound: false, detailHttp: null } } else { productCondition(matching !== undefined && typeof matching.reviewCaseId === 'string', 'review_api_review_case', 'completed_with_review Production run is absent from the Review API'); const detail = await requestJson(origin, `/api/reviews/${encodeURIComponent(matching!.reviewCaseId as string)}`); productCondition(detail.status === 200, 'review_api_detail', `Review detail failed with HTTP ${detail.status}`); evidence.reviewApi = { listHttp: reviewList.status, total: Number(listBody.total ?? 0), currentProducerRunFound: true, reviewCaseId: matching!.reviewCaseId, detailHttp: detail.status, detailProducerRunId: objectBody(detail).producerRunId } }
    const logPath = join(kbRoot, 'logs', 'ingestion', `${runId}.yaml`); const log = parseYaml(await readFile(logPath, 'utf8'), logPath); const context = isDict(log) && isDict(log.ingestionContext) ? log.ingestionContext : isDict(log) ? log : {}; const loggedCases = Array.isArray(context.reviewCases) ? context.reviewCases.filter(isDict) : []; evidence.reviewTelemetry = { total: Number(context.reviewSummary && isDict(context.reviewSummary) ? context.reviewSummary.total ?? 0 : 0), durableReviewCaseCount: loggedCases.length, logStatus: isDict(log) ? log.status : undefined, logCaseIds: loggedCases.map((item) => item.reviewCaseId).filter((value): value is string => typeof value === 'string').sort() }
    const assets = await new KnowledgeBaseLoaderV03(new KnowledgeBaseRegistry()).load(await new KnowledgeBaseRegistry().mount(kbRoot)); const validation = await validateKnowledgeBaseV03(kbRoot); productCondition(validation.status === 'passed', 'canonical_validation', 'Canonical Knowledge validation failed after targeted Production'); evidence.canonical = { revision: (await new KnowledgeBaseRegistry().mount(kbRoot)).revision, counts: collectionCounts(assets) }; evidence.validation = { status: 'PASS', reviewApiStatus: reviewList.status }; await stage(stages, 'runtime_close', async () => { await server!.close(); await runtime!.close(); await (modelRuntime as unknown as { dispose?: () => void | Promise<void> }).dispose?.(); explicitlyClosed = true }); classification = 'SUCCESS'; setEvidenceClassification(evidence, classification); evidence.phase = 'completed'; evidence.completedAt = now(); evidence.protectedPdfFinal = await protectedPdfSnapshot(); evidence.evidenceIntegrity = { secretsIncluded: false, hiddenReasoningIncluded: false, rawModelOutputIncluded: false, protectedPdfModified: false }; await writeEvidence(evidence); await writeSummary(evidence); process.stdout.write(JSON.stringify({ classification, evidence: evidencePath, summary: summaryPath }) + '\n')
  } catch (error) { if (error instanceof ValidationFailure) classification = error.classification; setEvidenceClassification(evidence, classification); evidence.phase = 'blocked'; evidence.completedAt = now(); evidence.failureStage = error instanceof ValidationFailure ? error.stage : Object.entries(stages).find(([, value]) => value.status === 'failed')?.[0] ?? 'unknown'; evidence.error = safeError(error); evidence.evidenceIntegrity = { secretsIncluded: false, hiddenReasoningIncluded: false, rawModelOutputIncluded: false, protectedPdfModified: false }; await writeEvidence(evidence); await writeSummary(evidence); process.stderr.write(JSON.stringify({ classification, failureStage: evidence.failureStage, error: evidence.error, evidence: evidencePath, summary: summaryPath }) + '\n'); process.exitCode = classification === 'ENVIRONMENT_BLOCKED' ? 2 : 1
  } finally { if (!explicitlyClosed) { try { await server?.close() } catch {} try { await runtime?.close() } catch {} try { await (modelRuntime as unknown as { dispose?: () => void | Promise<void> })?.dispose?.() } catch {} } if (tempRoot) await rm(tempRoot, { recursive: true, force: true }).catch(() => undefined) }
}
await main()
