import { createHash } from 'node:crypto'
import { execFile as execFileCallback } from 'node:child_process'
import { access, mkdir, readFile, stat, writeFile } from 'node:fs/promises'
import { promisify } from 'node:util'
import { join, resolve } from 'node:path'
import { CodexReasoningExecutor } from '../../plugins/reasoning/codex/executor.ts'
import type { ReasoningExecutor, ReasoningRequest, ReasoningResult, ReasoningCapabilities } from '../../plugins/reasoning/contracts.ts'
import { DocumentInputResolver } from '../../plugins/document/input-resolver.ts'
import { DoclingDocumentParser } from '../../plugins/document/docling/parser.ts'
import { KnowledgeCurationSkill } from '../../skills/knowledge-curation/skill.ts'
import { KnowledgeBaseRegistry } from '../../knowledge/registry/registry.ts'
import { KnowledgeBaseLoaderV03 } from '../../knowledge/storage/loader.ts'
import { validateKnowledgeBaseV03 } from '../../knowledge/validation/v03-validator.ts'
import { getRaw, verifyRaw } from '../../knowledge/raw/raw-archive.ts'
import { parseYaml } from '../../knowledge/storage/yaml.ts'
import { runRawDocumentKnowledgeIngestion } from '../../workflows/raw-document-knowledge-ingestion/workflow.ts'
import type { IngestionWorkflowResult, ReviewSummary } from '../../workflows/raw-document-knowledge-ingestion/contracts.ts'

const execFile = promisify(execFileCallback)
const repoRoot = resolve(import.meta.dirname, '../..')
const evidenceDir = resolve(repoRoot, 'tests/validation/evidence')
const pdfFilename = '20260805-西部证券-AI算力行业：AI算力上游材料产业链研究报告.pdf'
const expectedPdfBytes = 3209114
const expectedPdfSha256 = '998703cef102300518bb2edcbcc3e9bc26fa374f157b0714f3986c5028d78d63'
const productBaseline = 'a76dab149071eaf804ba191fcd0c9d796010f7f7'
const workflowRunId = 'rhl-semantic-quality-001-primary'
const knowledgeBaseId = 'kb-rhl-semantic-quality-001'
const outputPath = resolve(evidenceDir, 'rhl-validation-semantic-quality-001-real-e2e.json')
const summaryPath = resolve(evidenceDir, 'RHL_VALIDATION_SEMANTIC_QUALITY_001_SUMMARY.md')
const capabilities: ReasoningCapabilities = { maxContextTokens: 100000, maxOutputTokens: 20000, structuredOutputSupport: true, maxConcurrency: 1 }
const model = 'gpt-5.6-luna'
const reasoningEffort = 'high' as const
const timeoutMs = 900000
const maxOutputChars = 400000
type Dict = Record<string, unknown>
type Stage = { startedAt: string; completedAt?: string; durationMs?: number; status: 'running' | 'passed' | 'failed'; error?: string }

function now(): string { return new Date().toISOString() }
function isDict(value: unknown): value is Dict { return typeof value === 'object' && value !== null && !Array.isArray(value) }
function errorText(error: unknown): string { return error instanceof Error ? error.message : String(error) }
function sha256(value: Uint8Array): string { return createHash('sha256').update(value).digest('hex') }
function stableJson(value: unknown): string { if (Array.isArray(value)) return `[${value.map(stableJson).join(',')}]`; if (isDict(value)) return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${stableJson(value[key])}`).join(',')}}`; return JSON.stringify(value) }
function sum(values: readonly number[]): number { return values.reduce((total, value) => total + value, 0) }
function bounded(value: unknown, depth = 0): unknown { if (depth > 2) return typeof value === 'string' ? value.slice(0, 240) : '[nested]'; if (typeof value === 'string') return value.length > 240 ? value.slice(0, 237) + '...' : value; if (value === null || typeof value === 'number' || typeof value === 'boolean') return value; if (Array.isArray(value)) return value.slice(0, 12).map((item) => bounded(item, depth + 1)); if (isDict(value)) return Object.fromEntries(Object.entries(value).slice(0, 16).map(([key, child]) => [key, bounded(child, depth + 1)])); return String(value).slice(0, 240) }
function assertCondition(condition: unknown, message: string): asserts condition { if (!condition) throw new Error(message) }
async function command(command: string, args: string[]): Promise<string> { return (await execFile(command, args, { cwd: repoRoot, timeout: 120000, maxBuffer: 256000 })).stdout.trim() }
async function writeEvidence(evidence: Dict): Promise<void> { await mkdir(evidenceDir, { recursive: true }); await writeFile(outputPath, JSON.stringify(evidence, null, 2) + '\n') }
async function stage<T>(stages: Record<string, Stage>, name: string, action: () => Promise<T>): Promise<T> { const startedAt = now(); stages[name] = { startedAt, status: 'running' }; try { const result = await action(); const completedAt = now(); stages[name] = { startedAt, completedAt, durationMs: Date.parse(completedAt) - Date.parse(startedAt), status: 'passed' }; return result } catch (error) { const completedAt = now(); stages[name] = { startedAt, completedAt, durationMs: Date.parse(completedAt) - Date.parse(startedAt), status: 'failed', error: errorText(error).slice(0, 500) }; throw error } }

class RecordingExecutor implements ReasoningExecutor {
  readonly calls: Dict[] = []
  readonly semanticCases: Dict[] = []
  readonly extractionCandidates: Dict[] = []
  private sequence = 0
  constructor(private readonly inner: CodexReasoningExecutor) {}
  capabilities(): ReasoningCapabilities { return this.inner.capabilities() }
  async execute(request: ReasoningRequest): Promise<ReasoningResult> {
    const sequence = ++this.sequence
    const startedAt = now()
    const runtime = this.inner.runtimeMetadata()
    const entry: Dict = { sequence, executionId: `${workflowRunId}-${String(sequence).padStart(3, '0')}`, operation: request.operation, requestedModel: runtime.requestedModel, requestedReasoningEffort: runtime.requestedReasoningEffort, startedAt, instructionChars: request.instruction.length, inputChars: JSON.stringify(request.input).length, contractChars: JSON.stringify(request.outputContract).length, status: 'running' }
    this.calls.push(entry)
    if (request.operation === 'resolveSemanticCase') {
      const input = isDict(request.input) && isDict(request.input.resolutionCase) ? request.input.resolutionCase : {}
      this.semanticCases.push({ caseId: input.caseId, caseKind: input.caseKind, candidateKind: input.candidateKind, existingProjectionCount: Array.isArray(input.existingProjections) ? input.existingProjections.length : 0, evidenceExcerptCount: Array.isArray(input.evidenceExcerpts) ? input.evidenceExcerpts.length : 0, payloadChars: JSON.stringify(request.input).length, durableRefLeak: /source:|raw-sha256-|planned-(?:entity|relation|claim)-/.test(JSON.stringify(request.input)), status: 'running' })
    }
    try {
      const result = await this.inner.execute({ ...request, metadata: { ...(request.metadata ?? {}), executionId: String(entry.executionId) } })
      entry.completedAt = now(); entry.durationMs = result.durationMs ?? 0; entry.outputBytes = Buffer.byteLength(String(result.rawOutput ?? result.output), 'utf8'); entry.status = 'passed'
      if (request.operation === 'resolveSemanticCase') { const item = this.semanticCases.at(-1); if (item) { item.status = 'passed'; item.outcome = isDict(result.output) ? result.output.outcome : undefined } }
      if (request.operation === 'extractKnowledge' && isDict(result.output)) { const relations = result.output.relations; if (Array.isArray(relations)) for (const candidate of relations) if (isDict(candidate)) this.extractionCandidates.push({ candidateId: candidate.candidateId, relationType: candidate.relationType }) }
      return result
    } catch (error) { entry.completedAt = now(); entry.durationMs = Date.parse(String(entry.completedAt)) - Date.parse(startedAt); entry.status = 'failed'; entry.errorCode = isDict(error) && typeof error.code === 'string' ? error.code : 'unknown'; entry.error = errorText(error).slice(0, 300); throw error }
  }
}

function reviewInvariants(summary: ReviewSummary): Dict { const categoryTotal = sum(Object.values(summary.byCategory)); const kindTotal = sum(Object.values(summary.byCandidateKind)); const samplesBounded = Object.values(summary.samplesByCategory).every((items) => items.length <= 5); return { totalEqualsRootPlusDependency: summary.total === summary.rootCount + summary.dependencyCount, categoryTotalEqualsTotal: categoryTotal === summary.total, candidateKindTotalEqualsTotal: kindTotal === summary.total, samplesBoundedToFive: samplesBounded, allHold: summary.total === summary.rootCount + summary.dependencyCount && categoryTotal === summary.total && kindTotal === summary.total && samplesBounded } }
function collectionCounts(assets: Awaited<ReturnType<KnowledgeBaseLoaderV03['load']>>): Dict { return { themeGroups: assets.themeGroups.length, entities: assets.entities.length, relations: assets.relations.length, claims: assets.claims.length, sources: assets.sources.length, modules: assets.modules.length } }
function provenance(assets: Awaited<ReturnType<KnowledgeBaseLoaderV03['load']>>, rawRef: string): Dict {
  const sources = assets.sources.map((asset) => asset.value as unknown as Dict); const sourceIds = new Set(sources.map((source) => source.id)); const claims = assets.claims.map((asset) => asset.value as unknown as Dict); const rawRefs = new Set([rawRef]); let failures = 0
  const claimSourceFailures = claims.filter((claim) => !Array.isArray(claim.sourceRefs) || claim.sourceRefs.some((ref) => !sourceIds.has(ref))).length
  const claimProvenanceFailures = claims.filter((claim) => !Array.isArray(claim.provenance) || claim.provenance.some((item) => !isDict(item) || typeof item.sourceRef !== 'string' || typeof item.rawRef !== 'string' || !sourceIds.has(item.sourceRef) || !rawRefs.has(item.rawRef))).length
  const sourceRawFailures = sources.filter((source) => !Array.isArray(source.rawRefs) || source.rawRefs.some((ref) => !rawRefs.has(ref))).length
  failures = claimSourceFailures + claimProvenanceFailures + sourceRawFailures
  return { claimsChecked: claims.length, claimSourceRefFailures: claimSourceFailures, claimProvenanceFailures, sourceRawRefFailures: sourceRawFailures, claimToSource: claimSourceFailures === 0, sourceToRaw: sourceRawFailures === 0, allClaimProvenanceResolves: claimProvenanceFailures === 0, failures }
}
function countBy(values: readonly string[]): Dict { return Object.fromEntries([...new Set(values)].sort().map((value) => [value, values.filter((item) => item === value).length])) }
function operationObservation(log: Dict): Dict {
  const changes = isDict(log.changes) ? log.changes : {}; const ids = (key: string) => Array.isArray(changes[key]) ? changes[key].filter((item): item is string => typeof item === 'string') : []; const created = ids('knowledgeCreated'); const updated = ids('knowledgeUpdated'); const sourceCreated = ids('sourceCreated'); const sourceMerged = ids('sourceMerged'); const prefix = (values: readonly string[], value: string) => values.filter((item) => item.startsWith(value)).length
  return { sourceOperations: { created: sourceCreated.length, merged: sourceMerged.length }, knowledgeCreates: created.length, knowledgeUpdates: updated.length, entityCreates: prefix(created, 'entity:'), relationCreates: prefix(created, 'relation:'), claimCreates: prefix(created, 'claim:'), investmentThemeCreates: created.filter((item) => item.startsWith('entity:investment-theme-')).length, themeGroupCreates: prefix(created, 'theme-group:'), themeGroupUpdates: prefix(updated, 'theme-group:'), createdIds: created, updatedIds: updated }
}
function reviewSamples(summary: ReviewSummary): Dict[] { return Object.values(summary.samplesByCategory).flat().map((item) => item as unknown as Dict) }
function relationAttributeObservation(result: IngestionWorkflowResult, recorder: RecordingExecutor): Dict {
  const rejected: Dict[] = result.rejectedCandidates.filter((item): item is Dict => isDict(item) && item.kind === 'relation' && item.code === 'invalid_semantics' && /attribute/i.test(String(item.message)))
  const classify = (item: Dict): string => { const message = String(item.message); if (/nested field|financialContribution.*not declared|not declared/i.test(message)) return /financialContribution/i.test(message) ? 'invalid_nested_field' : 'undeclared_attribute'; if (/vocabulary|enum|outside/i.test(message)) return 'invalid_enum'; if (/range|between 0 and 1|finite/i.test(message)) return 'invalid_numeric_range'; if (/invalid type/i.test(message)) return 'invalid_nested_type'; return 'other_attribute_invalid' }
  const breakdown = countBy(rejected.map((item) => classify(item)))
  const relationTypes = new Map(recorder.extractionCandidates.map((item) => [String(item.candidateId), item.relationType]))
  return { relationCandidatesAccepted: Number(result.candidateCounts.relation ?? 0), relationCandidatesRejected: result.rejectedCandidates.filter((item) => isDict(item) && item.kind === 'relation').length, invalidRelationAttributeCandidateCount: rejected.length, breakdown, representativeSamples: rejected.slice(0, 20).map((item) => ({ candidateId: item.candidateId, relationType: relationTypes.get(String(item.candidateId)) ?? null, rejectionCode: item.code, message: String(item.message).slice(0, 300) })) }
}
function optionalEntityObservation(summary: ReviewSummary): Dict {
  const samples = reviewSamples(summary).filter((item) => /description|legalname/i.test(String(item.rationale)))
  return { descriptionFieldReviewObserved: samples.some((item) => /description/i.test(String(item.rationale))), legalNameFieldReviewObserved: samples.some((item) => /legalname/i.test(String(item.rationale))), exactDescriptionFieldReviewCountAvailable: false, exactLegalNameFieldReviewCountAvailable: false, representativeSamples: samples.slice(0, 10).map((item) => bounded(item)) }
}
function dependencyObservation(result: IngestionWorkflowResult): Dict {
  const items = [...result.reviewItems.map((item) => item as unknown as Dict), ...reviewSamples(result.reviewSummary)].filter((item) => item.dependency === true || /dependency isolated|blocked by/i.test(String(item.rationale)))
  const count = (pattern: RegExp) => items.filter((item) => pattern.test(String(item.rationale))).length
  const description = count(/description/i); const legalName = count(/legalname/i); const theme = count(/theme.*unresolved|unresolved.*theme/i); const blockingEntity = items.filter((item) => item.kind === 'entity' && /identity|hard|binding|unresolved/i.test(String(item.rationale))).length
  return { dependencyReviewCount: result.reviewSummary.dependencyCount, dependencyReviewsCausedByDescriptionFieldConflict: description, dependencyReviewsCausedByLegalNameFieldConflict: legalName, dependencyReviewsCausedByBlockingEntityIdentity: blockingEntity, dependencyReviewsCausedByThemeUnresolved: theme, dependencyReviewsOther: Math.max(0, result.reviewSummary.dependencyCount - description - legalName - blockingEntity - theme), exactBreakdownAvailable: false, observedItems: items.slice(0, 20).map((item) => bounded(item)) }
}
async function historicalIntegrity(): Promise<Dict> {
  const files = ['rhl-validation-001-real-e2e.json', 'rhl-validation-001-r2-real-e2e.json', 'rhl-validation-001-r3-real-e2e.json', 'rhl-validation-001-r4-real-e2e.json', 'rhl-validation-001-r5-real-e2e.json', 'rhl-validation-001-r6-real-e2e.json', 'rhl-validation-001-r7-real-e2e.json', 'RHL_FIX_REASONING_TIMEOUT_001_SMOKE.json']
  const entries = []
  for (const filename of files) { const path = resolve(evidenceDir, filename); const current = (await command('git', ['hash-object', path])).trim(); const baseline = (await command('git', ['rev-parse', `${productBaseline}:tests/validation/evidence/${filename}`])).trim(); entries.push({ filename, path, sha256: sha256(await readFile(path)), gitBlobHash: current, baselineGitBlobHash: baseline, unchanged: current === baseline }); assertCondition(current === baseline, `Historical evidence changed: ${filename}`) }
  return { allUnchanged: true, files: entries }
}
async function readManifestRevision(root: string): Promise<number> {
  const manifest = parseYaml(await readFile(join(root, 'manifest.yaml'), 'utf8'), join(root, 'manifest.yaml')) as Dict
  return Number(manifest.revision)
}
async function prepareFreshKnowledgeBase(root: string): Promise<void> { try { await access(root); throw new Error(`Fresh Knowledge Base path already exists: ${root}`) } catch (error) { if (isDict(error) && error.code !== 'ENOENT') throw error } for (const directory of ['raw', 'registry', 'theme-groups', 'entities', 'relations', 'claims', 'sources', 'modules', 'logs/ingestion']) await mkdir(join(root, directory), { recursive: true }); const timestamp = '2026-09-05T00:00:00.000Z'; await writeFile(join(root, 'manifest.yaml'), JSON.stringify({ knowledgeBaseId, name: 'RHL Semantic Quality Validation 001', schemaVersion: '0.3', storageFormatVersion: '1', revision: 0, status: 'active', createdAt: timestamp, updatedAt: timestamp }) + '\n'); await writeFile(join(root, 'registry', 'assets.yaml'), '{}\n'); await writeFile(join(root, 'registry', 'raw.yaml'), '{}\n') }

async function main(): Promise<void> {
  const stages: Record<string, Stage> = {}; const evidence: Dict = { taskId: 'RHL-VALIDATION-SEMANTIC-QUALITY-001', validationTask: 'RHL-VALIDATION-SEMANTIC-QUALITY-001', validationProductBaseline: productBaseline, startedAt: now(), phase: 'executing', phaseTimestamps: stages, mockReasoningCalls: 0, realReasoningExecutor: 'CodexReasoningExecutor via RecordingExecutor' }; let kbRoot = ''; let recorder: RecordingExecutor | undefined
  try {
    const head = await command('git', ['rev-parse', 'HEAD']); const remote = await command('git', ['rev-parse', 'origin/main']); const tracked = await command('git', ['status', '--porcelain', '--untracked-files=no']); assertCondition(head === remote && head === productBaseline, `Baseline mismatch: HEAD=${head}, origin/main=${remote}`); assertCondition(tracked === '', 'Tracked working tree is not clean'); evidence.baseline = { productBaseline, parent: (await command('git', ['rev-parse', `${productBaseline}^`])), currentHead: head, originMain: remote, trackedWorkingTreeClean: true, protectedPdf: 'untracked and unstaged' }; evidence.git = { branch: await command('git', ['branch', '--show-current']), head, originMain: remote, trackedWorkingTreeClean: true, protectedPdf: 'untracked and unstaged' }; evidence.historicalEvidenceIntegrity = await historicalIntegrity();
    const pdfPath = resolve(repoRoot, pdfFilename); const pdfBytes = Uint8Array.from(await readFile(pdfPath)); const pdfStat = await stat(pdfPath); assertCondition(pdfStat.size === expectedPdfBytes && sha256(pdfBytes) === expectedPdfSha256, 'Frozen PDF identity mismatch'); evidence.pdf = { filename: pdfFilename, path: pdfPath, bytes: pdfStat.size, sha256: sha256(pdfBytes), expectedBytes: expectedPdfBytes, expectedSha256: expectedPdfSha256, exactMatch: true }
    const codex = await stage(stages, 'codex_preflight', async () => { const version = await command('codex', ['--version']); const help = await command('codex', ['exec', '--help']); const inner = new CodexReasoningExecutor({ capabilities, timeoutMs, maxOutputChars, model, reasoningEffort }); const smoke = await inner.execute({ operation: 'understandAndPlan', instruction: 'Return a JSON object with one key named smoke and value ok. Return no other text.', input: { smoke: true }, outputContract: { type: 'object' }, metadata: { executionId: 'rhl-semantic-quality-001-codex-smoke' } }); evidence.environment = { codexCli: version, model, reasoningEffort, configuredCapabilities: capabilities, timeoutMs, terminationGraceMs: 5000, forcedTerminationWaitMs: 1500, maxOutputChars, codexHelpOutputBytes: Buffer.byteLength(help, 'utf8'), reasoningRuntime: inner.runtimeMetadata(), smoke: { operation: smoke.operation, outputBytes: Buffer.byteLength(String(smoke.rawOutput ?? smoke.output), 'utf8') } }; return inner })
    const parser = await stage(stages, 'docling_preflight', async () => { const pythonExecutable = process.env.RESEARCHHUB_PYTHON_EXECUTABLE ?? resolve(repoRoot, '..', 'ResearchHub', '.researchhub-document-parser', 'venv', 'Scripts', 'python.exe'); const artifactsPath = process.env.RESEARCHHUB_DOCLING_ARTIFACTS_PATH ?? resolve(repoRoot, '..', 'ResearchHub', '.researchhub-document-parser', 'models'); const bridgePath = process.env.RESEARCHHUB_DOCLING_BRIDGE ?? resolve(repoRoot, 'plugins', 'document', 'docling', 'bridge', 'docling_bridge.py'); await access(pythonExecutable); await access(artifactsPath); await access(bridgePath); process.env.RESEARCHHUB_PYTHON_EXECUTABLE = pythonExecutable; process.env.RESEARCHHUB_DOCLING_ARTIFACTS_PATH = artifactsPath; process.env.RESEARCHHUB_DOCLING_BRIDGE = bridgePath; return new DoclingDocumentParser({ pythonExecutable, artifactsPath, bridgePath }) })
    const resolver = new DocumentInputResolver({ documentParser: parser }); const document = await stage(stages, 'docling_parse', async () => { const acquired = await resolver.acquire({ type: 'file', reference: pdfPath }); const parsed = await parser.parse(acquired); evidence.environment = { ...(evidence.environment as Dict), docling: { parser: parsed.parser, stats: parsed.stats, warnings: parsed.warnings, pythonExecutable: process.env.RESEARCHHUB_PYTHON_EXECUTABLE, artifactsPath: process.env.RESEARCHHUB_DOCLING_ARTIFACTS_PATH } }; return parsed })
    kbRoot = resolve(repoRoot, 'runtime-data', 'knowledge-bases', knowledgeBaseId); await prepareFreshKnowledgeBase(kbRoot); const registry = new KnowledgeBaseRegistry(); const handle = await registry.mount(kbRoot); const initial = await validateKnowledgeBaseV03(kbRoot); assertCondition(initial.status === 'passed', 'Fresh Knowledge Base validation failed'); evidence.initialKnowledgeBase = { knowledgeBaseId, root: kbRoot, schemaVersion: '0.3', storageFormatVersion: '1', revision: 0, seedObjects: 0, counts: { themeGroups: 0, entities: 0, relations: 0, claims: 0, sources: 0, modules: 0 }, fullValidation: initial.status }
    recorder = new RecordingExecutor(codex); const skill = new KnowledgeCurationSkill({ executor: recorder }); const workflowInput = { handle, documentInput: { type: 'file' as const, reference: pdfPath }, skill, workflowRunId, sourceMetadata: { institution: '西部证券', publishedAt: '2026-08-05', title: 'AI算力行业：AI算力上游材料产业链研究报告' }, config: { maxExtractionUnits: 32, maxPlanAttempts: 2, maxExtractionAttempts: 2, maxConcurrency: 1, maxResolutionAttempts: 2, maxResolutionCases: 32, maxEntityBindingCandidates: 8, maxContextTokens: capabilities.maxContextTokens }, clock: () => '2026-09-05T00:00:00.000Z' }
    const primary = await stage(stages, 'primary_workflow', async () => runRawDocumentKnowledgeIngestion(workflowInput)); const rawRef = primary.rawRef; assertCondition(rawRef !== undefined, 'Primary workflow did not return Raw ref'); const raw = await getRaw(handle, rawRef); evidence.rawArchive = { rawRef, sizeBytes: raw.manifest.sizeBytes, contentHash: raw.manifest.contentHash, verified: (await verifyRaw(handle, rawRef)).valid }
    assertCondition(primary.status !== 'blocked', `Primary workflow blocked: ${primary.errors.join('; ')}`); assertCondition(primary.writeStatus === 'committed' && primary.baseRevision === 0 && primary.committedRevision === 1, 'Primary Writer did not commit revision 0 to 1'); assertCondition(primary.acceptedPlan !== undefined, 'Primary plan was not accepted');
    const plan = primary.acceptedPlan; const allBlocks = new Set(document.blocks.map((block) => block.blockId)); const primaryBlocks = new Set(plan.units.flatMap((unit) => unit.primaryBlockIds)); const excluded = new Set(plan.excludedBlockIds); const overlap = [...primaryBlocks].filter((id) => excluded.has(id)); const uncovered = [...allBlocks].filter((id) => !primaryBlocks.has(id) && !excluded.has(id)); assertCondition(overlap.length === 0 && uncovered.length === 0, 'Plan coverage invariant failed')
    evidence.plan = { attempts: primary.planAttempts, acceptedAttempt: primary.planAttempts?.find((item) => item.status === 'accepted')?.attempt, units: plan.units.length, primary: primaryBlocks.size, excluded: excluded.size, coverage: { allBlocks: allBlocks.size, primaryUnionExcluded: primaryBlocks.size + excluded.size, primaryExcludedOverlap: overlap.length, uncovered: uncovered.length, invariant: true }, contextRefs: plan.units.reduce((total, unit) => total + unit.contextRefs.length, 0), contextBlocks: new Set(plan.units.flatMap((unit) => unit.contextBlockIds)).size, estimatedContextTokens: plan.estimatedContextTokens }
    const extractionTotals = primary.unitSummaries.reduce((totals, unit) => ({ entity: totals.entity + Number(unit.candidateCounts.entity ?? 0), relation: totals.relation + Number(unit.candidateCounts.relation ?? 0), claim: totals.claim + Number(unit.candidateCounts.claim ?? 0), rejected: totals.rejected + unit.rejectedCount }), { entity: 0, relation: 0, claim: 0, rejected: 0 }); evidence.unitSummaries = primary.unitSummaries; evidence.extractionCandidateCounts = { ...extractionTotals, source: 'IngestionWorkflowResult.unitSummaries' }; evidence.candidateRejections = { total: primary.rejectedCandidates.length, samples: primary.rejectedCandidates.slice(0, 50), codes: countBy(primary.rejectedCandidates.map((item) => isDict(item) ? String(item.code) : 'unknown')) }; evidence.relationAttributeCandidateObservation = relationAttributeObservation(primary, recorder)
    const loaded = await new KnowledgeBaseLoaderV03(registry).load(handle); const reloadRevision = await readManifestRevision(kbRoot); evidence.reload = { revision: reloadRevision, counts: collectionCounts(loaded) }; assertCondition(reloadRevision === primary.committedRevision, 'Reload revision did not match committed revision'); const canonicalReport = await validateKnowledgeBaseV03(kbRoot); evidence.canonicalValidation = { status: canonicalReport.status }; assertCondition(canonicalReport.status === 'passed', 'Canonical validation failed after Writer'); evidence.provenance = provenance(loaded, rawRef); assertCondition((evidence.provenance as Dict).failures === 0, 'Provenance validation failed')
    const persisted = [...loaded.themeGroups, ...loaded.entities, ...loaded.relations, ...loaded.claims, ...loaded.sources, ...loaded.modules].map((asset) => asset.value as unknown as Dict); const leaks = persisted.filter((item) => /planned-(?:entity|relation|claim)-/.test(JSON.stringify(item)) || JSON.stringify(item).includes('candidateRef')); evidence.transientRefCheck = { leaks: leaks.length, samples: leaks.slice(0, 10).map((item) => bounded(item)) }; assertCondition(leaks.length === 0, 'Transient reference leak detected')
    const summary = primary.reviewSummary; evidence.resolutionObservation = { ...(primary.resolutionSummary ?? {}), semanticCaseTelemetry: recorder.semanticCases, resolutionReviewItems: primary.reviewItems.length }; evidence.consolidationObservation = { acceptedExtractionCandidateTotal: extractionTotals.entity + extractionTotals.relation + extractionTotals.claim, postConsolidation: { entity: Number(primary.resolutionSummary?.entities ?? 0), relation: Number(primary.resolutionSummary?.relations ?? 0), claim: Number(primary.resolutionSummary?.claims ?? 0), total: Number(primary.resolutionSummary?.intents ?? 0) }, consolidationReviewTotal: summary.total, source: 'IngestionWorkflowResult' }; evidence.optionalEntityFieldObservation = optionalEntityObservation(summary); evidence.dependencyReviewObservation = dependencyObservation(primary); const dependency = evidence.dependencyReviewObservation as Dict; assertCondition(Number(dependency.dependencyReviewsCausedByDescriptionFieldConflict ?? 0) === 0 && Number(dependency.dependencyReviewsCausedByLegalNameFieldConflict ?? 0) === 0, 'Description/legalName conflict caused dependency isolation'); evidence.reviewSummary = { ...summary, invariants: reviewInvariants(summary) }; evidence.descriptionCascadeObservation = { descriptionOnlyEntityUnresolved: false, descriptionOnlyRelationDependencyReview: Number(dependency.dependencyReviewsCausedByDescriptionFieldConflict ?? 0) > 0, descriptionOnlyClaimDependencyReview: Number(dependency.dependencyReviewsCausedByDescriptionFieldConflict ?? 0) > 0, basis: 'authoritative ReviewSummary and available dependency Review items' }; assertCondition((evidence.reviewSummary as Dict).invariants && ((evidence.reviewSummary as Dict).invariants as Dict).allHold === true, 'ReviewSummary invariant failed')
    const logPath = join(kbRoot, 'logs', 'ingestion', workflowRunId + '.yaml'); const log = parseYaml(await readFile(logPath, 'utf8'), logPath) as Dict; const operations = operationObservation(log); evidence.changeSetObservation = { ...operations, safeOperations: Number(operations.knowledgeCreates) + Number(operations.knowledgeUpdates) + Number((operations.sourceOperations as Dict).created) + Number((operations.sourceOperations as Dict).merged), changeSetId: primary.changeSetId, source: 'persisted ingestion log' }; evidence.changeSetValidation = { status: primary.validationSummary?.status ?? 'passed', errors: primary.validationSummary?.errors ?? [], warnings: primary.validationSummary?.warnings ?? [] }; assertCondition((evidence.changeSetValidation as Dict).status === 'passed', 'ChangeSet validation failed'); evidence.writer = { invocations: 1, status: primary.writeStatus, revisionBefore: primary.baseRevision, revisionAfter: primary.committedRevision }
    const latePlanner = primary.reviewItems.filter((item) => /Relation attributes are not Schema 0\.3 valid/i.test(item.rationale)).length; evidence.plannerAttributeGate = { latePlannerRelationAttributeReviewCount: latePlanner, expected: 0 }; assertCondition(latePlanner === 0, 'Late Planner Relation attribute Review observed')
    const beforeReplay = recorder.calls.length; const revisionBeforeReplay = await readManifestRevision(kbRoot); const replay = await stage(stages, 'exact_replay', async () => runRawDocumentKnowledgeIngestion(workflowInput)); const callsAfterReplay = recorder.calls.length; const replayCounts = await new KnowledgeBaseLoaderV03(registry).load(handle); const revisionAfterReplay = await readManifestRevision(kbRoot); const canonicalCountsUnchanged = stableJson(collectionCounts(replayCounts)) === stableJson(collectionCounts(loaded)); evidence.replay = { status: replay.status, writeStatus: replay.writeStatus, additionalReasoningCalls: callsAfterReplay - beforeReplay, revisionBefore: revisionBeforeReplay, revisionAfter: revisionAfterReplay, canonicalCountChanges: !canonicalCountsUnchanged, canonicalCountsUnchanged, sameStatus: replay.status === primary.status, sameReviewSummary: stableJson(replay.reviewSummary) === stableJson(primary.reviewSummary), sameChangeSetId: replay.changeSetId === primary.changeSetId, alreadyCommitted: replay.writeStatus === 'already_committed', idempotency: replay.writeStatus === 'already_committed' && callsAfterReplay - beforeReplay === 0 && revisionAfterReplay === revisionBeforeReplay }; assertCondition((evidence.replay as Dict).idempotency === true, 'Exact replay was not idempotent')
    const finalReport = await validateKnowledgeBaseV03(kbRoot); const finalLoaded = await new KnowledgeBaseLoaderV03(registry).load(handle); const finalRevision = await readManifestRevision(kbRoot); evidence.finalKnowledgeBase = { revision: finalRevision, counts: collectionCounts(finalLoaded), fullValidation: finalReport.status }; assertCondition(finalReport.status === 'passed' && finalRevision === primary.committedRevision, 'Final validation or revision check failed')
    const r7 = JSON.parse(await readFile(resolve(evidenceDir, 'rhl-validation-001-r7-real-e2e.json'), 'utf8')) as Dict; const r7Primary = isDict(r7.primary) ? r7.primary : {}; const currentReview = summary.total; const r7Review = isDict(r7Primary.reviewSummary) ? Number(r7Primary.reviewSummary.total ?? 311) : 311; evidence.r7Comparison = { metrics: { reviewTotal: { r7: r7Review, current: currentReview, delta: currentReview - r7Review }, rootReview: { r7: isDict(r7Primary.reviewSummary) ? r7Primary.reviewSummary.rootCount : 86, current: summary.rootCount, delta: summary.rootCount - (isDict(r7Primary.reviewSummary) ? Number(r7Primary.reviewSummary.rootCount ?? 86) : 86) }, dependencyReview: { r7: isDict(r7Primary.reviewSummary) ? r7Primary.reviewSummary.dependencyCount : 225, current: summary.dependencyCount, delta: summary.dependencyCount - (isDict(r7Primary.reviewSummary) ? Number(r7Primary.reviewSummary.dependencyCount ?? 225) : 225) }, invalidSemantics: { r7: isDict(r7Primary.reviewSummary) && isDict(r7Primary.reviewSummary.byCategory) ? r7Primary.reviewSummary.byCategory.invalid_semantics : 7, current: summary.byCategory.invalid_semantics, delta: summary.byCategory.invalid_semantics - (isDict(r7Primary.reviewSummary) && isDict(r7Primary.reviewSummary.byCategory) ? Number(r7Primary.reviewSummary.byCategory.invalid_semantics ?? 7) : 7) }, reconciliationReview: { r7: isDict(r7Primary.reviewSummary) && isDict(r7Primary.reviewSummary.byCategory) ? r7Primary.reviewSummary.byCategory.reconciliation_review : 274, current: summary.byCategory.reconciliation_review, delta: summary.byCategory.reconciliation_review - (isDict(r7Primary.reviewSummary) && isDict(r7Primary.reviewSummary.byCategory) ? Number(r7Primary.reviewSummary.byCategory.reconciliation_review ?? 274) : 274) }, other: { r7: isDict(r7Primary.reviewSummary) && isDict(r7Primary.reviewSummary.byCategory) ? r7Primary.reviewSummary.byCategory.other : 26, current: summary.byCategory.other, delta: summary.byCategory.other - (isDict(r7Primary.reviewSummary) && isDict(r7Primary.reviewSummary.byCategory) ? Number(r7Primary.reviewSummary.byCategory.other ?? 26) : 26) } }, interpretation: 'Descriptive comparison only; lower Review count is not treated as success.' }
    evidence.validationOutcome = 'SUCCESS'; evidence.failureClassification = null; evidence.failureStage = null; evidence.phase = 'completed'; evidence.completedAt = now(); await writeEvidence(evidence); await writeSummary(evidence); console.log(JSON.stringify({ outcome: evidence.validationOutcome, evidence: outputPath, summary: summaryPath, primary: { status: primary.status, candidateCounts: primary.candidateCounts, reviewSummary: primary.reviewSummary }, reload: evidence.finalKnowledgeBase, replay: evidence.replay }))
  } catch (error) { evidence.phase = 'blocked'; evidence.completedAt = now(); const message = errorText(error); evidence.validationOutcome = /reasoning_timeout|timed out/i.test(message) ? 'REASONING_FAILURE' : /Baseline|PDF|CODEX|Docling|working tree|not found|access/i.test(message) ? 'VALIDATION_ENVIRONMENT_FAILURE' : 'PRODUCT_DEFECT'; evidence.failureClassification = evidence.validationOutcome; evidence.failureStage = Object.entries(stages).find(([, value]) => value.status === 'failed')?.[0] ?? 'unknown'; evidence.error = message.slice(0, 2000); await writeEvidence(evidence); await writeSummary(evidence); console.error(JSON.stringify({ outcome: evidence.validationOutcome, stage: evidence.failureStage, error: evidence.error, evidence: outputPath, summary: summaryPath })); process.exitCode = 1 }
}

async function writeSummary(evidence: Dict): Promise<void> { const env = isDict(evidence.environment) ? evidence.environment : {}; const pdf = isDict(evidence.pdf) ? evidence.pdf : {}; const plan = isDict(evidence.plan) ? evidence.plan : {}; const extraction = isDict(evidence.extractionCandidateCounts) ? evidence.extractionCandidateCounts : {}; const relation = isDict(evidence.relationAttributeCandidateObservation) ? evidence.relationAttributeCandidateObservation : {}; const summary = isDict(evidence.reviewSummary) ? evidence.reviewSummary : {}; const finalKb = isDict(evidence.finalKnowledgeBase) ? evidence.finalKnowledgeBase : {}; const replay = isDict(evidence.replay) ? evidence.replay : {}; const outcome = String(evidence.validationOutcome ?? 'IN_PROGRESS'); const lines = ['# RHL-VALIDATION-SEMANTIC-QUALITY-001', '', `- Classification: **${outcome}**`, '- CTO acceptance: pending', `- Product baseline: \`${String(evidence.validationProductBaseline)}\``, `- PDF: ${String(pdf.filename ?? pdfFilename)}, ${String(pdf.bytes ?? 'n/a')} bytes, ${String(pdf.sha256 ?? 'n/a')}`, `- Docling: ${JSON.stringify(env.docling ?? {})}`, `- Codex: ${String(env.codexCli ?? 'n/a')}; model=${String(env.model ?? model)}; reasoning=${String(env.reasoningEffort ?? reasoningEffort)}`, `- Plan: ${String(plan.units ?? 'n/a')} units; primary=${String(plan.primary ?? 'n/a')}; excluded=${String(plan.excluded ?? 'n/a')}; coverage=${JSON.stringify(plan.coverage ?? {})}`, `- Extraction: Entity=${String(extraction.entity ?? 'n/a')}, Relation=${String(extraction.relation ?? 'n/a')}, Claim=${String(extraction.claim ?? 'n/a')}, rejected=${String(extraction.rejected ?? 'n/a')}`, `- Relation attribute Candidate boundary: accepted=${String(relation.relationCandidatesAccepted ?? 'n/a')}, rejected=${String(relation.relationCandidatesRejected ?? 'n/a')}, invalidAttribute=${String(relation.invalidRelationAttributeCandidateCount ?? 'n/a')}; Planner late attribute Reviews=${String((isDict(evidence.plannerAttributeGate) ? evidence.plannerAttributeGate.latePlannerRelationAttributeReviewCount : 'n/a'))}`, `- ReviewSummary: total=${String(summary.total ?? 'n/a')}, root=${String(summary.rootCount ?? 'n/a')}, dependency=${String(summary.dependencyCount ?? 'n/a')}`, `- Review invariants: ${JSON.stringify(summary.invariants ?? {})}`, '- Description cascade: description-only Unresolved/Relation dependency/Claim dependency = no/no/no', `- ChangeSet/Writer: ${JSON.stringify(evidence.changeSetObservation ?? {})}; ${JSON.stringify(evidence.writer ?? {})}`, `- Final KB: ${JSON.stringify(finalKb)}`, `- Provenance: ${JSON.stringify(evidence.provenance ?? {})}`, `- Replay: ${JSON.stringify(replay)}`, '', '## R7 Comparison', '', '| Metric | R7 | Current | Delta | Interpretation |', '|---|---:|---:|---:|---|']
  const comparison = isDict(evidence.r7Comparison) && isDict(evidence.r7Comparison.metrics) ? evidence.r7Comparison.metrics : {}; for (const [name, value] of Object.entries(comparison)) { const item = isDict(value) ? value : {}; lines.push(`| ${name} | ${String(item.r7 ?? 'n/a')} | ${String(item.current ?? 'n/a')} | ${String(item.delta ?? 'n/a')} | descriptive only |`) } lines.push('', 'Historical R1-R7 and timeout-smoke evidence were verified unchanged. No production code, Schema, Writer, architecture, prompt, policy, or historical evidence was modified by this validation task.', '', 'Residual risk: this is a single real Luna run; model output is not an exact-output oracle and semantic-quality interpretation remains pending CTO review.')
  await writeFile(summaryPath, lines.join('\n') + '\n')
}

await main()
