import assert from 'node:assert/strict'
import test from 'node:test'
import { evaluateThesisRedTeamPiGate, type ThesisRedTeamPiGateInput } from './thesis-red-team-pi-e2e-gate.ts'
const pass: ThesisRedTeamPiGateInput = { executed: true, actualPiReasoningExecutor: true, companyResolved: true, thesisResolved: true, dependencyClaimCount: 3, criticalAssumptionCount: 1, stageAFallback: false, attackVectorCount: 3, invalidationConditionCount: 1, stageBFallback: false, stageBSemanticValidated: true, invalidationAnalysisCount: 1, disconfirmingEvidenceCount: 1, challengeCount: 3, alternativeExplanationCount: 1, failureCaseCount: 1, affectedExistingClaimCount: 2, modelDerivedInterpretationCount: 3, thesisVerdict: 'weakened', acceptedProposalCount: 1, durableAppliedProposalCount: 1, canonicalClaimBindingCount: 1, qualifiedCanonicalSourceBinding: true, canonicalSourceCountDelta: 1, canonicalClaimCountDelta: 1, irrelevantSourceCanonicalized: false, signalCanonicalized: false, targetThesisChanged: false, thesisHashUnchanged: true, thesisLifecycleUnchanged: true, thesisSourceRefsUnchanged: true, thesisIdUnchanged: true, companyHashUnchanged: true, reportPersisted: true, reportSectionCount: 16, secretsRetained: false, rawBodiesRetained: false }
test('Thesis Red Team Pi gate blocks Stage B invalidation analysis missing', () => assert.equal(evaluateThesisRedTeamPiGate({ ...pass, invalidationAnalysisCount: 0 }).classification, 'REAL_MODEL_CONTRACT_BLOCKED'))
test('Thesis Red Team Pi gate passes the complete acceptance fixture', () => assert.deepEqual(evaluateThesisRedTeamPiGate(pass), { classification: 'EXECUTED / PASS GATE', exitCode: 0, reasons: [] }))
for (const field of ['stageAFallback', 'stageBFallback', 'syntheticSemanticRepair', 'targetThesisChanged', 'companyChanged', 'irrelevantSourceCanonicalized', 'unknownDateCanonicalized', 'reportPersisted'] as const) test(`Thesis Red Team Pi gate blocks ${field}`, () => { const input = { ...pass, [field]: field === 'reportPersisted' ? false : true }; assert.equal(evaluateThesisRedTeamPiGate(input).exitCode, 1) })
test('Thesis Red Team Pi gate does not require deterministic proposal construction', () => assert.equal(evaluateThesisRedTeamPiGate(pass).exitCode, 0))
test('Thesis Red Team Pi gate blocks missing qualified evidence', () => { assert.equal(evaluateThesisRedTeamPiGate({ ...pass, qualifiedDisconfirmingEvidenceCount: 0 }).exitCode, 1) })
test('Thesis Red Team Pi gate blocks inconsistent verdict', () => { assert.equal(evaluateThesisRedTeamPiGate({ ...pass, verdictConsistencyValid: false }).exitCode, 1) })
