import assert from 'node:assert/strict'
import { mkdtemp, rm } from 'node:fs/promises'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import test from 'node:test'
import { createFreshKnowledgeBaseV04, readCanonicalV04Assets } from '../../knowledge/storage/index.ts'
import { KnowledgeBaseRegistry } from '../../knowledge/registry/registry.ts'
import { KnowledgeProductionGateway } from '../../knowledge/production/gateway.ts'
import type { SemanticProductionProposal } from '../../knowledge/production/contracts.ts'
import type { NormalizedResearchSource, ResearchSourceCandidate } from '../../plugins/research-acquisition/contracts.ts'
import { sha256 } from '../../plugins/research-acquisition/hash.ts'

const NOW = '2026-09-10T00:00:00.000Z'
const rights = { accessScope: 'public' as const, retentionAllowed: true, aiProcessingAllowed: true, derivativeKnowledgeAllowed: true, redistributionAllowed: false }
function normalized(id: string, content: string): NormalizedResearchSource { const candidate: ResearchSourceCandidate = { candidateId: id, kind: 'official_disclosure', tier: 1, title: 'Generic Claim update evidence', provider: 'cninfo', url: `https://example.test/${id}`, publishedAt: NOW, metadata: { companySymbol: '600519' } }; return { candidate, retrievedAt: NOW, title: candidate.title, content, canonicalUrl: candidate.url, contentHash: sha256(content), rawBytes: new TextEncoder().encode(content), publisher: 'cninfo', rights } }

test('FIX-003 generic existing Claim update is producer-neutral and exact in place', async () => {
  const root = await mkdtemp(join(tmpdir(), 'rhl-thesis-gateway-'))
  try {
    await createFreshKnowledgeBaseV04(root, { knowledgeBaseId: 'kb-thesis-gateway', now: NOW })
    const registry = new KnowledgeBaseRegistry(); let handle = await registry.mount(root); const source = normalized('generic-source', 'verified update evidence')
    const seed = await new KnowledgeProductionGateway(registry).submit({ handle, producerType: 'fixture_seed', producerRunId: 'generic-seed', schemaProfile: { schemaVersion: '0.4', storageFormatVersion: '1', requiresRawProvenance: true }, entity: { localKey: 'company', entityType: 'company', name: 'Fixture Company', aliases: ['600519'], semanticFields: { ticker: '600519', exchange: 'SSE' } }, proposals: [{ proposalId: 'seed-assumption', kind: 'claim', claimType: 'assumption', subjectKey: 'company', statement: 'Demand remains resilient.', sourceCandidateIds: ['generic-source'], structuredValue: { metric: 'demand', value: true, unit: 'state', comparator: 'eq', period: 'current' } }], evidenceBindings: [{ localSourceId: 'generic-source', source }], asOf: NOW, now: () => NOW })
    assert.equal(seed.status, 'committed'); handle = await registry.mount(root); const before = await readCanonicalV04Assets(root); const existing = before.objects.find((item) => item.kind === 'claim' && (item.value as any).claimType === 'assumption')?.value as any; assert.ok(existing)
    const update = await new KnowledgeProductionGateway(registry).submit({ handle, producerType: 'fixture_generic', producerRunId: 'generic-update', schemaProfile: { schemaVersion: '0.4', storageFormatVersion: '1', requiresRawProvenance: true }, entity: { localKey: 'company', entityType: 'company', name: 'Fixture Company', aliases: ['600519'], semanticFields: { ticker: '600519', exchange: 'SSE' } }, proposals: [{ proposalId: 'generic-update', kind: 'claim', claimType: 'assumption', subjectKey: 'company', statement: existing.statement, sourceCandidateIds: ['generic-source'], existingKnowledgeRefs: [existing.id], resolution: 'update', structuredValue: { metric: 'demand', value: false, unit: 'state', comparator: 'eq', period: 'current' } }], evidenceBindings: [{ localSourceId: 'generic-source', source }], asOf: NOW, now: () => NOW })
    assert.equal(update.status, 'committed'); assert.deepEqual(update.updatedIds, [existing.id]); assert.equal(update.resolutionIntents.some((item) => item.disposition === 'bound_existing' && item.targetRef === existing.id), true)
    const after = await readCanonicalV04Assets(root); const changed = after.objects.find((item) => item.value.id === existing.id)?.value as any; assert.equal(changed.id, existing.id); assert.deepEqual({ claimType: changed.claimType, statement: changed.statement, subjectRefs: changed.subjectRefs, structuredValue: { ...changed.structuredValue, value: true } }, { claimType: existing.claimType, statement: existing.statement, subjectRefs: existing.subjectRefs, structuredValue: existing.structuredValue }); assert.equal(changed.structuredValue.value, false); assert.equal(changed.structuredValue.metric, existing.structuredValue.metric); assert.equal(changed.structuredValue.unit, existing.structuredValue.unit); assert.equal(changed.structuredValue.comparator, existing.structuredValue.comparator); assert.equal(changed.structuredValue.period, existing.structuredValue.period)
    handle = await registry.mount(root); const replay = await new KnowledgeProductionGateway(registry).submit({ handle, producerType: 'fixture_generic', producerRunId: 'generic-update-replay', schemaProfile: { schemaVersion: '0.4', storageFormatVersion: '1', requiresRawProvenance: true }, entity: { localKey: 'company', entityType: 'company', name: 'Fixture Company', aliases: ['600519'], semanticFields: { ticker: '600519', exchange: 'SSE' } }, proposals: [{ proposalId: 'generic-update-replay', kind: 'claim', claimType: 'assumption', subjectKey: 'company', statement: existing.statement, sourceCandidateIds: ['generic-source'], existingKnowledgeRefs: [existing.id], resolution: 'update', structuredValue: { metric: 'demand', value: false, unit: 'state', comparator: 'eq', period: 'current' } }], evidenceBindings: [{ localSourceId: 'generic-source', source }], asOf: NOW, now: () => NOW }); assert.equal(replay.status, 'no_changes'); assert.equal((await readCanonicalV04Assets(root)).objects.filter((item) => item.kind === 'claim').length, before.objects.filter((item) => item.kind === 'claim').length)
    const stableProposal: SemanticProductionProposal = { proposalId: 'stable-viewpoint-run-1', kind: 'claim', claimType: 'viewpoint', subjectKey: 'company', statement: 'The thesis remains materially challenged.', sourceCandidateIds: ['generic-source'], structuredValue: { metric: 'thesis_red_team_viewpoint_stable', value: true, unit: 'assessment', comparator: 'eq', period: 'current' } }
    handle = await registry.mount(root); const firstStableRun = await new KnowledgeProductionGateway(registry).submit({ handle, producerType: 'fixture_generic', producerRunId: 'stable-run-1', schemaProfile: { schemaVersion: '0.4', storageFormatVersion: '1', requiresRawProvenance: true }, entity: { localKey: 'company', entityType: 'company', name: 'Fixture Company', aliases: ['600519'], semanticFields: { ticker: '600519', exchange: 'SSE' } }, proposals: [stableProposal], evidenceBindings: [{ localSourceId: 'generic-source', source }], asOf: NOW, now: () => NOW }); assert.equal(firstStableRun.status, 'committed')
    const countAfterFirstStableRun = (await readCanonicalV04Assets(root)).objects.filter((item) => item.kind === 'claim').length
    handle = await registry.mount(root); const secondStableRun = await new KnowledgeProductionGateway(registry).submit({ handle, producerType: 'fixture_generic', producerRunId: 'stable-run-2', schemaProfile: { schemaVersion: '0.4', storageFormatVersion: '1', requiresRawProvenance: true }, entity: { localKey: 'company', entityType: 'company', name: 'Fixture Company', aliases: ['600519'], semanticFields: { ticker: '600519', exchange: 'SSE' } }, proposals: [{ ...stableProposal, proposalId: 'stable-viewpoint-run-2' }], evidenceBindings: [{ localSourceId: 'generic-source', source }], asOf: NOW, now: () => NOW }); assert.equal(secondStableRun.status, 'no_changes'); assert.equal((await readCanonicalV04Assets(root)).objects.filter((item) => item.kind === 'claim').length, countAfterFirstStableRun)
  } finally { await rm(root, { recursive: true, force: true }) }
})
