import { mkdir, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { AkshareDataAdapter } from '../../plugins/research-acquisition/akshare.ts'
import { validateUsableAcquisitionPayload } from '../../plugins/research-acquisition/payload-validation.ts'
import { normalizeValuationFinancialData, normalizeValuationMarketData, selectValuationBasis } from '../../skills/valuation/financials.ts'

const repoRoot = resolve(import.meta.dirname, '../..'); const evidenceDir = resolve(repoRoot, 'tests/validation/evidence'); const evidencePath = resolve(evidenceDir, 'RHL_M3A_VALUATION_V1_PROVIDER_SMOKE.json'); const now = '2026-09-09T00:00:00.000Z'; const adapter = new AkshareDataAdapter({ timeoutMs: 60_000 }); const calls = ['companyBasic', 'financialData', 'historicalMarketData'] as const; const results: Record<string, unknown> = {}; const payloads: Record<string, unknown> = {}
for (const method of calls) { const started = Date.now(); try { const payload = await adapter[method]({ symbol: '600519', ...(method === 'historicalMarketData' ? { endDate: '2026-09-09' } : {}) }); payloads[method] = payload; const usable = validateUsableAcquisitionPayload(payload); results[method] = { transport: 'PASS', usability: usable.status, reason: usable.reason, rowCount: Array.isArray(payload) ? payload.length : null, latencyMs: Date.now() - started } } catch (error) { const message = error instanceof Error ? error.message : String(error); results[method] = { transport: 'FAIL', usability: 'UNAVAILABLE', error: message.slice(0, 1_000), latencyMs: Date.now() - started } } }
const financial = results.financialData as { usability?: string } | undefined; const market = results.historicalMarketData as { usability?: string } | undefined; let basis: unknown = null; let normalizationError: string | undefined
try { const normalizedFinancial = normalizeValuationFinancialData(payloads.financialData); const normalizedMarket = normalizeValuationMarketData(payloads.historicalMarketData, now); const selected = selectValuationBasis(normalizedFinancial.rows, now); basis = { annualRowCount: normalizedFinancial.rows.length, marketFound: normalizedMarket.observation !== undefined, basisFiscalYear: selected.basis?.basisFiscalYear ?? null, publicationStatus: selected.publicationStatus ?? null, diagnostics: [...normalizedFinancial.diagnostics, ...normalizedMarket.diagnostics, ...selected.diagnostics] } } catch (error) { normalizationError = (error instanceof Error ? error.message : String(error)).slice(0, 1_000) }
const transportPass = calls.every((method) => (results[method] as { transport?: string } | undefined)?.transport === 'PASS'); const usable = financial?.usability === 'usable' && market?.usability === 'usable'; const evidence = { generatedAt: new Date().toISOString(), taskId: 'RHL-PERSONAL-RESEARCH-V1-M3A-VALUATION-001', classification: transportPass && usable ? 'PROVIDER_SMOKE_PASS' : transportPass ? 'PROVIDER_TRANSPORT_PASS_USABILITY_BLOCKED' : 'PROVIDER_TRANSPORT_BLOCKED', provider: 'AKShareDataAdapter', symbol: '600519', transportPass, usabilityPass: usable, calls: results, normalizedValuation: basis, ...(normalizationError === undefined ? {} : { normalizationError }), nonBlocking: true, secretsIncluded: false, rawBodiesIncluded: false }; await mkdir(evidenceDir, { recursive: true }); await writeFile(evidencePath, `${JSON.stringify(evidence, null, 2)}\n`, 'utf8'); console.log(JSON.stringify(evidence, null, 2))
