import type { KnowledgeBaseHandle } from '../../knowledge/storage/handle.ts'
import type { SemanticResolver, ResolutionIntentSummary } from '../../knowledge/production/contracts.ts'
import type { NormalizedResearchSource } from '../../plugins/research-acquisition/contracts.ts'
import type { ReasoningExecutor } from '../../plugins/reasoning/contracts.ts'
import type { IndustryTargetInput, ResearchDesign, IndustryModuleResult, CrossModuleSynthesis, ModuleEvidence } from '../../skills/industry-research/contracts.ts'

export interface IndustryAcquisitionWaveRequest { readonly target: IndustryTargetInput; readonly wave: 1 | 2; readonly design: ResearchDesign; readonly gaps: readonly string[]; readonly searchTerms: readonly string[] }
export type IndustryAcquisitionWave = (request: IndustryAcquisitionWaveRequest) => Promise<readonly NormalizedResearchSource[]>
export interface IndustryDeepResearchInput { readonly workflowRunId: string; readonly handle: KnowledgeBaseHandle; readonly target: IndustryTargetInput; readonly reportRoot: string; readonly reasoningExecutor: ReasoningExecutor; readonly acquisitionWave: IndustryAcquisitionWave; readonly semanticResolver?: SemanticResolver; readonly asOf?: string; readonly now?: () => string; readonly signal?: AbortSignal; readonly existingKnowledge?: readonly unknown[]; readonly maxSources?: number; readonly maxEvidencePerModule?: number }
export interface IndustryDeepResearchResult { readonly workflowRunId: string; readonly status: 'completed' | 'blocked' | 'cancelled' | 'failed'; readonly knowledgeBaseId: string; readonly knowledgeBaseRevision: number; readonly report?: { readonly reportId: string; readonly outputPath: string }; readonly design?: ResearchDesign; readonly modules: readonly IndustryModuleResult[]; readonly synthesis?: CrossModuleSynthesis; readonly evidence: readonly ModuleEvidence[]; readonly proposalIds: readonly string[]; readonly committedIds: readonly string[]; readonly sourceIds: readonly string[]; readonly relationIds: readonly string[]; readonly claimIds: readonly string[]; readonly entityRefs: Readonly<Record<string, string>>; readonly relationRefs: Readonly<Record<string, string>>; readonly claimRefs: Readonly<Record<string, string>>; readonly sourceRefs: Readonly<Record<string, string>>; readonly resolutionIntents: readonly ResolutionIntentSummary[]; readonly diagnostics: readonly string[]; readonly errors: readonly string[]; readonly gatewaySubmitCount: number; readonly acquisitionWaves: number; readonly moduleCallCounts: Readonly<Record<string, number>> }
