import { readCanonicalV04Assets } from '../../knowledge/storage/canonical-v04-loader.ts'
import { KnowledgeProductionGateway } from '../../knowledge/production/gateway.ts'
import { KnowledgeBaseRegistry } from '../../knowledge/registry/registry.ts'
import type { KnowledgeEntityV04 } from '../../knowledge/schema/domain-v04.ts'
import { KNOWLEDGE_SCHEMA_V04 } from '../../knowledge/schema/executable-schema-v04.ts'
import { validateUsableAcquisitionPayload } from '../../plugins/research-acquisition/payload-validation.ts'
import { validateRelationAttributesV03 } from '../../knowledge/validation/v03-validation-core.ts'
import type { NormalizedResearchSource } from '../../plugins/research-acquisition/contracts.ts'
import { IndustryResearchSkill } from '../../skills/industry-research/skill.ts'
import { INDUSTRY_MODULES, type IndustryModuleResult, type IndustryResearchModule, type ModuleEvidence } from '../../skills/industry-research/contracts.ts'
import type { SemanticProductionProposal } from '../../knowledge/production/contracts.ts'
import { validateResearchReport, writeResearchReport, type ResearchReport } from '../../app/services/research-report.ts'
import type { IndustryDeepResearchInput, IndustryDeepResearchResult } from './contracts.ts'

const safeId = /^[A-Za-z0-9][A-Za-z0-9._-]*$/
const moduleTitle: Record<IndustryResearchModule, string> = { industry_definition: 'Industry Scope & Definition', market_size_growth: 'Market Size & Growth', supply_demand_analysis: 'Demand Structure & Drivers', industry_chain_analysis: 'Industry Chain Map', competitive_landscape: 'Competitive Landscape', technology_evolution: 'Technology & Product Roadmap', company_mapping: 'Company Mapping & Exposure', risk_analysis: 'Risks & Invalidation Conditions' }
const sectionTitles = ['Executive Industry View', 'Industry Scope & Definition', 'Market Size & Growth', 'Demand Structure & Drivers', 'Supply, Capacity & Utilization', 'Supply-Demand Balance & Pricing', 'Industry Chain Map', 'Value Capture & Industry Economics', 'Competitive Landscape', 'Technology & Product Roadmap', 'Company Mapping & Exposure', 'Catalysts', 'Risks & Invalidation Conditions', 'Key Metrics & Monitoring', 'Research Gaps & Alternative Views', 'Methodology & Provenance'] as const
const relationTypes = new Set<string>(KNOWLEDGE_SCHEMA_V04.relation.types)
const abortIfNeeded = (signal?: AbortSignal) => { if (signal?.aborted) throw new Error('WORKFLOW_CANCELLED') }
const asOfOk = (source: NormalizedResearchSource, asOf: string) => source.candidate.publishedAt === undefined || Number.isNaN(Date.parse(source.candidate.publishedAt)) || Date.parse(source.candidate.publishedAt) <= Date.parse(asOf)
function emptyResult(input: IndustryDeepResearchInput, status: IndustryDeepResearchResult['status'], errors: readonly string[], extra: Partial<IndustryDeepResearchResult> = {}): IndustryDeepResearchResult { return { workflowRunId: input.workflowRunId, status, knowledgeBaseId: input.handle.knowledgeBaseId, knowledgeBaseRevision: input.handle.revision, modules: [], evidence: [], proposalIds: [], committedIds: [], sourceIds: [], relationIds: [], claimIds: [], entityRefs: {}, relationRefs: {}, claimRefs: {}, sourceRefs: {}, resolutionIntents: [], diagnostics: [], errors, gatewaySubmitCount: 0, acquisitionWaves: 0, moduleCallCounts: {}, ...extra } }
function project(objects: readonly { value: unknown }[], targets: readonly string[]): readonly unknown[] { const values = objects.map((x) => x.value as Record<string, unknown>); const ids = new Set(targets); if (!ids.size) return []; for (let depth = 0; depth < 1; depth++) { for (const x of values.filter((v) => String(v.id).startsWith('relation:'))) if (ids.has(x.sourceRef as string) || ids.has(x.targetRef as string)) { ids.add(String(x.id)); ids.add(String(x.sourceRef)); ids.add(String(x.targetRef)) } for (const x of values.filter((v) => String(v.id).startsWith('claim:'))) if (Array.isArray(x.subjectRefs) && x.subjectRefs.some((r) => ids.has(String(r)))) ids.add(String(x.id)) } return values.filter((x) => ids.has(String(x.id))).sort((a, b) => String(a.id).localeCompare(String(b.id))).slice(0, 80) }
function qualify(sources: readonly NormalizedResearchSource[], asOf: string, max: number, diagnostics: string[]): readonly NormalizedResearchSource[] { const out: NormalizedResearchSource[] = []; const seen = new Set<string>(); for (const source of sources) { const payload = validateUsableAcquisitionPayload(source.content); if (payload.status !== 'usable' || !source.content.trim() || !source.rights.retentionAllowed || !source.rights.aiProcessingAllowed || !source.rights.derivativeKnowledgeAllowed || !asOfOk(source, asOf)) { diagnostics.push(`Evidence rejected: ${source.candidate.candidateId}`); continue } if (seen.has(source.candidate.candidateId)) continue; seen.add(source.candidate.candidateId); out.push(source); if (out.length >= max) break } return out }
function gateProposals(modules: readonly IndustryModuleResult[], synthesis: { proposals: readonly SemanticProductionProposal[] }, evidence: readonly ModuleEvidence[], diagnostics: string[]): SemanticProductionProposal[] {
  const evidenceIds = new Set(evidence.map((e) => e.evidenceId)); const seen = new Set<string>(); const out: SemanticProductionProposal[] = []
  const all = [...modules.flatMap((m) => m.proposals), ...synthesis.proposals]
  const entities = new Map<string, string>([['industry', 'industry']]); const relations = new Set<string>(); const claims = new Map<string, SemanticProductionProposal>();
  for (const p of all) if (p.kind === 'entity' && !seen.has(p.proposalId) && ['company', 'industry', 'product', 'technology'].includes(p.entityType ?? '') && Boolean(p.entityName)) entities.set(p.subjectKey, p.entityType!)
  const sourceFor = (p: SemanticProductionProposal) => (p.sourceCandidateIds ?? []).map((id) => evidence.find((e) => e.evidenceId === id)?.source).filter((x): x is NonNullable<typeof x> => Boolean(x))
  const durableEvidence = (p: SemanticProductionProposal) => (p.sourceCandidateIds ?? []).length > 0 && (p.sourceCandidateIds ?? []).every((id) => evidenceIds.has(id))
  const structuredComplete = (v: unknown) => { if (!v || typeof v !== 'object' || Array.isArray(v)) return false; const x = v as Record<string, unknown>; return typeof x.metric === 'string' && x.metric.trim() !== '' && 'value' in x && (typeof x.value === 'number' ? Number.isFinite(x.value) : typeof x.value === 'string' ? x.value.trim() !== '' : typeof x.value === 'boolean') && typeof x.unit === 'string' && x.unit.trim() !== '' && typeof x.comparator === 'string' && x.comparator.trim() !== '' && (typeof x.period === 'string' && x.period.trim() !== '' || typeof x.fiscalPeriod === 'string' && x.fiscalPeriod.trim() !== '') }
  const semanticSlot = (p: SemanticProductionProposal) => { const v = p.structuredValue as Record<string, unknown> | null | undefined; return JSON.stringify({ subject: p.subjectKey, type: p.claimType, metric: v?.metric ?? null, period: v?.period ?? null, fiscalPeriod: v?.fiscalPeriod ?? null, geography: v?.geography ?? null, definition: v?.measurementDefinition ?? null, methodology: v?.sourceMethodology ?? null }) }
  for (const p of all) {
    if (seen.has(p.proposalId)) { diagnostics.push(`Duplicate local proposal rejected: ${p.proposalId}`); continue } seen.add(p.proposalId)
    if (p.kind === 'source') { diagnostics.push(`Source proposals are not durable inputs: ${p.proposalId}`); continue }
    if ((p.sourceCandidateIds ?? []).some((id) => !evidenceIds.has(id))) { diagnostics.push(`Unknown source ref rejected: ${p.proposalId}`); continue }
    if (p.kind === 'entity') { if (!entities.has(p.subjectKey) || !p.entityType || !p.entityName) diagnostics.push(`Invalid Entity proposal rejected: ${p.proposalId}`); else out.push(p); continue }
    if (!durableEvidence(p)) { diagnostics.push(`Missing durable evidence rejected: ${p.proposalId}`); continue }
    if (p.kind === 'relation') {
      const d = p.relationType ? KNOWLEDGE_SCHEMA_V04.relation.definitions[p.relationType as keyof typeof KNOWLEDGE_SCHEMA_V04.relation.definitions] : undefined; const sourceType = entities.get(p.subjectKey); const targetType = p.targetKey ? entities.get(p.targetKey) : undefined
      if (!d || !relationTypes.has(p.relationType ?? '') || !sourceType || !targetType || !(d.sourceTypes as readonly string[]).includes(sourceType) || !(d.targetTypes as readonly string[]).includes(targetType) || !validateRelationAttributesV03(p.relationType!, p.attributes).valid) { diagnostics.push(`Relation endpoint/type incompatibility rejected: ${p.proposalId}`); continue }
      if (p.relationType === 'supplier_of') { const sources = sourceFor(p); const admissible = sources.some((s) => s.candidate.tier <= 2 && (s.candidate.kind === 'official_disclosure' || s.candidate.kind === 'structured_data') && Boolean(s.publisher.trim()) && Boolean(s.title.trim()) && /(supplier|manufactur|procurement|vendor|supply chain)/i.test(`${s.title} ${s.content}`)); if (!admissible) { diagnostics.push(`Weak supplier_of evidence rejected: ${p.proposalId}`); continue } }
      relations.add(p.proposalId); out.push(p); continue
    }
    if (p.kind === 'claim') {
      if (!new Set(['fact', 'forecast', 'viewpoint', 'trend', 'risk', 'assumption', 'thesis', 'catalyst']).has(p.claimType ?? '') || !p.statement?.trim() || (!entities.has(p.subjectKey) && !relations.has(p.subjectKey)) || (p.structuredValue !== undefined && p.structuredValue !== null && !structuredComplete(p.structuredValue))) { diagnostics.push(`Invalid Claim or unresolved subject rejected: ${p.proposalId}`); continue }
      const slot = semanticSlot(p); const conflict = [...claims.values()].find((prior) => semanticSlot(prior) === slot && JSON.stringify(prior.structuredValue) !== JSON.stringify(p.structuredValue)); if (conflict) { diagnostics.push(`Unsupported same-slot conflict: ${conflict.proposalId}/${p.proposalId}`); continue }
      claims.set(p.proposalId, p); out.push(p)
    }
  }
  return out
}

export async function runIndustryDeepResearch(input: IndustryDeepResearchInput): Promise<IndustryDeepResearchResult> {
  const diagnostics: string[] = []; const counts: Record<string, number> = {}; let waves = 0; let gatewaySubmitCount = 0
  try {
    if (!safeId.test(input.workflowRunId) || !input.target.name.trim()) return emptyResult(input, 'failed', ['Invalid workflowRunId or Industry target'])
    if (input.handle.schemaVersion !== '0.4' || input.handle.storageFormatVersion !== '1') return emptyResult(input, 'failed', ['Industry Deep Research requires Schema 0.4 / Storage 1'])
    const assets = await readCanonicalV04Assets(input.handle.rootRef); const values = assets.objects.map((x) => x.value)
    let rootRef = input.target.canonicalRef
    if (rootRef) { const root = values.find((v) => v.id === rootRef) as KnowledgeEntityV04 | undefined; if (!root || root.type !== 'industry') return emptyResult(input, 'blocked', ['Supplied canonical ref must exist and be an Industry']) }
    const normalizedNames = new Set([input.target.name, ...(input.target.aliases ?? [])].map((x) => x.trim().toLowerCase()).filter(Boolean))
    const candidateRoots = rootRef ? [rootRef] : values.filter((v) => v.id?.startsWith('entity:') && (v as unknown as Record<string, unknown>).type === 'industry' && normalizedNames.has(String((v as unknown as Record<string, unknown>).name ?? '').trim().toLowerCase())).map((v) => String(v.id)).sort().slice(0, 5)
    const existing = input.existingKnowledge ?? project(assets.objects, candidateRoots)
    const skill = new IndustryResearchSkill(input.reasoningExecutor); abortIfNeeded(input.signal)
    const design = await skill.design({ target: input.target, existingKnowledge: existing })
    if (design.targetKind !== 'industry') return emptyResult(input, 'blocked', [`Bounded scope diagnosis: target is ${design.targetKind}, not one Industry`], { design })
    const now = input.now ?? (() => new Date().toISOString()); const asOf = input.asOf ?? input.target.asOf ?? now(); const maxSources = Math.max(1, Math.min(input.maxSources ?? 24, 50)); const maxPerModule = Math.max(1, Math.min(input.maxEvidencePerModule ?? 8, 12))
    waves++; const wave1 = qualify(await input.acquisitionWave({ target: input.target, wave: 1, design, gaps: design.knownGaps.map((g) => g.question), searchTerms: design.searchTerms }), asOf, maxSources, diagnostics)
    let evidence: ModuleEvidence[] = wave1.map((source) => ({ evidenceId: `evidence-${source.candidate.candidateId}`, source })); const modules: IndustryModuleResult[] = []
    const runModules = async (only?: ReadonlySet<IndustryResearchModule>) => { for (const module of INDUSTRY_MODULES) { if (only && !only.has(module)) continue; abortIfNeeded(input.signal); counts[module] = (counts[module] ?? 0) + 1; const question = design.moduleQuestions[module].toLowerCase(); const terms = new Set([module.replaceAll('_', ' '), input.target.name.toLowerCase(), ...question.split(/[^a-z0-9]+/).filter((x) => x.length > 3)]); const routed = evidence.filter((e) => { const metadata = e.source.candidate.metadata ?? {}; const hintValues = [metadata.module, metadata.modules, metadata.moduleHints, metadata.researchModules].flatMap((x) => Array.isArray(x) ? x : typeof x === 'string' ? [x] : []).map(String); if (hintValues.length) return hintValues.some((hint) => hint === module || hint.toLowerCase() === module.replaceAll('_', ' ')); const haystack = `${e.source.title} ${e.source.candidate.title} ${e.source.candidate.snippet ?? ''} ${e.source.content}`.toLowerCase(); return [...terms].some((term) => haystack.includes(term)) || (evidence.length <= 2 && e.source.candidate.kind === 'official_disclosure') }).slice(0, maxPerModule); modules.push(await skill.analyze(module, { target: input.target, designContext: { design, module }, evidence: routed, existingKnowledge: existing.slice(0, 80), localReferences: [] })) } }
    await runModules(); const firstGaps = modules.flatMap((m) => m.gaps).filter((g) => g.actionable); let affected = new Set<IndustryResearchModule>()
    if (firstGaps.length) { waves++; const wave2 = qualify(await input.acquisitionWave({ target: input.target, wave: 2, design, gaps: firstGaps.map((g) => g.question), searchTerms: [...new Set(firstGaps.flatMap((g) => g.searchTerms ?? []))] }), asOf, Math.max(0, maxSources - evidence.length), diagnostics); const prior = new Set(evidence.map((e) => e.evidenceId)); for (const source of wave2) { const e = { evidenceId: `evidence-${source.candidate.candidateId}`, source }; if (!prior.has(e.evidenceId)) evidence.push(e) } for (const gap of firstGaps) if (evidence.some((e) => (gap.searchTerms ?? []).some((term) => e.source.content.toLowerCase().includes(term.toLowerCase())) || e.source.content.toLowerCase().includes(gap.question.toLowerCase().slice(0, 12)))) affected.add(gap.module); if (affected.size) { for (let i = modules.length - 1; i >= 0; i--) if (affected.has(modules[i].module)) modules.splice(i, 1); await runModules(affected) } }
    const definition = modules.find((m) => m.module === 'industry_definition'); if (!definition || definition.status === 'unavailable') return emptyResult(input, 'blocked', ['Industry Definition is mandatory and unavailable after the bounded repair/gap-fill attempt'], { design, modules, evidence, diagnostics, acquisitionWaves: waves, moduleCallCounts: counts })
    const synthesis = await skill.synthesize({ modules, evidence }); const proposals = gateProposals(modules, synthesis, evidence, diagnostics); const gateway = new KnowledgeProductionGateway(new KnowledgeBaseRegistry()); const outcome = await gateway.submit({ handle: input.handle, producerType: 'industry_deep_research', producerRunId: input.workflowRunId, schemaProfile: { schemaVersion: '0.4', storageFormatVersion: '1', requiresRawProvenance: true }, entity: { localKey: 'industry', entityType: 'industry', name: input.target.name, aliases: input.target.aliases ?? [], existingEntityRef: rootRef }, proposals, evidenceBindings: evidence.map((e) => ({ localSourceId: e.evidenceId, source: e.source })), asOf, now, semanticResolver: input.semanticResolver })
    gatewaySubmitCount++
    if (outcome.status === 'blocked' || outcome.status === 'failed') return emptyResult(input, 'blocked', outcome.errors, { design, modules, synthesis, evidence, proposalIds: proposals.map((p) => p.proposalId), diagnostics, gatewaySubmitCount, acquisitionWaves: waves, moduleCallCounts: counts })
    const entityRefs = outcome.entityRefsByLocalKey; rootRef = entityRefs.industry; const relationRefs = outcome.relationRefsByProposalId; const claimRefs = outcome.claimRefsByProposalId; const sourceRefs = outcome.sourceRefsByLocalId
    const reloaded = await readCanonicalV04Assets(input.handle.rootRef); const canonicalIds = new Set<string>(reloaded.objects.map((x) => x.value.id)); const mappedRefs = [...Object.values(entityRefs), ...Object.values(relationRefs), ...Object.values(claimRefs), ...Object.values(sourceRefs)]; if (!rootRef || mappedRefs.some((id) => !canonicalIds.has(id))) return emptyResult(input, 'failed', ['Canonical reload missing a Gateway-mapped reference; report persistence refused'], { design, modules, synthesis, evidence, proposalIds: proposals.map((p) => p.proposalId), diagnostics, gatewaySubmitCount, acquisitionWaves: waves, moduleCallCounts: counts })
    const reportId = `industry-research-${input.workflowRunId}`; const byModule = new Map(modules.map((m) => [m.module, m.reportMaterial])); const allEvidence = Object.values(sourceRefs); const allClaims = Object.values(claimRefs); const sections = sectionTitles.map((title, index) => { const module = Object.entries(moduleTitle).find(([, t]) => t === title)?.[0] as IndustryResearchModule | undefined; const material = module ? byModule.get(module) : undefined; const markdown = index === 0 ? synthesis.executiveView : index === 15 ? 'Bounded Industry Research Design, qualified evidence, eight module analyses, one consolidated Gateway submission, canonical reload, and report persistence.' : material?.markdown ?? synthesis.reportMaterial.markdown; const localIds = material?.evidenceIds ?? synthesis.reportMaterial.evidenceIds; return { id: `section-${index + 1}`, title, markdown, sourceRefs: localIds.map((id) => sourceRefs[id]).filter((x): x is string => Boolean(x)), claimRefs: (material?.proposalIds ?? synthesis.reportMaterial.proposalIds).map((id) => claimRefs[id]).filter((x): x is string => Boolean(x)), relationRefs: (material?.relationProposalIds ?? []).map((id) => relationRefs[id]).filter((x): x is string => Boolean(x)) } })
    const report: ResearchReport = validateResearchReport({ reportId, reportType: 'industry_research', subjectRefs: rootRef ? [rootRef] : [], generatedAt: now(), asOf, workflowRunId: input.workflowRunId, knowledgeBaseRevision: outcome.knowledgeBaseRevision, sourceRefs: allEvidence, claimRefs: allClaims, methodology: 'Bounded design -> two-wave evidence qualification -> eight bounded modules -> deterministic gate -> one Gateway/Writer -> canonical reload.', sections, outputPath: `${reportId}.md` } as never); const outputPath = await writeResearchReport(report, input.reportRoot)
    return { workflowRunId: input.workflowRunId, status: 'completed', knowledgeBaseId: input.handle.knowledgeBaseId, knowledgeBaseRevision: outcome.knowledgeBaseRevision, report: { reportId, outputPath }, design, modules, synthesis, evidence, proposalIds: proposals.map((p) => p.proposalId), committedIds: outcome.createdIds, sourceIds: Object.values(sourceRefs), relationIds: Object.values(relationRefs), claimIds: Object.values(claimRefs), entityRefs, relationRefs, claimRefs, sourceRefs, resolutionIntents: outcome.resolutionIntents, diagnostics, errors: [], gatewaySubmitCount, acquisitionWaves: waves, moduleCallCounts: counts }
  } catch (error) { const message = error instanceof Error ? error.message : String(error); return emptyResult(input, message === 'WORKFLOW_CANCELLED' ? 'cancelled' : 'failed', [message], { diagnostics, gatewaySubmitCount, acquisitionWaves: waves, moduleCallCounts: counts }) }
}
