import { readCanonicalV04Assets } from '../../knowledge/storage/canonical-v04-loader.ts'
import { KnowledgeProductionGateway } from '../../knowledge/production/gateway.ts'
import { KnowledgeBaseRegistry } from '../../knowledge/registry/registry.ts'
import type { KnowledgeEntityV04 } from '../../knowledge/schema/domain-v04.ts'
import { KNOWLEDGE_SCHEMA_V04 } from '../../knowledge/schema/executable-schema-v04.ts'
import { validateUsableAcquisitionPayload } from '../../plugins/research-acquisition/payload-validation.ts'
import type { NormalizedResearchSource } from '../../plugins/research-acquisition/contracts.ts'
import { IndustryResearchSkill } from '../../skills/industry-research/skill.ts'
import { INDUSTRY_MODULES, type IndustryModuleResult, type IndustryResearchModule, type ModuleEvidence } from '../../skills/industry-research/contracts.ts'
import { validateResearchReport, writeResearchReport, type ResearchReport } from '../../app/services/research-report.ts'
import type { IndustryDeepResearchInput, IndustryDeepResearchResult } from './contracts.ts'

const safeId = /^[A-Za-z0-9][A-Za-z0-9._-]*$/
const moduleTitle: Record<IndustryResearchModule, string> = { industry_definition: 'Industry Scope & Definition', market_size_growth: 'Market Size & Growth', supply_demand_analysis: 'Demand Structure & Drivers', industry_chain_analysis: 'Industry Chain Map', competitive_landscape: 'Competitive Landscape', technology_evolution: 'Technology & Product Roadmap', company_mapping: 'Company Mapping & Exposure', risk_analysis: 'Risks & Invalidation Conditions' }
const sectionTitles = ['Executive Industry View', 'Industry Scope & Definition', 'Market Size & Growth', 'Demand Structure & Drivers', 'Supply, Capacity & Utilization', 'Supply-Demand Balance & Pricing', 'Industry Chain Map', 'Value Capture & Industry Economics', 'Competitive Landscape', 'Technology & Product Roadmap', 'Company Mapping & Exposure', 'Catalysts', 'Risks & Invalidation Conditions', 'Key Metrics & Monitoring', 'Research Gaps & Alternative Views', 'Methodology & Provenance'] as const
const relationTypes = new Set(KNOWLEDGE_SCHEMA_V04.relation.types)
const abortIfNeeded = (signal?: AbortSignal) => { if (signal?.aborted) throw new Error('WORKFLOW_CANCELLED') }
const asOfOk = (source: NormalizedResearchSource, asOf: string) => source.candidate.publishedAt === undefined || Number.isNaN(Date.parse(source.candidate.publishedAt)) || Date.parse(source.candidate.publishedAt) <= Date.parse(asOf)
function emptyResult(input: IndustryDeepResearchInput, status: IndustryDeepResearchResult['status'], errors: readonly string[], extra: Partial<IndustryDeepResearchResult> = {}): IndustryDeepResearchResult { return { workflowRunId: input.workflowRunId, status, knowledgeBaseId: input.handle.knowledgeBaseId, knowledgeBaseRevision: input.handle.revision, modules: [], evidence: [], proposalIds: [], committedIds: [], sourceIds: [], relationIds: [], claimIds: [], entityRefs: {}, relationRefs: {}, claimRefs: {}, sourceRefs: {}, resolutionIntents: [], diagnostics: [], errors, gatewaySubmitCount: 0, acquisitionWaves: 0, moduleCallCounts: {}, ...extra } }
function project(objects: readonly { value: unknown }[], target: string): readonly unknown[] { const values = objects.map((x) => x.value as Record<string, unknown>); const root = values.find((x) => x.id === target); if (!root) return []; const ids = new Set([target]); for (const x of values.filter((v) => String(v.id).startsWith('relation:'))) if (ids.has(x.sourceRef as string) || ids.has(x.targetRef as string)) { ids.add(String(x.id)); ids.add(String(x.sourceRef)); ids.add(String(x.targetRef)) } for (const x of values.filter((v) => String(v.id).startsWith('claim:'))) if (Array.isArray(x.subjectRefs) && x.subjectRefs.some((r) => ids.has(String(r)))) ids.add(String(x.id)); return values.filter((x) => ids.has(String(x.id))).sort((a, b) => String(a.id).localeCompare(String(b.id))).slice(0, 80) }
function qualify(sources: readonly NormalizedResearchSource[], asOf: string, max: number, diagnostics: string[]): readonly NormalizedResearchSource[] { const out: NormalizedResearchSource[] = []; const seen = new Set<string>(); for (const source of sources) { const payload = validateUsableAcquisitionPayload(source.content); if (payload.status !== 'usable' || !source.content.trim() || !source.rights.retentionAllowed || !source.rights.aiProcessingAllowed || !source.rights.derivativeKnowledgeAllowed || !asOfOk(source, asOf)) { diagnostics.push(`Evidence rejected: ${source.candidate.candidateId}`); continue } if (seen.has(source.candidate.candidateId)) continue; seen.add(source.candidate.candidateId); out.push(source); if (out.length >= max) break } return out }
function gateProposals(modules: readonly IndustryModuleResult[], synthesis: { proposals: readonly any[] }, evidence: readonly ModuleEvidence[], diagnostics: string[]): any[] { const evidenceIds = new Set(evidence.map((e) => e.evidenceId)); const seen = new Set<string>(); const out: any[] = []; const all = [...modules.flatMap((m) => m.proposals), ...synthesis.proposals]; for (const p of all) { if (seen.has(p.proposalId)) { diagnostics.push(`Duplicate local proposal dropped: ${p.proposalId}`); continue } seen.add(p.proposalId); if (p.sourceCandidateIds?.some((id: string) => !evidenceIds.has(id))) { diagnostics.push(`Unknown source ref dropped: ${p.proposalId}`); continue } if (p.kind === 'relation' && (!relationTypes.has(p.relationType) || !p.targetKey)) { diagnostics.push(`Unsupported relation dropped: ${p.proposalId}`); continue } if (p.kind === 'relation' && p.relationType === 'supplier_of') { const source = p.sourceCandidateIds?.map((id: string) => evidence.find((e) => e.evidenceId === id)?.source).find(Boolean); if (!source || source.candidate.tier > 2 || !/supplier|suppl(y|ies)|manufactur/i.test(source.content)) { diagnostics.push(`Weak supplier_of dropped: ${p.proposalId}`); continue } } if (p.kind === 'claim' && p.structuredValue && (typeof p.structuredValue !== 'object' || !('period' in p.structuredValue) || !('unit' in p.structuredValue) || !('metric' in p.structuredValue))) { diagnostics.push(`Incomplete quantitative claim dropped: ${p.proposalId}`); continue } out.push(p) } return out }

export async function runIndustryDeepResearch(input: IndustryDeepResearchInput): Promise<IndustryDeepResearchResult> {
  const diagnostics: string[] = []; const counts: Record<string, number> = {}; let waves = 0; let gatewaySubmitCount = 0
  try {
    if (!safeId.test(input.workflowRunId) || !input.target.name.trim()) return emptyResult(input, 'failed', ['Invalid workflowRunId or Industry target'])
    if (input.handle.schemaVersion !== '0.4' || input.handle.storageFormatVersion !== '1') return emptyResult(input, 'failed', ['Industry Deep Research requires Schema 0.4 / Storage 1'])
    const assets = await readCanonicalV04Assets(input.handle.rootRef); const values = assets.objects.map((x) => x.value)
    let rootRef = input.target.canonicalRef
    if (rootRef) { const root = values.find((v) => v.id === rootRef) as KnowledgeEntityV04 | undefined; if (!root || root.type !== 'industry') return emptyResult(input, 'blocked', ['Supplied canonical ref must exist and be an Industry']) }
    const existing = input.existingKnowledge ?? (rootRef ? project(assets.objects, rootRef) : [])
    const skill = new IndustryResearchSkill(input.reasoningExecutor); abortIfNeeded(input.signal)
    const design = await skill.design({ target: input.target, existingKnowledge: existing })
    if (design.targetKind !== 'industry') return emptyResult(input, 'blocked', [`Bounded scope diagnosis: target is ${design.targetKind}, not one Industry`], { design })
    const now = input.now ?? (() => new Date().toISOString()); const asOf = input.asOf ?? input.target.asOf ?? now(); const maxSources = Math.max(1, Math.min(input.maxSources ?? 24, 50)); const maxPerModule = Math.max(1, Math.min(input.maxEvidencePerModule ?? 8, 12))
    waves++; const wave1 = qualify(await input.acquisitionWave({ target: input.target, wave: 1, design, gaps: design.knownGaps.map((g) => g.question), searchTerms: design.searchTerms }), asOf, maxSources, diagnostics)
    let evidence: ModuleEvidence[] = wave1.map((source) => ({ evidenceId: `evidence-${source.candidate.candidateId}`, source })); const modules: IndustryModuleResult[] = []
    const runModules = async (only?: ReadonlySet<IndustryResearchModule>) => { for (const module of INDUSTRY_MODULES) { if (only && !only.has(module)) continue; abortIfNeeded(input.signal); counts[module] = (counts[module] ?? 0) + 1; const bounded = evidence.slice(0, maxPerModule); modules.push(await skill.analyze(module, { target: input.target, designContext: { design, module }, evidence: bounded, existingKnowledge: existing.slice(0, 80), localReferences: [] })) } }
    await runModules(); const firstGaps = modules.flatMap((m) => m.gaps).filter((g) => g.actionable); let affected = new Set<IndustryResearchModule>()
    if (firstGaps.length) { waves++; const wave2 = qualify(await input.acquisitionWave({ target: input.target, wave: 2, design, gaps: firstGaps.map((g) => g.question), searchTerms: [...new Set(firstGaps.flatMap((g) => g.searchTerms ?? []))] }), asOf, maxSources - evidence.length, diagnostics); const prior = new Set(evidence.map((e) => e.evidenceId)); for (const source of wave2) { const e = { evidenceId: `evidence-${source.candidate.candidateId}`, source }; if (!prior.has(e.evidenceId)) evidence.push(e) } for (const gap of firstGaps) if (evidence.some((e) => (gap.searchTerms ?? []).some((term) => e.source.content.toLowerCase().includes(term.toLowerCase())) || e.source.content.toLowerCase().includes(gap.question.toLowerCase().slice(0, 12)))) affected.add(gap.module); if (affected.size) { for (let i = modules.length - 1; i >= 0; i--) if (affected.has(modules[i].module)) modules.splice(i, 1); await runModules(affected) } }
    const synthesis = await skill.synthesize({ modules, evidence }); const proposals = gateProposals(modules, synthesis, evidence, diagnostics); const gateway = new KnowledgeProductionGateway(new KnowledgeBaseRegistry()); const outcome = await gateway.submit({ handle: input.handle, producerType: 'industry_deep_research', producerRunId: input.workflowRunId, schemaProfile: { schemaVersion: '0.4', storageFormatVersion: '1', requiresRawProvenance: true }, entity: { localKey: 'industry', entityType: 'industry', name: input.target.name, aliases: input.target.aliases ?? [], existingEntityRef: rootRef }, proposals, evidenceBindings: evidence.map((e) => ({ localSourceId: e.evidenceId, source: e.source })), asOf, now, semanticResolver: input.semanticResolver })
    gatewaySubmitCount++
    if (outcome.status === 'blocked' || outcome.status === 'failed') return emptyResult(input, 'blocked', outcome.errors, { design, modules, synthesis, evidence, proposalIds: proposals.map((p) => p.proposalId), diagnostics, gatewaySubmitCount, acquisitionWaves: waves, moduleCallCounts: counts })
    const entityRefs = outcome.entityRefsByLocalKey; rootRef = entityRefs.industry; const relationRefs = outcome.relationRefsByProposalId; const claimRefs = outcome.claimRefsByProposalId; const sourceRefs = outcome.sourceRefsByLocalId
    const reportId = `industry-research-${input.workflowRunId}`; const byModule = new Map(modules.map((m) => [m.module, m.reportMaterial])); const allEvidence = Object.values(sourceRefs); const allClaims = Object.values(claimRefs); const sections = sectionTitles.map((title, index) => { const module = Object.entries(moduleTitle).find(([, t]) => t === title)?.[0] as IndustryResearchModule | undefined; const material = module ? byModule.get(module) : undefined; const markdown = index === 0 ? synthesis.executiveView : index === 15 ? 'Bounded Industry Research Design, qualified evidence, eight module analyses, one consolidated Gateway submission, canonical reload, and report persistence.' : material?.markdown ?? synthesis.reportMaterial.markdown; const localIds = material?.evidenceIds ?? synthesis.reportMaterial.evidenceIds; return { id: `section-${index + 1}`, title, markdown, sourceRefs: localIds.map((id) => sourceRefs[id]).filter((x): x is string => Boolean(x)), claimRefs: (material?.proposalIds ?? synthesis.reportMaterial.proposalIds).map((id) => claimRefs[id]).filter((x): x is string => Boolean(x)), relationRefs: (material?.relationProposalIds ?? []).map((id) => relationRefs[id]).filter((x): x is string => Boolean(x)) } })
    const report: ResearchReport = validateResearchReport({ reportId, reportType: 'industry_research', subjectRefs: rootRef ? [rootRef] : [], generatedAt: now(), asOf, workflowRunId: input.workflowRunId, knowledgeBaseRevision: outcome.knowledgeBaseRevision, sourceRefs: allEvidence, claimRefs: allClaims, methodology: 'Bounded design -> two-wave evidence qualification -> eight bounded modules -> deterministic gate -> one Gateway/Writer -> canonical reload.', sections, outputPath: `${reportId}.md` } as never); const outputPath = await writeResearchReport(report, input.reportRoot)
    return { workflowRunId: input.workflowRunId, status: 'completed', knowledgeBaseId: input.handle.knowledgeBaseId, knowledgeBaseRevision: outcome.knowledgeBaseRevision, report: { reportId, outputPath }, design, modules, synthesis, evidence, proposalIds: proposals.map((p) => p.proposalId), committedIds: outcome.createdIds, sourceIds: Object.values(sourceRefs), relationIds: Object.values(relationRefs), claimIds: Object.values(claimRefs), entityRefs, relationRefs, claimRefs, sourceRefs, resolutionIntents: outcome.resolutionIntents, diagnostics, errors: [], gatewaySubmitCount, acquisitionWaves: waves, moduleCallCounts: counts }
  } catch (error) { const message = error instanceof Error ? error.message : String(error); return emptyResult(input, message === 'WORKFLOW_CANCELLED' ? 'cancelled' : 'failed', [message], { diagnostics, gatewaySubmitCount, acquisitionWaves: waves, moduleCallCounts: counts }) }
}
