import { KNOWLEDGE_SCHEMA_V04 } from '../schema/executable-schema-v04.ts'
import { getMetricDefinitionV04 } from '../schema/metric-registry.ts'
import type { ClaimTypeV04, KnowledgeAssetV04, KnowledgeClaimV04, KnowledgeEntityV04, KnowledgeEventV04, KnowledgeObservationV04, KnowledgeReasoningEdgeV04, KnowledgeRelationV04, KnowledgeSourceV04, KnowledgeThesisV04 } from '../schema/domain-v04.ts'
import { validateRelationAttributesV03 } from './v03-validation-core.ts'

export interface KnowledgeV04Diagnostic { readonly code: string; readonly message: string; readonly assetId?: string }
export interface KnowledgeV04ValidationReport { readonly status: 'passed' | 'failed'; readonly errors: readonly KnowledgeV04Diagnostic[] }

const CLAIM_TYPES = new Set<ClaimTypeV04>(KNOWLEDGE_SCHEMA_V04.claim.types)
const SOURCE_TYPES = new Set(KNOWLEDGE_SCHEMA_V04.source.types)
const SOURCE_RELIABILITIES = new Set(KNOWLEDGE_SCHEMA_V04.source.reliabilities)
const ENTITY_TYPES = new Set(KNOWLEDGE_SCHEMA_V04.entity.types)
const EVENT_TYPES = new Set(KNOWLEDGE_SCHEMA_V04.event.types)
const OBSERVATION_TYPES = new Set(KNOWLEDGE_SCHEMA_V04.observation.types)
const THESIS_STATUSES = new Set(KNOWLEDGE_SCHEMA_V04.thesis.statuses)
const EDGE_TYPES = new Set(KNOWLEDGE_SCHEMA_V04.reasoningEdge.types)
const RAW_PATTERN = /^raw-sha256-[0-9a-f]{64}$/
const HASH_PATTERN = /^[0-9a-f]{64}$/
const SAFE_ID = /^[A-Za-z0-9][A-Za-z0-9._-]*$/
type Dict = Record<string, unknown>
const record = (value: unknown): value is Dict => typeof value === 'object' && value !== null && !Array.isArray(value)
const date = (value: unknown): boolean => typeof value === 'string' && value.trim() !== '' && !Number.isNaN(Date.parse(value))
const nullableDate = (value: unknown): boolean => value === undefined || value === null || date(value)
const inRange = (value: unknown): boolean => typeof value === 'number' && Number.isFinite(value) && value >= 0 && value <= 1
const ref = (value: unknown, prefix: string): value is string => typeof value === 'string' && value.startsWith(prefix) && SAFE_ID.test(value.slice(prefix.length))
const arrayOfRefs = (value: unknown, prefix: string): value is string[] => Array.isArray(value) && value.every((item) => ref(item, prefix)) && new Set(value).size === value.length
function add(errors: KnowledgeV04Diagnostic[], code: string, message: string, assetId?: string): void { errors.push({ code, message, ...(assetId === undefined ? {} : { assetId }) }) }

function validateExternalIdentifiers(value: unknown, sources: ReadonlySet<string>, errors: KnowledgeV04Diagnostic[], id: string): void {
  if (value === undefined) return
  if (!Array.isArray(value)) { add(errors, 'V04_EXTERNAL_IDENTIFIERS', 'externalIdentifiers must be an array', id); return }
  for (const item of value) { if (!record(item) || typeof item.namespace !== 'string' || item.namespace.trim() === '' || typeof item.value !== 'string' || item.value.trim() === '') { add(errors, 'V04_EXTERNAL_IDENTIFIERS', 'ExternalIdentifier requires namespace and value', id); continue } if (!nullableDate(item.validFrom) || !nullableDate(item.validUntil)) add(errors, 'V04_EXTERNAL_IDENTIFIERS', 'ExternalIdentifier validity dates are invalid', id); if (item.sourceRef !== undefined && item.sourceRef !== null && !sources.has(String(item.sourceRef))) add(errors, 'V04_EXTERNAL_IDENTIFIER_SOURCE', `ExternalIdentifier sourceRef does not resolve: ${String(item.sourceRef)}`, id); if (item.confidence !== undefined && item.confidence !== null && !inRange(item.confidence)) add(errors, 'V04_EXTERNAL_IDENTIFIERS', 'ExternalIdentifier confidence must be between 0 and 1', id) }
}

function validateSource(source: KnowledgeSourceV04, errors: KnowledgeV04Diagnostic[]): void {
  const id = source.id
  if (!ref(id, 'source:')) add(errors, 'V04_SOURCE_ID', 'Source id must use source: namespace', id)
  if (typeof source.title !== 'string' || source.title.trim() === '') add(errors, 'V04_REQUIRED_FIELD', 'Source title is required', id)
  if (!SOURCE_TYPES.has(source.sourceType)) add(errors, 'V04_SOURCE_TYPE', 'Source sourceType is not declared by Schema 0.4', id)
  if (source.sourceReliability !== undefined && !SOURCE_RELIABILITIES.has(source.sourceReliability)) add(errors, 'V04_SOURCE_RELIABILITY', 'Source reliability is invalid', id)
  if (!nullableDate(source.publishedAt) || !nullableDate(source.retrievedAt)) add(errors, 'V04_SOURCE_DATE', 'Source publishedAt/retrievedAt must be dates or null', id)
  if (source.canonicalUrl !== undefined && source.canonicalUrl !== null && typeof source.canonicalUrl !== 'string') add(errors, 'V04_CANONICAL_URL', 'canonicalUrl must be a string or null', id)
  if (source.contentHash !== undefined && source.contentHash !== null && (typeof source.contentHash !== 'string' || !HASH_PATTERN.test(source.contentHash))) add(errors, 'V04_CONTENT_HASH', 'contentHash must be a lowercase SHA-256 hex string or null', id)
  if (!record(source.rights)) add(errors, 'V04_SOURCE_RIGHTS', 'Source rights metadata is required', id)
  else { const rights = source.rights; if (!['public', 'authenticated', 'restricted', 'unknown'].includes(String(rights.accessScope))) add(errors, 'V04_SOURCE_RIGHTS', 'rights.accessScope is invalid', id); if (typeof rights.providerTermsKnown !== 'boolean') add(errors, 'V04_SOURCE_RIGHTS', 'rights.providerTermsKnown must be boolean', id); for (const field of ['retentionAllowed', 'aiProcessingAllowed', 'derivativeKnowledgeAllowed', 'redistributionAllowed']) { const item = rights[field]; if (item !== undefined && item !== null && typeof item !== 'boolean' && item !== 'conditional') add(errors, 'V04_SOURCE_RIGHTS', `rights.${field} must be boolean, conditional, or null`, id) } if (!nullableDate(rights.expiresAt)) add(errors, 'V04_SOURCE_RIGHTS', 'rights.expiresAt must be a date or null', id) }
  if (!record(source.usagePolicy)) add(errors, 'V04_USAGE_POLICY', 'Source usagePolicy metadata is required', id)
  else if (source.usagePolicy.mode !== 'personal_noncommercial_research' || typeof source.usagePolicy.retainRaw !== 'boolean' || typeof source.usagePolicy.allowAiProcessing !== 'boolean' || typeof source.usagePolicy.allowDerivedKnowledge !== 'boolean' || source.usagePolicy.redistributionAllowed !== false) add(errors, 'V04_USAGE_POLICY', 'usagePolicy contains invalid operational values', id)
  if (source.acquisition !== undefined && source.acquisition !== null && !record(source.acquisition)) add(errors, 'V04_ACQUISITION', 'acquisition must be an object or null', id)
  if (source.rawRefs !== undefined && (!Array.isArray(source.rawRefs) || source.rawRefs.some((item) => !RAW_PATTERN.test(item)))) add(errors, 'V04_RAW_REF', 'Source rawRefs must be valid RawRef values', id)
}

function validateEntity(entity: KnowledgeEntityV04, sources: ReadonlySet<string>, errors: KnowledgeV04Diagnostic[]): void {
  const id = entity.id
  if (!ref(id, 'entity:')) add(errors, 'V04_ENTITY_ID', 'Entity id must use entity: namespace', id)
  if (!ENTITY_TYPES.has(entity.type)) add(errors, 'V04_ENTITY_TYPE', 'Entity type is invalid', id)
  if (typeof entity.name !== 'string' || entity.name.trim() === '') add(errors, 'V04_REQUIRED_FIELD', 'Entity name is required', id)
  if (!record(entity.lifecycle) || typeof entity.lifecycle.status !== 'string') add(errors, 'V04_LIFECYCLE', 'Entity lifecycle is required', id)
  validateExternalIdentifiers((entity as unknown as Dict).externalIdentifiers, sources, errors, id)
  if (entity.type === 'security') { const security = entity as Extract<KnowledgeEntityV04, { type: 'security' }>; if (typeof security.ticker !== 'string' || security.ticker.trim() === '' || typeof security.exchange !== 'string' || security.exchange.trim() === '' || !['equity', 'bond', 'fund', 'adr', 'other'].includes(security.securityType)) add(errors, 'V04_SECURITY_IDENTITY', 'Security requires ticker, exchange, and securityType', id) }
  if (entity.type === 'institution' && (entity as Extract<KnowledgeEntityV04, { type: 'institution' }>).institutionType !== undefined && !['broker', 'investment_bank', 'fund', 'regulator', 'industry_association', 'research_institution', 'media_organization', 'other'].includes(String((entity as unknown as Dict).institutionType))) add(errors, 'V04_INSTITUTION_TYPE', 'Institution type is invalid', id)
}

function validateClaim(claim: KnowledgeClaimV04, sources: ReadonlySet<string>, claims: ReadonlySet<string>, errors: KnowledgeV04Diagnostic[]): void {
  const id = claim.id
  if (!ref(id, 'claim:')) add(errors, 'V04_CLAIM_ID', 'Claim id must use claim: namespace', id)
  if (!CLAIM_TYPES.has(claim.claimType)) add(errors, 'V04_CLAIM_TYPE', 'Claim type is invalid', id)
  if (typeof claim.statement !== 'string' || claim.statement.trim() === '') add(errors, 'V04_REQUIRED_FIELD', 'Claim statement is required', id)
  if (!Array.isArray(claim.subjectRefs) || claim.subjectRefs.length === 0 || claim.subjectRefs.some((item) => (!String(item).startsWith('entity:') && !String(item).startsWith('relation:')))) add(errors, 'V04_SUBJECT_REFS', 'Claim subjectRefs must use Entity or Relation references', id)
  if (!Array.isArray(claim.sourceRefs) || claim.sourceRefs.length === 0) add(errors, 'V04_SOURCE_REFERENCE_REQUIRED', 'Claim must contain at least one Source reference', id)
  else for (const sourceRef of claim.sourceRefs) if (!sources.has(sourceRef)) add(errors, 'V04_MISSING_SOURCE_REF', `Claim sourceRef does not resolve: ${sourceRef}`, id)
  if (claim.confidence !== undefined && claim.confidence !== null && !inRange(claim.confidence)) add(errors, 'V04_CONFIDENCE', 'confidence must be between 0 and 1', id)
  if (claim.claimType === 'forecast' && !inRange(claim.probability)) add(errors, 'V04_PROBABILITY', 'Forecast probability is required and must be between 0 and 1', id)
  if (claim.claimType !== 'forecast' && claim.probability !== undefined && claim.probability !== null) add(errors, 'V04_PROBABILITY', 'probability is only valid for forecast claims', id)
  if (claim.provenance !== undefined) for (const item of claim.provenance) { if (!sources.has(item.sourceRef)) add(errors, 'V04_MISSING_PROVENANCE_SOURCE', `Provenance sourceRef does not resolve: ${item.sourceRef}`, id); if (!RAW_PATTERN.test(item.rawRef)) add(errors, 'V04_PROVENANCE_RAW_REF', 'Provenance rawRef is invalid', id) }
  if (claim.structuredValue !== undefined && claim.structuredValue !== null) { const structured = claim.structuredValue as unknown as Dict; if (Object.keys(structured).some((key) => !(KNOWLEDGE_SCHEMA_V04.claim.structuredValueFields as readonly string[]).includes(key)) || typeof structured.metric !== 'string' || structured.metric.trim() === '' || !('value' in structured) || !('unit' in structured) || (structured.unit !== null && typeof structured.unit !== 'string') || !('comparator' in structured) || (structured.comparator !== null && !KNOWLEDGE_SCHEMA_V04.claim.comparators.includes(structured.comparator as never)) || ['period', 'fiscalPeriod', 'semanticKey'].some((field) => structured[field] !== undefined && structured[field] !== null && typeof structured[field] !== 'string')) add(errors, 'V04_STRUCTURED_VALUE', 'Claim structuredValue is not valid for Schema 0.4', id) }
  for (const field of ['supportsClaimRefs', 'dependsOnClaimRefs', 'contradictsClaimRefs'] as const) for (const target of claim[field] ?? []) { if (!claims.has(target)) add(errors, 'V04_MISSING_CLAIM_REF', `${field} does not resolve: ${target}`, id); if (target === id) add(errors, 'V04_SELF_REFERENCE', `${field} cannot reference the same claim`, id) }
}

function validateEvent(event: KnowledgeEventV04, ids: ReadonlySet<string>, sources: ReadonlySet<string>, errors: KnowledgeV04Diagnostic[]): void {
  const id = event.id
  if (!ref(id, 'event:') || !EVENT_TYPES.has(event.eventType) || typeof event.title !== 'string' || event.title.trim() === '') add(errors, 'V04_EVENT', 'Event requires a valid id, eventType, and title', id)
  if (!arrayOfRefs(event.subjectRefs, 'entity:') || event.subjectRefs.some((item) => !ids.has(item))) add(errors, 'V04_EVENT_SUBJECT', 'Event subjectRefs must resolve to Entity objects', id)
  if (event.participantRefs !== undefined && (!arrayOfRefs(event.participantRefs, 'entity:') || event.participantRefs.some((item) => !ids.has(item)))) add(errors, 'V04_EVENT_PARTICIPANT', 'Event participantRefs must resolve to Entity objects', id)
  if (!record(event.temporal)) add(errors, 'V04_EVENT_TEMPORAL', 'Event temporal object is required', id)
  else for (const field of ['occurredAt', 'start', 'end', 'announcedAt'] as const) if (!nullableDate(event.temporal[field])) add(errors, 'V04_EVENT_TEMPORAL', `Event temporal.${field} is invalid`, id)
  if (!Array.isArray(event.sourceRefs) || event.sourceRefs.length === 0 || event.sourceRefs.some((item) => !sources.has(item))) add(errors, 'V04_EVENT_SOURCE', 'Event sourceRefs must resolve to Source objects', id)
  validateExternalIdentifiers(event.externalIdentifiers, sources, errors, id)
}

function validateObservation(observation: KnowledgeObservationV04, ids: ReadonlySet<string>, sources: ReadonlySet<string>, observations: ReadonlySet<string>, errors: KnowledgeV04Diagnostic[]): void {
  const id = observation.id
  if (!ref(id, 'observation:') || !OBSERVATION_TYPES.has(observation.observationType)) add(errors, 'V04_OBSERVATION', 'Observation id or observationType is invalid', id)
  if (!ids.has(observation.subjectRef) || !ref(observation.subjectRef, 'entity:')) add(errors, 'V04_OBSERVATION_SUBJECT', 'Observation subjectRef must resolve to an Entity', id)
  if (!getMetricDefinitionV04(observation.metricRef)) add(errors, 'V04_METRIC_REF', `Metric is not registered: ${String(observation.metricRef)}`, id)
  if (observation.observationType === 'metric') { if (!('value' in observation) || !observation.sourceRef || !sources.has(observation.sourceRef)) add(errors, 'V04_METRIC_OBSERVATION', 'MetricObservation requires value and Source', id); for (const field of ['observedAt', 'reportedAt', 'asOf'] as const) if (!nullableDate(observation[field])) add(errors, 'V04_OBSERVATION_TIME', `MetricObservation ${field} is invalid`, id) }
  else if (observation.observationType === 'estimate') { if (!ids.has(observation.institutionRef) || !ref(observation.institutionRef, 'entity:') || (observation.analystRef !== undefined && observation.analystRef !== null && (!ids.has(observation.analystRef) || !ref(observation.analystRef, 'entity:')))) add(errors, 'V04_ESTIMATE_PARTY', 'Estimate institutionRef/analystRef must resolve to Entity objects', id); if (!date(observation.publishedAt) || !observation.sourceRef || !sources.has(observation.sourceRef)) add(errors, 'V04_ESTIMATE_OBSERVATION', 'EstimateObservation requires publishedAt and Source', id); if (observation.revisionOf !== undefined && observation.revisionOf !== null && !observations.has(observation.revisionOf)) add(errors, 'V04_ESTIMATE_REVISION', 'Estimate revisionOf does not resolve', id) }
  else if (observation.observationType === 'consensus') { if (!Number.isInteger(observation.count) || observation.count < 1 || !Number.isFinite(observation.mean) || !arrayOfRefs(observation.contributingObservationRefs, 'observation:') || observation.contributingObservationRefs.some((item) => !observations.has(item))) add(errors, 'V04_CONSENSUS_OBSERVATION', 'ConsensusObservation requires count, mean, and contributing observations', id); if (observation.sourceRef !== undefined && observation.sourceRef !== null && !sources.has(observation.sourceRef)) add(errors, 'V04_CONSENSUS_SOURCE', 'Consensus sourceRef does not resolve', id); if (!date(observation.asOf)) add(errors, 'V04_OBSERVATION_TIME', 'Consensus asOf is required', id) }
}

function validateThesis(thesis: KnowledgeThesisV04, ids: ReadonlySet<string>, errors: KnowledgeV04Diagnostic[]): void { const id = thesis.id; if (!ref(id, 'thesis:') || !Array.isArray(thesis.subjectRefs) || thesis.subjectRefs.length === 0 || thesis.subjectRefs.some((item) => !ids.has(item) || !ref(item, 'entity:')) || typeof thesis.title !== 'string' || thesis.title.trim() === '' || typeof thesis.statement !== 'string' || thesis.statement.trim() === '' || !THESIS_STATUSES.has(thesis.status) || !date(thesis.createdAt)) add(errors, 'V04_THESIS', 'Thesis requires valid identity, subject, title, statement, status, and createdAt', id) }

function validateReasoningEdge(edge: KnowledgeReasoningEdgeV04, objects: ReadonlyMap<string, KnowledgeAssetV04>, sources: ReadonlySet<string>, errors: KnowledgeV04Diagnostic[]): void { const id = edge.id; const source = objects.get(edge.sourceRef); const target = objects.get(edge.targetRef); const sourceKind = source?.id.split(':', 1)[0]; const targetKind = target?.id.split(':', 1)[0]; if (!ref(id, 'reasoning-edge:') || !EDGE_TYPES.has(edge.type) || !source || !target) add(errors, 'V04_REASONING_EDGE', 'ReasoningEdge requires resolvable endpoints', id); if (!((sourceKind === 'observation' || sourceKind === 'claim') && (targetKind === 'claim' || targetKind === 'thesis'))) add(errors, 'V04_REASONING_ENDPOINT', 'ReasoningEdge endpoints must be Observation/Claim to Claim/Thesis', id); if (edge.sourceRef === edge.targetRef || sourceKind === 'source' || sourceKind === 'raw-sha256-' || sourceKind === 'theme-group') add(errors, 'V04_REASONING_ENDPOINT', 'ReasoningEdge endpoint is not an admissible research dependency', id); if (edge.sourceRefs?.some((item) => !sources.has(item))) add(errors, 'V04_REASONING_SOURCE', 'ReasoningEdge sourceRefs must resolve to Source objects', id); if (edge.confidence !== undefined && edge.confidence !== null && !inRange(edge.confidence)) add(errors, 'V04_CONFIDENCE', 'ReasoningEdge confidence must be between 0 and 1', id); if (!nullableDate(edge.asOf)) add(errors, 'V04_REASONING_TIME', 'ReasoningEdge asOf must be a date or null', id) }

function validateCycles(claims: ReadonlyMap<string, KnowledgeClaimV04>, errors: KnowledgeV04Diagnostic[]): void { const indegree = new Map([...claims.keys()].map((id) => [id, 0])); const outgoing = new Map([...claims.keys()].map((id) => [id, [] as string[]])); for (const [id, claim] of claims) for (const target of [...claim.supportsClaimRefs ?? [], ...claim.dependsOnClaimRefs ?? [], ...claim.contradictsClaimRefs ?? []]) if (claims.has(target)) { outgoing.get(target)!.push(id); indegree.set(id, indegree.get(id)! + 1) } const queue = [...indegree.entries()].filter(([, degree]) => degree === 0).map(([id]) => id).sort(); let visited = 0; while (queue.length) { const id = queue.shift()!; visited += 1; for (const next of outgoing.get(id)!.sort()) { const degree = indegree.get(next)! - 1; indegree.set(next, degree); if (degree === 0) queue.push(next) } } if (visited !== claims.size) add(errors, 'V04_DEPENDENCY_CYCLE', 'Claim dependency graph contains a deterministic cycle') }

export function validateKnowledgeV04Objects(objects: readonly KnowledgeAssetV04[]): KnowledgeV04ValidationReport { const errors: KnowledgeV04Diagnostic[] = []; const ids = new Set<string>(); const sources = new Map<string, KnowledgeSourceV04>(); const claims = new Map<string, KnowledgeClaimV04>(); const relations = new Map<string, KnowledgeRelationV04>(); const entities = new Map<string, string>(); const events = new Map<string, KnowledgeEventV04>(); const observations = new Map<string, KnowledgeObservationV04>(); const theses = new Map<string, KnowledgeThesisV04>(); const edges = new Map<string, KnowledgeReasoningEdgeV04>(); for (const object of objects) { if (!record(object) || typeof object.id !== 'string') { add(errors, 'V04_OBJECT', 'Canonical object must have a string id'); continue } if (ids.has(object.id)) add(errors, 'V04_DUPLICATE_ID', `Duplicate canonical id: ${object.id}`, object.id); ids.add(object.id); if (object.id.startsWith('source:')) sources.set(object.id, object as KnowledgeSourceV04); else if (object.id.startsWith('claim:')) claims.set(object.id, object as KnowledgeClaimV04); else if (object.id.startsWith('relation:')) relations.set(object.id, object as KnowledgeRelationV04); else if (object.id.startsWith('entity:')) entities.set(object.id, String((object as Dict).type)); else if (object.id.startsWith('event:')) events.set(object.id, object as KnowledgeEventV04); else if (object.id.startsWith('observation:')) observations.set(object.id, object as KnowledgeObservationV04); else if (object.id.startsWith('thesis:')) theses.set(object.id, object as KnowledgeThesisV04); else if (object.id.startsWith('reasoning-edge:')) edges.set(object.id, object as KnowledgeReasoningEdgeV04) }
  const sourceIds = new Set(sources.keys()); const claimIds = new Set(claims.keys()); const observationIds = new Set(observations.keys()); const objectMap = new Map(objects.map((object) => [object.id, object])); for (const object of objects) if (object.id.startsWith('entity:')) validateEntity(object as KnowledgeEntityV04, sourceIds, errors); for (const source of sources.values()) validateSource(source, errors); for (const claim of claims.values()) validateClaim(claim, sourceIds, claimIds, errors); for (const relation of relations.values()) { const definition = typeof relation.type === 'string' ? KNOWLEDGE_SCHEMA_V04.relation.definitions[relation.type as keyof typeof KNOWLEDGE_SCHEMA_V04.relation.definitions] : undefined; const sourceType = entities.get(relation.sourceRef); const targetType = entities.get(relation.targetRef); if (!definition || !KNOWLEDGE_SCHEMA_V04.relation.types.includes(relation.type as never)) add(errors, 'V04_RELATION_TYPE', 'Relation type is not declared by Schema 0.4', relation.id); if (!sourceType || !targetType) add(errors, 'V04_RELATION_ENDPOINT', 'Relation endpoints must resolve to Entity objects', relation.id); if (definition && sourceType && targetType && (!(definition.sourceTypes as readonly string[]).includes(sourceType) || !(definition.targetTypes as readonly string[]).includes(targetType) || ('endpointConstraint' in definition && definition.endpointConstraint === 'same_entity_type_on_both_sides' && sourceType !== targetType))) add(errors, 'V04_RELATION_SEMANTICS', 'Relation endpoint types violate the Schema 0.4 semantic definition', relation.id); if (relation.sourceRefs?.some((item) => !sourceIds.has(item))) add(errors, 'V04_RELATION_SOURCE_REF', 'Relation sourceRefs must resolve to Source objects', relation.id); if (relation.supportingClaimRefs?.some((item) => !claimIds.has(item))) add(errors, 'V04_RELATION_CLAIM_REF', 'Relation supportingClaimRefs must resolve to Claim objects', relation.id); if (!validateRelationAttributesV03(relation.type, relation.attributes).valid) add(errors, 'V04_RELATION_ATTRIBUTES', 'Relation attributes are not admissible for Schema 0.4', relation.id) }
  for (const event of events.values()) validateEvent(event, ids, sourceIds, errors); for (const observation of observations.values()) validateObservation(observation, ids, sourceIds, observationIds, errors); for (const thesis of theses.values()) validateThesis(thesis, ids, errors); for (const edge of edges.values()) validateReasoningEdge(edge, objectMap, sourceIds, errors); validateCycles(claims, errors); return { status: errors.length === 0 ? 'passed' : 'failed', errors } }
export function assertKnowledgeV04Objects(objects: readonly KnowledgeAssetV04[]): void { const report = validateKnowledgeV04Objects(objects); if (report.status === 'failed') throw new Error(report.errors.map((error) => `${error.code}: ${error.message}`).join('; ')) }
export function isKnowledgeV04RawRef(value: unknown): value is string { return typeof value === 'string' && RAW_PATTERN.test(value) }
