import { archiveRaw } from '../raw/raw-archive.ts'
import { readCanonicalV04Assets } from '../storage/canonical-v04-loader.ts'
import { hashKnowledgeObject } from '../storage/canonical-hash.ts'
import { allocateEntityId, allocateKnowledgeId, normalizeSemanticText } from '../registry/id-allocation.ts'
import { normalizeExchange } from '../../skills/knowledge-curation/identity/company-identity.ts'
import { KnowledgeBaseRegistry } from '../registry/registry.ts'
import type { KnowledgeAssetV04, KnowledgeClaimV04, KnowledgeEntityV04, KnowledgeRelationV04, KnowledgeSourceV04 } from '../schema/domain-v04.ts'
import { KNOWLEDGE_SCHEMA_V04 } from '../schema/executable-schema-v04.ts'
import type { KnowledgeChangeSetV04, KnowledgeOperationV04, KnowledgeWriteResultV04 } from '../schema/mutation-v04.ts'
import { validateRelationAttributesV03 } from '../validation/v03-validation-core.ts'
import { validateKnowledgeChangeSetV04 } from '../validation/v04-change-set-validator.ts'
import { writeKnowledgeBase } from '../writer/writer.ts'
import { validateUsableAcquisitionPayload } from '../../plugins/research-acquisition/payload-validation.ts'
import type { KnowledgeBaseHandle } from '../storage/handle.ts'
import { sha256 } from '../../plugins/research-acquisition/hash.ts'
import { persistReviewCases } from '../review/store.ts'
import type { ReviewCase } from '../review/contracts.ts'
import type { KnowledgeProductionInput, KnowledgeProductionOutcome, ResolutionIntentSummary, SemanticProductionProposal, SemanticResolver } from './contracts.ts'

type Dict = Record<string, unknown>
type AssetMap = Map<string, KnowledgeAssetV04>
type EntityType = 'company' | 'industry' | 'product' | 'technology'
type RawRef = `raw-sha256-${string}`
const safeId = /^[A-Za-z0-9][A-Za-z0-9._-]*$/
const relationTypes = new Set<string>(KNOWLEDGE_SCHEMA_V04.relation.types)
const claimTypes = new Set(['fact', 'forecast', 'viewpoint', 'trend', 'risk', 'assumption', 'thesis', 'catalyst'])
const record = (v: unknown): v is Dict => typeof v === 'object' && v !== null && !Array.isArray(v)
const text = (v: unknown) => typeof v === 'string' ? v.trim() : ''
const ident = (v: unknown) => normalizeSemanticText(String(v ?? ''))
const intent = (intentId: string, disposition: ResolutionIntentSummary['disposition'], reason: string, fields: Partial<ResolutionIntentSummary> = {}): ResolutionIntentSummary => ({ intentId, disposition, reason, ...fields })

function outcome(input: KnowledgeProductionInput, status: 'blocked' | 'failed', errors: readonly string[], intents: readonly ResolutionIntentSummary[] = [], entities: Readonly<Record<string, string>> = {}, relations: Readonly<Record<string, string>> = {}, sources: Readonly<Record<string, string>> = {}, claims: Readonly<Record<string, string>> = {}): KnowledgeProductionOutcome {
  return { status, knowledgeBaseId: input.handle.knowledgeBaseId, knowledgeBaseRevision: input.handle.revision, baseRevision: input.handle.revision, createdIds: [], updatedIds: [], sourceRefsByLocalId: sources, claimRefsByProposalId: claims, entityRefsByLocalKey: entities, relationRefsByProposalId: relations, resolutionIntents: intents, errors }
}
function companyFields(input: KnowledgeProductionInput) { const f = input.entity.semanticFields ?? {}; return { ...(text(f.ticker) ? { ticker: text(f.ticker) } : {}), ...(text(f.exchange) ? { exchange: normalizeExchange(text(f.exchange)) } : {}) } }
function companyMatch(o: KnowledgeAssetV04, f: { ticker?: string; exchange?: string }) { const v = o as KnowledgeEntityV04 & Dict; return o.id.startsWith('entity:') && v.type === 'company' && f.ticker !== undefined && ident(v.ticker) === ident(f.ticker) && (f.exchange === undefined || ident(v.exchange) === ident(f.exchange)) }
function nameMatch(o: KnowledgeAssetV04, type: EntityType, name: string, aliases: readonly string[]) { if (!o.id.startsWith('entity:')) return false; const v = o as KnowledgeEntityV04; const names = [v.name, ...(v.aliases ?? [])].map(ident); return v.type === type && (names.includes(ident(name)) || aliases.some((a) => names.includes(ident(a)))) }
function mergeEntity(e: KnowledgeEntityV04, i: { aliases: readonly string[]; semanticFields?: Readonly<Record<string, unknown>> }) { const v = e as unknown as Dict; const merged: Dict = { ...v, aliases: [...new Set([...(e.aliases ?? []), ...i.aliases])].sort() }; for (const k of ['ticker', 'exchange', 'legalName']) if (typeof i.semanticFields?.[k] === 'string' && !merged[k]) merged[k] = i.semanticFields[k]; return merged as unknown as KnowledgeEntityV04 }
function validStructured(v: unknown): Dict | undefined { return record(v) && typeof v.metric === 'string' && Boolean(v.metric.trim()) && 'value' in v && 'unit' in v && 'comparator' in v ? v : undefined }
function claimIdentity(p: SemanticProductionProposal, subjectRef: string) { return { claimType: p.claimType, statement: ident(p.statement), subjectRefs: [subjectRef], temporal: p.temporal ?? null, structuredValue: validStructured(p.structuredValue) ?? null } }
function exactClaim(o: KnowledgeAssetV04, id: Dict) { if (!o.id.startsWith('claim:')) return false; const c = o as KnowledgeClaimV04; return hashKnowledgeObject({ claimType: c.claimType, statement: ident(c.statement), subjectRefs: c.subjectRefs, temporal: c.temporal ?? null, structuredValue: c.structuredValue ?? null }) === hashKnowledgeObject(id) }
function frozenClaimFields(c: KnowledgeClaimV04, p: SemanticProductionProposal, subjectRef: string) { const incoming = validStructured(p.structuredValue); const prior = validStructured(c.structuredValue); if (!incoming || !prior) return false; return c.claimType === p.claimType && ident(c.statement) === ident(p.statement) && hashKnowledgeObject(c.subjectRefs) === hashKnowledgeObject([subjectRef]) && hashKnowledgeObject(c.temporal ?? null) === hashKnowledgeObject(p.temporal ?? null) && incoming.metric === prior.metric && incoming.unit === prior.unit && incoming.comparator === prior.comparator && incoming.period === prior.period && incoming.fiscalPeriod === prior.fiscalPeriod }
function mergeClaimEvidence(c: KnowledgeClaimV04, ev: readonly { sourceRef: `source:${string}`; rawRef: RawRef }[]) { const provenance = ev.map((x) => ({ sourceRef: x.sourceRef, rawRef: x.rawRef, locator: null, chunkRef: null })); return { ...c, sourceRefs: [...new Set([...(c.sourceRefs ?? []), ...ev.map((x) => x.sourceRef)])], provenance: [...new Map([...(c.provenance ?? []), ...provenance].map((x) => [`${x.sourceRef}|${x.rawRef}`, x])).values()] } as KnowledgeClaimV04 }
function sourceIdentity(s: KnowledgeProductionInput['evidenceBindings'][number]['source'], f: { ticker?: string }) { const m = s.candidate.metadata ?? {}; return { provider: ident(s.candidate.provider), kind: s.candidate.kind, dataset: m.dataset ?? m.dataKind ?? s.candidate.kind, company: m.companySymbol ?? f.ticker ?? null, query: m.query ?? m.period ?? m.startDate ?? null, url: s.canonicalUrl ?? s.candidate.url ?? null, publishedAt: s.candidate.publishedAt ?? null, title: s.title, metadata: Object.fromEntries(Object.entries(m).filter(([k]) => !['retrievedAt', 'requestId'].includes(k)).sort()) } }
function sourceObject(s: KnowledgeProductionInput['evidenceBindings'][number]['source'], id: string, rawRef: RawRef, f: { ticker?: string }): KnowledgeSourceV04 { const kind = s.candidate.kind; return { id: id as `source:${string}`, title: s.title, sourceType: kind === 'official_disclosure' ? 'official_disclosure' : kind === 'structured_data' ? 'industry_database' : 'general_media', publisher: s.publisher, publishedAt: s.candidate.publishedAt ?? null, url: s.canonicalUrl ?? s.candidate.url ?? null, rawRefs: [rawRef], provider: s.candidate.provider, canonicalUrl: s.canonicalUrl ?? s.candidate.url ?? null, retrievedAt: s.retrievedAt, contentHash: s.contentHash, metadata: { ...(s.candidate.metadata ?? {}), researchSourceIdentity: hashKnowledgeObject(sourceIdentity(s, f)) }, acquisition: { method: kind === 'official_disclosure' ? 'official' : kind === 'structured_data' ? 'structured_data' : kind === 'rss' ? 'rss' : 'news_search', discoveredAt: null, fetchedAt: s.retrievedAt, extractor: 'research-acquisition-normalizer' }, rights: { accessScope: s.rights.accessScope, providerTermsKnown: false, retentionAllowed: null, aiProcessingAllowed: null, derivativeKnowledgeAllowed: null, redistributionAllowed: false }, usagePolicy: { mode: 'personal_noncommercial_research', retainRaw: true, allowAiProcessing: true, allowDerivedKnowledge: true, redistributionAllowed: false }, lifecycle: { status: 'active' } } }

function localErrors(input: KnowledgeProductionInput): string[] {
  const errors: string[] = []; const ids = new Set<string>()
  if (!safeId.test(input.entity.localKey) || !input.entity.name.trim()) errors.push('Root Entity localKey/name is invalid')
  for (const raw of input.proposals as readonly unknown[]) {
    if (!record(raw)) { errors.push('Proposal must be an object'); continue }
    const p = raw as unknown as SemanticProductionProposal
    if (!safeId.test(p.proposalId) || ids.has(p.proposalId)) errors.push(`Proposal ID is not unique and local: ${String(p.proposalId)}`); ids.add(p.proposalId)
    if (!safeId.test(p.subjectKey)) errors.push(`Proposal subjectKey is not safe: ${String(p.subjectKey)}`)
    if (!['entity', 'claim', 'relation', 'source'].includes(p.kind)) errors.push(`Unsupported proposal kind: ${String(p.kind)}`)
    if (p.kind === 'entity' && (!['company', 'industry', 'product', 'technology'].includes(p.entityType ?? '') || !text(p.entityName))) errors.push(`Entity proposal is invalid: ${p.proposalId}`)
    if (p.kind === 'claim' && (!claimTypes.has(p.claimType ?? '') || !text(p.statement))) errors.push(`Claim proposal is invalid: ${p.proposalId}`)
    if (p.kind === 'relation' && (!text(p.relationType) || !text(p.targetKey))) errors.push(`Relation proposal is invalid: ${p.proposalId}`)
    if (p.resolution !== undefined && !['update', 'supersede', 'contradict', 'review'].includes(p.resolution)) errors.push(`Unsupported proposal resolution: ${p.proposalId}`)
  }
  for (const raw of input.proposals as readonly unknown[]) if (record(raw)) for (const key of ['supportsProposalIds', 'dependsOnProposalIds', 'contradictsProposalIds'] as const) { const links = raw[key]; if (links !== undefined && (!Array.isArray(links) || links.some((id) => typeof id !== 'string'))) errors.push(`Proposal links must be string arrays: ${String(raw.proposalId)}`); for (const id of Array.isArray(links) ? links : []) if (!ids.has(id)) errors.push(`Proposal link does not resolve locally: ${id}`) }
  return errors
}
function reviewCase(input: KnowledgeProductionInput, p: SemanticProductionProposal, rawRef: RawRef): ReviewCase { const claimType = claimTypes.has(p.claimType ?? '') ? p.claimType as 'fact' | 'forecast' | 'viewpoint' | 'trend' | 'risk' : 'fact'; return { version: '0.1', reviewCaseId: `review-case-${hashKnowledgeObject({ kb: input.handle.knowledgeBaseId, run: input.producerRunId, proposal: p.proposalId, reason: 'review' }).slice(7)}`, knowledgeBaseId: input.handle.knowledgeBaseId, producerType: input.reviewProducerType ?? input.producerType, producerRunId: input.producerRunId, createdAt: (input.now ?? (() => new Date().toISOString()))(), classification: { category: 'reconciliation_review', actionability: 'knowledge_decision', origin: 'semantic_case', stage: 'knowledge_resolution', rationale: 'Producer marked semantic resolution for review' }, rootProposal: { proposalId: p.proposalId, proposalKind: 'claim', semanticType: claimType, semanticPayload: { candidateId: p.proposalId, claimType, statement: p.statement ?? '', subjectRefs: [{ candidateRef: p.subjectKey, mention: p.subjectKey }], evidenceBlockRefs: [`source-${p.proposalId}`], reason: 'review' } as never, evidenceBindings: [{ kind: 'raw_document_block', rawRef, documentId: p.proposalId, blockId: `source-${p.proposalId}` }], dependencyRefs: [] }, suspendedProposalBundle: { dependentProposals: [] }, resolutionContext: { existingKnowledgeProjections: [], schemaVersionAtCreation: '0.3', knowledgeBaseRevisionAtCreation: input.handle.revision }, impact: { dependentProposalCount: 0, affectedProposalRefs: [] }, state: { status: 'open' } } }

export class KnowledgeProductionGateway {
  constructor(private readonly registry = new KnowledgeBaseRegistry(), private readonly resolver?: SemanticResolver) {}
  async projectExistingKnowledge(handle: KnowledgeBaseHandle, entity: { name?: string; symbol: string; exchange?: string }): Promise<readonly Dict[]> { const objects = (await readCanonicalV04Assets(handle.rootRef)).objects.map((x) => x.value); const f = { ticker: entity.symbol, ...(entity.exchange ? { exchange: normalizeExchange(entity.exchange) } : {}) }; const ids = new Set(objects.filter((o) => companyMatch(o, f) || nameMatch(o, 'company', entity.name ?? entity.symbol, [entity.symbol])).map((o) => o.id)); for (const r of objects.filter((o) => o.id.startsWith('relation:')) as KnowledgeRelationV04[]) if (ids.has(r.sourceRef) || ids.has(r.targetRef)) { ids.add(r.id); ids.add(r.sourceRef); ids.add(r.targetRef) } for (const c of objects.filter((o) => o.id.startsWith('claim:')) as KnowledgeClaimV04[]) if (c.subjectRefs.some((r) => ids.has(r))) ids.add(c.id); return objects.filter((o) => ids.has(o.id)).sort((a, b) => a.id.localeCompare(b.id)).slice(0, 80).map((o) => { const v = o as unknown as Dict; return { canonicalRef: o.id, kind: o.id.split(':', 1)[0], name: v.name ?? v.statement ?? null, aliases: Array.isArray(v.aliases) ? v.aliases.slice(0, 10) : [], ...v } }) }
  async submit(input: KnowledgeProductionInput): Promise<KnowledgeProductionOutcome> {
    const now = input.now ?? (() => new Date().toISOString()); const intents: ResolutionIntentSummary[] = []; const relationRefs: Record<string, string> = {}; const entityRefs: Record<string, string> = {}; const claimRefs: Record<string, string> = {}; const sourceRefs: Record<string, string> = {}
    try {
      const errors = localErrors(input); if (input.handle.schemaVersion !== '0.4' || input.handle.storageFormatVersion !== '1') errors.push('Knowledge Production Gateway requires Schema 0.4 / Storage Format 1'); if (errors.length) return outcome(input, 'blocked', errors, intents, entityRefs, relationRefs, sourceRefs, claimRefs)
      const assets = await readCanonicalV04Assets(input.handle.rootRef); const objects: AssetMap = new Map(assets.objects.map((x) => [x.value.id, structuredClone(x.value)])); const operations: KnowledgeOperationV04[] = []; const createdIds: string[] = []; const updatedIds: string[] = []; const rawBySource = new Map<string, RawRef>(); const f = companyFields(input)
      const entityInputs = new Map<string, KnowledgeProductionInput['entity']>([[input.entity.localKey, input.entity]])
      for (const p of input.proposals.filter((x) => x.kind === 'entity')) { if (p.subjectKey === input.entity.localKey) { if (p.entityType !== input.entity.entityType || p.entityName !== input.entity.name) return outcome(input, 'blocked', ['Semantic Entity proposal cannot overwrite authoritative root ProductionEntityInput'], intents, entityRefs, relationRefs, sourceRefs, claimRefs); continue } entityInputs.set(p.subjectKey, { localKey: p.subjectKey, entityType: p.entityType!, name: p.entityName!, aliases: [], semanticFields: p.structuredValue ?? undefined }) }
      for (const [localKey, ei] of entityInputs) {
        const isRoot = localKey === input.entity.localKey; let existing: KnowledgeEntityV04 | undefined
        if (ei.existingEntityRef) { const x = objects.get(ei.existingEntityRef); if (!x || !x.id.startsWith('entity:') || (x as KnowledgeEntityV04).type !== ei.entityType || (ei.entityType === 'company' && !companyMatch(x, f))) { intents.push(intent(`entity-${localKey}`, 'review_required', 'Explicit canonical Entity ref is missing, type-mismatched, or violates Company hard identity', { localKey })); continue } existing = x as KnowledgeEntityV04 }
        else if (isRoot && ei.entityType === 'company') { const matches = [...objects.values()].filter((o) => companyMatch(o, f)); if (matches.length > 1) { intents.push(intent(`entity-${localKey}`, 'review_required', 'Multiple canonical companies match hard identity', { localKey })); continue } existing = matches[0] as KnowledgeEntityV04 | undefined }
        else { const matches = [...objects.values()].filter((o) => nameMatch(o, ei.entityType, ei.name, ei.aliases ?? [])) as KnowledgeEntityV04[]; if (matches.length) { const resolver = input.semanticResolver ?? this.resolver; const decision = resolver ? await resolver({ proposal: { proposalId: `entity-${localKey}`, kind: 'entity', subjectKey: localKey, entityType: ei.entityType, entityName: ei.name }, existing: matches.map((m) => ({ canonicalRef: m.id, type: m.type, name: m.name, aliases: m.aliases ?? [] })), evidence: [] }) : undefined; if (decision?.outcome === 'equivalent' && matches.length === 1) existing = matches[0]; else { intents.push(intent(`entity-${localKey}`, 'review_required', matches.length > 1 ? 'Multiple plausible non-Company candidates require semantic resolution' : 'Name similarity alone cannot establish non-Company identity', { localKey, ...(matches.length === 1 ? { targetRef: matches[0].id } : {}) })); continue } } }
        const ref = existing?.id ?? allocateEntityId(ei.entityType, ei.entityType === 'company' && text(f.ticker) ? text(f.ticker) : ei.name); entityRefs[localKey] = ref
        if (existing) { const merged = mergeEntity(existing, { aliases: ei.aliases ?? [], semanticFields: isRoot ? f : ei.semanticFields }); if (hashKnowledgeObject(existing) !== hashKnowledgeObject(merged)) { objects.set(ref, merged); operations.push({ operationId: `update-entity-${operations.length + 1}`, type: 'update', knowledgeId: ref, expectedBeforeHash: hashKnowledgeObject(existing), object: merged }); updatedIds.push(ref) } intents.push(intent(`entity-${localKey}`, 'bound_existing', 'Bound to a validated canonical Entity', { localKey, targetRef: ref })) }
        else { const created = { id: ref as `entity:${string}`, type: ei.entityType, name: ei.name, aliases: [...new Set(ei.aliases ?? [])], ...(isRoot ? f : ei.semanticFields ?? {}), lifecycle: { status: 'active' } } as KnowledgeEntityV04; objects.set(ref, created); operations.push({ operationId: `create-entity-${operations.length + 1}`, type: 'create', object: created }); createdIds.push(ref); intents.push(intent(`entity-${localKey}`, 'created_new', 'No plausible canonical Entity was proven equivalent', { localKey, targetRef: ref })) }
      }
      if (!entityRefs[input.entity.localKey]) return outcome(input, 'blocked', ['Root Entity binding requires review before dependent Knowledge can be committed'], intents, entityRefs, relationRefs, sourceRefs, claimRefs)
      for (const b of input.evidenceBindings) { if (validateUsableAcquisitionPayload(b.source.content).status !== 'usable') continue; const bytes = b.source.rawBytes === undefined ? new TextEncoder().encode(b.source.content) : Uint8Array.from(b.source.rawBytes); const raw = await archiveRaw(input.handle, { bytes, originalFilename: b.originalFilename ?? `${b.localSourceId}.txt`, mediaType: b.mediaType ?? 'text/plain', suppliedMetadata: { title: b.source.title, institution: b.source.publisher, publishedAt: b.source.candidate.publishedAt ?? null, sourceUrl: b.source.canonicalUrl ?? b.source.candidate.url ?? null } }, { clock: now }); const rawRef = raw.manifest.rawRef as RawRef; rawBySource.set(b.localSourceId, rawRef); const hash = hashKnowledgeObject(sourceIdentity(b.source, f)); const old = [...objects.values()].find((o) => o.id.startsWith('source:') && (o as KnowledgeSourceV04).metadata?.researchSourceIdentity === hash) as KnowledgeSourceV04 | undefined; const s = sourceObject(b.source, old?.id ?? `source:research-${hash.slice(7, 23)}`, rawRef, f); const final = old ? { ...old, rawRefs: [...new Set([...(old.rawRefs ?? []), ...(s.rawRefs ?? [])])] } : s; sourceRefs[b.localSourceId] = final.id; objects.set(final.id, final); if (!old) { operations.push({ operationId: `create-source-${operations.length + 1}`, type: 'create', object: final }); createdIds.push(final.id) } else if (hashKnowledgeObject(old) !== hashKnowledgeObject(final)) { operations.push({ operationId: `update-source-${operations.length + 1}`, type: 'update', knowledgeId: old.id, expectedBeforeHash: hashKnowledgeObject(old), object: final }); updatedIds.push(old.id) } }
      const evidenceFor = (p: SemanticProductionProposal) => (p.sourceCandidateIds ?? []).map((id) => ({ sourceRef: sourceRefs[id], rawRef: rawBySource.get(id) })).filter((x): x is { sourceRef: `source:${string}`; rawRef: RawRef } => Boolean(x.sourceRef && x.rawRef))
      for (const p of input.proposals.filter((x) => x.kind === 'relation')) { const sr = entityRefs[p.subjectKey]; const tr = p.targetKey ? entityRefs[p.targetKey] : undefined; const d = p.relationType ? KNOWLEDGE_SCHEMA_V04.relation.definitions[p.relationType as keyof typeof KNOWLEDGE_SCHEMA_V04.relation.definitions] : undefined; const se = sr ? objects.get(sr) as KnowledgeEntityV04 : undefined; const te = tr ? objects.get(tr) as KnowledgeEntityV04 : undefined; const ev = evidenceFor(p); const valid = Boolean(sr && tr && d && relationTypes.has(p.relationType ?? '') && se && te && (d.sourceTypes as readonly string[]).includes(se.type) && (d.targetTypes as readonly string[]).includes(te.type) && validateRelationAttributesV03(p.relationType!, p.attributes).valid && ev.length); if (!valid) { intents.push(intent(`relation-${p.proposalId}`, 'review_required', 'Relation endpoint, type, attributes, or evidence could not be resolved', { proposalId: p.proposalId })); continue } const old = [...objects.values()].find((o) => o.id.startsWith('relation:') && (o as KnowledgeRelationV04).type === p.relationType && (o as KnowledgeRelationV04).sourceRef === sr && (o as KnowledgeRelationV04).targetRef === tr && hashKnowledgeObject((o as KnowledgeRelationV04).attributes ?? null) === hashKnowledgeObject(p.attributes ?? null)) as KnowledgeRelationV04 | undefined; const id = old?.id ?? allocateKnowledgeId('relation', { type: p.relationType, sourceRef: sr, targetRef: tr, attributes: p.attributes ?? null }); relationRefs[p.proposalId] = id; const merged = { id, type: p.relationType, sourceRef: sr, targetRef: tr, ...(p.attributes === undefined ? {} : { attributes: p.attributes }), sourceRefs: [...new Set([...(old?.sourceRefs ?? []), ...ev.map((x) => x.sourceRef)])], lifecycle: { status: 'active' } } as unknown as KnowledgeRelationV04; objects.set(id, merged); if (!old) { operations.push({ operationId: `create-relation-${operations.length + 1}`, type: 'create', object: merged }); createdIds.push(id) } else if (hashKnowledgeObject(old) !== hashKnowledgeObject(merged)) { operations.push({ operationId: `update-relation-${operations.length + 1}`, type: 'update', knowledgeId: id, expectedBeforeHash: hashKnowledgeObject(old), object: merged }); updatedIds.push(id) } intents.push(intent(`relation-${p.proposalId}`, old ? 'bound_existing' : 'created_new', old ? 'Exact canonical Relation matched' : 'Created canonical Relation', { proposalId: p.proposalId, targetRef: id })) }
      const reviewCases: ReviewCase[] = []
      for (const p of input.proposals.filter((x) => x.kind === 'claim')) { const ev = evidenceFor(p); const relationSubject = input.proposals.some((x) => x.kind === 'relation' && x.proposalId === p.subjectKey); const subject = p.resolution === 'review' ? undefined : relationRefs[p.subjectKey] ?? entityRefs[p.subjectKey] ?? (relationSubject ? undefined : entityRefs[input.entity.localKey]); if (!subject || ev.length === 0) { intents.push(intent(`claim-${p.proposalId}`, 'review_required', p.resolution === 'review' ? 'Producer marked semantic resolution for review' : relationSubject ? 'Relation subject unresolved; no root fallback permitted' : 'Claim lacks a bound subject or usable evidence', { proposalId: p.proposalId })); if (p.resolution === 'review' && ev[0]?.rawRef) reviewCases.push(reviewCase(input, p, ev[0].rawRef)); continue }
        const incoming = validStructured(p.structuredValue); const requestedRef = p.existingKnowledgeRefs?.length === 1 ? p.existingKnowledgeRefs[0] : undefined; if (p.existingKnowledgeRefs && (p.existingKnowledgeRefs.length !== 1 || p.resolution !== 'update')) { intents.push(intent(`claim-${p.proposalId}`, 'review_required', 'existingKnowledgeRefs require explicit update resolution', { proposalId: p.proposalId })); continue } const requested = p.resolution === 'update' && requestedRef ? objects.get(requestedRef) as KnowledgeClaimV04 | undefined : undefined; if (p.resolution === 'update' && (!requested || !requested.id.startsWith('claim:'))) { intents.push(intent(`claim-${p.proposalId}`, 'review_required', 'Explicit Claim update requires one existing canonical Claim ref', { proposalId: p.proposalId })); continue }
        const subjectRef = subject as `entity:${string}` | `relation:${string}`; const exact = requested ?? [...objects.values()].find((o) => exactClaim(o, claimIdentity(p, subjectRef))) as KnowledgeClaimV04 | undefined; let old = exact; let semanticSupersede = false; let semanticContradict = false; const resolver = input.semanticResolver ?? this.resolver; if (!old && incoming && resolver) { const plausible = [...objects.values()].filter((o) => o.id.startsWith('claim:') && (o as KnowledgeClaimV04).claimType === p.claimType && (o as KnowledgeClaimV04).subjectRefs.includes(subjectRef) && validStructured((o as KnowledgeClaimV04).structuredValue)?.metric === incoming.metric) as KnowledgeClaimV04[]; if (plausible.length) { const decision = await resolver({ proposal: p, existing: plausible.map((x) => ({ canonicalRef: x.id, claimType: x.claimType, statement: x.statement, structuredValue: x.structuredValue })), evidence: ev }); if (decision.outcome === 'uncertain' || plausible.length !== 1) { intents.push(intent(`claim-${p.proposalId}`, 'review_required', 'Bounded semantic resolution did not identify one canonical Claim', { proposalId: p.proposalId })); if (ev[0]?.rawRef) reviewCases.push(reviewCase(input, p, ev[0].rawRef)); continue } old = plausible[0]; semanticSupersede = decision.outcome === 'supersedes'; semanticContradict = decision.outcome === 'contradicts' } } if (!old && (p.resolution === 'supersede' || p.resolution === 'contradict') && incoming) old = [...objects.values()].find((o) => o.id.startsWith('claim:') && (o as KnowledgeClaimV04).subjectRefs.includes(subjectRef) && validStructured((o as KnowledgeClaimV04).structuredValue)?.metric === incoming.metric) as KnowledgeClaimV04 | undefined
        const id = (old && !((p.resolution === 'supersede' || p.resolution === 'contradict') || semanticSupersede || semanticContradict)) ? old.id : allocateKnowledgeId('claim', { ...claimIdentity(p, subjectRef), ...(old && (p.resolution === 'contradict' || semanticContradict) ? { contradictsClaimRef: old.id } : {}) }).replace('claim:', 'claim:research-'); const provenance = ev.map((x) => ({ sourceRef: x.sourceRef, rawRef: x.rawRef, locator: null, chunkRef: null })); const probability = p.probability ?? (p.claimType === 'forecast' ? 0.5 : null)
        let claim: KnowledgeClaimV04 = { id, claimType: p.claimType!, statement: p.statement!, subjectRefs: [subjectRef], primarySubjectRef: subjectRef, ...(p.temporal === undefined ? {} : { temporal: p.temporal }), ...(incoming ? { structuredValue: incoming } : {}), sourceRefs: ev.map((x) => x.sourceRef), provenance, confidence: p.confidence ?? 0.5, probability, lifecycle: { status: 'active' } } as unknown as KnowledgeClaimV04
        if (p.resolution === 'update' && old && incoming) { const prior = validStructured(old.structuredValue); if (!prior || !frozenClaimFields(old, p, subjectRef)) { intents.push(intent(`claim-${p.proposalId}`, 'review_required', 'Claim update changes a frozen canonical field; only structured value may change', { proposalId: p.proposalId, targetRef: old.id })); continue } claim = { ...mergeClaimEvidence(old, ev), structuredValue: { ...prior, value: incoming.value as string | number | boolean | null } as never } }
        else if (old && p.resolution !== 'supersede' && p.resolution !== 'contradict' && !semanticSupersede && !semanticContradict) claim = { ...old, sourceRefs: [...new Set([...(old.sourceRefs ?? []), ...ev.map((x) => x.sourceRef)])], provenance: [...new Map([...(old.provenance ?? []), ...provenance].map((x) => [`${x.sourceRef}|${x.rawRef}`, x])).values()] }
        if ((p.resolution === 'contradict' || semanticContradict) && old) claim = { ...claim, contradictsClaimRefs: [...new Set([...(claim.contradictsClaimRefs ?? []), old.id])] }
        if ((p.resolution === 'supersede' || semanticSupersede) && old && old.id !== id) { const superseded = { ...old, lifecycle: { ...old.lifecycle, status: 'superseded' as const }, supersededBy: [...new Set([...(old.supersededBy ?? []), id as `claim:${string}`])] } as KnowledgeClaimV04; claim = { ...claim, supersedes: [...new Set([...(claim.supersedes ?? []), old.id])] }; objects.set(old.id, superseded); operations.push({ operationId: `supersede-claim-${operations.length + 1}`, type: 'update', knowledgeId: old.id, expectedBeforeHash: hashKnowledgeObject(old), object: superseded }); updatedIds.push(old.id) }
        claimRefs[p.proposalId] = id; objects.set(id, claim); if (!old || ((p.resolution === 'supersede' || semanticSupersede) && old.id !== id) || p.resolution === 'contradict' || semanticContradict) { operations.push({ operationId: `claim-${operations.length + 1}`, type: 'create', object: { ...claim, id: id as `claim:${string}` } }); createdIds.push(id) } else if (hashKnowledgeObject(old) !== hashKnowledgeObject(claim)) { operations.push({ operationId: `update-claim-${operations.length + 1}`, type: 'update', knowledgeId: old.id, expectedBeforeHash: hashKnowledgeObject(old), object: { ...claim, id: old.id } }); updatedIds.push(old.id) } intents.push(intent(`claim-${p.proposalId}`, old ? 'bound_existing' : 'created_new', old ? 'Canonical Claim resolved and provenance merged' : 'Created canonical Claim', { proposalId: p.proposalId, targetRef: id }))
      }
      for (const p of input.proposals.filter((x) => x.kind === 'claim')) {
        const id = claimRefs[p.proposalId]; let current = id ? objects.get(id) as KnowledgeClaimV04 | undefined : undefined
        if (!current) continue
        for (const [key, field] of [['supportsProposalIds', 'supportsClaimRefs'], ['dependsOnProposalIds', 'dependsOnClaimRefs'], ['contradictsProposalIds', 'contradictsClaimRefs']] as const) {
          const refs = (p[key] ?? []).map((proposalId) => claimRefs[proposalId]).filter((ref): ref is `claim:${string}` => Boolean(ref) && ref !== id)
          if (!refs.length) continue
          const linked = { ...current, [field]: [...new Set([...(current[field] ?? []), ...refs])] } as KnowledgeClaimV04
          if (hashKnowledgeObject(linked) === hashKnowledgeObject(current)) continue
          objects.set(id, linked); current = linked
          let operationIndex = -1
          for (let index = operations.length - 1; index >= 0 && operationIndex < 0; index -= 1) { const candidate = operations[index]; if ((candidate.type === 'create' && candidate.object.id === id) || (candidate.type === 'update' && candidate.knowledgeId === id)) operationIndex = index }
          if (operationIndex >= 0) operations[operationIndex] = { ...operations[operationIndex], object: linked } as KnowledgeOperationV04
          else { const original = assets.objects.find((asset) => asset.value.id === id)?.value; if (original) operations.push({ operationId: `link-claim-${operations.length + 1}`, type: 'update', knowledgeId: id, expectedBeforeHash: hashKnowledgeObject(original), object: linked }) }
        }
      }
      for (const operation of operations) if (operation.type === 'update' && operation.knowledgeId !== operation.object.id) return outcome(input, 'blocked', ['Update operation knowledgeId must equal operation.object.id'], intents, entityRefs, relationRefs, sourceRefs, claimRefs)
      if (reviewCases.length) await persistReviewCases({ rootRef: input.handle.rootRef, knowledgeBaseId: input.handle.knowledgeBaseId, producerRunId: input.producerRunId, producerType: input.reviewProducerType ?? input.producerType, cases: reviewCases, createdAt: now(), knowledgeBaseRevisionAtCreation: input.handle.revision })
      if (!operations.length) return { status: 'no_changes', knowledgeBaseId: input.handle.knowledgeBaseId, knowledgeBaseRevision: input.handle.revision, baseRevision: input.handle.revision, createdIds: [], updatedIds: [], sourceRefsByLocalId: sourceRefs, claimRefsByProposalId: claimRefs, entityRefsByLocalKey: entityRefs, relationRefsByProposalId: relationRefs, resolutionIntents: intents, errors: [] }
      const cs: KnowledgeChangeSetV04 = { changeSetId: `changeset-${input.producerType}-${sha256(JSON.stringify(operations.map((o) => o.operationId))).slice(0, 20)}`, workflowRunId: input.producerRunId, knowledgeBaseId: input.handle.knowledgeBaseId, schemaVersion: '0.4', storageFormatVersion: '1', expectedBaseRevision: input.handle.revision, operations, ingestionContext: { producerType: input.producerType, producerRunId: input.producerRunId, asOf: input.asOf ?? null } }; const v = await validateKnowledgeChangeSetV04(input.handle, cs, { mode: 'commit', now }); if (!v.validatedChangeSet) return outcome(input, 'blocked', v.report.errors.map((e) => `${e.code}: ${e.message}`), intents, entityRefs, relationRefs, sourceRefs, claimRefs); const w = await writeKnowledgeBase(input.handle, v.validatedChangeSet, { registry: this.registry, clock: now }) as KnowledgeWriteResultV04; if (w.status === 'failed' || w.status === 'rejected') return outcome(input, 'failed', [w.error?.message ?? 'Shared Writer rejected the validated ChangeSet'], intents, entityRefs, relationRefs, sourceRefs, claimRefs); return { status: w.status, knowledgeBaseId: input.handle.knowledgeBaseId, knowledgeBaseRevision: w.committedRevision, baseRevision: input.handle.revision, changeSetId: cs.changeSetId, createdIds: w.createdIds, updatedIds: w.updatedIds, sourceRefsByLocalId: sourceRefs, claimRefsByProposalId: claimRefs, entityRefsByLocalKey: entityRefs, relationRefsByProposalId: relationRefs, resolutionIntents: intents, errors: [] }
    } catch (e) { return outcome(input, 'failed', [e instanceof Error ? e.message : String(e)], intents, entityRefs, relationRefs, sourceRefs, claimRefs) }
  }
}
