import { archiveRaw } from '../raw/raw-archive.ts'
import { readCanonicalV04Assets } from '../storage/canonical-v04-loader.ts'
import { hashKnowledgeObject } from '../storage/canonical-hash.ts'
import { allocateEntityId, allocateKnowledgeId, normalizeSemanticText } from '../registry/id-allocation.ts'
import { normalizeExchange } from '../../skills/knowledge-curation/identity/company-identity.ts'
import { KnowledgeBaseRegistry } from '../registry/registry.ts'
import type { KnowledgeAssetV04, KnowledgeClaimV04, KnowledgeEntityV04, KnowledgeRelationV04, KnowledgeSourceV04 } from '../schema/domain-v04.ts'
import { KNOWLEDGE_SCHEMA_V04 } from '../schema/executable-schema-v04.ts'
import type { KnowledgeChangeSetV04, KnowledgeOperationV04, KnowledgeWriteResultV04 } from '../schema/mutation-v04.ts'
import { validateRelationAttributesV03 } from '../validation/v03-validation-core.ts'
import { validateKnowledgeChangeSetV04 } from '../validation/v04-change-set-validator.ts'
import { writeKnowledgeBase } from '../writer/writer.ts'
import { validateUsableAcquisitionPayload } from '../../plugins/research-acquisition/payload-validation.ts'
import type { KnowledgeBaseHandle } from '../storage/handle.ts'
import { sha256 } from '../../plugins/research-acquisition/hash.ts'
import { persistReviewCases } from '../review/store.ts'
import type { ReviewCase } from '../review/contracts.ts'
import type { KnowledgeProductionInput, KnowledgeProductionOutcome, ResolutionIntentSummary, SemanticProductionProposal } from './contracts.ts'

type Dict = Record<string, unknown>; type AssetMap = Map<string, KnowledgeAssetV04>; type EntityType = 'company' | 'industry' | 'product' | 'technology'
const safeId = /^[A-Za-z0-9][A-Za-z0-9._-]*$/; const relationTypes = new Set<string>(KNOWLEDGE_SCHEMA_V04.relation.types)
const record = (v: unknown): v is Dict => typeof v === 'object' && v !== null && !Array.isArray(v); const text = (v: unknown) => typeof v === 'string' ? v.trim() : ''; const ident = (v: unknown) => normalizeSemanticText(String(v ?? ''))
const intent = (intentId: string, disposition: ResolutionIntentSummary['disposition'], reason: string, fields: Partial<ResolutionIntentSummary> = {}): ResolutionIntentSummary => ({ intentId, disposition, reason, ...fields })
function outcome(input: KnowledgeProductionInput, status: 'blocked' | 'failed', errors: readonly string[], intents: readonly ResolutionIntentSummary[] = [], entities: Readonly<Record<string, string>> = {}, relations: Readonly<Record<string, string>> = {}): KnowledgeProductionOutcome { return { status, knowledgeBaseId: input.handle.knowledgeBaseId, knowledgeBaseRevision: input.handle.revision, baseRevision: input.handle.revision, createdIds: [], updatedIds: [], sourceRefsByLocalId: {}, claimRefsByProposalId: {}, entityRefsByLocalKey: entities, relationRefsByProposalId: relations, resolutionIntents: intents, errors } }
function companyFields(input: KnowledgeProductionInput) { const f = input.entity.semanticFields ?? {}; return { ...(text(f.ticker) ? { ticker: text(f.ticker) } : {}), ...(text(f.exchange) ? { exchange: normalizeExchange(text(f.exchange)) } : {}) } }
function companyMatch(o: KnowledgeAssetV04, f: { ticker?: string; exchange?: string }) { const v = o as KnowledgeEntityV04 & Dict; return o.id.startsWith('entity:') && v.type === 'company' && f.ticker !== undefined && ident(v.ticker) === ident(f.ticker) && (f.exchange === undefined || ident(v.exchange) === ident(f.exchange)) }
function nameMatch(o: KnowledgeAssetV04, type: EntityType, name: string, aliases: readonly string[]) { if (!o.id.startsWith('entity:')) return false; const v = o as KnowledgeEntityV04; const names = [v.name, ...(v.aliases ?? [])].map(ident); return v.type === type && (names.includes(ident(name)) || aliases.some((a) => names.includes(ident(a)))) }
function mergeEntity(e: KnowledgeEntityV04, i: { aliases: readonly string[]; semanticFields?: Readonly<Record<string, unknown>> }) { const v = e as unknown as Dict; const merged: Dict = { ...v, aliases: [...new Set([...(e.aliases ?? []), ...i.aliases])].sort() }; for (const k of ['ticker', 'exchange', 'legalName']) if (typeof i.semanticFields?.[k] === 'string' && !merged[k]) merged[k] = i.semanticFields[k]; return merged as unknown as KnowledgeEntityV04 }
function validStructured(v: unknown): Readonly<Record<string, unknown>> | undefined { return record(v) && typeof v.metric === 'string' && Boolean(v.metric.trim()) && 'value' in v && 'unit' in v && 'comparator' in v ? v : undefined }
function claimIdentity(p: SemanticProductionProposal, subjectRef: string) { return { claimType: p.claimType, statement: ident(p.statement), subjectRefs: [subjectRef], temporal: p.temporal ?? null, structuredValue: validStructured(p.structuredValue) ?? null } }
function exactClaim(o: KnowledgeAssetV04, id: Dict) { if (!o.id.startsWith('claim:')) return false; const c = o as KnowledgeClaimV04; return hashKnowledgeObject({ claimType: c.claimType, statement: ident(c.statement), subjectRefs: c.subjectRefs, temporal: c.temporal ?? null, structuredValue: c.structuredValue ?? null }) === hashKnowledgeObject(id) }
function sourceIdentity(s: KnowledgeProductionInput['evidenceBindings'][number]['source'], f: { ticker?: string }) { const m = s.candidate.metadata ?? {}; return { provider: ident(s.candidate.provider), kind: s.candidate.kind, dataset: m.dataset ?? m.dataKind ?? s.candidate.kind, company: m.companySymbol ?? f.ticker ?? null, query: m.query ?? m.period ?? m.startDate ?? null, url: s.canonicalUrl ?? s.candidate.url ?? null, publishedAt: s.candidate.publishedAt ?? null, title: s.title, metadata: Object.fromEntries(Object.entries(m).filter(([k]) => !['retrievedAt', 'requestId'].includes(k)).sort()) } }
function sourceObject(s: KnowledgeProductionInput['evidenceBindings'][number]['source'], id: string, rawRef: `raw-sha256-${string}`, f: { ticker?: string }): KnowledgeSourceV04 { const i = sourceIdentity(s, f); const kind = s.candidate.kind; return { id: id as `source:${string}`, title: s.title, sourceType: kind === 'official_disclosure' ? 'official_disclosure' : kind === 'structured_data' ? 'industry_database' : 'general_media', publisher: s.publisher, publishedAt: s.candidate.publishedAt ?? null, url: s.canonicalUrl ?? s.candidate.url ?? null, rawRefs: [rawRef], provider: s.candidate.provider, canonicalUrl: s.canonicalUrl ?? s.candidate.url ?? null, retrievedAt: s.retrievedAt, contentHash: s.contentHash, metadata: { ...(s.candidate.metadata ?? {}), researchSourceIdentity: hashKnowledgeObject(i) }, acquisition: { method: kind === 'official_disclosure' ? 'official' : kind === 'structured_data' ? 'structured_data' : kind === 'rss' ? 'rss' : 'news_search', discoveredAt: null, fetchedAt: s.retrievedAt, extractor: 'research-acquisition-normalizer' }, rights: { accessScope: s.rights.accessScope, providerTermsKnown: false, retentionAllowed: null, aiProcessingAllowed: null, derivativeKnowledgeAllowed: null, redistributionAllowed: false }, usagePolicy: { mode: 'personal_noncommercial_research', retainRaw: true, allowAiProcessing: true, allowDerivedKnowledge: true, redistributionAllowed: false }, lifecycle: { status: 'active' } } }
function localErrors(ps: readonly SemanticProductionProposal[]) { const errors: string[] = []; const ids = new Set<string>(); for (const p of ps) { if (!safeId.test(p.proposalId) || ids.has(p.proposalId)) errors.push(`Proposal ID is not unique and local: ${p.proposalId}`); ids.add(p.proposalId); if (!safeId.test(p.subjectKey)) errors.push(`Proposal subjectKey is not safe: ${p.subjectKey}`) } for (const p of ps) for (const id of [...p.supportsProposalIds ?? [], ...p.dependsOnProposalIds ?? [], ...p.contradictsProposalIds ?? []]) if (!ids.has(id)) errors.push(`Proposal link does not resolve locally: ${id}`); return errors }
function reviewCase(input: KnowledgeProductionInput, p: SemanticProductionProposal, rawRef: string): ReviewCase { const claimType = ['fact', 'forecast', 'viewpoint', 'trend', 'risk'].includes(p.claimType ?? '') ? p.claimType as 'fact' | 'forecast' | 'viewpoint' | 'trend' | 'risk' : 'fact'; return { version: '0.1', reviewCaseId: `review-case-${hashKnowledgeObject({ kb: input.handle.knowledgeBaseId, run: input.producerRunId, proposal: p.proposalId, reason: 'review' }).slice(7)}`, knowledgeBaseId: input.handle.knowledgeBaseId, producerType: input.reviewProducerType ?? input.producerType, producerRunId: input.producerRunId, createdAt: (input.now ?? (() => new Date().toISOString()))(), classification: { category: 'reconciliation_review', actionability: 'knowledge_decision', origin: 'semantic_case', stage: 'knowledge_resolution', rationale: 'Producer marked semantic resolution for review' }, rootProposal: { proposalId: p.proposalId, proposalKind: 'claim', semanticType: claimType, semanticPayload: { candidateId: p.proposalId, claimType, statement: p.statement ?? '', subjectRefs: [{ candidateRef: p.subjectKey, mention: p.subjectKey }], evidenceBlockRefs: [`source-${p.proposalId}`], reason: 'review' } as never, evidenceBindings: [{ kind: 'raw_document_block', rawRef, documentId: p.proposalId, blockId: `source-${p.proposalId}` }], dependencyRefs: [] }, suspendedProposalBundle: { dependentProposals: [] }, resolutionContext: { existingKnowledgeProjections: [], schemaVersionAtCreation: '0.3', knowledgeBaseRevisionAtCreation: input.handle.revision }, impact: { dependentProposalCount: 0, affectedProposalRefs: [] }, state: { status: 'open' } } }

export class KnowledgeProductionGateway {
  constructor(private readonly registry = new KnowledgeBaseRegistry(), private readonly resolver?: (x: any) => any) {}
  async projectExistingKnowledge(handle: KnowledgeBaseHandle, entity: { name?: string; symbol: string; exchange?: string }): Promise<readonly Dict[]> { const objects = (await readCanonicalV04Assets(handle.rootRef)).objects.map((x) => x.value); const f = { ticker: entity.symbol, ...(entity.exchange ? { exchange: normalizeExchange(entity.exchange) } : {}) }; const ids = new Set(objects.filter((o) => companyMatch(o, f) || nameMatch(o, 'company', entity.name ?? entity.symbol, [entity.symbol])).map((o) => o.id)); for (const r of objects.filter((o) => o.id.startsWith('relation:')) as KnowledgeRelationV04[]) if (ids.has(r.sourceRef) || ids.has(r.targetRef)) { ids.add(r.id); ids.add(r.sourceRef); ids.add(r.targetRef) } for (const c of objects.filter((o) => o.id.startsWith('claim:')) as KnowledgeClaimV04[]) if (c.subjectRefs.some((r) => ids.has(r))) ids.add(c.id); return objects.filter((o) => ids.has(o.id)).sort((a, b) => a.id.localeCompare(b.id)).slice(0, 80).map((o) => { const v = o as unknown as Dict; return { canonicalRef: o.id, kind: o.id.split(':', 1)[0], name: v.name ?? v.statement ?? null, aliases: Array.isArray(v.aliases) ? v.aliases.slice(0, 10) : [], ...v } }) }
  async submit(input: KnowledgeProductionInput): Promise<KnowledgeProductionOutcome> {
    const now = input.now ?? (() => new Date().toISOString()); const intents: ResolutionIntentSummary[] = []; const relationRefsByProposalId: Record<string, string> = {}; const entityRefsByLocalKey: Record<string, string> = {}; const claimRefsByProposalId: Record<string, string> = {}; const sourceRefsByLocalId: Record<string, string> = {}
    try {
      if (input.handle.schemaVersion !== '0.4' || input.handle.storageFormatVersion !== '1') return outcome(input, 'blocked', ['Knowledge Production Gateway requires Schema 0.4 / Storage Format 1']); const errors = localErrors(input.proposals); if (errors.length) return outcome(input, 'blocked', errors)
      const assets = await readCanonicalV04Assets(input.handle.rootRef); const objects: AssetMap = new Map(assets.objects.map((x) => [x.value.id, structuredClone(x.value)])); const operations: KnowledgeOperationV04[] = []; const createdIds: string[] = []; const updatedIds: string[] = []; const rawRefsByLocalId = new Map<string, `raw-sha256-${string}`>(); const f = companyFields(input); const entityInputs = new Map<string, KnowledgeProductionInput['entity']>([[input.entity.localKey, input.entity]]); for (const p of input.proposals) if (p.kind === 'entity' && p.entityName && p.entityType) entityInputs.set(p.subjectKey, { localKey: p.subjectKey, entityType: p.entityType, name: p.entityName, aliases: [], semanticFields: p.structuredValue ?? undefined })
      for (const [localKey, ei] of entityInputs) { let existing: KnowledgeEntityV04 | undefined; const isRoot = localKey === input.entity.localKey; if (ei.existingEntityRef) { const x = objects.get(ei.existingEntityRef); if (!x || !x.id.startsWith('entity:') || (x as KnowledgeEntityV04).type !== ei.entityType) { intents.push(intent(`entity-${localKey}`, 'review_required', 'Explicit canonical Entity ref is missing or type-mismatched', { localKey })); continue } existing = x as KnowledgeEntityV04 } else if (isRoot) { const matches = [...objects.values()].filter((o) => companyMatch(o, f)); if (matches.length > 1) { intents.push(intent(`entity-${localKey}`, 'review_required', 'Multiple canonical companies match hard identity', { localKey })); continue } existing = matches[0] as KnowledgeEntityV04 | undefined } else { const matches = [...objects.values()].filter((o) => nameMatch(o, ei.entityType, ei.name, ei.aliases ?? [])) as KnowledgeEntityV04[]; if (matches.length > 1) { intents.push(intent(`entity-${localKey}`, 'review_required', 'Multiple plausible non-Company candidates require review', { localKey })); continue } if (matches.length === 1) { const decision = this.resolver ? await this.resolver({ proposal: { proposalId: `entity-${localKey}`, kind: 'entity', subjectKey: localKey, entityType: ei.entityType, entityName: ei.name }, existing: matches.map((m) => ({ canonicalRef: m.id, type: m.type, name: m.name })), evidence: [] }) : undefined; if (decision?.outcome === 'equivalent') existing = matches[0]; else { intents.push(intent(`entity-${localKey}`, 'review_required', 'Name similarity alone cannot establish non-Company identity', { localKey, targetRef: matches[0].id })); continue } } }
        const ref = existing?.id ?? allocateEntityId(ei.entityType, ei.entityType === 'company' && text(f.ticker) ? text(f.ticker) : ei.name); entityRefsByLocalKey[localKey] = ref; if (existing) { const merged = mergeEntity(existing, { aliases: ei.aliases ?? [], semanticFields: isRoot ? f : ei.semanticFields }); if (hashKnowledgeObject(existing) !== hashKnowledgeObject(merged)) { objects.set(ref, merged); operations.push({ operationId: `update-entity-${operations.length + 1}`, type: 'update', knowledgeId: ref, expectedBeforeHash: hashKnowledgeObject(existing), object: merged }); updatedIds.push(ref) } intents.push(intent(`entity-${localKey}`, 'bound_existing', 'Bound to a validated canonical Entity', { localKey, targetRef: ref })) } else { const created = { id: ref as `entity:${string}`, type: ei.entityType, name: ei.name, aliases: [...new Set(ei.aliases ?? [])], ...(isRoot ? f : ei.semanticFields ?? {}), lifecycle: { status: 'active' } } as KnowledgeEntityV04; objects.set(ref, created); operations.push({ operationId: `create-entity-${operations.length + 1}`, type: 'create', object: created }); createdIds.push(ref); intents.push(intent(`entity-${localKey}`, 'created_new', 'No deterministic canonical Entity was proven equivalent', { localKey, targetRef: ref })) } }
      if (!entityRefsByLocalKey[input.entity.localKey]) return outcome(input, 'blocked', ['Root Entity binding requires review before dependent Knowledge can be committed'], intents, entityRefsByLocalKey, relationRefsByProposalId)
      for (const b of input.evidenceBindings) { if (validateUsableAcquisitionPayload(b.source.content).status !== 'usable') continue; const bytes = b.source.rawBytes === undefined ? new TextEncoder().encode(b.source.content) : Uint8Array.from(b.source.rawBytes); const raw = await archiveRaw(input.handle, { bytes, originalFilename: b.originalFilename ?? `${b.localSourceId}.txt`, mediaType: b.mediaType ?? 'text/plain', suppliedMetadata: { title: b.source.title, institution: b.source.publisher, publishedAt: b.source.candidate.publishedAt ?? null, sourceUrl: b.source.canonicalUrl ?? b.source.candidate.url ?? null } }, { clock: now }); const rawRef = raw.manifest.rawRef as `raw-sha256-${string}`; const hash = hashKnowledgeObject(sourceIdentity(b.source, f)); const old = [...objects.values()].find((o) => o.id.startsWith('source:') && (o as KnowledgeSourceV04).metadata?.researchSourceIdentity === hash) as KnowledgeSourceV04 | undefined; const s = sourceObject(b.source, old?.id ?? `source:research-${hash.slice(7, 23)}`, rawRef, f); const final = old ? { ...old, rawRefs: [...new Set([...(old.rawRefs ?? []), ...(s.rawRefs ?? [])])] } : s; sourceRefsByLocalId[b.localSourceId] = final.id; objects.set(final.id, final); if (!old) { operations.push({ operationId: `create-source-${operations.length + 1}`, type: 'create', object: final }); createdIds.push(final.id) } }
      const sourceRefs = (p: SemanticProductionProposal) => (p.sourceCandidateIds ?? []).map((id) => sourceRefsByLocalId[id]).filter((x): x is `source:${string}` => x !== undefined); const raw = { manifest: { rawRef: (rawRefsByLocalId.values().next().value ?? `raw-sha256-${sha256(input.evidenceBindings[0]?.source.rawBytes ?? input.evidenceBindings[0]?.source.content ?? '')}`) as `raw-sha256-${string}` } }
      for (const p of input.proposals.filter((x) => x.kind === 'relation')) { const sr = entityRefsByLocalKey[p.subjectKey]; const tr = p.targetKey ? entityRefsByLocalKey[p.targetKey] : undefined; const d = p.relationType ? KNOWLEDGE_SCHEMA_V04.relation.definitions[p.relationType as keyof typeof KNOWLEDGE_SCHEMA_V04.relation.definitions] : undefined; const se = sr ? objects.get(sr) as KnowledgeEntityV04 : undefined; const te = tr ? objects.get(tr) as KnowledgeEntityV04 : undefined; const valid = sr && tr && d && relationTypes.has(p.relationType ?? '') && se && te && (d.sourceTypes as readonly string[]).includes(se.type) && (d.targetTypes as readonly string[]).includes(te.type) && validateRelationAttributesV03(p.relationType, p.attributes).valid && sourceRefs(p).length > 0; if (!valid) { intents.push(intent(`relation-${p.proposalId}`, 'review_required', 'Relation endpoint, type, attributes, or evidence could not be resolved', { proposalId: p.proposalId })); continue } const old = [...objects.values()].find((o) => o.id.startsWith('relation:') && (o as KnowledgeRelationV04).type === p.relationType && (o as KnowledgeRelationV04).sourceRef === sr && (o as KnowledgeRelationV04).targetRef === tr && hashKnowledgeObject((o as KnowledgeRelationV04).attributes ?? null) === hashKnowledgeObject(p.attributes ?? null)) as KnowledgeRelationV04 | undefined; const id = old?.id ?? allocateKnowledgeId('relation', { type: p.relationType, sourceRef: sr, targetRef: tr, attributes: p.attributes ?? null }); relationRefsByProposalId[p.proposalId] = id; const r = { id, type: p.relationType, sourceRef: sr, targetRef: tr, ...(p.attributes === undefined ? {} : { attributes: p.attributes }), sourceRefs: [...new Set(sourceRefs(p))], lifecycle: { status: 'active' } } as unknown as KnowledgeRelationV04; objects.set(id, r); if (!old) { operations.push({ operationId: `create-relation-${operations.length + 1}`, type: 'create', object: r }); createdIds.push(id) } else if (hashKnowledgeObject(old) !== hashKnowledgeObject(r)) { operations.push({ operationId: `update-relation-${operations.length + 1}`, type: 'update', knowledgeId: id, expectedBeforeHash: hashKnowledgeObject(old), object: r }); updatedIds.push(id) } intents.push(intent(`relation-${p.proposalId}`, old ? 'bound_existing' : 'created_new', old ? 'Exact canonical Relation matched' : 'Created canonical Relation', { proposalId: p.proposalId, targetRef: id })) }
      for (const p of input.proposals.filter((x) => x.kind === 'claim')) { const srcs = sourceRefs(p); const relationSubject = input.proposals.some((x) => x.kind === 'relation' && x.proposalId === p.subjectKey); const subject = (p.resolution === 'review' ? undefined : relationRefsByProposalId[p.subjectKey] ?? entityRefsByLocalKey[p.subjectKey] ?? (relationSubject ? undefined : entityRefsByLocalKey[input.entity.localKey])) as `entity:${string}` | `relation:${string}` | undefined; if (!subject || !p.statement || !p.claimType || srcs.length === 0) { intents.push(intent(`claim-${p.proposalId}`, 'review_required', p.resolution === 'review' ? 'Producer marked semantic resolution for review' : relationSubject ? 'Relation subject unresolved; no root fallback permitted' : 'Claim lacks a bound subject, source, or statement', { proposalId: p.proposalId })); continue } const requested = p.resolution === 'update' && p.existingKnowledgeRefs?.length === 1 ? objects.get(p.existingKnowledgeRefs[0]) as KnowledgeClaimV04 | undefined : undefined; const exact = requested ?? [...objects.values()].find((o) => exactClaim(o, claimIdentity(p, subject))) as KnowledgeClaimV04 | undefined; const incoming = validStructured(p.structuredValue); let old = exact ?? (p.resolution === 'supersede' && incoming ? [...objects.values()].find((o) => o.id.startsWith('claim:') && (o as KnowledgeClaimV04).subjectRefs.includes(subject) && validStructured((o as KnowledgeClaimV04).structuredValue)?.metric === incoming.metric) as KnowledgeClaimV04 | undefined : undefined); const id = exact?.id ?? allocateKnowledgeId('claim', claimIdentity(p, subject)).replace('claim:', 'claim:research-'); claimRefsByProposalId[p.proposalId] = id; const rawProvenance = srcs.map((sourceRef) => ({ sourceRef, rawRef: raw.manifest.rawRef, locator: null, chunkRef: null }))
        const claim = { id, claimType: p.claimType, statement: p.statement, subjectRefs: [subject], primarySubjectRef: subject, ...(p.temporal === undefined ? {} : { temporal: p.temporal }), ...(validStructured(p.structuredValue) ? { structuredValue: validStructured(p.structuredValue) } : {}), sourceRefs: srcs, provenance: rawProvenance, confidence: p.confidence ?? 0.5, probability: p.probability, lifecycle: { status: 'active' } } as unknown as KnowledgeClaimV04; if (p.resolution === 'supersede' && old && old.id !== id) { const superseded = { ...old, lifecycle: { ...old.lifecycle, status: 'superseded' as const }, supersededBy: [...new Set([...(old.supersededBy ?? []), id as `claim:${string}`])] } as KnowledgeClaimV04; objects.set(old.id, superseded); operations.push({ operationId: `supersede-claim-${operations.length + 1}`, type: 'update', knowledgeId: old.id, expectedBeforeHash: hashKnowledgeObject(old), object: superseded }); updatedIds.push(old.id); old = undefined as never } if (!old) { objects.set(id, claim); operations.push({ operationId: `create-claim-${operations.length + 1}`, type: 'create', object: claim }); createdIds.push(id) } else { const merged = { ...old, ...(p.resolution === 'update' && validStructured(p.structuredValue) ? { structuredValue: validStructured(p.structuredValue) } : {}), sourceRefs: [...new Set([...(old.sourceRefs ?? []), ...srcs])] } as KnowledgeClaimV04; if (hashKnowledgeObject(old) !== hashKnowledgeObject(merged)) { operations.push({ operationId: `update-claim-${operations.length + 1}`, type: 'update', knowledgeId: id, expectedBeforeHash: hashKnowledgeObject(old), object: merged }); updatedIds.push(id) } objects.set(id, merged) } intents.push(intent(`claim-${p.proposalId}`, old ? 'bound_existing' : 'created_new', old ? 'Exact canonical Claim matched' : 'Created canonical Claim', { proposalId: p.proposalId, targetRef: id })) }
      const reviewProposals = input.proposals.filter((p) => p.kind === 'claim' && p.resolution === 'review'); if (reviewProposals.length) await persistReviewCases({ rootRef: input.handle.rootRef, knowledgeBaseId: input.handle.knowledgeBaseId, producerRunId: input.producerRunId, producerType: input.reviewProducerType ?? input.producerType, cases: reviewProposals.map((p) => reviewCase(input, p, raw.manifest.rawRef)), createdAt: now(), knowledgeBaseRevisionAtCreation: input.handle.revision })
      if (!operations.length) return { status: 'no_changes', knowledgeBaseId: input.handle.knowledgeBaseId, knowledgeBaseRevision: input.handle.revision, baseRevision: input.handle.revision, createdIds: [], updatedIds: [], sourceRefsByLocalId, claimRefsByProposalId, entityRefsByLocalKey, relationRefsByProposalId, resolutionIntents: intents, errors: [] }
      const cs: KnowledgeChangeSetV04 = { changeSetId: `changeset-${input.producerType}-${sha256(JSON.stringify(operations.map((o) => o.operationId))).slice(0, 20)}`, workflowRunId: input.producerRunId, knowledgeBaseId: input.handle.knowledgeBaseId, schemaVersion: '0.4', storageFormatVersion: '1', expectedBaseRevision: input.handle.revision, operations, ingestionContext: { producerType: input.producerType, producerRunId: input.producerRunId, asOf: input.asOf ?? null } }; const v = await validateKnowledgeChangeSetV04(input.handle, cs, { mode: 'commit', now }); if (!v.validatedChangeSet) return outcome(input, 'blocked', v.report.errors.map((e) => `${e.code}: ${e.message}`), intents, entityRefsByLocalKey, relationRefsByProposalId); const w = await writeKnowledgeBase(input.handle, v.validatedChangeSet, { registry: this.registry, clock: now }) as KnowledgeWriteResultV04; if (w.status === 'failed' || w.status === 'rejected') return outcome(input, 'failed', [w.error?.message ?? 'Shared Writer rejected the validated ChangeSet'], intents, entityRefsByLocalKey, relationRefsByProposalId); return { status: w.status, knowledgeBaseId: input.handle.knowledgeBaseId, knowledgeBaseRevision: w.committedRevision, baseRevision: input.handle.revision, changeSetId: cs.changeSetId, createdIds: w.createdIds, updatedIds: w.updatedIds, sourceRefsByLocalId, claimRefsByProposalId, entityRefsByLocalKey, relationRefsByProposalId, resolutionIntents: intents, errors: [] }
    } catch (e) { return outcome(input, 'failed', [e instanceof Error ? e.message : String(e)], intents, entityRefsByLocalKey, relationRefsByProposalId) }
  }
}
