import type { DailySignalCluster, ResearchChangeAssessment, ResearchChangeDisposition } from '../../plugins/daily-intelligence/contracts.ts'
import type { ReasoningExecutor } from '../../plugins/reasoning/contracts.ts'

export interface ExistingKnowledgeProjection { readonly canonicalRef: string; readonly kind: string; readonly statement?: string; readonly name?: string; readonly claimType?: string; readonly type?: string; readonly subjectRefs?: readonly string[] }
export interface ChangeAssessmentResult { readonly assessment: ResearchChangeAssessment; readonly reasoningUsed: boolean; readonly applied: boolean }
const dispositions: readonly ResearchChangeDisposition[] = ['new', 'supports', 'contradicts', 'changes_assumption', 'affects_thesis', 'catalyst', 'risk', 'noise']
export class DailyChangeAssessmentSkill {
  async assess(cluster: DailySignalCluster, projection: readonly ExistingKnowledgeProjection[], watchlist: readonly string[], executor?: ReasoningExecutor): Promise<ChangeAssessmentResult> { const deterministic = precheck(cluster, projection, watchlist); if (deterministic) return { assessment: deterministic, reasoningUsed: false, applied: false }; if (!executor) return { assessment: fallback(cluster), reasoningUsed: false, applied: false }; try { const result = await executor.execute({ operation: 'daily_change_assessment', instruction: 'Compare this cluster with only the supplied bounded projection. Return valid local references and no canonical allocations.', input: { cluster, existingKnowledge: projection.slice(0, 40), watchlist }, outputContract: { clusterId: cluster.clusterId, disposition: dispositions, relatedKnowledgeRefs: ['canonicalRef from input'], rationale: 'string', durableCandidate: false, subjectKey: 'watchlist symbol' }, metadata: { workflow: 'daily-intelligence' } }); const value = result.output as Record<string, unknown>; const refs = Array.isArray(value?.relatedKnowledgeRefs) ? value.relatedKnowledgeRefs.filter((ref): ref is string => typeof ref === 'string') : []; const allowed = new Set(projection.map((item) => item.canonicalRef)); if (value?.clusterId !== cluster.clusterId || typeof value.disposition !== 'string' || !dispositions.includes(value.disposition as ResearchChangeDisposition) || refs.some((ref) => !allowed.has(ref))) return { assessment: fallback(cluster), reasoningUsed: true, applied: false }; const symbols = new Set([...watchlist, ...cluster.entities]); const subjectKey = typeof value.subjectKey === 'string' && symbols.has(value.subjectKey) ? value.subjectKey : undefined; return { assessment: { clusterId: cluster.clusterId, disposition: value.disposition as ResearchChangeDisposition, relatedKnowledgeRefs: refs, rationale: typeof value.rationale === 'string' ? value.rationale.slice(0, 1000) : 'Validated semantic comparison.', durableCandidate: value.durableCandidate === true && refs.length > 0, ...(subjectKey ? { subjectKey } : {}) }, reasoningUsed: true, applied: true } } catch { return { assessment: fallback(cluster), reasoningUsed: false, applied: false } } }
}
function precheck(cluster: DailySignalCluster, projection: readonly ExistingKnowledgeProjection[], watchlist: readonly string[]): ResearchChangeAssessment | undefined { const text = cluster.signals.map((signal) => `${signal.title} ${signal.excerpt ?? ''}`).join(' ').toLowerCase(); const relevant = projection.filter((item) => item.statement && overlap(text, item.statement.toLowerCase())).map((item) => item.canonicalRef); if (cluster.signals.every((signal) => signal.kind === 'community')) return { clusterId: cluster.clusterId, disposition: 'noise', relatedKnowledgeRefs: relevant, rationale: 'Community-only low-confidence signal.', durableCandidate: false }; if (!relevant.length) return undefined; const matched = projection.filter((item) => relevant.includes(item.canonicalRef)); const labels = matched.map((item) => `${item.kind} ${item.claimType ?? ''} ${item.type ?? ''}`).join(' '); let disposition: ResearchChangeDisposition = 'supports'; if (/指引|下调|下降|延迟|库存|恶化|违约|取消|down|cut|delay|decline/.test(text) && /assumption|thesis|claim/i.test(labels)) disposition = /assumption/i.test(labels) ? 'changes_assumption' : /thesis/i.test(labels) ? 'affects_thesis' : 'contradicts'; else if (/风险|下滑|下降|减产|亏损|处罚|诉讼|risk|down|cut|delay|decline/.test(text)) disposition = 'risk'; else if (/订单|扩产|增长|突破|合作|利好|order|expand|growth|breakthrough/.test(text)) disposition = 'catalyst'; const subjectKey = cluster.entities.find((entity) => watchlist.includes(entity)); return { clusterId: cluster.clusterId, disposition, relatedKnowledgeRefs: relevant, rationale: `Deterministic comparison against ${relevant.length} relevant projection item(s).`, durableCandidate: cluster.signals.some((signal) => signal.sourceTier <= 2), ...(subjectKey ? { subjectKey } : {}) } }
function overlap(text: string, statement: string): boolean { const tokens = statement.split(/[^\p{L}\p{N}]+/u).filter((token) => token.length >= 2); return tokens.filter((token) => text.includes(token)).length >= Math.min(2, tokens.length) }
function fallback(cluster: DailySignalCluster): ResearchChangeAssessment { return { clusterId: cluster.clusterId, disposition: cluster.signals.every((signal) => signal.kind === 'community') ? 'noise' : 'new', relatedKnowledgeRefs: [], rationale: 'No deterministic match; no durable semantic conclusion was made.', durableCandidate: false } }
