import type { DailyResearchSignal } from '../../plugins/daily-intelligence/contracts.ts'
import type { ReasoningExecutor } from '../../plugins/reasoning/contracts.ts'

export interface DailySignalEnrichment { readonly signal: DailyResearchSignal; readonly entities: readonly string[]; readonly themes: readonly string[]; readonly category: DailyResearchSignal['category']; readonly rationale: string }
export interface DailyEnrichmentResult { readonly signals: readonly DailyResearchSignal[]; readonly reasoningUsed: boolean; readonly appliedCount: number; readonly fallbackCount: number }
export class DailyIntelligenceSignalEnrichmentSkill {
  enrich(signal: DailyResearchSignal, watchlistSymbols: readonly string[], focusTags: readonly string[]): DailySignalEnrichment { const value = `${signal.title} ${signal.excerpt ?? ''}`.toLowerCase(); const entities = [...new Set([...signal.entities, ...watchlistSymbols.filter((item) => value.includes(item.toLowerCase()))])].sort(); const themes = [...new Set([...signal.themes, ...focusTags.filter((item) => value.includes(item.toLowerCase()))])].sort(); const category = signal.category === 'news' && /公告|业绩|财报|年报|季报|investor|guidance/i.test(value) ? 'earnings' : signal.category; return { signal: { ...signal, entities, themes, category }, entities, themes, category, rationale: `bounded lexical enrichment; entities=${entities.length}; themes=${themes.length}` } }
  enrichMany(signals: readonly DailyResearchSignal[], watchlistSymbols: readonly string[], focusTags: readonly string[], _executor?: ReasoningExecutor): DailyResearchSignal[] { return signals.map((signal) => this.enrich(signal, watchlistSymbols, focusTags).signal) }
  async enrichManyAsync(signals: readonly DailyResearchSignal[], watchlistSymbols: readonly string[], focusTags: readonly string[], executor?: ReasoningExecutor): Promise<DailyResearchSignal[]> { return (await this.enrichManyDetailedAsync(signals, watchlistSymbols, focusTags, executor)).signals as DailyResearchSignal[] }
  async enrichManyDetailedAsync(signals: readonly DailyResearchSignal[], watchlistSymbols: readonly string[], focusTags: readonly string[], executor?: ReasoningExecutor): Promise<DailyEnrichmentResult> {
    const lexical = signals.map((signal) => this.enrich(signal, watchlistSymbols, focusTags).signal); if (!executor || lexical.length === 0) return { signals: lexical, reasoningUsed: false, appliedCount: 0, fallbackCount: lexical.length }
    try { const result = await executor.execute({ operation: 'daily_signal_enrichment', instruction: 'Return only validated semantic fields for supplied signal IDs. Never modify identity, source, hashes, timestamps, or canonical IDs.', input: { signals: lexical, watchlistSymbols, focusTags }, outputContract: { signals: [{ signalId: 'string', entities: ['watchlist-symbol'], themes: ['string'], category: 'string', relevance: 0.0, sentiment: 0.0, importance: 0.0, narrative: 'string' }] }, metadata: { workflow: 'daily-intelligence' } }); const rows = Array.isArray((result.output as { signals?: unknown })?.signals) ? (result.output as { signals: unknown[] }).signals : []; const ids = new Set(lexical.map((signal) => signal.signalId)); const byId = new Map<string, Partial<DailyResearchSignal>>(); for (const raw of rows) { if (!raw || typeof raw !== 'object') continue; const row = raw as Record<string, unknown>; if (typeof row.signalId !== 'string' || !ids.has(row.signalId)) continue; const entities = Array.isArray(row.entities) ? row.entities.filter((item): item is string => typeof item === 'string' && watchlistSymbols.includes(item)) : []; const themes = Array.isArray(row.themes) ? row.themes.filter((item): item is string => typeof item === 'string' && focusTags.includes(item)) : []; const category = typeof row.category === 'string' && ['announcement', 'earnings', 'performance_forecast', 'investor_relations', 'institutional_research', 'management_guidance', 'macro', 'market', 'community', 'technology', 'industry', 'news'].includes(row.category) ? row.category as DailyResearchSignal['category'] : undefined; if (!category) continue; byId.set(row.signalId, { entities, themes, category, relevance: bounded(row.relevance, 0, 1), sentiment: boundedOptional(row.sentiment, -1, 1), importance: bounded(row.importance, 0, 1), narrative: typeof row.narrative === 'string' ? row.narrative.slice(0, 1000) : undefined }) } const applied = lexical.map((signal) => { const patch = byId.get(signal.signalId); return patch ? { ...signal, ...patch } : signal }); return { signals: applied, reasoningUsed: true, appliedCount: byId.size, fallbackCount: lexical.length - byId.size } } catch { return { signals: lexical, reasoningUsed: false, appliedCount: 0, fallbackCount: lexical.length } }
  }
}
function bounded(value: unknown, min: number, max: number): number { return typeof value === 'number' && Number.isFinite(value) ? Math.max(min, Math.min(max, value)) : (min + max) / 2 }
function boundedOptional(value: unknown, min: number, max: number): number | undefined { return typeof value === 'number' && Number.isFinite(value) ? Math.max(min, Math.min(max, value)) : undefined }
