import type { DailyBriefSection, DailyResearchSignal, DailySignalCluster, DailyBriefType, ResearchChangeAssessment } from '../../plugins/daily-intelligence/contracts.ts'
import type { ReasoningExecutor } from '../../plugins/reasoning/contracts.ts'

const MORNING = ['Overnight Global', 'Macro/Policy', 'A-share Important Announcements', 'Market/Futures/Major Asset', 'AI/Technology/Industry', 'Public Institutional Views', 'IR/Institution Research', 'Watchlist', 'Community/Sentiment', 'Existing Thesis Changes', 'Catalysts', 'Risks', 'Research Gaps', "Today's Questions"]
const EVENING = ['A-share summary', 'Sector/Industry/Theme', 'Important Events', 'Announcements', 'Institutional Views', 'IR', 'Community Narrative', 'Watchlist', 'Knowledge changes', 'Thesis/Assumption impacts', 'Catalysts/Risks', 'Gaps', 'Tomorrow Watchlist']

export interface DailySynthesisResult { readonly sections: readonly DailyBriefSection[]; readonly proposals: readonly { readonly proposalId: string; readonly kind: 'claim'; readonly subjectKey: string; readonly claimType: 'viewpoint' | 'risk' | 'trend'; readonly statement: string; readonly sourceCandidateIds: readonly string[]; readonly confidence: number }[]; readonly reasoningUsed: boolean }

export class DailyBriefSynthesisSkill {
  async synthesize(type: DailyBriefType, signals: readonly DailyResearchSignal[], clusters: readonly DailySignalCluster[], assessments: readonly ResearchChangeAssessment[], executor?: ReasoningExecutor): Promise<DailySynthesisResult> {
    let reasoningUsed = false
    if (executor) { try { await executor.execute({ operation: 'company_research_synthesis', instruction: 'Produce bounded daily intelligence section suggestions. Never invent facts; every item must cite provided signal IDs.', input: { type, signals: signals.slice(0, 30), clusters: clusters.slice(0, 20), assessments: assessments.slice(0, 20) }, outputContract: { sections: 'array', proposals: 'array' }, metadata: { workflow: 'daily-intelligence' } }); reasoningUsed = true } catch { reasoningUsed = false } }
    const names = type === 'morning' ? MORNING : EVENING
    const sections = names.map((title, index) => { const selected = signals.filter((signal) => sectionMatches(title, signal)).slice(0, 5); const unavailable = selected.length === 0; const items = unavailable ? [{ itemId: `gap-${index + 1}`, headline: 'Unavailable / no usable public signal', markdown: 'Unavailable: configured public providers returned no usable signal for this section. No consensus or paid-data claim is inferred.', signalRefs: [], sourceRefs: [], kind: 'gap' as const, rank: 1 }] : selected.map((signal, rank) => ({ itemId: `item-${index + 1}-${rank + 1}`, headline: signal.title, markdown: `${signal.excerpt ?? signal.title}\n\nSource: ${signal.source.url ?? signal.provider}.`, signalRefs: [signal.signalId], sourceRefs: signal.source.url ? [`source:${signal.signalId}`] : [], kind: 'signal' as const, rank: rank + 1 })); return { id: title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''), title, items, ...(unavailable ? { unavailable: true } : {}) } })
    const proposals = assessments.filter((assessment) => assessment.durableCandidate).slice(0, 20).map((assessment, index) => ({ proposalId: `daily-proposal-${index + 1}`, kind: 'claim' as const, subjectKey: assessment.clusterId, claimType: assessment.disposition === 'risk' ? 'risk' as const : assessment.disposition === 'catalyst' ? 'trend' as const : 'viewpoint' as const, statement: assessment.rationale, sourceCandidateIds: [], confidence: 0.5 }))
    return { sections, proposals, reasoningUsed }
  }
}
function sectionMatches(section: string, signal: DailyResearchSignal): boolean { const text = `${signal.title} ${signal.category} ${signal.kind}`.toLowerCase(); if (/announcement|公告/.test(section)) return signal.kind === 'announcement' || signal.category === 'announcement' || signal.category === 'earnings'; if (/institution|ir/.test(section)) return signal.kind === 'institutional_view' || signal.category === 'institutional_research' || signal.category === 'investor_relations'; if (/community|narrative|sentiment/.test(section)) return signal.kind === 'community' || signal.kind === 'social_attention'; if (/market|summary|sector|industry|theme/.test(section)) return signal.kind === 'market' || signal.category === 'market' || signal.category === 'industry'; return text.length > 0
}
