import assert from 'node:assert/strict'
import test from 'node:test'
import { CpcaIndustryResearchPlugin, CPCA_INDUSTRY_ROUTES, validCpcaUrl } from '../../../plugins/research-acquisition/cpca-industry.ts'
import { sha256 } from '../../../plugins/research-acquisition/hash.ts'

const request = { industry: { name: 'PCB Manufacturing', aliases: ['Printed Circuit Board', '印制电路板'], searchTerms: ['PCB', '印制电路板', 'HDI'] }, asOf: '2026-09-14T00:00:00.000Z', limitPerKind: 8 }
const html = (body: string, url = '') => { const response = new Response(body, { headers: { 'content-type': 'text/html' } }); if (url) Object.defineProperty(response, 'url', { value: url }); return response }
const resolver = { async parse(source: { bytes: Uint8Array }) { return { documentId: 'fixture', parser: 'fixture', metadata: {}, sections: [], blocks: [], normalizedText: new TextDecoder().decode(source.bytes).replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim(), warnings: [] } } } as any
const candidate = (url: string, title = 'PCB market analysis') => ({ candidateId: `cpca-${sha256(url)}`, kind: 'web_article' as const, tier: 4 as const, title, provider: 'cpca', url })

test('discovers all three bounded route families, relative links, pagination and deterministic ranking', async () => {
  const calls: string[] = []; const plugin = new CpcaIndustryResearchPlugin({ documentResolver: resolver, fetchImpl: async (input) => { const url = String(input); calls.push(url); if (url === CPCA_INDUSTRY_ROUTES[0]) return html('<a href="detail-a.html">PCB industry analysis 2026</a><span>2026-01-02</span><a href="?page=2">下一页</a>', url); if (url.includes('page=2')) return html('<a href="/detail-dup.html">PCB market analysis 2026</a><span>2026-02-02</span>', url); if (url === CPCA_INDUSTRY_ROUTES[1]) return html('<a href="market.pdf">PCB market analysis 2026</a><span>2026-03-03</span>', url); return html('<a href="weekly.html">PCB weekly industry information 2026</a><span>2026-04-04</span>', url) } })
  const values = await plugin.discover(request); assert.equal(calls.length, 4); assert.equal(values.length, 4); assert.equal(values[0]!.tier, 4); assert.ok(values.some((x) => x.url === 'https://www.cpca.org.cn/detail-a.html')); assert.ok(values.some((x) => x.url === 'https://www.cpca.org.cn/market.pdf')); assert.equal(new Set(values.map((x) => x.url)).size, values.length); assert.equal(values.find((x) => x.url?.endsWith('detail-a.html'))?.publishedAt, '2026-01-02T00:00:00.000Z')
})
test('is Industry-only and validates the exact public CPCA hosts', async () => { let calls = 0; const plugin = new CpcaIndustryResearchPlugin({ fetchImpl: async () => { calls++; throw new Error('network') } }); assert.deepEqual(await plugin.discover({ company: { symbol: '600519' } }), []); assert.equal(calls, 0); assert.equal(validCpcaUrl('https://cpca.org.cn/x'), true); assert.equal(validCpcaUrl('https://www.cpca.org.cn/x'), true); assert.equal(validCpcaUrl('https://sub.cpca.org.cn/x'), false); assert.equal(validCpcaUrl('http://www.cpca.org.cn/x'), false) })
test('fetches and normalizes public HTML and supported PDF with provenance and rights', async () => { const plugin = new CpcaIndustryResearchPlugin({ documentResolver: resolver, fetchImpl: async (input) => html(String(input).endsWith('.pdf') ? '%PDF PCB market' : '<html><body>public PCB industry evidence</body></html>'), now: () => '2026-09-14T01:00:00.000Z' }); for (const item of [candidate('https://www.cpca.org.cn/detail.html'), candidate('https://www.cpca.org.cn/market.pdf')]) { const normalized = await plugin.normalize(await plugin.fetch(item)); assert.equal(normalized.publisher, 'China Printed Circuit Association'); assert.equal(normalized.candidate.tier, 4); assert.equal(normalized.rights.redistributionAllowed, false); assert.equal(normalized.contentHash, sha256(normalized.rawBytes!)) } })
test('does not classify ordinary navigation login or membership links as restricted', async () => { const plugin = new CpcaIndustryResearchPlugin({ documentResolver: resolver, fetchImpl: async () => html('<html><header>登录 会员中心</header><nav>登录 | 会员服务</nav><main><h1>PCB market analysis</h1><p>Public substantive industry evidence and market data.</p></main><footer>会员订阅</footer></html>') }); const normalized = await plugin.normalize(await plugin.fetch(candidate('https://www.cpca.org.cn/public.html'))); assert.match(normalized.content, /Public substantive/) })
test('rejects restricted redirects, teaser content, unsupported content and oversized payloads', async () => { const item = candidate('https://www.cpca.org.cn/detail.html'); const redirected = new CpcaIndustryResearchPlugin({ fetchImpl: async () => html('x', 'https://login.cpca.org.cn/login') }); await assert.rejects(() => redirected.fetch(item), /redirect/); const restricted = new CpcaIndustryResearchPlugin({ fetchImpl: async () => html('<html>请登录会员后购买订阅</html>') }); await assert.rejects(() => restricted.fetch(item), /restricted|teaser/); const binary = new CpcaIndustryResearchPlugin({ fetchImpl: async () => new Response('x', { headers: { 'content-type': 'application/zip' } }) }); await assert.rejects(() => binary.fetch(item), /unsupported/); const large = new CpcaIndustryResearchPlugin({ maxDocumentPayloadBytes: 10, fetchImpl: async () => html('x'.repeat(100)) }); await assert.rejects(() => large.fetch(item), /exceeds/) })
test('resolves pagination from the validated final list URL and ignores off-site links', async () => { const calls: string[] = []; const plugin = new CpcaIndustryResearchPlugin({ routes: [CPCA_INDUSTRY_ROUTES[0]], fetchImpl: async (input) => { calls.push(String(input)); if (calls.length === 1) return html('<a href="article.html">PCB detail</a><a href="page/2/">next</a><a href="https://evil.example/x">PCB evil</a>', 'https://www.cpca.org.cn/current/list/'); return html('<a href="article-2.html">PCB second</a>', String(input)) } }); const values = await plugin.discover(request); assert.deepEqual(calls, [CPCA_INDUSTRY_ROUTES[0], 'https://www.cpca.org.cn/current/list/page/2/']); assert.equal(values.length, 2); assert.ok(values.every((x) => validCpcaUrl(x.url))) })
test('times out and returns empty discovery for generic-only or empty pages', async () => { const empty = new CpcaIndustryResearchPlugin({ routes: [CPCA_INDUSTRY_ROUTES[0]], fetchImpl: async () => html('<a href="generic.html">Industry information</a>') }); assert.deepEqual(await empty.discover(request), []); const stalled = new CpcaIndustryResearchPlugin({ timeoutMs: 5, fetchImpl: async (_input, init) => await new Promise<Response>((_resolve, reject) => init?.signal?.addEventListener('abort', () => reject(new DOMException('aborted', 'AbortError'))) ) }); await assert.rejects(() => stalled.discover(request), /aborted|AbortError/) })
