import assert from 'node:assert/strict'
import test from 'node:test'
import { GovCnIndustryResearchPlugin } from '../../../plugins/research-acquisition/govcn-industry.ts'
import { sha256 } from '../../../plugins/research-acquisition/hash.ts'

const request = { industry: { name: 'PCB Manufacturing', aliases: ['Printed Circuit Board', '印制电路板'], searchTerms: ['PCB', '电子信息制造业', '线路板'] }, asOf: '2026-09-12T00:00:00.000Z', limitPerKind: 8 }
const api = (rows: unknown[], status = 200) => new Response(JSON.stringify({ data: { list: rows } }), { status, headers: { 'content-type': 'application/json' } })
const row = (title: string, url = 'https://www.gov.cn/zhengce/2026-01/01/content_1.htm', extra: Record<string, unknown> = {}) => ({ title, url, pubOrg: '工业和信息化部', pubTime: '2026-01-01', summary: '官方政策与产业技术信息', ...extra })

test('Company discovery is empty with zero network requests', async () => { let calls = 0; const plugin = new GovCnIndustryResearchPlugin({ fetchImpl: async () => { calls++; throw new Error('network') } }); assert.deepEqual(await plugin.discover({ company: { symbol: '600519' } }), []); assert.equal(calls, 0) })

test('constructs bounded government queries and at most eight requests', async () => { const urls: string[] = []; const plugin = new GovCnIndustryResearchPlugin({ fetchImpl: async (url) => { urls.push(String(url)); return api([]) } }); await plugin.discover(request); assert.ok(urls.length <= 8 && urls.length > 0); assert.ok(urls.every((value) => { const url = new URL(value); return url.origin === 'https://sousuo.www.gov.cn' && url.searchParams.get('t') === 'zhengcelibrary_gw_bm_gb' && url.searchParams.get('searchfield') === 'title:content:summary' && url.searchParams.get('orderBy') === 'RELEVANCE' && (url.searchParams.get('q')?.length ?? 999) <= 120 && Number(url.searchParams.get('pageSize')) <= 10 })) })

test('accepts documented empty responses and rejects malformed, HTTP, and oversized responses', async () => { const empty = new GovCnIndustryResearchPlugin({ fetchImpl: async () => new Response(JSON.stringify({ data: { total: 0, list: [] } })) }); assert.deepEqual(await empty.discover(request), []); const malformed = new GovCnIndustryResearchPlugin({ fetchImpl: async () => new Response('{bad') }); await assert.rejects(() => malformed.discover(request), /JSON|bounded/); const http = new GovCnIndustryResearchPlugin({ fetchImpl: async () => new Response('{}', { status: 503 }) }); await assert.rejects(() => http.discover(request), /HTTP 503/); const oversized = new GovCnIndustryResearchPlugin({ maxSearchPayloadBytes: 20, fetchImpl: async () => new Response('x'.repeat(100)) }); await assert.rejects(() => oversized.discover(request), /exceeds bound/) })

test('filters non-government URLs, deduplicates and ranks target-specific Chinese terms', async () => { const plugin = new GovCnIndustryResearchPlugin({ fetchImpl: async () => api([row('产业制造行业政策', 'https://www.gov.cn/generic'), row('印制电路板技术规范', undefined, { url: 'https://miit.gov.cn/tech/1', summary: '印制电路板技术与产业链政策' }), row('印制电路板技术规范', 'https://evil.example/a')]) }); const candidates = await plugin.discover({ ...request, limitPerKind: 2 }); assert.equal(candidates.length, 1); assert.equal(candidates[0]!.url, 'https://miit.gov.cn/tech/1'); assert.equal(candidates[0]!.tier, 1); assert.equal(candidates[0]!.provider, 'govcn') })

test('fetch accepts same-domain redirects and HTML, rejects cross-domain redirects and binary content', async () => { const sourceCandidate = (url = 'https://www.gov.cn/a') => ({ candidateId: `govcn-${sha256(url)}`, kind: 'web_article' as const, tier: 1 as const, title: '官方产业政策', provider: 'govcn', url }); const valid = sourceCandidate(); const plugin = new GovCnIndustryResearchPlugin({ fetchImpl: async () => new Response('<html><body>官方产业政策文本</body></html>', { headers: { 'content-type': 'text/html' } }), now: () => '2026-09-12T00:00:00.000Z' }); const source = await plugin.fetch(valid); assert.equal(source.rawBytes!.byteLength > 0, true); assert.equal(source.contentHash!.length, 64); const binary = new GovCnIndustryResearchPlugin({ fetchImpl: async () => new Response('binary', { headers: { 'content-type': 'application/zip' } }) }); await assert.rejects(() => binary.fetch(valid), /unsupported/); await assert.rejects(() => plugin.fetch({ ...valid, url: 'https://evil.example/a', candidateId: `govcn-${sha256('https://evil.example/a')}` }), /candidate|Gov.cn/) })

test('normalizes through DocumentInputResolver, strips markup, preserves provenance and rights', async () => { const candidate = { candidateId: `govcn-${sha256('https://www.gov.cn/a')}`, kind: 'web_article' as const, tier: 1 as const, title: '官方产业政策', provider: 'govcn', url: 'https://www.gov.cn/a', metadata: { publicationOrganization: '工业和信息化部' } }; const plugin = new GovCnIndustryResearchPlugin({ fetchImpl: async () => new Response('<html><head><style>x</style></head><body><h1>官方产业政策</h1><p>印制电路板技术标准。</p></body></html>', { headers: { 'content-type': 'text/html' } }), now: () => '2026-09-12T00:00:00.000Z' }); const normalized = await plugin.normalize(await plugin.fetch(candidate)); assert.match(normalized.content, /印制电路板技术标准/); assert.doesNotMatch(normalized.content, /<html|<p>/); assert.equal(normalized.publisher, '工业和信息化部'); assert.equal(normalized.canonicalUrl, 'https://www.gov.cn/a'); assert.equal(normalized.contentHash, sha256(normalized.rawBytes!)); assert.deepEqual(normalized.rights, { accessScope: 'public', retentionAllowed: true, aiProcessingAllowed: true, derivativeKnowledgeAllowed: true, redistributionAllowed: false, policyBasis: 'personal_noncommercial_research' }) })
