import assert from 'node:assert/strict'
import test from 'node:test'
import { AkshareIndustryResearchPlugin } from '../../../plugins/research-acquisition/industry.ts'
import { GdeltResearchPlugin } from '../../../plugins/research-acquisition/gdelt.ts'
import { IndustryAcquisitionComposition } from '../../../plugins/research-acquisition/industry-composition.ts'

const req = { company: { symbol: 'INDUSTRY' }, industry: { name: 'PCB', aliases: ['印制电路板'], searchTerms: ['PCB', 'HDI'] }, limitPerKind: 99 }
test('Industry GDELT query is bounded and does not use a company symbol', async () => { let seen = ''; const plugin = new GdeltResearchPlugin({ endpoint: 'https://fixture.invalid', fetchImpl: async (input) => { seen = String(input); return new Response(JSON.stringify({ articles: [] }), { status: 200 }) } }); await plugin.discover(req); const url = new URL(seen); assert.ok(url.searchParams.get('query')!.length <= 900); assert.equal(url.searchParams.get('maxrecords'), '20'); assert.match(url.searchParams.get('query')!, /PCB/); assert.doesNotMatch(url.searchParams.get('query')!, /INDUSTRY/) })
test('AKShare Industry source requires one exact board and carries public structured evidence', async () => { const plugin = new AkshareIndustryResearchPlugin({ companyBasic: async () => [], financialData: async () => [], historicalMarketData: async () => [], sectorPerformance: async () => [{ 板块名称: 'PCB', 涨跌幅: 1.2, observation: '2026-09-01' }] }); const candidates = await plugin.discover(req); assert.equal(candidates.length, 1); const source = await plugin.normalize(await plugin.fetch(candidates[0]!)); assert.equal(source.candidate.kind, 'structured_data'); assert.equal(source.publisher, 'AKShare'); assert.equal(source.rights.accessScope, 'public'); assert.equal(source.rights.derivativeKnowledgeAllowed, true) })
test('Industry composition degrades a failed provider and deduplicates stable source identity', async () => { const source = (id: string) => ({ candidate: { candidateId: id, kind: 'news' as const, tier: 3 as const, title: id, url: `https://fixture/${id}`, provider: id }, retrievedAt: '2026-09-01T00:00:00.000Z', title: id, content: 'bounded evidence', canonicalUrl: `https://fixture/${id}`, contentHash: id.padEnd(64, '0'), publisher: id, rights: { accessScope: 'public' as const, retentionAllowed: true, aiProcessingAllowed: true, derivativeKnowledgeAllowed: true, redistributionAllowed: false } }); const ok = { name: 'ok', discover: async () => [{ candidateId: 'a', kind: 'news' as const, tier: 3 as const, title: 'A', url: 'https://fixture/a', provider: 'ok' }, { candidateId: 'duplicate', kind: 'news' as const, tier: 3 as const, title: 'D', url: 'https://fixture/a', provider: 'ok' }], fetch: async (c: any) => ({ candidate: c, retrievedAt: '2026-09-01T00:00:00.000Z', content: 'x' }), normalize: async (s: any) => ({ ...source(s.candidate.candidateId), canonicalUrl: s.candidate.url }) }; const failed = { name: 'failed', discover: async () => { throw new Error('offline') }, fetch: async () => { throw new Error('never') }, normalize: async () => { throw new Error('never') } }; const result = await new IndustryAcquisitionComposition([failed, ok]).acquire({ target: req.industry, wave: 1, design: {} as any, gaps: [], searchTerms: req.industry.searchTerms }); assert.equal(result.sources.length, 1); assert.equal(result.outcomes[0]!.providerFailed, true); assert.equal(result.outcomes[1]!.usableSourceCount, 1); assert.doesNotMatch(JSON.stringify(result.diagnostics), /offline/) })
