import type { NormalizedResearchSource } from '../../plugins/research-acquisition/contracts.ts'
import type { SemanticProductionProposal } from '../../knowledge/production/contracts.ts'
export const INDUSTRY_MODULES = ['industry_definition','market_size_growth','supply_demand_analysis','industry_chain_analysis','competitive_landscape','technology_evolution','company_mapping','risk_analysis'] as const
export type IndustryResearchModule = typeof INDUSTRY_MODULES[number]
export type IndustryTargetKind = 'industry'|'theme'|'product'|'technology'|'uncertain'
export const INDUSTRY_RELATION_TYPES = ['upstream_of','business_exposure','belongs_to_industry','offers_product','component_of','develops_technology','uses_technology','applied_in','depends_on','substitutes_for','competes_with','supplier_of'] as const
export const INDUSTRY_CLAIM_TYPES = ['fact','forecast','viewpoint','trend','risk','assumption','thesis','catalyst'] as const
export const INDUSTRY_MODEL_BOUNDS = { maxString:2000,maxAnalysis:6000,maxArray:32,maxEvidence:32,maxProposals:24,maxGaps:16,maxAlternatives:6,maxExistingKnowledge:80,maxEvidenceExcerpt:2400,maxPriorOutput:6000,maxDiagnostics:1200,maxDepth:3 } as const
export interface IndustryTargetInput { readonly name:string; readonly canonicalRef?:string; readonly aliases?:readonly string[]; readonly geography?:string; readonly asOf?:string }
export interface ResearchGap { readonly gapId:string; readonly module:IndustryResearchModule; readonly question:string; readonly reason:string; readonly actionable:boolean; readonly searchTerms?:readonly string[] }
export interface ResearchDesign { readonly definitionHypothesis:string; readonly targetKind:IndustryTargetKind; readonly scope:{readonly included:readonly string[];readonly excluded:readonly string[]}; readonly moduleQuestions:Readonly<Record<IndustryResearchModule,string>>; readonly keyMetrics:readonly string[]; readonly evidenceRequirements:readonly string[]; readonly searchTerms:readonly string[]; readonly knownGaps:readonly ResearchGap[]; readonly verificationCandidates:readonly {readonly name:string;readonly kind:'product'|'technology'|'industry'|'company';readonly reason:string}[] }
export interface ModuleEvidence { readonly evidenceId:string; readonly source:NormalizedResearchSource; readonly excerpt?:string }
export interface LocalReportMaterial { readonly markdown:string;readonly evidenceIds:readonly string[];readonly proposalIds:readonly string[];readonly relationProposalIds?:readonly string[];readonly reportOnly?:boolean }
export interface IndustryModuleResult { readonly module:IndustryResearchModule;readonly status:'supported'|'partial'|'unavailable';readonly analysis:string;readonly evidenceIds:readonly string[];readonly proposals:readonly SemanticProductionProposal[];readonly gaps:readonly ResearchGap[];readonly reportMaterial:LocalReportMaterial }
export interface CrossModuleSynthesis { readonly executiveView:string;readonly analysis:string;readonly evidenceIds:readonly string[];readonly proposals:readonly SemanticProductionProposal[];readonly gaps:readonly ResearchGap[];readonly alternativeViews:readonly string[];readonly reportMaterial:LocalReportMaterial }
export interface IndustryResearchSkillInput { readonly target:IndustryTargetInput;readonly designContext?:unknown;readonly evidence:readonly ModuleEvidence[];readonly existingKnowledge:readonly unknown[];readonly localReferences:readonly string[] }
export const ALL_INDUSTRY_OPERATION_NAMES = ['industry_research_design','industry_module_analysis','industry_cross_module_synthesis'] as const
export type IndustryOperationName = typeof ALL_INDUSTRY_OPERATION_NAMES[number]
const strings={type:'array',minItems:1,maxItems:INDUSTRY_MODEL_BOUNDS.maxArray,uniqueItems:true,items:{type:'string',minLength:1,maxLength:INDUSTRY_MODEL_BOUNDS.maxString}}
const gap={type:'object',required:['gapId','module','question','reason','actionable'],properties:{gapId:{type:'string',maxLength:120},module:{enum:[...INDUSTRY_MODULES]},question:{type:'string',maxLength:500},reason:{type:'string',maxLength:1000},actionable:{type:'boolean'},searchTerms:strings}}
const proposal={type:'object',required:['proposalId','kind','subjectKey'],properties:{proposalId:{type:'string',maxLength:120},kind:{enum:['entity','relation','claim']},subjectKey:{type:'string',maxLength:120},targetKey:{type:'string',maxLength:120},entityType:{enum:['industry','product','technology','company']},entityName:{type:'string',maxLength:300},relationType:{enum:[...INDUSTRY_RELATION_TYPES]},claimType:{enum:[...INDUSTRY_CLAIM_TYPES]},statement:{type:'string',maxLength:2000},sourceCandidateIds:{...strings,maxItems:INDUSTRY_MODEL_BOUNDS.maxEvidence},structuredValue:{type:'object',required:['metric','value','unit','comparator'],properties:{metric:{type:'string',maxLength:200},value:{},unit:{type:'string',maxLength:80},comparator:{type:'string',maxLength:40},period:{type:'string',maxLength:80},fiscalPeriod:{type:'string',maxLength:80},geography:{type:'string',maxLength:200},measurementDefinition:{type:'string',maxLength:500},sourceMethodology:{type:'string',maxLength:500}}}}}
const material={type:'object',required:['markdown','evidenceIds','proposalIds'],properties:{markdown:{type:'string',maxLength:6000},evidenceIds:{...strings,minItems:0},proposalIds:{...strings,minItems:0},relationProposalIds:{...strings,minItems:0},reportOnly:{type:'boolean'}}}
export const INDUSTRY_RESEARCH_DESIGN_CONTRACT={name:'IndustryResearchDesign',type:'object',required:['definitionHypothesis','targetKind','scope','moduleQuestions','keyMetrics','evidenceRequirements','searchTerms','knownGaps','verificationCandidates'],bounds:INDUSTRY_MODEL_BOUNDS,properties:{definitionHypothesis:{type:'string',maxLength:1200},targetKind:{enum:['industry','theme','product','technology','uncertain']},scope:{type:'object',required:['included','excluded'],properties:{included:strings,excluded:{...strings,minItems:0}}},moduleQuestions:{type:'object',required:[...INDUSTRY_MODULES]},keyMetrics:strings,evidenceRequirements:strings,searchTerms:strings,knownGaps:{type:'array',maxItems:16,items:gap},verificationCandidates:{type:'array',maxItems:16}}}
export const INDUSTRY_MODULE_RESULT_CONTRACT={name:'IndustryModuleResult',type:'object',required:['module','status','analysis','evidenceIds','proposals','gaps','reportMaterial'],bounds:INDUSTRY_MODEL_BOUNDS,properties:{module:{enum:[...INDUSTRY_MODULES]},status:{enum:['supported','partial','unavailable']},analysis:{type:'string',maxLength:INDUSTRY_MODEL_BOUNDS.maxAnalysis},evidenceIds:{...strings,minItems:0,maxItems:32},proposals:{type:'array',maxItems:24,items:proposal},gaps:{type:'array',maxItems:16,items:gap},reportMaterial:material},proposalRules:'Claim and Relation candidates require at least one supplied evidence ID; Entity candidates may be evidence-free.'}
export const INDUSTRY_SYNTHESIS_CONTRACT={name:'CrossModuleSynthesis',type:'object',required:['executiveView','analysis','evidenceIds','proposals','gaps','alternativeViews','reportMaterial'],bounds:INDUSTRY_MODEL_BOUNDS,properties:{executiveView:{type:'string',maxLength:3000},analysis:{type:'string',maxLength:INDUSTRY_MODEL_BOUNDS.maxAnalysis},evidenceIds:{...strings,minItems:0,maxItems:32},proposals:{type:'array',maxItems:24,items:proposal},gaps:{type:'array',maxItems:16},alternativeViews:{type:'array',maxItems:6},reportMaterial:material},allowlists:['supplied evidence IDs','existing module proposal IDs and relation proposal IDs'],proposalRules:'New IDs are local and non-canonical; no new external facts or canonical writes.'}
