import type { ReasoningExecutor, ReasoningOperation } from '../../plugins/reasoning/contracts.ts'
import type { SemanticProductionProposal } from '../../knowledge/production/contracts.ts'
import { INDUSTRY_MODULES, type CrossModuleSynthesis, type IndustryModuleResult, type IndustryResearchModule, type IndustryResearchSkillInput, type LocalReportMaterial, type ResearchDesign, type ResearchGap } from './contracts.ts'
type R = Record<string, unknown>
const obj = (v: unknown): v is R => typeof v === 'object' && v !== null && !Array.isArray(v)
const id = /^[A-Za-z][A-Za-z0-9._-]*$/, canon = /^(entity|relation|claim|source|raw|changeset|review-case):/i
const text = (v: unknown): v is string => typeof v === 'string' && v.trim() !== ''
const arr = (v: unknown): v is readonly unknown[] => Array.isArray(v)
const strs = (v: unknown): v is readonly string[] => arr(v) && v.every(text)
const uniq = (v: unknown): v is readonly string[] => strs(v) && new Set(v).size === v.length
const local = (v: unknown): v is string => typeof v === 'string' && id.test(v) && !canon.test(v)
const finite = (v: unknown) => typeof v === 'number' ? Number.isFinite(v) : typeof v === 'string' ? v.trim() !== '' : typeof v === 'boolean'

export function validateIndustryResearchDesign(v: unknown): ResearchDesign {
  if (!obj(v) || !text(v.definitionHypothesis) || !['industry','theme','product','technology','uncertain'].includes(String(v.targetKind))) throw new Error('Invalid Industry Research Design target diagnosis')
  if (!obj(v.scope) || !strs(v.scope.included) || !strs(v.scope.excluded)) throw new Error('Invalid Industry Research Design scope')
  if (!obj(v.moduleQuestions) || INDUSTRY_MODULES.some((m) => !text((v.moduleQuestions as R)[m]))) throw new Error('Research Design must contain all eight module questions')
  for (const k of ['keyMetrics','evidenceRequirements','searchTerms']) if (!uniq(v[k]) || v[k].length === 0) throw new Error(`Research Design ${k} must be a non-empty string array`)
  if (!arr(v.knownGaps)) throw new Error('Research Design knownGaps must be an array'); const gaps = new Set<string>(); for (const g of v.knownGaps) { if (!obj(g) || !local(g.gapId) || gaps.has(String(g.gapId)) || !INDUSTRY_MODULES.includes(g.module as IndustryResearchModule) || !text(g.question) || !text(g.reason) || typeof g.actionable !== 'boolean' || (g.searchTerms !== undefined && !uniq(g.searchTerms))) throw new Error('Invalid Research Design known gap'); gaps.add(String(g.gapId)) }
  if (!arr(v.verificationCandidates)) throw new Error('Research Design verificationCandidates must be an array'); for (const c of v.verificationCandidates) if (!obj(c) || !text(c.name) || !['product','technology','industry','company'].includes(String(c.kind)) || !text(c.reason)) throw new Error('Invalid verification candidate')
  return v as unknown as ResearchDesign
}
function proposal(v: unknown, evidence: Set<string>, seen: Set<string>): SemanticProductionProposal {
  if (!obj(v) || !local(v.proposalId) || seen.has(v.proposalId) || [v.proposalId,v.subjectKey,v.targetKey].some((x) => x !== undefined && canon.test(String(x)))) throw new Error('Proposal contains canonical-looking identifier or duplicate local ID')
  if (!['entity','relation','claim'].includes(String(v.kind)) || !local(v.subjectKey) || (v.targetKey !== undefined && !local(v.targetKey))) throw new Error('Unsupported or unsafe semantic proposal')
  if (v.kind === 'entity' && (!['industry','product','technology','company'].includes(String(v.entityType)) || !text(v.entityName))) throw new Error('Unsupported Entity proposal')
  if (v.kind === 'relation' && (!text(v.relationType) || !local(v.targetKey))) throw new Error('Invalid Relation proposal')
  if (v.kind === 'claim' && (!['fact','forecast','viewpoint','trend','risk','assumption','thesis','catalyst'].includes(String(v.claimType)) || !text(v.statement))) throw new Error('Invalid Claim proposal')
  if (v.sourceCandidateIds !== undefined && (!uniq(v.sourceCandidateIds) || v.sourceCandidateIds.some((x) => !evidence.has(x)))) throw new Error('Proposal references unknown evidence')
  for (const k of ['supportsProposalIds','dependsOnProposalIds','contradictsProposalIds'] as const) if (v[k] !== undefined && (!uniq(v[k]) || v[k].some((x) => !local(x)))) throw new Error('Proposal contains invalid local link')
  if (v.kind === 'claim' && v.structuredValue != null) { const x = v.structuredValue; if (!obj(x) || !text(x.metric) || !('value' in x) || !finite(x.value) || !text(x.unit) || !text(x.comparator) || (x.period !== undefined && !text(x.period)) || (x.fiscalPeriod !== undefined && !text(x.fiscalPeriod))) throw new Error('Malformed quantitative structured value') }
  seen.add(v.proposalId); return v as unknown as SemanticProductionProposal
}
function gaps(v: unknown, module?: IndustryResearchModule): ResearchGap[] { if (!arr(v)) throw new Error('gaps must be an array'); const seen = new Set<string>(); return v.map((g) => { if (!obj(g) || !local(g.gapId) || seen.has(String(g.gapId)) || (module !== undefined && g.module !== module) || !INDUSTRY_MODULES.includes(g.module as IndustryResearchModule) || !text(g.question) || !text(g.reason) || typeof g.actionable !== 'boolean' || (g.searchTerms !== undefined && !uniq(g.searchTerms))) throw new Error('Invalid Research Gap'); seen.add(String(g.gapId)); return g as unknown as ResearchGap }) }
function material(v: unknown, evidence: Set<string>, proposals: Set<string>, relations: Set<string>): LocalReportMaterial { if (!obj(v) || !text(v.markdown) || !uniq(v.evidenceIds) || v.evidenceIds.some((x) => !evidence.has(x)) || !uniq(v.proposalIds) || v.proposalIds.some((x) => !proposals.has(x)) || (v.relationProposalIds !== undefined && (!uniq(v.relationProposalIds) || v.relationProposalIds.some((x) => !relations.has(x))))) throw new Error('Invalid local report material'); return v as unknown as LocalReportMaterial }
function links(ps: readonly SemanticProductionProposal[], allowed: Set<string>) { for (const p of ps) for (const k of ['supportsProposalIds','dependsOnProposalIds','contradictsProposalIds'] as const) if ((p[k] ?? []).some((x) => x === p.proposalId || !allowed.has(x))) throw new Error('Proposal contains unresolved local link') }
export function validateIndustryModuleResult(v: unknown, module: IndustryResearchModule, supplied: readonly string[]): IndustryModuleResult { if (!obj(v) || v.module !== module || !['supported','partial','unavailable'].includes(String(v.status)) || !text(v.analysis) || !uniq(v.evidenceIds) || v.evidenceIds.some((x) => !supplied.includes(x)) || !arr(v.proposals)) throw new Error('Invalid bounded module result or evidence escape'); const ev = new Set(supplied), seen = new Set<string>(), ps = v.proposals.map((x) => proposal(x, ev, seen)); links(ps, seen); const ids = new Set(ps.map((x) => x.proposalId)), rs = new Set(ps.filter((x) => x.kind === 'relation').map((x) => x.proposalId)); return { module, status: v.status as IndustryModuleResult['status'], analysis: v.analysis, evidenceIds: v.evidenceIds as string[], proposals: ps, gaps: gaps(v.gaps, module), reportMaterial: material(v.reportMaterial, ev, ids, rs) } }
export function validateCrossModuleSynthesis(v: unknown, supplied: readonly string[], moduleIds: readonly string[]): CrossModuleSynthesis { if (!obj(v) || !text(v.executiveView) || !text(v.analysis) || !uniq(v.evidenceIds) || v.evidenceIds.some((x) => !supplied.includes(x)) || !arr(v.proposals)) throw new Error('Invalid cross-module synthesis evidence'); const ev = new Set(supplied), seen = new Set(moduleIds), ps = v.proposals.map((x) => proposal(x, ev, seen)); links(ps, seen); const rs = new Set(ps.filter((x) => x.kind === 'relation').map((x) => x.proposalId)); const all = new Set(seen); if (!uniq(v.alternativeViews)) throw new Error('Invalid alternative views'); return { executiveView: v.executiveView, analysis: v.analysis, evidenceIds: v.evidenceIds as string[], proposals: ps, gaps: gaps(v.gaps), alternativeViews: v.alternativeViews as string[], reportMaterial: material(v.reportMaterial, ev, all, new Set([...rs, ...moduleIds])) } }
export class IndustryResearchSkill { constructor(private readonly executor: ReasoningExecutor) {} private async call(operation: ReasoningOperation, input: unknown, contract: unknown, repair?: unknown) { return (await this.executor.execute({ operation, instruction: repair === undefined ? `Perform bounded ${operation} using only supplied evidence.` : `Repair invalid bounded ${operation}. Return only a corrected object. Validation error: ${String(repair)}`, input, outputContract: contract })).output } async design(input: { target: IndustryResearchSkillInput['target']; existingKnowledge: readonly unknown[] }) { try { return validateIndustryResearchDesign(await this.call('industry_research_design', input, 'ResearchDesign')) } catch (e) { return validateIndustryResearchDesign(await this.call('industry_research_design', input, 'ResearchDesign', e instanceof Error ? e.message : String(e))) } } async analyze(module: IndustryResearchModule, input: IndustryResearchSkillInput): Promise<IndustryModuleResult> { try { return validateIndustryModuleResult(await this.call('industry_module_analysis', { module, ...input }, 'IndustryModuleResult'), module, input.evidence.map((x) => x.evidenceId)) } catch (e) { try { return validateIndustryModuleResult(await this.call('industry_module_analysis', { module, ...input }, 'IndustryModuleResult', e instanceof Error ? e.message : String(e)), module, input.evidence.map((x) => x.evidenceId)) } catch (second) { return { module, status: 'unavailable', analysis: 'Module reasoning failed after one bounded repair attempt.', evidenceIds: [], proposals: [], gaps: [{ gapId: `${module}-failure`, module, question: 'What evidence is required?', reason: second instanceof Error ? second.message : String(second), actionable: true }], reportMaterial: { markdown: 'Module unavailable.', evidenceIds: [], proposalIds: [] } } } } } async synthesize(input: { modules: readonly IndustryModuleResult[]; evidence: readonly IndustryResearchSkillInput['evidence'][number][] }) { return validateCrossModuleSynthesis(await this.call('industry_cross_module_synthesis', input, 'CrossModuleSynthesis'), input.evidence.map((x) => x.evidenceId), input.modules.flatMap((m) => m.proposals.map((p) => p.proposalId))) } }
