import assert from 'node:assert/strict'
import { mkdtemp } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { test } from 'node:test'
import { runDailyIntelligence } from '../../workflows/daily-intelligence/workflow.ts'
import { FileDailySignalStore } from '../../plugins/daily-intelligence/signal-store.ts'
import type { ResearchAcquisitionPlugin } from '../../plugins/research-acquisition/contracts.ts'

const watchlist = { companies: [{ symbol: '600519', name: 'Moutai', exchange: 'SSE' }], themes: ['AI'], industries: ['technology'] }
const emptyProvider: ResearchAcquisitionPlugin = { name: 'empty-provider', async discover() { return [] }, async fetch() { throw new Error('not called') }, async normalize() { throw new Error('not called') } }
const fixtureProvider: ResearchAcquisitionPlugin = { name: 'fixture-provider', async discover() { return [{ candidateId: 'fixture-1', kind: 'news', tier: 2, title: 'Public company update', url: 'https://example.test/update', provider: 'fixture', publishedAt: '2026-09-08T00:00:00.000Z', metadata: { companySymbol: '600519' } }] }, async fetch(candidate) { return { candidate, retrievedAt: '2026-09-08T01:00:00.000Z', content: 'Publicly available update', contentHash: 'fixture-hash' } }, async normalize(source) { return { candidate: source.candidate, retrievedAt: source.retrievedAt, title: source.candidate.title, content: source.content, contentHash: source.contentHash!, canonicalUrl: source.candidate.url, publisher: 'fixture', rights: { accessScope: 'public', retentionAllowed: true, aiProcessingAllowed: true, derivativeKnowledgeAllowed: true, redistributionAllowed: false } } } }
async function input(root: string, providers: readonly ResearchAcquisitionPlugin[]) { return { workflowRunId: 'daily-fixture-run', briefType: 'morning' as const, tradeDate: '2026-09-08', watchlist, providers, signalStore: new FileDailySignalStore(join(root, 'signals.jsonl')), briefRoot: join(root, 'briefs'), reportRoot: join(root, 'reports'), now: () => '2026-09-08T02:00:00.000Z' } }
test('empty providers still complete with explicit unavailable sections', async () => { const root = await mkdtemp(join(tmpdir(), 'rhl-daily-empty-')); const result = await runDailyIntelligence(await input(root, [emptyProvider])); assert.equal(result.status, 'completed'); assert.equal(result.brief?.sections.length, 14); assert.ok(result.brief?.sections.every((section) => section.unavailable)); assert.equal(result.providerOutcomes[0]?.status, 'empty'); assert.equal(result.brief?.quality.claimCount, 0) })
test('fixture workflow keeps signal count bounded and report source coverage auditable', async () => { const root = await mkdtemp(join(tmpdir(), 'rhl-daily-fixture-')); const result = await runDailyIntelligence(await input(root, [fixtureProvider])); assert.equal(result.status, 'completed'); assert.equal(result.signals.length, 1); assert.equal(result.brief?.quality.claimCount, 0); assert.ok((result.brief?.quality.reportItemWithSourceRatio ?? 0) > 0); assert.equal(result.brief?.calendarConfidence, 'fallback'); const replay = await runDailyIntelligence(await input(root, [fixtureProvider])); assert.equal(replay.status, 'already_completed') })
