import assert from 'node:assert/strict'
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import test from 'node:test'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { createFreshKnowledgeBaseV04, readCanonicalV04Assets } from '../../knowledge/storage/index.ts'
import { KnowledgeBaseRegistry } from '../../knowledge/registry/registry.ts'
import { KnowledgeProductionGateway } from '../../knowledge/production/gateway.ts'
import { verifyRaw } from '../../knowledge/raw/raw-archive.ts'
import type { ReasoningExecutor, ReasoningRequest, ReasoningResult } from '../../plugins/reasoning/contracts.ts'
import type { NormalizedResearchSource, ResearchAcquisitionPlugin, ResearchFetchedSource, ResearchSourceCandidate } from '../../plugins/research-acquisition/contracts.ts'
import type { AkshareDataClient } from '../../plugins/research-acquisition/akshare.ts'
import { sha256 } from '../../plugins/research-acquisition/hash.ts'
import { computeEarningsMetrics, earningsPeriodSpec, normalizeAkshareFinancialData } from '../../skills/earnings-review/financials.ts'
import { EARNINGS_REVIEW_SECTIONS, type EarningsImpactAssessment, type EarningsReviewProposal } from '../../skills/earnings-review/contracts.ts'
import { filterEarningsReviewProposals, runEarningsReview, selectOfficialEarningsFilings, validateEarningsImpactAssessments } from '../../workflows/earnings-review/workflow.ts'
import { ResearchService } from '../../app/services/research-service.ts'
import { WorkflowService } from '../../app/services/workflow-service.ts'
import { createResearchHubTools } from '../../app/pi/tools.ts'
import type { KnowledgeService } from '../../app/services/knowledge-service.ts'
import type { KnowledgeGraphService } from '../../app/services/knowledge-graph-service.ts'
import type { ProductionService } from '../../app/services/production-service.ts'
import type { ReviewService } from '../../app/services/review-service.ts'

const NOW = '2026-09-08T23:59:59.000Z'
const PERIOD = earningsPeriodSpec(2026, 'H1')
const RIGHTS = { accessScope: 'public' as const, retentionAllowed: true, aiProcessingAllowed: true, derivativeKnowledgeAllowed: true, redistributionAllowed: false }

class FixtureExecutor implements ReasoningExecutor {
  readonly requests: ReasoningRequest[] = []
  constructor(private readonly output: unknown) {}
  capabilities() { return { maxContextTokens: 100_000, maxOutputTokens: 10_000, structuredOutputSupport: true, maxConcurrency: 2 } }
  async execute(request: ReasoningRequest): Promise<ReasoningResult> { this.requests.push(request); return { operation: request.operation, operationId: `fixture-${this.requests.length}`, output: this.output } }
}
class SequenceExecutor implements ReasoningExecutor {
  readonly requests: ReasoningRequest[] = []
  constructor(private readonly outputs: readonly unknown[]) {}
  capabilities() { return { maxContextTokens: 100_000, maxOutputTokens: 10_000, structuredOutputSupport: true, maxConcurrency: 2 } }
  async execute(request: ReasoningRequest): Promise<ReasoningResult> { this.requests.push(request); return { operation: request.operation, operationId: `sequence-${this.requests.length}`, output: this.outputs[Math.min(this.requests.length - 1, this.outputs.length - 1)] } }
}

function source(candidate: ResearchSourceCandidate, content = 'bounded official filing content', rawBytes?: Uint8Array): NormalizedResearchSource { return { candidate, retrievedAt: NOW, title: candidate.title, content, contentHash: sha256(content), ...(rawBytes === undefined ? {} : { rawBytes }), publisher: candidate.provider, rights: RIGHTS } }
function officialCandidate(id = 'official-2026-h1', title = '2026年半年度报告', publishedAt = '2026-08-30T00:00:00.000Z'): ResearchSourceCandidate { return { candidateId: id, kind: 'official_disclosure', tier: 1, title, provider: 'cninfo', publishedAt, metadata: { companySymbol: '600519' } } }
function fixturePlugin(candidates: readonly ResearchSourceCandidate[], content = 'Official filing: revenue increased and operating cash flow remained positive.'): ResearchAcquisitionPlugin {
  return { name: 'fixture-official-disclosure', discover: async () => candidates, fetch: async (candidate): Promise<ResearchFetchedSource> => ({ candidate, retrievedAt: NOW, content, contentHash: sha256(content), rawBytes: new TextEncoder().encode(`PDF:${content}`), mediaType: 'application/pdf' }), normalize: async (fetched) => source(fetched.candidate, fetched.content, fetched.rawBytes) }
}
function fixtureAkshare(rows: readonly Record<string, unknown>[]): AkshareDataClient { return { companyBasic: async () => { throw new Error('companyBasic must not be called') }, financialData: async () => rows, historicalMarketData: async () => { throw new Error('historicalMarketData must not be called') } } }
function defaultRows(): readonly Record<string, unknown>[] { return [{ 报告期: '2025-06-30', 营业收入: 90, 净利润: 9, 销售毛利率: 40, 经营活动产生的现金流量净额: 8, 基本每股收益: 0.8 }, { 报告期: '2026-06-30', 营业收入: 120, 净利润: 15, 销售毛利率: 45, 经营活动产生的现金流量净额: 20, 基本每股收益: 1.2 }, { 报告期: '2026-03-31', 营业收入: 50, 净利润: 5 }] }
async function fixture(options: { readonly official?: readonly ResearchSourceCandidate[]; readonly rows?: readonly Record<string, unknown>[]; readonly akshare?: boolean } = {}) {
  const root = await mkdtemp(join(tmpdir(), 'rhl-earnings-review-')); const reports = join(root, 'reports'); await createFreshKnowledgeBaseV04(root, { knowledgeBaseId: `kb-earnings-${Date.now()}`, now: NOW }); const registry = new KnowledgeBaseRegistry(); let handle = await registry.mount(root)
  const seed = source({ candidateId: 'seed-source', kind: 'official_disclosure', tier: 1, title: 'Seed coverage source', provider: 'cninfo', publishedAt: '2026-01-01T00:00:00.000Z', metadata: { companySymbol: '600519' } }, 'Seed coverage evidence')
  const seeded = await new KnowledgeProductionGateway(registry).submit({ handle, producerType: 'fixture_seed', producerRunId: `seed-${Date.now()}-${Math.random().toString(16).slice(2)}`, schemaProfile: { schemaVersion: '0.4', storageFormatVersion: '1', requiresRawProvenance: true }, entity: { localKey: 'company', entityType: 'company', name: '贵州茅台', aliases: ['600519'], semanticFields: { ticker: '600519', exchange: 'SH' } }, proposals: [{ proposalId: 'seed-assumption', kind: 'claim', claimType: 'assumption', subjectKey: 'company', statement: 'Premium spirits demand remains resilient.', sourceCandidateIds: ['seed-source'] }, { proposalId: 'seed-thesis', kind: 'claim', claimType: 'thesis', subjectKey: 'company', statement: 'The company can maintain long-term pricing power.', sourceCandidateIds: ['seed-source'] }], evidenceBindings: [{ localSourceId: 'seed-source', source: seed }], asOf: NOW, now: () => NOW })
  assert.equal(seeded.status, 'committed'); handle = await registry.mount(root)
  const candidates = options.official ?? [officialCandidate()]; const plugin = fixturePlugin(candidates); const akshare = options.akshare === false ? undefined : fixtureAkshare(options.rows ?? defaultRows())
  return { root, reports, handle, plugin, akshare, async remount() { handle = await registry.mount(root); return handle }, async close() { await rm(root, { recursive: true, force: true }) } }
}
function validOutput(sourceId: string, claimType: 'fact' | 'assumption' | 'thesis' = 'fact', extra: Record<string, unknown> = {}) {
  const disposition: EarningsImpactAssessment['disposition'] = claimType === 'assumption' ? 'changes_assumption' : claimType === 'thesis' ? 'affects_thesis' : 'new_fact'; const existingKnowledgeRefs = disposition === 'changes_assumption' ? ['claim:seed-assumption'] : disposition === 'affects_thesis' ? ['claim:seed-thesis'] : []
  const proposal = { proposalId: 'proposal-1', kind: 'claim' as const, claimType, subjectKey: 'company', statement: 'The requested earnings period contains a verified company result.', sourceCandidateIds: [sourceId], assessmentRefs: ['impact-1'], ...extra } as EarningsReviewProposal
  return { sections: EARNINGS_REVIEW_SECTIONS.map((title) => ({ title, markdown: title === 'Earnings Snapshot' ? 'Verified earnings evidence.' : `Bounded fixture section: ${title}.`, sourceCandidateIds: title === 'Earnings Snapshot' ? [sourceId] : [], assessmentRefs: title === 'Earnings Snapshot' ? ['impact-1'] : [] })), impactAssessments: [{ assessmentId: 'impact-1', disposition, existingKnowledgeRefs, sourceCandidateIds: [sourceId], rationale: 'Bounded fixture evidence supports this assessment.' }], proposals: [proposal] }
}
async function runFixture(f: Awaited<ReturnType<typeof fixture>>, executor: ReasoningExecutor | undefined, overrides: Partial<Parameters<typeof runEarningsReview>[0]> = {}) { return runEarningsReview({ workflowRunId: `earnings-${Date.now()}-${Math.random().toString(16).slice(2)}`, handle: f.handle, company: { symbol: '600519', name: '贵州茅台', exchange: 'SSE' }, fiscalYear: 2026, period: 'H1', reportRoot: f.reports, acquisitionPlugins: [f.plugin], akshare: f.akshare, reasoningExecutor: executor, now: () => NOW, ...overrides }) }

test('ER1 period mapping covers Q1/H1/Q3/FY', () => { assert.deepEqual([earningsPeriodSpec(2026, 'Q1').endDate, earningsPeriodSpec(2026, 'H1').endDate, earningsPeriodSpec(2026, 'Q3').endDate, earningsPeriodSpec(2026, 'FY').endDate], ['2026-03-31', '2026-06-30', '2026-09-30', '2026-12-31']); assert.deepEqual([earningsPeriodSpec(2026, 'Q1').key, earningsPeriodSpec(2026, 'H1').key, earningsPeriodSpec(2026, 'Q3').key, earningsPeriodSpec(2026, 'FY').key], ['2026-Q1', '2026-H1', '2026-Q3', '2026-FY']) })
test('ER2 exact-period official filing is selected', () => { const result = selectOfficialEarningsFilings([officialCandidate('wrong', '2025年年度报告'), officialCandidate('right', '2026年半年度报告')], PERIOD, NOW); assert.deepEqual(result.candidates.map((item) => item.candidateId), ['right']) })
test('ER3 future filings are excluded by asOf', () => { const result = selectOfficialEarningsFilings([officialCandidate('future', '2026年半年度报告', '2026-10-01T00:00:00.000Z')], PERIOD, NOW); assert.equal(result.candidates.length, 0); assert.equal(result.futureFilteredCount, 1) })
test('ER4 full, summary, and correction selection is deterministic', () => { const result = selectOfficialEarningsFilings([officialCandidate('summary', '2026年半年度报告摘要'), officialCandidate('correction', '2026年半年度报告更正公告'), officialCandidate('full', '2026年半年度报告')], PERIOD, NOW); assert.deepEqual(result.candidates.map((item) => item.candidateId), ['full', 'correction']) })
test('ER5 AKShare normalization locates requested row rather than first row', () => { const result = normalizeAkshareFinancialData([{ 报告期: '2025-06-30', 营业收入: 90 }, { 报告期: '2026-06-30', 营业收入: 120 }], PERIOD); assert.equal(result.current?.metrics.revenue?.value, 120) })
test('ER6 prior-year comparable period is selected', () => { const result = normalizeAkshareFinancialData(defaultRows(), PERIOD); assert.equal(result.priorYear?.period, '2025-H1'); assert.equal(result.priorYear?.metrics.revenue?.value, 90) })
test('ER7 derived earnings calculations are deterministic', () => { const result = computeEarningsMetrics(normalizeAkshareFinancialData(defaultRows(), PERIOD)); assert.equal(result.byMetric.revenue_yoy?.value, 33.33333333333333); assert.equal(result.byMetric.gross_margin_delta_bps?.value, 500); assert.equal(result.byMetric.operating_cash_flow_to_net_profit?.value, 20 / 15) })
test('ER8 divide-by-zero and missing values remain unavailable', () => { const result = computeEarningsMetrics(normalizeAkshareFinancialData([{ 报告期: '2026-06-30', 净利润: 0, 经营活动产生的现金流量净额: 2 }, { 报告期: '2025-06-30', 净利润: 0 }], PERIOD)); assert.equal(result.byMetric.operating_cash_flow_to_net_profit, undefined); assert.equal(result.byMetric.revenue_yoy, undefined); assert.ok(result.unavailable.includes('revenue_yoy')) })
test('ER9 missing Company coverage blocks before reasoning and Gateway', async () => { const root = await mkdtemp(join(tmpdir(), 'rhl-earnings-missing-')); const reports = join(root, 'reports'); await createFreshKnowledgeBaseV04(root, { knowledgeBaseId: 'kb-missing', now: NOW }); let called = 0; const plugin = fixturePlugin([]); const original = plugin.discover; const wrapped = { ...plugin, discover: async (...args: Parameters<typeof original>) => { called += 1; return original(...args) } }; const result = await runEarningsReview({ workflowRunId: 'er9', handle: await new KnowledgeBaseRegistry().mount(root), company: { symbol: '600519', exchange: 'SSE' }, fiscalYear: 2026, period: 'H1', reportRoot: reports, acquisitionPlugins: [wrapped], reasoningExecutor: new FixtureExecutor({}), now: () => NOW }); assert.equal(result.status, 'blocked'); assert.equal(result.blockedReason, 'COMPANY_COVERAGE_NOT_FOUND'); assert.equal(called, 0); await rm(root, { recursive: true, force: true }) })
test('ER10 ambiguous Company coverage blocks', async () => { const f = await fixture(); try { const registry = new KnowledgeBaseRegistry(); const assets = JSON.parse(await readFile(join(f.root, 'registry', 'assets.yaml'), 'utf8')) as Record<string, unknown>; assets['entity:duplicate-company'] = { type: 'entity', storageRef: 'entities/duplicate-company.yaml' }; await writeFile(join(f.root, 'registry', 'assets.yaml'), `${JSON.stringify(assets)}\n`); await writeFile(join(f.root, 'entities', 'duplicate-company.yaml'), `${JSON.stringify({ id: 'entity:duplicate-company', type: 'company', name: 'Duplicate', aliases: [], ticker: '600519', exchange: 'SH', lifecycle: { status: 'active' } })}\n`); const result = await runEarningsReview({ workflowRunId: 'er10', handle: await registry.mount(f.root), company: { symbol: '600519', exchange: 'SSE' }, fiscalYear: 2026, period: 'H1', reportRoot: f.reports, acquisitionPlugins: [f.plugin], akshare: f.akshare, reasoningExecutor: new FixtureExecutor({}), now: () => NOW }); assert.equal(result.status, 'blocked'); assert.equal(result.blockedReason, 'COMPANY_COVERAGE_AMBIGUOUS') } finally { await f.close() } })
test('ER11 impact refs outside covered Company are rejected', () => { const sources = [source(officialCandidate())]; const outcome = validateEarningsImpactAssessments([{ assessmentId: 'a', disposition: 'supports_existing', existingKnowledgeRefs: ['claim:other-company'], sourceCandidateIds: ['official-2026-h1'], rationale: 'x' }], [{ canonicalRef: 'claim:own', claimType: 'thesis' }], sources); assert.equal(outcome.valid.length, 0) })
test('ER12 forged canonical Claim refs are rejected', () => { const outcome = validateEarningsImpactAssessments([{ assessmentId: 'a', disposition: 'changes_assumption', existingKnowledgeRefs: ['claim:invented'], sourceCandidateIds: ['official-2026-h1'], rationale: 'x' }], [{ canonicalRef: 'claim:seed-assumption', claimType: 'assumption' }], [source(officialCandidate())]); assert.equal(outcome.valid.length, 0) })
test('ER13 unknown sourceCandidateId is rejected', async () => { const f = await fixture({ akshare: false }); try { const result = await runFixture(f, new FixtureExecutor(validOutput('unknown-source'))); assert.equal(result.status, 'completed'); assert.equal(result.telemetry.acceptedProposalCount, 0) } finally { await f.close() } })
test('ER14 proposal without assessmentRefs is rejected', () => { const claims = [{ canonicalRef: 'claim:seed-assumption', claimType: 'assumption' }]; const assessments = [{ assessmentId: 'a', disposition: 'new_fact' as const, existingKnowledgeRefs: [], sourceCandidateIds: ['official-2026-h1'], rationale: 'x' }]; const proposal = { ...validOutput('official-2026-h1').proposals[0]!, assessmentRefs: [] } as EarningsReviewProposal; assert.equal(filterEarningsReviewProposals([proposal], assessments, claims, [source(officialCandidate())], { metrics: [], byMetric: {}, unavailable: [] }).length, 0) })
test('ER15 proposal referencing only non-durable assessment is rejected', () => { const assessment = { assessmentId: 'a', disposition: 'no_change' as const, existingKnowledgeRefs: [], sourceCandidateIds: ['official-2026-h1'], rationale: 'x' }; const proposal = { ...validOutput('official-2026-h1').proposals[0]!, assessmentRefs: ['a'] } as EarningsReviewProposal; assert.equal(filterEarningsReviewProposals([proposal], [assessment], [], [source(officialCandidate())], { metrics: [], byMetric: {}, unavailable: [] }).length, 0) })
test('ER16 changes_assumption requires an assumption Claim', () => { const outcome = validateEarningsImpactAssessments([{ assessmentId: 'a', disposition: 'changes_assumption', existingKnowledgeRefs: ['claim:thesis'], sourceCandidateIds: ['official-2026-h1'], rationale: 'x' }], [{ canonicalRef: 'claim:thesis', claimType: 'thesis' }], [source(officialCandidate())]); assert.equal(outcome.valid.length, 1); assert.equal(outcome.durable.length, 0) })
test('ER17 affects_thesis requires a thesis Claim', () => { const outcome = validateEarningsImpactAssessments([{ assessmentId: 'a', disposition: 'affects_thesis', existingKnowledgeRefs: ['claim:assumption'], sourceCandidateIds: ['official-2026-h1'], rationale: 'x' }], [{ canonicalRef: 'claim:assumption', claimType: 'assumption' }], [source(officialCandidate())]); assert.equal(outcome.valid.length, 1); assert.equal(outcome.durable.length, 0) })
test('ER18 incompatible claimType is rejected', () => { const proposal = { ...validOutput('official-2026-h1').proposals[0]!, claimType: 'thesis' } as EarningsReviewProposal; const assessment = { assessmentId: 'impact-1', disposition: 'new_fact' as const, existingKnowledgeRefs: [], sourceCandidateIds: ['official-2026-h1'], rationale: 'x' }; assert.equal(filterEarningsReviewProposals([proposal], [assessment], [], [source(officialCandidate())], { metrics: [], byMetric: {}, unavailable: [] }).length, 0) })
test('ER19 invented numerical structuredValue is rejected', () => { const proposal = { ...validOutput('official-2026-h1').proposals[0]!, structuredValue: { metric: 'revenue', value: 999, unit: 'CNY', period: '2026-H1', comparator: 'observed' } } as EarningsReviewProposal; const assessment = { assessmentId: 'impact-1', disposition: 'new_fact' as const, existingKnowledgeRefs: [], sourceCandidateIds: ['official-2026-h1'], rationale: 'x' }; assert.equal(filterEarningsReviewProposals([proposal], [assessment], [], [source(officialCandidate())], { metrics: [], byMetric: {}, unavailable: [] }).length, 0) })
test('ER20 valid durable fact proposal passes', () => { const proposal = validOutput('official-2026-h1').proposals[0] as EarningsReviewProposal; const assessment = validOutput('official-2026-h1').impactAssessments[0]; assert.equal(filterEarningsReviewProposals([proposal], [assessment], [], [source(officialCandidate())], { metrics: [], byMetric: {}, unavailable: [] }).length, 1) })
test('ER21 valid assumption-change proposal passes', () => { const output = validOutput('official-2026-h1', 'assumption'); const claims = [{ canonicalRef: 'claim:seed-assumption', claimType: 'assumption' }]; const assessments = output.impactAssessments; assert.equal(filterEarningsReviewProposals([output.proposals[0] as EarningsReviewProposal], assessments, claims, [source(officialCandidate())], { metrics: [], byMetric: {}, unavailable: [] }).length, 1) })
test('ER22 acquired sources are narrowed to proposal-referenced evidence', async () => { const many = Array.from({ length: 20 }, (_, index) => officialCandidate(`unused-${index}`, 'Unrelated announcement')); const f = await fixture({ official: [...many, officialCandidate('selected', '2026年半年度报告')], akshare: false }); try { const result = await runFixture(f, new FixtureExecutor(validOutput('selected'))); const assets = await readCanonicalV04Assets(f.root); assert.equal(result.status, 'completed'); assert.equal(assets.objects.filter((item) => item.kind === 'source').length, 2) } finally { await f.close() } })
test('ER23 unused report evidence does not become canonical Source', async () => { const f = await fixture({ akshare: false }); try { const output = { sections: [{ title: 'Earnings Snapshot', markdown: 'Evidence.', sourceCandidateIds: ['official-2026-h1'], assessmentRefs: ['impact-1'] }], impactAssessments: [{ assessmentId: 'impact-1', disposition: 'no_change', existingKnowledgeRefs: [], sourceCandidateIds: ['official-2026-h1'], rationale: 'No durable change.' }], proposals: [] }; const result = await runFixture(f, new FixtureExecutor(output)); const assets = await readCanonicalV04Assets(f.root); assert.equal(result.status, 'completed'); assert.equal(assets.objects.filter((item) => item.kind === 'source').length, 1) } finally { await f.close() } })
test('ER24 official raw bytes are preserved while reasoning receives bounded excerpts', async () => { const f = await fixture({ akshare: false }); try { const longContent = 'x'.repeat(10_000); const executor = new FixtureExecutor(validOutput('official-2026-h1')); const result = await runFixture(f, executor, { acquisitionPlugins: [fixturePlugin([officialCandidate()], longContent)] }); const assets = await readCanonicalV04Assets(f.root); const official = assets.objects.find((item) => item.kind === 'source' && (item.value as { provider?: string; title?: string }).provider === 'cninfo' && (item.value as { title?: string }).title === '2026年半年度报告')!; const rawRef = (official.value as { rawRefs: readonly string[] }).rawRefs[0]!; const verified = await verifyRaw(f.handle, rawRef); const requestInput = executor.requests[0]?.input as { selectedOfficialFilingExcerpts?: readonly { content?: unknown }[] }; const excerpt = requestInput.selectedOfficialFilingExcerpts?.[0]?.content; const rawBytes = await readFile(verified.originalPath); assert.equal(result.status, 'completed'); assert.equal(verified.valid, true); assert.equal(rawBytes.byteLength, Buffer.byteLength(`PDF:${longContent}`)); assert.equal(typeof excerpt, 'string'); assert.ok(longContent.length > (excerpt as string).length); assert.ok((excerpt as string).length <= 1_500) } finally { await f.close() } })
test('ER25 earnings_review report has canonical Company subjectRef', async () => { const f = await fixture({ akshare: false }); try { const result = await runFixture(f, new FixtureExecutor(validOutput('official-2026-h1'))); const report = JSON.parse(await readFile(join(f.reports, `${result.report!.reportId}.md.json`), 'utf8')) as { reportType: string; subjectRefs: string[] }; assert.equal(report.reportType, 'earnings_review'); assert.equal(report.subjectRefs.length, 1); assert.match(report.subjectRefs[0]!, /^entity:/) } finally { await f.close() } })
test('ER26 report contains no synthetic canonical refs', async () => { const f = await fixture({ akshare: false }); try { const result = await runFixture(f, new FixtureExecutor(validOutput('official-2026-h1'))); const report = JSON.parse(await readFile(join(f.reports, `${result.report!.reportId}.md.json`), 'utf8')) as { sourceRefs: string[]; claimRefs: string[]; subjectRefs: string[] }; for (const ref of [...report.sourceRefs, ...report.claimRefs, ...report.subjectRefs]) assert.doesNotMatch(ref, /^(?:source|entity|claim):(?:official|600519|invented)/) } finally { await f.close() } })
test('ER27 report explicitly contains Consensus unavailable', async () => { const f = await fixture({ akshare: false }); try { const result = await runFixture(f, new FixtureExecutor(validOutput('official-2026-h1'))); const markdown = await readFile(join(f.reports, `${result.report!.reportId}.md`), 'utf8'); assert.match(markdown, /Consensus unavailable/) } finally { await f.close() } })
test('ER28 no-durable-change review produces zero fabricated Claims', async () => { const f = await fixture({ akshare: false }); try { const result = await runFixture(f, new FixtureExecutor({ sections: [], impactAssessments: [{ assessmentId: 'impact-1', disposition: 'no_change', existingKnowledgeRefs: [], sourceCandidateIds: ['official-2026-h1'], rationale: 'Results confirm existing research.' }], proposals: [] })); assert.equal(result.status, 'completed'); assert.equal(result.claimIds.length, 0); assert.equal(result.telemetry.durableAssessmentCount, 0) } finally { await f.close() } })
test('ER29 invalid Pi output safely falls back with zero unauthorized proposals', async () => { const f = await fixture({ akshare: false }); try { const result = await runFixture(f, new FixtureExecutor({ impactAssessments: [{ assessmentId: 'bad', disposition: 'new_fact', existingKnowledgeRefs: [], sourceCandidateIds: ['forged'], rationale: '' }], proposals: [] })); assert.equal(result.status, 'completed'); assert.equal(result.telemetry.reasoning.fallbackUsed, true); assert.equal(result.telemetry.reasoning.repairAttempts, 1); assert.match(result.telemetry.reasoning.diagnostic ?? '', /assessment_0_/); assert.equal(result.telemetry.acceptedProposalCount, 0) } finally { await f.close() } })
test('ER30 valid structured Pi output is marked applied', async () => { const f = await fixture(); try { const output = validOutput('official-2026-h1', 'fact', { structuredValue: { metric: 'revenue', value: 120, unit: 'CNY', period: '2026-H1', comparator: 'eq' } }); const result = await runFixture(f, new FixtureExecutor(output)); assert.equal(result.status, 'completed'); assert.equal(result.telemetry.reasoning.validated, true); assert.equal(result.telemetry.reasoning.applied, true); assert.equal(result.telemetry.acceptedProposalCount, 1) } finally { await f.close() } })
test('ER31 replay does not create duplicate canonical identities', async () => { const f = await fixture(); try { const output = validOutput('official-2026-h1'); const first = await runEarningsReview({ workflowRunId: 'er31-replay', handle: f.handle, company: { symbol: '600519', exchange: 'SSE' }, fiscalYear: 2026, period: 'H1', reportRoot: f.reports, acquisitionPlugins: [f.plugin], akshare: f.akshare, reasoningExecutor: new FixtureExecutor(output), now: () => NOW }); await f.remount(); const second = await runEarningsReview({ workflowRunId: 'er31-replay', handle: f.handle, company: { symbol: '600519', exchange: 'SSE' }, fiscalYear: 2026, period: 'H1', reportRoot: f.reports, acquisitionPlugins: [f.plugin], akshare: f.akshare, reasoningExecutor: new FixtureExecutor(output), now: () => NOW }); const assets = await readCanonicalV04Assets(f.root); assert.equal(first.status, 'completed'); assert.equal(second.status, 'completed'); assert.equal(assets.objects.filter((item) => item.kind === 'entity').length, 1); assert.equal(assets.objects.filter((item) => item.kind === 'source').length, 2); assert.equal(assets.objects.filter((item) => item.kind === 'claim').length, 3) } finally { await f.close() } })
test('ER32 ResearchService registers workflowType earnings_review', async () => { const f = await fixture({ akshare: false }); try { const workflows = new WorkflowService(); const service = new ResearchService({ mountedKnowledgeBaseRoot: f.root, reportRoot: f.reports, acquisitionPlugins: [f.plugin], workflowService: workflows }); const started = service.startEarningsReview({ workflowRunId: 'er32-service', symbol: '600519', exchange: 'SSE', fiscalYear: 2026, period: 'H1' }); assert.equal(workflows.getWorkflowStatus(started.runId)?.workflowType, 'earnings_review'); assert.equal((await started.completion).status, 'completed') } finally { await f.close() } })
test('ER33 Pi tool routes review_earnings to startEarningsReview with exact input', async () => {
  const received: Record<string, unknown>[] = []
  const researchService = {
    startEarningsReview: (input: Record<string, unknown>) => {
      received.push(input)
      return { runId: input.workflowRunId, completion: Promise.resolve({ status: 'completed', runId: input.workflowRunId, knowledgeBaseId: 'kb-tool', committedIds: [], proposalCount: 1, summary: 'fixture', telemetry: {} }) }
    },
  } as unknown as ResearchService
  const context = { knowledgeService: {} as KnowledgeService, productionService: {} as ProductionService, reviewService: {} as ReviewService, workflowService: new WorkflowService(), researchService, knowledgeGraphService: {} as KnowledgeGraphService }
  const tool = createResearchHubTools(context).find((item) => item.name === 'review_earnings')!
  const result = await tool.execute('er33-tool-call', { workflowRunId: 'er33-routing', symbol: '600519', exchange: 'SSE', fiscalYear: 2026, period: 'H1', asOf: NOW }, undefined, undefined, {} as never)
  const first = result.content[0]
  assert.equal(first?.type, 'text')
  if (first?.type !== 'text') throw new Error('Pi tool did not return text')
  assert.equal((JSON.parse(first.text) as { summary: string }).summary, 'fixture')
  assert.deepEqual(received, [{ workflowRunId: 'er33-routing', symbol: '600519', exchange: 'SSE', fiscalYear: 2026, period: 'H1', asOf: NOW }])
})
test('ER34 HTTP product route is part of the runtime route contract', async () => { const text = await readFile(join(process.cwd(), 'app/runtime/server.ts'), 'utf8'); assert.match(text, /\/api\/production\/review-earnings/); assert.match(text, /\/api\/review-earnings/) })
test('ER35 cancellation is respected before acquisition', async () => { const f = await fixture({ akshare: false }); try { const controller = new AbortController(); controller.abort(); const result = await runFixture(f, new FixtureExecutor({}), { signal: controller.signal }); assert.equal(result.status, 'cancelled') } finally { await f.close() } })
test('ER36 repair request carries prior output, safe diagnostics, and explicit allowed sets', async () => { const f = await fixture({ akshare: false }); try { const invalid = { sections: [], impactAssessments: [{ assessmentId: 'bad', disposition: 'new_fact', existingKnowledgeRefs: [], sourceCandidateIds: ['forged'], rationale: '' }], proposals: [] }; const executor = new SequenceExecutor([invalid, validOutput('official-2026-h1')]); const result = await runFixture(f, executor); const repair = executor.requests[1]?.input as { repair?: { priorInvalidStructuredOutput?: unknown; validatorDiagnostics?: readonly string[]; allowedDispositionValues?: readonly string[] }; allowedSourceCandidateIds?: readonly string[]; allowedExistingClaimRefs?: readonly string[] }; assert.equal(result.telemetry.reasoning.validated, true); assert.equal(result.telemetry.reasoning.repairAttempts, 1); assert.ok(repair.repair?.priorInvalidStructuredOutput); assert.ok(repair.repair?.validatorDiagnostics?.some((item) => item.startsWith('assessment_0_'))); assert.ok(repair.repair?.allowedDispositionValues?.includes('new_fact')); assert.ok(repair.allowedSourceCandidateIds?.includes('official-2026-h1')); assert.ok((repair.allowedExistingClaimRefs?.length ?? 0) > 0); assert.equal(JSON.stringify(repair).includes('stack'), false) } finally { await f.close() } })
test('ER37 section claimRefs map assessmentId through accepted proposalId to Gateway Claim ref', async () => { const f = await fixture({ akshare: false }); try { const output = validOutput('official-2026-h1'); const result = await runFixture(f, new FixtureExecutor({ ...output, proposals: [{ ...output.proposals[0], proposalId: 'proposal-xyz', assessmentRefs: ['impact-1'] }] })); const report = JSON.parse(await readFile(join(f.reports, `${result.report!.reportId}.md.json`), 'utf8')) as { sections: readonly { title: string; claimRefs?: readonly string[] }[]; claimRefs: readonly string[] }; const section = report.sections.find((item) => item.title === 'Earnings Snapshot')!; assert.equal(result.status, 'completed'); assert.deepEqual(section.claimRefs, report.claimRefs); assert.match(section.claimRefs?.[0] ?? '', /^claim:/) } finally { await f.close() } })
