import assert from 'node:assert/strict'
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import test from 'node:test'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { createFreshKnowledgeBaseV04, readCanonicalV04Assets } from '../../knowledge/storage/index.ts'
import { KnowledgeBaseRegistry } from '../../knowledge/registry/registry.ts'
import { KnowledgeProductionGateway } from '../../knowledge/production/gateway.ts'
import type { ReasoningExecutor, ReasoningRequest, ReasoningResult } from '../../plugins/reasoning/contracts.ts'
import type { DailyResearchSignal } from '../../plugins/daily-intelligence/contracts.ts'
import type { NormalizedResearchSource, ResearchAcquisitionPlugin, ResearchFetchedSource, ResearchSourceCandidate } from '../../plugins/research-acquisition/contracts.ts'
import { FileDailySignalStore } from '../../plugins/daily-intelligence/signal-store.ts'
import { sha256 } from '../../plugins/research-acquisition/hash.ts'
import { EVENT_RESEARCH_SECTIONS, type EventEvidenceAssessmentOutput } from '../../skills/event-research/contracts.ts'
import { eventResearchSectionId } from '../../skills/event-research/skill.ts'
import { EVENT_RESEARCH_REPORT_CONTRACT_NOTE, mapEventGatewayOutcomeStatus, runEventResearch, type EventResearchWorkflowInput } from '../../workflows/event-research/index.ts'

const NOW = '2026-09-09T00:00:00.000Z'
const RIGHTS = { accessScope: 'public' as const, retentionAllowed: true, aiProcessingAllowed: true, derivativeKnowledgeAllowed: true, redistributionAllowed: false }
type Dict = Record<string, unknown>
function isEventOccurrence(value: Dict): boolean { const structured = value.structuredValue; return Boolean(structured && typeof structured === 'object' && (structured as Dict).metric && String((structured as Dict).metric).startsWith('event_occurrence_')) }

class SequenceExecutor implements ReasoningExecutor {
  readonly requests: ReasoningRequest[] = []
  private index = 0
  constructor(private readonly outputs: readonly unknown[]) {}
  capabilities() { return { maxContextTokens: 100_000, maxOutputTokens: 10_000, structuredOutputSupport: true, maxConcurrency: 2 } }
  async execute(request: ReasoningRequest): Promise<ReasoningResult> { this.requests.push(request); return { operation: request.operation, output: this.outputs[Math.min(this.index++, this.outputs.length - 1)] } }
}

function source(candidate: ResearchSourceCandidate, content = 'Bounded event evidence.'): NormalizedResearchSource { return { candidate, retrievedAt: NOW, title: candidate.title, content, contentHash: sha256(content), canonicalUrl: candidate.url, publisher: candidate.provider, rights: RIGHTS } }
function candidate(id: string, provider: 'cninfo' | 'gdelt', publishedAt = '2026-09-08T02:00:00.000Z', suffix = id): ResearchSourceCandidate { return { candidateId: id, kind: provider === 'cninfo' ? 'official_disclosure' : 'news', tier: provider === 'cninfo' ? 1 : 3, title: `${provider} event ${suffix}`, url: `https://example.test/${provider}/${id}`, provider, publishedAt, metadata: { companySymbol: '600519' } } }
function plugin(name: string, candidates: readonly ResearchSourceCandidate[], contents = new Map<string, string>()): ResearchAcquisitionPlugin { return { name, async discover() { return candidates }, async fetch(item): Promise<ResearchFetchedSource> { const content = contents.get(item.candidateId) ?? `Evidence ${item.candidateId}`; return { candidate: item, retrievedAt: NOW, content, contentHash: sha256(content), rawBytes: new TextEncoder().encode(content) } }, async normalize(fetched) { return source(fetched.candidate, fetched.content) } } }
function validAssessment(sourceIds: readonly string[] = ['cninfo-1']): EventEvidenceAssessmentOutput { return { sourceAssessments: sourceIds.map((sourceCandidateId, index) => ({ sourceCandidateId, verdict: 'supports' as const, confidence: 0.9 - index / 10, rationale: 'The bounded source supports the selected event.', evidenceRequirement: index === 0 ? 'primary' as const : 'corroborated' as const })), verifiedFacts: [{ factId: 'event-fact', statement: 'The selected event occurred.', sourceCandidateIds: [...sourceIds], confidence: 0.9, evidenceRequirement: sourceIds.length > 1 ? 'corroborated' : 'primary' }], contradictions: [] } }
function validSynthesis(sourceIds: readonly string[] = ['cninfo-1']): Dict { return { sections: EVENT_RESEARCH_SECTIONS.map((title) => ({ sectionId: eventResearchSectionId(title), title, markdown: `Bounded event research for ${title}.`, sourceCandidateIds: title === 'Evidence Verification' ? [...sourceIds] : [], existingKnowledgeRefs: [], assessmentRefs: ['impact-1'] })), assessments: [{ assessmentId: 'impact-1', disposition: 'new_risk', existingKnowledgeRefs: [], sourceCandidateIds: [...sourceIds], rationale: 'The verified event creates a bounded monitoring risk.', directImpact: 'Direct impact is bounded to the company.', secondOrderImpact: 'Second-order effects require monitoring.' }], proposals: [{ proposalId: 'risk-1', kind: 'claim', claimType: 'risk', subjectKey: 'company', statement: 'The event creates a new company-specific monitoring risk.', sourceCandidateIds: [...sourceIds], existingKnowledgeRefs: [], assessmentRefs: ['impact-1'] }] } }
function signal(signalId = 'signal-event-1'): DailyResearchSignal { return { signalId, kind: 'announcement', category: 'announcement', provider: 'fixture', source: candidate('signal-source', 'cninfo'), publishedAt: '2026-09-08T01:00:00.000Z', discoveredAt: '2026-09-08T01:10:00.000Z', entities: ['600519'], themes: [], title: 'Fixture event signal', contentHash: 'signal-content', relevance: 1, novelty: 1, importance: 1, sourceTier: 1, excerpt: 'A bounded event signal.' } }

async function fixture() {
  const root = await mkdtemp(join(tmpdir(), 'rhl-event-research-')); await createFreshKnowledgeBaseV04(root, { knowledgeBaseId: `kb-event-${Date.now()}`, now: NOW }); const registry = new KnowledgeBaseRegistry(); let handle = await registry.mount(root); const seed = source({ candidateId: 'seed-source', kind: 'official_disclosure', tier: 1, title: 'Seed Company coverage', provider: 'cninfo', url: 'https://example.test/seed', publishedAt: '2026-01-01T00:00:00.000Z', metadata: { companySymbol: '600519' } }, 'Seed coverage for the existing Company.')
  const seeded = await new KnowledgeProductionGateway(registry).submit({ handle, producerType: 'fixture_seed', producerRunId: `seed-${Date.now()}-${Math.random().toString(16).slice(2)}`, schemaProfile: { schemaVersion: '0.4', storageFormatVersion: '1', requiresRawProvenance: true }, entity: { localKey: 'company', entityType: 'company', name: 'Fixture Company', aliases: ['600519'], semanticFields: { ticker: '600519', exchange: 'SSE' } }, proposals: [{ proposalId: 'seed-thesis', kind: 'claim', claimType: 'thesis', subjectKey: 'company', statement: 'The company has durable operating strength.', sourceCandidateIds: ['seed-source'] }], evidenceBindings: [{ localSourceId: 'seed-source', source: seed }], asOf: NOW, now: () => NOW }); assert.equal(seeded.status, 'committed'); handle = await registry.mount(root)
  const signalStore = new FileDailySignalStore(join(root, 'signals.jsonl')); await signalStore.appendMany([signal()]); const reports = join(root, 'reports'); const close = async () => rm(root, { recursive: true, force: true }); const input = (overrides: Partial<EventResearchWorkflowInput> = {}): EventResearchWorkflowInput => ({ workflowRunId: 'event-run-1', handle, company: { symbol: '600519', name: 'Fixture Company', exchange: 'SSE' }, anchor: { kind: 'daily_signal', signalId: 'signal-event-1' }, acquisitionPlugins: [plugin('official-cninfo', [candidate('cninfo-1', 'cninfo')]), plugin('gdelt-news', [candidate('gdelt-1', 'gdelt', '2026-09-08T03:00:00.000Z')])], signalStore: signalStore as never, reportRoot: reports, now: () => NOW, ...overrides }); return { root, registry, get handle() { return handle }, signalStore, input, close }
}

test('E1-E4 exact existing Company coverage blocks providers and reasoning', async () => { const f = await fixture(); try { let discovered = 0; const p = plugin('official-cninfo', [], new Map()); const wrapped = { ...p, discover: async () => { discovered++; return [] } }; const result = await runEventResearch(f.input({ company: { symbol: '000858', name: 'Missing Company', exchange: 'SZSE' }, acquisitionPlugins: [wrapped] })); assert.equal(result.status, 'blocked'); assert.equal(result.blockedReason, 'COMPANY_COVERAGE_NOT_FOUND'); assert.equal(discovered, 0) } finally { await f.close() } })

test('E5 ambiguous canonical Company coverage blocks', async () => { const f = await fixture(); try { const registryAssets = JSON.parse(await readFile(join(f.root, 'registry', 'assets.yaml'), 'utf8')) as Dict; registryAssets['entity:duplicate-company'] = { type: 'entity', storageRef: 'entities/duplicate-company.yaml' }; await writeFile(join(f.root, 'registry', 'assets.yaml'), `${JSON.stringify(registryAssets)}\n`); await writeFile(join(f.root, 'entities', 'duplicate-company.yaml'), `${JSON.stringify({ id: 'entity:duplicate-company', type: 'company', name: 'Duplicate', aliases: [], ticker: '600519', exchange: 'SH', lifecycle: { status: 'active' } })}\n`); const result = await runEventResearch(f.input()); assert.equal(result.status, 'blocked'); assert.equal(result.blockedReason, 'COMPANY_COVERAGE_AMBIGUOUS') } finally { await f.close() } })

test('E6-E8 Daily Signal is exact, company-bound, and missing signals block', async () => { const f = await fixture(); try { const missing = await runEventResearch(f.input({ anchor: { kind: 'daily_signal', signalId: 'signal-missing' } })); assert.equal(missing.blockedReason, 'EVENT_SIGNAL_NOT_FOUND'); const mismatch = await runEventResearch(f.input({ anchor: { kind: 'daily_signal', signalId: 'signal-event-1' }, company: { symbol: '000858', exchange: 'SZSE' } })); assert.equal(mismatch.blockedReason, 'COMPANY_COVERAGE_NOT_FOUND'); const noStore = await runEventResearch(f.input({ signalStore: undefined, dailySignalStore: undefined })); assert.equal(noStore.blockedReason, 'EVENT_SIGNAL_NOT_FOUND') } finally { await f.close() } })

test('E9-E14 bounded dates reject future and impossible calendar inputs and derive a stable fingerprint/date', async () => { const f = await fixture(); try { const future = await runEventResearch(f.input({ asOf: '2026-09-10T00:00:00.000Z' })); assert.equal(future.blockedReason, 'EVENT_ASOF_IN_FUTURE'); const invalid = await runEventResearch(f.input({ anchor: { kind: 'user_event', title: 'x', description: 'x', eventDate: 'not-a-date' } })); assert.equal(invalid.blockedReason, 'EVENT_DATE_INVALID'); const impossible = await runEventResearch(f.input({ anchor: { kind: 'user_event', title: 'x', description: 'x', eventDate: '2026-02-30' } })); assert.equal(impossible.blockedReason, 'EVENT_DATE_INVALID'); const impossibleAsOf = await runEventResearch(f.input({ asOf: '2026-02-30T00:00:00.000Z' })); assert.equal(impossibleAsOf.errors[0], 'EVENT_DATE_INVALID'); const first = await runEventResearch(f.input({ reasoningExecutor: undefined })); const second = await runEventResearch(f.input({ workflowRunId: 'event-run-2', reasoningExecutor: undefined })); assert.equal(first.status, 'completed'); assert.equal(first.telemetry.eventFingerprint, second.telemetry.eventFingerprint); assert.equal(first.telemetry.eventDate, '2026-09-08') } finally { await f.close() } })

test('E15-E25 only targeted CNINFO/GDELT are called with six-per-provider and twelve-global bounds', async () => { const f = await fixture(); try { const calls: Dict[] = []; const cn = Array.from({ length: 8 }, (_, i) => candidate(`cn-${i}`, 'cninfo', '2026-09-08T02:00:00.000Z', String(i))); const gd = Array.from({ length: 8 }, (_, i) => candidate(`gd-${i}`, 'gdelt', '2026-09-08T03:00:00.000Z', String(i))); const other: ResearchAcquisitionPlugin = { ...plugin('rss-other', [candidate('other', 'gdelt')]), async discover(request) { calls.push({ provider: 'other', limit: request.limitPerKind }); return [] } }; const cnPlugin = { ...plugin('cninfo-official', cn), discover: async (request: Parameters<ResearchAcquisitionPlugin['discover']>[0]) => { calls.push({ provider: 'cninfo', limit: request.limitPerKind }); return cn } }; const gdPlugin = { ...plugin('gdelt-news', gd), discover: async (request: Parameters<ResearchAcquisitionPlugin['discover']>[0]) => { calls.push({ provider: 'gdelt', limit: request.limitPerKind }); return gd } }; const result = await runEventResearch(f.input({ acquisitionPlugins: [other, cnPlugin, gdPlugin], reasoningExecutor: undefined })); assert.equal(result.status, 'completed'); assert.deepEqual(calls, [{ provider: 'cninfo', limit: 6 }, { provider: 'gdelt', limit: 6 }]); assert.ok(result.telemetry.selectedCount <= 12); assert.ok(result.acquiredSources.length <= 12) } finally { await f.close() } })

test('E26-E33 future/out-of-window/URL/content duplicates are filtered before reasoning', async () => { const f = await fixture(); try { const duplicateUrl = { ...candidate('cn-duplicate', 'cninfo'), candidateId: 'cn-duplicate', url: 'https://example.test/same' }; const duplicateContent = { ...candidate('gd-duplicate', 'gdelt'), candidateId: 'gd-duplicate', url: 'https://example.test/other' }; const future = candidate('cn-future', 'cninfo', '2026-09-10T00:00:00.000Z'); const old = candidate('gd-old', 'gdelt', '2026-08-01T00:00:00.000Z'); const contents = new Map([['cn-duplicate', 'same content'], ['gd-duplicate', 'same content']]); const result = await runEventResearch(f.input({ acquisitionPlugins: [plugin('cninfo-official', [duplicateUrl, future], contents), plugin('gdelt-news', [duplicateContent, old], contents)], reasoningExecutor: undefined })); assert.equal(result.status, 'completed'); assert.equal(result.telemetry.futureFilteredCount, 1); assert.equal(result.telemetry.outsideWindowFilteredCount, 1); assert.equal(result.telemetry.deduplicatedCount, 1); assert.equal(result.acquiredSources.length, 1) } finally { await f.close() } })

test('E33a provider transport/fetch success is independent from usable normalized evidence', async () => { const f = await fixture(); try { const cn = plugin('official-cninfo', [candidate('cn-empty', 'cninfo')]); const emptyPayload = { ...cn, fetch: async (item: ResearchSourceCandidate): Promise<ResearchFetchedSource> => ({ candidate: item, retrievedAt: NOW, content: '', contentHash: sha256(''), rawBytes: new TextEncoder().encode('') }) }; const result = await runEventResearch(f.input({ acquisitionPlugins: [emptyPayload, plugin('gdelt-news', [])], reasoningExecutor: undefined })); const cnOutcome = result.providerOutcomes.find((item) => item.provider === 'cninfo'); assert.equal(result.status, 'completed'); assert.equal(cnOutcome?.providerSucceeded, true); assert.equal(cnOutcome?.transportSucceeded, true); assert.equal(cnOutcome?.fetchSucceeded, true); assert.equal(cnOutcome?.usableSourceCount, 0); assert.equal(result.telemetry.providerTransportSucceeded.cninfo, true); assert.equal(result.telemetry.providerFetchSucceeded.cninfo, true) } finally { await f.close() } })

test('E34-E41 company-only projection is bounded and Stage A receives bounded evidence', async () => { const f = await fixture(); try { const executor = new SequenceExecutor([validAssessment(['cninfo-1', 'gdelt-1']), validSynthesis(['cninfo-1'])]); const result = await runEventResearch(f.input({ reasoningExecutor: executor })); assert.equal(result.status, 'completed'); assert.ok(result.existingKnowledge.every((claim) => (claim.subjectRefs as string[]).includes('entity:company-600519'))); const request = executor.requests[0]?.input as Dict; const sources = request.sources as readonly Dict[]; assert.ok(sources.every((item) => String(item.excerpt).length <= 1_500)); assert.ok(result.existingKnowledge.length <= 60) } finally { await f.close() } })

test('E42-E52 strong verification creates one deterministic event occurrence and narrows evidence to proposals', async () => { const f = await fixture(); try { const executor = new SequenceExecutor([validAssessment(['cninfo-1', 'gdelt-1']), validSynthesis(['cninfo-1'])]); const result = await runEventResearch(f.input({ reasoningExecutor: executor })); assert.equal(result.status, 'completed'); assert.equal(result.verification?.verificationLevel, 'official_verified'); assert.equal(result.telemetry.eventOccurrenceProposalCount, 1); assert.equal(result.report?.sections.length, 16); const assets = await readCanonicalV04Assets(f.root); const eventClaims = assets.objects.filter((item) => item.kind === 'claim' && isEventOccurrence(item.value as unknown as Dict)); assert.equal(eventClaims.length, 1); assert.equal(result.sourceIds.length, 2); assert.equal(result.claimIds.length, 2); assert.ok(result.report?.sourceRefs.every((ref) => ref.startsWith('source:'))); assert.equal(result.telemetry.reportPersistence, 'deferred_report_contract') } finally { await f.close() } })

test('E42a event occurrence requires a verified fact supported by deterministic supporting sources', async () => { const f = await fixture(); try { const assessment = validAssessment(['cninfo-1']); const unsupportedFact = { ...assessment, verifiedFacts: [{ ...assessment.verifiedFacts[0]!, sourceCandidateIds: ['gdelt-1'] }] }; const executor = new SequenceExecutor([unsupportedFact, validSynthesis(['cninfo-1'])]); const result = await runEventResearch(f.input({ reasoningExecutor: executor })); assert.equal(result.status, 'completed'); assert.equal(result.telemetry.eventOccurrenceProposalCount, 0); const assets = await readCanonicalV04Assets(f.root); assert.equal(assets.objects.filter((item) => item.kind === 'claim' && isEventOccurrence(item.value as unknown as Dict)).length, 0) } finally { await f.close() } })

test('E42b Stage B receives exact bounded supporting and contradicting excerpts and allowlists', async () => { const f = await fixture(); try { const assessment = { ...validAssessment(['cninfo-1', 'gdelt-1']), sourceAssessments: [{ ...validAssessment(['cninfo-1']).sourceAssessments[0]!, sourceCandidateId: 'cninfo-1', verdict: 'supports' as const }, { ...validAssessment(['gdelt-1']).sourceAssessments[0]!, sourceCandidateId: 'gdelt-1', verdict: 'contradicts' as const }] }; const executor = new SequenceExecutor([assessment, validSynthesis(['cninfo-1'])]); const result = await runEventResearch(f.input({ reasoningExecutor: executor })); assert.equal(result.status, 'completed'); const request = executor.requests.find((item) => item.operation === 'event_research_synthesis'); assert.ok(request); const requestInput = request.input as Dict; const supporting = requestInput.supportingSourceExcerpts as readonly Dict[]; const contradicting = requestInput.contradictingSourceExcerpts as readonly Dict[]; assert.deepEqual(supporting.map((item) => item.candidateId), ['cninfo-1']); assert.deepEqual(contradicting.map((item) => item.candidateId), ['gdelt-1']); assert.deepEqual(requestInput.allowedSupportingSourceCandidateIds, ['cninfo-1']); assert.deepEqual(requestInput.allowedContradictingSourceCandidateIds, ['gdelt-1']); assert.ok(supporting.every((item) => String(item.excerpt).length <= 1_500)); assert.ok(contradicting.every((item) => String(item.excerpt).length <= 1_500)); assert.equal('content' in (supporting[0] ?? {}), false) } finally { await f.close() } })

test('E42c Gateway failed and blocked outcomes preserve distinct workflow status', () => { assert.equal(mapEventGatewayOutcomeStatus('failed'), 'failed'); assert.equal(mapEventGatewayOutcomeStatus('blocked'), 'blocked'); assert.equal(mapEventGatewayOutcomeStatus('committed'), undefined); assert.equal(mapEventGatewayOutcomeStatus('no_changes'), undefined) })

test('E53-E58 weak or conflicted verification completes safely with zero durable canonical output', async () => { const f = await fixture(); try { const weak = new SequenceExecutor([validAssessment(['gdelt-1']), validSynthesis(['gdelt-1'])]); const weakResult = await runEventResearch(f.input({ reasoningExecutor: weak, acquisitionPlugins: [plugin('gdelt-news', [candidate('gdelt-1', 'gdelt')])] })); assert.equal(weakResult.status, 'completed'); assert.equal(weakResult.verification?.verificationLevel, 'single_source'); assert.equal(weakResult.proposalIds.length, 0); assert.equal(weakResult.sourceIds.length, 0); const conflictedAssessment = { ...validAssessment(['cninfo-1', 'gdelt-1']), sourceAssessments: [{ ...validAssessment(['cninfo-1']).sourceAssessments[0]!, sourceCandidateId: 'cninfo-1', verdict: 'supports' as const }, { ...validAssessment(['gdelt-1']).sourceAssessments[0]!, sourceCandidateId: 'gdelt-1', verdict: 'contradicts' as const }] }; const conflicted = new SequenceExecutor([conflictedAssessment, validSynthesis()]); const conflictResult = await runEventResearch(f.input({ reasoningExecutor: conflicted })); assert.equal(conflictResult.verification?.verificationLevel, 'conflicted'); assert.equal(conflictResult.proposalIds.length, 0) } finally { await f.close() } })

test('E59-E64 Stage A/B repair is one attempt and invalid output falls back without unauthorized refs', async () => { const f = await fixture(); try { const invalidA = { sourceAssessments: [{ sourceCandidateId: 'forged', verdict: 'supports', confidence: 1, rationale: 'bad', evidenceRequirement: 'primary' }], verifiedFacts: [], contradictions: [] }; const executor = new SequenceExecutor([invalidA, invalidA, validSynthesis()]); const result = await runEventResearch(f.input({ reasoningExecutor: executor })); assert.equal(result.status, 'completed'); assert.equal(result.telemetry.assessment.repairAttempts, 1); assert.equal(result.telemetry.assessment.fallbackUsed, true); assert.equal(result.telemetry.synthesis.fallbackUsed, true); assert.equal(result.proposalIds.length, 0); assert.equal(executor.requests.length, 4); assert.equal(JSON.stringify(executor.requests[1]?.input).includes('stack'), false) } finally { await f.close() } })

test('E65-E69 replay keeps the event occurrence Claim slot stable', async () => { const f = await fixture(); try { const output = [validAssessment(['cninfo-1']), validSynthesis(['cninfo-1'])]; const first = await runEventResearch(f.input({ reasoningExecutor: new SequenceExecutor(output) })); const remounted = await f.registry.mount(f.root); const second = await runEventResearch(f.input({ handle: remounted, workflowRunId: 'event-run-replay', reasoningExecutor: new SequenceExecutor(output) })); const assets = await readCanonicalV04Assets(f.root); const occurrence = assets.objects.filter((item) => item.kind === 'claim' && JSON.stringify(item.value).includes('event_occurrence_')); assert.equal(first.status, 'completed'); assert.equal(second.status, 'completed'); assert.equal(occurrence.length, 1); assert.equal(second.claimIds.length, 2) } finally { await f.close() } })

test('E70-E75 manual article/user event content remains anchor context and is never canonical evidence by itself', async () => { const f = await fixture(); try { const result = await runEventResearch(f.input({ anchor: { kind: 'article', url: 'https://example.test/manual', title: 'Manual article', publishedAt: '2026-09-08T01:00:00.000Z', content: 'User-provided article text.' }, acquisitionPlugins: [], reasoningExecutor: undefined })); assert.equal(result.status, 'completed'); assert.equal(result.sourceIds.length, 0); assert.equal(result.claimIds.length, 0); assert.equal(result.report?.anchor.kind, 'article'); assert.equal(result.telemetry.anchorResolved, true) } finally { await f.close() } })

test('E76-E80 cancellation is safe at the workflow boundary and report contract gap is explicit', async () => { const f = await fixture(); try { const controller = new AbortController(); controller.abort(); let called = 0; const p = plugin('cninfo-official', [candidate('cninfo-1', 'cninfo')]); const wrapped = { ...p, discover: async () => { called++; return [] } }; const result = await runEventResearch(f.input({ signal: controller.signal, acquisitionPlugins: [wrapped] })); assert.equal(result.status, 'cancelled'); assert.equal(called, 0); assert.match(EVENT_RESEARCH_REPORT_CONTRACT_NOTE, /ResearchReport\.reportType/); assert.match(result.errors.join('\n'), /WORKFLOW_CANCELLED/) } finally { await f.close() } })
