import assert from 'node:assert/strict'
import test from 'node:test'
import { calculateBusinessDriverAnalysis } from '../../skills/business_driver_analysis/index.ts'
import { calculateUnitEconomics } from '../../skills/unit_economics/index.ts'
import { analyzeIndustrySupplyDemandCycle } from '../../skills/industry_supply_demand_cycle/index.ts'
import { calculateCompanyIndustryExposureBridge } from '../../workflows/company-deep-research/industry-exposure-bridge.ts'

const refs = (name: string): readonly string[] => [`fixture:${name}`]
const asOf = '2026-09-21T00:00:00.000Z'

test('fixture target A manufacturing composes drivers, shipment economics, cycle, and exposure impact', () => {
  const driver = calculateBusinessDriverAnalysis({ companyRef: 'company:target-a', archetype: 'manufacturing', currentPeriod: '2026-H1', priorPeriod: '2025-H1', asOf, segments: [{ id: 'industrial', name: 'Industrial products', outcomes: [{ metric: 'revenue', unit: 'CNYm', currentValue: 1_320, priorValue: 1_000, currentSourceRefs: refs('a-revenue-current'), priorSourceRefs: refs('a-revenue-prior') }], drivers: [{ id: 'volume', name: 'Units shipped', driverType: 'volume', segment: 'industrial', metric: 'revenue', relationshipType: 'multiplicative', unit: 'units', period: '2026-H1', priorPeriod: '2025-H1', currentValue: 120, priorValue: 100, sourceRefs: refs('a-volume'), availability: 'reported', confidence: 'high' }, { id: 'price', name: 'ASP', driverType: 'price', segment: 'industrial', metric: 'revenue', relationshipType: 'multiplicative', unit: 'CNY/unit', period: '2026-H1', priorPeriod: '2025-H1', currentValue: 11, priorValue: 10, sourceRefs: refs('a-price'), availability: 'reported', confidence: 'high' }] }] })
  const unit = calculateUnitEconomics({ companyRef: 'company:target-a', archetype: 'manufacturing', currentPeriod: '2026-H1', priorPeriod: '2025-H1', asOf, units: [{ id: 'shipment', name: 'Industrial shipment', unitType: 'shipment', scope: 'industrial products', countUnit: 'units', currentCount: 120, priorCount: 100, currentCountSourceRefs: refs('a-count-current'), priorCountSourceRefs: refs('a-count-prior'), metrics: [{ metric: 'revenue', unit: 'CNYm', currentValue: 1_320, priorValue: 1_000, currentPeriod: '2026-H1', priorPeriod: '2025-H1', sourceRefs: refs('a-revenue'), availability: 'reported' }] }] })
  const cycle = analyzeIndustrySupplyDemandCycle({ industryRef: 'industry:industrial-components', asOf, demand: [{ id: 'orders', kind: 'orders', direction: 'down', period: '2026-H1', sourceRefs: refs('a-orders'), confidence: 'high', availability: 'reported' }], capacity: [{ id: 'effective-capacity', state: 'effective', change: 'up', value: 120, unit: 'units', period: '2026-H1', sourceRefs: refs('a-capacity') }], utilization: { period: '2026-H1', reportedValue: 0.55, unit: 'ratio', sourceRefs: refs('a-utilization') }, inventory: [{ id: 'channel', kind: 'channel_inventory', direction: 'up', level: 120, unit: 'days', period: '2026-H1', hasHistory: true, sourceRefs: refs('a-inventory') }], pricing: [{ id: 'spot', kind: 'spot_price', direction: 'down', currentValue: 90, priorValue: 100, unit: 'CNY/unit', period: '2026-H1', priorPeriod: '2025-H1', sourceRefs: refs('a-price-cycle') }] })
  const bridge = calculateCompanyIndustryExposureBridge({ companyRef: 'company:target-a', industryRef: 'industry:industrial-components', asOf, items: [{ id: 'a-volume-exposure', driver: { id: 'cycle-demand', name: 'Industry shipment demand', delta: -0.1, unit: 'ratio', period: '2026-H1', sourceRefs: refs('a-cycle-driver') }, exposure: { type: 'revenue', description: 'Target A industrial shipment revenue', value: 1_320, unit: 'CNYm', sourceRefs: refs('a-exposure') }, sensitivity: { value: 1, outputUnit: 'CNYm', sourceRefs: refs('a-sensitivity') }, qualitativeDependency: 'Lower industry demand pressures shipment revenue.' }] })
  assert.equal(driver.status, 'complete')
  assert.equal(unit.units[0]?.metrics[0]?.currentPerUnit, 11)
  assert.equal(cycle.state, 'oversupply')
  assert.equal(bridge.items[0]?.financialImpact?.value, -132)
})

test('fixture target B SaaS uses customer and ARPU economics without manufacturing assumptions', () => {
  const driver = calculateBusinessDriverAnalysis({ companyRef: 'company:target-b', archetype: 'software_saas', currentPeriod: '2026-H1', priorPeriod: '2025-H1', asOf, segments: [{ id: 'subscription', name: 'Subscription', outcomes: [{ metric: 'revenue', unit: 'USDm', currentValue: 14_400, priorValue: 10_000, currentSourceRefs: refs('b-revenue-current'), priorSourceRefs: refs('b-revenue-prior') }], drivers: [{ id: 'customers', name: 'Customers', driverType: 'customers', segment: 'subscription', metric: 'revenue', relationshipType: 'multiplicative', unit: 'customers', period: '2026-H1', priorPeriod: '2025-H1', currentValue: 1_200, priorValue: 1_000, sourceRefs: refs('b-customers'), availability: 'reported', confidence: 'high' }, { id: 'arpu', name: 'ARPU', driverType: 'ARPU', segment: 'subscription', metric: 'revenue', relationshipType: 'multiplicative', unit: 'USD/customer', period: '2026-H1', priorPeriod: '2025-H1', currentValue: 12, priorValue: 10, sourceRefs: refs('b-arpu'), availability: 'reported', confidence: 'high' }] }] })
  const unit = calculateUnitEconomics({ companyRef: 'company:target-b', archetype: 'software_saas', currentPeriod: '2026-H1', priorPeriod: '2025-H1', asOf, units: [{ id: 'customer', name: 'Active customer', unitType: 'customer', scope: 'subscription base', countUnit: 'customers', currentCount: 1_200, priorCount: 1_000, currentCountSourceRefs: refs('b-count-current'), priorCountSourceRefs: refs('b-count-prior'), metrics: [{ metric: 'revenue', unit: 'USDm', currentValue: 14_400, priorValue: 10_000, currentPeriod: '2026-H1', priorPeriod: '2025-H1', sourceRefs: refs('b-revenue'), availability: 'reported' }] }] })
  const bridge = calculateCompanyIndustryExposureBridge({ companyRef: 'company:target-b', industryRef: 'industry:software', asOf, items: [{ id: 'b-retention', driver: { id: 'industry-adoption', name: 'Enterprise software adoption', unit: 'state', period: '2026-H1', sourceRefs: refs('b-adoption') }, exposure: { type: 'customer', description: 'Customer retention dependency', unit: 'customers', sourceRefs: refs('b-exposure') }, qualitativeDependency: 'Adoption and retention affect customer count and ARPU, but no explicit sensitivity is supplied.' }] })
  assert.equal(driver.archetype, 'software_saas')
  assert.equal(driver.status, 'complete')
  assert.equal(unit.units[0]?.metrics[0]?.currentPerUnit, 12)
  assert.equal(bridge.items[0]?.financialImpact, undefined)
  assert.equal(bridge.qualitativeDependencies.length, 1)
})
