import assert from 'node:assert/strict'
import test from 'node:test'
import type { ReasoningExecutor, ReasoningRequest, ReasoningResult } from '../../plugins/reasoning/contracts.ts'
import { boundedPreviousReasoningOutput, deriveVerdictDurableEvidence, designThesisAttacks, filterThesisRedTeamProposals, projectionClaimsForThesis, qualifyRedTeamEvidence, qualifyRedTeamEvidenceSet, repairThesisRedTeamProposals, synthesizeThesisRedTeam, validateRedTeamVerdictConsistency, validateThesisRedTeamSynthesis } from '../../skills/thesis-red-team/index.ts'
import type { ThesisRedTeamSkillContext } from '../../skills/thesis-red-team/contracts.ts'

class FixtureExecutor implements ReasoningExecutor {
  constructor(private readonly outputs: readonly unknown[]) {}
  capabilities() { return { maxContextTokens: 10_000, maxOutputTokens: 4_000, structuredOutputSupport: true, maxConcurrency: 1 } }
  private index = 0
  async execute(request: ReasoningRequest): Promise<ReasoningResult> { return { operation: request.operation, output: this.outputs[Math.min(this.index++, this.outputs.length - 1)] } }
}
const claims = [
  { canonicalRef: 'claim:thesis-1', claimType: 'thesis', subjectRefs: ['entity:company'], statement: 'Demand leadership drives durable growth.', lifecycle: { status: 'active' }, dependsOnClaimRefs: ['claim:assumption-1'], supportsClaimRefs: ['claim:fact-1'] },
  { canonicalRef: 'claim:assumption-1', claimType: 'assumption', subjectRefs: ['entity:company'], statement: 'Demand remains strong.', lifecycle: { status: 'active' }, structuredValue: { metric: 'demand', value: true, unit: 'state', comparator: 'eq', period: 'current' } },
  { canonicalRef: 'claim:fact-1', claimType: 'fact', subjectRefs: ['entity:company'], statement: 'Capacity expanded.', lifecycle: { status: 'active' } },
  { canonicalRef: 'claim:risk-1', claimType: 'risk', subjectRefs: ['entity:company'], statement: 'Competition may intensify.', lifecycle: { status: 'active' } },
]
const context = (sources = [{ candidateId: 'official-1', title: 'Official', provider: 'cninfo', kind: 'official_disclosure', excerpt: 'Disclosure.', publishedAt: '2026-09-08T00:00:00.000Z' }]): ThesisRedTeamSkillContext => { const projection = projectionClaimsForThesis(claims, 'entity:company', 'claim:thesis-1'); return { company: { symbol: '600519', name: 'Fixture', exchange: 'SSE' }, thesis: claims[0]!, projection, signals: [], sources, attackDesign: { attackVectors: [{ vectorId: 'vector-1', vectorType: 'assumption_failure', priority: 'high', targetExistingClaimRefs: ['claim:assumption-1'], falsificationQuestion: 'What breaks demand?', failureMechanism: 'Demand falls.', evidenceNeeded: 'Disclosure', searchTerms: ['demand'] }], implicitAssumptions: [], invalidationConditions: [{ conditionId: 'condition-1', statement: 'Demand collapses.', severity: 'critical', targetExistingClaimRefs: ['claim:assumption-1'] }] } } }
const attack = { attackVectors: [{ vectorId: 'vector-1', vectorType: 'assumption_failure', priority: 'high', targetExistingClaimRefs: ['claim:assumption-1'], falsificationQuestion: 'What breaks demand?', failureMechanism: 'Demand falls.', evidenceNeeded: 'Disclosure', searchTerms: ['demand'] }], implicitAssumptions: [], invalidationConditions: [{ conditionId: 'condition-1', statement: 'Demand collapses.', severity: 'critical', targetExistingClaimRefs: ['claim:assumption-1'] }] }
const synthesis = { evidenceAssessments: [{ sourceCandidateId: 'official-1', attackVectorRefs: ['vector-1'], relation: 'disconfirms', strength: 'high', rationale: 'Official evidence challenges demand.' }], challengeAssessments: [{ challengeId: 'challenge-1', challengeType: 'thesis_contradiction', basis: 'verified_evidence', status: 'supported', severity: 'high', timeHorizon: 'near_term', targetExistingClaimRefs: ['claim:thesis-1'], attackVectorRefs: ['vector-1'], sourceCandidateIds: ['official-1'], causalChain: 'Demand falls -> growth weakens.', rationale: 'The thesis is challenged.' }, { challengeId: 'challenge-2', challengeType: 'alternative_explanation', basis: 'inference', status: 'partially_supported', severity: 'medium', timeHorizon: 'medium_term', targetExistingClaimRefs: [], attackVectorRefs: ['vector-1'], sourceCandidateIds: [], causalChain: 'Mix shift -> observed growth.', rationale: 'An alternative explanation fits.' }, { challengeId: 'challenge-3', challengeType: 'failure_case', basis: 'hypothesis', status: 'unresolved', severity: 'high', timeHorizon: 'long_term', targetExistingClaimRefs: [], attackVectorRefs: ['vector-1'], sourceCandidateIds: [], causalChain: 'Competition rises -> margins fall.', rationale: 'A bear case remains possible.' }], thesisVerdict: 'weakened', interpretations: [{ interpretationId: 'interpretation-1', sectionId: 'resilience', markdown: 'The thesis is weakened but not invalidated.', sourceCandidateIds: ['official-1'], existingKnowledgeRefs: ['claim:thesis-1'], challengeRefs: ['challenge-1'] }], proposals: [{ proposalId: 'proposal-1', kind: 'claim', claimType: 'risk', subjectKey: 'company', statement: 'Demand risk increased.', sourceCandidateIds: ['official-1'], challengeRefs: ['challenge-1'] }] }

test('Thesis Red Team projection is one-hop bounded and includes dependency fields', () => { const result = projectionClaimsForThesis(claims, 'entity:company', 'claim:thesis-1'); assert.ok(result.criticalAssumptions.some((item) => item.canonicalRef === 'claim:assumption-1')); assert.ok(result.claims.length <= 40); assert.deepEqual(result.directDependencyRefs, ['claim:assumption-1', 'claim:fact-1']) })
test('Thesis Red Team Stage A validates attack design and does not receive sources', async () => { const executor = new FixtureExecutor([attack]); const result = await designThesisAttacks(context(), executor); assert.equal(result.reasoning.applied, true); assert.equal(result.output.attackVectors.length, 1) })
test('Thesis Red Team Stage B keeps semantic core separate from proposal gate', async () => { const result = await synthesizeThesisRedTeam(context(), new FixtureExecutor([synthesis])); assert.equal(result.reasoning.applied, true); assert.equal(result.output.challengeAssessments.length, 3); const filtered = filterThesisRedTeamProposals(context(), result.output); assert.equal(filtered.accepted.length, 1) })
test('Thesis Red Team rejects legacy report sections and hypothesis evidence', () => { assert.throws(() => validateThesisRedTeamSynthesis({ sections: [], evidenceAssessments: [], challengeAssessments: [], thesisVerdict: 'inconclusive', interpretations: [], proposals: [] }, context()), /Model-owned report sections/) })
test('Thesis Red Team second invalid Stage A output fails closed', async () => { const result = await designThesisAttacks(context(), new FixtureExecutor([{}, {}])); assert.equal(result.reasoning.fallbackUsed, true); assert.equal(result.reasoning.validated, false); assert.equal(result.output.attackVectors.length, 0) })
test('Thesis Red Team second invalid Stage B output fails closed', async () => { const result = await synthesizeThesisRedTeam(context(), new FixtureExecutor([{}, {}])); assert.equal(result.reasoning.fallbackUsed, true); assert.equal(result.reasoning.validated, false); assert.equal(result.output.thesisVerdict, 'inconclusive') })
test('Thesis Red Team malformed proposal does not invalidate semantic core', async () => { const malformed = { ...synthesis, proposals: [{ ...synthesis.proposals[0], claimType: 'thesis' }] } as any; const result = await synthesizeThesisRedTeam(context(), new FixtureExecutor([malformed])); assert.equal(result.reasoning.fallbackUsed, false); assert.equal(result.output.challengeAssessments.length, 3); assert.equal(result.output.proposals.length, 0) })
test('Thesis Red Team unknown-date evidence is not qualified or durable', () => { const assessment = synthesis.evidenceAssessments[0] as any; const qualified = qualifyRedTeamEvidence(assessment, [{ candidateId: 'official-1', title: 'Official', provider: 'cninfo', kind: 'official_disclosure', excerpt: 'Disclosure.' }]); assert.equal(qualified.qualified, false); const filtered = filterThesisRedTeamProposals(context([{ candidateId: 'official-1', title: 'Official', provider: 'cninfo', kind: 'official_disclosure', excerpt: 'Disclosure.' }] as any), { ...synthesis, proposals: synthesis.proposals } as any); assert.equal(filtered.accepted.length, 0) })
test('Thesis Red Team repair carries bounded real previous output and diagnostics context', async () => { const output = { attackVectors: [{ vectorId: 'keep-me', vectorType: 'bad', priority: 'bad', targetExistingClaimRefs: [], falsificationQuestion: 'x', failureMechanism: 'x', evidenceNeeded: 'x', searchTerms: [] }], implicitAssumptions: [], invalidationConditions: [] }; const value = boundedPreviousReasoningOutput({ ...output, apiToken: 'must-not-appear' }); assert.match(value, /keep-me/); assert.doesNotMatch(value, /must-not-appear/); assert.ok(value.length <= 12000) })
test('Thesis Red Team Stage A repair receives the bounded first output', async () => { const requests: ReasoningRequest[] = []; const executor: ReasoningExecutor = { capabilities: () => ({ maxContextTokens: 1000, maxOutputTokens: 1000, structuredOutputSupport: true, maxConcurrency: 1 }), execute: async (request) => { requests.push(request); return { operation: request.operation, output: requests.length === 1 ? { attackVectors: [{ vectorId: 'keep-id' }], implicitAssumptions: [], invalidationConditions: [] } : attack } } }; await designThesisAttacks(context(), executor); assert.match(JSON.stringify(requests[1]?.input), /keep-id/); assert.doesNotMatch(JSON.stringify(requests[1]?.input), /bounded-invalid-output/) })
test('Thesis Red Team Stage B repair receives the bounded first output', async () => { const requests: ReasoningRequest[] = []; const executor: ReasoningExecutor = { capabilities: () => ({ maxContextTokens: 1000, maxOutputTokens: 1000, structuredOutputSupport: true, maxConcurrency: 1 }), execute: async (request) => { requests.push(request); return { operation: request.operation, output: requests.length === 1 ? { evidenceAssessments: [{ sourceCandidateId: 'keep-source' }], challengeAssessments: [], thesisVerdict: 'weakened', interpretations: [], proposals: [] } : synthesis } } }; await synthesizeThesisRedTeam(context(), executor); assert.match(JSON.stringify(requests[1]?.input), /keep-source/); assert.doesNotMatch(JSON.stringify(requests[1]?.input), /bounded-invalid-output/) })
test('Thesis Red Team collection qualification uses same relation and attack context', () => { const sources = [{ candidateId: 'a', title: 'A', provider: 'news-a', url: 'https://a.example/x', publishedAt: '2026-09-08T00:00:00Z', excerpt: 'a' }, { candidateId: 'b', title: 'B', provider: 'news-b', url: 'https://b.example/x', publishedAt: '2026-09-08T00:00:00Z', excerpt: 'b' }, { candidateId: 'c', title: 'C', provider: 'news-c', url: 'https://c.example/x', publishedAt: '2026-09-08T00:00:00Z', excerpt: 'c' }]; const assessments = [{ sourceCandidateId: 'a', attackVectorRefs: ['vector-1'], relation: 'disconfirms', strength: 'high', rationale: 'a' }, { sourceCandidateId: 'b', attackVectorRefs: ['vector-1'], relation: 'disconfirms', strength: 'low', rationale: 'b' }, { sourceCandidateId: 'c', attackVectorRefs: ['vector-1'], relation: 'supports', strength: 'high', rationale: 'c' }] as any; const result = qualifyRedTeamEvidenceSet(assessments, sources); assert.equal(result.find((item) => item.sourceCandidateId === 'a')?.strength, 'high'); assert.deepEqual(result.find((item) => item.sourceCandidateId === 'a')?.corroboratingSourceIds, ['b']); assert.equal(result.find((item) => item.sourceCandidateId === 'c')?.strength, 'medium') })
test('Thesis Red Team verdict requires qualified evidence binding', () => { const challenge = synthesis.challengeAssessments[0]! as any; const invalid = validateRedTeamVerdictConsistency('materially_challenged', [challenge], [], new Set(['condition-1'])); assert.equal(invalid.valid, false); const evidence = qualifyRedTeamEvidenceSet(synthesis.evidenceAssessments as any, [{ candidateId: 'official-1', title: 'Official', provider: 'cninfo', kind: 'official_disclosure', excerpt: 'Disclosure.', publishedAt: '2026-09-08T00:00:00.000Z' }] as any); const valid = validateRedTeamVerdictConsistency('weakened', [challenge], evidence, new Set(['condition-1'])); assert.equal(valid.valid, true) })
test('Thesis Red Team projection preserves priority and additional hop under 40-item bound', () => { const large = [{ ...claims[0], dependsOnClaimRefs: ['claim:direct-assumption'], supportsClaimRefs: ['claim:direct-fact'] }, { canonicalRef: 'claim:direct-assumption', claimType: 'assumption', subjectRefs: ['entity:company'], statement: 'Direct assumption.', dependsOnClaimRefs: ['claim:hop'] }, { canonicalRef: 'claim:direct-fact', claimType: 'fact', subjectRefs: ['entity:company'], statement: 'Direct fact.' }, { canonicalRef: 'claim:hop', claimType: 'fact', subjectRefs: ['entity:company'], statement: 'Additional hop.' }, ...Array.from({ length: 50 }, (_, index) => ({ canonicalRef: `claim:unrelated-${index}`, claimType: 'fact', subjectRefs: ['entity:company'], statement: 'Unrelated.' }))]; const result = projectionClaimsForThesis(large, 'entity:company', 'claim:thesis-1'); assert.ok(result.claims.length <= 40); assert.ok(result.claims.some((item) => item.canonicalRef === 'claim:thesis-1')); assert.ok(result.claims.some((item) => item.canonicalRef === 'claim:direct-assumption')); assert.ok(result.claims.some((item) => item.canonicalRef === 'claim:hop')); assert.equal(result.claims.some((item) => item.canonicalRef === 'claim:unrelated-49'), false) })
test('Thesis Red Team single nonofficial evidence remains medium', () => { const result = qualifyRedTeamEvidenceSet([{ sourceCandidateId: 'news-1', attackVectorRefs: ['vector-1'], relation: 'disconfirms', strength: 'high', rationale: 'news' }], [{ candidateId: 'news-1', title: 'News', provider: 'news', url: 'https://news.example/a', publishedAt: '2026-09-08T00:00:00Z', excerpt: 'news' }]); assert.equal(result[0]?.strength, 'medium'); assert.equal(result[0]?.effectiveStrength, 'medium') })
test('Thesis Red Team unrelated providers do not corroborate', () => { const result = qualifyRedTeamEvidenceSet([{ sourceCandidateId: 'a', attackVectorRefs: ['vector-1'], relation: 'disconfirms', strength: 'high', rationale: 'a' }, { sourceCandidateId: 'b', attackVectorRefs: ['vector-2'], relation: 'disconfirms', strength: 'high', rationale: 'b' }], [{ candidateId: 'a', title: 'A', provider: 'a', url: 'https://a.example/a', publishedAt: '2026-09-08T00:00:00Z', excerpt: 'a' }, { candidateId: 'b', title: 'B', provider: 'b', url: 'https://b.example/b', publishedAt: '2026-09-08T00:00:00Z', excerpt: 'b' }]); assert.equal(result.every((item) => item.strength === 'medium'), true); assert.deepEqual(result.map((item) => item.corroboratingSourceIds), [[], []]) })
test('Thesis Red Team irrelevant or context source cannot support a durable proposal', () => { const sources = [{ candidateId: 'official-1', title: 'Official', provider: 'cninfo', kind: 'official_disclosure', publishedAt: '2026-09-08T00:00:00Z', excerpt: 'context' }]; const qualified = qualifyRedTeamEvidenceSet([{ sourceCandidateId: 'official-1', attackVectorRefs: ['vector-1'], relation: 'irrelevant', strength: 'high', rationale: 'irrelevant' }], sources); const output = { ...synthesis, evidenceAssessments: [{ ...synthesis.evidenceAssessments[0], relation: 'irrelevant' }], proposals: [{ ...synthesis.proposals[0], claimType: 'risk', sourceCandidateIds: ['official-1'] }] } as any; assert.equal(qualified[0]?.qualified, false); assert.equal(filterThesisRedTeamProposals(context(sources as any), output, qualified).accepted.length, 0) })
test('Thesis Red Team invalidation requires matching strong disconfirming evidence', () => { const challenge = { ...synthesis.challengeAssessments[0], challengeType: 'invalidation_condition', status: 'condition_met', conditionRef: 'condition-1' } as any; const evidence = qualifyRedTeamEvidenceSet([{ ...synthesis.evidenceAssessments[0], relation: 'supports' } as any], context().sources as any); assert.equal(validateRedTeamVerdictConsistency('invalidation_condition_met', [challenge], evidence, new Set(['condition-1'])).valid, false) })
test('Thesis Red Team assumption update binds one existing assumption and preserves fields', () => { const valid = { ...synthesis, proposals: [{ proposalId: 'assumption-update', kind: 'claim', claimType: 'assumption', subjectKey: 'company', statement: 'Demand remains strong.', sourceCandidateIds: ['official-1'], existingKnowledgeRefs: ['claim:assumption-1'], challengeRefs: ['challenge-1'], structuredValue: { metric: 'demand', value: false, unit: 'state', comparator: 'eq', period: 'current' } }] } as any; assert.equal(filterThesisRedTeamProposals(context(), valid).accepted.length, 1); assert.equal(filterThesisRedTeamProposals(context(), { ...valid, proposals: [{ ...valid.proposals[0], existingKnowledgeRefs: ['claim:thesis-1'] }] }).accepted.length, 0); assert.equal(filterThesisRedTeamProposals(context(), { ...valid, proposals: [{ ...valid.proposals[0], structuredValue: { ...valid.proposals[0].structuredValue, unit: 'ratio' } }] }).accepted.length, 0) })
test('FIX-003 deterministic verdict evidence is independent of model proposals', () => { const qualified = qualifyRedTeamEvidenceSet(synthesis.evidenceAssessments as any, context().sources); const result = deriveVerdictDurableEvidence('weakened', synthesis.challengeAssessments as any, qualified); assert.deepEqual(result.sourceCandidateIds, ['official-1']); assert.deepEqual(result.supportingChallengeIds, ['challenge-1']) })
test('FIX-003 proposal-only repair freezes the semantic core and returns proposals only', async () => { const qualified = qualifyRedTeamEvidenceSet(synthesis.evidenceAssessments as any, context().sources); const requests: ReasoningRequest[] = []; const executor: ReasoningExecutor = { capabilities: () => ({ maxContextTokens: 1000, maxOutputTokens: 1000, structuredOutputSupport: true, maxConcurrency: 1 }), execute: async (request) => { requests.push(request); return { operation: request.operation, output: { proposals: [synthesis.proposals[0]] } } } }; const core = { evidenceAssessments: synthesis.evidenceAssessments, challengeAssessments: synthesis.challengeAssessments, thesisVerdict: synthesis.thesisVerdict, interpretations: synthesis.interpretations }; const result = await repairThesisRedTeamProposals(context(), core as any, [{ ...synthesis.proposals[0], claimType: 'thesis' } as any], qualified, ['proposal_0_qualified_evidence_required'], executor); assert.equal(result.called, true); assert.equal(result.accepted.length, 1); assert.equal(requests.length, 1); assert.ok(JSON.stringify(requests[0]?.input).includes('challenge-1')); assert.equal(JSON.stringify(requests[0]?.input).includes('evidenceAssessments'), false) })
test('FIX-003 proposal-only repair fails closed after its single attempt', async () => { const qualified = qualifyRedTeamEvidenceSet(synthesis.evidenceAssessments as any, context().sources); const executor = new FixtureExecutor([{ proposals: [{ proposalId: 'bad', kind: 'claim', claimType: 'thesis', subjectKey: 'company', statement: 'bad', sourceCandidateIds: ['official-1'], challengeRefs: [] }] }]); const core = { evidenceAssessments: synthesis.evidenceAssessments, challengeAssessments: synthesis.challengeAssessments, thesisVerdict: synthesis.thesisVerdict, interpretations: synthesis.interpretations }; const result = await repairThesisRedTeamProposals(context(), core as any, synthesis.proposals as any, qualified, ['proposal_invalid'], executor); assert.equal(result.called, true); assert.equal(result.proposals.length, 0); assert.equal(result.accepted.length, 0) })
test('FIX-003 missing failure case invokes semantic repair exactly once', async () => { const missing = { ...synthesis, challengeAssessments: synthesis.challengeAssessments.filter((item) => item.challengeType !== 'failure_case') }; const requests: ReasoningRequest[] = []; const executor: ReasoningExecutor = { capabilities: () => ({ maxContextTokens: 1000, maxOutputTokens: 1000, structuredOutputSupport: true, maxConcurrency: 1 }), execute: async (request) => { requests.push(request); return { operation: request.operation, output: requests.length === 1 ? missing : synthesis } } }; const result = await synthesizeThesisRedTeam(context(), executor); assert.equal(result.reasoning.repairAttempts, 1); assert.equal(result.reasoning.fallbackUsed, false); assert.equal(result.output.challengeAssessments.some((item) => item.challengeType === 'failure_case'), true); assert.equal(requests.length, 2) })
test('FIX-003 hypothesis failure case is report-only after deterministic evidence stripping', () => { const value = { ...synthesis, challengeAssessments: synthesis.challengeAssessments.map((item) => item.challengeType === 'failure_case' ? { ...item, sourceCandidateIds: ['official-1'] } : item) }; const result = validateThesisRedTeamSynthesis(value, context()); assert.deepEqual(result.challengeAssessments.find((item) => item.challengeType === 'failure_case')?.sourceCandidateIds, []) })
