import assert from 'node:assert/strict'
import test from 'node:test'
import type { ReasoningExecutor, ReasoningRequest, ReasoningResult } from '../../plugins/reasoning/contracts.ts'
import { designThesisAttacks, filterThesisRedTeamProposals, projectionClaimsForThesis, qualifyRedTeamEvidence, synthesizeThesisRedTeam, validateThesisRedTeamSynthesis } from '../../skills/thesis-red-team/index.ts'
import type { ThesisRedTeamSkillContext } from '../../skills/thesis-red-team/contracts.ts'

class FixtureExecutor implements ReasoningExecutor {
  constructor(private readonly outputs: readonly unknown[]) {}
  capabilities() { return { maxContextTokens: 10_000, maxOutputTokens: 4_000, structuredOutputSupport: true, maxConcurrency: 1 } }
  private index = 0
  async execute(request: ReasoningRequest): Promise<ReasoningResult> { return { operation: request.operation, output: this.outputs[Math.min(this.index++, this.outputs.length - 1)] } }
}
const claims = [
  { canonicalRef: 'claim:thesis-1', claimType: 'thesis', subjectRefs: ['entity:company'], statement: 'Demand leadership drives durable growth.', lifecycle: { status: 'active' }, dependsOnClaimRefs: ['claim:assumption-1'], supportsClaimRefs: ['claim:fact-1'] },
  { canonicalRef: 'claim:assumption-1', claimType: 'assumption', subjectRefs: ['entity:company'], statement: 'Demand remains strong.', lifecycle: { status: 'active' }, structuredValue: { metric: 'demand', value: true, unit: 'state', comparator: 'eq', period: 'current' } },
  { canonicalRef: 'claim:fact-1', claimType: 'fact', subjectRefs: ['entity:company'], statement: 'Capacity expanded.', lifecycle: { status: 'active' } },
  { canonicalRef: 'claim:risk-1', claimType: 'risk', subjectRefs: ['entity:company'], statement: 'Competition may intensify.', lifecycle: { status: 'active' } },
]
const context = (sources = [{ candidateId: 'official-1', title: 'Official', provider: 'cninfo', kind: 'official_disclosure', excerpt: 'Disclosure.', publishedAt: '2026-09-08T00:00:00.000Z' }]): ThesisRedTeamSkillContext => { const projection = projectionClaimsForThesis(claims, 'entity:company', 'claim:thesis-1'); return { company: { symbol: '600519', name: 'Fixture', exchange: 'SSE' }, thesis: claims[0]!, projection, signals: [], sources, attackDesign: { attackVectors: [{ vectorId: 'vector-1', vectorType: 'assumption_failure', priority: 'high', targetExistingClaimRefs: ['claim:assumption-1'], falsificationQuestion: 'What breaks demand?', failureMechanism: 'Demand falls.', evidenceNeeded: 'Disclosure', searchTerms: ['demand'] }], implicitAssumptions: [], invalidationConditions: [{ conditionId: 'condition-1', statement: 'Demand collapses.', severity: 'critical', targetExistingClaimRefs: ['claim:assumption-1'] }] } } }
const attack = { attackVectors: [{ vectorId: 'vector-1', vectorType: 'assumption_failure', priority: 'high', targetExistingClaimRefs: ['claim:assumption-1'], falsificationQuestion: 'What breaks demand?', failureMechanism: 'Demand falls.', evidenceNeeded: 'Disclosure', searchTerms: ['demand'] }], implicitAssumptions: [], invalidationConditions: [{ conditionId: 'condition-1', statement: 'Demand collapses.', severity: 'critical', targetExistingClaimRefs: ['claim:assumption-1'] }] }
const synthesis = { evidenceAssessments: [{ sourceCandidateId: 'official-1', attackVectorRefs: ['vector-1'], relation: 'disconfirms', strength: 'high', rationale: 'Official evidence challenges demand.' }], challengeAssessments: [{ challengeId: 'challenge-1', challengeType: 'thesis_contradiction', basis: 'verified_evidence', status: 'supported', severity: 'high', timeHorizon: 'near_term', targetExistingClaimRefs: ['claim:thesis-1'], attackVectorRefs: ['vector-1'], sourceCandidateIds: ['official-1'], causalChain: 'Demand falls -> growth weakens.', rationale: 'The thesis is challenged.' }, { challengeId: 'challenge-2', challengeType: 'alternative_explanation', basis: 'inference', status: 'partially_supported', severity: 'medium', timeHorizon: 'medium_term', targetExistingClaimRefs: [], attackVectorRefs: ['vector-1'], sourceCandidateIds: [], causalChain: 'Mix shift -> observed growth.', rationale: 'An alternative explanation fits.' }, { challengeId: 'challenge-3', challengeType: 'failure_case', basis: 'hypothesis', status: 'unresolved', severity: 'high', timeHorizon: 'long_term', targetExistingClaimRefs: [], attackVectorRefs: ['vector-1'], sourceCandidateIds: [], causalChain: 'Competition rises -> margins fall.', rationale: 'A bear case remains possible.' }], thesisVerdict: 'weakened', interpretations: [{ interpretationId: 'interpretation-1', sectionId: 'resilience', markdown: 'The thesis is weakened but not invalidated.', sourceCandidateIds: ['official-1'], existingKnowledgeRefs: ['claim:thesis-1'], challengeRefs: ['challenge-1'] }], proposals: [{ proposalId: 'proposal-1', kind: 'claim', claimType: 'risk', subjectKey: 'company', statement: 'Demand risk increased.', sourceCandidateIds: ['official-1'], challengeRefs: ['challenge-1'] }] }

test('Thesis Red Team projection is one-hop bounded and includes dependency fields', () => { const result = projectionClaimsForThesis(claims, 'entity:company', 'claim:thesis-1'); assert.ok(result.criticalAssumptions.some((item) => item.canonicalRef === 'claim:assumption-1')); assert.ok(result.claims.length <= 40); assert.deepEqual(result.directDependencyRefs, ['claim:assumption-1', 'claim:fact-1']) })
test('Thesis Red Team Stage A validates attack design and does not receive sources', async () => { const executor = new FixtureExecutor([attack]); const result = await designThesisAttacks(context(), executor); assert.equal(result.reasoning.applied, true); assert.equal(result.output.attackVectors.length, 1) })
test('Thesis Red Team Stage B keeps semantic core separate from proposal gate', async () => { const result = await synthesizeThesisRedTeam(context(), new FixtureExecutor([synthesis])); assert.equal(result.reasoning.applied, true); assert.equal(result.output.challengeAssessments.length, 3); const filtered = filterThesisRedTeamProposals(context(), result.output); assert.equal(filtered.accepted.length, 1) })
test('Thesis Red Team rejects legacy report sections and hypothesis evidence', () => { assert.throws(() => validateThesisRedTeamSynthesis({ sections: [], evidenceAssessments: [], challengeAssessments: [], thesisVerdict: 'inconclusive', interpretations: [], proposals: [] }, context()), /Model-owned report sections/) })
test('Thesis Red Team second invalid Stage A output fails closed', async () => { const result = await designThesisAttacks(context(), new FixtureExecutor([{}, {}])); assert.equal(result.reasoning.fallbackUsed, true); assert.equal(result.reasoning.validated, false); assert.equal(result.output.attackVectors.length, 0) })
test('Thesis Red Team second invalid Stage B output fails closed', async () => { const result = await synthesizeThesisRedTeam(context(), new FixtureExecutor([{}, {}])); assert.equal(result.reasoning.fallbackUsed, true); assert.equal(result.reasoning.validated, false); assert.equal(result.output.thesisVerdict, 'inconclusive') })
test('Thesis Red Team malformed proposal does not invalidate semantic core', async () => { const malformed = { ...synthesis, proposals: [{ ...synthesis.proposals[0], claimType: 'thesis' }] } as any; const result = await synthesizeThesisRedTeam(context(), new FixtureExecutor([malformed])); assert.equal(result.reasoning.fallbackUsed, false); assert.equal(result.output.challengeAssessments.length, 3); assert.equal(result.output.proposals.length, 0) })
test('Thesis Red Team unknown-date evidence is not qualified or durable', () => { const assessment = synthesis.evidenceAssessments[0] as any; const qualified = qualifyRedTeamEvidence(assessment, [{ candidateId: 'official-1', title: 'Official', provider: 'cninfo', kind: 'official_disclosure', excerpt: 'Disclosure.' }]); assert.equal(qualified.qualified, false); const filtered = filterThesisRedTeamProposals(context([{ candidateId: 'official-1', title: 'Official', provider: 'cninfo', kind: 'official_disclosure', excerpt: 'Disclosure.' }] as any), { ...synthesis, proposals: synthesis.proposals } as any); assert.equal(filtered.accepted.length, 0) })
