import assert from 'node:assert/strict'
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import test from 'node:test'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { createFreshKnowledgeBaseV04, readCanonicalV04Assets } from '../../knowledge/storage/index.ts'
import { KnowledgeBaseRegistry } from '../../knowledge/registry/registry.ts'
import { KnowledgeProductionGateway } from '../../knowledge/production/gateway.ts'
import type { ReasoningExecutor, ReasoningRequest, ReasoningResult } from '../../plugins/reasoning/contracts.ts'
import type { AkshareDataClient } from '../../plugins/research-acquisition/akshare.ts'
import { VALUATION_REPORT_SECTIONS } from '../../skills/valuation/contracts.ts'
import { buildValuationBasis, calculateTargetPrice, calculateValuation, methodEligibility, normalizeValuationFinancialData, normalizeValuationMarketData, referenceMultiples, selectValuationBasis, validateScenarioAssumptions } from '../../skills/valuation/financials.ts'
import { runValuation } from '../../workflows/valuation/workflow.ts'
import { ResearchService } from '../../app/services/research-service.ts'
import { WorkflowService } from '../../app/services/workflow-service.ts'

const NOW = '2026-09-09T00:00:00.000Z'
const RIGHTS = { accessScope: 'public' as const, retentionAllowed: true, aiProcessingAllowed: true, derivativeKnowledgeAllowed: true, redistributionAllowed: false }
type Dict = Record<string, unknown>

class FixtureExecutor implements ReasoningExecutor {
  readonly requests: ReasoningRequest[] = []
  capabilities() { return { maxContextTokens: 100_000, maxOutputTokens: 10_000, structuredOutputSupport: true, maxConcurrency: 2 } }
  async execute(request: ReasoningRequest): Promise<ReasoningResult> {
    this.requests.push(request)
    const input = request.input as Dict
    const source = ((input.allowedSourceCandidateIds as string[] | undefined) ?? [])[0] ?? 'missing-source'
    if (request.operation === 'valuation_assumption_design') {
      const targetFiscalYear = Number(input.targetFiscalYear)
      return { operation: request.operation, operationId: `fixture-${this.requests.length}`, output: { primaryMethod: 'PE', secondaryMethods: ['PB'], targetFiscalYear, scenarios: ['bear', 'base', 'bull'].map((scenarioId, index) => ({ scenarioId, primaryMethod: 'PE', targetFiscalYear, growthRate: [0.05, 0.1, 0.2][index], targetMultiple: [10, 12, 14][index], rationale: `Fixture ${scenarioId} assumption.`, sourceCandidateIds: [source], existingKnowledgeRefs: [] })) } }
    }
    return { operation: request.operation, operationId: `fixture-${this.requests.length}`, output: { sections: [{ sectionId: 'valuation-view', markdown: 'Bounded deterministic interpretation.', sourceCandidateIds: [source], existingKnowledgeRefs: [], valuationResultRefs: ['result-base'] }], proposals: [{ proposalId: 'valuation-view', kind: 'claim', claimType: 'viewpoint', subjectKey: 'company', statement: 'The base-case valuation is a bounded scenario view.', sourceCandidateIds: [source], valuationAssumptionRefs: [], valuationResultRefs: ['result-base'], existingKnowledgeRefs: [] }] } }
  }
}

function financialRows(): readonly Dict[] { return [{ 报告期: '2025-12-31', 公告日期: '2026-03-30', 基本每股收益: 10, 每股净资产: 20, EBITDA: 100000000, 净负债: 10000000, 总股本: 1000000 }, { 报告期: '2024-12-31', 公告日期: '2025-03-30', 基本每股收益: 8, 每股净资产: 18, EBITDA: 90000000, 净负债: 12000000, 总股本: 1000000 }, { 报告期: '2025-09-30', 公告日期: '2025-11-01', 基本每股收益: 7 }] }
function marketRows(): readonly Dict[] { return [{ 日期: '2026-01-02', 收盘: 120 }, { 日期: '2026-09-08', 收盘: 150 }, { 日期: '2026-12-31', 收盘: 999 }] }
function akshareFixture(options: { readonly financial?: readonly Dict[]; readonly market?: readonly Dict[] } = {}): AkshareDataClient & { readonly calls: string[] } { const calls: string[] = []; return { calls, companyBasic: async () => { calls.push('companyBasic'); return [{ 公司名称: 'Fixture Company' }] }, financialData: async () => { calls.push('financialData'); return options.financial ?? financialRows() }, historicalMarketData: async () => { calls.push('historicalMarketData'); return options.market ?? marketRows() } } }
async function fixture(options: { readonly financial?: readonly Dict[]; readonly market?: readonly Dict[]; readonly executor?: ReasoningExecutor } = {}) {
  const root = await mkdtemp(join(tmpdir(), 'rhl-valuation-')); const reports = join(root, 'reports'); await createFreshKnowledgeBaseV04(root, { knowledgeBaseId: `kb-valuation-${Date.now()}`, now: NOW }); const registry = new KnowledgeBaseRegistry(); let handle = await registry.mount(root)
  const content = 'Seed coverage evidence for an existing canonical company.'; const seedSource = { candidate: { candidateId: 'seed-source', kind: 'official_disclosure' as const, tier: 1 as const, title: 'Seed coverage', provider: 'fixture', publishedAt: '2026-01-01T00:00:00.000Z', metadata: { companySymbol: '600519' } }, retrievedAt: NOW, title: 'Seed coverage', content, rawBytes: new TextEncoder().encode(content), contentHash: 'a'.repeat(64), publisher: 'Fixture', rights: RIGHTS }
  const seeded = await new KnowledgeProductionGateway(registry).submit({ handle, producerType: 'fixture_seed', producerRunId: `seed-${Date.now()}-${Math.random().toString(16).slice(2)}`, schemaProfile: { schemaVersion: '0.4', storageFormatVersion: '1', requiresRawProvenance: true }, entity: { localKey: 'company', entityType: 'company', name: 'Fixture Company', aliases: ['600519'], semanticFields: { ticker: '600519', exchange: 'SH' } }, proposals: [{ proposalId: 'seed-assumption', kind: 'claim', claimType: 'assumption', subjectKey: 'company', statement: 'Seed assumption.', sourceCandidateIds: ['seed-source'] }, { proposalId: 'seed-thesis', kind: 'claim', claimType: 'thesis', subjectKey: 'company', statement: 'Seed thesis.', sourceCandidateIds: ['seed-source'] }], evidenceBindings: [{ localSourceId: 'seed-source', source: seedSource }], asOf: NOW, now: () => NOW })
  assert.equal(seeded.status, 'committed'); handle = await registry.mount(root)
  const akshare = akshareFixture({ financial: options.financial, market: options.market }); const executor = options.executor ?? new FixtureExecutor()
  return { root, reports, handle, akshare, executor, async remount() { handle = await registry.mount(root); return handle }, async close() { await rm(root, { recursive: true, force: true }) } }
}
async function runFixture(f: Awaited<ReturnType<typeof fixture>>, overrides: Partial<Parameters<typeof runValuation>[0]> = {}) { return runValuation({ workflowRunId: `valuation-${Date.now()}-${Math.random().toString(16).slice(2)}`, handle: f.handle, company: { symbol: '600519', name: 'Fixture Company', exchange: 'SSE' }, reportRoot: f.reports, akshare: f.akshare, reasoningExecutor: f.executor, now: () => NOW, ...overrides }) }
function fixtureExecutor(f: Awaited<ReturnType<typeof fixture>>): FixtureExecutor { return f.executor as FixtureExecutor }
function basis() { const market = normalizeValuationMarketData(marketRows(), NOW).observation!; const row = normalizeValuationFinancialData(financialRows()).rows[0]!; return buildValuationBasis(market, row, NOW, 'verified') }
function plan() { return { primaryMethod: 'PE' as const, secondaryMethods: ['PB' as const], targetFiscalYear: 2026, scenarios: [{ scenarioId: 'bear' as const, primaryMethod: 'PE' as const, targetFiscalYear: 2026, growthRate: 0.05, targetMultiple: 10, rationale: 'bear', sourceCandidateIds: ['s'], existingKnowledgeRefs: [] }, { scenarioId: 'base' as const, primaryMethod: 'PE' as const, targetFiscalYear: 2026, growthRate: 0.1, targetMultiple: 12, rationale: 'base', sourceCandidateIds: ['s'], existingKnowledgeRefs: [] }, { scenarioId: 'bull' as const, primaryMethod: 'PE' as const, targetFiscalYear: 2026, growthRate: 0.2, targetMultiple: 14, rationale: 'bull', sourceCandidateIds: ['s'], existingKnowledgeRefs: [] }] } }

test('V1 normalizes dashed dates', () => assert.equal(normalizeValuationMarketData([{ date: '2026-09-08', close: 1 }], NOW).observation?.priceDate, '2026-09-08'))
test('V2 normalizes Chinese dates', () => assert.equal(normalizeValuationMarketData([{ date: '2026年9月8日', close: 1 }], NOW).observation?.priceDate, '2026-09-08'))
test('V3 selects the latest usable market close', () => assert.equal(normalizeValuationMarketData(marketRows(), NOW).observation?.close, 150))
test('V4 excludes future market rows', () => assert.equal(normalizeValuationMarketData([{ 日期: '2026-12-31', 收盘: 999 }], NOW).observation, undefined))
test('V5 rejects non-positive market closes', () => assert.equal(normalizeValuationMarketData([{ 日期: '2026-09-08', 收盘: 0 }], NOW).observation, undefined))
test('V6 keeps annual December 31 rows', () => assert.equal(normalizeValuationFinancialData(financialRows()).rows.length, 2))
test('V7 excludes Q1 H1 Q3 rows from the FY basis', () => assert.equal(normalizeValuationFinancialData([{ 报告期: '2025-09-30', 基本每股收益: 1 }]).rows.length, 0))
test('V8 sorts annual basis rows newest first', () => assert.equal(normalizeValuationFinancialData(financialRows()).rows[0]?.basisFiscalYear, 2025))
test('V9 parses publication dates', () => assert.equal(normalizeValuationFinancialData(financialRows()).rows[0]?.publicationDate, '2026-03-30'))
test('V10 explicit asOf selects a published basis', () => assert.equal(selectValuationBasis(normalizeValuationFinancialData(financialRows()).rows, '2026-09-09', '2026-09-09').pointInTimeVerified, true))
test('V11 explicit asOf rejects missing publication dates', () => assert.equal(selectValuationBasis(normalizeValuationFinancialData([{ 报告期: '2025-12-31', 基本每股收益: 1 }]).rows, NOW, NOW).basis, undefined))
test('V12 explicit asOf rejects future publication dates', () => assert.equal(selectValuationBasis(normalizeValuationFinancialData([{ 报告期: '2025-12-31', 公告日期: '2026-10-01', 基本每股收益: 1 }]).rows, NOW, NOW).basis, undefined))
test('V13 current snapshot records unverified publication status when needed', () => assert.equal(selectValuationBasis(normalizeValuationFinancialData([{ 报告期: '2025-12-31', 基本每股收益: 1 }]).rows, NOW).publicationStatus, 'current_snapshot_unverified'))
test('V14 basis carries explicit units', () => assert.equal(basis().units.marketPrice, 'CNY/share'))
test('V15 PE eligibility requires positive EPS', () => assert.equal(methodEligibility(basis()).find((item) => item.method === 'PE')?.eligible, true))
test('V16 PB eligibility requires positive BVPS', () => assert.equal(methodEligibility(basis()).find((item) => item.method === 'PB')?.eligible, true))
test('V17 EV EBITDA eligibility requires finite net debt and shares', () => assert.equal(methodEligibility(basis()).find((item) => item.method === 'EV_EBITDA')?.eligible, true))
test('V18 computes PE reference multiple in code', () => assert.equal(referenceMultiples(basis()).PE, 15))
test('V19 computes PB reference multiple in code', () => assert.equal(referenceMultiples(basis()).PB, 7.5))
test('V20 computes EV EBITDA reference multiple in code', () => assert.equal(referenceMultiples(basis()).EV_EBITDA, 1.6))
test('V21 computes one-period PE target price', () => assert.equal(calculateTargetPrice(basis(), 'PE', 2026, 0.1, 12).targetPrice, 132))
test('V22 computes one-period PB target price', () => assert.equal(calculateTargetPrice(basis(), 'PB', 2026, 0.1, 8).targetPrice, 176))
test('V23 computes one-period EV EBITDA target price', () => assert.equal(calculateTargetPrice(basis(), 'EV_EBITDA', 2026, 0.1, 2).targetPrice, 210.00000000000003))
test('V24 permits bounded negative growth above minus one', () => assert.equal(calculateTargetPrice(basis(), 'PE', 2026, -0.1, 10).targetPrice, 90))
test('V25 rejects a target year at or before the basis year', () => assert.throws(() => calculateTargetPrice(basis(), 'PE', 2025, 0.1, 10)))
test('V26 requires exactly Bear Base Bull', () => assert.ok(validateScenarioAssumptions(plan(), ['PE', 'PB'], 2025).length === 0))
test('V27 rejects non-monotonic assumptions', () => assert.ok(validateScenarioAssumptions({ ...plan(), scenarios: plan().scenarios.map((item) => item.scenarioId === 'base' ? { ...item, targetMultiple: 9 } : item) }, ['PE'], 2025).some((item) => item.includes('monotonic'))))
test('V28 calculates nine sensitivity cells', () => assert.equal(calculateValuation(basis(), plan(), ['PE', 'PB']).sensitivity.length, 9))
test('V29 deterministically recomputes scenario outputs', () => assert.equal(calculateValuation(basis(), plan(), ['PE', 'PB']).deterministicRecomputeMatched, true))
test('V30 workflow defaults target fiscal year to basis plus one', async () => { const f = await fixture(); try { const r = await runFixture(f); assert.equal(r.plan?.targetFiscalYear, 2026) } finally { await f.close() } })
test('V31 allows target fiscal year at basis plus three', () => assert.doesNotThrow(() => calculateValuation(basis(), { ...plan(), targetFiscalYear: 2028, scenarios: plan().scenarios.map((item) => ({ ...item, targetFiscalYear: 2028 })) }, ['PE'])))
test('V32 rejects target fiscal year beyond basis plus three', async () => { const f = await fixture(); try { const r = await runFixture(f, { targetFiscalYear: 2029 }); assert.equal(r.status, 'blocked'); assert.equal(r.blockedReason, 'VALUATION_TARGET_FISCAL_YEAR_INVALID') } finally { await f.close() } })
test('V33 filters requested methods to eligible methods', async () => { const f = await fixture(); try { const r = await runFixture(f, { methods: ['PB'] }); assert.deepEqual(r.telemetry.eligibleMethods, ['PB']) } finally { await f.close() } })
test('V34 keeps the method set bounded to PE PB EV_EBITDA', () => assert.deepEqual(methodEligibility(basis()).map((item) => item.method), ['PE', 'PB', 'EV_EBITDA']))
test('V35 completes with one exact canonical Company', async () => { const f = await fixture(); try { const r = await runFixture(f); assert.equal(r.status, 'completed'); assert.equal(r.telemetry.companyCoverageResolved, true) } finally { await f.close() } })
test('V36 missing Company coverage blocks before acquisition', async () => { const root = await mkdtemp(join(tmpdir(), 'rhl-valuation-missing-')); try { await createFreshKnowledgeBaseV04(root, { knowledgeBaseId: 'missing', now: NOW }); let calls = 0; const ak = akshareFixture(); const wrapped = { ...ak, companyBasic: async () => { calls++; return [] } }; const r = await runValuation({ workflowRunId: 'v36', handle: await new KnowledgeBaseRegistry().mount(root), company: { symbol: '600519', exchange: 'SSE' }, reportRoot: join(root, 'reports'), akshare: wrapped }); assert.equal(r.blockedReason, 'COMPANY_COVERAGE_NOT_FOUND'); assert.equal(calls, 0) } finally { await rm(root, { recursive: true, force: true }) } })
test('V37 ambiguous exact Company coverage blocks', async () => { const f = await fixture(); try { const assets = JSON.parse(await readFile(join(f.root, 'registry', 'assets.yaml'), 'utf8')) as Dict; assets['entity:duplicate-company'] = { type: 'entity', storageRef: 'entities/duplicate-company.yaml' }; await writeFile(join(f.root, 'registry', 'assets.yaml'), `${JSON.stringify(assets)}\n`); await writeFile(join(f.root, 'entities', 'duplicate-company.yaml'), `${JSON.stringify({ id: 'entity:duplicate-company', type: 'company', name: 'Duplicate', aliases: [], ticker: '600519', exchange: 'SH', lifecycle: { status: 'active' } })}\n`); const r = await runFixture({ ...f, handle: await new KnowledgeBaseRegistry().mount(f.root) }); assert.equal(r.blockedReason, 'COMPANY_COVERAGE_AMBIGUOUS') } finally { await f.close() } })
test('V38 unavailable market data blocks', async () => { const f = await fixture({ market: [] }); try { const r = await runFixture(f); assert.equal(r.blockedReason, 'VALUATION_MARKET_PRICE_UNAVAILABLE') } finally { await f.close() } })
test('V39 acquisition calls all three AKShare methods', async () => { const f = await fixture(); try { await runFixture(f); assert.deepEqual(f.akshare.calls, ['companyBasic', 'financialData', 'historicalMarketData']) } finally { await f.close() } })
test('V40 writes a valuation ResearchReport', async () => { const f = await fixture(); try { const r = await runFixture(f); const report = JSON.parse(await readFile(join(f.reports, `${r.report?.reportId}.md.json`), 'utf8')) as Dict; assert.equal(report.reportType, 'valuation') } finally { await f.close() } })
test('V41 uses exactly sixteen fixed report sections', async () => { const f = await fixture(); try { const r = await runFixture(f); const report = JSON.parse(await readFile(join(f.reports, `${r.report?.reportId}.md.json`), 'utf8')) as { sections: readonly { title: string }[] }; assert.deepEqual(report.sections.map((item) => item.title), [...VALUATION_REPORT_SECTIONS]) } finally { await f.close() } })
test('V42 states consensus is unavailable', async () => { const f = await fixture(); try { const r = await runFixture(f); const report = await readFile(join(f.reports, `${r.report?.reportId}.md`), 'utf8'); assert.match(report, /Consensus unavailable/) } finally { await f.close() } })
test('V43 states DCF is deferred in v1', async () => { const f = await fixture(); try { const r = await runFixture(f); const report = await readFile(join(f.reports, `${r.report?.reportId}.md`), 'utf8'); assert.match(report, /DCF: Unavailable \/ deferred in v1/) } finally { await f.close() } })
test('V44 calls Stage A assumption design', async () => { const f = await fixture(); try { await runFixture(f); assert.ok(fixtureExecutor(f).requests.some((request) => request.operation === 'valuation_assumption_design')) } finally { await f.close() } })
test('V45 Stage A selects one primary method', async () => { const f = await fixture(); try { const r = await runFixture(f); assert.equal(r.plan?.primaryMethod, 'PE') } finally { await f.close() } })
test('V46 calls Stage B synthesis after computation', async () => { const f = await fixture(); try { await runFixture(f); assert.ok(fixtureExecutor(f).requests.some((request) => request.operation === 'valuation_synthesis')) } finally { await f.close() } })
test('V47 reasoning receives bounded source IDs', async () => { const f = await fixture(); try { await runFixture(f); const request = fixtureExecutor(f).requests.find((item) => item.operation === 'valuation_assumption_design')!; assert.equal(((request.input as Dict).allowedSourceCandidateIds as string[]).length, 3) } finally { await f.close() } })
test('V48 viewpoint proposal passes the durable gate', async () => { const f = await fixture(); try { const r = await runFixture(f); assert.equal(r.telemetry.acceptedProposalCount, 1); assert.equal(r.claimIds.length, 1) } finally { await f.close() } })
test('V49 durable proposals are company scoped', async () => { const f = await fixture(); try { const r = await runFixture(f); const assets = await readCanonicalV04Assets(f.root); const claim = assets.objects.find((item) => item.value.id === r.claimIds[0])!; const company = assets.objects.find((item) => item.kind === 'entity' && (item.value as unknown as Dict).ticker === '600519')!; assert.deepEqual((claim.value as unknown as Dict).subjectRefs, [company.value.id]) } finally { await f.close() } })
test('V50 proposal count is bounded at three', async () => { const f = await fixture(); try { const r = await runFixture(f); assert.ok(r.proposalIds.length <= 3) } finally { await f.close() } })
test('V51 report section refs are canonical Gateway refs', async () => { const f = await fixture(); try { const r = await runFixture(f); const report = JSON.parse(await readFile(join(f.reports, `${r.report?.reportId}.md.json`), 'utf8')) as { sections: readonly { sourceRefs: readonly string[] }[] }; assert.ok(report.sections.every((section) => section.sourceRefs.every((ref) => ref.startsWith('source:')))) } finally { await f.close() } })
test('V52 canonical claims remain attached to the existing Company', async () => { const f = await fixture(); try { const r = await runFixture(f); const assets = await readCanonicalV04Assets(f.root); const company = assets.objects.find((item) => item.kind === 'entity' && (item.value as unknown as Dict).ticker === '600519'); assert.ok(company); assert.ok(r.claimIds.every((id) => ((assets.objects.find((item) => item.value.id === id)?.value as unknown as Dict | undefined)?.subjectRefs as string[] | undefined)?.includes(company.value.id))) } finally { await f.close() } })
test('V53 replay is idempotent for the same workflow run', async () => { const f = await fixture(); try { const input = { workflowRunId: 'v53-replay', handle: f.handle, company: { symbol: '600519', exchange: 'SSE' as const }, reportRoot: f.reports, akshare: f.akshare, reasoningExecutor: f.executor, now: () => NOW }; const first = await runValuation(input); await f.remount(); const second = await runValuation({ ...input, handle: f.handle }); assert.equal(first.status, 'completed'); assert.equal(second.status, 'completed'); const assets = await readCanonicalV04Assets(f.root); assert.equal(assets.objects.filter((item) => item.kind === 'entity' && (item.value as unknown as Dict).type === 'company').length, 1) } finally { await f.close() } })
test('V54 telemetry records deterministic computation and persistence counts', async () => { const f = await fixture(); try { const r = await runFixture(f); assert.equal(r.telemetry.computation.sensitivityCellCount, 9); assert.equal(r.telemetry.computation.deterministicRecomputeStatus, 'matched'); assert.equal(r.telemetry.canonicalClaimCount, 1) } finally { await f.close() } })
test('V55 cancellation is respected before coverage acquisition', async () => { const f = await fixture(); try { const controller = new AbortController(); controller.abort(); const r = await runFixture(f, { signal: controller.signal }); assert.equal(r.status, 'cancelled') } finally { await f.close() } })
test('V56 future asOf is rejected', async () => { const f = await fixture(); try { const r = await runFixture(f, { asOf: '2026-09-10T00:00:00.000Z' }); assert.equal(r.blockedReason, 'VALUATION_ASOF_IN_FUTURE') } finally { await f.close() } })
test('V57 ResearchService registers valuation workflow type', async () => { const f = await fixture(); try { const workflows = new WorkflowService(); const service = new ResearchService({ mountedKnowledgeBaseRoot: f.root, reportRoot: f.reports, acquisitionPlugins: [], akshare: f.akshare, workflowService: workflows, reasoningExecutor: f.executor }); const started = service.startValuation({ workflowRunId: 'v57-service', symbol: '600519', exchange: 'SSE' }); assert.equal(workflows.getWorkflowStatus(started.runId)?.workflowType, 'valuation'); assert.equal((await started.completion).status, 'completed') } finally { await f.close() } })
test('V58 runtime exposes the production valuation route', async () => { const source = await readFile('app/runtime/server.ts', 'utf8'); assert.match(source, /\/api\/production\/analyze-valuation/) })
test('V59 reasoning operations include both valuation stages', async () => { const source = await readFile('plugins/reasoning/contracts.ts', 'utf8'); assert.match(source, /valuation_assumption_design/); assert.match(source, /valuation_synthesis/) })
test('V60 Pi tool exposes analyze_valuation', async () => { const source = await readFile('app/pi/tools.ts', 'utf8'); assert.match(source, /analyze_valuation/) })
test('V61 model cannot be the arithmetic authority', async () => { const source = await readFile('skills/valuation/skill.ts', 'utf8'); assert.match(source, /Do not return targetPrice/); assert.match(source, /deterministic/) })
test('V62 valuation does not create a canonical Valuation object', async () => { const f = await fixture(); try { await runFixture(f); const assets = await readCanonicalV04Assets(f.root); assert.equal(assets.objects.some((item) => (item.value as unknown as Dict).type === 'valuation'), false) } finally { await f.close() } })
test('V63 report contains the three scenario sections and sensitivity', async () => { const f = await fixture(); try { const r = await runFixture(f); const report = await readFile(join(f.reports, `${r.report?.reportId}.md`), 'utf8'); for (const title of ['Bear Scenario', 'Base Scenario', 'Bull Scenario', 'Sensitivity Analysis']) assert.match(report, new RegExp(title)); } finally { await f.close() } })
