import type { DocumentContentRef, EntityCandidate, ExtractKnowledgeInput, CandidateEntityRef, RelationCandidate, ClaimCandidate, ValidatedExtractKnowledgeResult, CandidateKind, CandidateValidationCode, CandidateValidationRejection, UnderstandAndPlanOutput, ReconcileKnowledgeInput, ReconcileKnowledgeOutput, ReconciliationAction } from './contracts.ts'
import { KnowledgeCurationError } from './errors.ts'
import { blockIdsForRef } from './model-input.ts'
import type { CurationSchemaContext } from './schema-context-types.ts'

type RecordValue = Record<string, unknown>
const ACTIONS: readonly ReconciliationAction[] = ['create', 'duplicate', 'merge_source', 'update_state', 'supersede', 'keep_both', 'reject', 'user_review']
const TRUSTED_KEYS = new Set(['id', 'entityId', 'relationId', 'claimId', 'sourceRef', 'sourceRefs', 'rawRef', 'rawRefs', 'registryPath', 'revision', 'storageRef', 'workflowRunId', 'changeSetId', 'knowledgeBaseId'])

function fail(code: KnowledgeCurationError['code'], message: string): never { throw new KnowledgeCurationError(code, message) }
function record(value: unknown, label: string): RecordValue { if (!value || typeof value !== 'object' || Array.isArray(value)) fail('invalid_model_output', `${label} must be an object`); return value as RecordValue }
function list(value: unknown, label: string): unknown[] { if (!Array.isArray(value)) fail('invalid_model_output', `${label} must be an array`); return value }
function text(value: unknown, label: string): string { if (typeof value !== 'string' || value.trim() === '') fail('invalid_model_output', `${label} must be a non-empty string`); return value.trim() }
function optionalText(value: unknown, label: string): string | undefined { return value === undefined ? undefined : text(value, label) }
function exact(value: RecordValue, allowed: readonly string[], label: string): void { const keys = new Set(allowed); for (const key of Object.keys(value)) if (!keys.has(key)) fail('invalid_model_output', `${label} contains unsupported field ${key}`) }
function enumText<T extends readonly string[]>(value: unknown, values: T, label: string): T[number] { const item = text(value, label); if (!values.includes(item)) fail('invalid_semantics', `${label} is outside the Schema 0.3 vocabulary`); return item as T[number] }
function confidence(value: unknown, label: string): number { if (typeof value !== 'number' || !Number.isFinite(value)) fail('invalid_confidence', `${label} must be finite`); if (value < 0 || value > 1) fail('invalid_confidence', `${label} must be between 0 and 1`); return value }
function strings(value: unknown, label: string): string[] { return list(value, label).map((item, index) => text(item, `${label}[${index}]`)) }
function jsonValue(value: unknown): boolean { if (value === null || typeof value === 'string' || typeof value === 'boolean') return true; if (typeof value === 'number') return Number.isFinite(value); if (Array.isArray(value)) return value.every(jsonValue); return typeof value === 'object' && value !== null && Object.values(value).every(jsonValue) }
function rejectTrusted(value: unknown, path: string): void { if (!value || typeof value !== 'object') return; if (Array.isArray(value)) { value.forEach((item, index) => rejectTrusted(item, `${path}[${index}]`)); return } for (const [key, child] of Object.entries(value)) { if (TRUSTED_KEYS.has(key)) fail('invalid_reference', `${path}.${key} is trusted Workflow or storage data`); rejectTrusted(child, `${path}.${key}`) } }
function unitBlockSets(input: ExtractKnowledgeInput): { all: Set<string>; primary: Set<string> } {
  return { all: new Set([...input.unit.primaryRefs, ...input.unit.contextRefs].flatMap((ref) => blockIdsForRef(input.document, ref))), primary: new Set(input.unit.primaryRefs.flatMap((ref) => blockIdsForRef(input.document, ref))) }
}
function validateRef(value: unknown, document: ExtractKnowledgeInput['document'], label: string): DocumentContentRef {
  const ref = record(value, label); exact(ref, ['kind', 'blockId', 'sectionId'], label); const kind = enumText(ref.kind, ['block', 'section'] as const, `${label}.kind`)
  if (kind === 'block') { const id = text(ref.blockId, `${label}.blockId`); if (!document.blocks.some((block) => block.blockId === id)) fail('invalid_reference', `${label} points outside the document`); if (ref.sectionId !== undefined) fail('invalid_model_output', `${label}.sectionId is not allowed for block refs`); return { kind, blockId: id } }
  const id = text(ref.sectionId, `${label}.sectionId`); if (!document.sections.some((section) => section.sectionId === id)) fail('invalid_reference', `${label} points outside the document`); if (ref.blockId !== undefined) fail('invalid_model_output', `${label}.blockId is not allowed for section refs`); return { kind, sectionId: id }
}
function validateRefs(value: unknown, document: ExtractKnowledgeInput['document'], label: string, required = false): DocumentContentRef[] { const refs = list(value, label).map((item, index) => validateRef(item, document, `${label}[${index}]`)); const keys = refs.map((ref) => `${ref.kind}:${ref.kind === 'block' ? ref.blockId : ref.sectionId}`); if (new Set(keys).size !== keys.length) fail('invalid_reference', `${label} contains duplicate references`); if (required && refs.length === 0) fail('invalid_reference', `${label} must not be empty`); return refs }

export function validateUnderstandAndPlanOutput(value: unknown, input: { document: ExtractKnowledgeInput['document']; schemaContext: CurationSchemaContext }): UnderstandAndPlanOutput {
  const root = record(value, 'UnderstandAndPlan output'); exact(root, ['reportMap', 'extractionPlanProposal'], 'UnderstandAndPlan output')
  const report = record(root.reportMap, 'reportMap'); exact(report, ['sourceAssessment', 'researchScope', 'majorTopics', 'majorEntityMentions', 'majorConclusions', 'sectionSemantics', 'semanticDependencies', 'themeHypotheses', 'uncertainty'], 'reportMap')
  const source = record(report.sourceAssessment, 'reportMap.sourceAssessment'); exact(source, ['summary', 'sourceType', 'reliability', 'uncertainty'], 'sourceAssessment'); const sourceAssessment = { summary: text(source.summary, 'sourceAssessment.summary'), ...(source.sourceType === undefined ? {} : { sourceType: enumText(source.sourceType, input.schemaContext.sourceTypes, 'sourceAssessment.sourceType') }), ...(source.reliability === undefined ? {} : { reliability: enumText(source.reliability, ['high', 'medium', 'low', 'unknown'] as const, 'sourceAssessment.reliability') }), ...(source.uncertainty === undefined ? {} : { uncertainty: strings(source.uncertainty, 'sourceAssessment.uncertainty') }) }
  const makeEvidenceItems = (value: unknown, label: string) => list(value, label).map((item, index) => { const itemRecord = record(item, `${label}[${index}]`); return itemRecord })
  const majorTopics = makeEvidenceItems(report.majorTopics, 'reportMap.majorTopics').map((item, index) => { exact(item, ['topicId', 'label', 'description', 'evidenceRefs'], `majorTopics[${index}]`); return { topicId: text(item.topicId, `majorTopics[${index}].topicId`), label: text(item.label, `majorTopics[${index}].label`), ...(item.description === undefined ? {} : { description: text(item.description, `majorTopics[${index}].description`) }), evidenceRefs: validateRefs(item.evidenceRefs, input.document, `majorTopics[${index}].evidenceRefs`, true) } })
  const majorEntityMentions = makeEvidenceItems(report.majorEntityMentions, 'reportMap.majorEntityMentions').map((item, index) => { exact(item, ['mentionId', 'text', 'entityType', 'evidenceRefs'], `majorEntityMentions[${index}]`); return { mentionId: text(item.mentionId, `majorEntityMentions[${index}].mentionId`), text: text(item.text, `majorEntityMentions[${index}].text`), ...(item.entityType === undefined ? {} : { entityType: enumText(item.entityType, input.schemaContext.entityTypes, `majorEntityMentions[${index}].entityType`) }), evidenceRefs: validateRefs(item.evidenceRefs, input.document, `majorEntityMentions[${index}].evidenceRefs`, true) } })
  const majorConclusions = makeEvidenceItems(report.majorConclusions, 'reportMap.majorConclusions').map((item, index) => { exact(item, ['conclusionId', 'text', 'evidenceRefs'], `majorConclusions[${index}]`); return { conclusionId: text(item.conclusionId, `majorConclusions[${index}].conclusionId`), text: text(item.text, `majorConclusions[${index}].text`), evidenceRefs: validateRefs(item.evidenceRefs, input.document, `majorConclusions[${index}].evidenceRefs`, true) } })
  const sectionSemantics = makeEvidenceItems(report.sectionSemantics, 'reportMap.sectionSemantics').map((item, index) => { exact(item, ['sectionRef', 'summary', 'topicRefs', 'evidenceRefs'], `sectionSemantics[${index}]`); const sectionRef = text(item.sectionRef, `sectionSemantics[${index}].sectionRef`); if (!input.document.sections.some((section) => section.sectionId === sectionRef)) fail('invalid_reference', `sectionSemantics[${index}].sectionRef is unknown`); return { sectionRef, summary: text(item.summary, `sectionSemantics[${index}].summary`), ...(item.topicRefs === undefined ? {} : { topicRefs: strings(item.topicRefs, `sectionSemantics[${index}].topicRefs`) }), ...(item.evidenceRefs === undefined ? {} : { evidenceRefs: validateRefs(item.evidenceRefs, input.document, `sectionSemantics[${index}].evidenceRefs`) }) } })
  const semanticDependencies = makeEvidenceItems(report.semanticDependencies, 'reportMap.semanticDependencies').map((item, index) => { exact(item, ['fromSectionRef', 'toSectionRef', 'reason'], `semanticDependencies[${index}]`); const from = text(item.fromSectionRef, `semanticDependencies[${index}].fromSectionRef`); const to = text(item.toSectionRef, `semanticDependencies[${index}].toSectionRef`); if (!input.document.sections.some((section) => section.sectionId === from) || !input.document.sections.some((section) => section.sectionId === to)) fail('invalid_reference', `semanticDependencies[${index}] has an unknown section`); return { fromSectionRef: from, toSectionRef: to, reason: text(item.reason, `semanticDependencies[${index}].reason`) } })
  const themeHypotheses = makeEvidenceItems(report.themeHypotheses, 'reportMap.themeHypotheses').map((item, index) => { exact(item, ['text', 'evidenceRefs'], `themeHypotheses[${index}]`); return { text: text(item.text, `themeHypotheses[${index}].text`), evidenceRefs: validateRefs(item.evidenceRefs, input.document, `themeHypotheses[${index}].evidenceRefs`, true) } })
  const plan = record(root.extractionPlanProposal, 'extractionPlanProposal'); exact(plan, ['units', 'excludedRefs'], 'extractionPlanProposal'); const units = list(plan.units, 'extractionPlanProposal.units').map((item, index) => { const unit = record(item, `units[${index}]`); exact(unit, ['proposedUnitId', 'topic', 'semanticPurpose', 'primaryRefs', 'contextRefs', 'extractionFocus'], `units[${index}]`); const primaryRefs = validateRefs(unit.primaryRefs, input.document, `units[${index}].primaryRefs`, true); const contextRefs = validateRefs(unit.contextRefs, input.document, `units[${index}].contextRefs`); const primaryKeys = new Set(primaryRefs.map((ref) => `${ref.kind}:${ref.kind === 'block' ? ref.blockId : ref.sectionId}`)); if (contextRefs.some((ref) => primaryKeys.has(`${ref.kind}:${ref.kind === 'block' ? ref.blockId : ref.sectionId}`))) fail('invalid_reference', `units[${index}] repeats a reference in primaryRefs and contextRefs`); return { proposedUnitId: text(unit.proposedUnitId, `units[${index}].proposedUnitId`), topic: text(unit.topic, `units[${index}].topic`), semanticPurpose: text(unit.semanticPurpose, `units[${index}].semanticPurpose`), primaryRefs, contextRefs, ...(unit.extractionFocus === undefined ? {} : { extractionFocus: text(unit.extractionFocus, `units[${index}].extractionFocus`) }) } })
  if (new Set(units.map((unit) => unit.proposedUnitId)).size !== units.length) fail('invalid_model_output', 'proposedUnitId values must be unique')
  const normalizedPlan = { units, ...(plan.excludedRefs === undefined ? {} : { excludedRefs: validateRefs(plan.excludedRefs, input.document, 'extractionPlanProposal.excludedRefs') }) }
  return { reportMap: { sourceAssessment, researchScope: text(report.researchScope, 'reportMap.researchScope'), majorTopics, majorEntityMentions, majorConclusions, sectionSemantics, semanticDependencies, themeHypotheses, uncertainty: strings(report.uncertainty, 'reportMap.uncertainty') }, extractionPlanProposal: normalizedPlan }
}

function candidateId(value: unknown, label: string): string { const id = text(value, label); if (/^(entity|relation|claim|source|module|theme-group):/i.test(id)) fail('invalid_reference', `${label} must be a local candidate reference`); return id }
function candidateRef(value: unknown, label: string, entities: ReadonlyMap<string, EntityCandidate>): CandidateEntityRef { const item = record(value, label); exact(item, ['candidateRef', 'mention', 'entityType'], label); const ref = candidateId(item.candidateRef, `${label}.candidateRef`); const entity = entities.get(ref); if (!entity) fail('invalid_reference', `${label} references an unavailable EntityCandidate`); const mention = text(item.mention, `${label}.mention`); if (item.entityType !== undefined && item.entityType !== entity.entityType) fail('invalid_semantics', `${label}.entityType disagrees with the referenced EntityCandidate`); return { candidateRef: ref, mention, ...(item.entityType === undefined ? {} : { entityType: item.entityType as EntityCandidate['entityType'] }) } }
function evidence(value: unknown, label: string, input: ExtractKnowledgeInput): string[] { const ids = strings(value, label); const { all, primary } = unitBlockSets(input); for (const id of ids) if (!all.has(id)) fail('invalid_reference', `${label} contains a block not supplied to this extraction unit`); if (!ids.some((id) => primary.has(id))) fail('ungrounded_candidate', `${label} must include a primary-grounded block`); if (new Set(ids).size !== ids.length) fail('invalid_reference', `${label} contains duplicate block references`); return ids }
function capture<T>(kind: CandidateKind, raw: unknown, validate: () => T, rejected: CandidateValidationRejection[]): T | undefined { try { return validate() } catch (error) { if (!(error instanceof KnowledgeCurationError)) throw error; const item = raw as RecordValue; rejected.push({ candidateId: typeof item?.candidateId === 'string' ? item.candidateId : undefined, kind, code: error.code as CandidateValidationCode, message: error.message }); return undefined } }

export function validateExtractKnowledge(value: unknown, input: ExtractKnowledgeInput): ValidatedExtractKnowledgeResult {
  const root = record(value, 'ExtractKnowledge output'); exact(root, ['entities', 'relations', 'claims'], 'ExtractKnowledge output'); rejectTrusted(root, 'ExtractKnowledge output')
  const rejected: CandidateValidationRejection[] = []; const entities = new Map<string, EntityCandidate>(); const entityList: EntityCandidate[] = []
  for (const [index, raw] of list(root.entities, 'entities').entries()) { const accepted = capture('entity', raw, () => { const item = record(raw, `entities[${index}]`); exact(item, ['candidateId', 'entityType', 'name', 'aliases', 'description', 'semanticFields', 'evidenceBlockRefs', 'reason', 'confidence'], `entities[${index}]`); const id = candidateId(item.candidateId, `entities[${index}].candidateId`); if (entities.has(id)) fail('invalid_reference', `duplicate EntityCandidate id ${id}`); const result: EntityCandidate = { candidateId: id, entityType: enumText(item.entityType, input.schemaContext.entityTypes, `entities[${index}].entityType`), name: text(item.name, `entities[${index}].name`), ...(item.aliases === undefined ? {} : { aliases: strings(item.aliases, `entities[${index}].aliases`) }), ...(item.description === undefined ? {} : { description: item.description === null ? null : text(item.description, `entities[${index}].description`) }), ...(item.semanticFields === undefined ? {} : { semanticFields: record(item.semanticFields, `entities[${index}].semanticFields`) }), evidenceBlockRefs: evidence(item.evidenceBlockRefs, `entities[${index}].evidenceBlockRefs`, input), reason: text(item.reason, `entities[${index}].reason`), ...(item.confidence === undefined ? {} : { confidence: confidence(item.confidence, `entities[${index}].confidence`) }) }; if (result.semanticFields !== undefined && !jsonValue(result.semanticFields)) fail('invalid_model_output', `entities[${index}].semanticFields must be JSON`) ; entities.set(id, result); return result }, rejected); if (accepted) entityList.push(accepted) }
  const relations: RelationCandidate[] = []; const relationIds = new Set<string>()
  for (const [index, raw] of list(root.relations, 'relations').entries()) { const accepted = capture('relation', raw, () => { const item = record(raw, `relations[${index}]`); exact(item, ['candidateId', 'relationType', 'source', 'target', 'attributes', 'evidenceBlockRefs', 'reason', 'confidence'], `relations[${index}]`); const id = candidateId(item.candidateId, `relations[${index}].candidateId`); if (relationIds.has(id)) fail('invalid_reference', `duplicate RelationCandidate id ${id}`); const relationType = enumText(item.relationType, input.schemaContext.relationTypes, `relations[${index}].relationType`); const contract = input.schemaContext.relationContracts.find((item) => item.relationType === relationType); if (!contract) fail('invalid_semantics', `no Schema 0.3 relation contract for ${relationType}`); const source = candidateRef(item.source, `relations[${index}].source`, entities); const target = candidateRef(item.target, `relations[${index}].target`, entities); if (!contract.allowedSourceTypes.includes(entities.get(source.candidateRef)!.entityType) || !contract.allowedTargetTypes.includes(entities.get(target.candidateRef)!.entityType)) fail('invalid_semantics', `${relationType} endpoint types are not allowed by the executable schema`); if (relationType === 'substitutes_for' && entities.get(source.candidateRef)!.entityType !== entities.get(target.candidateRef)!.entityType) fail('invalid_semantics', 'substitutes_for requires same-kind endpoints'); const result: RelationCandidate = { candidateId: id, relationType, source, target, ...(item.attributes === undefined ? {} : { attributes: record(item.attributes, `relations[${index}].attributes`) }), evidenceBlockRefs: evidence(item.evidenceBlockRefs, `relations[${index}].evidenceBlockRefs`, input), reason: text(item.reason, `relations[${index}].reason`), ...(item.confidence === undefined ? {} : { confidence: confidence(item.confidence, `relations[${index}].confidence`) }) }; if (result.attributes !== undefined && !jsonValue(result.attributes)) fail('invalid_model_output', `relations[${index}].attributes must be JSON`); relationIds.add(id); return result }, rejected); if (accepted) relations.push(accepted) }
  const claims: ClaimCandidate[] = []; const claimIds = new Set<string>()
  for (const [index, raw] of list(root.claims, 'claims').entries()) { const accepted = capture('claim', raw, () => { const item = record(raw, `claims[${index}]`); exact(item, ['candidateId', 'claimType', 'statement', 'subjectRefs', 'temporal', 'structuredValue', 'evidenceBlockRefs', 'reason', 'confidence'], `claims[${index}]`); const id = candidateId(item.candidateId, `claims[${index}].candidateId`); if (claimIds.has(id)) fail('invalid_reference', `duplicate ClaimCandidate id ${id}`); const subjects = list(item.subjectRefs, `claims[${index}].subjectRefs`); if (subjects.length === 0) fail('invalid_reference', `claims[${index}].subjectRefs must not be empty`); const temporal = item.temporal === undefined || item.temporal === null ? item.temporal : claimTemporal(item.temporal, input.schemaContext, `claims[${index}].temporal`); const structuredValue = item.structuredValue === undefined || item.structuredValue === null ? item.structuredValue : claimStructuredValue(item.structuredValue, input.schemaContext, `claims[${index}].structuredValue`); const result: ClaimCandidate = { candidateId: id, claimType: enumText(item.claimType, input.schemaContext.claimTypes, `claims[${index}].claimType`), statement: text(item.statement, `claims[${index}].statement`), subjectRefs: subjects.map((subject, subjectIndex) => candidateRef(subject, `claims[${index}].subjectRefs[${subjectIndex}]`, entities)), ...(temporal === undefined ? {} : { temporal }), ...(structuredValue === undefined ? {} : { structuredValue }), evidenceBlockRefs: evidence(item.evidenceBlockRefs, `claims[${index}].evidenceBlockRefs`, input), reason: text(item.reason, `claims[${index}].reason`), ...(item.confidence === undefined ? {} : { confidence: confidence(item.confidence, `claims[${index}].confidence`) }) }; claimIds.add(id); return result }, rejected); if (accepted) claims.push(accepted) }
  const counts = (items: readonly unknown[], kind: CandidateKind) => ({ input: items.length, accepted: kind === 'entity' ? entityList.length : kind === 'relation' ? relations.length : claims.length, rejected: rejected.filter((item) => item.kind === kind).length }); const entityCounts = counts(list(root.entities, 'entities'), 'entity'); const relationCounts = counts(list(root.relations, 'relations'), 'relation'); const claimCounts = counts(list(root.claims, 'claims'), 'claim')
  return { entities: entityList, relations, claims, rejected, summary: { inputCounts: { entity: entityCounts.input, relation: relationCounts.input, claim: claimCounts.input }, acceptedCounts: { entity: entityCounts.accepted, relation: relationCounts.accepted, claim: claimCounts.accepted }, rejectedCounts: { entity: entityCounts.rejected, relation: relationCounts.rejected, claim: claimCounts.rejected }, rejectionCodes: [...new Set(rejected.map((item) => item.code))] } }
}

export function validateReconcileKnowledge(value: unknown, input: ReconcileKnowledgeInput): ReconcileKnowledgeOutput {
  const root = record(value, 'ReconcileKnowledge output'); exact(root, ['decisions'], 'ReconcileKnowledge output'); rejectTrusted(root, 'ReconcileKnowledge output'); const decisions = list(root.decisions, 'decisions'); const supplied = new Set(input.candidateGroups.map((group) => group.candidateId)); const seen = new Set<string>(); const normalized = decisions.map((raw, index) => { const item = record(raw, `decisions[${index}]`); exact(item, ['candidateId', 'action', 'rationale', 'targetCandidateId', 'conflictingFields'], `decisions[${index}]`); const id = candidateId(item.candidateId, `decisions[${index}].candidateId`); if (!supplied.has(id)) fail('invalid_reference', `decision references an unknown candidate ${id}`); if (seen.has(id)) fail('reconciliation_invalid', `candidate ${id} has more than one decision`); seen.add(id); const action = enumText(item.action, ACTIONS, `decisions[${index}].action`); const target = optionalText(item.targetCandidateId, `decisions[${index}].targetCandidateId`); if (target !== undefined && !supplied.has(target)) fail('invalid_reference', `targetCandidateId ${target} is unknown`); return { candidateId: id, action, rationale: text(item.rationale, `decisions[${index}].rationale`), ...(target === undefined ? {} : { targetCandidateId: target }), ...(item.conflictingFields === undefined ? {} : { conflictingFields: strings(item.conflictingFields, `decisions[${index}].conflictingFields`) }) } })
  if (seen.size !== supplied.size) fail('reconciliation_invalid', 'exactly one decision is required for every supplied candidate')
  return { decisions: normalized }
}

function claimTemporal(value: unknown, schema: CurationSchemaContext, label: string): RecordValue {
  const temporal = record(value, label)
  exact(temporal, ['asOf', 'scope'], label)
  const scope = record(temporal.scope, `${label}.scope`)
  exact(scope, ['type', 'start', 'end', 'label'], `${label}.scope`)
  return {
    asOf: temporal.asOf === null ? null : text(temporal.asOf, `${label}.asOf`),
    scope: {
      type: enumText(scope.type, schema.claimTemporalScopeTypes, `${label}.scope.type`),
      start: scope.start === null ? null : text(scope.start, `${label}.scope.start`),
      end: scope.end === null ? null : text(scope.end, `${label}.scope.end`),
      label: scope.label === null ? null : text(scope.label, `${label}.scope.label`),
    },
  }
}

function claimStructuredValue(value: unknown, schema: CurationSchemaContext, label: string): RecordValue {
  const structured = record(value, label)
  exact(structured, ['metric', 'value', 'unit', 'comparator'], label)
  if (typeof structured.value !== 'string' && typeof structured.value !== 'number' && typeof structured.value !== 'boolean' && structured.value !== null) fail('invalid_model_output', `${label}.value must be JSON scalar`)
  return {
    metric: text(structured.metric, `${label}.metric`),
    value: structured.value,
    unit: structured.unit === null ? null : text(structured.unit, `${label}.unit`),
    comparator: structured.comparator === null ? null : enumText(structured.comparator, schema.claimComparators, `${label}.comparator`),
  }
}
