import { join, resolve } from 'node:path'
import { hashKnowledgeObject } from '../../knowledge/storage/canonical-hash.ts'
import type { DailyBriefReport, DailyIntelligenceInput, DailyIntelligenceResult, DailyProviderOutcome, DailyResearchSignal, ResearchChangeAssessment } from '../../plugins/daily-intelligence/contracts.ts'
import { FileDailyBriefStore } from '../../plugins/daily-intelligence/brief-store.ts'
import { deduplicateDailySignals, clusterDailySignals, rankDailySignals } from '../../plugins/daily-intelligence/signal-intelligence.ts'
import { DailyIntelligenceSignalEnrichmentSkill } from '../../skills/daily-intelligence/enrichment.ts'
import { DailyBriefSynthesisSkill } from '../../skills/daily-intelligence/synthesis.ts'
import { validateResearchReport, writeResearchReport, type ResearchReport } from '../../app/services/research-report.ts'
import { KnowledgeBaseRegistry } from '../../knowledge/registry/registry.ts'
import { KnowledgeProductionGateway } from '../../knowledge/production/gateway.ts'
import type { NormalizedResearchSource } from '../../plugins/research-acquisition/contracts.ts'
import type { SemanticProductionProposal } from '../../knowledge/production/contracts.ts'

const safeId = /^[A-Za-z0-9][A-Za-z0-9._-]*$/
function abort(signal?: AbortSignal): void { if (signal?.aborted) throw new Error('WORKFLOW_CANCELLED') }
function providerName(plugin: { name: string }): string { return plugin.name.includes('official') ? 'cninfo' : plugin.name.replace(/-research-acquisition$/, '').replace(/^web-research-/, '') }
function outcome(provider: string, status: DailyProviderOutcome['status'], usable: number, diagnostics: string[]): DailyProviderOutcome { return { provider, status, attempted: true, succeeded: status === 'succeeded', empty: status === 'empty', blocked: status === 'blocked', failed: status === 'failed', usable, diagnostics } }

export async function runDailyIntelligence(input: DailyIntelligenceInput): Promise<DailyIntelligenceResult> {
  if (!safeId.test(input.workflowRunId) || !/^\d{4}-\d{2}-\d{2}$/.test(input.tradeDate)) return failure(input, 'failed', ['workflowRunId/tradeDate is invalid'])
  const now = input.now ?? (() => new Date().toISOString()); const asOf = input.asOf ?? now(); const briefStore = new FileDailyBriefStore(input.briefRoot); const logicalId = `daily-${input.briefType}-${input.tradeDate}`; const prior = await briefStore.get(logicalId)
  const calendar = input.calendar ? await input.calendar.isTradingDay(input.tradeDate) : { isTradingDay: true as const, calendarConfidence: input.calendarConfidence ?? 'fallback' as const }
  if (!calendar.isTradingDay) return { ...failure(input, 'completed', ['Non-trading day: acquisition skipped']), providerOutcomes: [], errors: ['Non-trading day: acquisition skipped'] }
  if (prior && !input.forceRefresh) return { workflowRunId: input.workflowRunId, status: 'already_completed', brief: prior, reportPath: join(input.reportRoot, `${logicalId}.md`), signals: [], clusters: [], assessments: [], providerOutcomes: prior.providerOutcomes, proposalCount: 0, committedKnowledgeRefs: prior.committedKnowledgeRefs, reviewCaseCount: prior.reviewCaseCount, errors: [] }
  try {
    const raw: DailyResearchSignal[] = []; const normalizedSources: NormalizedResearchSource[] = []; const outcomes: DailyProviderOutcome[] = []
    for (const plugin of input.providers) { abort(input.signal); const provider = providerName(plugin); const diagnostics: string[] = []; let usable = 0; try { const candidates = await plugin.discover({ company: input.watchlist.companies[0] ?? { symbol: 'WATCHLIST', name: 'watchlist' }, asOf, limitPerKind: 10 }); if (candidates.length === 0) { outcomes.push(outcome(provider, 'empty', 0, ['provider returned no candidates'])); continue } for (const candidate of candidates) { abort(input.signal); try { const fetched = await plugin.fetch(candidate); if (!fetched.content.trim()) { diagnostics.push(`${candidate.candidateId}: empty content`); continue } const normalized = await plugin.normalize(fetched); const symbol = typeof candidate.metadata?.companySymbol === 'string' ? candidate.metadata.companySymbol : undefined; const entityRefs = symbol ? [symbol] : input.watchlist.companies.filter((company) => normalized.title.includes(company.name ?? company.symbol)).map((company) => company.symbol); const kind = candidate.kind === 'official_disclosure' ? 'announcement' : /institution|analyst|broker/i.test(provider) ? 'institutional_view' : /xueqiu|eastmoney|guba|community/i.test(provider) ? 'community' : candidate.kind === 'structured_data' ? 'market' : 'news'; const signal: DailyResearchSignal = { signalId: `signal-${hashKnowledgeObject({ provider, candidateId: candidate.candidateId, contentHash: normalized.contentHash }).slice(7, 27)}`, kind, category: kind === 'announcement' ? 'announcement' : kind === 'institutional_view' ? 'institutional_research' : kind === 'market' ? 'market' : kind === 'community' ? 'community' : 'news', provider, sourceAccountRef: provider, source: candidate, publishedAt: candidate.publishedAt, discoveredAt: now(), entities: entityRefs, themes: [...(candidate.metadata?.focusTags as string[] ?? [])], title: normalized.title, contentRef: normalized.canonicalUrl, contentHash: normalized.contentHash, excerpt: normalized.content.slice(0, 500), relevance: entityRefs.length > 0 ? 1 : 0.35, novelty: 0.5, sentiment: undefined, importance: candidate.tier <= 2 ? 0.9 : 0.5, sourceTier: candidate.tier, rawRef: undefined, clusterKey: normalized.canonicalUrl }; raw.push(signal); usable++ } catch (error) { diagnostics.push(`${candidate.candidateId}: ${error instanceof Error ? error.message : String(error)}`) } } outcomes.push(outcome(provider, usable > 0 ? 'succeeded' : diagnostics.some((item) => /401|403|blocked|captcha/i.test(item)) ? 'blocked' : 'failed', usable, diagnostics)) } catch (error) { const message = error instanceof Error ? error.message : String(error); outcomes.push(outcome(provider, /401|403|captcha|login/i.test(message) ? 'blocked' : 'failed', 0, [message])) } }
    const bounded = raw.slice(0, Math.max(1, Math.min(input.maxSignals ?? 500, 1000))); const deduped = deduplicateDailySignals(bounded); const enrichment = new DailyIntelligenceSignalEnrichmentSkill(); const enriched = deduped.map((signal) => enrichment.enrich(signal, input.watchlist.companies.map((company) => company.symbol), [...input.watchlist.themes, ...input.watchlist.industries]).signal); await input.signalStore.appendMany(enriched); const clusters = clusterDailySignals(enriched); const ranked = rankDailySignals(enriched, asOf, input.topLimit ?? 20)
    const assessments: ResearchChangeAssessment[] = clusters.map((cluster) => ({ clusterId: cluster.clusterId, disposition: cluster.signals.some((signal) => signal.kind === 'announcement') ? 'new' : cluster.signals.some((signal) => signal.kind === 'community') ? 'noise' : 'supports', rationale: `${cluster.title} is a bounded signal cluster with ${cluster.sourceDiversity} source(s).`, relatedKnowledgeRefs: [], durableCandidate: cluster.signals.some((signal) => signal.kind === 'announcement' && signal.sourceTier <= 2) }))
    const synthesis = await new DailyBriefSynthesisSkill().synthesize(input.briefType, ranked, clusters, assessments, input.reasoningExecutor); const evidenceSources = normalizedSources.length ? normalizedSources : enriched.map(signalToNormalizedSource); const knowledge = await projectDailyKnowledge(input, evidenceSources, assessments, clusters); const revision = (prior?.revision ?? 0) + 1; const reportId = logicalId; const brief: DailyBriefReport = { reportId, briefType: input.briefType, tradeDate: input.tradeDate, asOf, timezone: 'Asia/Shanghai', revision, workflowRunId: input.workflowRunId, generatedAt: now(), sections: synthesis.sections, topSignals: ranked, providerOutcomes: outcomes, quality: { ...quality(enriched, deduped, clusters, ranked, synthesis.sections, assessments), claimCount: knowledge.proposalCount, claimWithSourceCount: knowledge.proposalCount, claimWithRawProvenanceCount: 0 }, consensusStatement: 'Consensus unavailable unless explicitly supported by attributable point-in-time public observations; no paid or fabricated consensus is used.', knowledgeBaseRevision: knowledge.revision, committedKnowledgeRefs: knowledge.committedRefs, reviewCaseCount: knowledge.reviewCount, calendarConfidence: calendar.calendarConfidence }
    const report: ResearchReport = { reportId, reportType: 'daily_brief', subjectRefs: ['module:daily-intelligence'], generatedAt: brief.generatedAt, asOf, workflowRunId: input.workflowRunId, knowledgeBaseRevision: 0, sourceRefs: [...new Set(ranked.flatMap((signal) => signal.source.url ? [`source:${signal.signalId}`] : []))], claimRefs: [], methodology: 'Deterministic public-source acquisition, bounded signal deduplication, enrichment, clustering, ranking, and explicit unavailable-gap synthesis.', sections: synthesis.sections.map((section) => ({ id: section.id, title: section.title, markdown: section.items.map((item) => `### ${item.headline}\n\n${item.markdown}`).join('\n\n'), sourceRefs: itemSources(section.items) })) , outputPath: `${reportId}.md` }
    validateResearchReport(report); await writeResearchReport(report, resolve(input.reportRoot)); await briefStore.put(brief); return { workflowRunId: input.workflowRunId, status: 'completed', brief, reportPath: join(resolve(input.reportRoot), `${reportId}.md`), signals: enriched, clusters, assessments, providerOutcomes: outcomes, proposalCount: knowledge.proposalCount, committedKnowledgeRefs: knowledge.committedRefs, reviewCaseCount: knowledge.reviewCount, errors: [] }
  } catch (error) { const message = error instanceof Error ? error.message : String(error); return failure(input, message === 'WORKFLOW_CANCELLED' ? 'cancelled' : 'failed', [message]) }
}
function itemSources(items: readonly { sourceRefs: readonly string[] }[]): readonly string[] { return [...new Set(items.flatMap((item) => item.sourceRefs))] }
function quality(input: readonly DailyResearchSignal[], deduped: readonly DailyResearchSignal[], clusters: readonly unknown[], ranked: readonly DailyResearchSignal[], sections: readonly { items: readonly { sourceRefs: readonly string[] }[] }[], assessments: readonly ResearchChangeAssessment[]) { const items = sections.flatMap((section) => section.items); const sourced = items.filter((item) => item.sourceRefs.length > 0).length; return { inputSignalCount: input.length, dedupSignalCount: deduped.length, clusterCount: clusters.length, rankedCount: ranked.length, topCount: ranked.length, claimCount: 0, claimWithSourceCount: 0, claimWithRawProvenanceCount: 0, sourceCount: new Set(input.map((signal) => signal.source.url ?? signal.signalId)).size, uniqueSourceCount: new Set(input.map((signal) => signal.provider)).size, unsupportedProposalCount: 0, reportItemWithSourceRatio: items.length === 0 ? 0 : sourced / items.length, durableChangeCount: assessments.filter((item) => item.durableCandidate).length, reviewCount: 0 } }
function failure(input: DailyIntelligenceInput, status: DailyIntelligenceResult['status'], errors: readonly string[]): DailyIntelligenceResult { return { workflowRunId: input.workflowRunId, status, signals: [], clusters: [], assessments: [], providerOutcomes: [], proposalCount: 0, committedKnowledgeRefs: [], reviewCaseCount: 0, errors } }

async function projectDailyKnowledge(input: DailyIntelligenceInput, sources: readonly NormalizedResearchSource[], assessments: readonly ResearchChangeAssessment[], clusters: readonly import('../../plugins/daily-intelligence/contracts.ts').DailySignalCluster[]): Promise<{ readonly proposalCount: number; readonly committedRefs: readonly string[]; readonly revision?: number; readonly reviewCount: number }> {
  if (!input.knowledgeBaseRoot || input.watchlist.companies.length === 0) return { proposalCount: 0, committedRefs: [], reviewCount: 0 }
  const company = input.watchlist.companies[0]!; const proposals: SemanticProductionProposal[] = assessments.filter((item) => item.durableCandidate).slice(0, 20).map((item, index) => { const cluster = clusters.find((candidate) => candidate.clusterId === item.clusterId); const sourceCandidateIds = cluster?.signals.filter((signal) => signal.kind === 'announcement' && signal.sourceTier <= 2).map((signal) => signal.source.candidateId) ?? []; const claimType: SemanticProductionProposal['claimType'] = item.disposition === 'risk' ? 'risk' : item.disposition === 'catalyst' ? 'catalyst' : 'viewpoint'; return { proposalId: `daily-knowledge-${index + 1}`, kind: 'claim', subjectKey: 'watchlist-company', claimType, statement: item.rationale, sourceCandidateIds, confidence: 0.5 } })
  if (proposals.length === 0) return { proposalCount: 0, committedRefs: [], reviewCount: 0 }
  const registry = new KnowledgeBaseRegistry(); const handle = await registry.mount(resolve(input.knowledgeBaseRoot)); if (handle.schemaVersion !== '0.4' || handle.storageFormatVersion !== '1') return { proposalCount: 0, committedRefs: [], revision: handle.revision, reviewCount: 0 }; const gateway = new KnowledgeProductionGateway(); await gateway.projectExistingKnowledge(handle, company); const result = await gateway.submit({ handle, producerType: 'daily_intelligence', producerRunId: input.workflowRunId, schemaProfile: { schemaVersion: '0.4', storageFormatVersion: '1', requiresRawProvenance: true }, entity: { localKey: 'watchlist-company', entityType: 'company', name: company.name ?? company.symbol, semanticFields: { ticker: company.symbol, ...(company.exchange ? { exchange: company.exchange } : {}) } }, proposals, evidenceBindings: sources.map((source) => ({ localSourceId: source.candidate.candidateId, source })), asOf: input.asOf, now: input.now }); return { proposalCount: proposals.length, committedRefs: [...result.createdIds, ...result.updatedIds], revision: result.knowledgeBaseRevision, reviewCount: result.resolutionIntents.filter((item) => item.disposition === 'review_required').length }
}

function signalToNormalizedSource(signal: DailyResearchSignal): NormalizedResearchSource { return { candidate: signal.source, retrievedAt: signal.discoveredAt, title: signal.title, content: signal.excerpt ?? signal.title, canonicalUrl: signal.source.url, contentHash: signal.contentHash, publisher: signal.provider, rights: { accessScope: 'public', retentionAllowed: true, aiProcessingAllowed: true, derivativeKnowledgeAllowed: true, redistributionAllowed: false } } }
