import type { ReasoningExecutor, ReasoningRequest } from '../../plugins/reasoning/contracts.ts'
import type { NormalizedResearchSource } from '../../plugins/research-acquisition/contracts.ts'
import { ReasoningExecutorError } from '../../plugins/reasoning/errors.ts'
import { VALUATION_METHODS, VALUATION_SCENARIOS, type DurableValuationEvidenceRole, type ValuationAssumptionPlan, type ValuationBasis, type ValuationComputation, type ValuationMethod, type ValuationScenarioAssumption, type ValuationScenarioId, type ValuationStructuredValue, type ValuationSynthesisOutput, type ValuationSynthesisProposal, type ValuationSynthesisSection } from './contracts.ts'
import { validateScenarioAssumptions } from './financials.ts'

const LOCAL_ID = /^[A-Za-z0-9][A-Za-z0-9._-]*$/
const MAX_REPAIR_OUTPUT_CHARS = 16_000
const MAX_EXISTING_CLAIMS = 40

export interface ValuationAssumptionDesignInput { readonly company: { readonly symbol: string; readonly name?: string; readonly exchange?: string }; readonly valuationDate: string; readonly basis: ValuationBasis; readonly targetFiscalYear: number; readonly eligibleMethods: readonly ValuationMethod[]; readonly referenceMultiples: Readonly<Partial<Record<ValuationMethod, number>>>; readonly existingKnowledge: readonly Record<string, unknown>[]; readonly sources: readonly NormalizedResearchSource[] }
export interface ValuationSynthesisInput extends ValuationAssumptionDesignInput { readonly plan: ValuationAssumptionPlan; readonly computation: ValuationComputation }

export class ValuationSemanticError extends Error {
  readonly diagnostics: readonly string[]
  constructor(message: string, diagnostics: readonly string[] = []) { super(message); this.name = 'ValuationSemanticError'; this.diagnostics = diagnostics }
}

function runtimeModel(executor: ReasoningExecutor | undefined): string | undefined { const value = executor as unknown as { runtimeMetadata?: () => { requestedModel?: string } } | undefined; return typeof value?.runtimeMetadata === 'function' ? value.runtimeMetadata().requestedModel : undefined }
function telemetry(executor: ReasoningExecutor | undefined, operation: 'valuation_assumption_design' | 'valuation_synthesis', values: { readonly validated: boolean; readonly applied: boolean; readonly fallbackUsed: boolean; readonly repairAttempts: number; readonly diagnostic?: string }) { return { called: executor !== undefined, operation, model: runtimeModel(executor), ...values } }
function evidenceRole(source: NormalizedResearchSource): DurableValuationEvidenceRole | undefined {
  const metadata = source.candidate.metadata ?? {}
  const role = metadata.valuationEvidenceRole
  if (role === 'market' || role === 'financial') return role
  if (metadata.dataKind === 'valuation-market') return 'market'
  if (metadata.dataKind === 'valuation-financial') return 'financial'
  return undefined
}
export function deterministicValuationEvidence(sources: readonly NormalizedResearchSource[]): readonly NormalizedResearchSource[] { return sources.filter((source) => evidenceRole(source) !== undefined) }
function sources(input: ValuationAssumptionDesignInput): readonly string[] { return [...new Set(deterministicValuationEvidence(input.sources).map((source) => source.candidate.candidateId))].filter((id) => id.trim() !== '').sort() }
function claims(input: ValuationAssumptionDesignInput): readonly string[] { return [...new Set(input.existingKnowledge.map((item) => typeof item.canonicalRef === 'string' ? item.canonicalRef : '').filter((item) => /^claim:\S+$/.test(item)))].slice(0, MAX_EXISTING_CLAIMS).sort() }
function modelInput(input: ValuationAssumptionDesignInput, repair?: { readonly priorInvalidStructuredOutput: unknown; readonly validatorDiagnostics: readonly string[] }): Record<string, unknown> {
  const value: Record<string, unknown> = { company: input.company, valuationDate: input.valuationDate, basisFiscalYear: input.basis.basisFiscalYear, targetFiscalYear: input.targetFiscalYear, eligibleMethods: input.eligibleMethods, referenceMultiples: input.referenceMultiples, valuationBasis: input.basis, allowedSourceCandidateIds: sources(input), allowedExistingClaimRefs: claims(input), existingKnowledge: input.existingKnowledge.slice(0, MAX_EXISTING_CLAIMS).map((item) => ({ canonicalRef: item.canonicalRef, claimType: item.claimType, statement: typeof item.statement === 'string' ? item.statement.slice(0, 600) : undefined, structuredValue: item.structuredValue })), methodology: 'Code owns valuation data normalization, method eligibility, reference multiples, scenario arithmetic, target prices, implied returns, and sensitivity. Select one eligible primary method and design only Bear/Base/Bull assumptions.' }
  if (repair) value.repair = { attempt: 1, priorInvalidStructuredOutput: boundValue(repair.priorInvalidStructuredOutput), validatorDiagnostics: repair.validatorDiagnostics, allowedMethods: input.eligibleMethods, allowedSourceCandidateIds: sources(input), allowedExistingClaimRefs: claims(input), targetFiscalYear: input.targetFiscalYear, requiredScenarioIds: VALUATION_SCENARIOS }
  return value
}
function designInstruction(repair = false, diagnostics: readonly string[] = []): string { return `${repair ? `Bounded repair attempt 1. Correct these deterministic diagnostics: ${diagnostics.join(', ') || 'valuation_output_invalid'}.` : 'Return one complete candidate.'} Return exactly one JSON object with primaryMethod, secondaryMethods, targetFiscalYear, and scenarios. primaryMethod must be one eligible method. secondaryMethods must be eligible cross-check methods and must not include primaryMethod. scenarios must contain exactly bear, base, and bull, all using the same primaryMethod and targetFiscalYear. Each scenario returns only scenarioId, primaryMethod, targetFiscalYear, growthRate, targetMultiple, rationale, sourceCandidateIds, and existingKnowledgeRefs. growthRate is finite and greater than -1; targetMultiple is finite and greater than 0; bear <= base <= bull for both growthRate and targetMultiple. Copy IDs only from allowed arrays. Do not return targetPrice, impliedReturn, currentMultiple, enterpriseValue, forecastMetric, sensitivity, semanticKey, or arbitrary formulas. Do not use consensus or DCF.` }

export class ValuationAssumptionDesignSkill {
  constructor(private readonly executor?: ReasoningExecutor) {}
  fallback(reason?: string, repairAttempts = 0): { readonly plan?: ValuationAssumptionPlan; readonly reasoning: ReturnType<typeof telemetry> } { return { reasoning: telemetry(this.executor, 'valuation_assumption_design', { validated: false, applied: false, fallbackUsed: true, repairAttempts, ...(reason === undefined ? {} : { diagnostic: reason.slice(0, 300) }) }) } }
  async design(input: ValuationAssumptionDesignInput): Promise<{ readonly plan?: ValuationAssumptionPlan; readonly reasoning: ReturnType<typeof telemetry> }> {
    if (!this.executor) return this.fallback()
    const allowed = { methods: input.eligibleMethods, sourceIds: sources(input), claimRefs: claims(input) }; let repairAttempts = 0; let prior: unknown = null; let diagnostics: readonly string[] = []
    const execute = (repair?: { readonly priorInvalidStructuredOutput: unknown; readonly validatorDiagnostics: readonly string[] }) => this.executor!.execute({ operation: 'valuation_assumption_design', instruction: designInstruction(repair !== undefined, repair?.validatorDiagnostics), input: modelInput(input, repair), outputContract: { type: 'object', required: ['primaryMethod', 'secondaryMethods', 'targetFiscalYear', 'scenarios'], allowedMethods: allowed.methods, allowedSourceCandidateIds: allowed.sourceIds, allowedExistingClaimRefs: allowed.claimRefs, targetFiscalYear: input.targetFiscalYear, requiredScenarioIds: VALUATION_SCENARIOS, forbiddenCalculatedFields: ['targetPrice', 'impliedReturn', 'currentMultiple', 'enterpriseValue', 'forecastMetric'] }, metadata: { operationFamily: 'personal-research-v1', companySymbol: input.company.symbol, targetFiscalYear: String(input.targetFiscalYear) } } satisfies ReasoningRequest)
    try {
      try { const result = await execute(); prior = parseObject(result.output); return { plan: validatePlan(prior, input), reasoning: telemetry(this.executor, 'valuation_assumption_design', { validated: true, applied: true, fallbackUsed: false, repairAttempts }) } } catch (error) { diagnostics = safeDiagnostics(error) }
      repairAttempts = 1; const result = await execute({ priorInvalidStructuredOutput: prior, validatorDiagnostics: diagnostics }); return { plan: validatePlan(parseObject(result.output), input), reasoning: telemetry(this.executor, 'valuation_assumption_design', { validated: true, applied: true, fallbackUsed: false, repairAttempts }) }
    } catch (error) { return this.fallback(safeDiagnostics(error).join('; '), repairAttempts) }
  }
}

function validatePlan(value: unknown, input: ValuationAssumptionDesignInput): ValuationAssumptionPlan {
  const object = parseObject(value); const primaryMethod = object.primaryMethod; const secondaryMethods = strings(object.secondaryMethods); const targetFiscalYear = object.targetFiscalYear; const rawScenarios = arrayOfRecords(object.scenarios)
  if (!isMethod(primaryMethod) || !input.eligibleMethods.includes(primaryMethod)) throw new ValuationSemanticError('primaryMethod is not eligible', ['primary_method_not_eligible'])
  if (!Number.isInteger(targetFiscalYear) || targetFiscalYear !== input.targetFiscalYear) throw new ValuationSemanticError('targetFiscalYear mismatch', ['target_fiscal_year_mismatch'])
  if (secondaryMethods.some((method) => !isMethod(method) || !input.eligibleMethods.includes(method) || method === primaryMethod) || new Set(secondaryMethods).size !== secondaryMethods.length) throw new ValuationSemanticError('secondaryMethods are invalid', ['secondary_methods_invalid'])
  const scenarios: ValuationScenarioAssumption[] = rawScenarios.map((raw, index) => {
    const scenarioId = raw.scenarioId; const method = raw.primaryMethod; const sourceCandidateIds = strings(raw.sourceCandidateIds); const existingKnowledgeRefs = strings(raw.existingKnowledgeRefs); const keys = Object.keys(raw); const forbidden = ['targetPrice', 'impliedReturn', 'impliedUpside', 'currentMultiple', 'enterpriseValue', 'forecastMetric', 'sensitivity', 'semanticKey'].filter((key) => Object.prototype.hasOwnProperty.call(raw, key)); if (forbidden.length) throw new ValuationSemanticError(`Unauthorized calculated fields in scenario ${index}`, [`scenario_${index}_forbidden_${forbidden.join('_')}`]); if (!isScenario(scenarioId) || method !== primaryMethod || !Number.isInteger(raw.targetFiscalYear) || raw.targetFiscalYear !== targetFiscalYear || typeof raw.growthRate !== 'number' || typeof raw.targetMultiple !== 'number' || !Number.isFinite(raw.growthRate) || raw.growthRate <= -1 || !Number.isFinite(raw.targetMultiple) || raw.targetMultiple <= 0 || typeof raw.rationale !== 'string' || raw.rationale.trim() === '' || !Array.isArray(raw.sourceCandidateIds) || sourceCandidateIds.length !== raw.sourceCandidateIds.length || !sourceCandidateIds.every((id) => allowedSource(input, id)) || !Array.isArray(raw.existingKnowledgeRefs) || existingKnowledgeRefs.length !== raw.existingKnowledgeRefs.length || !existingKnowledgeRefs.every((ref) => allowedClaim(input, ref))) throw new ValuationSemanticError(`Invalid scenario at index ${index}`, [`scenario_${index}_keys_${keys.sort().join(',')}`, `scenario_${index}_invalid`]); return { scenarioId, primaryMethod: method as ValuationMethod, targetFiscalYear, growthRate: raw.growthRate, targetMultiple: raw.targetMultiple, rationale: raw.rationale.trim().slice(0, 1_000), sourceCandidateIds, existingKnowledgeRefs }
  })
  const errors = validateScenarioAssumptions({ primaryMethod, targetFiscalYear, scenarios }, input.eligibleMethods, input.basis.basisFiscalYear); if (errors.length) throw new ValuationSemanticError('Scenario plan failed deterministic validation', errors)
  return { primaryMethod: primaryMethod as ValuationMethod, secondaryMethods: secondaryMethods as ValuationMethod[], targetFiscalYear, scenarios }
}

function baseScenario(plan: ValuationAssumptionPlan): ValuationScenarioAssumption {
  const scenario = plan.scenarios.find((item) => item.scenarioId === 'base')
  if (scenario === undefined) throw new ValuationSemanticError('Base scenario is required', ['base_scenario_missing'])
  return scenario
}

export function expectedValuationAssumptionStructuredValue(plan: ValuationAssumptionPlan, assumptionRef: 'base-growth' | 'base-multiple'): ValuationStructuredValue {
  const base = baseScenario(plan)
  const growth = assumptionRef === 'base-growth'
  return { metric: growth ? (plan.primaryMethod === 'PE' ? 'eps_growth' : plan.primaryMethod === 'PB' ? 'bvps_growth' : 'ebitda_growth') : (plan.primaryMethod === 'PE' ? 'target_pe_multiple' : plan.primaryMethod === 'PB' ? 'target_pb_multiple' : 'target_ev_ebitda_multiple'), value: growth ? base.growthRate : base.targetMultiple, unit: growth ? 'ratio' : 'multiple', period: `${plan.targetFiscalYear}-${plan.primaryMethod}`, comparator: 'eq' }
}

export function expectedValuationViewpointStructuredValue(plan: ValuationAssumptionPlan, computation: ValuationComputation, metric: 'target_price' | 'implied_return_pct' | 'reference_multiple'): ValuationStructuredValue {
  const result = computation.scenarios.find((item) => item.scenarioId === 'base')
  if (result === undefined) throw new ValuationSemanticError('Base result is required', ['base_result_missing'])
  if (metric === 'target_price') return { metric, value: result.targetPrice, unit: 'CNY/share', period: `${plan.targetFiscalYear}-${plan.primaryMethod}`, comparator: 'eq' }
  if (metric === 'implied_return_pct') return { metric, value: result.impliedReturnPct, unit: 'percent', period: `${plan.targetFiscalYear}-${plan.primaryMethod}`, comparator: 'eq' }
  const value = computation.referenceMultiples[plan.primaryMethod]
  if (value === undefined) throw new ValuationSemanticError('Reference multiple is unavailable', ['reference_multiple_missing'])
  return { metric, value, unit: 'multiple', period: `${computation.basis.basisFiscalYear}-${plan.primaryMethod}`, comparator: 'eq' }
}

export function validateValuationStructuredValue(value: unknown, expected: ValuationStructuredValue): value is ValuationStructuredValue {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return false
  const record = value as Record<string, unknown>
  if (Object.keys(record).sort().join(',') !== 'comparator,metric,period,unit,value') return false
  return record.metric === expected.metric && record.value === expected.value && record.unit === expected.unit && record.period === expected.period && record.comparator === expected.comparator
}

export function deterministicValuationAssumptionStatement(plan: ValuationAssumptionPlan, scenarioId: ValuationScenarioId): string {
  const scenario = plan.scenarios.find((item) => item.scenarioId === scenarioId)
  if (scenario === undefined) throw new ValuationSemanticError('Scenario is required', ['scenario_missing'])
  return `${scenarioId} ${plan.primaryMethod} FY${plan.targetFiscalYear} assumption: growth rate ${scenario.growthRate} ratio and target multiple ${scenario.targetMultiple} multiple; calculation inputs are code-owned.`
}

const NUMERIC_VALUATION_CLAIM = /(?:\b(?:valuation|target\s*price|implied\s*return|reference\s*multiple|upside|return|price|multiple|base|bear|bull|scenario|case|PE|PB|EV\s*\/\s*EBITDA)\b|估值|目标价|隐含回报|参考倍数|涨幅|回报)[^\n。；;]{0,80}[-+]?\d+(?:\.\d+)?\s*(?:%|倍|x|元|CNY|人民币)?|[-+]?\d+(?:\.\d+)?\s*(?:%|倍|x|元|CNY|人民币)(?:\s*\/\s*(?:share|股))?/iu
export function hasNumericValuationClaim(statement: string): boolean { return NUMERIC_VALUATION_CLAIM.test(statement) }
export function deterministicValuationViewpointStatement(plan: ValuationAssumptionPlan, computation: ValuationComputation): string {
  const result = expectedValuationViewpointStructuredValue(plan, computation, 'target_price'); const returnValue = expectedValuationViewpointStructuredValue(plan, computation, 'implied_return_pct'); const multiple = expectedValuationViewpointStructuredValue(plan, computation, 'reference_multiple')
  return `Base ${plan.primaryMethod} valuation: target price ${result.value} CNY/share, implied return ${returnValue.value}%, reference multiple ${multiple.value}x; deterministic outputs are authoritative.`
}
export function canonicalizeValuationViewpointStatement(statement: string, plan: ValuationAssumptionPlan, computation: ValuationComputation): string {
  const trimmed = statement.trim().slice(0, 1_500)
  return hasNumericValuationClaim(trimmed) ? deterministicValuationViewpointStatement(plan, computation) : trimmed
}

export class ValuationSynthesisSkill {
  constructor(private readonly executor?: ReasoningExecutor) {}
  fallback(reason?: string, repairAttempts = 0): { readonly output: ValuationSynthesisOutput; readonly reasoning: ReturnType<typeof telemetry> } { return { output: { sections: [], proposals: [] }, reasoning: telemetry(this.executor, 'valuation_synthesis', { validated: false, applied: false, fallbackUsed: true, repairAttempts, ...(reason === undefined ? {} : { diagnostic: reason.slice(0, 300) }) }) } }
  async synthesize(input: ValuationSynthesisInput): Promise<{ readonly output: ValuationSynthesisOutput; readonly reasoning: ReturnType<typeof telemetry> }> {
    if (!this.executor) return this.fallback()
    let repairAttempts = 0; let prior: unknown = null; let diagnostics: readonly string[] = []
    const execute = (repair?: { readonly priorInvalidStructuredOutput: unknown; readonly validatorDiagnostics: readonly string[] }) => this.executor!.execute({ operation: 'valuation_synthesis', instruction: `${repair ? `Bounded repair attempt 1. Correct: ${repair.validatorDiagnostics.join(', ') || 'valuation_synthesis_output_invalid'}.` : 'Return a complete synthesis.'} Interpret only supplied deterministic valuation results. Return one JSON object with sections and proposals. sections MUST contain at least one qualitative commentary item with sectionId, non-empty markdown, and all three reference arrays. Every proposal MUST include proposalId, kind:"claim", claimType, subjectKey:"company", statement, sourceCandidateIds, valuationAssumptionRefs, valuationResultRefs, and existingKnowledgeRefs; all four reference fields must be arrays, even when empty. Prefer exactly one viewpoint proposal for this bounded output: it MUST use valuationAssumptionRefs:[] and valuationResultRefs:["result-base"]. If an assumption proposal is returned, it MUST use exactly one valuationAssumptionRefs value, either "base-growth" or "base-multiple", and valuationResultRefs:[]; never put both assumption refs in one proposal and never put assumption refs on a viewpoint. Copy exact allowed IDs only. For a valid Base viewpoint proposal, copy one exact allowedSourceCandidateId, use existingKnowledgeRefs:[], and do not include structuredValue. A valid minimal shape is {"proposalId":"valuation-view","kind":"claim","claimType":"viewpoint","subjectKey":"company","statement":"Bounded interpretation.","sourceCandidateIds":["<copy exact allowed source id>"],"valuationAssumptionRefs":[],"valuationResultRefs":["result-base"],"existingKnowledgeRefs":[]}. proposals may contain at most 3 local claim proposals, only assumption or viewpoint. Do not create numeric calculation values; any structuredValue must exactly equal the supplied deterministic result or base assumption. Include Consensus unavailable and DCF deferred in the report through the application output, not as invented analysis.`, input: synthesisModelInput(input, repair), outputContract: synthesisContract(input), metadata: { operationFamily: 'personal-research-v1', companySymbol: input.company.symbol, targetFiscalYear: String(input.plan.targetFiscalYear) } } satisfies ReasoningRequest)
    try {
      try { const result = await execute(); prior = parseObject(result.output); return { output: validateSynthesis(prior, input), reasoning: telemetry(this.executor, 'valuation_synthesis', { validated: true, applied: true, fallbackUsed: false, repairAttempts }) } } catch (error) { diagnostics = safeDiagnostics(error) }
      repairAttempts = 1; const result = await execute({ priorInvalidStructuredOutput: prior, validatorDiagnostics: diagnostics }); return { output: validateSynthesis(parseObject(result.output), input), reasoning: telemetry(this.executor, 'valuation_synthesis', { validated: true, applied: true, fallbackUsed: false, repairAttempts }) }
    } catch (error) { return this.fallback(safeDiagnostics(error).join('; '), repairAttempts) }
  }
}

function synthesisModelInput(input: ValuationSynthesisInput, repair?: { readonly priorInvalidStructuredOutput: unknown; readonly validatorDiagnostics: readonly string[] }): Record<string, unknown> { const value: Record<string, unknown> = { company: input.company, valuationDate: input.valuationDate, eligibleMethods: input.eligibleMethods, referenceMultiples: input.referenceMultiples, existingKnowledge: input.existingKnowledge.slice(0, MAX_EXISTING_CLAIMS), validatedAssumptionPlan: input.plan, deterministicValuationResults: input.computation.scenarios, deterministicSensitivity: input.computation.sensitivity, allowedValuationResultIds: input.computation.scenarios.map((item) => `result-${item.scenarioId}`), allowedSourceCandidateIds: sources(input), allowedExistingClaimRefs: claims(input) }; if (repair) value.repair = { attempt: 1, priorInvalidStructuredOutput: boundValue(repair.priorInvalidStructuredOutput), validatorDiagnostics: repair.validatorDiagnostics }; return value }
function synthesisContract(input: ValuationSynthesisInput): Record<string, unknown> { return { type: 'object', required: ['sections', 'proposals'], sections: { type: 'array', minItems: 1, item: { sectionId: 'safe id', markdown: 'non-empty string', sourceCandidateIds: sources(input), existingKnowledgeRefs: claims(input), valuationResultRefs: input.computation.scenarios.map((item) => `result-${item.scenarioId}`) } }, proposals: { type: 'array', maxItems: 3, item: { proposalId: 'safe local id', kind: 'claim', subjectKey: 'company', claimType: ['assumption', 'viewpoint'], sourceCandidateIds: sources(input), valuationAssumptionRefs: ['base-growth', 'base-multiple'], valuationResultRefs: ['result-base'], existingKnowledgeRefs: claims(input), structuredValue: 'must exactly match supplied value when present' } } } }
function validateSynthesis(value: unknown, input: ValuationSynthesisInput): ValuationSynthesisOutput { const object = parseObject(value); if (!Array.isArray(object.sections)) throw new ValuationSemanticError('Synthesis sections must be an array', ['synthesis_sections_missing']); if (!Array.isArray(object.proposals)) throw new ValuationSemanticError('Synthesis proposals must be an array', ['synthesis_proposals_missing']); const rawSections = arrayOfRecords(object.sections); const rawProposals = arrayOfRecords(object.proposals); if (rawSections.length !== object.sections.length) throw new ValuationSemanticError('Synthesis sections contain non-objects', ['synthesis_sections_invalid']); if (rawProposals.length !== object.proposals.length) throw new ValuationSemanticError('Synthesis proposals contain non-objects', ['synthesis_proposals_invalid']); if (rawSections.length < 1) throw new ValuationSemanticError('Synthesis requires an interpretive section', ['synthesis_sections_empty']); if (rawProposals.length > 3) throw new ValuationSemanticError('Too many valuation proposals', ['proposal_count_exceeds_three']); const resultIds = new Set(input.computation.scenarios.map((item) => `result-${item.scenarioId}`)); const validSections: ValuationSynthesisSection[] = rawSections.map((raw, index) => { const sourceCandidateIds = strings(raw.sourceCandidateIds); const existingKnowledgeRefs = strings(raw.existingKnowledgeRefs); const valuationResultRefs = strings(raw.valuationResultRefs); if (!validLocalId(raw.sectionId) || typeof raw.markdown !== 'string' || raw.markdown.trim() === '' || !Array.isArray(raw.sourceCandidateIds) || sourceCandidateIds.length !== raw.sourceCandidateIds.length || !sourceCandidateIds.every((id) => allowedSource(input, id)) || !Array.isArray(raw.existingKnowledgeRefs) || existingKnowledgeRefs.length !== raw.existingKnowledgeRefs.length || !existingKnowledgeRefs.every((ref) => allowedClaim(input, ref)) || !Array.isArray(raw.valuationResultRefs) || valuationResultRefs.length !== raw.valuationResultRefs.length || !valuationResultRefs.every((ref) => resultIds.has(ref))) throw new ValuationSemanticError(`Invalid synthesis section ${index}`, [`synthesis_section_${index}_invalid`]); return { sectionId: raw.sectionId, markdown: raw.markdown.trim().slice(0, 2_000), sourceCandidateIds, existingKnowledgeRefs, valuationResultRefs } }); const proposals: ValuationSynthesisProposal[] = rawProposals.map((raw, index) => validateProposal(raw, index, input, resultIds)); return { sections: validSections, proposals } }
function validateProposal(raw: Record<string, unknown>, index: number, input: ValuationSynthesisInput, resultIds: ReadonlySet<string>): ValuationSynthesisProposal {
  const sourceCandidateIds = strings(raw.sourceCandidateIds); const valuationAssumptionRefs = strings(raw.valuationAssumptionRefs); const valuationResultRefs = strings(raw.valuationResultRefs); const existingKnowledgeRefs = strings(raw.existingKnowledgeRefs); const claimType = raw.claimType; const allowedAssumptionRefs = new Set(['base-growth', 'base-multiple'])
  if (!validLocalId(raw.proposalId) || raw.kind !== 'claim' || raw.subjectKey !== 'company' || (claimType !== 'assumption' && claimType !== 'viewpoint') || typeof raw.statement !== 'string' || raw.statement.trim() === '' || !Array.isArray(raw.sourceCandidateIds) || sourceCandidateIds.length === 0 || sourceCandidateIds.length !== raw.sourceCandidateIds.length || !sourceCandidateIds.every((id) => allowedSource(input, id)) || !Array.isArray(raw.valuationAssumptionRefs) || valuationAssumptionRefs.length !== raw.valuationAssumptionRefs.length || !valuationAssumptionRefs.every((ref) => allowedAssumptionRefs.has(ref)) || !Array.isArray(raw.valuationResultRefs) || valuationResultRefs.length !== raw.valuationResultRefs.length || !valuationResultRefs.every((ref) => resultIds.has(ref)) || !Array.isArray(raw.existingKnowledgeRefs) || existingKnowledgeRefs.length !== raw.existingKnowledgeRefs.length || !existingKnowledgeRefs.every((ref) => allowedClaim(input, ref))) throw new ValuationSemanticError(`Invalid valuation proposal ${index}`, [`proposal_${index}_invalid`])
  if (claimType === 'assumption') {
    if (valuationAssumptionRefs.length !== 1) throw new ValuationSemanticError(`Invalid valuation proposal ${index}`, [`proposal_${index}_assumption_ref_count`])
    if (valuationResultRefs.length !== 0) throw new ValuationSemanticError(`Invalid valuation proposal ${index}`, [`proposal_${index}_assumption_result_refs`])
    const baseScenario = input.plan.scenarios.find((item) => item.scenarioId === 'base')
    if (baseScenario === undefined || !sourceCandidateIds.every((id) => baseScenario.sourceCandidateIds.includes(id))) throw new ValuationSemanticError(`Invalid valuation proposal ${index}`, [`proposal_${index}_assumption_source_not_in_base`])
    if (raw.structuredValue !== undefined && !validateValuationStructuredValue(raw.structuredValue, expectedValuationAssumptionStructuredValue(input.plan, valuationAssumptionRefs[0] as 'base-growth' | 'base-multiple'))) throw new ValuationSemanticError(`Invalid valuation proposal ${index}`, [`proposal_${index}_structured_value_mismatch`])
  } else {
    if (valuationAssumptionRefs.length !== 0 || valuationResultRefs.length !== 1 || valuationResultRefs[0] !== 'result-base') throw new ValuationSemanticError(`Invalid valuation proposal ${index}`, [`proposal_${index}_viewpoint_refs`])
    if (raw.structuredValue !== undefined) {
      const metric = raw.structuredValue && typeof raw.structuredValue === 'object' && !Array.isArray(raw.structuredValue) ? (raw.structuredValue as Record<string, unknown>).metric : undefined
      if (metric !== 'target_price' && metric !== 'implied_return_pct' && metric !== 'reference_multiple') throw new ValuationSemanticError(`Invalid valuation proposal ${index}`, [`proposal_${index}_structured_metric`])
      if (!validateValuationStructuredValue(raw.structuredValue, expectedValuationViewpointStructuredValue(input.plan, input.computation, metric))) throw new ValuationSemanticError(`Invalid valuation proposal ${index}`, [`proposal_${index}_structured_value_mismatch`])
    }
  }
  const proposal: ValuationSynthesisProposal = { proposalId: raw.proposalId as string, kind: 'claim', subjectKey: 'company', claimType, statement: (raw.statement as string).trim().slice(0, 1_500), sourceCandidateIds, valuationAssumptionRefs, valuationResultRefs, existingKnowledgeRefs, ...(raw.structuredValue === undefined ? {} : { structuredValue: raw.structuredValue as unknown as Record<string, unknown> }) }
  return proposal
}

function parseObject(value: unknown): Record<string, unknown> { if (typeof value === 'string') { try { return parseObject(JSON.parse(value.trim().replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '')))} catch { throw new ValuationSemanticError('Valuation reasoning returned invalid JSON', ['output_json_invalid']) } } if (!value || typeof value !== 'object' || Array.isArray(value)) throw new ValuationSemanticError('Valuation reasoning must return an object', ['output_object_missing']); const object = value as Record<string, unknown>; for (const wrapper of ['result', 'output', 'data', 'structuredOutput', 'response']) if (object[wrapper] !== undefined) return parseObject(object[wrapper]); return object }
function arrayOfRecords(value: unknown): readonly Record<string, unknown>[] { return Array.isArray(value) ? value.filter((item): item is Record<string, unknown> => Boolean(item) && typeof item === 'object' && !Array.isArray(item)) : [] }
function strings(value: unknown): readonly string[] { return Array.isArray(value) ? value.filter((item): item is string => typeof item === 'string') : [] }
function validLocalId(value: unknown): value is string { return typeof value === 'string' && LOCAL_ID.test(value) }
function isMethod(value: unknown): value is ValuationMethod { return typeof value === 'string' && (VALUATION_METHODS as readonly string[]).includes(value) }
function isScenario(value: unknown): value is ValuationScenarioId { return typeof value === 'string' && (VALUATION_SCENARIOS as readonly string[]).includes(value) }
function allowedSource(input: ValuationAssumptionDesignInput, value: string): boolean { return sources(input).includes(value) }
function allowedClaim(input: ValuationAssumptionDesignInput, value: string): boolean { return claims(input).includes(value) }
function safeDiagnostics(error: unknown): readonly string[] { if (error instanceof ValuationSemanticError && error.diagnostics.length) return error.diagnostics.filter((item) => /^[A-Za-z0-9_.:,?=-]+$/.test(item)).slice(0, 24); if (error instanceof ReasoningExecutorError) return [`executor_${error.code}`]; return ['valuation_reasoning_failed'] }
function boundValue(value: unknown, depth = 0): unknown { if (depth >= 4) return typeof value === 'string' ? value.slice(0, 400) : '[bounded]'; if (typeof value === 'string') return value.slice(0, 1_200); if (typeof value === 'number' || typeof value === 'boolean' || value === null) return value; if (Array.isArray(value)) return value.slice(0, 24).map((item) => boundValue(item, depth + 1)); if (value && typeof value === 'object') { const serialized = Object.entries(value as Record<string, unknown>).slice(0, 32).map(([key, item]) => [key, boundValue(item, depth + 1)]); const result = Object.fromEntries(serialized); return JSON.stringify(result).length <= MAX_REPAIR_OUTPUT_CHARS ? result : { bounded: true, preview: JSON.stringify(result).slice(0, MAX_REPAIR_OUTPUT_CHARS - 80) } } return null }
