import assert from 'node:assert/strict'
import test from 'node:test'
import { KNOWLEDGE_SCHEMA_V04, type KnowledgeClaimV04, type KnowledgeSourceV04 } from '../../knowledge/schema/index.ts'
import { assertKnowledgeV04Objects, validateKnowledgeV04Objects } from '../../knowledge/validation/index.ts'

const source = (id: `source:${string}` = 'source:test'): KnowledgeSourceV04 => ({ id, title: 'Official source', sourceType: 'official_disclosure', provider: 'cninfo', canonicalUrl: 'https://example.com/report', retrievedAt: '2026-09-08T00:00:00.000Z', contentHash: 'a'.repeat(64), rights: { accessScope: 'public', retentionAllowed: true, aiProcessingAllowed: true, derivativeKnowledgeAllowed: true, redistributionAllowed: false }, lifecycle: { status: 'active' } })
const claim = (id: `claim:${string}`, claimType: KnowledgeClaimV04['claimType'], extra: Partial<KnowledgeClaimV04> = {}): KnowledgeClaimV04 => ({ id, claimType, statement: 'A bounded research statement', subjectRefs: ['entity:company-test'], sourceRefs: ['source:test'] as `source:${string}`[], confidence: 0.8, lifecycle: { status: 'active' }, ...extra })

test('Schema 0.4 declares additions without changing v0.3 identity', () => { assert.equal(KNOWLEDGE_SCHEMA_V04.identity.schemaVersion, '0.4'); assert.ok(KNOWLEDGE_SCHEMA_V04.claim.types.includes('thesis')); assert.ok(KNOWLEDGE_SCHEMA_V04.source.fields.includes('rights')) })
test('Schema 0.4 separates forecast probability from confidence', () => { assertKnowledgeV04Objects([source(), claim('claim:forecast', 'forecast', { probability: 0.65 })]); assert.equal(validateKnowledgeV04Objects([source(), claim('claim:forecast', 'forecast')]).status, 'failed'); assert.equal(validateKnowledgeV04Objects([source(), claim('claim:fact', 'fact', { probability: 0.5 })]).status, 'failed') })
test('Schema 0.4 rejects missing, self, and cyclic claim dependencies deterministically', () => { const missing = validateKnowledgeV04Objects([source(), claim('claim:missing', 'fact', { dependsOnClaimRefs: ['claim:nope'] })]); assert.ok(missing.errors.some((error) => error.code === 'V04_MISSING_CLAIM_REF')); const self = validateKnowledgeV04Objects([source(), claim('claim:self', 'fact', { supportsClaimRefs: ['claim:self'] })]); assert.ok(self.errors.some((error) => error.code === 'V04_SELF_REFERENCE')); const a = claim('claim:a', 'fact', { supportsClaimRefs: ['claim:b'] }); const b = claim('claim:b', 'fact', { supportsClaimRefs: ['claim:a'] }); const cycle = validateKnowledgeV04Objects([source(), a, b]); assert.ok(cycle.errors.some((error) => error.code === 'V04_DEPENDENCY_CYCLE')) })
test('Schema 0.4 requires explicit source rights and provenance-shaped metadata', () => { assert.equal(validateKnowledgeV04Objects([{ ...source(), rights: undefined } as unknown as KnowledgeSourceV04]).status, 'failed'); assertKnowledgeV04Objects([source()]) })
